### ISSUE TITLE
Scroll bar

### ISSUE THREAD

**Issue by grahamperrin** [mbnuqw/sidebery#1]
No scroll bar: 

![2018-11-25 05 29 29 sidebery get this extension for firefox en-gb - mozilla firefox](https://user-images.githubusercontent.com/192271/48975888-3c65a600-f073-11e8-8322-e4e8e57fc370.png)

– is that by design? 

It's difficult to use with a trackball.

**Comment by mbnuqw** [comment]
Added support for native scrollbars. Please update addon to version 1.6.0.

**Comment by grahamperrin** [comment]
Smart! Thanks.
