### ISSUE TITLE
Keybindings for expanding/folding selected tabs

### ISSUE THREAD

**Issue by Clyybber** [mbnuqw/sidebery#101]
## Description
Can't really describe it much further than the title already does, but let me take this opportunity to tell you how much I love this addon.. its just amazing.
## Use cases
Not having to use the mouse to fold/expand a tab.

**Comment by mbnuqw** [comment]
You can use "Activate selection" keybinding on the activated tab:
- select folded tab and press "Activate selection" keybinding  (if the tab is not activated)
- press this keybinding again
- voila!

But of course, having independent keybinding is better, so I think I can add one for expanding and one for folding the branch. Any suggestions for default values are welcome.

**Comment by Clyybber** [comment]
Oh, thats nice. Thank you for the quick response. I guess `alt-f` and `alt-e` would be fine? I think it doesn't matter so much as long as they are configurable.

**Comment by mbnuqw** [comment]
Available in the latest version.
