### ISSUE TITLE
Cloned/mirrored live snapshot

### ISSUE THREAD

**Issue by good-nitrogen** [mbnuqw/sidebery#1011]
## Description

I have no idea if this is possible already but essentially the feature would work as follows:

A snapshot including all of your tabs would be synced to your profile. You could then open multiple windows that would all read from a single snapshot profile.
Essentially what it would mean is that you could have two monitors or a split screen or even separate devices and each new window wouldn't need to be a fresh set of tabs/panels etc. That would mean that all of your work would stay unified & synced across all windows/devices.

**Comment by mbnuqw** [comment]
Not possible with Firefox sync server due to [tight limits](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/sync#storage_quotas_for_sync_data).

**Comment by good-nitrogen** [comment]
> Not possible with Firefox sync server due to [tight limits](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/sync#storage_quotas_for_sync_data).

Is it possible to add an unlimited file export with a local folder output? That way you can import/export from a file that doesn't need to be live and synced by Firefox sync

Please advise <3

**Comment by mbnuqw** [comment]
Yes, it's planned feature to auto save snapshots in files. In the next beta version you will be able to manually export/import snapshot to/from a file and next, I will try to add auto export to a file via the Downloads API (and I'll check File System Access API)

**Comment by good-nitrogen** [comment]
Fantastic that's gonna be a lifesaver!
At the moment where is the snapshot data stored?
