### ISSUE TITLE
[FR] Duplicate Tab Shortcut

### ISSUE THREAD

**Issue by megamorphg** [mbnuqw/sidebery#1015]
## Description
Duplicating a tab is an extremely frequent action... yet there's no keyboard shortcut for it. (Microsoft Edge has this currently.)

Can we introduce some sort of keyboard shortcut for this? To duplicate the current tab as the current Right-Click Hold over a tab does. I'd hate to install an add-on just to do that.

For now, I will just make an Autohotkey script to copy the current tab URL, create a sibling tab, paste the URL and press Enter.

**Comment by albino1** [comment]
FWIW, if you CTRL+Drag the tab it duplicates.  You can also CTRL+Click the Reload button.  But yeah, a shortcut to duplicate might be nice to have.

**Comment by mbnuqw** [comment]
Resolved in v5.0.0
