### ISSUE TITLE
[Feature request] "Allow only" urls in panel options

### ISSUE THREAD

**Issue by mju-spyrosoft** [mbnuqw/sidebery#1016]
## Description

Option that would allow only certain url's to be added to sideberry panel. If you open new tab which does not match allow url it would get moved to other (default?) panel. Not sure what user experience of this would be like if panel switched automatically but 🤷 

Using this with "move tabs with matched urls to this panel" would allow easily to create panels dedicated for certain urls.
Right now i can use "move tabs with matches urls to this panel" but if i forget to switch out of panel bunch and open bunch of tabs with different urls my pristine dedicated panel gets "polluted"

**Comment by BloodyRain2k** [comment]
Basically, the functionality for "filtering" urls that is currently tied to containers for panels too. And I'd even go further and say that it'd be nice to have that for Groups as well.

**Comment by mbnuqw** [comment]
@BloodyRain2k, "move rules" for Group pages is tracked in #56

**Comment by mbnuqw** [comment]
Resolved in v5.0.0
