### ISSUE TITLE
Add more icons and colors for panels 

### ISSUE THREAD

**Issue by Riffaells** [mbnuqw/sidebery#1025]
## New features

<details>
<summary>1. Add more icons and colors for panels</summary>

![изображение](https://user-images.githubusercontent.com/63253896/234677610-1e0213d1-df10-47ba-856b-29402390f80a.png)
Or does it only depend on Firefox?
</details>

<details>
<summary>2. Add so that in the context menu when you clicked on the tab there was an option "move to panel..."</summary>

![изображение](https://user-images.githubusercontent.com/63253896/234684506-82904b7d-8512-4d1b-8ef1-e364aa0c4ce3.png)
![изображение](https://user-images.githubusercontent.com/63253896/234681158-aef4a21f-be44-494f-a791-e0b55a345af5.png)
</details>

3. You are simply amazing

**Comment by emvaized** [comment]
"Move to panel" context menu entry is already available in [v5](https://github.com/mbnuqw/sidebery/releases/tag/v5.0.0b33)

**Comment by mbnuqw** [comment]
'Add more icons' - the task is too vague. If you think that there is an icon that can be helpful to a wide range of users, please, open a new feature request.
'more colors' - wontfix. I'd like to keep panel colors in sync with [colors of Firefox containers.](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/contextualIdentities/ContextualIdentity#color)
'Move to panel' - implemented.
