### ISSUE TITLE
Don't activate dropped tabs

### ISSUE THREAD

**Issue by governos** [mbnuqw/sidebery#1026]
Sidebery [v5.0.0b31](https://github.com/mbnuqw/sidebery/releases/tag/v5.0.0b31) on Firefox Nightly 114.0a1.
## Description
Hello.

Currently I'm experiencing that dragging and dropping a selection or group of tabs will shift and activate one tab at a time.
This is disadvantageous when doing panel organizing and moving any significant number of tabs, as now there's `n` tabs loading that I don't want to use at the moment.

I searched the settings by "drag", "activate", "load", "drop", etc… and came up with nothing. So did I read the "Drag and Drop" section. Apologies if this a setting that I missed.

Thank you for your attention and continued development.

**Comment by lc-guy** [comment]
Accidentally got rate-limit banned from a site after dragging a panel which had about a hundred tabs there. Would appreciate this as well :-(

**Comment by mbnuqw** [comment]
To not activate dragged tab, enable "Activate tab on mouse button release" (Sidebery settings > Mouse > Tab actions).
Sidebery also will reload an active tab dropped to panel with configured option "Reopen tab that was dropped to this panel in container: ...".
Other than that, Sidebery should not activate or reload tabs on drag and drop (at least in the latest version).

**Comment by governos** [comment]
Thank you.
