### ISSUE TITLE
Can not upgrade to version 5

### ISSUE THREAD

**Issue by ClausMandal** [mbnuqw/sidebery#1035]
I am trying to upgrade from 4.10.2 to 5.0.0b31 and get this. Tried to press F1 to toggle sidebar, and can see it only get to the first part of several, and then I see below image. Clicking Continue darkens the sidepanel, and waiting a couple of minutes doesn't result in anything. I got more than 3300 tabs spread out over 13 panels.
![snap01](https://github.com/mbnuqw/sidebery/assets/5451310/33083fc2-733a-4341-99d3-2bbc92d8fe84)

**Comment by ghost** [comment]
Uninstall v4 completely, then install v5. You must have exactly **one** tab open, no more.

**Comment by ClausMandal** [comment]
Thanks for answering. When I uninstall v4 won't I still have 3300+ tabs open, which I'll have to close. Should probably close them in v4, instead of in Firefox. Then install v5, then import the exported data from v4? I know it's beta, but can't see why that can't be done as part of the upgrade. Anyway, will v5 have any problems importing my v4 export you think?
