### ISSUE TITLE
Double click and context options from snap shot list

### ISSUE THREAD

**Issue by gotjoshua** [mbnuqw/sidebery#1043]
## Description
Would be great to be able to double click a single url from a small spot to restore it

Context menu to restore groups and single urls from the snapshot viewer to current or new window would also make sense.

**Comment by mbnuqw** [comment]
> Would be great to be able to double click a single url from a small spot to restore it

It's possible in v5. You can long-press (or shift+click) on interested link, this will activate selection mode where you can select other links (or range of links using shift+click) and then click the "Open in current panel" button at the bottom. You can also use drag and drop for individual links (without selection mode). It's not very intuitive UI and will be improved later, maybe will use suggested double-click.

> Context menu to restore groups and single urls from the snapshot viewer to current or new window would also make sense.

I don't plan to override the native context menu in setup(settings) pages, but I can add buttons to open selected links in a new window.

**Comment by gotjoshua** [comment]
> not very intuitive UI

what about starting in selection mode by default (then the long press discovery is not needed) ?

I could offer a PR with double click to open and/or selection mode by default if you like...

**Comment by mbnuqw** [comment]
> what about starting in selection mode by default (then the long press discovery is not needed) ?

Yes, this is the best way.


> I could offer a PR with double click to open and/or selection mode by default if you like...

No need, I'll update the snapshot viewer myself soon. I just checked the git version and found that links are opening on a normal click (it seems there is a bug in the current beta).

**Comment by mbnuqw** [comment]
Resolved in v5.0.0
