### ISSUE TITLE
Tab Selection

### ISSUE THREAD

**Issue by andreyjc** [mbnuqw/sidebery#1056]
Have you considered option for multiple tab selection to do an action on more than one tab at a time. This would be very useful.

Also, to put tabs under another tab does not seem easy to do.

Also, I don't understand this group page and layout of tabs. There seems to be no easy way other than right-click each tab to move to another "panel" (group).

**Comment by albino1** [comment]
> Have you considered option for multiple tab selection to do an action on more than one tab at a time. This would be very useful.

FWIW you can just CTRL+click them like you would with normal horizontal tabs.

**Comment by mbnuqw** [comment]
Multi-selection is possible through:
- Ctrl+Click, Shift+Click
- Keybindings
- Right-click on the favicon of expanded parent tab to select the whole branch
- If you use non-native context menu: Press right mouse button and move cursor to select the range of tabs.
