### ISSUE TITLE
"Recently Closed Tabs" does not follow the general rules for the position of new tabs.

### ISSUE THREAD

**Issue by ongots** [mbnuqw/sidebery#1061]
v5.0.0b31. Возможно это уже исправлено.
Вкладки из панели "Недавно закрытые вкладки" востанавливаются в конец нанели. Хотелось бы чтобы они придерживались: "Позиция новых вкладок / Общее правило".

Релизы выходят редко, может автоматическую сборку замутить? как здесь:
https://github.com/easymodo/qimgv/releases
https://github.com/features/actions

**Comment by mbnuqw** [comment]
Thanks for report! I was in a hurry when implementing the recently-closed-tabs feature, so I used this behavior. Will fix it.

> Релизы выходят редко, может автоматическую сборку замутить?

I thought about that, but sometimes I push WIP features and breaking changes in storage, which requires a careful upgrade from prev version and tests. [https://github.com/easymodo/qimgv](https://github.com/easymodo/qimgv/releases) is using a "workflow_dispatch" event, so it's a manual action. Maybe I'll add something like that to simplify release workflow, but it won't change the release freq. btw, b32 will be soon (most likely this weekend).

**Comment by albino1** [comment]
I wonder if anyone can explain how to get the Recently Closed Tabs panel in the first place?  There's no existing element for it, and I tried adding a new panel and checking the options for it, but there's nothing saying Recently Closed.  I see from the releases that it was added in v5.0.0b30 and I'm currently on v5.0.0b31 so I would think I should be able to find it.

**Comment by mbnuqw** [comment]
@albino1, I didn't implement "Recently Closed Tabs" as a dedicated panel component yet, so it's available only as a "sub-panel" that can be opened from the bottom-bar in tabs-panel:
![2023-06-03-00-18-40](https://github.com/mbnuqw/sidebery/assets/6276694/5ea5262c-a7bc-49bf-b4cf-01fdd288f1b9)

**Comment by albino1** [comment]
Got it, thank you!  For what it's worth, I thought that was a delete/close tab button, but I see now it's more like a recycle bin.  This is a cool feature, thanks for adding it.
