### ISSUE TITLE
Toggle sidebar on hotkey binding?

### ISSUE THREAD

**Issue by mxmilkiib** [mbnuqw/sidebery#1065]
## Description

I found it very handy to toggle the display of TST off and on through the use of F1.

**Comment by mxmilkiib** [comment]
Ah, ctrl-e.

But, bug? Opening the history with ctrl-h, then pressing ctrl-e, doesn't open Sidebery.

The ability to set toggle to F1 would be super handy though.

**Comment by Nionor** [comment]
I'm not sure exactly what you are trying to do but for me it works with F1.
If I press ctrl-h it shows me history and if I then press F1 Sidebery shows up instead. F1 again and it goes away.

I'm on v5.0.0b31

**Comment by mikefirefly** [comment]
This key is configurable in Settings -> Keybindings, in General section.

**Comment by mxmilkiib** [comment]
That's very strange. It was still not bringing it up on ctrl-e after ctrl-h, then I changed it to F1 and that works after ctrl-h, then I changed it back to ctrl-e and it now works after ctrl-h. Idk. Some strange state edgecase? Closing as problem resolved. Thanks for the help!
