### ISSUE TITLE
Feature request: dynamic tab panels

### ISSUE THREAD

**Issue by flexagoon** [mbnuqw/sidebery#1066]
## Description

Currently, you need to manually create panels in order to switch between them. I'd like to have dynamic panels functionality, where panels are automatically created and deleted. For example, if you only have one panel, and you press `Alt+.`, a new panel should be created automatically. Then, when you close all tabs in a panel, it automatically gets deleted.

**Comment by mbnuqw** [comment]
Duplicate of #534 and #265 - all planned after v5 release.
