### ISSUE TITLE
DNS Leaks

### ISSUE THREAD

**Issue by Crehet** [mbnuqw/sidebery#1069]
## Steps to reproduce
1. update firefox to 114
2. create a new container or an already existing one
3. setup your socks5 and port
4. turn on Proxy DNS
5. check your dns leaks on any site of preference

![leaks](https://github.com/mbnuqw/sidebery/assets/119722248/b3b975c2-a53b-4541-839a-fda6e5f07de4)

## Expected behavior
in dns leaks; if using socks5 proxy with Proxy DNS turned on, only the socks5 proxy dns should be shown.

## Actual behavior
in dns leaks; both your socks proxy dns and your ISP/vpn dns are shown.

<details>
<summary><b>OS: linux Firefox: 114.0 Addon: 4.10.2</b></summary>

**Comment by mbnuqw** [comment]
Sidebery doesn't have specific logic to handle DNS requests. It uses [standard proxy API](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/proxy) and [directly sets user settings](https://github.com/mbnuqw/sidebery/blob/5a6f05b7daa4081e10caaf93f6523a9c99219834/src/services/web-req.actions.ts#L151) and [provides them to Firefox](https://github.com/mbnuqw/sidebery/blob/5a6f05b7daa4081e10caaf93f6523a9c99219834/src/services/web-req.actions.ts#L254). Perhaps this is a Firefox issue?
