### ISSUE TITLE
native context menu options don't work

### ISSUE THREAD

**Issue by pointfourone** [mbnuqw/sidebery#107]
## Steps to reproduce
1. enabled native context menu
2. try to discard, pin, or reload an inactive tab and nothing happens

## Expected behavior
The native context menu should work

## Actual behavior
try to discard, pin, or reload an inactive tab and nothing happens

## Environment info

OS:  linux
Firefox version:  71.0
Addon version:  3.11

<details><code>
{
  "settings": {
    "version": "3.1.1",
    "nativeScrollbars": false,
    "ctxMenuNative": true,
    "autoHideCtxMenu": "none",
    "ctxMenuRenderInact": false,
    "navBarInline": true,
    "hideSettingsBtn": false,
    "navBtnCount": true,
    "hideEmptyPanels": true,
    "navMidClickAction": "none",
    "navSwitchPanelsWheel": true,
    "groupLayout": "grid",
    "activateOnMouseUp": false,
    "activateLastTabOnPanelSwitching": true,
    "skipEmptyPanels": false,
    "showTabRmBtn": true,
    "hideInact": false,
    "activateAfterClosing": "next",
    "activateAfterClosingPrevRule": "visible",
    "activateAfterClosingNextRule": "tree",
    "pinnedTabsPosition": "panel",
    "pinnedTabsList": true,
    "tabsTree": true,
    "groupOnOpen": true,
    "tabsTreeLimit": "none",
    "hideFoldedTabs": false,
    "autoFoldTabs": false,
    "autoExpandTabs": true,
    "rmChildTabs": "none",
    "tabsChildCount": true,
    "tabsLvlDots": true,
    "discardFolded": true,
    "discardFoldedDelay": 2,
    "discardFoldedDelayUnit": "min",
    "bookmarksPanel": false,
    "openBookmarkNewTab": true,
    "autoCloseBookmarks": false,
    "autoRemoveOther": false,
    "highlightOpenBookmarks": false,
    "activateOpenBookmarkTab": false,
    "showBookmarkLen": true,
    "fontSize": "xl",
    "bgNoise": true,
    "animations": false,
    "theme": "default",
    "style": "dark",
    "sidebarCSS": false,
    "groupCSS": false,
    "snapInterval": 0,
    "snapIntervalUnit": "min",
    "snapLimit": 0,
    "snapLimitUnit": "snap",
    "hScrollThroughPanels": false,
    "scrollThroughTabs": "none",
    "scrollThroughVisibleTabs": false,
    "scrollThroughTabsExceptOverflow": true,
    "tabDoubleClick": "pin",
    "tabLongLeftClick": "none",
    "tabLongRightClick": "none",
    "tabsPanelLeftClickAction": "none",
    "tabsPanelDoubleClickAction": "tab",
    "tabsPanelRightClickAction": "menu"
  },
  "permissions": {
    "allUrls": false,
    "tabHide": false,
    "actualAllUrls": false,
    "actualTabHide": false
  },
  "storage": {
    "size": "175.9 kb",
    "props": {
      "bookmarksMenu": "162 b",
      "bookmarksPanelMenu": "54 b",
      "expandedBookmarks": "35 b",
      "favAutoCleanTime": "10 b",
      "favUrls": "3.3 kb",
      "favicons": "166.9 kb",
      "panelIndex": "1 b",
      "panels": "2.9 kb",
      "prevTabsTrees": "339 b",
      "settings": "1.4 kb",
      "tabsMenu": "276 b",
      "tabsPanelMenu": "170 b",
      "tabsTrees": "2 b"
    }
  },
  "panels": [
    {
      "cookieStoreId": "bookmarks",
      "icon": "...",
      "name": 9,
      "type": "bookmarks",
      "panel": "BookmarksPanel",
      "lockedPanel": false,
      "bookmarks": true
    },
    {
      "cookieStoreId": "firefox-default",
      "icon": "...",
      "name": 7,
      "type": "default",
      "panel": "TabsPanel",
      "lockedTabs": false,
      "lockedPanel": false,
      "noEmpty": false
    },
    {
      "cookieStoreId": "firefox-container-16",
      "color": "...",
      "icon": "...",
      "name": 11,
      "type": "ctx",
      "panel": "TabsPanel",
      "lockedTabs": false,
      "lockedPanel": false,
      "proxy": null,
      "proxified": false,
      "noEmpty": false,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": ""
    },
    {
      "cookieStoreId": "firefox-container-6",
      "color": "...",
      "icon": "...",
      "name": 16,
      "type": "ctx",
      "panel": "TabsPanel",
      "lockedTabs": false,
      "lockedPanel": false,
      "proxy": null,
      "proxified": false,
      "noEmpty": false,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": ""
    },
    {
      "cookieStoreId": "firefox-container-8",
      "color": "...",
      "icon": "...",
      "name": 4,
      "type": "ctx",
      "panel": "TabsPanel",
      "lockedTabs": false,
      "lockedPanel": false,
      "proxy": null,
      "proxified": false,
      "noEmpty": false,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": ""
    },
    {
      "cookieStoreId": "firefox-container-9",
      "color": "...",
      "icon": "...",
      "name": 12,
      "type": "ctx",
      "panel": "TabsPanel",
      "lockedTabs": false,
      "lockedPanel": false,
      "proxy": null,
      "proxified": false,
      "noEmpty": false,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": ""
    },
    {
      "cookieStoreId": "firefox-container-10",
      "color": "...",
      "icon": "...",
      "name": 4,
      "type": "ctx",
      "panel": "TabsPanel",
      "lockedTabs": false,
      "lockedPanel": false,
      "proxy": null,
      "proxified": false,
      "noEmpty": false,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": ""
    },
    {
      "cookieStoreId": "firefox-container-11",
      "color": "...",
      "icon": "...",
      "name": 6,
      "type": "ctx",
      "panel": "TabsPanel",
      "lockedTabs": false,
      "lockedPanel": false,
      "proxy": null,
      "proxified": false,
      "noEmpty": false,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": ""
    },
    {
      "cookieStoreId": "firefox-container-12",
      "color": "...",
      "icon": "...",
      "name": 5,
      "type": "ctx",
      "panel": "TabsPanel",
      "lockedTabs": false,
      "lockedPanel": false,
      "proxy": null,
      "proxified": false,
      "noEmpty": false,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": ""
    },
    {
      "cookieStoreId": "firefox-container-13",
      "color": "...",
      "icon": "...",
      "name": 15,
      "type": "ctx",
      "panel": "TabsPanel",
      "lockedTabs": false,
      "lockedPanel": false,
      "proxy": null,
      "proxified": false,
      "noEmpty": false,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": ""
    },
    {
      "cookieStoreId": "firefox-container-15",
      "color": "...",
      "icon": "...",
      "name": 8,
      "type": "ctx",
      "panel": "TabsPanel",
      "lockedTabs": false,
      "lockedPanel": false,
      "proxy": null,
      "proxified": false,
      "noEmpty": false,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": ""
    }
  ],
  "cssVars": "TypeError: can't convert undefined to object",
  "windows": [
    {
      "state": "minimized",
      "incognito": false,
      "tabsCount": 26,
      "logs": [
        "[INFO] Settings loaded",
        "[INFO] Containers loaded",
        "[INFO] Tabs loaded",
        "[INFO] Keybindings loaded",
        "[INFO] Tabs menu loaded",
        "[INFO] Tabs panel menu loaded",
        "[INFO] Bookmarks menu loaded",
        "[INFO] Bookmarks panel menu loaded",
        "[INFO] Styles loaded",
        "[INFO] Permissions loaded",
        "[INFO] Favicons loaded"
      ]
    },
    {
      "state": "normal",
      "incognito": false,
      "tabsCount": 53,
      "logs": [
        "[INFO] Settings loaded",
        "[INFO] Containers loaded",
        "[INFO] Tabs order was normalized",
        "[INFO] Tabs loaded",
        "[INFO] Keybindings loaded",
        "[INFO] Tabs menu loaded",
        "[INFO] Tabs panel menu loaded",
        "[INFO] Bookmarks menu loaded",
        "[INFO] Bookmarks panel menu loaded",
        "[INFO] Styles loaded",
        "[INFO] Favicons loaded",
        "[INFO] Permissions loaded"
      ]
    }
  ],
  "tabsMenu": [
    [
      "undoRmTab",
      "mute",
      "reload",
      "bookmark"
    ],
    "separator-1",
    [
      {
        "name": "Move to"
      },
      "moveToNewWin",
      "moveToNewPrivWin",
      "moveToAnotherWin",
      "moveToWin"
    ],
    [
      {
        "name": "Reopen in"
      },
      "moveToCtr"
    ],
    "separator-2",
    "pin",
    "discard",
    "separator-3",
    "group",
    "flatten",
    "separator-4",
    "clearCookies",
    "close"
  ],
  "bookmarksMenu": [
    [
      {
        "name": "Open in"
      },
      "openInNewWin",
      "openInNewPrivWin",
      "openInCtr"
    ],
    "separator-5",
    "createBookmark",
    "createFolder",
    "createSeparator",
    "separator-6",
    "edit",
    "delete"
  ],
  "bookmarks": {
    "bookmarksCount": 2880,
    "foldersCount": 4,
    "separatorsCount": 0,
    "maxDepth": 1
  }
}
</code></details>

**Comment by mbnuqw** [comment]
Thanks for reporting! I think, I can reproduce it.

Is the tab highlighted after clicking on context menu option?
Like this:

![Peek 2019-11-25 19-12](https://user-images.githubusercontent.com/6276694/69547552-9f0bbd80-0fb7-11ea-9292-a9ab160f395d.gif)

**Comment by pointfourone** [comment]
> Is the tab highlighted after clicking on context menu option?
Yes, it is. However, the tab isn't discarded, reloaded or pinned when I try to do it.

**Comment by mbnuqw** [comment]
Closing it. If you still have that issue, please reopen.
