### ISSUE TITLE
tab coloring

### ISSUE THREAD

**Issue by Nalla22** [mbnuqw/sidebery#1075]
Hi, I'm a new Sidebery user, but I don't know how to custom color tabs. Is there a way to color certain tabs?

**Comment by albino1** [comment]
You need to be using beta v5 and not v4 from the addon store:

https://github.com/mbnuqw/sidebery/releases/tag/v5.0.0b31

Then you can right-click on any tab and choose `Set Color`.

In the settings you can also go to Tabs -> Tabs Colorization and fiddle with some options regarding auto-colors based on domain, containers, etc.

Hope this helps.

**Comment by mbnuqw** [comment]
Implemented in the latest version: Context menu options and auto-coloring
