### ISSUE TITLE
"^" for searching in history

### ISSUE THREAD

**Issue by entibo** [mbnuqw/sidebery#1079]
In keyboard layouts that use the caret "^" accent (e.g. french azerty), the caret key doesn't trigger a [keydown "^" event](https://github.com/mbnuqw/sidebery/commit/d2c3e3f85e364a07e6305b5c642a803f2eee6107#diff-448a1422187793a378778ea9705cf058cf47d62c4ab9f83df78fabe145cf2161R64), but instead starts a composition.
The composition can be detected, but not cancelled, making this character a bad fit for this feature.

Note: there is a way to input the "^" character directly using RightAlt, but this is rarely used and in my opinion, other characters such as &%$#@! would work better

**Comment by albino1** [comment]
`^` is the same default as Firefox for searching History from the URL bar.  How does Firefox deal with the issue you're describing?

**Comment by mbnuqw** [comment]
Hm... yeah, it seems like a problem in that use case. I'll make these shortcuts configurable - pass the event further and make it printable as done in Firefox (answering @albino1's question) and/or to use the different key.

**Comment by mbnuqw** [comment]
Fixed in `rc1`
