### ISSUE TITLE
Unable to close tab if duplicated from pinned tab

### ISSUE THREAD

**Issue by Decoy7884** [mbnuqw/sidebery#1080]
## Steps to reproduce
- Have 5 tags pinned
- Tried to duplicate one in a panel
- Click click tried to close, unable to
- Reinstalled extension, same result.
- If duplicated tab moved to a different panel, then it will close.

**Comment by mbnuqw** [comment]
Thanks for the report!

**Comment by Decoy7884** [comment]
My apologizes, I didn't see I had the option ticked to not allow tabs to close.

**Comment by mbnuqw** [comment]
Interesting. It seems I found another bug trying to reproduce this...
Now I see that the bug I found is different, you can close this issue.
