### ISSUE TITLE
Beta (5.0.0b33) Lost all extension data and can't import config on update

### ISSUE THREAD

**Issue by Photo-0ps** [mbnuqw/sidebery#1081]
## Steps to reproduce
Update from beta b31 to b33 via github
Private browser

## Expected behavior
Extension data (settings, css, keybindings, snapshots etc) maintained across versions
Importing config data should work as expected, replacing configuration with those in json

## Actual behavior
Extension basically reset.
Choosing a file to import data works, but clicking import does nothing.

## Debug info

Looks like it's got a new extension id, whereas other beta updates maintined same internal and external extension id. Most likely cause of issue

Attached console output on clicking 'import data'. Seems issue is with panel.moveRules function.
[console-export-2023-6-22_11-52-6.txt](https://github.com/mbnuqw/sidebery/files/11833768/console-export-2023-6-22_11-52-6.txt)

**Comment by mbnuqw** [comment]
Fixed in `rc1`
