### ISSUE TITLE
Search engine for bookmark

### ISSUE THREAD

**Issue by ashrea06** [mbnuqw/sidebery#1082]
## Description
Kindly let me know if there is a search engine function to go through all my bookmarks, if that is not the case, then this would be a plus , an integrated search engine to filter through bookmarks folder as well as bookmarks name. 

Thank you.

**Comment by albino1** [comment]
FWIW, if you're Sidebery v5 you can just add Bookmarks to your Panels and then search it like you would any other panel using the search box at the top.  Also, if you click the sidebar dropdown at the top you can just switch the sidebar to the normal Firefox Bookmarks sidebar and then search that way as well.

**Comment by mbnuqw** [comment]
Implemented in the latest version
