### ISSUE TITLE
single pinned container tabs are not visible

### ISSUE THREAD

**Issue by pointfourone** [mbnuqw/sidebery#109]
## Steps to reproduce
1. set `hide empty panels` to on
2. open a website in a tab in a container
3. pin the container tab with no other container tabs in that window
4. the container panel is no long visible

## Expected behavior
The container panel should be visible so that I can select the pinned tab

## Actual behavior
A pinned container tab isn't visible when no other container tabs are open

## Environment info

OS:  Linux
Firefox version:  71.0
Addon version:  3.1.1

<details><code>
{
  "settings": {
    "version": "3.1.1",
    "nativeScrollbars": false,
    "ctxMenuNative": false,
    "autoHideCtxMenu": "none",
    "ctxMenuRenderInact": false,
    "navBarInline": true,
    "hideSettingsBtn": false,
    "navBtnCount": true,
    "hideEmptyPanels": true,
    "navMidClickAction": "none",
    "navSwitchPanelsWheel": true,
    "groupLayout": "grid",
    "activateOnMouseUp": false,
    "activateLastTabOnPanelSwitching": true,
    "skipEmptyPanels": false,
    "showTabRmBtn": true,
    "hideInact": false,
    "activateAfterClosing": "next",
    "activateAfterClosingPrevRule": "visible",
    "activateAfterClosingNextRule": "tree",
    "pinnedTabsPosition": "panel",
    "pinnedTabsList": true,
    "tabsTree": true,
    "groupOnOpen": true,
    "tabsTreeLimit": "none",
    "hideFoldedTabs": false,
    "autoFoldTabs": false,
    "autoExpandTabs": true,
    "rmChildTabs": "none",
    "tabsChildCount": true,
    "tabsLvlDots": true,
    "discardFolded": true,
    "discardFoldedDelay": 2,
    "discardFoldedDelayUnit": "min",
    "bookmarksPanel": false,
    "openBookmarkNewTab": true,
    "autoCloseBookmarks": false,
    "autoRemoveOther": false,
    "highlightOpenBookmarks": false,
    "activateOpenBookmarkTab": false,
    "showBookmarkLen": true,
    "fontSize": "xl",
    "bgNoise": true,
    "animations": false,
    "theme": "default",
    "style": "dark",
    "sidebarCSS": false,
    "groupCSS": false,
    "snapInterval": 0,
    "snapIntervalUnit": "min",
    "snapLimit": 0,
    "snapLimitUnit": "snap",
    "hScrollThroughPanels": false,
    "scrollThroughTabs": "none",
    "scrollThroughVisibleTabs": false,
    "scrollThroughTabsExceptOverflow": true,
    "tabDoubleClick": "pin",
    "tabLongLeftClick": "none",
    "tabLongRightClick": "none",
    "tabsPanelLeftClickAction": "none",
    "tabsPanelDoubleClickAction": "tab",
    "tabsPanelRightClickAction": "menu"
  },
  "permissions": {
    "allUrls": false,
    "tabHide": false,
    "actualAllUrls": false,
    "actualTabHide": false
  },
  "storage": {
    "size": "273 kb",
    "props": {
      "bookmarksMenu": "162 b",
      "bookmarksPanelMenu": "54 b",
      "expandedBookmarks": "35 b",
      "favAutoCleanTime": "10 b",
      "favUrls": "2.4 kb",
      "favicons": "256.6 kb",
      "lastSnapTime": "13 b",
      "panelIndex": "1 b",
      "panels": "2.9 kb",
      "prevTabsTrees": "1.9 kb",
      "settings": "1.4 kb",
      "snapshots": "2 b",
      "tabsMenu": "276 b",
      "tabsPanelMenu": "170 b",
      "tabsTrees": "6.6 kb"
    }
  },
  "panels": [
    {
      "cookieStoreId": "bookmarks",
      "icon": "...",
      "name": 9,
      "type": "bookmarks",
      "panel": "BookmarksPanel",
      "lockedPanel": false,
      "bookmarks": true
    },
    {
      "cookieStoreId": "firefox-default",
      "icon": "...",
      "name": 7,
      "type": "default",
      "panel": "TabsPanel",
      "lockedTabs": false,
      "lockedPanel": false,
      "noEmpty": false
    },
    {
      "cookieStoreId": "firefox-container-16",
      "color": "...",
      "icon": "...",
      "name": 11,
      "type": "ctx",
      "panel": "TabsPanel",
      "lockedTabs": false,
      "lockedPanel": false,
      "proxy": null,
      "proxified": false,
      "noEmpty": false,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": ""
    },
    {
      "cookieStoreId": "firefox-container-6",
      "color": "...",
      "icon": "...",
      "name": 16,
      "type": "ctx",
      "panel": "TabsPanel",
      "lockedTabs": false,
      "lockedPanel": false,
      "proxy": null,
      "proxified": false,
      "noEmpty": false,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": ""
    },
    {
      "cookieStoreId": "firefox-container-8",
      "color": "...",
      "icon": "...",
      "name": 4,
      "type": "ctx",
      "panel": "TabsPanel",
      "lockedTabs": false,
      "lockedPanel": false,
      "proxy": null,
      "proxified": false,
      "noEmpty": false,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": ""
    },
    {
      "cookieStoreId": "firefox-container-9",
      "color": "...",
      "icon": "...",
      "name": 12,
      "type": "ctx",
      "panel": "TabsPanel",
      "lockedTabs": false,
      "lockedPanel": false,
      "proxy": null,
      "proxified": false,
      "noEmpty": false,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": ""
    },
    {
      "cookieStoreId": "firefox-container-10",
      "color": "...",
      "icon": "...",
      "name": 4,
      "type": "ctx",
      "panel": "TabsPanel",
      "lockedTabs": false,
      "lockedPanel": false,
      "proxy": null,
      "proxified": false,
      "noEmpty": false,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": ""
    },
    {
      "cookieStoreId": "firefox-container-11",
      "color": "...",
      "icon": "...",
      "name": 6,
      "type": "ctx",
      "panel": "TabsPanel",
      "lockedTabs": false,
      "lockedPanel": false,
      "proxy": null,
      "proxified": false,
      "noEmpty": false,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": ""
    },
    {
      "cookieStoreId": "firefox-container-12",
      "color": "...",
      "icon": "...",
      "name": 5,
      "type": "ctx",
      "panel": "TabsPanel",
      "lockedTabs": false,
      "lockedPanel": false,
      "proxy": null,
      "proxified": false,
      "noEmpty": false,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": ""
    },
    {
      "cookieStoreId": "firefox-container-13",
      "color": "...",
      "icon": "...",
      "name": 15,
      "type": "ctx",
      "panel": "TabsPanel",
      "lockedTabs": false,
      "lockedPanel": false,
      "proxy": null,
      "proxified": false,
      "noEmpty": false,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": ""
    },
    {
      "cookieStoreId": "firefox-container-15",
      "color": "...",
      "icon": "...",
      "name": 8,
      "type": "ctx",
      "panel": "TabsPanel",
      "lockedTabs": false,
      "lockedPanel": false,
      "proxy": null,
      "proxified": false,
      "noEmpty": false,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": ""
    }
  ],
  "cssVars": "TypeError: can't convert undefined to object",
  "windows": [
    {
      "state": "minimized",
      "incognito": false,
      "tabsCount": 24,
      "logs": [
        "[INFO] Settings loaded",
        "[INFO] Containers loaded",
        "[INFO] Tabs loaded",
        "[INFO] Keybindings loaded",
        "[INFO] Tabs menu loaded",
        "[INFO] Tabs panel menu loaded",
        "[INFO] Bookmarks menu loaded",
        "[INFO] Bookmarks panel menu loaded",
        "[INFO] Styles loaded",
        "[INFO] Permissions loaded",
        "[INFO] Favicons loaded"
      ]
    },
    {
      "state": "normal",
      "incognito": false,
      "tabsCount": 60,
      "logs": [
        "[INFO] Settings loaded",
        "[INFO] Containers loaded",
        "[INFO] Tabs loaded",
        "[INFO] Keybindings loaded",
        "[INFO] Tabs menu loaded",
        "[INFO] Tabs panel menu loaded",
        "[INFO] Bookmarks menu loaded",
        "[INFO] Bookmarks panel menu loaded",
        "[INFO] Styles loaded",
        "[INFO] Permissions loaded",
        "[INFO] Favicons loaded"
      ]
    }
  ],
  "tabsMenu": [
    [
      "undoRmTab",
      "mute",
      "reload",
      "bookmark"
    ],
    "separator-1",
    [
      {
        "name": "Move to"
      },
      "moveToNewWin",
      "moveToNewPrivWin",
      "moveToAnotherWin",
      "moveToWin"
    ],
    [
      {
        "name": "Reopen in"
      },
      "moveToCtr"
    ],
    "separator-2",
    "pin",
    "discard",
    "separator-3",
    "group",
    "flatten",
    "separator-4",
    "clearCookies",
    "close"
  ],
  "bookmarksMenu": [
    [
      {
        "name": "Open in"
      },
      "openInNewWin",
      "openInNewPrivWin",
      "openInCtr"
    ],
    "separator-5",
    "createBookmark",
    "createFolder",
    "createSeparator",
    "separator-6",
    "edit",
    "delete"
  ],
  "bookmarks": {
    "bookmarksCount": 2880,
    "foldersCount": 4,
    "separatorsCount": 0,
    "maxDepth": 1
  }
}
</code></details>

**Comment by mbnuqw** [comment]
Should be fixed in the latest version.
