### ISSUE TITLE
Pinned tabs no longer in separate hidden/visible panel

### ISSUE THREAD

**Issue by DutchPete** [mbnuqw/sidebery#11]
> OS: linux x86-64  
> Firefox: 65.0.1  
> Extension: 2.0.1  
Today, when I opened Firefox, the separate pin favicon was gone, and my pinned tabs are separated from the non-pinned tabs by a horizontal line in a panel that is no longer hidden when not active. Also, Alt+comma and Alt+fullstop don't work anymore.

**Comment by mbnuqw** [comment]
Sorry, I completely reworked handling of pinned tabs and currently there is no separate panel with them. You can place them in panels filtered by containers (as favicons grid or list with titles) or globally at top/left/right side.

About keybindings - can you try to reset them and restart extension?

**Comment by DutchPete** [comment]
I did that, but I still cannot toggle between the pinned and non-pinned panels.

**Comment by mbnuqw** [comment]
No, this is what I wanted to say - there is no pinned tabs panel anymore. It was my wrong UX decision to place pinned tabs (mixed by containers) in separate panel. Sorry about that.

**Comment by DutchPete** [comment]
Tabs can still be pinned, though they now appear vertically above the non-pinned ones.
I don't understand the reason for this change, previously it was much better.

**Comment by mbnuqw** [comment]
The reason of doing this is that pinned tabs should always be visualized and accessible by user. This is how they work in default Firefox tabs strip. Also there are some quirks in panels logic with separate pinned tabs panel.

Bus maybe you right, I think its possible to add option for returning panel with pinned tabs...

**Comment by DutchPete** [comment]
> ... I think its possible to add option for returning panel with pinned tabs...

I sincerely hope it is possible, I liked the previous structure. I also understand you cannot cater for the preferences of just 1 user, so whatever you decide will have to be accepted.

**Comment by DutchPete** [comment]
What I found yesterday too is that the focus can move away from the panels to an empty space. I think it is when I close a tab. FYI: Sidebery has become too much of a hassle and is a lot less useful for me. So I have removed it from Firefox.
