### ISSUE TITLE
Search when dropping plain text

### ISSUE THREAD

**Issue by mrkishi** [mbnuqw/sidebery#110]
When you drop plain text into native tabs, Firefox redirects it to the default search engine with the text as the query. Similarly, dropping text into blank space opens a new search tab.

I miss this when using sideberry, as it's a quick way to open a new search tab with queries from the current page.

Is there interest in such a feature?

**Comment by mbnuqw** [comment]
Wow! Never knew about this feature. I'll definitely add this, thanks for suggestion!

**Comment by mbnuqw** [comment]
Added in v4.x.x
