### ISSUE TITLE
Option to not unload pinned tabs

### ISSUE THREAD

**Issue by advait404** [mbnuqw/sidebery#1100]
Often, I pin messaging tabs like WhatsApp, teams, element etc. which I never want to unload. However, when right-clicking and selecting unload tabs, it unloads all but one of the pinned tab. An option to ignore pinned tabs when unloading would be very useful. The extension [Auto Tab Discard](https://addons.mozilla.org/en-US/firefox/addon/auto-tab-discard/) has a feature like this.

**Comment by mbnuqw** [comment]
Resolved in v5.0.0
