### ISSUE TITLE
Hide panel when there is only one tab

### ISSUE THREAD

**Issue by noscript** [mbnuqw/sidebery#1101]
## Description
It would be great if the panel would hide automatically when there is only one tab. For example when moving tab to a new separate window, the new window has only one tab and the panel takes a lot of useful vertical space.

![image](https://github.com/mbnuqw/sidebery/assets/717109/df072838-affa-4ba2-834b-a48203e1b402)

**Comment by mbnuqw** [comment]
It's impossible to implement. Related issues: #685, #405
