### ISSUE TITLE
Moving tabs to another panel via the context menu is broken

### ISSUE THREAD

**Issue by ongots** [mbnuqw/sidebery#1105]
v5.0.0rc2

## Steps to reproduce
- Select multiple tabs
- In the context menu, select: move > to another panel

## Expected behavior
Tabs will move

## Actual behavior
One tab is moved. The rest remain in place, there is no [data-selected] when they are selected.
Sometimes moving works correctly.

**Comment by mbnuqw** [comment]
Should be fixed in `rc3`
