### ISSUE TITLE
Make middle-clicking on Bookmark Folders consistent with vanilla Bookmark Folders

### ISSUE THREAD

**Issue by Squaredude** [mbnuqw/sidebery#1107]
## Description

In the vanilla toolbar/sidebar of Bookmarks, if you have several bookmarks in a folder, middle-clicking on said folder opens all the bookmarks in new tabs.

However, for the Sidebery Bookmark panel, middle-clicking on a bookmark folder does nothing.

It would be a good idea to make the behavior consistent by allowing opening multiple bookmarks in new tabs by middle-clicking on a bookmark folder in Sidebery.

**Comment by mbnuqw** [comment]
Available since v5.0.0
