### ISSUE TITLE
Sort by Group and Group title color/font

### ISSUE THREAD

**Issue by rjameson3** [mbnuqw/sidebery#1108]
## Description
My tab's list has grown quite large, would be a nice feature to be able to sort by GROUP, so all my groups can be at the top of a long list of tabs as I organize the view.

Also, did not see a style for Group names where I can change the color/font and specifics of a group title.  That also would be nice.

**Comment by stw203** [comment]
I second this! Thanks! :-)

**Comment by mbnuqw** [comment]
Sorting was implemented in v5.2.0 with an option "Sort groups before other tabs"
