### ISSUE TITLE
Moving tab bellow group

### ISSUE THREAD

**Issue by robyerts** [mbnuqw/sidebery#1110]
## Steps to reproduce
drag a tab just bellow the group

## Expected behavior
- tab moves out of group, just bellow the group

## Actual behavior
sometimes it moves, sometimes it doesn't do anything. the blue line kinda indicates that, but you have to pay close attention if the blue line goes all the way to the left. If it doesn't, the tab doesn't move at all. 

tab moves out of group:
![tabMoves](https://github.com/mbnuqw/sidebery/assets/19748460/260b0f50-316f-44b0-af4a-9ad83766f088)

tab doesn't move:
the blue background is present at random
![tabDoesntMove](https://github.com/mbnuqw/sidebery/assets/19748460/7e2064cb-4f57-4b8c-b197-9aaca9e36de7)

version: Firefox: 115.0.2
Addon: 4.10.2

I suggest to have the blue line appear only when a tab is going to be moved out of group and increase the drag and drop range for moving the tab

**Comment by mbnuqw** [comment]
Can't reproduce in v5. Please, reopen if issue is reproduced in the latest version of Sidebery.
