### ISSUE TITLE
How to open side bar in addon screenshot?

### ISSUE THREAD

**Issue by slrgt** [mbnuqw/sidebery#1113]
I can't find a button or option to open the sidebar next to the vertical tabs thats shown in the addon screenshots.

![waterfox_gawXfaOTEa](https://github.com/mbnuqw/sidebery/assets/114287507/5b886022-5362-425d-b4a2-d7311fbf30c8)

**Comment by albino1** [comment]
I think what you're looking for is:

Settings -> Navigation Bar -> Layout -> Vertical

**Comment by slrgt** [comment]
im looking to have bookmarks on the side

**Comment by emvaized** [comment]
@slrgt 
These are probably not bookmarks, but panels – one of them has a Twitter icon, so you probably mistook it as a bookmark. On top of the panel are pinned tabs (Todoist and Google Translate)

**Comment by mbnuqw** [comment]
Answered by @albino1 and @emvaized
