### ISSUE TITLE
Can Sidebery become compatible with Side View?

### ISSUE THREAD

**Issue by slrgt** [mbnuqw/sidebery#1115]
[Sideview ](https://addons.mozilla.org/en-US/firefox/addon/side-view/) is a great addon that allow you to have a tab on the side similar to how the [Pulse Browser ](https://pulsebrowser.app) allows. It would be great for Sidebery to be compatible with it because currently Sidebery covers the Sideview tab. Pulse Browser includes Sidebery by default but includes tweaks to allow it to work with a side tab as well

**Comment by emvaized** [comment]
It seems to me Sideview uses the same sidebar area to show a tab as Sidebery. And Firefox doesn't allow to have two sidebars simultaniosly right now (there's a [feature request](https://connect.mozilla.org/t5/ideas/2nd-sidebar/idi-p/4968) about it). 
So you either show Sidebery panel in the sidebar, or a Sideview panel — no way to show them both, as they occupy the same sidebar area. And the whole sidebar area must be dedicated for a single extension at one time, it's the way sidebar works in Firefox.

Pulse Browser doesn't include tweaks for Sidebery to work with another extension's sidebar, and it doesn't include Sidebery by default either. It uses browser's default tab bar, but modifies it to be displayed vertically on the side of the screen (there's another [feature request](https://connect.mozilla.org/t5/ideas/native-vertical-tabs/idi-p/85) to implement it in Firefox as well). 
So, these are not Sidebery tabs, and don't support its unique features. If you try to install Sidebery in the Pulse Browser, you'll notice it behaves exactly the same as in Firefox — you can show either Sidebery or Sideview in sidebar area. 

---

By the way, if you just want to view tab on the side while having Sidebery open, you can simply open this tab in new browser window and align it side-by-side like this: 
![FINAL_1-Snap-Assist](https://github.com/mbnuqw/sidebery/assets/37851576/51e65cd2-9c5e-4126-ba48-8677813b1a34)

**Comment by mbnuqw** [comment]
As @emvaized already answered, it's impossible to implement.
