### ISSUE TITLE
Import , then apply snapshots on diff pc - groups lost info in page body

### ISSUE THREAD

**Issue by rjameson3** [mbnuqw/sidebery#1117]
I had some issues with importing  - I exported from my main PC to file, then imported on a new.   I then applied a snapshot in that import and the Group info went missing in the browser window - it is blank.    I cannot rename it as it shows nothing.  On the left tree, I see the group and the pages in that group.

Because I export/import to a new PC - does it break the link to a profile perhaps?

**Comment by mbnuqw** [comment]
`Because I export/import to a new PC - does it break the link to a profile perhaps?`
Yes, it seems, sidebery didn't detect these group pages and didn't update their urls to match the new profile.

**Comment by mbnuqw** [comment]
Should be fixed in v5.0.0. Feel free to reopen if not.

**Comment by rjameson3** [comment]
Awesome – I will give it a test.  Thanks.

Regards,

Ron Jameson
