### ISSUE TITLE
Navigation bar tab count font size?

### ISSUE THREAD

**Issue by mxmilkiib** [mbnuqw/sidebery#1120]
## Steps to reproduce

I'm trying to reduce the navigation bar panel count font size, but I'm not sure if that's possible?

I've tried all the style font configuration fields but haven't been able to affect it.

They're just a bit too for me big as they stand.

![image](https://github.com/mbnuqw/sidebery/assets/108225/bd442553-1fd6-4bbb-9d33-544a34d610eb)

**Comment by ongots** [comment]
Original style:
```
.NavigationBar .nav-item .len {
    position: absolute;
    top: var(--nav-btn-len-margin);
    right: var(--nav-btn-len-margin);
    font-size: 0.5625rem;
    font-weight: 500;
    padding: 0 2px;
    color: var(--nav-btn-fg);
    text-shadow: 0 0 2px var(--toolbar-bg), 0 0 2px var(--toolbar-bg), 0 0 3px var(--toolbar-bg), 0 0 3px var(--toolbar-bg);
    border-radius: 4px;
    transform: translateZ(0);
}
```
Paste into the style editor, and edit

**Comment by mxmilkiib** [comment]
Thank you. I just tried that, but I'm not seeing a change. Might I be doing something wrong?

![image](https://github.com/mbnuqw/sidebery/assets/108225/29bc2472-833e-43b5-bdb5-9464ec73b3a0)

**Comment by ongots** [comment]
Try adding !important
```
.NavigationBar .nav-item .len {
    font-size: 8px !important;
}
```

**Comment by mxmilkiib** [comment]
Cheers :)

Hmm, I realise now that it's not going smaller than 12px, with or without !important.

**Comment by mxmilkiib** [comment]
Aaah got it, it was the browser font config setting for a minimum font size. I thought this would only apply to pages! Thanks anyway.
