### ISSUE TITLE
Auto-collapsed sidebar

### ISSUE THREAD

**Issue by erzaki** [mbnuqw/sidebery#1124]
## Description
Greetings fellow. 
I was using microsoft edge on windows before. It have vertical tabs option that auto-collapsed sidebar and show me only the icon of websites that i opened. To show the page name, can be done with just hover my cursor into the sidebar. Thats amazing feature and that way, the sidebar didn't  show me the smaller view whenever i opened the page. Recently i am using linux OS and here firefox is the best browser i found. I tried another firefox extension to make vertical tabs like i was using before, but that extension is too didn't have auto-collapsing like edge's. There are tutorials i found in internet to make your own css code to make auto-collapsed feature on the extension, but it was heavy and made firefox slow, so i am uninstalled it. Yesterday i found sideberry, this extension is fast. Is there already auto-collapsed sidebar features in sideberry? I think sideberry would be great with auto-collapsed sidebar feature. 
Thank you in advances and sorry for my bad english.

**Comment by ongots** [comment]
https://github.com/ongots/pseudo-fullscreen-firefox
https://firefoxcss-store.github.io/
https://www.reddit.com/r/FirefoxCSS/

**Comment by firai** [comment]
Firefox doesn't allow extensions to hack the UI that way, so the best/only way is to use legacy CSS style sheets

**Comment by Nionor** [comment]
With the following code in userChrome.css you can make the sidebar collapse like this.
![sidebery](https://github.com/mbnuqw/sidebery/assets/36626165/93172d32-603a-417c-85a5-22de76f828ec)

```
#sidebar-header {
  display: none !important;
}

*#sidebar-box + #sidebar-splitter {
  display: none !important;
}

#sidebar-box #sidebar-header {
  visibility: collapse;
}


#sidebar-box {
  overflow: hidden !important;
  position: relative !important;
  transition: all 500ms !important;
  transition-timing-function: ease-in;
  min-width: var(--thin-tab-width) !important;
  max-width: var(--thin-tab-width) !important;
  z-index: 1;
}
#sidebar-box:hover,
#sidebar-box #sidebar {
  transition: all 200ms !important;
  transition-timing-function: ease-out;
  min-width: var(--wide-tab-width) !important;
  max-width: var(--wide-tab-width) !important;
  margin-right: calc((var(--wide-tab-width) - var(--thin-tab-width)) * -1) !important;
  z-index: 1;
}

:root { --thin-tab-width: 34px; }
:root { --wide-tab-width: 300px; }
```
Not exactly what you are looking for but maybe you can work around it.

**Comment by erzaki** [comment]
Thanks all. I have zero knowledge in CSS, but your advices definitely helps me :)
