### ISSUE TITLE
Address bar + back/forward history, refresh buttons 

### ISSUE THREAD

**Issue by MotherOfClamperl** [mbnuqw/sidebery#1127]
Brilliant extension, it's saved me from using Arc using w/ custom css to reclaim all the vertical space (with the address bar auto revealing when you put your mouse near the top). It's flawless, but it does make messing around with links more of a hassle, so I was wondering if there's any plans to add a address bar + buttons like they have in the arc sidebar?

<details>
  <summary>for reference:</summary>
  
![image](https://github.com/mbnuqw/sidebery/assets/107922209/1ac20985-8eae-4f71-ae54-353ff1d969d2)

</details>

**Comment by emvaized** [comment]
You probably better use userChrome browser modifications to achieve this as well, for example [ArcFox](https://github.com/use-arcfox/arcfox) project

**Comment by yotamguttman** [comment]
so you're not interested in supporting this feature I gather?

**Comment by mbnuqw** [comment]
It would take a lot of time to implement something like this, and I'm not interested in maintaining this feature.
