### ISSUE TITLE
Allow Panels to Group by name instead of Container

### ISSUE THREAD

**Issue by mustaqimM** [mbnuqw/sidebery#113]
## Description
I wish for the tabs to be grouped by a common name 

## Use cases

For example a Work Group has all tabs related to work and each tab opens as usual in it's own container: I open a github link in the work container and it is opened in a container because of it's url. I couldn't use sidebery in it's current form as I don't group tabs by container but rather by a common tag as it were. So the top panel is used to switch between Tag names rather than containers.

Thanks for this awesome project!

**Comment by mbnuqw** [comment]
Yeah, I'm currently working on a new version in which you will be able to create panels without strong binding to some container and configure containers and panels separately. As a result, you will also be able to place tabs of different containers in the same panel (#83). 

Some examples:
- Container config
![screenshot-2019-12-06 19:51:35](https://user-images.githubusercontent.com/6276694/70331805-15cf7300-1862-11ea-9e2b-f7f4d5ea4691.png)

- Panel config
![screenshot-2019-12-06 19:53:07](https://user-images.githubusercontent.com/6276694/70331868-33044180-1862-11ea-94f9-90be8d715624.png)

- Sidebar
![screenshot-2019-12-06 19:58:09](https://user-images.githubusercontent.com/6276694/70332154-c6d60d80-1862-11ea-9351-23e3eef2fad4.png)

**Comment by Mrfiregem** [comment]
My problem seems to be related to changes for this issue; opening a bookmark in a new tab no longer puts it in the default group, instead moving it to the next available group, even though the container doesn't match

**Comment by mbnuqw** [comment]
@Mrfiregem, You can try to set up options in section "New tab position". Previously sidebery automatically sort tabs by containers and place new tabs to the end of panels. Right now this behavior is optional, but anyway, sorry, this is my fault to not to provide sensible defaults for users of previous version.

**Comment by Mrfiregem** [comment]
Thanks for pointing me in the right direction, I think I got it set up now

**Comment by mustaqimM** [comment]
Hey there, I think this issue can now be closed as it's been implemented

Thanks so much for this feature

**Comment by mbnuqw** [comment]
Yep, closing it.
