### ISSUE TITLE
[V5] no seperated color scheme for each window. Cycling through all windows if each window has different theme color

### ISSUE THREAD

**Issue by SunnyZebra** [mbnuqw/sidebery#1134]
## Steps to reproduce
- Open Firefox in [new profile](https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles)
- Install Sidebery
- Install [Adaptive Tab Bar Color](https://addons.mozilla.org/firefox/addon/adaptive-tab-bar-color/)
- Set Sidebery color scheme to Firefox
- Have multiple windows open

## Expected behavior
Keep color scheme of each window and update each window only on theme (-moz-dialog?) color update of each window.

## Actual behavior
ColorScheme cycling through all windows until it settles on the current active window. On tab/window change color cycling through all windows again.
Sidebery can currently [v5.0.0rc4] not have separated different theme colors for each window at the same time.
Simple Auto:Dark/Light not (visibly?) cycling through all window colors again.

## Debug info

<details>
<summary><b>Addon data</b></summary>
     
```json
To get addon data: 
- Go to the Sidebery settings page - section "Help"
- Click on the "Debug info" button
- Copy and paste here inside this codeblock, replacing this text.
Note: all URLs, titles and other personal info are skipped.
```
</details>

<details>
<summary><b>Logs</b></summary>

```
To get logs: 
- Open DevTools (open this url in new tab: about:devtools-toolbox?id=%7B3c078156-979c-498b-8990-85f7987dd929%7D&type=extension).
- Navigate to "console" tab.
- Click on the trash bin icon (at the top-left) to clear console.
- Then try to reproduce the issue.
- If messages appear, copy and paste them here inside this codeblock, replacing this text.
```
</details>

**Comment by emvaized** [comment]
Did you tried changing Sidebery color scheme to "firefox", as it was suggested [here](https://github.com/easonwong-de/Adaptive-Tab-Bar-Color/issues/36#issuecomment-1473236469)?

**Comment by SunnyZebra** [comment]
Highlevel nagging since it uses an additional addon Adaptive Tab Bar Color to dynamically change window theme color.

Setting color scheme to firefox already done. The other settings with constant window color are working fine. If there is only dark, light or constant custom theme there is no issue since windows are not changing theme colors.

Here example image how it looks for me. It is getting the right color, but it is changing all windows to the current focused window theme. Each color change forces a cycling through all windows.

Left window in focus
![Screenshot 2023-07-28 134032](https://github.com/mbnuqw/sidebery/assets/140318690/e8aacce5-22b3-4886-ba88-d9d950a087c5)

Right window in focus
![Screenshot 2023-07-28 134055](https://github.com/mbnuqw/sidebery/assets/140318690/b86c86d8-79e1-4b76-8384-c05a8bf71b6b)

From that behavior i assume that there is only one global variable to use the current theme color instead of a variable for each window. Somehow the script needs to cycle each window again to get the current window color.  
For now i'll just keep it in the dark mode setting.
