### ISSUE TITLE
Links opened from pinned tabs opens in the last created panel instead on active panel.

### ISSUE THREAD

**Issue by chinook77** [mbnuqw/sidebery#1135]
## Steps to reproduce
- Open Firefox in [new profile](https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles)
- Install Sidebery

## Expected behavior
Open links in the actual/default panel.

## Actual behavior
Links are opened in the last created panel.

## Debug info

<details>
<summary><b>Addon data</b></summary>
     
```json
To get addon data: 
- Go to the Sidebery settings page - section "Help"
- Click on the "Debug info" button
- Copy and paste here inside this codeblock, replacing this text.
Note: all URLs, titles and other personal info are skipped.
```
</details>

<details>
<summary><b>Logs</b></summary>

```
To get logs: 
- Open DevTools (open this url in new tab: about:devtools-toolbox?id=%7B3c078156-979c-498b-8990-85f7987dd929%7D&type=extension).
- Navigate to "console" tab.
- Click on the trash bin icon (at the top-left) to clear console.
- Then try to reproduce the issue.
- If messages appear, copy and paste them here inside this codeblock, replacing this text.
```
</details>

**Comment by albino1** [comment]
What version of Sidebery?

**Comment by chinook77** [comment]
Sorry I didn't mention, 

FF 115.0.3
Stable (4.10.2) and Beta (v5.0.0rc4).

It happens on both versions.

**Comment by mbnuqw** [comment]
Cannot reproduce. As one of the possible reason - it might be some enabled addon that handles a new tab position. Please, provide Sidebery debug info
>To get addon data: 
>- Go to the Sidebery settings page - section "Help"
>- Click on the "Debug info" button
>- Copy and paste here inside this codeblock, replacing this text.
>Note: all URLs, titles and other personal info are skipped.

**Comment by chinook77** [comment]
_"As one of the possible reason - it might be some enabled addon that handles a new tab position. "_

Sorry, my bad. This was the culprit.

![Screenshot 2023-07-29 192453](https://github.com/mbnuqw/sidebery/assets/19517348/187e2740-28e5-4165-8c82-1cf3af89edc2)
