### ISSUE TITLE
User experience improvement suggestion when using the search functionality and switching between panels

### ISSUE THREAD

**Issue by ericpa06** [mbnuqw/sidebery#1142]
When searching something on the history/bookmarks panel, and then switching back to common panels, consider having an option that resets your search term.

Sometimes you just searched something on these special panels _(like middle clicking some links on the history panel)_ and then you switch back to the normal panels, but the search terms you used is still active, which might be a little annoying for some users, depending your user workflow, like maybe you just hope seeing your normal panel again.

I thought more precisely when switching between the history/bookmarks panels to normal panels, but I guess, there could there also be an option that just reset the search term when switching between any panels.  I don't know, maybe both.

Anyway, I hope I described my suggestion well enough.

Also thank you very much for your extension. it's so good that Mozilla should implement it natively in the browser in my opinion  :)

**Comment by mbnuqw** [comment]
Resolved in v5.0.0
