### ISSUE TITLE
cannot open about: and chrome: bookmarks 

### ISSUE THREAD

**Issue by whudwl** [mbnuqw/sidebery#115]
## Steps to reproduce
for instance: 

about:downloads 
chrome://browser/content/places/places.xul

## Expected behavior
Can open these types of bookmarks. 

## Actual behavior
Nothing happens when clicking on suck bookmarks.

**Comment by mbnuqw** [comment]
Right now opening bookmarks with such urls will lead to creating placeholder page with target url and button for copying it. Unfortunately, this is the only thing I can do.

**Comment by whudwl** [comment]
> 
> 
> Right now opening bookmarks with such urls will lead to creating placeholder page with target url and button for copying it. Unfortunately, this is the only thing I can do.

Thank you for making this change.
