### ISSUE TITLE
Pull request for the wiki

### ISSUE THREAD

**Issue by Fletcher-Alderton** [mbnuqw/sidebery#1151]
I have added a guide to the Wiki on how to use the Firefox GNOME theme with a hidden Tabs bar, addressing issues with the close button disappearance and unsightly square edges. As well as making it more comprehensive.

How do i make a pull request for the wiki

**Comment by robbyph** [comment]
Looks like there isn't native support for pull requests for the wiki in Github, however, some folks have found a few workarounds

https://stackoverflow.com/questions/10642928/how-can-i-make-a-pull-request-for-a-wiki-page-on-github

**Comment by Fletcher-Alderton** [comment]
Awesome thanks for the info, here is my updated wiki if you would like to merge: https://github.com/Fletcher-Alderton/sidebery/wiki.

This seems like the easiest way to do it

# Merge Wiki Changes From A Forked GitHub Repo
 
This is inspired (or basically copied) from [How To Merge GitHub Wiki Changes From One Repository To Another](http://roman-ivanov.blogspot.com/2013/11/how-to-merge-github-wiki-changes-from.html), by Roman Ivanov, and serves to ensure that should something happen to the original article, the information remains nice and safe here.

 ### Terminology

 **OREPO**: original repo - the repo created or maintained by the owner
  
 **FREPO**: the forked repo that presumably has updates to its wiki, not yet on the **OREPO**

 ## Contributing
 
Should you want to contribute to the wiki of a repo you have forked, do the following:
 
- fork the repo
- clone only the wiki to your machine: `$ g clone [FREPO].wiki.git`
 - make changes to your local forked wiki repo
 - push your changes to GitHub
 
 Once you are ready to let the author know you have changes, do the following:
 
 - open an issue on **OREPO**
 - provide a direct link to your wiki's git repo for ease of merging: i.e. [**FREPO**].wiki.git
 
 ## Merging Changes
 
 As the owner of **OREPO**, you have now received a message that there are updates to your wiki on someone else's **FREPO**.
 
 If wiki changes are forked from latest **OREPO** wiki, you may do the following:
 
 ```bash
 $ git clone [OREPO].wiki.git
 $ cd [OREPO].wiki.git
 
 # squashing all FREPO changes
 $ git pull [FREPO].wiki.git master
 
 $ git push origin master
 ```
 
 If **OREPO** wiki is ahead of where **FREPO** forked from, do the following:
 
 ```bash
 $ git clone [OREPO].wiki.git
 $ cd [OREPO].wiki.git
 $ git fetch [FREPO] master:[FREPO-branch]
 $ git checkout [FREPO-branch]
 
 # Check out to last OREPO commit
 $ git reset --hard [last-OREPO-commit-hash]
 
 # Do massive squash of all FREPO changes
 $ git merge --squash HEAD@{1}
 $ git commit -m "Wiki update from FREPO - [description]"
 $ git checkout master
 
 # Cherry-pick newly squashed commit
 $ git cherry-pick [OREPO-newly-squashed-commit]
 $ git push 
```

**Comment by mbnuqw** [comment]
Thank you! I'll add your snippet. Also, I think I'll duplicate wiki files and put them in `./docs` dir to make it easier to PR (for both sides).
