### ISSUE TITLE
Snapshot Storage Location

### ISSUE THREAD

**Issue by andreyjc** [mbnuqw/sidebery#1157]
## Description
It would be especially useful to set the location that the snapshot are saved in.

**Comment by mbnuqw** [comment]
In the latest beta (5.0.0rc4) you can set location for auto-exported snapshots (although Firefox only allows paths inside your "Downloads" folder). The location of non-exported snapshots is in addon's storage somewhere in the Firefox profile folder, and it can't be changed.

**Comment by mbnuqw** [comment]
Available since v5.0.0
