### ISSUE TITLE
Search Tabs

### ISSUE THREAD

**Issue by everyonus** [mbnuqw/sidebery#116]
## Description
As the title suggests, this feature is for searching though tabs to find the specified tab.

## Use cases
My use case is when I have loads of tabs opened in a variety of windows, this feature would allow me to find a specific tab faster.

**Comment by mbnuqw** [comment]
Sorry, right now I'm not planning to add this feature b/c Firefox is already have this feature - searching with '%' prefix in url-bar. More info [here](https://support.mozilla.org/en-US/kb/address-bar-autocomplete-firefox?redirectlocale=en-US&redirectslug=awesome-bar-search-firefox-bookmarks-history-tabs#w_changing-results-on-the-fly). If you have use case that doesn't fit current Firefox searching abilities, feel free to describe it.

**Comment by everyonus** [comment]
Alright, didn't know about that. Thanks.
