### ISSUE TITLE
Ctrl+W to close all selected tabs

### ISSUE THREAD

**Issue by Narotiza** [mbnuqw/sidebery#1165]
When i was using tree-style tabs and wanted to close a large number of tabs, i would shift+click select them and use ctrl+w to close them all, but currently ctrl+w only closes the active tab. i know there's a keybind to remove selected items or active tab, but i can't change it to ctrl+w because entering that in closes the settings page haha

**Comment by drkhn1234** [comment]
This is a non-issue. You should go to Sidebery Settings > Tabs > Tabs Tree > "Close child tabs along with parent" and select "all" value in the right; then after that, you ctrl+w will close the whole branch.

**Comment by Narotiza** [comment]
that isn't quite what i want; i don't want ctrl+w to close more than one tab if i don't have anything selected, even if the active tab has children (i just want it to close the parent node and keep the children), and i want to be able to select and close multiple tabs that might not be in the same branch as each other, and/or not constitute all of a branch's children.
essentially i'd like the option to apply the "remove selected items or active tab" keybind's functionality to ctrl+w.

**Comment by albino1** [comment]
If I `CTRL+Click` or `Shift+Click` a bunch of random tabs and hit `CTRL+W` then they all close just fine.  And `CTRL+Shift+T` correctly brings them all back in their previous locations.  This is using Sidbery [v5.0.0rc4](https://github.com/mbnuqw/sidebery/releases/tag/v5.0.0rc4).  Maybe you have some sort of other addon interfering with it?

**Comment by mbnuqw** [comment]
@Narotiza, to get ctrl+w working you need to enable the "Highlight native tabs..." option (v4: __Settings/Tabs__ section, v5: __Settings/Tabs/Native (horizontal) tabs__ section)

**Comment by Narotiza** [comment]
@mbnuqw that worked! i installed 5.0.0rc4 and ctrl+shift+t also puts everything in its proper place
