### ISSUE TITLE
[QoL] Refine the Bookmarks search

### ISSUE THREAD

**Issue by drkhn1234** [mbnuqw/sidebery#1168]
## Description

While "bookmarks bottombar" in tabs panel is turned on, searching for bookmarks opens search results at "bookmarks bottombar" whilst having a separate bookmarks panel in Navigation bar changes this behaviour and causes the search opening bookmarks view inside the bookmarks panel located at Navigation bar. I think this behaviour makes sense--nonetheless a way to configure whether to open bookmarks search in bottombar or in bookmarks panel at navigation bar should be added. Moreover, in the case of the second behaviour mentioned above that is bookmarks view getting opened in "bookmarks panel", the active panel doesn't revert back to the one where the search was initiated from, which results in manually moving all the way back to where the panel active previous to the search was. I suggest after searching bookmarks and it opening "bookmarks panel",  by pressing Escape the active panel should revert to the previous one prior to the search.

**Comment by mbnuqw** [comment]
Resolved in v5.0.0
