### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by ongots** [mbnuqw/sidebery#117]
1. При развертывании снепшота или переносе(Открыть в X) больше 10 вкладок: не загружать вкладки. Т.е. если я переношу несколько сотен вкладок, они начинают разом загружаться, компьютер офигивает и браузер падает, если бы вкладки не загружались все бы прошло легко и быстро.

2. В контекстном меню вкладки из контейнера А есть пункт 'Открыть в А'

3. Есть возможность выключить цветовые пометки табов?

4. Добавить настройки:
Позиция новых вкладок:
Открытие из другой вкладки:  выше по соседству
Для остальных случаев:  перед активной вкладкой

**Comment by mbnuqw** [comment]
Спасиб за репорты. 1, 2 - пофиксил, скоро залью
3. Кастомный CSS:
```css
.Tab .ctx {
  display: none;
}
```
4. ноу проблем, к 4.1 добавлю

**Comment by mbnuqw** [comment]
1, 2 - Fixed in 4.0.4

**Comment by ongots** [comment]
Серьезный баг в 4.0.4
Перенесенные через контекстное меню вкладки, в контейнере не загружаются, URL не отображается.

**Comment by mbnuqw** [comment]
не могу воспроизвести

![Peek 2019-12-31 19-15](https://user-images.githubusercontent.com/6276694/71623990-02fe5300-2c02-11ea-975a-47e43c8fe0af.gif)

скинь пожалуйста отладочные данные

**Comment by ongots** [comment]
https://drive.google.com/file/d/1ttuylQdHpvoN7-Kvh6L4aPUORMXpADv-/view

{
  "settings": {
    "version": "4.0.4",
    "nativeScrollbars": true,
    "stateStorage": "global",
    "ctxMenuNative": false,
    "autoHideCtxMenu": "none",
    "ctxMenuRenderInact": false,
    "navBarLayout": "horizontal",
    "navBarInline": true,
    "hideAddBtn": false,
    "hideSettingsBtn": false,
    "navBtnCount": true,
    "hideEmptyPanels": false,
    "navMidClickAction": "none",
    "navSwitchPanelsWheel": true,
    "groupLayout": "grid",
    "warnOnMultiTabClose": "collapsed",
    "activateOnMouseUp": true,
    "activateLastTabOnPanelSwitching": true,
    "skipEmptyPanels": false,
    "showTabRmBtn": true,
    "hideInact": false,
    "activateAfterClosing": "none",
    "activateAfterClosingPrevRule": "any",
    "activateAfterClosingNextRule": "any",
    "activateAfterClosingGlobal": false,
    "shiftSelAct": true,
    "askNewBookmarkPlace": false,
    "tabsRmUndoNote": true,
    "nativeHighlight": false,
    "moveNewTabPin": "none",
    "moveNewTabParent": "none",
    "moveNewTabParentActPanel": false,
    "moveNewTab": "none",
    "pinnedTabsPosition": "panel",
    "pinnedTabsList": false,
    "tabsTree": false,
    "groupOnOpen": false,
    "tabsTreeLimit": 2,
    "hideFoldedTabs": false,
    "autoFoldTabs": false,
    "autoFoldTabsExcept": "none",
    "autoExpandTabs": false,
    "rmChildTabs": "none",
    "tabsChildCount": true,
    "tabsLvlDots": false,
    "discardFolded": false,
    "discardFoldedDelay": 0,
    "discardFoldedDelayUnit": "sec",
    "tabsTreeBookmarks": true,
    "bookmarksPanel": true,
    "warnOnMultiBookmarkDelete": "collapsed",
    "openBookmarkNewTab": true,
    "midClickBookmark": "open_new_tab",
    "actMidClickTab": false,
    "autoCloseBookmarks": true,
    "autoRemoveOther": true,
    "highlightOpenBookmarks": true,
    "activateOpenBookmarkTab": true,
    "showBookmarkLen": true,
    "bookmarksRmUndoNote": true,
    "fontSize": "s",
    "bgNoise": false,
    "animations": true,
    "theme": "default",
    "style": "dark",
    "sidebarCSS": true,
    "groupCSS": false,
    "snapInterval": 2,
    "snapIntervalUnit": "hr",
    "snapLimit": 10,
    "snapLimitUnit": "snap",
    "hScrollThroughPanels": false,
    "scrollThroughTabs": "none",
    "scrollThroughVisibleTabs": false,
    "scrollThroughTabsSkipDiscarded": false,
    "scrollThroughTabsExceptOverflow": true,
    "tabDoubleClick": "new_after",
    "tabLongLeftClick": "none",
    "tabLongRightClick": "none",
    "tabsPanelLeftClickAction": "none",
    "tabsPanelDoubleClickAction": "tab",
    "tabsPanelRightClickAction": "none"
  },
  "permissions": {
    "allUrls": true,
    "tabHide": false,
    "actualAllUrls": true,
    "actualTabHide": false
  },
  "storage": {
    "size": "6.6 mb",
    "props": {
      "bookmarksMenu": "113 b",
      "bookmarksPanelMenu": "54 b",
      "containers_v4": "459 b",
      "cssVars": "1.6 kb",
      "expandedBookmarks": "2 b",
      "favAutoCleanTime": "10 b",
      "favUrls": "55.5 kb",
      "favicons": "1.7 mb",
      "groupCSS": "2 b",
      "lastSnapTime": "13 b",
      "panelIndex": "1 b",
      "panels": "843 b",
      "panels_v4": "641 b",
      "prevTabsData_v4": "53.4 kb",
      "prevTabsTrees": "2 b",
      "settings": "2 kb",
      "sidebarCSS": "109 b",
      "snapshots": "2.2 mb",
      "snapshots_v4": "2.4 mb",
      "tabsData_v4": "54.8 kb",
      "tabsMenu": "176 b",
      "tabsPanelMenu": "170 b",
      "tabsTrees": "2 b"
    }
  },
  "panels": [
    {
      "cookieStoreId": "firefox-default",
      "icon": "...",
      "name": 16,
      "type": "default",
      "panel": "TabsPanel",
      "lockedTabs": false,
      "lockedPanel": false,
      "noEmpty": true
    },
    {
      "cookieStoreId": "firefox-container-6",
      "color": "...",
      "icon": "...",
      "name": 1,
      "type": "ctx",
      "panel": "TabsPanel",
      "lockedTabs": false,
      "lockedPanel": false,
      "proxy": "...",
      "proxified": false,
      "noEmpty": true,
      "includeHostsActive": true,
      "includeHosts": 115,
      "excludeHostsActive": true,
      "excludeHosts": ""
    },
    {
      "cookieStoreId": "bookmarks",
      "icon": "...",
      "name": 8,
      "type": "bookmarks",
      "panel": "BookmarksPanel",
      "lockedPanel": false,
      "bookmarks": true
    }
  ],
  "cssVars": {
    "bg": "#000000",
    "favicons_placehoder_bg": "#525252ff",
    "ctx_menu_bg": "#000000",
    "ctx_menu_bg_hover": "#292929",
    "nav_btn_width": "28px",
    "nav_btn_height": "28px",
    "tabs_height": "30px",
    "tabs_activated_bg": "#2a2a2aff"
  },
  "sidebarCSSLen": 103,
  "groupCSSLen": 0,
  "windows": [
    {
      "state": "maximized",
      "incognito": false,
      "tabsCount": 1266
    }
  ],
  "tabsMenu": [
    [
      "undoRmTab",
      "pin",
      "discard"
    ],
    "moveToCtr",
    "mute",
    "reload",
    "bookmark",
    "moveToNewWin",
    "moveToNewPrivWin",
    "moveToAnotherWin",
    "moveToWin",
    "group",
    "flatten",
    "clearCookies",
    "close"
  ],
  "bookmarksMenu": [
    "openInNewWin",
    "openInNewPrivWin",
    "openInCtr",
    "createBookmark",
    "createFolder",
    "createSeparator",
    "edit",
    "delete"
  ],
  "bookmarks": {
    "bookmarksCount": 1189,
    "foldersCount": 47,
    "separatorsCount": 24,
    "maxDepth": 4
  }
}

**Comment by ongots** [comment]
В форме для кастомных стилей, к заглушке "CSS . . ." стоит добавить инструкцию:

To get currently available css-selectors use debugger:
- enter about:debugging in the URL bar.
- in the left-hand menu, click This Firefox (or This Nightly).
- click Inspect next to Sidebery extension.
- select frame to inspect - click on the rectangular icon (with three sections) in top-right area of the debugger page and select "/sidebar/index.html"
- browse "Inspector" tab

**Comment by mbnuqw** [comment]
Залил версию 4.0.5, попробуй пожалуйста воспроизвести баг с ней. Если не поможет - урлы, которые ты переоткрывашь в другом контейнере, начинаются на `http...` или это внутренние ссылки типа (about:...)?

за инструкцию спасибо, действительно нужно сделать

**Comment by ongots** [comment]
Уже не актуально: Это сайты https... После обновления Sidebery на тестовом браузере до версии 4.0.0 вкладки из контейнера ссыпались в общий список и половина вкладок стала называться Новая вкладка с адресом about:blank. Если открыть такую вкладку, она становится нормальной и перемещается в свой контейнер. Но если её не открывать, а переместить через контекстное меню, получается результат выше на скриншоте.
Обновления вплоть до 4.0.5 не исправили этот баг, вероятно была ошибка импорта в четвертой версии.

Сейчас сбросил профиль в тестовом браузере и обновил 3.1.1 до 4.0.5
Импортировалось корректно но:
1. Вкладки снова ссыпались в общий список. "Перемещать вкладки выбранного контейнера в эту панель" не работает? Пришлось адреса из настроек контейнера переместить в настройки панели и перезагрузить вкладки, тогда они переместились на свою панель.
2. При перемещении вкладки загружаются

**Comment by ongots** [comment]
Добавить в контекстное меню табов:

1. Переместить в начало, Переместить в конец
2. сортировку как в закладках

**Comment by mbnuqw** [comment]
`Подскажи css для отключения скругления углов контекстного меню. А то у меня всё квадратное, кроме этого меню.`
```css
.CtxMenu .box {
  border-radius: 0;
}
```

`Если возможно, сделать сброс зажатой кнопки, после выполнение функции Длительного нажатия кнопки мыши.`
Не совсем понял, что имеется в виду - после срабатывания "Длительного нажатия кнопки мыши" контекстное меню не открывается, таб (если стоит опция "Активировать таб при отпускании кнопки мыши") не активируется.

`сортировку как в закладках`
Да, это запланированно

`Переместить в начало, Переместить в конец`
Можно добавить

`"Перемещать вкладки выбранного контейнера в эту панель" не работает`
Табы перемещаются пока только при отркытии, при изменении параметра в настройках ничего не должно происходить. Позже поправлю.

`При перемещении в другой контейнер вкладки загружаются.`
Да, можно только открыть новый таб с таким же url. Так работают контейнеры.

`Перетаскивание большого количества вкладок`
А вот с этим пока могут быть проблемы, да. Со временем постараюсь оптимизировать.

**Comment by ongots** [comment]
`Не совсем понял...`
Зажимаю правую кнопку мыши > Срабатывает функция Закрепить, вкладка улетает на панель > Отпускаю кнопку, появляется ненужное контекстное меню

**Comment by ongots** [comment]
Привязать к параметру `Позиция новых вкладок: Для остальных случаев: Перед активной вкладкой`:
1.  Создание вкладки двойным кликом и длительным нажатием `Мышь: ... : новая вкладка`. 
2.  Открытие закладок Sidebery. Закладки FF у меня открываются рядом с текущей вкладкой, Sidebery  в конце.

**Comment by ongots** [comment]
При включении `Открытие из другой вкладки: перед родительской` вкладки открываются так:
 1
 2
 3
 4
 5
[0]

Желаемое поведение:
 5
 4
 3
 2
 1
[0]

С этим связанно закрытие вкладок в неправильном порядке

**Comment by mbnuqw** [comment]
`Открытие из другой вкладки: перед родительской`
Да, новый таб всегда открывается перед род. вкладкой. При этом теряется теряется связь с родительским табом, а каких-либо вменяемых способов перевернуть порядок вкладок нет, увы.

**Comment by ongots** [comment]
Привязать к параметру `Позиция новых вкладок: Для остальных случаев: ...`
1.  Создание вкладки двойным кликом и длительным нажатием `Мышь: ... : новая вкладка`
2.  Открытие закладок Sidebery
3.  Перетаскивание вкладки на значок панели

**Comment by mbnuqw** [comment]
1. Да, разумно.
2 и 3 - баг, постараюсь пофиксить к след. релизу.

**Comment by ongots** [comment]
Если включить `Показывать заголовки закрепленных табов`, под закрепленными табами появляется толстый разделитель. Его бы убрать, тени более чем достаточно.

**Comment by ongots** [comment]
Я тут хотел отца пересадить с OneTab на встроенные закладки. Но оказалось что закладки Sidebery слишком узкие, библиотека в отдельном окне неудобна. А что если поместить закладки Sidebery в отдельную вкладку, как и настройки. Тогда получиться удобная замена OneTab

**Comment by mbnuqw** [comment]
хм... только что попробовал открыть "moz-extension://{ext-id}/sidebar/index.html" во вкладке и все дерево сломалось... :) Но в целом работает. Думаю сдалать отдельную страницу с закладками будет несложно.

**Comment by ongots** [comment]
Опиши пожалуйста, в чем ты редактируешь и тестируешь расширение, и как потом синхронизируешь расширение с гитхабом. Хочу внести мелкие улучшения.

**Comment by mbnuqw** [comment]
Если совсем маленькие исправления - можно прямо здесь, в вебе. Редактируешь файл, создаешь pull request.

А если локально потестить - нужны гит и свежая нода
Делаешь тут на сайте форк, клонируешь к себе.
В директории проекта: `npm i`
Потом сборка. Есть сборка всех модулей сразу для конечного билда: `npm run build`
Есть сборка отдельных модулей для разработки: `npm run dev.sidebar` или `npm run dev.settings` - полный список тут https://github.com/mbnuqw/sidebery/blob/master/package.json#L6
Чтобы каждый модуль не собирать, можно сбилдить все с `npm run build` и потом уже с dev.xxx интересуемый модуль.

Потом запуск браузера с `npm run dev.ext.[nightly|beta]` - тут, если винда, может не завестись из-за названия браузера. В этом случае можно попробовать напрямую: `npx web-ext run --source-dir ./addon -f firefox-nightly` - вместо "firefox-nightly" название браузера.

Ну и далее
`git add .`
`git commit -m Commit message`
`git push`
И пулл реквест уже на сайте.

**Comment by ongots** [comment]
Куда эти npm команды вбивать чтобы они работали? У меня уже голова сломалась

**Comment by ongots** [comment]
Не получается собрать
[Скрин VSCode](https://drive.google.com/file/d/1WEW8O1LdfQ2CPjdIgEJQvCTPLuee_yiE/view?usp=sharing)
[log ошибки](https://drive.google.com/open?id=14iCWz8ZEEI4ZfSteLyr_q_fd1j5YqOov)

**Comment by mbnuqw** [comment]
а что в папке node_modules/vue/dist?

**Comment by mbnuqw** [comment]
попробуй удалить `./node_modules` и `./.cache`
затем заново установить зависимости и сбилдить
`npm install`
`npm run build`

**Comment by mbnuqw** [comment]
еще если нет, попробуй создать папку ./addon/vendor

**Comment by ongots** [comment]
Проблема была в папке vendor

**Comment by ongots** [comment]
Спрашивать куда сохранить закладки > перевести панельку.

Значок обозначающий звук, на закрепленной вкладке нестандартных размеров - съезжает. Рамку значка можно заменить на тень.
![2020-03-16_162013](https://user-images.githubusercontent.com/43604031/76779789-946a7380-67b4-11ea-8bff-39f568b1ff7e.png)


На закрепленных вкладках с заголовком - отсутствует последняя метка места падения.

**Comment by ongots** [comment]
В закрепленных вкладках: c заголовком, слева, справа. Устранить наложение меток места падения, и последующее залипание.
![986986](https://user-images.githubusercontent.com/43604031/76931689-e664e380-68f1-11ea-8c71-c823934269cb.gif)

**Comment by ongots** [comment]
В закрепленных вкладках c заголовком еще нужно поправить. Чтобы увидеть наложение, нужно открыть много вкладок и проскролить вниз.

**Comment by ongots** [comment]
settings.tabs_panel_middle_click_action - добавить ру локаль

**Comment by ongots** [comment]
Групповая страница разгруппировывается при закреплении

**Comment by mbnuqw** [comment]
`Групповая страница разгруппировывается при закреплении`
Да, в закрепленных вкладках не может быть древовидной структуры.

**Comment by ongots** [comment]
`не может быть древовидной структуры` - это не важно, я хотел временно закрепить несколько ГС чтобы закидывать туда вкладки, для сортировки. Получил неожиданное поведение: ГС закрепляется, но работать нормально не может. Простым решением может быть - сделать неактивной кнопку закрепления для ГС

**Comment by ongots** [comment]
Если выбрать: `Позиция новых вкладок > Перед активной вкладкой`, то на групповой странице - кнопка `+`, создает вкладку вне группы.

Закладки Sidebery открываются в конце, а нужно перед активной вкладкой, как и закладки Firefox.

**Comment by mbnuqw** [comment]
Точно, спасиб за репорт.

**Comment by ongots** [comment]
> > Я тут хотел отца пересадить с OneTab на встроенные закладки. Но оказалось что закладки Sidebery слишком узкие. А что если поместить закладки Sidebery в отдельную вкладку, как и настройки. Тогда получиться удобная замена OneTab

> хм... только что попробовал открыть "moz-extension://{ext-id}/sidebar/index.html" во вкладке и все дерево сломалось... :) Но в целом работает. Думаю сдалать отдельную страницу с закладками будет несложно.

Лучше сделать префикс [Bookmarks],  тогда я смогу сделать CSS открывающую закладки на пол экрана, и увеличить шрифт.

**Comment by ongots** [comment]
I made a style for Firefox and Sidebery
https://github.com/ongots/firefox-sidebery-minimal-style

**Comment by ongots** [comment]
У закрепленных вкладок с заголовками, неправильная метка контейнера.

При изменении `--bookmarks-separator-height:` разделитель съезжает. Нужно удалить `.Separator .body::after {top:8px}`

В README добавить: `npx web-ext run --source-dir ./addon -f nightly` для винды.

К css для скрытия панели вкладок в wiki, можно добавить:
`@media(-moz-windows-default-theme) { [sizemode="maximized"] #nav-bar {margin-top: 8px} }`
для исправления смещения в windows.

**Comment by ongots** [comment]
https://github.com/ongots/always-fullscreen-firefox
