### ISSUE TITLE
Highlight native tabs (in top horizontal bar) along with tabs in sidebar, **but don't highlight the active tab**

### ISSUE THREAD

**Issue by drkhn1234** [mbnuqw/sidebery#1177]
## Description

When I decide, say, to use Ctrl+Shift+D to bookmark a selection of multiple tabs or Ctrl+W to close multiple tabs, I generally select a range of tabs not including the active tab I am on. Hence, it is erroneous if I select my tabs using Sidebery with "Highlight native tabs (in top horizontal bar) along with tabs in sidebar" turned on because it also includes the active tab in the selection.

What I propose is add an option to not include the active tab in the selection that highlights native tabs in the horizontal bar.

**Comment by mbnuqw** [comment]
It's impossible - [Firefox will activate the first highlighted tab](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/highlight#tabs) anyway. That's the reason why highlighting the native tabs is turned off by default - Sidebery allows selecting only inactive tabs, but Firefox not (at least one tab in selection should be active).

I should write some kind of note in settings page that explains that...
