### ISSUE TITLE
[V5] [BUG] Active tab's highlight breaks after unpinning tab

### ISSUE THREAD

**Issue by lkster** [mbnuqw/sidebery#1180]
## Steps to reproduce
- Pin tab (if there's no pinned tab yet)
- Unpin tab

## Expected behavior
Highlighting active tabs works as expected

## Actual behavior
Highlighting active tab no longer works. Tab that was active right before unpinning stays highlighted.

## Debug info
After unpinning, `data-active` attribute no longer changes it's state. This however recovers itself for pinned tabs only if one is pinned back (then there are 2 highlighted tabs if pinned one is active)

**Comment by mbnuqw** [comment]
Fixed in f06b1f9 and 5cd5d76 (unreleased)

**Comment by mbnuqw** [comment]
Resolved in v5.0.0
