### ISSUE TITLE
[v5] [BUG] "Open menu for selected (or active) tab or bookmark" shortcut doesn't invoke a context menu for selected elements of Navigation bar (i.e. pinned tabs, panels)

### ISSUE THREAD

**Issue by drkhn1234** [mbnuqw/sidebery#1186]
#### "Open menu for selected (or active) tab or bookmark" shortcut doesn't invoke a context menu for selected elements of Navigation bar (i.e. pinned tabs, panels)

Steps to reproduce:

1. Use either "Switch to previous/next panel" or "Select up/down" shortcuts, respectively, to select a panel or pinned tab present inside the Navigation bar.

2. Activate "Open menu for selected (or active) tab or bookmark"

Expected behaviour:

* Context menu relevant to the selected element is opened

Actual behaviour:

* nothing happens

**Comment by mbnuqw** [comment]
Resolved in v5.0.0
