### ISSUE TITLE
Plain Square appears when Bookmarks toolbar is set to "Only shows on New Tab"

### ISSUE THREAD

**Issue by GitEin11** [mbnuqw/sidebery#1188]
## Steps to reproduce
- Set Bookmarks toolbar to "Only shows on New Tab"
- open a new tab

## Expected behavior
- clean interface

## Actual behavior
- A plain space appears along side the bookmark toolbar.

Using Mozilla Firefox v 117.0
Sidebery v 5.0.0rc4
Ubuntu 20.04.6 LTS x86_64

![scre](https://github.com/mbnuqw/sidebery/assets/84138811/607f4b51-d81f-48dd-8d9b-bf4ca1773e5f)

**Comment by mbnuqw** [comment]
It's most likely an issue with the userChrome.css styles, not with Sidebery. Post your custom css here, I'll check what could be the reason.

**Comment by GitEin11** [comment]
thanks for the reply, I've been playing around userChrome.css so I was able to make it work by hiding bookmark toolbar when not hovering into navigator bar instead showing only on new tab.

I'll just share my userChrome.css so if other experience it

>#TabsToolbar { visibility: collapse !important; }
#sidebar-header{ display: none }
>
>
>/* -------------------------- toggle bookmark toolbar when hovering -------------------------- */
/* ------------------------------------------------------------------------------------------- */
>
>/* Source file https://github.com/MrOtherGuy/firefox-csshacks/tree/master/chrome/autohide_bookmarks_toolbar.css */
>
>#PersonalToolbar{
  --uc-bm-height: 24px; /* Might need to adjust if the toolbar has other buttons */
  --uc-bm-padding: 4px; /* Vertical padding to be applied to bookmarks */
  --uc-autohide-toolbar-delay: 600ms; /* The toolbar is hidden after 0.6s */
> 
>  /* 0deg = "show" ; 90deg = "hide" ;  Set the following to control when bookmarks are shown */
>  --uc-autohide-toolbar-focus-rotation: 0deg; /* urlbar is focused */
>  --uc-autohide-toolbar-hover-rotation: 0deg; /* cursor is over the toolbar area */
>}
>
>:root[uidensity="touch"] #PersonalToolbar{ --uc-bm-padding: 7px }
>
>#PersonalToolbar:not([customizing]){
  position: relative;
  margin-bottom: calc(-1px - var(--uc-bm-height) - 2 * var(--uc-bm-padding));
  transform: rotateX(90deg);
  transform-origin: top;
  transition: transform 135ms linear var(--uc-autohide-toolbar-delay) !important;
  z-index: 1;
  /* The following properties should allow the themes with trasparent toolbars to work */
  background-color: transparent !important;
  background-repeat: no-repeat,no-repeat,var(--lwt-background-tiling);
  --uc-bg-y: calc(-2 * (var(--tab-block-margin) + var(--toolbarbutton-inner-padding) + var(--toolbarbutton-outer-padding)) - var(--tab-min-height) - 16px - var(--bookmark-block-padding));
  background-position: top left,top left,var(--lwt-background-alignment,top left);
  background-position-y:top,top,var(--uc-bg-y),var(--uc-bg-y),var(--uc-bg-y);
  background-image: var(--toolbar-bgimage,linear-gradient(transparent,transparent)), linear-gradient(var(--toolbar-bgcolor),var(--toolbar-bgcolor)),var(--lwt-header-image,var(--lwt-additional-images)) !important;
}
>
>#PlacesToolbarItems > .bookmark-item,
#OtherBookmarks,
#PersonalToolbar > #import-button{
  padding-block: var(--uc-bm-padding) !important;
}
>
>#nav-bar:focus-within + #PersonalToolbar{
  transition-delay: 100ms !important;
  transform: rotateX(var(--uc-autohide-toolbar-focus-rotation,0));
}
>
>#navigator-toolbox:hover > #PersonalToolbar{
  transition-delay: 100ms !important;
  transform: rotateX(var(--uc-autohide-toolbar-hover-rotation,0));
}
>
>#navigator-toolbox:hover > #nav-bar:focus-within + #PersonalToolbar {  
  transform: rotateX(0);
}
>
>
>/* ------------------------------------------------------------------------------------ */
/* -------------------------- Sidebery Auto-hiding Sidebar ------------------------ */
>/*   https://github.com/Redundakitties/colorful-minimalist/blob/main/hacks/sideberyMods.css  */
>
>:root {
    --autohide-sidebar-extended: 180px; /* width of tab panel shown */
    --autohide-sidebar-collapsed: 30px; /* width of tab panel hidden */
    --sidebar-height: 100vh;
>}
>
>/* width of panel (grey box) (different from width of each tab) */
#main-window:not([extradragspace="true"])
#sidebar-box[sidebarcommand="_3c078156-979c-498b-8990-85f7987dd929_-sidebar-action"]:not([hidden]) {
    position: absolute;
    right: 0px;
    width: var(--autohide-sidebar-collapsed) !important;
    min-width: unset !important;
    z-index: 1;
    transition: all 0.2s ease-in-out;
}
/* width of panel (grey box):hover */
#main-window:not([extradragspace="true"]) 
#sidebar-box[sidebarcommand="_3c078156-979c-498b-8990-85f7987dd929_-sidebar-action"]:not([hidden]):hover,
>
>/* width of panel header - use if your header is shown */
#main-window:not([extradragspace="true"]) 
#sidebar-box[sidebarcommand="_3c078156-979c-498b-8990-85f7987dd929_-sidebar-action"] #sidebar {
  width: var(--autohide-sidebar-extended) !important;
}
>
>/* normal website page right margin */
#main-window:not([extradragspace="true"])
#sidebar-box[sidebarcommand="_3c078156-979c-498b-8990-85f7987dd929_-sidebar-action"]:not([hidden])
~ #appcontent {
    margin-right: var(--autohide-sidebar-collapsed);
}
/* when youtube full screen */
#main-window:not([extradragspace="true"])[inFullscreen][inDOMFullscreen] 
#sidebar-box[sidebarcommand="_3c078156-979c-498b-8990-85f7987dd929_-sidebar-action"]:not([hidden]) 
~ #appcontent {
  margin-right: 0 !important;
}
>
>/* adjust if your sidebery is not tall enough */
#main-window:not([extradragspace="true"])[inFullscreen]
#sidebar-box[sidebarcommand="_3c078156-979c-498b-8990-85f7987dd929_-sidebar-action"],
#main-window:not([extradragspace="true"])
#sidebar-box[sidebarcommand="_3c078156-979c-498b-8990-85f7987dd929_-sidebar-action"] {
    height: var(--sidebar-height); 
}
>
>/* ----------------------- some modification ------------------- */
>
>/* Hide sidebar splitter */
#sidebar-splitter { display: none !important; }
>
>/* place a gap between navigation and bookmark toolbar */
#PersonalToolbar {
  margin-top: 2px !important; 
  background-color: transparent !important;
}
>
>/* ------ remove the label of "Other Bookmarks" ------------ */
/* --------------------------------------------------------- */
/* add flexible space after the "other bookmarks" so it doesnt overlap with sideberry */
>
>#PlacesToolbar #OtherBookmarks .toolbarbutton-text {
>  display: none !important;
>}

here it is in action


![test2](https://github.com/mbnuqw/sidebery/assets/84138811/3a75a2ba-5875-4b63-b350-bc0a43acbbff)
