### ISSUE TITLE
broken grouping

### ISSUE THREAD

**Issue by Spacelight42** [mbnuqw/sidebery#1194]
when I select random tabs all over the side panel, some of them are above other groups and some of them are bellow, and then I click on "group" to group them, it creates one group and puts all tabs and groups flatted inside of this newly created group, the original tree structure is broke apart

**Comment by albino1** [comment]
Sidebery v4 or v5?  If you're on v4, try upgrading to v5, which you can install from here:

https://github.com/mbnuqw/sidebery/releases/tag/v5.0.0rc4
