### ISSUE TITLE
Moving tabs between panels via the context menu.

### ISSUE THREAD

**Issue by Dook1** [mbnuqw/sidebery#120]
Without this feature, it’s difficult to sort already open tabs between panels.

**Comment by mbnuqw** [comment]
Yeah, I already thought about this idea, but I was afraid that users can be confused by the same icons of containers and panels in context menu. Now (after some time of using a new version), I think I can add some badge to the icon of container/panel to show type of action (reopen in container / move to panel). So I'll add this feature for sure!

**Comment by Dook1** [comment]
Thanks

**Comment by mbnuqw** [comment]
Added in the v4.3.0. You can find it in the context menu editor.

**Comment by Dook1** [comment]
Спасибо. Правда почему-то изначально этот пункт меню был отключен, пришлось активировать его в настройках и создавать подменю.

**Comment by mbnuqw** [comment]
Closing as implemented.
