### ISSUE TITLE
Sidebery on Firefox in private windows

### ISSUE THREAD

**Issue by nicolafarina** [mbnuqw/sidebery#1203]
Hi there,

I enabled Sidebery to run on private mode too, but it seems that I need to manually show it every time I open a new private window. Is there a way to always show it (like on standard mode Firefox windows)?

Thanks.

**Comment by mbnuqw** [comment]
It's impossible to control this behavior from the addon side. Firefox's issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1268550

**Comment by nicolafarina** [comment]
Thanks for clarification!
