### ISSUE TITLE
Restore from Bookmarks is not restoring full tree when a DUPLICATE Bookmark is present IN THE SAME TREE

### ISSUE THREAD

**Issue by JohnVKRDam** [mbnuqw/sidebery#1209]
### ## Steps to reproduce
- Create a Bookmark Tree with sub folder, where the sub folder has multiple bookmarks, with at least one duplicate.

**As follows:**
- Bookmarks Base Folder (the one you SELECT when you do "**_Restore from Bookmarks_**")
-- Sub folder 1
--- Bookmark NAME-A
--- Bookmark NAME-B
--- Bookmark NAME-C
--- Bookmark NAME-A
--- Bookmark NAME-D
--- Bookmark NAME-E
--- Bookmark NAME-F

Bookmark NAME-A has a duplicate on the 4th row.
Now do a "Restore from Bookmarks" for this Bookmark Folder.

### ## Expected behavior
I expect to see in the PANEL: one sub folder. In the sub folder are ALL of the bookmarks.

- Sub folder 1
-- Bookmark NAME-A
-- Bookmark NAME-B
-- Bookmark NAME-C
-- Bookmark NAME-A
-- Bookmark NAME-D
-- Bookmark NAME-E
-- Bookmark NAME-F

### ## Actual behavior
What I see in the PANEL: one sub folder. The sub folder ONLY contains the Bookmarks UP TO the duplicate one, then all others (EXCLUDING the duplicate one) directly under the PANEL, as individual tabs:
- Sub folder 1
-- Bookmark NAME-A
-- Bookmark NAME-B
-- Bookmark NAME-C
Bookmark NAME-D
Bookmark NAME-E
Bookmark NAME-F

The import was cut-off when it encountered the DUPLICATE bookmark. **The DUPLICATE is discarded altogether** and All FOLLOWING bookmarks are then imported as single, individual tabs, NOT in any folder, directly under the PANEL.

**Comment by mbnuqw** [comment]
Resolved in v5.0.0
