### ISSUE TITLE
Dual Function Shortcut: Toggle between folded/expanded states of branch (Merge folding & expanding)

### ISSUE THREAD

**Issue by drkhn1234** [mbnuqw/sidebery#1211]
## Description

Providing two shortcuts, one for expanding and one for folding, is unnecessary based upon the binary nature of the state of a branch. Therefore, lets merge those two shortcuts into one single action and allow users to only need activate one keybind whilst retaining the ability to execute both actions.

**Comment by mbnuqw** [comment]
Sidebery has a multipurpose keybinding "Activate selection" that is also toggling the branch in some cases, but sometimes using it is not convenient and having a new one for exclusively toggling branch is ok (but without removing individual expand/fold keybindings).

**Comment by drkhn1234** [comment]
> Sidebery has a multipurpose keybinding "Activate selection" that is also toggling the branch in some cases, but sometimes using it is not convenient and having a new one for exclusively toggling branch is ok (but without removing individual expand/fold keybindings).

I can't quite think of any use case for keeping individual keybindings, but as long as my suggestion goes, I would not mind their existance. Apart from this, "Activate Selection", unfortunately, is not a one-to-one  equivalent to my suggestion—since it also changes the active tab.

**Comment by paul-ohl** [comment]
Hi!
I'd like to offer my help on this issue.
I'm a relatively inexperienced developer, but this is a feature I'm quite interested in, so if that OK with the maintainers and nobody already started working on it, I'd be happy to help.

**Comment by paul-ohl** [comment]
Welp, I did it, so hopefully [my feature](https://github.com/mbnuqw/sidebery/pull/1276) is accepted !
