### ISSUE TITLE
Dragging local files to Sibery bar and opening them on the actual "file://" address instead of "blob:"? 

### ISSUE THREAD

**Issue by ericpa06** [mbnuqw/sidebery#1213]
So, I'm not sure if this is possible, but I noticed that if you drag a local file (let's say an HTML file) to sidebery, it doesn't open that file on its normal (file://), as it does when you drag the file to the normal tab bar.

![image_2702](https://github.com/mbnuqw/sidebery/assets/6937720/f9f625ba-01d8-488e-8ca6-d9a366a1a868)

Why is this an issue? Some extensions, don't work if the files starts on "blob:", like for instance: Stylus, Dark Mode, etc, etc... So if your using dark mode extensions, and drag a file a local HTML file to sidebery bar, it won't apply dark mode to to it, because the address is a "blob"

Here is an example. In the first one, I dragged the file directly to sidebery bar:

![image_2700](https://github.com/mbnuqw/sidebery/assets/6937720/aa3bbdf9-b820-40ec-8202-0712c806f5ee)

In the second I dragged the file to tab bar instead:

![image_2701](https://github.com/mbnuqw/sidebery/assets/6937720/694fd8b5-de45-420d-a9ff-a04ffee6e803)

Also dragging directly to tab bar might not even be some option in some cases since many users use css modifications to hide the normal bar and just use sidebar to locate themselves instead.

What would be the desired output? To make so that when you drag a file to sidebar it opens the actual file location instead of blob. 

I hope I was to describe the issue. As I said in the beginning, I don't know how much this is possible, maybe it's not possible to forward the actual file address and the thing can only be open on "blob:". As always, thanks for your attention.

**Comment by mbnuqw** [comment]
It's not possible. Firefox doesn't return the real file path, only that blob link. Plus, Firefox doesn't allow addon to open a tab with the real file path, even if it's known.
