### ISSUE TITLE
Forbid returning to discarded tabs and tabs in minimized trees on closing a tab.

### ISSUE THREAD

**Issue by prizrak9** [mbnuqw/sidebery#122]
## Description
When I close a tab I'm being returned to the previous tab no matter if it's discarded or not. 
Would be cool to make an option for returning to non-discarded tabs only.

The same goes for tabs in minimized trees. If I minimized it, it means I don't intend to return there anytime soon. No need to reopen the tree if I close something else.

## Use cases
I have about 60 tabs and most of them are discarded. I switch to the other tab and discard the previous one. I close the new tab and it switches me to the discarded tab and triggers its reloading.

It's especially inconvenient when the discarded tab is somewhere in the minimized tree and you have to minimize it all over again.

**Comment by mbnuqw** [comment]
Landed with v4.4.0
