### ISSUE TITLE
Non-cryptocurrency donation

### ISSUE THREAD

**Issue by Pandry** [mbnuqw/sidebery#1226]
Hi!
I've been using Sidebery for a few months, and I'm loving it!
I was wondering if there was any way to donate to the project without recurring to cryptocurrencies.
Thanks!

**Comment by Elementari** [comment]
Paypal also supports bitcoin I was once told, even though I myself have never used it.
https://www.paypal.com/us/digital-wallet/manage-money/crypto

Apart from that if someone trustworthy volunteers to "forward" paypal USD/EUR donations as crypto to sideberry devs, that would also be a possibility. I would donate too if there were a non crypto option.

**Comment by mbnuqw** [comment]
Thank you! Unfortunately, due to my current location (and the difficulty in changing it) it's not possible.
