### ISSUE TITLE
Bookmarks do not support  jar:file://

### ISSUE THREAD

**Issue by thiesw** [mbnuqw/sidebery#123]
## Steps to reproduce
Create a bookmark starting with ` jar:file://`
e.g.   jar:file:///d:/Java/jdk-11.0.3_doc-all.zip!/docs/api/index.html?overview-summary.html

## Expected behavior
Should open as any other bookmark. Copying and pasting into address bar works fine.

## Actual behavior
Does nothing, ignores the click.

## Environment info
OS:  Windows 10 x64
Firefox version:  72.0.1 x64
Addon version:  4.2.0

**Comment by mbnuqw** [comment]
Unfortunately, its not possible to open such url due to WebExtension api limitation. From the docs:
> For security reasons, in Firefox, this may not be a privileged URL. So passing any of the following URLs will fail:
>  - chrome: URLs
>  - javascript: URLs
>  - data: URLs
>  - file: URLs (i.e., files on the filesystem. However, to use a file packaged inside the extension, see below)
>  - privileged about: URLs (for example, about:config, about:addons, about:debugging). Non-privileged URLs (e.g., about:blank) are allowed.
>  - The New Tab page (about:newtab) can be opened if no value for URL is provided.

But behavior that you described is still a bug, b/c in this case Sidebery should open `placeholder` page with the link and button to copy it. Will fix this in the next release.

**Comment by mbnuqw** [comment]
Should be fixed in v4.3.0.

**Comment by mbnuqw** [comment]
Closing it as partially fixed
