### ISSUE TITLE
Add keybinding to move sidebar to left or right

### ISSUE THREAD

**Issue by muffin4** [mbnuqw/sidebery#1233]
## Description
When clicking on "Sidebery" at the top of the Sidebar a menu opens.  One of the options in that menu is either "Move Sidebar to Left" or "Move Sidebar to Right", depending on the Sidebar's current position.

It would be nice if it were possible to create a keybinding to move the Sidebar between Left and Right.  Maybe a single keybind to switch between the positions, or two keybinds: one for "move to Right" and one for "move to Left".

I like to change the position of the Sidebar when I move the browser window to take up the left or right half of my screen, so the sidebar is always on the outside.  And I would like it if I could do this with a keybinding instead of having to use the menu.

**Comment by mbnuqw** [comment]
Unfortunately, it's not possible due to API limitations.
