### ISSUE TITLE
Show favicons only. Hide page titles.

### ISSUE THREAD

**Issue by johnnymatthews** [mbnuqw/sidebery#1234]
## Description

Add an option to hide the titles of each page, and show only the favicon. This is what this looks like in Brave:

![image](https://github.com/mbnuqw/sidebery/assets/9611008/c09a300c-60fc-4777-a36b-76cf616372df)

This _feature_ is likely possible with just CSS, but I haven't been able to find any working examples in this repo or through Google. Any pointers would be super appreciated!

**Comment by mbnuqw** [comment]
Firefox doesn't allow addons to change sidebar width. I don't use this behavior, so I can only suggest you to search in https://www.reddit.com/r/FirefoxCSS/ for auto-hide sidebar styles (a few examples):
- https://github.com/Redundakitties/colorful-minimalist/tree/main
- https://gist.github.com/BrianGilbert/1ad7e3931406f485a86a35aefb0aa1b1
- https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/autohide_sidebar.css
- https://www.reddit.com/r/FirefoxCSS/comments/12xz7oi/been_fiddling_around_with_userchromecss_since_i/
- https://www.reddit.com/r/FirefoxCSS/comments/pcuir9/sidebery_hideshow_sidebar_when_hovering_very/

This involves using [userChrome.css](https://github.com/mbnuqw/sidebery/wiki/Firefox-Styles-Snippets-(via-userChrome.css)#firefox-styles-snippets-via-userchromecss).

**Comment by johnnymatthews** [comment]
Ah, _auto-hide sidebar_ was the term I should have been searching for. Thanks!
