### ISSUE TITLE
Integrate with Firefox's tab multi select

### ISSUE THREAD

**Issue by Lej77** [mbnuqw/sidebery#1244]
## Description

Currently if `Use native context menu` is enabled and there are addons that provide other context menu items then those won't be informed about the tab selection in the Sideberry sidebar. Instead they will only notice the tab that was right clicked.

For example the [`Tab Mover`](https://addons.mozilla.org/firefox/addon/tab-mover/) addon will only move the right clicked tab instead of all selected tabs.

The fix should be to either always synchronize the tab selection with Firefox or to do so when the native context menu is opened. (I guess this could also be an option that could be enabled in the settings page if the performance hit is large enough.)

**Comment by mbnuqw** [comment]
Already implemented:
Sidebery settings >> Tabs >> Native (horizontal) tabs >> `Highlight native tabs...`
