### ISSUE TITLE
New tabs in wrong panel

### ISSUE THREAD

**Issue by dzejba** [mbnuqw/sidebery#125]
## Steps to reproduce
Have some configured Panels in Sidebery
Open Firefox side strip with Sidebery
Switch to "Default" panel in Sidebery
Close Firefox side strip with Sidebery 
Create new tab in Firefox
Open Firefox side strip with Sidebery to check membership of tabs into Panels

## Expected behavior
The new tabs should be in Default panel (or other panel I switched to before closing Sidebery side strip)

## Actual behavior
New tabs are in different Panel (probably the last created?). And also Sidebery shows that this Panel is actual one (not the one I left before closing Sidebery side strip).

## Environment info

OS:  Windows 10
Firefox version:  72.0.1 64bit
Addon version:  4.2.0

**Comment by mbnuqw** [comment]
This is expected behavior right now b/c the relation between panels and tabs as well as the tabs tree are handled in sidebar instance. Sidebery was created as replacement for the default tabs stripe and implies the use of a permanently open sidebar.

I'll leave this issue open, maybe later I'll add sidebar-less tabs handling.

**Comment by dzejba** [comment]
Any hint how to configure Sidebery/Panels/order of Panels so that newly created tabs will appear in Default Panel when Sidebery closed? Would be absolutely sufficient for my workflows for now...
Thx

**Comment by mbnuqw** [comment]
On sidebar initialization Sidebery appends unregistered tabs to the panel of the previous "registered" tab. So if you place the Default panel at the last position and all new unregistered tabs will be open atleast after the first registered tab of Default panel they will be placed in Default panel.
