### ISSUE TITLE
New tabs in wrong panel #2

### ISSUE THREAD

**Issue by dzejba** [mbnuqw/sidebery#126]
## Steps to reproduce
Open Sidebery side strip in Firefox
Select some Panel in Sidebery e.g. default one
Open new tab by Firefox - either. Ctrl-T or click on "+" right to Firefox tabs

## Expected behavior
Tab should be opened in current Sidebery panel

## Actual behavior
Tab is opened in different Sidebery panel (the last created?) and Sidebery activates this Panel

## Environment info

OS:  Windows 10
Firefox version:  72.0.1
Addon version:  4.2.0

<details><code>

</code></details>

**Comment by oliva** [comment]
Same here, discovered through slightly different steps:
* Open page on Default panel
* Open page in second panel
* Switch back to Default panel
* Press Control-T to open a tab

New tab opens in second panel, Sidebery switches back to it

Versions:
OS: linux
Firefox: 74.0a1
Addon: 4.2.0

**Comment by mbnuqw** [comment]
Thanks for the report, soon will upload the new version with the fix.

**Comment by mbnuqw** [comment]
I've just uploaded v4.3.0, so you can try it. Also, check setting 'Position of new tab (for the other cases)'.

**Comment by mpdeimos** [comment]
Have sadly the same problem with 4.3.0. I'm wondering if there is any option I miss that controls where ctrl+T (new tab) opens.

**Comment by mbnuqw** [comment]
@mpdeimos you're right, in c999b67 I've added default container to possible options, so I hope this issue and #125 will be resolved in the next release.

**Comment by mpdeimos** [comment]
Thanks. Will test as soon it's released!

**Comment by ianelletson** [comment]
Could there be multiple containers per panel? For example I have an "environments" panel which I'd like to add all my "local", "SIT", "QE", etc containers to automatically. I know I could do this with just 1:1 panel:container but I'd prefer 1:*

**Comment by mbnuqw** [comment]
@ianelletson, yes, this sounds reasonable, I think I can add possibility to select multiple containers for auto-move new tabs.

**Comment by mbnuqw** [comment]
@mpdeimos, v4.4.0 is released with the 'default panel' option, so you can try it!
@ianelletson' I've created issue for your suggestion: #131

And I'm closing this issue

**Comment by lmBored** [comment]
Im having this same issue in sidebery 5.4.0 :( Is there a setting I should change in sidebery?

I set this to panel end but it's not overwriting firefox's `CMD-T` behavior

<img width="653" height="192" alt="Image" src="https://github.com/user-attachments/assets/a7abd788-06a3-4d68-8e90-df12bce7c8be" />

Edit: Weirdly, this issue sometimes occurs, sometimes doesn't...
