### ISSUE TITLE
How to disable/edit the new menu? (recent closed, boomkarks, history)

### ISSUE THREAD

**Issue by felixsanz** [mbnuqw/sidebery#1269]
How to disable or edit the menu that appears at the bottom of the tab list?

![1695563146](https://github.com/mbnuqw/sidebery/assets/6182099/09c86e5a-ef63-4ba1-943c-a3aa490cb608)

**Comment by llc0930** [comment]
settings > left 1-3 > right 6-1,6-2,6-3
If you mean the button and not the menu content.

**Comment by felixsanz** [comment]
> settings > left 1-3 > right 6-1,6-2,6-3 If you mean the button and not the menu content.

That is! Thank you
