### ISSUE TITLE
what does "tabs state storage type" do?

### ISSUE THREAD

**Issue by berot3** [mbnuqw/sidebery#127]
## Description

under tabs there is now a option called "**tabs state storage type**" which can be set to `global` or `session`.

## Use cases

What does it do?
A short info or tooltip would be nice to have. I could not find a explanation on google.

**Comment by mbnuqw** [comment]
This setting declares where to store tabs data (tab-panel relations, tabs tree). It tightly related to the process of initialization and tabs tree restoring.

- global storage - fast, but inaccurate in rare cases. Data is stored in storage of addon.
- session storage - more strict, but slower. Data is bound to each opened tab and will be removed if you lost your session.

I'll add the description in the settings page.

**Comment by berot3** [comment]
ok thanks!

and regarding session-storage: you mean by "lost session" that the browser crashed for example?
so since I am using automatic snapshots I could also go with session-storage 😄 
but will I actually feel the slowness? I sometimes have many many tabs open 🤣

**Comment by mbnuqw** [comment]
If after the crash you can restore the previous session than Sidebery should handle it (well.. I hope). And of course, if tabs were gone you still can use snapshots. About the slowness - this deeply depends on the count of tabs, yes. On my machine, I've felt sadness after 100pcs with session-based storage.

Closing this issue
