### ISSUE TITLE
add a toggle for new "clicking on already active tab" feature

### ISSUE THREAD

**Issue by jgournet** [mbnuqw/sidebery#1272]
## Description
In V5, when clicking on the already active, sidebery does the equivalent of "ctrl+tab" and displays the previously active tab.
=> Is there a way to disable that functionality, and just make it do "nothing" (ie: just keep the already active tabs) ?

**Comment by llc0930** [comment]
setting > mouse > tab > 2

**Comment by gforien** [comment]
Stumbled across this too. Here is a screenshot of the toggle setting in v5.0.0

![image](https://github.com/mbnuqw/sidebery/assets/7701186/dd43393d-38f7-408e-9723-18485e76b8f4)
