### ISSUE TITLE
Scroll tabs while drag'n'dropping a tab

### ISSUE THREAD

**Issue by postpersonality** [mbnuqw/sidebery#1278]
## Description
It would be nice to have scroll enabled during drag'n'drop process for long (tall) list of tabs. Currently you have to bump to ether top or bottom edge of the list in order to scroll up or down, which is slow and imprecise (in terms of tab placement).

**Comment by llc0930** [comment]
setting > left 6 > right 1
This may alleviate your problem.

**Comment by postpersonality** [comment]
Not really sure what "setting > left 6 > right 1" means. If you mean keybindings, then yes, I'm aware of that possibility. Thanks for suggestion!
And having mouse scroll during drag'n'drop is just an option that I personally used to.

**Comment by llc0930** [comment]
No, I'm referring to the location of the options in the settings page.
`/page.setup/setup.html#settings_dnd`

**Comment by postpersonality** [comment]
Ah, I see. Yes, that solves tab activation problem. Thanks!
![image](https://github.com/mbnuqw/sidebery/assets/2012215/6dd229ca-2fae-4eed-a978-7590717fd17a)

Main issue I have is waste of time when I drag'n'drop a tab from very bottom to some place at the top of tall tab tree.

**Comment by lolicon0930** [comment]
keybindings > last 1 > 1
Hope this saves your time temporarily.
You can use this setting to return to your original position:
settings_mouse > 3-2

**Comment by azizLIGHT** [comment]
It's also uncontrollable. You have to put the mouse in a very particular area to do a controlled scroll. Otherwise it's either too fast or too slow everywhere else. Using the mousewheel to scroll will let me actually control the scroll rate while drag/dropping tabs

**Comment by mbnuqw** [comment]
It's impossible to use the scroll wheel while dragging the element. As a workaround for dropping an element to the end of a panel, you can drop it on the panel icon in the navigation bar.
