### ISSUE TITLE
Wrap tabs when scrolling

### ISSUE THREAD

**Issue by cougarten** [mbnuqw/sidebery#128]
## Description

similar to strg+tab moving from my last tab to my pinned tabs or the top of the tap list I'd love to change tabs by scrolling. When I reach the bottom of the tab list I want the next tab to be activated by scrolling further to be the pinned tabs.

## Use cases

quick switch from usually oldest and most persistent tabs to what are usually the newest tabs

thanks for sidebery, it's great! :)

**Comment by mbnuqw** [comment]
Added in v4.4.0 with option "Switch tabs with scroll wheel / Cyclically"
