### ISSUE TITLE
Option to move the Sidebar to the Right Side of the Screen

### ISSUE THREAD

**Issue by dcadint** [mbnuqw/sidebery#1291]
Over the years working with applications I have found that navigation type interfaces are used for a short period of time and then they are not used as often as you work in the main workspace.  Also over the years computer screens have changed from 4:3 to 16:9 ratios which means the screens are wider and have less vertical real-estate.  Tools and navigation interfaces need to be careful how much vertical real-estate they take up.  What I have found is that I do my work from left to right (probably a cultural thing, other cultures that read right to left are probably used to working from the right).  So I have moved my menu and task bars to the right side of the screen and within applications I moved any navigation type sidebars to the right side as well.  This way they are not jutting out into the area in which I do my work.  I think if more people try this method out they will find that putting these interfaces on the right moves them out of the way and allows them to concentrate on the work at hand.  So I would request that an option be added to move the sidebery sidebar to the right side of the Firefox window.

**Comment by albino1** [comment]
This is already built into Firefox:

![sb1](https://github.com/mbnuqw/sidebery/assets/12164957/125f1544-9c7e-490f-94c7-887a7d2e7b19)

**Comment by b0o** [comment]
You can also set `sidebar.position_start` to `false` in `about:config`.

**Comment by devgid** [comment]
@dcadint Close this issue
