### ISSUE TITLE
Group/Flatten keybindings

### ISSUE THREAD

**Issue by ThinkSalat** [mbnuqw/sidebery#1295]
I'd love to have keybindings to create a new group. I tend to use that to very clearly delineate groups of tabs within panels. Also, I often end up with unnecessary hierarchy and a shortcut to flatten selected tabs would be great as well.

**Comment by maanemann** [comment]
I second this request. You can do almost everything else with keybindings - like moving tab selection, multi-selecting tabs, focus selected tab, unloading tabs etc. Seems almost like a mistake that there's no keybinding for creating groups? Can't see how it should be more technically challanging than other commands, but what do i know.

There's a workaround for 'flattening' tabs. You can bind keys to "Move tabs up" and "Move tabs down", as well as to "Increase tab's tree level (indent)" and "Decrease tab's tree level (outdent)". It's probably the last one you need for this, but the other ones are nice to have in this context too. If you don't know already, you find the "Keybindings" button in the side panel of Sidebery's settings. When you're there, you can just use ctrl/cmd+F to find the mentioned bindings, or scroll to the section called "Moving tabs".
