### ISSUE TITLE
Selecting pinned tab scrolls tabs to bottom

### ISSUE THREAD

**Issue by mbaz** [mbnuqw/sidebery#13]
When I click on a pinned tab to select it, the non-pinned tabs scroll down to the bottom tab. This is very inconvenient when there are a large number of tabs. I'm using version 2.1.0.

**Comment by mbnuqw** [comment]
Fixed in 2.1.1

**Comment by mbaz** [comment]
I just upgraded to v2.2.0, and this problem is happening again.

**Comment by mbnuqw** [comment]
Sorry, already fixed, soon will upload v2.2.1

**Comment by mbnuqw** [comment]
Fixed in v2.2.1

**Comment by mbaz** [comment]
Thanks!
