### ISSUE TITLE
Add Send Tab to Device Right Click Context Menu

### ISSUE THREAD

**Issue by TWDickson** [mbnuqw/sidebery#130]
## Description
Standard tabs allow users to "Send Tab to Device" via a right click menu. This utilizes Firefox sync

## Use cases
Quickly sending a tab to another device like a phone

**Comment by mbnuqw** [comment]
This is not possible, sorry. Unfortunately, there is just no api for that.

**Comment by TWDickson** [comment]
Awww too bad!

**Comment by passcod** [comment]
This is the Firefox bug for this API: https://bugzilla.mozilla.org/show_bug.cgi?id=1417183 (vote on it!)

**Comment by djsime1** [comment]
Alternative option: Create an encoded URI and ask the user to send that single tab. The URI could be an HTML document listing each tab, or something that Sidebery on the other device can decode and open the multiple tabs.
