### ISSUE TITLE
[FR] Cycle Tabs in Active Panel.

### ISSUE THREAD

**Issue by darkelectron** [mbnuqw/sidebery#1315]
## Description

- Currently, the `Sidebery` keybindings have only `next` and `prev` for active panel.

## Feature Request

- It would be nice to have tabs cycle in the active panel. This could also use the `Firefox` keybindings.

Thanks.

**Comment by devgid** [comment]
This issue occurs with standard Firefox tab navigation Ctrl+Tab, Ctrl+Shift+Tab

If I have the setting enabled:
![image](https://github.com/mbnuqw/sidebery/assets/13977449/c1f7792e-5009-45f6-aa4e-c0efc677927a)
It won't switch to the next panel if I use keyboard shortcut Ctrl+Tab on the last tab in my open panel.  It keeps the current panel open. However it does switch to the tab in the next panel despite that panel not visually showing.

That same setting should make Ctrl+Tab cycle through the tabs in the same panel and not jump to other tabs.

**Comment by devgid** [comment]
The setting "Stay in Panel until last tab"  makes Ctrl+Tab keep the same Panel open as that setting will already prevent the next panel from showing. 
Having a tab in another panel shown the doesn't belong to the current panel  makes no sense as the open tab is not part of the visual shown panel nor shown visually in the treeview.

I would suggest to add this behavior to the current setting "Stay in Panel until last Tab: and move the setting one level up e.g "Stay in panel to the last tab" is not a child of the setting "After closing current tab activate" but on same level seeing that you want to stay in the panel if you close a tab as well as stay in the panel when navigate to the next tab.

**Comment by devgid** [comment]
Related issue : https://github.com/mbnuqw/sidebery/issues/463
but with standard Firefox keyboard shortcut

**Comment by mbnuqw** [comment]
Implemented in the latest version (keybindings: "Switch to the next/prev tab")
See also: #1515
