### ISSUE TITLE
Panels and Containers are no longer tied together

### ISSUE THREAD

**Issue by johnksawers** [mbnuqw/sidebery#132]
## Steps to reproduce

Have several containers. Have panels that match the containers. Assign a few tabs to each container. 

## Expected behavior

Up until a week ago, panels and containers had a 1:1 mapping and opening a tab in a container (or moving it there) would switch to the the panel for that container and open there. Now I have panels that are named for my containers but there is no correlation between them and no way to put tabs in other panels. 

## Actual behavior

I opened Firefox today and all my tabs were listed in one panel, even though they're in separate containers. If I right click to move them to another container, the color of the tab highlight changes to match the container color but does not change panels. 

## Environment info

OS:  MacOS 10.15.2
Firefox version:  72.0.2
Addon version:  4.4.0

<details><code>
{
  "settings": {
    "version": "4.4.0",
    "nativeScrollbars": false,
    "stateStorage": "global",
    "ctxMenuNative": false,
    "autoHideCtxMenu": "none",
    "ctxMenuRenderInact": true,
    "navBarLayout": "horizontal",
    "navBarInline": true,
    "hideAddBtn": true,
    "hideSettingsBtn": false,
    "navBtnCount": true,
    "hideEmptyPanels": true,
    "navMidClickAction": "none",
    "navSwitchPanelsWheel": true,
    "groupLayout": "grid",
    "warnOnMultiTabClose": "collapsed",
    "activateOnMouseUp": false,
    "activateLastTabOnPanelSwitching": true,
    "skipEmptyPanels": false,
    "showTabRmBtn": true,
    "showTabCtx": true,
    "hideInact": false,
    "activateAfterClosing": "next",
    "activateAfterClosingPrevRule": "visible",
    "activateAfterClosingNextRule": "tree",
    "activateAfterClosingGlobal": false,
    "activateAfterClosingNoFolded": false,
    "activateAfterClosingNoDiscarded": false,
    "shiftSelAct": true,
    "askNewBookmarkPlace": false,
    "tabsRmUndoNote": true,
    "nativeHighlight": false,
    "moveNewTabPin": "end",
    "moveNewTabParent": "end",
    "moveNewTabParentActPanel": false,
    "moveNewTab": "end",
    "pinnedTabsPosition": "panel",
    "pinnedTabsList": false,
    "tabsTree": false,
    "groupOnOpen": true,
    "tabsTreeLimit": "none",
    "hideFoldedTabs": false,
    "autoFoldTabs": false,
    "autoFoldTabsExcept": "none",
    "autoExpandTabs": false,
    "rmChildTabs": "none",
    "tabsChildCount": true,
    "tabsLvlDots": false,
    "discardFolded": false,
    "discardFoldedDelay": 0,
    "discardFoldedDelayUnit": "sec",
    "tabsTreeBookmarks": true,
    "bookmarksPanel": false,
    "warnOnMultiBookmarkDelete": "collapsed",
    "openBookmarkNewTab": false,
    "midClickBookmark": "open_new_tab",
    "actMidClickTab": false,
    "autoCloseBookmarks": false,
    "autoRemoveOther": false,
    "highlightOpenBookmarks": false,
    "activateOpenBookmarkTab": false,
    "showBookmarkLen": false,
    "bookmarksRmUndoNote": true,
    "fontSize": "xxs",
    "bgNoise": true,
    "animations": true,
    "theme": "tactile",
    "style": "light",
    "sidebarCSS": false,
    "groupCSS": false,
    "snapNotify": true,
    "snapInterval": 0,
    "snapIntervalUnit": "min",
    "snapLimit": 0,
    "snapLimitUnit": "snap",
    "hScrollThroughPanels": false,
    "scrollThroughTabs": "none",
    "scrollThroughVisibleTabs": false,
    "scrollThroughTabsSkipDiscarded": false,
    "scrollThroughTabsExceptOverflow": true,
    "scrollThroughTabsCyclic": false,
    "tabDoubleClick": "none",
    "tabLongLeftClick": "none",
    "tabLongRightClick": "none",
    "tabsPanelLeftClickAction": "none",
    "tabsPanelDoubleClickAction": "tab",
    "tabsPanelRightClickAction": "menu"
  },
  "permissions": {
    "allUrls": false,
    "tabHide": false,
    "actualAllUrls": false,
    "actualTabHide": false
  },
  "storage": {
    "size": "1.9 mb",
    "props": {
      "containers_v4": "1 kb",
      "expandedBookmarks": "2 b",
      "favAutoCleanTime": "10 b",
      "favUrls": "36.4 kb",
      "favicons": "1.7 mb",
      "panelIndex": "1 b",
      "panels": "1.7 kb",
      "panels_v4": "1.4 kb",
      "prevTabsData_v4": "118.3 kb",
      "prevTabsTrees": "2 b",
      "settings": "2 kb",
      "tabsData_v4": "118.7 kb",
      "tabsTrees": "2 b"
    }
  },
  "panels": [
    {
      "cookieStoreId": "bookmarks",
      "icon": "...",
      "name": 9,
      "type": "bookmarks",
      "panel": "BookmarksPanel",
      "lockedPanel": false,
      "bookmarks": true
    },
    {
      "cookieStoreId": "firefox-default",
      "icon": "...",
      "name": 7,
      "type": "default",
      "panel": "TabsPanel",
      "lockedTabs": false,
      "lockedPanel": false,
      "noEmpty": false
    },
    {
      "cookieStoreId": "firefox-container-1",
      "color": "...",
      "icon": "...",
      "name": 8,
      "type": "ctx",
      "panel": "TabsPanel",
      "lockedTabs": false,
      "lockedPanel": false,
      "proxy": null,
      "proxified": false,
      "noEmpty": false,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": ""
    },
    {
      "cookieStoreId": "firefox-container-2",
      "color": "...",
      "icon": "...",
      "name": 4,
      "type": "ctx",
      "panel": "TabsPanel",
      "lockedTabs": false,
      "lockedPanel": false,
      "proxy": null,
      "proxified": false,
      "noEmpty": false,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": ""
    },
    {
      "cookieStoreId": "firefox-container-4",
      "color": "...",
      "icon": "...",
      "name": 8,
      "type": "ctx",
      "panel": "TabsPanel",
      "lockedTabs": false,
      "lockedPanel": false,
      "proxy": null,
      "proxified": false,
      "noEmpty": false,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": ""
    },
    {
      "cookieStoreId": "firefox-container-6",
      "color": "...",
      "icon": "...",
      "name": 8,
      "type": "ctx",
      "panel": "TabsPanel",
      "lockedTabs": false,
      "lockedPanel": false,
      "proxy": null,
      "proxified": false,
      "noEmpty": false,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": ""
    },
    {
      "cookieStoreId": "firefox-container-7",
      "color": "...",
      "icon": "...",
      "name": 6,
      "type": "ctx",
      "panel": "TabsPanel",
      "lockedTabs": false,
      "lockedPanel": false,
      "proxy": null,
      "proxified": false,
      "noEmpty": false,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": ""
    }
  ],
  "cssVars": "TypeError: can't convert undefined to object",
  "windows": [
    {
      "state": "fullscreen",
      "incognito": false,
      "tabsCount": 928
    }
  ],
  "bookmarks": {
    "bookmarksCount": 4449,
    "foldersCount": 64,
    "separatorsCount": 1,
    "maxDepth": 4
  }
}
</code></details>

**Comment by mbnuqw** [comment]
Yes, in v4.x.x I separated panels and containers, but its still possible to "bind" them together. To do that you need to open Settings, click on the target panel and set options "Container of new tab" and "Move tabs of selected container to this panel" to desired container (also you can set icon and color).

The strange thing is that this should've been done automatically on upgrade from v3.x.x. Looks like you've encountered a bug, which is unfortunately cannot be fixed without a time machine..(

**Comment by johnksawers** [comment]
Ah, I hadn't understood that wording in the prefs, thanks for clarifying. Now I just have to manually move 900 tabs into the right containers :-( - Thanks for all the hard work on this, it's the best tab sidebar.
