### ISSUE TITLE
Lock pinned tabs

### ISSUE THREAD

**Issue by iFUCKINGHATEcomputers** [mbnuqw/sidebery#1324]
## Description
The option to have any links opened from pinned tabs (or a particular pinned tab) be opened as new, non-pinned tabs, thus preventing any changes to the pinned tab.

Edit: this seems to work great as a solution so far:
https://addons.mozilla.org/en-US/firefox/addon/lock-tab-page/

**Comment by HenryTheVacuum** [comment]
However, lock icon doesn't show up in sidebery tabs with that extension

**Comment by mbnuqw** [comment]
[Lock Tab Page](https://addons.mozilla.org/en-US/firefox/addon/lock-tab-page/) works fine, so I don't see the reason to add this feature to Sidebery.
