### ISSUE TITLE
Allow setting indentation size/amount for the hierarchy. Perhaps also a thicker indentation bar.

### ISSUE THREAD

**Issue by PrefersAwkward** [mbnuqw/sidebery#1327]
I have trouble seeing the hierarchical structure of the tree. Can we allow perhaps a thicker border line, maybe a rainbow of colors and/or thicker indentation?

**Comment by mbnuqw** [comment]
It's possible to change indentation size: Sidebery settings > Styles editor > Tabs > Indent
It's also possible to change opacity of the indent mark: Sidebery settings > Styles editor > Tabs > Lvl opacity
Thicker indentation bar:
```css
.Tab .body:after {
	width: 2px;
}
```
