### ISSUE TITLE
Compatibility with Firefox's native Dark Mode

### ISSUE THREAD

**Issue by gunir** [mbnuqw/sidebery#1332]
## Description
Firefox has a native Dark Mode, it's the fastest Dark Mode ever exists, turning it on by changing these values:

**Go to `about:config`, set:**

browser.display.background_color #c0c0c0
browser.display.foreground_color #000000
browser.anchor_color #ffcc99
browser.display.use_system_colors false
browser.display.document_color_use 2

**Result:**
![image](https://github.com/mbnuqw/sidebery/assets/134402102/df8cb317-7a37-4da9-93d0-151b871f3170)

Source post: https://github.com/Floorp-Projects/Floorp/discussions/487

But the issue is, Sidebery's tab text color doesn't follow Dark Mode's `browser.display.foreground_color`, and it uses black text anyway, which is not good:
![image](https://github.com/mbnuqw/sidebery/assets/134402102/70ed37e4-d21e-43dc-9ab3-f7228c0600f4)

**What's expected ?**
Sidebery's tab text SHOULD follow `browser.display.foreground_color` color instead of using its own.

**Comment by mbnuqw** [comment]
> Sidebery's tab text SHOULD follow

No, it shouldn't.
