### ISSUE TITLE
Multiple windows : Sidebery opens only last closed window instead of all windows.

### ISSUE THREAD

**Issue by Elaws** [mbnuqw/sidebery#1337]
If you have multiple windows and close them all, when starting Firefox again, only the last closed window will open, therefore loosing all the panels that were opened in the others windows. This forces users to load a previous snapshot.

**Comment by llc0930** [comment]
I think this is a behavior issue in Firefox lol.

**Comment by Elaws** [comment]
Couldn't sidebery override this ? Like there is a button in snapshot viewer to "open all windows". I guess then this could be automated ?

**Comment by dfaligertwood** [comment]
Simple Tab Groups does this correctly, so I'm not sure it's a Firefox problem?

**Comment by mbnuqw** [comment]
Sidebery doesn't open anything, there is no such feature. It just uses what Firefox gives it (windows, tabs restored by Firefox according to Firefox settings). There is a related feature request: #721

**Comment by Elaws** [comment]
A solution could be as follow :

In case where last 100 Sidebery snapshots include 100+ tabs and suddenly Firefox restores 3 tabs only (because the last window we closed was the "wrong" one), there could be an option to automatically reload the correct snapshot with 100+ tabs.

**Comment by Elaws** [comment]
> A solution could be as follow :
> 
> In case where last 100 Sidebery snapshots include 100+ tabs and suddenly Firefox restores 3 tabs only (because the last window we closed was the "wrong" one), there could be an option to automatically reload the correct snapshot with 100+ tabs.

Hi @mbnuqw : do you think adding such option would be feasible ?

Very often, I open another Firefox window and mistakenly close the wrong one first. I would like Sidebery to automatically restore the snapshot I'm constantly using (with many tabs open, not just a few).

Thank you very much !

**Comment by Elaws** [comment]
> A solution could be as follow :
> 
> In case where last 100 Sidebery snapshots include 100+ tabs and suddenly Firefox restores 3 tabs only (because the last window we closed was the "wrong" one), there could be an option to automatically reload the correct snapshot with 100+ tabs.

This would be amazing, any news regarding this FR please ?

Thank you.
