### ISSUE TITLE
Improve some drag and drop behaviour for tabs at the end of trees

### ISSUE THREAD

**Issue by cougarten** [mbnuqw/sidebery#134]
## Description

If I drop a tab at the end of a branch it will become part of that branch (same as dragging it on to the parent, just gets inserted at the bottom).

![image](https://user-images.githubusercontent.com/7131556/73883399-27ce9180-4864-11ea-8da3-33c28a794b7a.png)
_the "dragme" will become a sibling of the other child. I think it should rather become a sibling of the parent_

There is no way to insert a tab at the desired spot without it becoming part of the branch.

easy solution: always prefer dropping outside of the branch.

other solution: have 2 drop zones close to each other, the top one dropping inside the branch, tho bottom one on the branches parent level. This would also need visual feedback though. Might be worth having a look what tree style tabs does, I remember that worked well.

## Use cases

- insert tab in desired space without nesting it
- make tab top-level by quickly dragging it in to the free bottom area of the sidebar

**Comment by mbnuqw** [comment]
I've implemented new drag and drop in 43de56da87a94ee560d57644aa50c1e36aaf42f7 which will add ability to choose target level of the dragged element. Will be released soon.

![Peek 2020-02-06 20-11](https://user-images.githubusercontent.com/6276694/73949911-e221cf80-491c-11ea-8e82-79faecc4c5da.gif)

**Comment by mbnuqw** [comment]
Was released in v4.5.0
