### ISSUE TITLE
Suggestion to change "mouse wheel" references in settings to "vertical scrolling" (or similar)

### ISSUE THREAD

**Issue by evanmarzahn** [mbnuqw/sidebery#1343]
This is very minor, but I noticed some inconsistency in how the settings page refers to scrolling. It refers to "horizontal scrolling" but appears to use the "mouse wheel" as a synonym for vertical scrolling. I think given the variety of devices people may use to scroll (I'm on a laptop that never has a mouse connected, for example) it might be helpful for understanding if the mouse wheel references were changed to be more device-agnostic and refer to vertical scrolling, if that is what is meant.

**Comment by bzm3r** [comment]
It is confusing for me to figure out what is meant here too, and I am using a mouse. 

Horizontal scrolling, at least in Firefox means typically means setting action `4` for something like `mousewheel.with_shift.action` (not really sure where these values are enumerated, but there seems to be consensus on the internet, and it is easy to try it out for yourself.

But, holding Shift+mouse-scroll does not let me switch between *recently active tabs*, even when I set that up in Sidebery. It always switches up and down between the tab above/below in the list.

So, what does "horizontal scrolling" mean?
