### ISSUE TITLE
Open dragged text in new tab

### ISSUE THREAD

**Issue by cougarten** [mbnuqw/sidebery#135]
## Description
 
When I drag selected text in the sidebar I expect it to open a new tab and handle it as if I typed the dragged text in the browsers navigation bar and hit return.

![image](https://user-images.githubusercontent.com/7131556/73883914-16d25000-4865-11ea-8e3f-06d72fc2f702.png)
_I expect a new tab will open at the desired position and it will trigger a search in my default search engine_

When I drag an unlinked, pure text URL I also expect it to open the website instead of searching for it in my default search engine.

Surprisingly dragging text in to the empty part of the sidebar already behaves as expected :)

## Use cases

- open a search or text-link by dragging selected text at any desired location in sidebery

Thanks again for building this :)
And if you don't have time for my detailed feature requests that's more than fine, too!

**Comment by mbnuqw** [comment]
Thanks for the report! I've just tested dropping plain text to the sidebar and indeed, found inconsistency in behavior - I'll try to fix this in the next release.

About opening urls from the dropped plain text - this is a good idea, definitely worth implementing!

**Comment by mbnuqw** [comment]
I've fixed (I hope) this in v4.6.0. Right now it behaves like that:

![Peek 2020-02-20 20-50](https://user-images.githubusercontent.com/6276694/74953036-f4266680-5422-11ea-8445-b34448e45748.gif)

so I'm closing this. Feel free to reopen if something looks not right.
