### ISSUE TITLE
[Feature request] Option to disable font antialiasing

### ISSUE THREAD

**Issue by Zeioth** [mbnuqw/sidebery#1376]
## Description
I have a 4K screen and the default antialias CSS aplied to the fonts make it blurrier than without it. antialiasing is only recommended for low pixel density displays.

It would be great if we had a way to disable it.

**Comment by mbnuqw** [comment]
It's only possible to change [`-moz-osx-font-smoothing`](https://developer.mozilla.org/en-US/docs/Web/CSS/font-smooth) prop, which only works on macOS. If it's your case you can try to set this custom style (Sidebery settings > Styles editor):
```css
#root {
  -moz-osx-font-smoothing: auto;
}
```
