### ISSUE TITLE
How to disable auto-loading the pinned tabs when starting Firefox

### ISSUE THREAD

**Issue by c02y** [mbnuqw/sidebery#1381]
## Description

When I start my Firefox, all the tabs are unloaded(sleep status, I'm using `Auto Tab Discard` extension if it matters) except the current tab, but all the pinned tabs are also loaded which I don't like, so is it possible that all the pinned tabs are not auto loaded when I start my Firefox?

**Comment by albino1** [comment]
My pinned tabs don't load when I start Firefox, though I don't know if that's because of Sidebery or some other extension.  Maybe take a look at this setting though and see what you have it set to:

![sideb](https://github.com/mbnuqw/sidebery/assets/12164957/eaac02a4-da1c-456e-b800-8e10f8ae0bf4)

**Comment by c02y** [comment]
I tried to disable `Auto Tab Discard` extension, and the `Prevent pinned tabs from unloading` in sidebery's settings is already `off`. But the pinned tabs are still auto loaded when I start Firefox.

**Comment by albino1** [comment]
I'm not sure then, you might have to post a log so the developer can help you.

Also, you could maybe take a look at this post and check the deeper pinned settings:

https://github.com/mbnuqw/sidebery/issues/380#issuecomment-1734262392

FWIW, I have:

```
 "pinnedTabsPosition": "top",
 "pinnedTabsList": false,
 "pinnedAutoGroup": false,
 "pinnedNoUnload": false,
```

**Comment by c02y** [comment]
Thanks.

After I set `browser.sessionstore.restore_pinned_tabs_on_demand = true`, the pinned tabs are unloaded after I start Firefox which is what I want. The thing is like https://github.com/mbnuqw/sidebery/issues/380 the the pinned tabs' favicons are not dimmed.

I'll close this for now.

**Comment by TobiaszCudnik** [comment]
@c02y Are they really "unloaded" though? Or do they simply seem to load once you click them? You can check the unloeded status in `about:performance`, steps:

1. open a browser with pinned and unpinned tabs
2. unload everything
3. confirm `about:performance` contains only browser stuff (10-15 entries)
4. restart ff

Expected: `about:performance` stays the same

Result: all the pages, not just pinned tabs, are present in `about:performance`

The difference it makes is mem usage and the start speed. I suppose their cache is till being loaded on start and the tabs are actually **suspended**, which is different from **unloading** (the latter is newer).

It very annoying, as I restart my browser daily coz to mem leaks and have to wait a substantial time before even being able to unload anything.

**Comment by c02y** [comment]
@TobiaszCudnik I tried the steps, `about:performance` it not the same after I restart Firefox, it contains multiple tabs in the list, they are the pinned tabs, normal tabs are not in it, and the icons of the pinned tabs are all not dimmed, but if I click one of the pinned tabs, I can see the reloading process (both the Refresh button and the web page are reloading)

**Comment by TheInfamousAlk** [comment]
Pinned tabs still autoload for me on browser start as well despite "prevent pinned tabs from unloading" being off.

**Comment by occasionalbughunter** [comment]
Just go to about:config and set 
browser.sessionstore.restore_pinned_tabs_on_demand 
to TRUE.
Logos will still load, but pinned tabs will not load until you click on them.

**Comment by rostislaved** [comment]
this works:
browser.sessionstore.restore_pinned_tabs_on_demand = true

tabs are not active (but icons still look like they are).

I found the addon which makes them look like unloaded:
https://addons.mozilla.org/en-US/firefox/addon/discard-pinned-tabs-on-start/

Anyway it would be better to have sideberry option to not load pinned tabs on start
