### ISSUE TITLE
Massive CPU Usage Suddenly on Nightly

### ISSUE THREAD

**Issue by colemickens** [mbnuqw/sidebery#1388]
## Steps to reproduce

Hi, I don't know if this is due to a recent change in Nightly, but I noticed that Firefox was eating a ton of CPU and Firefox's Task Manager indicated that that was due to a WebExtension. 

I pretty quickly narrowed it down to SideBery.

This is with Sidebery disabled.

![screenshot-1702309774](https://github.com/mbnuqw/sidebery/assets/327028/d4ed5da8-aa64-45fb-adf6-36dca4f9264d)

This is immediately after re-enabling it.
![screenshot-1702309788](https://github.com/mbnuqw/sidebery/assets/327028/ca1c59b3-d9c4-480d-9a61-fa0f6ff76f10)

and it stay this high. In my non-work profile browser, I have considerably more tabs, and the problem is worse. I'm sitting at huge idle CPU usage, with literally every tab unloaded.

I'm not sure how else to help investigate, unfortunately.

I can't share logs from this session as it's my work browser. Later, i can repro in my other session and provide that log.

## Debug info

<details>
<summary><b>Addon data</b></summary>
     
```json
To get addon data: 
- Go to the Sidebery settings page - section "Help"
- Click on the "Debug info" button
- Copy and paste here inside this codeblock, replacing this text.
Note: all URLs, titles and other personal info are skipped.
```
</details>

<details>
<summary><b>Logs</b></summary>

```
To get logs: 
- Open DevTools (open this url in new tab: about:devtools-toolbox?id=%7B3c078156-979c-498b-8990-85f7987dd929%7D&type=extension).
- Navigate to "console" tab.
- Click on the trash bin icon (at the top-left) to clear console.
- Then try to reproduce the issue.
- If messages appear, copy and paste them here inside this codeblock, replacing this text.
```
</details>

**Comment by ongots** [comment]
@mbnuqw , there is an important problem here, on Firefox 122-123 Sidebery constantly loads processor

**Comment by serdarth** [comment]
I've found revoking History permission in Sidebery settings reduces CPU utilization back to normal levels on Firefox 122 beta X and onwards. It apparently also disables History panel for users that rely on this feature. So keep it in mind.

**Comment by colemickens** [comment]
@serdarth what made you think to try this? it does seem to help significantly for me as well.

**Comment by serdarth** [comment]
@colemickens good ol' trial and error actually. I thought it had to be one or a combination of the settings after creating a fresh Firefox profile and not reproducing the same behaviour on said profile with default sidebery configuration.
