### ISSUE TITLE
Add ability to UNLOAD tab

### ISSUE THREAD

**Issue by berliozz** [mbnuqw/sidebery#139]
## Description
Sometimes we use many tabs, but not all of it needed in time.
But modern web use scripts, dynamic content update, etc.
Adding option to Unload tab in context menu allow to decrease memory usage of firefox.

## Use cases
Select tab, click by right mouse button, select menu item Unload tab.
In this case tab will unloaded from memory, but stay in tree.

**Comment by mbnuqw** [comment]
This feature already implemented, its called 'Discard tab' ("zzZ" icon).
Also you can automatically discard folded tabs (with optional delay).

**Comment by berliozz** [comment]
Ooops, sorry. Thanks of great extension.

**Comment by mbnuqw** [comment]
Its okay, thanks
