### ISSUE TITLE
Tab scroll area width calculation

### ISSUE THREAD

**Issue by King-of-Infinite-Space** [mbnuqw/sidebery#1391]
## Steps to reproduce
- Open Firefox in [new profile](https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles)
- Install Sidebery
- Set "Scroll area width (px)" under "Mouse" -> "Switch tabs with scroll wheel"
- Scroll in the area

## Expected behavior

I assume this setting means the width that allows scrolling through the tabs. So the width (RightX - LeftX) should be equal to the set value. 

Something like this:
```ts
 if (area >= 0) { 
   Sidebar.scrollAreaRightX = area 
   Sidebar.scrollAreaLeftX = 0 
 } else if (area < 0) { 
   Sidebar.scrollAreaRightX = 0 
   Sidebar.scrollAreaLeftX = panelsBoxBounds.right + area
 } 
```
## Actual behavior

https://github.com/mbnuqw/sidebery/blob/2cbf82360a96ff6014a5f847f807f1542470c1da/src/services/sidebar.actions.ts#L173-L181

(also in L237-245)

Here larger value leads to smaller width to scroll tabs, so it's not behaving as intended.

## Debug info

<details>
<summary><b>Addon data</b></summary>
     
```json
To get addon data: 
- Go to the Sidebery settings page - section "Help"
- Click on the "Debug info" button
- Copy and paste here inside this codeblock, replacing this text.
Note: all URLs, titles and other personal info are skipped.
```
</details>

<details>
<summary><b>Logs</b></summary>

```
To get logs: 
- Open DevTools (open this url in new tab: about:devtools-toolbox?id=%7B3c078156-979c-498b-8990-85f7987dd929%7D&type=extension).
- Navigate to "console" tab.
- Click on the trash bin icon (at the top-left) to clear console.
- Then try to reproduce the issue.
- If messages appear, copy and paste them here inside this codeblock, replacing this text.
```
</details>

**Comment by llc0930** [comment]
As I comment in your PR (https://github.com/mbnuqw/sidebery/pull/1390#issuecomment-1859165017), I think you misunderstood.
