### ISSUE TITLE
Add option to Blacklist websites from creating sub-tree on opening link in new tab

### ISSUE THREAD

**Issue by Crunchbits** [mbnuqw/sidebery#1392]
## Description
Would be useful for websites where you do not need sub-trees. Of course, you should still be able to drag them into sub-trees, but it just won't do it automatically on opening link in new tab.

**Comment by mbnuqw** [comment]
Wontfix, because URL is unavailable on tab creation event (at that moment Sidebery decides where to place the new tab) and only updates some time later, so implementation of this feature will lead to double moving of tab and generally bug prone.
