### ISSUE TITLE
Sideberry crashes often

### ISSUE THREAD

**Issue by mbaz** [mbnuqw/sidebery#14]
I've been using Sideberry for less than two hours and it's crashed Firefox twice. I use Arch Linux, and Firefox 65.0.2.

I like the project and I'll keep watching it, but I will uninstall it for now.

**Comment by mbnuqw** [comment]
Can you please write what addons you use?
Also, did you use tabs tree structure and sync for containers (when firefox was crashed)?
Thanks.

**Comment by mbaz** [comment]
I use uMatrix, HTTPSEverywhere, Decentraleyes, and Nuke Everything.

The first time it crashed I was using the default settings. The second time, I was adjusting the settings. It crashed a short time after I had enabled tree structure; I was still going through the rest of the settings. However, when Firefox restarted, Sideberry still had the default settings -- my changes didn't stay.

Let me know if you need more information.

**Comment by mbnuqw** [comment]
Really appreciate additional details, thank you!
I'll dig into it soon.

**Comment by mbnuqw** [comment]
Finally got firefox crashed after few hours of intensive work with first three addons installed and lots of tabs!
But I can't reproduce it again. I'll keep looking...

**Comment by mbaz** [comment]
Thanks for trying. I do have lots of tabs open (maybe 400) across eight windows. Let me know if you want me to test something.

**Comment by ainola** [comment]
In contrast, I also run Archlinux (though I've only installed this on firefox 66) and I haven't had an issue yet. I keep significantly fewer tabs, usually around 15 and rarely ever more than 50.

Addons:

```
browserpass-ce
Buster: Captcha Solver for Humans
Cast Kodi
Cookie AutoDelete
Decentraleyes
HTTPS Everywhere
Sidebery
Tridactyl
uBlock Origin
uMatrix
Wallabagger
```

**Comment by mbnuqw** [comment]
@ainola, thanks for testing!

All right, I hope v2.2.0 will resolve this problem. At least, I cannot reproduce issue with firefox 67-66 and this version.

@mbaz, I will leave this opened for some time, if issue will appear again, please ping me.

Thanks you all.

**Comment by mbaz** [comment]
I've been running v2.2.1 with no problems for about an hour now... I'll report back after more intensive use.

**Comment by mbaz** [comment]
Things seems pretty solid, so I'll close this issue.
