### ISSUE TITLE
Option to promote only first child tab when parent is closed

### ISSUE THREAD

**Issue by Mrfiregem** [mbnuqw/sidebery#140]
## Description
Unless I'm missing it, an option to promote only the first child tab to the parent when the parent tab is closed would be great. This would keep the other child tabs under the new one

## Use cases
Helpful for keeping a branch together, since right now, all children move up one level if their parent is closed.

**Comment by mbnuqw** [comment]
Agreed, I plan to add more options for controlling this behavior.

**Comment by rsalmei** [comment]
I was opening an issue just for this!

Also related, when I've seen I lost my hierarchy, tried to CTRL+SHIFT+T to restore it.... Humpf, the tree was not restored as it were... Please do not forget about this.

Hey man, great work by the way, thanks!
I've had it installed for a long time, but never really used. Just a few days ago, my TreeStyleTab is not clicking anymore, so I switched to this... I'm liking it till now 👍

**Comment by Klohto** [comment]
This is the only feature that's missing that would make me migrate from TST. +1!

**Comment by mbnuqw** [comment]
Added in v4.9.0
Option "After closing parent tab, outdent:..." in Tabs Tree section.
