### ISSUE TITLE
[Feature request] Option to set ms on double click on a tab to collapse/expand

### ISSUE THREAD

**Issue by Zeioth** [mbnuqw/sidebery#1403]
## Description
When double clicking on a tree, it collapses/expand correctly. But there is a hard coded delay of 500ms before I can double click on the tree again. 

I assume this is in place so it doesn't conflict with animations. But I don't have animations enabled and I'd like it to be snappy.

There is some way to achieve this?

## More info
This 500ms delay only seems to be present on double click, and not when  I click on the collapse/expand icon.

So this might actually be a bug.

**Comment by mbnuqw** [comment]
Hm, it's a browser behavior (that delay between double-clicks). You can check it here: https://developer.mozilla.org/en-US/docs/Web/API/Element/dblclick_event#result
