### ISSUE TITLE
conflict Sidebery & SingleFile

### ISSUE THREAD

**Issue by labyrinth-to-solve** [mbnuqw/sidebery#142]
See https://github.com/gildas-lormeau/SingleFile/issues/365

**Comment by mbnuqw** [comment]
Thanks for the report! You need to turn on option "Highlight native tabs (in top horizontal bar) along with tabs in sidebar"
(its the last option in section "Tabs" in sidebery settings)

I think I need to update its title and maybe change its default state.

**Comment by mbnuqw** [comment]
Closing this as workaround exists.
