### ISSUE TITLE
Select range to start from active tab if there's no selected tab

### ISSUE THREAD

**Issue by rafaelliu** [mbnuqw/sidebery#1421]
## Description

The `Select range up/down` short cut seems ment to be used with the `Select up/down` and is not aware of active tab. This means users need to have bindings for `Switch next/prev tab` and `Select up/down`.

It would be very helpful if `Select range` started from the active tab. If it did, I suspect `Switch next/prev tab` shortcut would cover most of user's cases and in those cases there would be no need for additional bindings. It would be more intuitive too, if there's no selected tab, `Select range up/down` starts from the first tab or last tab which seems hardly useful.

**Comment by JhonDoe-x** [comment]
strongly agree!
