### ISSUE TITLE
shift + arrow shortcut

### ISSUE THREAD

**Issue by Mr7F** [mbnuqw/sidebery#1427]
# Description
Currently, we can not add a `shift + arrow` shortcut, it can be cool if it was possible
(because it's the same shortcut used in terminal to switch tabs)

**Comment by devgid** [comment]
It uses the Firefox browser's keyboard shortcuts to switch tabs.

Look into Firefox extensions that customizes default Firefox keyboard shortcuts.

**Comment by mbnuqw** [comment]
It's not possible: [Firefox requires "Ctrl", "Alt", "Command", or "MacCtrl" as first mandatory modifier](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/commands#key_combinations)
