### ISSUE TITLE
Coloured bar on tabs (like Containers)

### ISSUE THREAD

**Issue by binvius** [mbnuqw/sidebery#143]
Greetings from England!

I firmly believe Sideberry is one of the best extensions ever created for Firefox throughout the many many years I've been a user. However, there is just one extra addition that would be the cherry on top.

At the moment, I am reluctantly using containers to manually 'group' related tabs with a coloured indicator for efficient identification. Unfortunately but as expected, this reloads the tab into a container and as an unimportant consequence, makes using containers in the traditional fashion, much harder.

What I'd like to propose to maximise productivity for your users is to offer a separate option within the right click menu which allows users to do nothing but simply add a coloured bar to the left of the tab (in the same fashion containers add a coloured bar to the right. Or, even better, move the container coloured bar to the left and place this new simple tab colour on the right.)

Implementation should hopefully be as simple as duplicating the code for Containers into a new section called something like 'Colour Group Tabs' but unlike Containers, remove the mechanism that 'contains' the tab and reloads it, instead, simply places a user selected coloured bar on it for easy identification of related tabs. Bonus points if the colour could also be labelled and show that tag name on the tab.

(Completely separate request would be allowing the theme engine/style editor to colourise the Sideberry panel header (where users can switch between Sideberry, Bookmarks, History, etc.))

Please feel free to let me know if you require alternative explanation or any beta testing.

Huge thanks in advance for your consideration.

Warmest regards

**Comment by mbnuqw** [comment]
Thank you for so well described suggestion! I plan to implement the feature called "Tags" which hopefully will match your idea. I made a few experiments on how it could be displayed [here](https://github.com/mbnuqw/sidebery/issues/106#issuecomment-555643495), but its not final (I think, I'll add options to define styles of tags).

About the sidebar header:
![screenshot-2020-02-24 20:22:17](https://user-images.githubusercontent.com/6276694/75166137-41694780-5745-11ea-898f-ab65ea04865e.png)
It is a part of Firefox interface, so to change the style of it you can use different Firefox theme or use userChrome.css

**Comment by binvius** [comment]
Hey!
Many thanks for the swift responce - much appreciated!

I cannot appologise enough as I thought I had searched exstensively enough for previous requests but appear to have missed that one!

It looks ideal. I agree - allowing users to colourize/style the tags like they can with conatiners/panels would be ideal to match users theming.

Oh - cheers for pointing out the header is FF and not Sideberry. Silly really - should have realised it's done within userChrome.css.

All pretty now and very very very much looking forwad to your completion of something allowing tabs to me marked with a colour for easy indication. Will liteally be a game changer for my productivity so am sure for many others too.

Keep up the good work buddy and happy coding!

Warmest regards

**Comment by mbnuqw** [comment]
Implemented in v5: Tabs colorization via context menu
