### ISSUE TITLE
Handle Tab-Placement between Ctrl-T and opening external Links

### ISSUE THREAD

**Issue by powo** [mbnuqw/sidebery#1431]
## expected Behaviour

* When pressing Ctrl-T I would like to have a new Tab being opened as **last Child** of the currently opened tab
* When clicking a Link in some Application outside Firefox, I'd like it to be opened as a new "independant" Tab at **panel end**

## actual Behaviour

regardless of what I configure for 
  * "_Place new tab opened from another tab_"
  * "_Place new tab (general rule)_"
... both above mentioned use-cases always behave exactly identical ... either opening all tabs at the panel end or opening all new tabs/links as a child of the last/current opened Tab.

## Note

Until recently I've used TreeStyleTabs extension ... but since a few days, it suddenly had this described weird behaviour, so I gave Sideberry a try, and noticed it behaving exactly the same. Not sure if this has to du with some change in Firefox itself.

Unfortunately this makes me crazy now, because I end up searching for Tabs all the time, and that's exactly what I want Sideberry(or TreeStyleTabs) to solve :-( 

I'm using FF 121.0.1 on Linux and Sideberry 5.0.0.

**Comment by devgid** [comment]
See below screenshot of two underlined settings.

![image](https://github.com/mbnuqw/sidebery/assets/13977449/9c471d0d-8f0a-4608-95d3-ee7f869190b6)

With that setting in my setup a new Tab opens with Ctrl +T as last Child of the currently opened tab

I did notice the Place new tab (general rule) setting is used with Ctrl+T

**Comment by powo** [comment]
Yes, that works for opening new tabs with Ctrl-T.

but it has the side-effect, that now every Link I open from some other Application (eMail-Client, ...) opens a Link also as last-Child of the Tab that was opened in the Browser.

**Comment by devgid** [comment]
> Yes, that works for opening new tabs with Ctrl-T.
> 
> but it has the side-effect, that now every Link I open from some other Application (eMail-Client, ...) opens a Link also as last-Child of the Tab that was opened in the Browser.

New Tabs, External applications and toolbar bookmarks open in new tab are all New Tabs and will use the Place New Tab (General Rule) setting, so that makes sense because you set it to last child of Active tab. If you want external applications to open at bottom then change that settings  to End of Panel.

Then a possible workaround is to instead of using Ctrl+T, create your own keybinding in SideBery settings

e.g Create Keybinding
> Open a new tab as the last child of the active tab : Ctrl + Shift+ Down

or another alternative in Sidebery settings use a left or right long click customization.
 
> Long Right Click on Tab = new child tab.

**Comment by powo** [comment]
yep thx  - using another Shortcut instead of Ctrl-T ... is the workaround I went now ... and I'm slowly getting comfortable with it ;-) 

So I'll close this issue
