### ISSUE TITLE
Bug disabling Always Right plugin.

### ISSUE THREAD

**Issue by JAPMedia** [mbnuqw/sidebery#1445]
## Steps to reproduce
- Open Firefox in [new profile](https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles)
- Install Sidebery
- Install Always Right https://github.com/autonome/Always-Right/

## Expected behavior
Always Right  not working anymore

## Actual behavior
new tabs should open right to ne active tabs not working.

## Debug info

<details>
<summary><b>Addon data</b></summary>
     
```json
To get addon data: 
- Go to the Sidebery settings page - section "Help"
- Click on the "Debug info" button
- Copy and paste here inside this codeblock, replacing this text.
Note: all URLs, titles and other personal info are skipped.
```
</details>

<details>
<summary><b>Logs</b></summary>

```
To get logs: 
- Open DevTools (open this url in new tab: about:devtools-toolbox?id=%7B3c078156-979c-498b-8990-85f7987dd929%7D&type=extension).
- Navigate to "console" tab.
- Click on the trash bin icon (at the top-left) to clear console.
- Then try to reproduce the issue.
- If messages appear, copy and paste them here inside this codeblock, replacing this text.
```
</details>

**Comment by albino1** [comment]
Can you not just remove Always Right completely and just use the Sidebery tab opening settings to do what you're after?

**Comment by JAPMedia** [comment]
Yes, I just did that. 
I didn't know it was already in Slidebery. Wow, there are so many options in this plugin. Thanks for the great job!

**Comment by mbnuqw** [comment]
Expected interference of addons.
