### ISSUE TITLE
Option to show "new tab" button at the top

### ISSUE THREAD

**Issue by moritz-ferdinand-rocker** [mbnuqw/sidebery#1452]
I configured the sidebar in such a way, that new tabs appear at the panel start. Consequently it would be more logical and often faster, if the "new tab" button is placed at the top. At the moment one can choose "after tabs" or "bottom": I would love to see a third option "top". Thank you very much in advance!

**Comment by devgid** [comment]
Duplicate https://github.com/mbnuqw/sidebery/issues/1279

**Comment by emvaized** [comment]
This CSS will do it for now (considering you set your new tab button to be shown on "bottom"):

`.new-tab-btns { order: -1; }`
