### ISSUE TITLE
Feature Request: Add a "Menu within panel" set of context menus

### ISSUE THREAD

**Issue by nh-oriki** [mbnuqw/sidebery#1459]
Currently right clicking the blank space underneath your tabs seems to be handled as if you had clicked the panel's icon (so, it typically gives you several actions you can perform upon the group). However, since that space is more visible, I often right click there expecting it to give me a few "New..." options, similar to a file manager.

Because it seems like there are a variety of options for what you might want to do with such a menu, I think it'd probably be worth building it out with the existing customization stuff - this could also give the opportunity to make the context menu items' text a little bit clearer. For instance, "Save to bookmarks" is unclear when you're right clicking in the big empty space underneath all of your tabs, and if you don't notice the panel's icon highlighting, you may not know what it's saving the bookmarks for in that context. I also know that personally I generally can't think of why I'd want to delete a panel from actively _within_ it, so I'd probably remove that button myself.

My suggestion is to add a new menu to the existing set of menus, for "inside tabs panel" and "inside bookmarks panel". The menu options likely don't need to be substantially different, but should be changed so that it's more obvious that operations will take place upon the entire group. Alternatively, a quick-and-easy fix would likely be to visually highlight all of the items in the selected panel when a context menu is opened on it/within it.

**Comment by mbnuqw** [comment]
Don't see any contradictions in current behavior (although I should probably better visualize panel selection), and it seems to me strange to target "empty space". Sorry, wontfix.
