### ISSUE TITLE
Option to Close Other Tabs in Right-Click Menu

### ISSUE THREAD

**Issue by Zhuxb-Clouds** [mbnuqw/sidebery#1479]
## Description
Would you consider adding an option to close other tabs in the right-click menu? Or this feature already haved?

**Comment by mbnuqw** [comment]
You can add it in Context menu editor: Open sidebery settings > "Menu Editor" on the left side > Click on the needed, disabled (dimmed) option. To change it position, use arrow buttons or click on it to select it and use mouse wheel.
