### ISSUE TITLE
Panel Tab Rules Should Allow For Reopening Tab in Specified Container

### ISSUE THREAD

**Issue by Squire4Hire** [mbnuqw/sidebery#1483]
We can create rules that automatically move a tab into a panel when particular criteria are met. We can also automatically reassign a tab to a container when the tab is _dropped_ into a panel, and assign a container to a newly created tab inside a panel. However, there is currently no way to automatically reopen/reassign a tab to a specified container when the criteria to relocate the tab is met.

![image](https://github.com/mbnuqw/sidebery/assets/5404664/18dc2fba-18b1-4eee-bb1a-d208ba4a119f)

**Comment by mbnuqw** [comment]
It's a separate list of rules per container: Sidebery settings > Containers > Click on some container > Include / Exclude rules.
