### ISSUE TITLE
Sidebery Doesn't Sync Tab Panels??????????????????????????????????????????????????????????????????????????????????????????????

### ISSUE THREAD

**Issue by Neltulz** [mbnuqw/sidebery#1484]
Why the h*ll not? All value for this add-on is lost by not doing that. (Exaggerating, of course, but you get my point.  I love this add-on, but knowing that I can't backup the tab panels just reduced its usefulness by a neutron star mass amount)

## Steps to reproduce
- Flounder about as Sidebery's most useful feature isn't even backed up in Add-on Data and Sync Data

## Expected behavior
- Backup the tab panels

## Actual behavior
- Doesn't backup the tab panels

Snapshots show the tab panels, but how is that useful when the tab panels don't even get backed up?

**Comment by albino1** [comment]
Firefox Sync has size limits:

https://github.com/mbnuqw/sidebery/issues/54
