### ISSUE TITLE
Tab Close button dangerously close to resize handle.

### ISSUE THREAD

**Issue by cwmoriarty** [mbnuqw/sidebery#1486]
## Description
A tab's Close button is too close to the edge. Attempting to resize the sidebar sometimes closing a tab inadvertently, this has happened to me several times.

As a workaround, I've set `--tabs-close-btn-margin` to like `-100` to just move it elsewhere, but it would be cool to change the behavior. 

Perhaps putting the close button on a r-click menu, or over the favicon?

Thanks!

**Comment by SunnyZebra** [comment]
If you don't want to see the close button you could completely disable it in

`sidebery settings → tabs → show close button → no`

Rightclick menu seems to already exist.

alternative custom css if you just want to push it a bit away from the border
```css
.Tab .close {
  margin-right:10px;
}
```

**Comment by cwmoriarty** [comment]
> `sidebery settings → tabs → show close button → no`

Ah, great. Missed this. IMHO this should be the default!
