### ISSUE TITLE
Add option to define the export folder for snapshots

### ISSUE THREAD

**Issue by cluxter** [mbnuqw/sidebery#1489]
## Description
Right now, the feature to auto-export the snapshots automatically export them to the download folder of the browser.

This can be a problem because, for example in my case, I defined the download folder of Firefox as `/tmp/Web`. This is the equivalent of `C:\Users\<username>\AppData\Local\Temp\Web` or `C:\Windows\Temp\Web` in Windows. These folders are stored in RAM so their content is automatically deleted when the computer is off. So each time I turn my computer off (or worse: when there is an unexpected power cut) I lose all my snapshots.

I'm doing this because I don't keep 98% of what I download, and I don't want to spend time erasing the downloaded files (I always forget to erase them and I end up having hundreds of files sitting there, then I need to spend time sorting them all to be sure that I'm not deleting something I shouldn't). Some people may have other reasons.

This could be easily solved by adding a simple field where we could set the folder in which we want the snapshots to be saved.

**Comment by albino1** [comment]
Unfortunately, you can only store Snapshots [in the Firefox Downloads folder or a subdirectory within it](https://github.com/mbnuqw/sidebery/issues/1157#issuecomment-1666761894), so if your download directory is a temp folder then the Snapshots can only be stored in that temp folder.

**Comment by cluxter** [comment]
Alright, thank you very much. This is what I feared unfortunately.
Maybe I could mount a sub-directory of the temp folder on a permanent device so the data would become persistent. I will try.

**Comment by albino1** [comment]
Maybe you could symlink?  I'm not sure, I've never tried.

**Comment by mbnuqw** [comment]
Closing this as nothing can be done from Sidebery's side.
