### ISSUE TITLE
Sideberry isnt staying on the side.

### ISSUE THREAD

**Issue by VaiTheCatto** [mbnuqw/sidebery#1498]
## Steps to reproduce
(assuming you aldready have sideberry)
>Open The Firefox Browser
> open any type of left side opening panels, example history (ctrl+h), bookmarks (ctrl+B)

## Expected behavior
After closing the said panels, sideberry should return back to the side instead of having to click on it all the time.

## Actual behavior
It doesn't.

##
Note: I checked most of the settings and I don't see where the problem exactly is.

**Comment by albino1** [comment]
When you close those things you're closing the entire sidebar.  Instead, either just switch back to Sidebery using the drop down or hit your keybinding for Sidebery found in Settings -> Keybindings -> General -> Open/Close Sidebar Panel.  Mine is set to F2 for example.

**Comment by VaiTheCatto** [comment]
alright, thank you.
