### ISSUE TITLE
Copy Url on group tab should select child URLs as well or at least copy all selected tabs URLs

### ISSUE THREAD

**Issue by devgid** [mbnuqw/sidebery#1499]
## Description
If I use the right click context menu on a parent or group tab and select "Copy Url" and then paste to another program then it only pastes the current tab. I should copy all the selected tab URLs that were selected with Ctrl+Click. Or even better copy the child tab URLs as well.

![image](https://github.com/mbnuqw/sidebery/assets/13977449/94274df7-07df-4e9e-924e-7192e546bb84)

I have tried many Firefox extensions that copy the url but it only copies one url and not all the selected sidebery tabs I highlighted.
I think this is because browsers by default doesn't allow multi tab select.

**Comment by JohnVKRDam** [comment]
I disagree! That is not what I (would) expect this option to do.
One tab/group selected = one Url copied.
That is, IF THE PARENT IS OPEN! That's the distinction of importance!

The option should definitely NOT indiscriminately (always) copy all tabs/children, whatever the state of the parent (open/closed). That would seriously degrade usability of this fantastic option.

.

If you want to copy all the URLs, including children, do this:
- CLOSE the parent (which can be a tab or a group), then right-click
- You will see the option then says "URLs" and not "URL". See the difference?
With the parent CLOSED it will copy ALL the URLs, including ALL direct children and ALL GROUPS w/ their respective children.

The same is true for the COPY TITLE / TITLES right-click context menu option.

**Comment by devgid** [comment]
@JohnVKRDam Agree. sideberry allows you to select multiple tabs.(Ctrl+Click). Firefox does not. 
If you select multiple tabs and select copy URL then it only copies one and not all the selected tabs. Other Firefox extensions do the same with sidebery by only copying one url to clipboard

**Comment by JohnVKRDam** [comment]
May I ask what version of Sidebery you are running? Because I do not have that issue. I am on v5.1.1

If I select multiple tabs with Ctrl (or by using shift), then right-click, and choose "**_Copy URLs_**", all of the selected tab's URLs are copied to the clipboard. You will see that the option in the context menu has the text "**_Copy URLs_**" instead of "**_Copy URL_**".

**Comment by devgid** [comment]
@JohnVKRDam 

I realized its the UI that mislead me. The current visually open tab has a blue rectangle giving one the impression that it is selected. But it isn't. You have to explicitly click on it it again for it to be included in the Copy URL. You can see it visually that the background has to change to gray and not rely on the blue rectangle around the text which also occurs when multiple items are selected.
