### ISSUE TITLE
Conflicts with "Google Container" addon

### ISSUE THREAD

**Issue by zingyb** [mbnuqw/sidebery#15]
[Google container](https://addons.mozilla.org/en-US/firefox/addon/google-container/) (a fork of Mozilla's Facebook container, so same concept, different scum) wreaks havoc on sessions. Visiting a Google service will cause a new container workspace to replace all others, including the main workspace. I was only able to fix sidebery after uninstalling both and starting fresh with Sidebery.

Considering the featureset that Sidebery provides, both of these addons are not needed. But you might appreciate the information.

Firefox 66
Archlinux

**Comment by mbnuqw** [comment]
Thanks for reporting!

Hm... just tested it with Sidebery, it seems that this addon only creates new Google container on starting. Other containers leaved untouched and everything works...

Yes, with v2.2.0 you can create include/exclude rules for any sites you want.

Again, thanks for opening it, I'll test it more carefully little bit later and maybe add compatibility list in description.

**Comment by zingyb** [comment]
Hm, I'm unable to reproduce any more, so I'll close unless I come across it again.

Thanks for being awesome!
