### ISSUE TITLE
New tabs not showing up

### ISSUE THREAD

**Issue by aashish108** [mbnuqw/sidebery#151]
Hi, I have a situation where some new tabs opened do not register in the sidebar. Like links from Twitter (when I open in a new tab) and also when I open a new tab - it doesnt show up but I see it in Firefox's tab view. I guess this is a bug? Or is there a setting that I am missing?

Thanks!

## Environment info
OS:  Windows 10 Pro
Firefox version:  73.0.1
Addon version:  4.6.0

<details><code>
{
  "settings": {
    "version": "4.6.0",
    "nativeScrollbars": false,
    "ctxMenuNative": false,
    "autoHideCtxMenu": "none",
    "ctxMenuRenderInact": true,
    "navBarLayout": "horizontal",
    "navBarInline": false,
    "hideAddBtn": false,
    "hideSettingsBtn": false,
    "navBtnCount": true,
    "hideEmptyPanels": true,
    "navMidClickAction": "none",
    "navSwitchPanelsWheel": true,
    "groupLayout": "grid",
    "dndTabAct": true,
    "dndTabActDelay": 750,
    "dndTabActMod": "none",
    "dndExp": "pointer",
    "dndExpDelay": 0,
    "dndExpMod": "none",
    "stateStorage": "global",
    "warnOnMultiTabClose": "collapsed",
    "activateOnMouseUp": false,
    "activateLastTabOnPanelSwitching": true,
    "skipEmptyPanels": false,
    "showTabRmBtn": true,
    "showTabCtx": true,
    "hideInact": false,
    "activateAfterClosing": "next",
    "activateAfterClosingPrevRule": "visible",
    "activateAfterClosingNextRule": "tree",
    "activateAfterClosingGlobal": false,
    "activateAfterClosingNoFolded": false,
    "activateAfterClosingNoDiscarded": false,
    "shiftSelAct": true,
    "askNewBookmarkPlace": false,
    "tabsRmUndoNote": true,
    "nativeHighlight": false,
    "moveNewTabPin": "start",
    "moveNewTabParent": "last_child",
    "moveNewTabParentActPanel": false,
    "moveNewTab": "end",
    "pinnedTabsPosition": "panel",
    "pinnedTabsList": false,
    "tabsTree": true,
    "groupOnOpen": true,
    "tabsTreeLimit": "none",
    "hideFoldedTabs": false,
    "autoFoldTabs": false,
    "autoFoldTabsExcept": "none",
    "autoExpandTabs": false,
    "rmChildTabs": "none",
    "tabsChildCount": true,
    "tabsLvlDots": false,
    "discardFolded": false,
    "discardFoldedDelay": 0,
    "discardFoldedDelayUnit": "sec",
    "tabsTreeBookmarks": true,
    "bookmarksPanel": true,
    "warnOnMultiBookmarkDelete": "collapsed",
    "openBookmarkNewTab": false,
    "midClickBookmark": "open_new_tab",
    "actMidClickTab": false,
    "autoCloseBookmarks": false,
    "autoRemoveOther": false,
    "highlightOpenBookmarks": false,
    "activateOpenBookmarkTab": false,
    "showBookmarkLen": false,
    "bookmarksRmUndoNote": true,
    "fontSize": "m",
    "bgNoise": true,
    "animations": true,
    "animationSpeed": "fast",
    "theme": "default",
    "style": "dark",
    "sidebarCSS": false,
    "groupCSS": false,
    "snapNotify": true,
    "snapExcludePrivate": false,
    "snapInterval": 0,
    "snapIntervalUnit": "min",
    "snapLimit": 0,
    "snapLimitUnit": "snap",
    "hScrollThroughPanels": false,
    "scrollThroughTabs": "none",
    "scrollThroughVisibleTabs": false,
    "scrollThroughTabsSkipDiscarded": false,
    "scrollThroughTabsExceptOverflow": true,
    "scrollThroughTabsCyclic": false,
    "tabDoubleClick": "none",
    "tabLongLeftClick": "none",
    "tabLongRightClick": "none",
    "tabsPanelLeftClickAction": "none",
    "tabsPanelDoubleClickAction": "tab",
    "tabsPanelRightClickAction": "menu",
    "syncName": "",
    "syncSaveSettings": true,
    "syncSaveCtxMenu": true,
    "syncSaveStyles": true,
    "syncAutoApply": false
  },
  "permissions": {
    "allUrls": true,
    "tabHide": true,
    "actualAllUrls": true,
    "actualTabHide": true
  },
  "storage": {
    "size": "417.6 kb",
    "props": {
      "containers_v4": "2.2 kb",
      "expandedBookmarks": "18 b",
      "favAutoCleanTime": "10 b",
      "favUrls": "2.6 kb",
      "favicons": "399.5 kb",
      "panelIndex": "1 b",
      "panels_v4": "953 b",
      "prevTabsData_v4": "4 kb",
      "profileID": "14 b",
      "settings": "2.4 kb",
      "tabsData_v4": "5.6 kb"
    }
  },
  "panels": "TypeError: t is undefined",
  "cssVars": "TypeError: can't convert undefined to object",
  "windows": [
    {
      "state": "maximized",
      "incognito": false,
      "tabsCount": 51
    }
  ],
  "bookmarks": {
    "bookmarksCount": 2699,
    "foldersCount": 228,
    "separatorsCount": 0,
    "maxDepth": 6
  }
}
</code></details>

**Comment by mbnuqw** [comment]
Thanks for the report! It's definitely a bug. Hm... I'm suspecting that the reason can be the same as in #147 and #148. 

Could you list of the active addons, please?

**Comment by grahamperrin** [comment]
Also @aashish108 please, do you make use of the _panels_ feature of Sidebery?

**Comment by mbnuqw** [comment]
Closing this as stale. Please, reopen if the issue is reproduced in the latest version of Sidebery.
