### ISSUE TITLE
[Feature Request]: add icon-only items in native context menu

### ISSUE THREAD

**Issue by devxan** [mbnuqw/sidebery#1511]
## Description
Firefox's context menu looks great with these icon-only items at the top
![JshUCN_jb](https://github.com/mbnuqw/sidebery/assets/57809064/a75c587b-3fc7-48c3-8656-d5facf337411)
and Sidebery's non-native context menu has these, but only when the native menu toggle is off. (Unlike here:)
![HIjJSZ__q](https://github.com/mbnuqw/sidebery/assets/57809064/1c1e7d53-aff1-47f1-90d6-f59bee44ad81)
Could they be added, or is some technical limitation preventing this? (and sorry for the long screenshots; love your work here)

**Comment by mbnuqw** [comment]
It's not possible.
