### ISSUE TITLE
Change default behaviour for click on active tab

### ISSUE THREAD

**Issue by eriolloan** [mbnuqw/sidebery#1521]
I suggest changing the default behaviour for click on tab to be none.

I don't know of any mainstream browser doing anything when left-clicking on tabs and I think most users don't expect it would do anything particular, even in an extension. There may be a use case for this but it should not be the default.

The option is not very discoverable and I found the solution to my problem in the closed issue #1383. But reading documentation for each feature (if it exists and I doubt many users read docs) or looking for a solution on github is not something that comes naturally to a standard user probably not aware that github is a thing.

Feel free to skip the following User Story :
I lived a few months dealing with the tabs switching "randomly" (it took me a week to notice there was a logical "pattern" to this... I'm slow). It's been a real nuisance and I could not find the right setting for this, I expected to find something in general or tab sections (there are so many options in there, which is cool but a bit overwhelming when you think something is not working right) so I believed there was a bug on my side. I came to check here before ditching the extension solely because of this. At no point did I think it was a feature.

Anyway thanks for the amazing extension, I'll keep using it !

**Comment by Heyian** [comment]
I had no idea that if I clicked the active tab it would revert to the last tab, I upvote this suggestion.

**Comment by albino1** [comment]
Definitely seems like no action should be the default behavior if it's not already.

**Comment by mbnuqw** [comment]
You can turn off this behavior with "Activate previously active tab when clicking on the active tab (Tab flip)" setting (sidebery settings > mouse > tab actions).

Regarding the default value - agree. It should be opt-in.
