### ISSUE TITLE
Most hotkeys doesn't work unless sideberry is visible. That's a big turn off for many users.

### ISSUE THREAD

**Issue by s624** [mbnuqw/sidebery#1523]
## Description
If I hide the sideberry pannel, then many shortcuts(like jumpint to the next/previous active tab or jumping to the next or previous pannel) won't work.
I am on firefox on a laptop, small display. And so space matters to me, and I am sure space matters for many of us. 
If somehow we could use the hotkeys even when sideberry is not visible then it would be a major change on betterment. 

I am not an proficient coder. But I am an enthusiastic one. 
Let me know if I could help you in some way. 
Thank you for reading this far.

**Comment by mbnuqw** [comment]
Duplicate of #1178
