### ISSUE TITLE
Snapshots no longer created

### ISSUE THREAD

**Issue by nearcatch** [mbnuqw/sidebery#154]
## Steps to reproduce
Cannot create snapshots manually or with the automatic setting.

## Expected behavior
Clicking the snapshot button creates a snapshot.

## Actual behavior
Clicking the snapshot button does nothing.

## Environment info

OS: win
Firefox: 74.0
Addon: 4.6.2

<details><code>
{
  "settings": {
    "version": "4.6.2",
    "nativeScrollbars": true,
    "ctxMenuNative": false,
    "autoHideCtxMenu": "none",
    "ctxMenuRenderInact": true,
    "navBarLayout": "horizontal",
    "navBarInline": false,
    "hideAddBtn": true,
    "hideSettingsBtn": false,
    "navBtnCount": true,
    "hideEmptyPanels": false,
    "navMidClickAction": "none",
    "navSwitchPanelsWheel": false,
    "groupLayout": "list",
    "dndTabAct": false,
    "dndTabActDelay": 750,
    "dndTabActMod": "none",
    "dndExp": "pointer",
    "dndExpDelay": 0,
    "dndExpMod": "none",
    "stateStorage": "global",
    "warnOnMultiTabClose": "any",
    "activateOnMouseUp": true,
    "activateLastTabOnPanelSwitching": false,
    "skipEmptyPanels": false,
    "showTabRmBtn": false,
    "showTabCtx": true,
    "hideInact": true,
    "activateAfterClosing": "next",
    "activateAfterClosingPrevRule": "tree",
    "activateAfterClosingNextRule": "tree",
    "activateAfterClosingGlobal": false,
    "activateAfterClosingNoFolded": true,
    "activateAfterClosingNoDiscarded": true,
    "shiftSelAct": true,
    "askNewBookmarkPlace": true,
    "tabsRmUndoNote": true,
    "nativeHighlight": true,
    "moveNewTabPin": "end",
    "moveNewTabParent": "last_child",
    "moveNewTabParentActPanel": false,
    "moveNewTab": "end",
    "pinnedTabsPosition": "panel",
    "pinnedTabsList": false,
    "tabsTree": true,
    "groupOnOpen": true,
    "tabsTreeLimit": "none",
    "hideFoldedTabs": true,
    "autoFoldTabs": true,
    "autoFoldTabsExcept": 2,
    "autoExpandTabs": true,
    "rmChildTabs": "folded",
    "tabsChildCount": true,
    "tabsLvlDots": true,
    "discardFolded": false,
    "discardFoldedDelay": 0,
    "discardFoldedDelayUnit": "sec",
    "tabsTreeBookmarks": true,
    "bookmarksPanel": true,
    "warnOnMultiBookmarkDelete": "collapsed",
    "openBookmarkNewTab": false,
    "midClickBookmark": "open_new_tab",
    "actMidClickTab": false,
    "autoCloseBookmarks": false,
    "autoRemoveOther": false,
    "highlightOpenBookmarks": true,
    "activateOpenBookmarkTab": false,
    "showBookmarkLen": true,
    "bookmarksRmUndoNote": true,
    "fontSize": "m",
    "bgNoise": true,
    "animations": true,
    "animationSpeed": "fast",
    "theme": "default",
    "style": "dark",
    "sidebarCSS": true,
    "groupCSS": false,
    "snapNotify": true,
    "snapExcludePrivate": false,
    "snapInterval": 90,
    "snapIntervalUnit": "min",
    "snapLimit": 14,
    "snapLimitUnit": "day",
    "hScrollThroughPanels": false,
    "scrollThroughTabs": "none",
    "scrollThroughVisibleTabs": false,
    "scrollThroughTabsSkipDiscarded": false,
    "scrollThroughTabsExceptOverflow": true,
    "scrollThroughTabsCyclic": false,
    "tabDoubleClick": "reload",
    "tabLongLeftClick": "none",
    "tabLongRightClick": "none",
    "tabsPanelLeftClickAction": "none",
    "tabsPanelDoubleClickAction": "tab",
    "tabsPanelRightClickAction": "menu",
    "syncName": "DeeperThought",
    "syncSaveSettings": true,
    "syncSaveCtxMenu": true,
    "syncSaveStyles": true,
    "syncAutoApply": false
  },
  "permissions": {
    "allUrls": true,
    "tabHide": true,
    "actualAllUrls": true,
    "actualTabHide": true
  },
  "storage": {
    "size": "702.6 kb",
    "props": {
      "bookmarksMenu": "226 b",
      "bookmarksPanelMenu": "54 b",
      "containers_v4": "261 b",
      "disabledKeybindings": "24 b",
      "expandedBookmarks": "208 b",
      "favAutoCleanTime": "10 b",
      "favUrls": "30.5 kb",
      "favicons": "515.8 kb",
      "lastSnapTime": "13 b",
      "panelIndex": "1 b",
      "panels_v4": "947 b",
      "prevTabsData_v4": "72 kb",
      "profileID": "14 b",
      "settings": "2.4 kb",
      "sidebarCSS": "1.8 kb",
      "snapshots_v4": "2 b",
      "tabsData_v4": "77.4 kb",
      "tabsMenu": "299 b",
      "tabsPanelMenu": "144 b"
    }
  },
  "panels": [
    {
      "type": "bookmarks",
      "id": "bookmarks",
      "cookieStoreId": "bookmarks",
      "name": 9,
      "icon": "...",
      "bookmarks": true,
      "lockedPanel": false
    },
    {
      "type": "default",
      "id": "firefox-default",
      "name": 7,
      "icon": "...",
      "cookieStoreId": "firefox-default",
      "lockedTabs": false,
      "lockedPanel": false,
      "noEmpty": false,
      "newTabCtx": "none",
      "moveTabCtx": "none",
      "moveTabCtxNoChild": true
    },
    {
      "type": "tabs",
      "id": "Qf9vV8t_uFI9",
      "name": 7,
      "icon": "...",
      "color": "...",
      "customIconSrc": "",
      "customIcon": "",
      "lockedTabs": false,
      "lockedPanel": false,
      "noEmpty": false,
      "newTabCtx": "none",
      "moveTabCtx": "none",
      "moveTabCtxNoChild": true,
      "urlRulesActive": false,
      "urlRules": ""
    },
    {
      "type": "tabs",
      "id": "fiTbDpS9AQyX",
      "name": 9,
      "icon": "...",
      "color": "...",
      "customIconSrc": "",
      "customIcon": "",
      "lockedTabs": false,
      "lockedPanel": false,
      "noEmpty": false,
      "newTabCtx": "firefox-container-4",
      "moveTabCtx": "none",
      "moveTabCtxNoChild": true,
      "urlRulesActive": false,
      "urlRules": ""
    }
  ],
  "cssVars": "TypeError: can't convert undefined to object",
  "sidebarCSSLen": 1848,
  "windows": [
    {
      "state": "maximized",
      "incognito": false,
      "tabsCount": 663
    },
    {
      "state": "normal",
      "incognito": false,
      "tabsCount": 1
    }
  ],
  "tabsMenu": [
    [
      "undoRmTab",
      "mute",
      "reload",
      "bookmark"
    ],
    "separator-1",
    [
      {
        "name": "Move to"
      },
      "moveToNewWin",
      "moveToNewPrivWin",
      "moveToAnotherWin",
      "moveToWin"
    ],
    [
      {
        "name": "Reopen in"
      },
      "moveToCtr"
    ],
    "separator-2",
    "pin",
    "duplicate",
    "discard",
    "copyUrls",
    "separator-3",
    "group",
    "flatten",
    "separator-4",
    "clearCookies",
    "close"
  ],
  "bookmarksMenu": [
    [
      {
        "name": "Open in"
      },
      "openInNewWin",
      "openInNewPrivWin",
      "openInCtr"
    ],
    "separator-5",
    "createBookmark",
    "createFolder",
    "createSeparator",
    "separator-6",
    "sortByName",
    "sortByLink",
    "sortByTime",
    "separator-7",
    "copyUrls",
    "edit",
    "delete"
  ],
  "bookmarks": {
    "bookmarksCount": 4518,
    "foldersCount": 325,
    "separatorsCount": 1,
    "maxDepth": 8
  }
}
</code></details>

**Comment by mbnuqw** [comment]
The snapshot will NOT be created if the tabs are the same as in the previous snapshot. This can be the reason.

**Comment by aletaziar** [comment]
I tested this by opening several new tabs and trying to create snapshots and it didn't work. I also deleted all the snapshots and tried creating a new one, and it still didn't work.

Also, I noticed this because I have automated snapshots set and I could see that no snapshots were created for the past two days.

I have since restarted the browser several times and now I see one automated snapshot was created. I still cannot create one on demand, and I will have to wait to see if another automated one is created.

**Comment by mbnuqw** [comment]
Oh, this is definitely a bug. I'll investigate this later today. Thanks for reporting this!

**Comment by mbnuqw** [comment]
Could you try to remove limit(set zero) of snapshots and then try to create one?

**Comment by aletaziar** [comment]
I set the limit to 0 and pressed reload addon at the bottom of the page. It let me create new snapshots from both the settings section and from the snapshots viewer. I have put the limit back on and will let you know if the snapshots stop working again.

**Comment by mbnuqw** [comment]
Thank you for checking this.

**Comment by aletaziar** [comment]
Following up on this: snapshots seem to still work ok, but they stopped today. The earliest snapshot I have is from 3/12, and I have the snapshot limit set to 14 days. Automatic snapshots are set to every 3 hours. Does this mean no more snapshots will be taken until I delete some old ones? I assumed older automatic snapshots would be cleared as needed.

**Comment by mbnuqw** [comment]
`Does this mean no more snapshots will be taken until I delete some old ones?`
No, Sidebery will (well, should) automatically remove snapshots beyond the limit.

I've found and fix a few bugs that can potentially prevent creation of snapshots. Will upload new version soon.

**Comment by mbnuqw** [comment]
@aletaziar, could you check this behavior in v4.7.0?

**Comment by nearcatch** [comment]
(changed my name)

Sorry, seems like I never responded to this. Snapshots are working great now. I have scheduled snapshots from the past week for every 3 hours.

**Comment by mbnuqw** [comment]
Good! I'm closing this then.

**Comment by Keagel** [comment]
Sorry to be the bearer of bad news but I think this should be reopened @mbnuqw 
I have had a few instances of this happening recently. I'm not sure what's causing it but for example yesterday after 6 PM snapshots were no longer being created. I did have different tabs and when I noticed it a few hours later, pressing "Create snapshot" did nothing.
Interestingly, when I restarted Firefox this morning it created a snapshot immediately and the number of tabs is, as you can see, different:

![image](https://user-images.githubusercontent.com/18720666/84416580-b2f5d480-ac14-11ea-88d3-375e26bf3cbb.png)

Another thing, but I'm not sure if that's a bug or if snapshots are created individually for each window and in that case only the modified window is saved, but this also happens from time to time:

![image](https://user-images.githubusercontent.com/18720666/84416735-e3d60980-ac14-11ea-8169-d973bf5f5595.png)

As you can see, the first three snapshots in the screenshot (the last three created) only have one window, despite me never having closed the other window. If that's a bug I'll gladly open a new issue.

**Comment by Keagel** [comment]
For the second bug, I checked what's happening with the debugger and it appears this.windows is incorrect and only returns one window instead of two.

![image](https://user-images.githubusercontent.com/18720666/84418222-21d42d00-ac17-11ea-945c-b6e9a24f04df.png)

**Comment by ffabbroc** [comment]
I know it's been almost 2 years since any activity on this issue but this problem continues to happen for me.

I'm using Sideberry 4.10.2 on Firefox for macOS 13.2.1.

It seems to happen after FF has been running for some time. Usually, if I restart FF then I am able to create a snapshot manually.

The problem for is, sometimes after restarting FF some of my Sideberry tabs get "flattened".

And I have a LOT of tabs in Sideberry so this is painful to recover from unless I have a recent snapshot...but I don't have a recent snapshot. :(

Happy to provide more info....

Thanks,
Francesco

**Comment by albino1** [comment]
Sidebery v4 is mostly abandoned, you'll either need to switch to v5, which is beta, or just wait until it gets out of beta and released to the addon store.  FWIW, most of the people here are using v5 beta now with no issues.  You can find the most recent beta release here:

https://github.com/mbnuqw/sidebery/releases/tag/v5.0.0b31

**Comment by ffabbroc** [comment]
albino1, have I been living under a rock!
I've upgraded to the latest beta and so far so good.
Thanks!
