### ISSUE TITLE
"Close subtree" button

### ISSUE THREAD

**Issue by ColonelPhantom** [mbnuqw/sidebery#1540]
### Description

It would be nice if there was a way to right-click a subtree of tabs to close it entirely.

Currently, I seem to be able to achieve it by folding and then closing, but right-click -> "close group" or similar would be nice to have.

I'm not sure what the best name for such a button would be, though.

**Comment by mbnuqw** [comment]
Already possible:
- Right click on close button of the parent tab
- or Right click on the favicon of the parent tab (it will select the whole branch and open context menu) > Click on "close"
