### ISSUE TITLE
Auto-save to bookmarks when converted to Bookmark panel

### ISSUE THREAD

**Issue by redrockvp** [mbnuqw/sidebery#1541]
### Description

Its awesome that we can save a whole panel as a bookmark folder with the structure, but I'd love to have the ability to turn on an auto-save option once a panel is converted so that I don't have to re-save the bookmarks if I close/open tabs. 

This would ultimately mean that we can have a project context that is persistent, even across machines.

**Comment by redrockvp** [comment]
This would basically be the same functionality as Edge's "Workspaces"

**Comment by mbnuqw** [comment]
Merging with #1352
