### ISSUE TITLE
Ctrl-E can't be disabled

### ISSUE THREAD

**Issue by unera** [mbnuqw/sidebery#1542]
### Steps to reproduce

Hi, there!

I've just installed sidebery plugin (before I used 'Tree style tab').

It's great! Thanks for your work!

But there is one small problem.

Many sites (for example notion, github, etc) use `Ctrl-E` shortcut as `<code markup key>`.

But sidebery catches the key and don't free even if I change the key in Options.

I tried to drop the shortcut, change it to `Ctrl-period` (like screenshot), but `Ctrl-E` always closes/opens sidebery panel.

![My Key Options](https://github.com/mbnuqw/sidebery/assets/538980/8e01d479-9b3f-406c-b9b5-f207ad301f32)

So, could you fix the?

### Actual behavior

see above

### Expected behavior

see above

### System

Linux/Debian

### Firefox version

124.0

### Sidebery version

5.2.0 (2024-03-21).

**Comment by mbnuqw** [comment]
Can't reproduce. Could you try to set Ctrl+Period and then restart Firefox? If this helps, it's probably this Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1881820

**Comment by unera** [comment]
Oh, Firefox restart solved the problem! 

Try: `this is a code`.
Works fine, thanks!

Looks like Firefox bug.

**Comment by mbnuqw** [comment]
Should be fixed from Firefox v125 (Firefox Beta/Dev 125.0b6 and current Nightly)
