### ISSUE TITLE
Main menu is broken from time to time

### ISSUE THREAD

**Issue by unera** [mbnuqw/sidebery#1544]
### Steps to reproduce

Hi, there.

I have some tab lists: "Главная", "Личное", etc (sorry for non English screenshot)

![изображение](https://github.com/mbnuqw/sidebery/assets/538980/4914ad7d-6c87-4ae5-b286-15222b176311)

Also I enabled `bookmark` button at sidebery panel:

![изображение](https://github.com/mbnuqw/sidebery/assets/538980/6f15c4e9-5055-436e-a39f-9018bce69a76)

There is a bug in main menu list (I can't create screenshot) - button "Главная" at the first screenshot.

If I click "Главная" and then "Bookmarks"

The menu showes menutiem "Главная" that allows return to sidebery (and bookmarks menu is showed and sidebery panel isn't showed).

![изображение](https://github.com/mbnuqw/sidebery/assets/538980/f7e9d898-27c8-493e-bb5e-6774673ae021)

But if I enter into Bookmarks by sidebery's button (second screenshot), I see:

![изображение](https://github.com/mbnuqw/sidebery/assets/538980/d4db4400-ca23-41f6-9da7-39020dab4e24)

- sidebery panel is showed **(not as in the first example)**
- but main menu doesn't contain menuitem "Главная" **(not as in the first example)**

So, problems list:

- I think menu in the first and second cases should be the same.
- I think that in the first example sidebery should show its bars, too.

### Actual behavior

see above

### Expected behavior

see above

### System

Linux/Debian

### Firefox version

124.0

### Sidebery version

5.2.0 (2024-03-21).

**Comment by unera** [comment]
Also

Is there any way to disable (hide) main menu (and close button)?

(Главная and X)
![screenshot](https://github.com/mbnuqw/sidebery/assets/538980/3e554b91-f568-4a27-8498-74380db813ae)

**Comment by mbnuqw** [comment]
This header with drop down list is part of Firefox and cannot be removed/controlled by addon. Addons also can't open/close default Bookmarks sidebar (your second screenshot), so Sidebery implements its own bookmarks panels (your third screenshot).

Area that can be controlled by addon: https://github.com/mbnuqw/sidebery/discussions/1502#discussioncomment-8665214

To edit that sidebar header, use userChrome hacks: https://www.reddit.com/r/FirefoxCSS/search?q=Sidebar+header&restrict_sr=on

**Comment by unera** [comment]
The css helps to drop the header. Thanks!

```css
#sidebar-box #sidebar-header {  
      visibility: collapse !important;
}
```
