### ISSUE TITLE
Add attribute for tab that is playing audio but muted

### ISSUE THREAD

**Issue by aletaziar** [mbnuqw/sidebery#156]
There are attributes for audio playing (`[data-audible]`) and muted tabs (`[data-muted]`). I would like an attribute for a tab that is playing audio but still muted, perhaps `[data-silenced]`. My goal is to create a css style for tabs that are trying to play audio but are muted.

The default firefox tabs have the attributes `[soundplaying]` and `[muted]`, but `[muted]` tabs that are playing audio silently also have the attribute `style="--soundplaying-removal-delay:2700ms;"`, which can combine with `[muted]` to style tabs with silent audio.

**Comment by mbnuqw** [comment]
You can try to use both`data-audible` and `data-muted` attributes.
```css
.Tab[data-audible][data-muted] {
...
}
```

**Comment by aletaziar** [comment]
That doesn't work because `[data-audible]` is removed from the tab when the tab is muted.

**Comment by mbnuqw** [comment]
hm... indeed.
But this means that I won 't be able to determine if the muted tab is playing or not.

**Comment by mbnuqw** [comment]
Yeap, just checked this. Unfortunately this is impossible to implement. Internally, I have two flags: audible and muted. After user mute the tab, audible flag is updating to false and I cannot know if this is because user mute the tab or the tab is stop playing.

**Comment by aletaziar** [comment]
Couldn't you check the default firefox tab? It is styled with `style="--soundplaying-removal-delay:2700ms;"` when audio is playing, even if the tab is muted.

**Comment by mbnuqw** [comment]
No. Firefox extensions these days cannot read/modify Firefox layout. Sorry.

**Comment by aletaziar** [comment]
Ok, thanks anyway. Here is the code I was using for the audio notifications if you're interested.
```
/* Style tabs for audio events */
:root {
    --pulse-circle-diameter: 40px;
}
@keyframes pulse-circle {
    0% {
        height: 0px;
        width: 0px;
        opacity: 1;
        top: 50%;
        left: 50%;
    }
    100% {
        height: var(--pulse-circle-diameter);
        width: var(--pulse-circle-diameter);
        opacity: 0;
        top: calc(50% - var(--pulse-circle-diameter) / 2);
        left: calc(50% - var(--pulse-circle-diameter) / 2);
    }
}
@keyframes pulse-bg {
    0% {
        opacity: 0;
    }
    100% {
        opacity: 0.4;
    }
}
.Tab[data-audible] .fav::after {
    content: '';
    position: absolute;
    height: 0px;
    width: 0px;
    background: #FFF;
    border-radius: 50%;
    opacity: 0;
    z-index: -1;
    pointer-events: none;
    touch-action: none;
    animation: pulse-circle 1s ease-out 0s infinite;
}
.Tab[data-audible][data-muted] .fav::after {
    background: red;
}
.Tab[data-muted]:not([data-audible]) .fav::after {
    content: '';
    position: absolute;
    top: -7px;
    left: -7px;
    height: 30px;
    width: 30px;
    background: red;
    border-radius: 2px;
    opacity: 0;
    z-index: -1;
    pointer-events: none;
    touch-action: none;
    animation: pulse-bg 1.25s ease-out 0s infinite alternate;
}
```
