### ISSUE TITLE
Turning off "Preserve tree on creating bookmarks" doesn't work

### ISSUE THREAD

**Issue by iFUCKINGHATEcomputers** [mbnuqw/sidebery#1570]
### Steps to reproduce

- Turn off "Preserve tree on creating bookmarks"
- Drag the parent tab of a tree into bookmarks

### Actual behavior

- It bookmarks the entire tree

### Expected behavior

- It's only supposed to bookmark the parent tab

### System

Windows 7

### Firefox version

115.9.1esr

### Sidebery version

5.2.0

**Comment by mbnuqw** [comment]
Not a bug, it's a "feature" of Sidebery drag-and-drop: it selects the whole branch when you drag the root tab.
For the option to turn it off, track the #511 issue
