### ISSUE TITLE
Add an "empty" style option

### ISSUE THREAD

**Issue by Baerbeisser** [mbnuqw/sidebery#1574]
### Description

In styling settings, there's themes "Proton" and "Simple", density, farb scheme and font size settings.
But sometimes, people want to do something different than the dev envisioned while creating the theme and setting his variables. For example, i had a hard time figuring out how to tweak size and padding/margin of tabs in Proton style.
Tree Style Tabs had this option, which made  it simpler creating my prefered minimalist flat style from scratch.
Would adding something like an "empty" setting be possible?

**Comment by mbnuqw** [comment]
wontfix, workaround: [use `all` property to reset styles](https://developer.mozilla.org/en-US/docs/Web/CSS/all)
