### ISSUE TITLE
Add option to adhere to historical order of tabs visisted when closing or going to previous opened, if previous tab is in another panel

### ISSUE THREAD

**Issue by devgid** [mbnuqw/sidebery#1584]
### Description

I have multiple panels set up, each panel has its automove rule based on domain name.

1. I have a panel shopping. I have setup an automove rule to move any site with the name amazon.com to that panel.
2. I am in panel Main. I enter either the url amazon.com in the browser url
3. If "Switch panel after auto moving active tab to another panel" is "always",  then the panel Shopping Panel website is shown and Shopping panel is is shown
4. Then when I press Ctrl+ Shift+ tab to move to the prev opened tab ,I don't go to the last tab I opened in Panel Main. but instead the previous shopping tab in the Shopping Panel.
Same with when I press Ctrl+W to close the shopping tab,vit moves to the prev tab in shopping panel and  and not the last tab I am from in Panel Main. 

What I would want is that Ctrl+Shift+Tab moves me back to the originating panel (historical order. Same with Ctrl+W to close the just opened shopping tab)

Even if I set "Automatically switch panel on activating tab of another panel" to No then if I close the shopping tab or go to previous tab it goes to the previous shopping tab and not previous opened tab.

What I would like is a setting to force it to keep historical/previous opened order when using Ctrl+Shit+Tab or Ctrl+W

**Comment by mbnuqw** [comment]
Sidebery can't handle `Ctrl[+Shift]+Tab` keybindings (and any other Firefox keybindings like `Ctrl+T`, `Ctrl+W` and so on...). Given that, the only workaround I can suggest is to use Sidebery's keybindings: "Tabs activation history"
