### ISSUE TITLE
don't load tab until mouse up

### ISSUE THREAD

**Issue by colemickens** [mbnuqw/sidebery#1593]
### Description

I want/need to drag move tabs without them loading. This is not possible because (As with a number of other sideberry mouse actions) they trigger on mouse-down instead of mouse-up. (I find this to be counter to virtually all other desktop mouse use cases).

**Comment by mbnuqw** [comment]
Already possible: Sidebery settings > Mouse > Tab actions > Activate tab on mouse button release: on

**Comment by colemickens** [comment]
Wow, thank you! Sorry for the noise. What amazing software! :)
