### ISSUE TITLE
Sort tabs once each N seconds

### ISSUE THREAD

**Issue by valeriy-zainullin** [mbnuqw/sidebery#1599]
### Description

Right now there is an option to sort tabs, but it requires user interaction. Is it possible to have it run automatically?

Right now I use a patched Sort Tabs By Domain (https://github.com/valeriy-zainullin/w3x-taborder), it doesn't work well with separate panels feature.
I understand that there should be more than one person who wants  the feature for it to be implemented.

**Comment by rieje** [comment]
Using a binding to sort tabs is not enough? Sounds like a nightmare having order of tabs change periodically automatically and requires an internal timer for a trivial operation.

**Comment by valeriy-zainullin** [comment]
> Using a binding to sort tabs is not enough? Sounds like a nightmare having order of tabs change periodically automatically and requires an internal timer for a trivial operation.

I wanted my clutter to self organize. Not interact with it for the thing to happen. Yeah, tabs may slip out of pointer due to sorting. I have small number of tabs in panels in sidebery and it doesn't make me search tabs.

Thanks for your opinion!

But I may be the only one, who wants the feature.  So if someone else shows up, who needs that, maybe the idea is useful. Otherwise, it's a special case :)

**Comment by albino1** [comment]
Personally, if my tabs were somewhere, and then suddenly they were somewhere else, I would lose my mind.  But everybody's needs are different I guess.

**Comment by valeriy-zainullin** [comment]
I've actually topic-separated my tabs into panels. And now I think a hotkey is enough.
