### ISSUE TITLE
Dragging pinned tabs to reorder them causes the drop target line to get stuck

### ISSUE THREAD

**Issue by jathek** [mbnuqw/sidebery#163]
## Steps to reproduce
1. Pin 3 tabs [A, B, C].
2. Drag tab C to the left so the order is now [A, C, B].

## Expected behavior
Drop target line should disappear.

## Actual behavior
Drop target line is stuck, and is the target line for non-pinned tabs. The stuck target line interferes with clicking the first pinned tab. If you drag a non-pinned tab it resets the target line.

## Environment info

OS: win
Firefox: 75.0
Addon: 4.6.2

<details><code>
{
  "settings": {
    "version": "4.6.2",
    "nativeScrollbars": true,
    "ctxMenuNative": false,
    "autoHideCtxMenu": "none",
    "ctxMenuRenderInact": true,
    "navBarLayout": "horizontal",
    "navBarInline": false,
    "hideAddBtn": true,
    "hideSettingsBtn": false,
    "navBtnCount": true,
    "hideEmptyPanels": false,
    "navMidClickAction": "none",
    "navSwitchPanelsWheel": false,
    "groupLayout": "list",
    "dndTabAct": false,
    "dndTabActDelay": 750,
    "dndTabActMod": "none",
    "dndExp": "pointer",
    "dndExpDelay": 0,
    "dndExpMod": "none",
    "stateStorage": "global",
    "warnOnMultiTabClose": "any",
    "activateOnMouseUp": true,
    "activateLastTabOnPanelSwitching": false,
    "skipEmptyPanels": false,
    "showTabRmBtn": false,
    "showTabCtx": true,
    "hideInact": true,
    "activateAfterClosing": "next",
    "activateAfterClosingPrevRule": "visible",
    "activateAfterClosingNextRule": "tree",
    "activateAfterClosingGlobal": false,
    "activateAfterClosingNoFolded": true,
    "activateAfterClosingNoDiscarded": true,
    "shiftSelAct": true,
    "askNewBookmarkPlace": true,
    "tabsRmUndoNote": true,
    "nativeHighlight": true,
    "moveNewTabPin": "end",
    "moveNewTabParent": "last_child",
    "moveNewTabParentActPanel": false,
    "moveNewTab": "end",
    "pinnedTabsPosition": "panel",
    "pinnedTabsList": false,
    "tabsTree": true,
    "groupOnOpen": true,
    "tabsTreeLimit": "none",
    "hideFoldedTabs": true,
    "autoFoldTabs": true,
    "autoFoldTabsExcept": 2,
    "autoExpandTabs": true,
    "rmChildTabs": "folded",
    "tabsChildCount": true,
    "tabsLvlDots": true,
    "discardFolded": false,
    "discardFoldedDelay": 0,
    "discardFoldedDelayUnit": "sec",
    "tabsTreeBookmarks": true,
    "bookmarksPanel": true,
    "warnOnMultiBookmarkDelete": "collapsed",
    "openBookmarkNewTab": false,
    "midClickBookmark": "open_new_tab",
    "actMidClickTab": false,
    "autoCloseBookmarks": false,
    "autoRemoveOther": false,
    "highlightOpenBookmarks": true,
    "activateOpenBookmarkTab": false,
    "showBookmarkLen": true,
    "bookmarksRmUndoNote": true,
    "fontSize": "m",
    "bgNoise": true,
    "animations": true,
    "animationSpeed": "fast",
    "theme": "default",
    "style": "dark",
    "sidebarCSS": true,
    "groupCSS": false,
    "snapNotify": true,
    "snapExcludePrivate": false,
    "snapInterval": 90,
    "snapIntervalUnit": "min",
    "snapLimit": 14,
    "snapLimitUnit": "day",
    "hScrollThroughPanels": false,
    "scrollThroughTabs": "none",
    "scrollThroughVisibleTabs": false,
    "scrollThroughTabsSkipDiscarded": false,
    "scrollThroughTabsExceptOverflow": true,
    "scrollThroughTabsCyclic": false,
    "tabDoubleClick": "reload",
    "tabLongLeftClick": "none",
    "tabLongRightClick": "none",
    "tabsPanelLeftClickAction": "none",
    "tabsPanelDoubleClickAction": "tab",
    "tabsPanelRightClickAction": "menu",
    "syncName": "DeeperThought",
    "syncSaveSettings": true,
    "syncSaveCtxMenu": true,
    "syncSaveStyles": true,
    "syncAutoApply": false
  },
  "permissions": {
    "allUrls": true,
    "tabHide": true,
    "actualAllUrls": true,
    "actualTabHide": true
  },
  "storage": {
    "size": "3.8 mb",
    "props": {
      "bookmarksMenu": "226 b",
      "bookmarksPanelMenu": "54 b",
      "containers_v4": "261 b",
      "disabledKeybindings": "24 b",
      "expandedBookmarks": "97 b",
      "favAutoCleanTime": "10 b",
      "favUrls": "32.6 kb",
      "favicons": "572.5 kb",
      "lastSnapTime": "13 b",
      "panelIndex": "1 b",
      "panels_v4": "947 b",
      "prevTabsData_v4": "155.1 kb",
      "profileID": "14 b",
      "settings": "2.4 kb",
      "sidebarCSS": "2.8 kb",
      "snapshots_v4": "3 mb",
      "tabsData_v4": "74 kb",
      "tabsMenu": "350 b",
      "tabsPanelMenu": "144 b"
    }
  },
  "panels": [
    {
      "type": "bookmarks",
      "id": "bookmarks",
      "cookieStoreId": "bookmarks",
      "name": 9,
      "icon": "...",
      "bookmarks": true,
      "lockedPanel": false
    },
    {
      "type": "default",
      "id": "firefox-default",
      "name": 7,
      "icon": "...",
      "cookieStoreId": "firefox-default",
      "lockedTabs": false,
      "lockedPanel": false,
      "noEmpty": false,
      "newTabCtx": "none",
      "moveTabCtx": "none",
      "moveTabCtxNoChild": true
    },
    {
      "type": "tabs",
      "id": "Qf9vV8t_uFI9",
      "name": 7,
      "icon": "...",
      "color": "...",
      "customIconSrc": "",
      "customIcon": "",
      "lockedTabs": false,
      "lockedPanel": false,
      "noEmpty": false,
      "newTabCtx": "none",
      "moveTabCtx": "none",
      "moveTabCtxNoChild": true,
      "urlRulesActive": false,
      "urlRules": ""
    },
    {
      "type": "tabs",
      "id": "fiTbDpS9AQyX",
      "name": 9,
      "icon": "...",
      "color": "...",
      "customIconSrc": "",
      "customIcon": "",
      "lockedTabs": false,
      "lockedPanel": false,
      "noEmpty": false,
      "newTabCtx": "firefox-container-4",
      "moveTabCtx": "none",
      "moveTabCtxNoChild": true,
      "urlRulesActive": false,
      "urlRules": ""
    }
  ],
  "cssVars": "TypeError: can't convert undefined to object",
  "sidebarCSSLen": 2780,
  "windows": [
    {
      "state": "maximized",
      "incognito": false,
      "tabsCount": 665
    }
  ],
  "tabsMenu": [
    [
      "undoRmTab",
      "mute",
      "reload",
      "bookmark"
    ],
    "separator-1",
    [
      {
        "name": "Move to"
      },
      "moveToNewWin",
      "moveToNewPrivWin",
      "moveToAnotherWin",
      "moveToWin"
    ],
    [
      {
        "name": "Reopen in"
      },
      "moveToCtr"
    ],
    "separator-2",
    [
      "pin",
      "duplicate",
      "discard",
      "copyUrls"
    ],
    "separator-3",
    [
      "moveToPanel"
    ],
    "separator-3795259787627495",
    [
      "group",
      "flatten"
    ],
    "separator-4",
    [
      "clearCookies",
      "close"
    ]
  ],
  "bookmarksMenu": [
    [
      {
        "name": "Open in"
      },
      "openInNewWin",
      "openInNewPrivWin",
      "openInCtr"
    ],
    "separator-5",
    "createBookmark",
    "createFolder",
    "createSeparator",
    "separator-6",
    "sortByName",
    "sortByLink",
    "sortByTime",
    "separator-7",
    "copyUrls",
    "edit",
    "delete"
  ],
  "bookmarks": {
    "bookmarksCount": 4519,
    "foldersCount": 326,
    "separatorsCount": 0,
    "maxDepth": 8
  }
}
</code></details>

**Comment by mbnuqw** [comment]
Thanks for the report, yes I can reproduce this. Also I found a few other issues related to moving pinned tabs. I'll try to fix them to the next release.

**Comment by mbnuqw** [comment]
Should be fixed now
