### ISSUE TITLE
Restore last closed tab by middle click

### ISSUE THREAD

**Issue by VVelda** [mbnuqw/sidebery#167]
## Description

Hello, I'd like to see option to set action after middle click onto tabs panel's free space (just like there's settings for double click and so on). I'd like to use it for restoring the last closed tab (undo close tab). (That was default action for Tab Mix Plus in the old days btw.)

I think this would be beneficial to many others, as they could set different action to this event, or set this action to different event. (I think this option should be possible to set for the other types of click too)

**Comment by mbnuqw** [comment]
Ok, this is simple to do, so I'll add this option soon.

**Comment by mbnuqw** [comment]
Landed in v4.7.0
