### ISSUE TITLE
On opening, scroll so that active tab is visible

### ISSUE THREAD

**Issue by tkafka** [mbnuqw/sidebery#17]
When I have many tabs open (which is why I use Sidebery and love it :)), I often show and hide the sidebar. Currently, on opening the list is scrolled to the top, so my currently open tam might not be visible.

Proposed behavior: On opening, scroll down so that current tab is in viewport.

I don't know FF extension API, but on web https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView should help:

    element.scrollIntoView({ behavior: 'smooth', block: 'center' })

It will probably need to be delayed until after the tabs are loaded (it takes a few hundred milliseconds after starting an extension).

What do you think?

**Comment by mbnuqw** [comment]
Thanks for reporting! I'll fix it in next version (2.2.2)

**Comment by tkafka** [comment]
Awesome! You rock! :)

**Comment by mbnuqw** [comment]
Fixed in v2.2.2

**Comment by tkafka** [comment]
Wow, that was quick! Do you have PayPal 🍺?

**Comment by mbnuqw** [comment]
No, thank you. It's enough that you've written report about this bug.
