### ISSUE TITLE
Sort the contents of a panel

### ISSUE THREAD

**Issue by grahamperrin** [mbnuqw/sidebery#170]
Where tabs are spread across multiple Sidebery panels: 

* the sort features of [FoxyTab](https://addons.mozilla.org/addon/foxytab/) can cause the contents of panels to be lost – https://github.com/erosman/support/issues/163 
* the sort features of @fgueguen [Tabs manager](https://addons.mozilla.org/addon/duplicated-tabs-manager/) seem to be non-effective.

@mbnuqw please, are you aware of an extension that can sort within the confines of a panel?

### Use case

Wishing to sort the contents of my _add-ons_ panel: 

![image](https://user-images.githubusercontent.com/192271/77224154-afddd180-6b5a-11ea-8bd9-47de79814618.png)

**Comment by mbnuqw** [comment]
Yep, this is planned.

**Comment by mbnuqw** [comment]
Closing this in favor of #643, since it has more activity.
