### ISSUE TITLE
Tab preview header is obscured by page contents

### ISSUE THREAD

**Issue by opeik** [mbnuqw/sidebery#1708]
### Steps to reproduce

- Open Firefox in a new profile
- Install Sidebery
- Enable tab previews via popups
- Hover over a tab

### Actual behavior

- The tab preview header is obscured by the page

### Expected behavior

- The tab preview header is not obscured by the page
- A semi-transparent black background behind the preview container to improve text contrast would help

<img width="603" alt="Screenshot 2024-07-08 at 23 12 17" src="https://github.com/mbnuqw/sidebery/assets/11566773/81ed7f59-9e69-424f-a1f8-369faa4a401b">

### System

macOS 14.1.1

### Firefox version

127.0.2

### Sidebery version

5.2.0

**Comment by opeik** [comment]
After digging through the code it seems that the popup is created in [`tab-preview.ts`](https://github.com/mbnuqw/sidebery/blob/aa476a47f3663230ee5722d1a3cebffe4faf3192/src/injections/tab-preview.ts#L238), but I couldn't find any way to influence the style.

**Comment by opeik** [comment]
This issue appears to be limited to the "dark" color scheme? Firefox looks correct.

### Firefox color scheme
<img width="538" alt="Screenshot 2024-07-11 at 20 34 57" src="https://github.com/mbnuqw/sidebery/assets/11566773/9431f177-0055-431d-a1bc-913ae86dc461">

### Dark color scheme
Notice the lack of background causing overlapping text:

<img width="532" alt="Screenshot 2024-07-11 at 20 36 16" src="https://github.com/mbnuqw/sidebery/assets/11566773/f12aa2ff-7f5c-4cc9-9947-c6834de27f0f">

**Comment by ghost** [comment]
![image](https://github.com/user-attachments/assets/50cfe045-e48e-4f1d-aac2-b5574de0c1d2)

I've been facing this for a really long time now.

**Comment by guigirl42** [comment]
Yes this has been & remains an ongoing problem for me too, in Firefox Nightly & Floorp.

**Comment by b0o** [comment]
Same issue here. Also, it would be nice to be able to style the popup, but it doesn't seem to be influenced by custom CSS set in the styles editor.
