### ISSUE TITLE
Proxy per domain feature is reliable?

### ISSUE THREAD

**Issue by slrslr** [mbnuqw/sidebery#172]
Hello,

on Windows 10 with Firefox beta, i am interested to separate my footprint (cookies,proxy and ideally also user agent) between various domains.
I want to use this web browser extension to visit gmail.com and thanks to this extension, make sure that the site and all its elements loaded from third party domains will go only via mine defined proxy. I want to prevent at all cost that it happen that the gmail and any of its elements will be loaded directly (not via proxy).
I [read here](https://github.com/mozilla/multi-account-containers/issues/313#issuecomment-500121445) that this extension is not that reliable to do it.
Can anyone please comment this or can anything be done to improve this?
Maybe more reliable thing to separate traffic may be to use two different browsers or two different Firefox profiles with different look so i can not confuse it - but this is maybe not ideal regarding used memory and still some potential to confuse one window with another?
Thank you

**Comment by mbnuqw** [comment]
Hi! I fixed mentioned issue, so right now this function can work without sidebar. To use it you need to configure container:
- Include URLs
- Proxy

Example:

![screenshot-2020-03-21 19:41:12](https://user-images.githubusercontent.com/6276694/77228856-f9a2d800-6bab-11ea-80c3-4af0bca73a55.png)
![Peek 2020-03-21 19-43](https://user-images.githubusercontent.com/6276694/77228901-471f4500-6bac-11ea-9749-2b8802adccfe.gif)

### How it works internally
- Include URLs - I check the first request (before it was sent) using the configured ReqExps rules and if the url is matched I block it, then reopen tab in the target container.
- Proxy - I just check container of tab and provide the user's proxy configuration.

**Comment by slrslr** [comment]
> I fixed mentioned issue

Very good, thank You.
I see i am running v. 4.6.2 and when i close the Sidebery sidebar, the site is loading properly via proxy.
Hopefuly this feature to visit defined site/s via proxy is safe and it will not happen that i accidentally visit defined site without proxy..

**Comment by GeniusBroccoli** [comment]
Hi. I can't figure out how to correctly specify the URL, tried both just google.com and using regex, the site does not open in the container. I use stable version of sidebery.

**Comment by slrslr** [comment]
@GeniusBroccoli You should not ask it there IMO. Use https://github.com/mbnuqw/sidebery/discussions and mention me @slrslr i will reply.
