### ISSUE TITLE
Moving tabs across windows copies them instead

### ISSUE THREAD

**Issue by sig-kill** [mbnuqw/sidebery#1723]
### Steps to reproduce

- Open Firefox in a new profile
- Install Sidebery
- Open a new window (shown left)
  - ![image](https://github.com/user-attachments/assets/124066ad-eebb-4942-b5f9-48fb51614065)
- Drag a tab from one Sidebery panel to the other

### Actual behavior

Tab is copied over to the new window, and not active: 
![image](https://github.com/user-attachments/assets/6048259d-d9d3-465a-94d4-9cabb1349430)

### Expected behavior

Tab should be moved from the old window and made active in the new window. Result in the example should be this:
![image](https://github.com/user-attachments/assets/b511f135-3ef1-461d-9c2d-4827f1acaaf2)

Moving tabs used to behave this way seamlessly (even moving a playing Youtube tab across windows worked without interrupting the video) so it seems like there's a regression.

### System

Windows 10

### Firefox version

129.0b5

### Sidebery version

5.2.0

### Logs

```code
No console logs
```

**Comment by ForsakenHarmony** [comment]
Wonder if this is the same issue as #1714

**Comment by geduardcatalindev** [comment]
I have the exact same problem using the same versions of Firefox and Sidebery mentioned by @sig-kill

**Comment by Bobo1239** [comment]
Did some debugging like in https://github.com/mbnuqw/sidebery/issues/1714#issuecomment-2267961026 and the regression is caused by the same Firefox change. Opened https://bugzilla.mozilla.org/show_bug.cgi?id=1912340 upstream since it's a different bug than [what causes #1714](https://bugzilla.mozilla.org/show_bug.cgi?id=1911486) which already has a [patch pending](https://phabricator.services.mozilla.com/D218667).

**Comment by Bobo1239** [comment]
The just released Firefox Nightly contains the fix and afaict everything works again. :tada: All credits go to David Parks (handyman) who wrote the patches. Currently it is slated to land in Firefox 131 ([scheduled for Oct. 1](https://whattrainisitnow.com/release/?version=131)) but they may deem this important/unrisky enough to uplift to an earlier release.

Update: Got uplifted to beta (starting 130.0rc1) and should land on stable [on September 3](https://whattrainisitnow.com/release/?version=130).

**Comment by sig-kill** [comment]
That's great news. Thanks for following up!

**Comment by sig-kill** [comment]
Confirmed working on 131.0b3
