### ISSUE TITLE
Add "Move to the new panel" to the context menu.

### ISSUE THREAD

**Issue by Dook1** [mbnuqw/sidebery#173]
Could you add "Move to the new panel" (creating a new panel and moving selected tabs to it) to the context menu?

**Comment by mbnuqw** [comment]
Yes, I also can add options to set default or random color/icon for the new panel.

**Comment by Dook1** [comment]
Thanks.  About random color - the idea is super. 
And can you add a quick rename of the panel, without opening the settings page? Or open a new issue?

**Comment by mbnuqw** [comment]
Yep,  #174

**Comment by Dook1** [comment]
thanks
