### ISSUE TITLE
Modal window in sidebar for fast renaming the panel.

### ISSUE THREAD

**Issue by mbnuqw** [mbnuqw/sidebery#174]
- [ ] Create option in context menu for renaming the panel.
- [ ] Create modal window for renaming.

**Comment by Dook1** [comment]
And, if possible, add a color selection.

**Comment by Dook1** [comment]
If this feature is added, where is it located?

**Comment by mbnuqw** [comment]
Not sure why I've marked it as resolved in v5 beta, but this feature will be available from v5.2.0

**Comment by Dook1** [comment]
Thanks
