### ISSUE TITLE
switch tab with mouse scroll wheel bug

### ISSUE THREAD

**Issue by krapbucket** [mbnuqw/sidebery#1740]
### Steps to reproduce

Please see video on the steps to reproduce the problem.
https://www.loom.com/share/6717fb0f3045452cb2410f69a43c6cd6?sid=24e13ea7-b9a9-4a5c-be18-21168928522f

Firefox version v128.0.3
Sidebery version v5.2.0
OS: Windows 10

Sidebery mouse configuration of "`switch tab with scroll wheel`" is setup to "`in panel`"
1. create a few new tabs
2. scroll mouse wheel

### Actual behavior

Tabs take focus as mouse wheel scrolls.  However, as the number of new tabs grow to a certain number (number is dependent on the vertical height of firefox window), scrolling of mouse wheel no longer changes tab focus.  Instead, scrolling of mouse wheel becomes scrolling of vertical tab panel.

### Expected behavior

Scrolling of mouse wheel continues to change tab focus irrespective of the number of tabs present.

### System

Windows 10

### Firefox version

128.0.3

### Sidebery version

5.2.0

### Logs

```code
unfortunately, dev console shows no logs.
```

**Comment by llc0930** [comment]
Please close the third option below.

**Comment by krapbucket** [comment]
@llc0930   It appears your message above may be incomplete.  Can you please explain which option I should close in Sidebery's configuration?

**Comment by llc0930** [comment]
Unless panel is overflowing

**Comment by krapbucket** [comment]
@llc0930 Thank you for providing the instructions to provide the desired behavior.  This is a user error (my error) and not a bug.   I am closing this ticket. 

Thank you for your assistance.

**Comment by krapbucket** [comment]
This is a user error (my error) and not a bug. I am closing this ticket.

**Comment by llc0930** [comment]
@krapbucket You are welcome.
