### ISSUE TITLE
"Discarded" status is lost when moving to another window

### ISSUE THREAD

**Issue by Dook1** [mbnuqw/sidebery#175]
## Steps to reproduce
1. Activate any tab.
2. Select a group of tabs starting from the active tab and a few following it.
3. Discard selected tabs via the context menu. 
4. Move this group to any other window via the context menu "Move to"-"Window"

## Expected behavior
The "discarded" status of the moved tabs is lost. They reload in a new window. 
(Although they will be highlighted on sidebar in gray, like discarded tabs, their real status can be easily checked simply by switching to any of them)

## Actual behavior
"Discarded" status should be saved when moving to another window.
##

**_If the active tab is not included in the selected group, the "discarded" state is saved when you move them to another window._**

**Comment by mbnuqw** [comment]
Thanks for the report!

**Comment by mbnuqw** [comment]
Fixed
