### ISSUE TITLE
Group Names Show Internal ID After Firefox Restart

### ISSUE THREAD

**Issue by ffabbroc** [mbnuqw/sidebery#178]
## Steps to reproduce
1. Restart Firefox
2. Observe that some Groups have been renamed to something like "f393c2cd-5dab-0c44-b7c9-03616b4b6287/group/group.html#Amazon"
I've attached a screenshot of the bug. Note that I've blurred some of the group names that were not changed after restarting.

## Expected behavior
Group names should not change after Firefox restart.

## Actual behavior
Group names show different name, likely an internal name of some kind. 

## Environment info

OS:  
Firefox version:  74.0
Addon version:  4.6.2

<details><code>
{
  "application": {
    "name": "Firefox",
    "osVersion": "Darwin 19.3.0",
    "version": "74.0",
    "buildID": "20200309095159",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:74.0) Gecko/20100101 Firefox/74.0",
    "safeMode": false,
    "updateChannel": "release",
    "supportURL": "https://support.mozilla.org/1/firefox/74.0/Darwin/en-US/",
    "numTotalWindows": 1,
    "numRemoteWindows": 1,
    "remoteAutoStart": true,
    "autoStartStatus": 1,
    "policiesStatus": 0,
    "keyLocationServiceGoogleFound": true,
    "keySafebrowsingGoogleFound": true,
    "keyMozillaFound": true
  },
  "securitySoftware": {
    "registeredAntiVirus": "",
    "registeredAntiSpyware": "",
    "registeredFirewall": ""
  },
  "processes": {
    "remoteTypes": {
      "web": 8,
      "extension": 1
    },
    "maxWebContentProcesses": 8
  },
  "modifiedPreferences": {
    "accessibility.typeaheadfind.flashBar": 0,
    "browser.cache.disk.amount_written": 1968184,
    "browser.cache.disk.capacity": 1048576,
    "browser.cache.disk.filesystem_reported": 1,
    "browser.cache.disk.hashstats_reported": 1,
    "browser.cache.disk.smart_size.first_run": false,
    "browser.cache.disk.telemetry_report_ID": 40,
    "browser.contentblocking.category": "custom",
    "browser.display.document_color_use": 1,
    "browser.link.open_newwindow.override.external": 3,
    "browser.link.open_newwindow.restriction": 0,
    "browser.places.smartBookmarksVersion": 8,
    "browser.sessionstore.upgradeBackup.latestBuildID": "20200309095159",
    "browser.startup.homepage_override.buildID": "20200309095159",
    "browser.startup.homepage_override.mstone": "74.0",
    "browser.startup.page": 3,
    "browser.tabs.drawInTitlebar": false,
    "browser.tabs.insertRelatedAfterCurrent": false,
    "browser.urlbar.matchBuckets": "general:5,suggestion:Infinity",
    "browser.urlbar.maxRichResults": 12,
    "browser.urlbar.placeholderName": "Google",
    "browser.urlbar.placeholderName.private": "Google",
    "browser.urlbar.timesBeforeHidingSuggestionsHint": 0,
    "dom.forms.autocomplete.formautofill": true,
    "dom.push.userAgentID": "08f0f47436f14f30b675bbc7b1263f32",
    "extensions.formautofill.addresses.enabled": false,
    "extensions.formautofill.firstTimeUse": false,
    "extensions.lastAppVersion": "74.0",
    "font.internaluseonly.changed": true,
    "font.name.serif.x-western": "Arial",
    "font.size.fixed.x-western": 16,
    "idle.lastDailyNotification": 1585023226,
    "media.gmp-manager.lastCheck": 1585073537,
    "media.benchmark.vp9.fps": 302,
    "media.benchmark.vp9.versioncheck": 5,
    "media.gmp-gmpopenh264.abi": "x86_64-gcc3",
    "media.gmp-gmpopenh264.lastUpdate": 1571854536,
    "media.gmp-gmpopenh264.version": "1.8.1.1",
    "media.gmp-manager.buildID": "20200309095159",
    "media.gmp-widevinecdm.abi": "x86_64-gcc3",
    "media.gmp-widevinecdm.lastUpdate": 1581445081,
    "media.gmp-widevinecdm.version": "4.10.1582.2",
    "media.gmp.storage.version.observed": 1,
    "network.cookie.cookieBehavior": 3,
    "network.cookie.prefsMigrated": true,
    "network.predictor.cleaned-up": true,
    "places.database.lastMaintenance": 1584936826,
    "places.history.expiration.transient_current_max_pages": 136771,
    "plugin.disable_full_page_plugin_for_types": "application/pdf",
    "plugin.flash.arch": "x86_64-gcc3",
    "plugin.flash.blockliststate": 0,
    "plugin.flash.desc": "Shockwave Flash 32.0 r0",
    "plugin.flash.lastmod_hi": 368,
    "plugin.flash.lastmod_lo": -822666085,
    "plugin.flash.path": "/Library/Internet Plug-Ins/Flash Player.plugin",
    "plugin.flash.version": "32.0.0.344",
    "print.print_bgcolor": false,
    "print.print_bgimages": false,
    "print.print_duplex": 0,
    "print.print_evenpages": true,
    "print.print_in_color": true,
    "print.print_margin_bottom": "0.5",
    "print.print_margin_left": "0.5",
    "print.print_margin_right": "0.5",
    "print.print_margin_top": "0.5",
    "print.print_oddpages": true,
    "print.print_orientation": 0,
    "print.print_page_delay": 50,
    "print.print_paper_data": 0,
    "print.print_paper_height": " 11.00",
    "print.print_paper_name": "",
    "print.print_paper_size_unit": 0,
    "print.print_paper_width": "  8.50",
    "print.print_resolution": 0,
    "print.print_reversed": false,
    "print.print_scaling": "  0.70",
    "print.print_shrink_to_fit": true,
    "print.print_to_file": false,
    "print.print_unwriteable_margin_bottom": 17,
    "print.print_unwriteable_margin_left": 17,
    "print.print_unwriteable_margin_right": 17,
    "print.print_unwriteable_margin_top": 17,
    "privacy.sanitize.pending": "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]",
    "privacy.clearOnShutdown.downloads": false,
    "privacy.clearOnShutdown.formdata": false,
    "privacy.clearOnShutdown.history": false,
    "privacy.donottrackheader.enabled": true,
    "privacy.history.custom": true,
    "privacy.trackingprotection.enabled": true,
    "privacy.trackingprotection.introCount": 20,
    "privacy.userContext.enabled": true,
    "privacy.userContext.extension": "{3c078156-979c-498b-8990-85f7987dd929}",
    "privacy.userContext.longPressBehavior": 2,
    "privacy.userContext.ui.enabled": true,
    "security.remote_settings.intermediates.checked": 1562528540,
    "security.sandbox.content.tempDirSuffix": "1f0e3370-4ce5-ff40-bcfd-46b3b11273b9",
    "security.sandbox.plugin.tempDirSuffix": "f51093d2-fec5-584e-8280-0725f6be1956",
    "services.sync.declinedEngines": "forms,history,passwords",
    "services.sync.lastPing": 1584996885,
    "services.sync.lastSync": "Tue Mar 24 2020 11:22:53 GMT-0700 (Pacific Daylight Time)",
    "services.sync.engine.addresses.available": true,
    "services.sync.engine.history": false,
    "services.sync.engine.passwords": false,
    "services.sync.engine.prefs.modified": false,
    "signon.importedFromSqlite": true,
    "signon.rememberSignons": false,
    "storage.vacuum.last.index": 1,
    "storage.vacuum.last.places.sqlite": 1584040981,
    "svg.context-properties.content.enabled": true
  },
  "lockedPreferences": {
    "fission.autostart": false
  },
  "media": {
    "currentAudioBackend": "audiounit-rust",
    "currentMaxAudioChannels": 2,
    "currentPreferredSampleRate": 48000,
    "audioOutputDevices": [
      {
        "name": "Description",
        "groupId": "LogMeInSoundEngine:0",
        "vendor": "ManufacturerName",
        "type": 2,
        "state": 2,
        "preferred": 0,
        "supportedFormat": 12336,
        "defaultFormat": 4096,
        "maxChannels": 2,
        "defaultRate": 44100,
        "maxRate": 192000,
        "minRate": 32000,
        "maxLatency": 4096,
        "minLatency": 14
      },
      {
        "name": "MacBook Pro Speakers",
        "groupId": "BuiltInSpeakerDevice",
        "vendor": "Apple Inc.",
        "type": 2,
        "state": 2,
        "preferred": 0,
        "supportedFormat": 12336,
        "defaultFormat": 4096,
        "maxChannels": 2,
        "defaultRate": 48000,
        "maxRate": 96000,
        "minRate": 44100,
        "maxLatency": 4390,
        "minLatency": 309
      },
      {
        "name": "USB PnP Audio Device",
        "groupId": "AppleUSBAudioEngine:Unknown Manufacturer:USB PnP Audio Device:14332000:1",
        "vendor": "Unknown Manufacturer",
        "type": 2,
        "state": 2,
        "preferred": 15,
        "supportedFormat": 12336,
        "defaultFormat": 4096,
        "maxChannels": 2,
        "defaultRate": 48000,
        "maxRate": 48000,
        "minRate": 48000,
        "maxLatency": 4144,
        "minLatency": 63
      },
      {
        "name": "LG Ultra HD",
        "groupId": "AppleGFXHDAEngineOutputDP:10001:0:{6D1E-5B08-000032E0}",
        "vendor": "Apple Inc.",
        "type": 2,
        "state": 2,
        "preferred": 0,
        "supportedFormat": 12336,
        "defaultFormat": 4096,
        "maxChannels": 2,
        "defaultRate": 48000,
        "maxRate": 48000,
        "minRate": 32000,
        "maxLatency": 4098,
        "minLatency": 17
      },
      {
        "name": "Microsoft LifeChat LX-3000",
        "groupId": "AppleUSBAudioEngine:C-Media Electronics Inc.      :Microsoft LifeChat LX-3000:14100000:2,1",
        "vendor": "C-Media Electronics Inc.      ",
        "type": 2,
        "state": 2,
        "preferred": 0,
        "supportedFormat": 12336,
        "defaultFormat": 4096,
        "maxChannels": 2,
        "defaultRate": 48000,
        "maxRate": 48000,
        "minRate": 44100,
        "maxLatency": 4144,
        "minLatency": 63
      }
    ],
    "audioInputDevices": [
      {
        "name": "Description",
        "groupId": "LogMeInSoundEngine:0",
        "vendor": "ManufacturerName",
        "type": 1,
        "state": 2,
        "preferred": 0,
        "supportedFormat": 12336,
        "defaultFormat": 4096,
        "maxChannels": 2,
        "defaultRate": 44100,
        "maxRate": 192000,
        "minRate": 32000,
        "maxLatency": 4096,
        "minLatency": 14
      },
      {
        "name": "MacBook Pro Microphone",
        "groupId": "BuiltInMicrophoneDevice",
        "vendor": "Apple Inc.",
        "type": 1,
        "state": 2,
        "preferred": 0,
        "supportedFormat": 12336,
        "defaultFormat": 4096,
        "maxChannels": 1,
        "defaultRate": 48000,
        "maxRate": 96000,
        "minRate": 44100,
        "maxLatency": 6052,
        "minLatency": 1971
      },
      {
        "name": "USB PnP Audio Device",
        "groupId": "AppleUSBAudioEngine:Unknown Manufacturer:USB PnP Audio Device:14332000:2",
        "vendor": "Unknown Manufacturer",
        "type": 1,
        "state": 2,
        "preferred": 15,
        "supportedFormat": 12336,
        "defaultFormat": 4096,
        "maxChannels": 1,
        "defaultRate": 48000,
        "maxRate": 48000,
        "minRate": 48000,
        "maxLatency": 4144,
        "minLatency": 63
      },
      {
        "name": "Microsoft LifeChat LX-3000",
        "groupId": "AppleUSBAudioEngine:C-Media Electronics Inc.      :Microsoft LifeChat LX-3000:14100000:2,1",
        "vendor": "C-Media Electronics Inc.      ",
        "type": 1,
        "state": 2,
        "preferred": 0,
        "supportedFormat": 12336,
        "defaultFormat": 4096,
        "maxChannels": 1,
        "defaultRate": 48000,
        "maxRate": 48000,
        "minRate": 44100,
        "maxLatency": 4144,
        "minLatency": 63
      }
    ]
  },
  "javaScript": {
    "incrementalGCEnabled": true
  },
  "accessibility": {
    "isActive": false,
    "forceDisabled": 0,
    "handlerUsed": false,
    "instantiator": ""
  },
  "libraryVersions": {
    "NSPR": {
      "minVersion": "4.25",
      "version": "4.25"
    },
    "NSS": {
      "minVersion": "3.50",
      "version": "3.50"
    },
    "NSSUTIL": {
      "minVersion": "3.50",
      "version": "3.50"
    },
    "NSSSSL": {
      "minVersion": "3.50",
      "version": "3.50"
    },
    "NSSSMIME": {
      "minVersion": "3.50",
      "version": "3.50"
    }
  },
  "userJS": {
    "exists": false
  },
  "intl": {
    "localeService": {
      "requested": [
        "en-US"
      ],
      "available": [
        "en-US"
      ],
      "supported": [
        "en-US"
      ],
      "regionalPrefs": [
        "en-US"
      ],
      "defaultLocale": "en-US"
    },
    "osPrefs": {
      "systemLocales": [
        "en-US"
      ],
      "regionalPrefsLocales": [
        "en-US"
      ]
    }
  },
  "crashes": {
    "submitted": [],
    "pending": 0
  },
  "sandbox": {
    "contentSandboxLevel": 3,
    "effectiveContentSandboxLevel": 3
  },
  "graphics": {
    "numTotalWindows": 1,
    "numAcceleratedWindows": 1,
    "windowLayerManagerType": "OpenGL",
    "windowLayerManagerRemote": true,
    "windowUsingAdvancedLayers": false,
    "adapterDescription": "",
    "adapterVendorID": "0x1002",
    "adapterDeviceID": "0x67ef",
    "adapterRAM": 0,
    "adapterDrivers": "",
    "driverVendor": "",
    "driverVersion": "",
    "driverDate": "",
    "usesTiling": true,
    "contentUsesTiling": true,
    "offMainThreadPaintEnabled": true,
    "offMainThreadPaintWorkerCount": 4,
    "targetFrameRate": 60,
    "webgl1Renderer": "ATI Technologies Inc. -- AMD Radeon Pro 560X OpenGL Engine",
    "webgl1Version": "4.1 ATI-3.5.5",
    "webgl1DriverExtensions": "GL_ARB_blend_func_extended GL_ARB_draw_buffers_blend GL_ARB_draw_indirect GL_ARB_ES2_compatibility GL_ARB_explicit_attrib_location GL_ARB_gpu_shader_fp64 GL_ARB_gpu_shader5 GL_ARB_instanced_arrays GL_ARB_internalformat_query GL_ARB_occlusion_query2 GL_ARB_sample_shading GL_ARB_sampler_objects GL_ARB_separate_shader_objects GL_ARB_shader_bit_encoding GL_ARB_shader_subroutine GL_ARB_shading_language_include GL_ARB_tessellation_shader GL_ARB_texture_buffer_object_rgb32 GL_ARB_texture_cube_map_array GL_ARB_texture_gather GL_ARB_texture_query_lod GL_ARB_texture_rgb10_a2ui GL_ARB_texture_storage GL_ARB_texture_swizzle GL_ARB_timer_query GL_ARB_transform_feedback2 GL_ARB_transform_feedback3 GL_ARB_vertex_attrib_64bit GL_ARB_vertex_type_2_10_10_10_rev GL_ARB_viewport_array GL_EXT_debug_label GL_EXT_debug_marker GL_EXT_depth_bounds_test GL_EXT_texture_compression_s3tc GL_EXT_texture_filter_anisotropic GL_EXT_texture_mirror_clamp GL_EXT_texture_sRGB_decode GL_APPLE_client_storage GL_APPLE_container_object_shareable GL_APPLE_flush_render GL_APPLE_object_purgeable GL_APPLE_rgb_422 GL_APPLE_row_bytes GL_APPLE_texture_range GL_ATI_texture_mirror_once GL_NV_texture_barrier",
    "webgl1Extensions": "ANGLE_instanced_arrays EXT_blend_minmax EXT_color_buffer_half_float EXT_float_blend EXT_frag_depth EXT_shader_texture_lod EXT_sRGB EXT_texture_compression_rgtc EXT_texture_filter_anisotropic MOZ_debug OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_float_linear OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_depth_texture WEBGL_draw_buffers WEBGL_lose_context",
    "webgl1WSIInfo": "CGL",
    "webgl2Renderer": "ATI Technologies Inc. -- AMD Radeon Pro 560X OpenGL Engine",
    "webgl2Version": "4.1 ATI-3.5.5",
    "webgl2DriverExtensions": "GL_ARB_blend_func_extended GL_ARB_draw_buffers_blend GL_ARB_draw_indirect GL_ARB_ES2_compatibility GL_ARB_explicit_attrib_location GL_ARB_gpu_shader_fp64 GL_ARB_gpu_shader5 GL_ARB_instanced_arrays GL_ARB_internalformat_query GL_ARB_occlusion_query2 GL_ARB_sample_shading GL_ARB_sampler_objects GL_ARB_separate_shader_objects GL_ARB_shader_bit_encoding GL_ARB_shader_subroutine GL_ARB_shading_language_include GL_ARB_tessellation_shader GL_ARB_texture_buffer_object_rgb32 GL_ARB_texture_cube_map_array GL_ARB_texture_gather GL_ARB_texture_query_lod GL_ARB_texture_rgb10_a2ui GL_ARB_texture_storage GL_ARB_texture_swizzle GL_ARB_timer_query GL_ARB_transform_feedback2 GL_ARB_transform_feedback3 GL_ARB_vertex_attrib_64bit GL_ARB_vertex_type_2_10_10_10_rev GL_ARB_viewport_array GL_EXT_debug_label GL_EXT_debug_marker GL_EXT_depth_bounds_test GL_EXT_texture_compression_s3tc GL_EXT_texture_filter_anisotropic GL_EXT_texture_mirror_clamp GL_EXT_texture_sRGB_decode GL_APPLE_client_storage GL_APPLE_container_object_shareable GL_APPLE_flush_render GL_APPLE_object_purgeable GL_APPLE_rgb_422 GL_APPLE_row_bytes GL_APPLE_texture_range GL_ATI_texture_mirror_once GL_NV_texture_barrier",
    "webgl2Extensions": "EXT_color_buffer_float EXT_float_blend EXT_texture_compression_rgtc EXT_texture_filter_anisotropic MOZ_debug OES_texture_float_linear WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context",
    "webgl2WSIInfo": "CGL",
    "info": {
      "AzureCanvasBackend": "skia",
      "AzureFallbackCanvasBackend": "none",
      "AzureContentBackend": "skia",
      "ApzWheelInput": 1,
      "ApzDragInput": 1,
      "ApzKeyboardInput": 1,
      "ApzAutoscrollInput": 1,
      "TileHeight": 1024,
      "TileWidth": 1024,
      "CMSOutputProfile": "AAACFGFwcGwEAAAAbW50clJHQiBYWVogB+QAAwAWABUABAASYWNzcEFQUEwAAAAAQVBQTAAAAAAAAAAAAAAAAAAAAAAAAPbWAAEAAAAA0y1hcHBsSRTysPmJOv9zj28bbQgPpQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKZGVzYwAAAPwAAABmY3BydAAAAWQAAAAjd3RwdAAAAYgAAAAUclhZWgAAAZwAAAAUZ1hZWgAAAbAAAAAUYlhZWgAAAcQAAAAUclRSQwAAAdgAAAAQY2hhZAAAAegAAAAsYlRSQwAAAdgAAAAQZ1RSQwAAAdgAAAAQZGVzYwAAAAAAAAAMTEcgVWx0cmEgSEQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB0ZXh0AAAAAENvcHlyaWdodCBBcHBsZSBJbmMuLCAyMDIwAABYWVogAAAAAAAA89gAAQAAAAEWCFhZWiAAAAAAAABzMAAAOo0AAAFwWFlaIAAAAAAAAF0UAAC0aAAADmNYWVogAAAAAAAAJpIAABELAADDWnBhcmEAAAAAAAAAAAAB9gRzZjMyAAAAAAABC7cAAAWW///zVwAABykAAP3X///7t////aYAAAPaAADA9g==",
      "DisplayCount": 1,
      "Display0": "3840x2160 scale:1.000000"
    },
    "featureLog": {
      "features": [
        {
          "name": "HW_COMPOSITING",
          "description": "Compositing",
          "status": "available",
          "log": [
            {
              "type": "default",
              "status": "available"
            }
          ]
        },
        {
          "name": "OPENGL_COMPOSITING",
          "description": "OpenGL Compositing",
          "status": "available",
          "log": [
            {
              "type": "default",
              "status": "available"
            }
          ]
        },
        {
          "name": "WEBRENDER",
          "description": "WebRender",
          "status": "opt-in",
          "log": [
            {
              "type": "default",
              "status": "opt-in",
              "message": "WebRender is an opt-in feature"
            }
          ]
        },
        {
          "name": "WEBRENDER_QUALIFIED",
          "description": "WebRender qualified",
          "status": "blacklisted",
          "log": [
            {
              "type": "default",
              "status": "available"
            },
            {
              "type": "env",
              "status": "blacklisted",
              "message": "No qualified hardware"
            }
          ]
        },
        {
          "name": "WEBRENDER_COMPOSITOR",
          "description": "WebRender native compositor",
          "status": "disabled",
          "log": [
            {
              "type": "default",
              "status": "disabled",
              "message": "Disabled by default"
            }
          ]
        },
        {
          "name": "OMTP",
          "description": "Off Main Thread Painting",
          "status": "available",
          "log": [
            {
              "type": "default",
              "status": "available"
            }
          ]
        },
        {
          "name": "WEBGPU",
          "description": "WebGPU",
          "status": "disabled",
          "log": [
            {
              "type": "default",
              "status": "disabled",
              "message": "Disabled by default"
            }
          ]
        }
      ],
      "fallbacks": []
    },
    "crashGuards": []
  },
  "extensions": [
    {
      "name": "Activate Reader View",
      "version": "0.1.1",
      "isActive": true,
      "id": "@activatereaderview"
    },
    {
      "name": "Adblock Plus - free ad blocker",
      "version": "3.8",
      "isActive": true,
      "id": "{d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d}"
    },
    {
      "name": "Amazon.com",
      "version": "1.1",
      "isActive": true,
      "id": "amazondotcom@search.mozilla.org"
    },
    {
      "name": "Bing",
      "version": "1.1",
      "isActive": true,
      "id": "bing@search.mozilla.org"
    },
    {
      "name": "BuiltWith",
      "version": "2.1",
      "isActive": true,
      "id": "gary@builtwith.com"
    },
    {
      "name": "Cookie AutoDelete",
      "version": "3.1.1",
      "isActive": true,
      "id": "CookieAutoDelete@kennydo.com"
    },
    {
      "name": "Dark Background and Light Text",
      "version": "0.7.2",
      "isActive": true,
      "id": "jid1-QoFqdK4qzUfGWQ@jetpack"
    },
    {
      "name": "Dashlane",
      "version": "6.2009.1",
      "isActive": true,
      "id": "jetpack-extension@dashlane.com"
    },
    {
      "name": "Don't Fuck With Paste",
      "version": "2.3.1",
      "isActive": true,
      "id": "DontFuckWithPaste@raim.ist"
    },
    {
      "name": "Downloads sidebar",
      "version": "1.0.1",
      "isActive": true,
      "id": "{bbb81fb3-49c1-4a42-bcc9-94bc93e19fb8}"
    },
    {
      "name": "DuckDuckGo",
      "version": "1.0",
      "isActive": true,
      "id": "ddg@search.mozilla.org"
    },
    {
      "name": "eBay",
      "version": "1.0",
      "isActive": true,
      "id": "ebay@search.mozilla.org"
    },
    {
      "name": "Enhancer for YouTube™",
      "version": "2.0.99",
      "isActive": true,
      "id": "enhancerforyoutube@maximerf.addons.mozilla.org"
    },
    {
      "name": "Google",
      "version": "1.0",
      "isActive": true,
      "id": "google@search.mozilla.org"
    },
    {
      "name": "Google Reverse Image Search",
      "version": "64.1.0",
      "isActive": true,
      "id": "{95322c08-05ff-4f3c-85fd-8ceb821988dd}"
    },
    {
      "name": "Honey",
      "version": "11.11.4",
      "isActive": true,
      "id": "jid1-93CWPmRbVPjRQA@jetpack"
    },
    {
      "name": "HTTPS Everywhere",
      "version": "2019.11.7",
      "isActive": true,
      "id": "https-everywhere@eff.org"
    },
    {
      "name": "Power Tabs",
      "version": "1.8.0",
      "isActive": true,
      "id": "power-tabs@rapptz-addons.com"
    },
    {
      "name": "Print Preview Button",
      "version": "1.4",
      "isActive": true,
      "id": "print-preview-single@codefisher.org"
    },
    {
      "name": "Push to Kindle",
      "version": "1.9",
      "isActive": true,
      "id": "jid0-GokC6R49cBZciOKniufAR4QKFWc@jetpack"
    },
    {
      "name": "Select After Closing Current",
      "version": "4.3",
      "isActive": true,
      "id": "select-after-closing-current@qw.linux-2g64.local"
    },
    {
      "name": "Sidebery",
      "version": "4.6.2",
      "isActive": true,
      "id": "{3c078156-979c-498b-8990-85f7987dd929}"
    },
    {
      "name": "Tab Session Manager",
      "version": "5.2.0",
      "isActive": true,
      "id": "Tab-Session-Manager@sienori"
    },
    {
      "name": "Twitter",
      "version": "1.0",
      "isActive": true,
      "id": "twitter@search.mozilla.org"
    },
    {
      "name": "Wikipedia (en)",
      "version": "1.0",
      "isActive": true,
      "id": "wikipedia@search.mozilla.org"
    },
    {
      "name": "Location Guard",
      "version": "2.4.0",
      "isActive": false,
      "id": "jid1-HdwPLukcGQeOSh@jetpack"
    }
  ],
  "features": [
    {
      "name": "DoH Roll-Out",
      "version": "1.3.0",
      "id": "doh-rollout@mozilla.org"
    },
    {
      "name": "Firefox Screenshots",
      "version": "39.0.0",
      "id": "screenshots@mozilla.org"
    },
    {
      "name": "Form Autofill",
      "version": "1.0",
      "id": "formautofill@mozilla.org"
    },
    {
      "name": "Web Compat",
      "version": "7.0.0",
      "id": "webcompat@mozilla.org"
    },
    {
      "name": "WebCompat Reporter",
      "version": "1.1.0",
      "id": "webcompat-reporter@mozilla.org"
    }
  ]
}</code></details>

**Comment by ffabbroc** [comment]
Forgot screenshot :)

![2020-03-24_11-21-47 (2)](https://user-images.githubusercontent.com/1831958/77463172-70192300-6dc2-11ea-92ec-17fa02fd2327.png)

**Comment by mbnuqw** [comment]
Thanks for the report! Yep, this is a known bug (I've seen this several times), after reloading the group page the title should normalize. I'll try to fix this soon.

**Comment by ffabbroc** [comment]
Max, sorry if it is a duplicate; I did search all open issues but couldn't find this particular bug. 

I didn't think of reloading the group page, which fixes it more easily than renaming each one.

**Comment by mbnuqw** [comment]
@ffabbroc, I've updated addon (v4.7.0) сould you check if problem is still present?

**Comment by ffabbroc** [comment]
Looks like it's fixed, thanks!
