### ISSUE TITLE
Move to new window exits private mode

### ISSUE THREAD

**Issue by Ooglogput** [mbnuqw/sidebery#181]
## Steps to reproduce
Open a tab in a private window. Right click it and choose *Move to new window* from the context menu. 

## Expected behavior
The tab opens in a new, private window. 

## Actual behavior
The tab opens in a new, non-private window. 

## Environment info
OS: Arch Linux
Firefox version: 74.0
Addon version: 4.6.2

**Comment by mbnuqw** [comment]
Ouch, its inaccurate wording. You should click on option 'Move to private window'.

**Comment by Ooglogput** [comment]
Would it be possible to have it detect if the current window is private and move to a private window in that case? I feel like that use case is more common, and it could have pretty unfortunate consequences if you make this slip. 

Ideally in my mind the two buttons should be *move to same kind of window* and *move to different kind of window*, although I understand if you don't agree with this.

**Comment by mbnuqw** [comment]
Available in the latest version. I hope there will be less ambiguity now.
