### ISSUE TITLE
Tabs not being saved

### ISSUE THREAD

**Issue by cmdillon** [mbnuqw/sidebery#1819]
### Steps to reproduce

- open Firefox
- open new tabs
- enter website address
- close Firefox browser making sure to leave tabs open

### Actual behavior

after restarting Firefox all previously opened tabs are not visible. Only pinned tabs are saved.

### Expected behavior

I would expect when I reopen Firefox that I would see the previously opened tabs

### System

macOS 15

### Firefox version

130.0.1 (64-bit) and 131.0b9 (aarch64)

### Sidebery version

5.2.0

**Comment by h4zm1** [comment]
Am not on macOS but I noticed you didn't mention enabling the option in the settings in your steps to reproduce this issue.
![image](https://github.com/user-attachments/assets/c8b1169f-9739-4687-aaa6-e31c6dcd9f22)

**Comment by cmdillon** [comment]
> Am not on macOS but I noticed you didn't mention enabling the option in the settings in your steps to reproduce this issue. ![image](https://private-user-images.githubusercontent.com/24853128/372646575-c8b1169f-9739-4687-aaa6-e31c6dcd9f22.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4NDk4MzksIm5iZiI6MTcyNzg0OTUzOSwicGF0aCI6Ii8yNDg1MzEyOC8zNzI2NDY1NzUtYzhiMTE2OWYtOTczOS00Njg3LWFhYTYtZTMxYzZkY2Q5ZjIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAyVDA2MTIxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlNGZlNzdmYTJiZWFjOGU5MGRlMWUzNDAwNDAzZDAwMzAxYWU4MTY0ZDViNTM5MmIxYjYwZjVjZDdlZWNiYzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.4XPOMKmUnNEhuGQ1JYQUYlymwELP6k8ggQF39CF3ANo)

thx! I noticed that today. I guess mozzila changed the default settings.
