### ISSUE TITLE
Cannot share tab with other device/Firefox

### ISSUE THREAD

**Issue by 7wells** [mbnuqw/sidebery#1820]
### Steps to reproduce

- Open Firefox in a new profile
- Install Sidebery
- Right-click on tab and search for share tab function

### Actual behavior

Unless I completely missed something, there does not seem to be a share function for a tab, so it could be opened on another device/Firefox.

Is it really missing?

### Expected behavior

It should be possible to share a tab with another device/Firefox.

### System

Windows 11 Pro

### Firefox version

130.0.1

### Sidebery version

5.2.0

### Logs

```code
Not applicable
```

**Comment by the-nelsonator** [comment]
Probably not going to happen. Was requested and not possible as of 2020: https://github.com/mbnuqw/sidebery/issues/130

There was a bugzilla asking for the API to be opened up but it seems to have been rejected: https://bugzilla.mozilla.org/show_bug.cgi?id=1417183

However, syncing across devices seems to have some traction: https://github.com/mbnuqw/sidebery/issues/1372. Don't think this would solve sending to your phone though, unless Sidebery functions on Android, I've never tried.

**Comment by 7wells** [comment]
Thank you for letting me know! 👍
