### ISSUE TITLE
Use system's style

### ISSUE THREAD

**Issue by mbnuqw** [mbnuqw/sidebery#184]
## Description
Add an "auto" option to the "Style" setting and set it as the default.

**Comment by do-bo** [comment]
Hi!
Would it be possible for the "Auto" style (or maybe another new one, like "Tabbar") to follow the Firefox tab bar style? When I used Tree Style Tab, the "Vertigo" theme followed tab bar colors, so the sidebar blended with the rest of browser UI, whatever the theme was.

**Comment by mbnuqw** [comment]
@do-bo, I already experimented with applying the colors of used theme and it unfortunately not worked very well. But I won't give up and eventually will add this feature (maybe I'll mark it as experimental). Issue to track: #203

**Comment by mbnuqw** [comment]
Available in current version
