### ISSUE TITLE
Tabs not closing/sleeping when changing panels [SOLVED]

### ISSUE THREAD

**Issue by SGM1910** [mbnuqw/sidebery#1847]
### Steps to reproduce

- Create 2 panels
- Open different tabs on each panel
- Go from one panel to the other

### Actual behavior

When i change panels the tabs do not go to sleep or close, making it so i can see all of the open wtabs in the horizontal bar. This makes firefox slow down because i have many tabs open in different panels.

### Expected behavior

When you change panels, the tabs from that panel should not be kept open/not appear on the horizontal bar.
i've been using sidebery for a few weeks and that's how it used to work until today

### System

windows 11

### Firefox version

131.0.3 (64-bit)

### Sidebery version

5.2.0

**Comment by albino1** [comment]
Under `Tabs` -> `Native (horizontal) tabs` do you have `Hide native tabs of inactive panels` turned on?

**Comment by SGM1910** [comment]
Yeah, no, i must've turned it off by accident, sorry lmao

**Comment by JohnVKRDam** [comment]
@SGM1910  Glad to see it was solved 👍 Could you please close this issue? That way it is removed from the "open issues" list.

You can do that by adding a comment with the option CLOSE ISSUE from the dropdown selected:

![2024-10-28_115349](https://github.com/user-attachments/assets/1cf6dede-f6e7-453f-9a9f-764fb71d69a7)
