### ISSUE TITLE
Rename tabs

### ISSUE THREAD

**Issue by dchawisher** [mbnuqw/sidebery#185]
## Description
Add option to rename tabs to context menu. (Tab ReTitle implements this feature.)

**Rationale**
If a user has many tabs from the same website, it can be difficult to identify the tab he needs, especially if the tab titles are cut off or are not very descriptive. For instance, I use Westlaw to do legal research. By default, it can be difficult to keep track of Westlaw tabs.
![image](https://user-images.githubusercontent.com/22660616/78064069-28187400-735f-11ea-8d78-f993c73fc7e1.png)

After renaming the tabs, it is much easier. 
![image](https://user-images.githubusercontent.com/22660616/78064391-af65e780-735f-11ea-9e6e-705d9455162e.png)

However, to do that currently I have to use a different add-on and navigate to the tab before renaming it.

**Comment by mbnuqw** [comment]
Ok, I'll add this feature. Implementation doesn't look difficult so I think this will appear in the next release.

**Comment by aletaziar** [comment]
I would point out that [Tab ReTitle](https://addons.mozilla.org/en-US/firefox/addon/tab-retitle/) has a few advanced renaming options. It can set renaming to persist through sessions, automatically by domain, automatically by url, and a beta feature uses regex to rename the tab title automatically by domain. I would love to uninstall Tab ReTitle and use Sidebery, but I would keep Tab ReTitle if you didn't replicate its feature set.

**Comment by emvaized** [comment]
I really hope this feature could land some day in already gorgeous `v5` version. Using another extension's toolbar icon for this feels unnatural, as well as the need to select tab first in order to rename it.

**Comment by emvaized** [comment]
I like how simple it's done in the experimental Arc browser for mac os – you just click on current tab and enter new title:
![arc-tab-rename](https://user-images.githubusercontent.com/37851576/199356893-0817877a-d876-4cd1-8f0c-0eef29f86926.gif)

Not sure though, if it's possible to do it this way in Sidebery

**Comment by emvaized** [comment]
I can't believe it, but it works now in [b30](https://github.com/mbnuqw/sidebery/releases/tag/v5.0.0b30) release, and it works flawlessly! Even with the inline editing and double click gesture. 
@mbnuqw Many-many thanks!🙏

**Comment by albino1** [comment]
In case anybody stumbles on this in the future trying to figure out how to get double-click and long-click to work for editing titles, the setting is under:

`Mouse -> Tab actions`

And then either `Double click on tab` or whichever you prefer.

**Comment by davidleejy** [comment]
anyone knows when the b30 release will be available in Firefox's Extensions Store?

**Comment by icytree** [comment]
It indeed works very well ! I was wondering if it would be possible to also add a keybinding for renaming ? I would propose F2 as it is pretty standard with other programs.

**Comment by prmichaelsen** [comment]
Holy cow I'm so excited

**Comment by koppor** [comment]
Context menu works, double click just unfocuses and refocuses the current tab. Not important.

I would ask for having <kbd>F2</kbd> as keybinding (keyboard shortcut). Currently, the settings for key bindings do not offer an option for renaming.

**Comment by MotherOfClamperl** [comment]
When a pinned tab is double clicked, it gets a blue outline that you cannot remove (unless you reopen the sidebar or unpin it and re-double click it). The outline also prevents refocusing the tab.

**Comment by mbnuqw** [comment]
@MotherOfClamperl, thanks for report!

**Comment by morphles** [comment]
So... as someone already asked in firefox when? :) Hm actually seems no release in ff add-ons for almost a year now. Is it still considered supported on FF?

**Comment by morphles** [comment]
When is v5 expected to be released out of bet into official ff addons?

**Comment by mbnuqw** [comment]
@morphles Public release of v5 - optimistically, next week. There will also be a few rc releases (rc4 today).

**Comment by sgoodluck** [comment]
Ooh this is exciting -- is there an update?

**Comment by albino1** [comment]
> Ooh this is exciting -- is there an update?

The update is that it was added to v5 in January, so feel free to start using it ;)

**Comment by mbnuqw** [comment]
Resolved in v5.0.0
