### ISSUE TITLE
Add "open tab beside this one" feature.

### ISSUE THREAD

**Issue by HamzaMateen** [mbnuqw/sidebery#1855]
### Description

I have realized that Zen browser allows opening of a tab relative to the active tab but in Sidebery, a tab is always opened at the far end. This is cumbersome when there are numerous tabs, potentially filling the sidebar. 
I hope this makes sense. Thank you!

**Comment by albino1** [comment]
Take a look at `Settings` -> `Tabs` -> `Position of new tab`

**Comment by HamzaMateen** [comment]
Got it, thank you!
