### ISSUE TITLE
Dynamic sidebar userChrome.css changes has no effect

### ISSUE THREAD

**Issue by zilexa** [mbnuqw/sidebery#186]
## Steps to reproduce
Follow the steps of the readme exactly to get dynamic sidebar. Note I did not change anything else, I did apply the other 2 changes in userChrome.css, successfully ("Completely hide tabs strip" and "Hide sidebar top-menu"). 

## Expected behavior
Dynamic sidebar, at least it should hide when Firefox goes fullscreen.

## Actual behavior
No behavioral change, sidebar is always shown, unless user hides it using the button in the navbar.

## Environment info

OS:  Ubuntu 19.10
Firefox version:  74
Addon version:  4.7.0

**Comment by tk-nguyen** [comment]
I think the readme config is old, you can check the fix in [issue #124](https://github.com/mbnuqw/sidebery/issues/124)

**Comment by mbnuqw** [comment]
Yes, sorry, this is low priority task for me right now. Later, I'll update the [wiki section](https://github.com/mbnuqw/sidebery/wiki/Firefox-Styles-Snippets-(via-userChrome.css)) to fix this.

**Comment by mbnuqw** [comment]
Closing this as a duplicate.
