### ISSUE TITLE
Add "Close Descendants" option

### ISSUE THREAD

**Issue by benplumley** [mbnuqw/sidebery#188]
## Description
I've just moved from Tree Style Tab, and one feature that has that I used regularly but can't find in Sidebery is a "Close Descendants" option. In TST this goes in the context menu but could fit equally well as a keyboard shortcut action or one of the options in the "Mouse" category of settings.

The option would close all descendants of the tab that was selected but not the selected tab itself. (The  selected tab means the current tab for a keybind, or the tab that was clicked for a mouse-invoked option.)

**Comment by mbnuqw** [comment]
Available in context menu editor.

**Comment by char101** [comment]
Could this action and the close branch action are also added to the keyboard shortcut list?

TST has these on its shortcut list. It is faster to use the keyboard shortcut that using the context menu.
