### ISSUE TITLE
Segfault after changing permissions (Firefox 66, v2.2.1, Arch Linux)

### ISSUE THREAD

**Issue by mbaz** [mbnuqw/sidebery#19]
I enabled the "access website data" permission, and it pegged my CPU at 100%. After a while, Firefox crashed, and I found this in `dmesg`:

[186727.730014] WebExtensions[5951]: segfault at 0 ip 00005648c8c65d8d sp 00007ffdf164c620 error 6 in firefox[5648c8c64000+1f000]

Upon relaunch, I found that I lost several tabs; some were pinned, and others were inside a container.

**Comment by mbaz** [comment]
One maybe related thing I've just noticed:

Before Firefox crashed, I had created a "reddit" container. All tabs I lost were inside it. This container was only visible in the window in which I created it.

After starting Firefox again, now I see the reddit button in the panel of every window.

Just to test, I created a new container in a different window. This container is only visible in the window in which it was created.

Is this the intended behavior?

**Comment by mbnuqw** [comment]
This is definitely not intended behaviour. After creation of new container
it should be visible from every window.

I'll check this asap.

**Comment by mbnuqw** [comment]
I've fixed in v2.2.2 changing of permissions and handling updates of containers across multiple windows, but I'm not entirely sure if it was the source of segfault.

In version 2.2.1, sidebery restart itself after permission change and start the process of restoring the tabs tree. This is currently not so well optimized process, so I'll continue to work on it.

Few questions:
What is the structure of the tabs you had during the segfault - plain or tree?
Did you use bookmarks panel and if so, how much of them you have (approximately)?

**Comment by mbaz** [comment]
The tab restoration process is indeed slow; it takes maybe a minute on my i7 laptop and makes the fan sound like a vacuum cleaner :)

I have a tree structure. I do have the bookmark panel active, with maybe 4-5 hundred bookmarks.

**Comment by mbaz** [comment]
BTW, I disabled the bookmark panel just prior to updating to v2.2.2. The process of restoring the tabs was much faster and it didn't even engage the laptop's fan.

**Comment by mbnuqw** [comment]
Aha! Thanks for the info.

**Comment by mbnuqw** [comment]
@mbaz, could you please check current state of this issue? I've uploaded v2.4.0 with some optimizations of init process, so I hope there will no more such problems.

**Comment by mbaz** [comment]
@mbnuqw Upgrading TST and other vertical tabs extensions usually engage my laptop's fan and block firefox for tens of seconds or more. The update to v2.4.0 was so fast and smooth that I thought something had failed. Activating the bookmarks panel took less than two seconds. I don't know what you did but it seems to work :)
