### ISSUE TITLE
When hiding a panel then then the hidden panel cannot be made unhidden

### ISSUE THREAD

**Issue by devgid** [mbnuqw/sidebery#1918]
### Steps to reproduce

- Setup multiple panels
![image](https://github.com/user-attachments/assets/d79207f1-885c-4c20-9e47-43468a39a270)
- Right Click on Panel and click on Hide
![image](https://github.com/user-attachments/assets/c139a320-4567-4e40-aadd-783a826679e1)
- Icon to the right appears but clicking on it does nothing
![image](https://github.com/user-attachments/assets/14572673-2bc9-401c-9900-c3381342ada0)
- Go to Sideberry Panel settings 
![image](https://github.com/user-attachments/assets/b5f5da4a-c2c8-45fa-901e-dfe645c970bd)

### Actual behavior

Panels that are hidden are lost and its tab cannot be accessed or made visible again
Panels being hidden is per Firefox window so there is no setting to restore them and panel and tabs cannot be accessed again.

### Expected behavior

Panels that are hidden must be accessible
Settings that show hidden tabs must not be inactive as otherwise tabs in hidden panels cannot be accessed again
![image](https://github.com/user-attachments/assets/0256d496-4a83-43a9-9c0d-3dab6bb462ab)
Show Hidden button next to panels must be made to work or removed
![image](https://github.com/user-attachments/assets/5d4c4263-ab8e-48b1-98b4-4128a9bb2431)

### System

Windows 11

### Firefox version

133.0.3

### Sidebery version

5.2.0.9

### Logs

```code
Console is empty when hiding a tab and clicking on the Show Hidden Panel arrow which does noting
```

**Comment by llc0930** [comment]
If you turn off "Show navigation bar in one line", the "Hidden panels" element will take effect, it is just used to set the position of the button.
There may be other reasons why clicking a button doesn't work, which require a more detailed explanation, especially your other settings.

**Comment by devgid** [comment]
Nothing in sidebery console logs when click on the button

When you click on it, this transparent shadow appears
![image](https://github.com/user-attachments/assets/974a5593-7e42-431e-976e-62638cbd0b7d)

**Comment by devgid** [comment]
> If you turn off "Show navigation bar in one line", the "Hidden panels" element will take effect, it is just used to set the position of the button. There may be other reasons why clicking a button doesn't work, which require a more detailed explanation, especially your other settings.

If I set it to off that arrow icon disappears from right but is now on the left. Also the panel setting is now not disabled

![image](https://github.com/user-attachments/assets/6248fa5e-2bab-42f3-90ac-cce08234daa8)


the left down arrow only appears if a window has hidden panels in it. Otherwise it doesn't show  


![image](https://github.com/user-attachments/assets/a2d85cd1-3621-44c8-98b8-196f46c02a50)
Clicking on the down arrow it makes this overlay type darker transparent background image with nothing in it. 

I realized it  styleseditor to show panel icons in the bottom
 rather than top
 
 If I remove my css code 

`#root.root .top-horizontal-box {
  display: flex;
  order: 1 !important;
  margin: 100 auto !important;
margin-top :0px;
}`

Then I can see the panels in a submenu when pressing the down arrow.

Only problem is there is no way to make them unidden anymore as the right context menu in the submenu does not have the options for unhide.

![image](https://github.com/user-attachments/assets/47850e88-6ec5-432a-a657-f67e816149fd)

**Comment by llc0930** [comment]
> If I set it to off that arrow icon disappears from right but is now on the left.

Because you placed the component as the first item, the button is the first item from the left.
> Clicking on the down arrow it makes this overlay type darker transparent background image with nothing in it.
> I realized it styleseditor to show panel icons in the bottom rather than top

I think your custom CSS styles are causing the popup panel to appear outside the lower side of the visual area.
It looks like the problem is simply with your custom CSS styles.
> Only problem is there is no way to make them unidden anymore as the right context menu in the submenu does not have the options for unhide.

All you have to do is click on the panel and it will unhide itself.

**Comment by devgid** [comment]
Thanks I will try get solution for my custom css.
