### ISSUE TITLE
Merge move to window buttons

### ISSUE THREAD

**Issue by Ooglogput** [mbnuqw/sidebery#193]
## Description
As far as I can tell, _Move to another window_ is only available with two windows, and _Move to window..._ is only available with more than two. Could these be merged into one button?

**Comment by mbnuqw** [comment]
Well, this was strange solution :smile:...
I'm working on that and #181 right now

![screenshot-2020-04-10 16:30:15](https://user-images.githubusercontent.com/6276694/78987841-9bcd3480-7b48-11ea-8323-c226f7435950.png)

- in the second row - options for moving:
  - Move to new window (same type)
  - Move to window (this case)
  - Move to panel...
- in the third - options for reopening:
  - Reopen in new window of another type
  - Reopen in window of another type
  - Reopen in container...

**Comment by mbnuqw** [comment]
Fixed in the latest version.
