### ISSUE TITLE
Only load a tab on mouse up instead of down to allow for dragging discarded tabs

### ISSUE THREAD

**Issue by Keagel** [mbnuqw/sidebery#198]
## Description

Ideally you could move discarded tabs around without loading them.
For example, if the user clicks on a tab (or drags it a little but it doesn't change positions, to allow for accidental dragging?), on mouse up load the tab. If the tab has been dragged and its position has changed within the tree, don't load it. 
Maybe as an option?

**Comment by mbnuqw** [comment]
You need to switch option "Activate tab on mouse button release" in section "Tabs".
