### ISSUE TITLE
Hide pinned tabs of inactive panels?

### ISSUE THREAD

**Issue by CrendKing** [mbnuqw/sidebery#199]
## Description

I enabled "Hide tabs of inactive panels" but the pinned tabs of inactive panels are still visible. Is there a trick or hack to hide them too? If not, can you implement an option for it?

**Comment by mbnuqw** [comment]
Sorry, there is no way to hide pinned tabs using the current API. [more info](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/hide)
