### ISSUE TITLE
wrong switching between containers

### ISSUE THREAD

**Issue by dzejba** [mbnuqw/sidebery#20]
Bug faced with version 2.2.1.
Steps to reproduce:
* have default (DFLT) container and containers A and B, each with some tabs
* have DFLT container active with its tabs
* switch to container B
* switch to DFLT container
* BUG:
** Sidebery shows tabs from container A
** Firefox show tabs from DBLT but ALSO one container from A

**Comment by dzejba** [comment]
Cannot reproduce it always, will report if I find more details. But it happens pretty often.

**Comment by mbnuqw** [comment]
Thanks for reporting!
Could you please write what method you use to switch panels? (Click on panel icon, scroll on navigation strip, horizontal scroll)
Also, do you use any of these options: "Hide tabs of inactive panels" or "Hide folded tabs"?
Thanks

**Comment by dzejba** [comment]
I click on panel icon.
Options: 
* Hide tabs of inactive panels: on
* Tabs tree structure: off (thus Hide folded tabs unavailable)

**Comment by mbnuqw** [comment]
Found cause of bug, it'll be fixed in next release.

**Comment by mbnuqw** [comment]
Fixed in v2.3.0
