### ISSUE TITLE
Groups Periodically Get "Flattened"

### ISSUE THREAD

**Issue by ffabbroc** [mbnuqw/sidebery#201]
## Steps to reproduce

Sorry, I don't know how to reproduce this. I've tried to figure it out but haven't been able to.

## Expected behavior

Groups don't get "flattened"

## Actual behavior

Every once in a while, some or most of my groups become "flat", in other words, the pages under a group end up on the same level as the group.

Please see screenshot which shows a number of pages with groups that are all on the same level. Before this happened, all of the pages were under groups. :(
![2020-04-17_16-45-51](https://user-images.githubusercontent.com/1831958/79622207-2b379200-80cb-11ea-9b27-aa4c1d7463a1.png)

## Environment info

OS:  
Firefox version:  75.0
Addon version:  4.7.0

<details><code>
{
  "settings": {
    "version": "4.7.0",
    "nativeScrollbars": false,
    "selWinScreenshots": true,
    "tabsCheck": true,
    "tabsFix": "notify",
    "ctxMenuNative": true,
    "autoHideCtxMenu": "none",
    "ctxMenuRenderInact": true,
    "navBarLayout": "hidden",
    "navBarInline": false,
    "hideAddBtn": true,
    "hideSettingsBtn": false,
    "navBtnCount": true,
    "hideEmptyPanels": false,
    "navMidClickAction": "none",
    "navSwitchPanelsWheel": true,
    "groupLayout": "list",
    "dndTabAct": false,
    "dndTabActDelay": 750,
    "dndTabActMod": "none",
    "dndExp": "none",
    "dndExpDelay": 0,
    "dndExpMod": "none",
    "stateStorage": "global",
    "warnOnMultiTabClose": "any",
    "activateOnMouseUp": false,
    "activateLastTabOnPanelSwitching": true,
    "skipEmptyPanels": false,
    "showTabRmBtn": true,
    "showTabCtx": true,
    "hideInact": false,
    "activateAfterClosing": "prev_act",
    "activateAfterClosingPrevRule": "visible",
    "activateAfterClosingNextRule": "tree",
    "activateAfterClosingGlobal": false,
    "activateAfterClosingNoFolded": false,
    "activateAfterClosingNoDiscarded": false,
    "shiftSelAct": true,
    "askNewBookmarkPlace": false,
    "tabsRmUndoNote": true,
    "nativeHighlight": false,
    "tabsUnreadMark": false,
    "moveNewTabPin": "end",
    "moveNewTabParent": "last_child",
    "moveNewTabParentActPanel": true,
    "moveNewTab": "last_child",
    "pinnedTabsPosition": "panel",
    "pinnedTabsList": false,
    "pinnedAutoGroup": true,
    "tabsTree": true,
    "groupOnOpen": true,
    "tabsTreeLimit": "none",
    "hideFoldedTabs": false,
    "autoFoldTabs": false,
    "autoFoldTabsExcept": "none",
    "autoExpandTabs": true,
    "rmChildTabs": "none",
    "tabsChildCount": false,
    "tabsLvlDots": false,
    "discardFolded": false,
    "discardFoldedDelay": 0,
    "discardFoldedDelayUnit": "sec",
    "tabsTreeBookmarks": true,
    "bookmarksPanel": true,
    "warnOnMultiBookmarkDelete": "collapsed",
    "openBookmarkNewTab": false,
    "midClickBookmark": "open_new_tab",
    "actMidClickTab": false,
    "autoCloseBookmarks": false,
    "autoRemoveOther": false,
    "highlightOpenBookmarks": false,
    "activateOpenBookmarkTab": false,
    "showBookmarkLen": false,
    "bookmarksRmUndoNote": true,
    "fontSize": "xxs",
    "bgNoise": false,
    "animations": true,
    "animationSpeed": "fast",
    "theme": "tactile",
    "style": "dark",
    "sidebarCSS": false,
    "groupCSS": false,
    "snapNotify": true,
    "snapExcludePrivate": false,
    "snapInterval": 0,
    "snapIntervalUnit": "min",
    "snapLimit": 0,
    "snapLimitUnit": "snap",
    "hScrollThroughPanels": false,
    "scrollThroughTabs": "none",
    "scrollThroughVisibleTabs": false,
    "scrollThroughTabsSkipDiscarded": false,
    "scrollThroughTabsExceptOverflow": true,
    "scrollThroughTabsCyclic": false,
    "tabDoubleClick": "exp",
    "tabLongLeftClick": "none",
    "tabLongRightClick": "none",
    "tabsPanelLeftClickAction": "expand",
    "tabsPanelDoubleClickAction": "tab",
    "tabsPanelRightClickAction": "menu",
    "tabsPanelMiddleClickAction": "tab",
    "syncName": "",
    "syncSaveSettings": false,
    "syncSaveCtxMenu": false,
    "syncSaveStyles": false,
    "syncAutoApply": false
  },
  "permissions": {
    "allUrls": false,
    "tabHide": false,
    "actualAllUrls": false,
    "actualTabHide": false
  },
  "storage": {
    "size": "956.7 kb",
    "props": {
      "bookmarksMenu": "226 b",
      "bookmarksPanelMenu": "54 b",
      "containers_v4": "1 kb",
      "cssVars": "1.6 kb",
      "disabledKeybindings": "2 b",
      "expandedBookmarks": "18 b",
      "favAutoCleanTime": "10 b",
      "favUrls": "14.6 kb",
      "favicons": "813.2 kb",
      "lastSnapTime": "13 b",
      "panelIndex": "1 b",
      "panels_v4": "378 b",
      "prevTabsData_v4": "36.9 kb",
      "profileID": "14 b",
      "settings": "2.4 kb",
      "snapshots_v4": "50.1 kb",
      "tabsData_v4": "35.1 kb",
      "tabsMenu": "299 b",
      "tabsPanelMenu": "170 b"
    }
  },
  "panels": [
    {
      "type": "default",
      "id": "firefox-default",
      "name": 7,
      "icon": "...",
      "cookieStoreId": "firefox-default",
      "lockedTabs": false,
      "lockedPanel": false,
      "noEmpty": false,
      "newTabCtx": "none",
      "moveTabCtx": "none",
      "moveTabCtxNoChild": true
    },
    {
      "type": "bookmarks",
      "id": "bookmarks",
      "cookieStoreId": "bookmarks",
      "name": 9,
      "icon": "...",
      "bookmarks": true,
      "lockedPanel": false
    }
  ],
  "cssVars": {
    "bg": "#323232",
    "btn_bg": "#000000",
    "tabs_fg": "#FFFFFF",
    "tabs_fg_hover": "#FFFFFF",
    "tabs_fg_active": "#FFFFFF",
    "tabs_activated_bg": "rgba(36,36,36,0.686)",
    "tabs_selected_fg": "#FFFFFF"
  },
  "windows": [
    {
      "state": "maximized",
      "incognito": false,
      "tabsCount": 277
    }
  ],
  "tabsMenu": [
    [
      "undoRmTab",
      "mute",
      "reload",
      "bookmark"
    ],
    "separator-1",
    [
      {
        "name": "Move to"
      },
      "moveToNewWin",
      "moveToNewPrivWin",
      "moveToAnotherWin",
      "moveToWin"
    ],
    [
      {
        "name": "Reopen in"
      },
      "moveToCtr"
    ],
    "separator-2",
    "pin",
    "duplicate",
    "discard",
    "copyUrls",
    "separator-3",
    "group",
    "flatten",
    "separator-4",
    "clearCookies",
    "close"
  ],
  "bookmarksMenu": [
    [
      {
        "name": "Open in"
      },
      "openInNewWin",
      "openInNewPrivWin",
      "openInCtr"
    ],
    "separator-5",
    "createBookmark",
    "createFolder",
    "createSeparator",
    "separator-6",
    "sortByName",
    "sortByLink",
    "sortByTime",
    "separator-7",
    "copyUrls",
    "edit",
    "delete"
  ],
  "bookmarks": {
    "bookmarksCount": 11503,
    "foldersCount": 1122,
    "separatorsCount": 4,
    "maxDepth": 7
  }
}
</code></details>

**Comment by mbnuqw** [comment]
Thanks for the report. Does this happen after launching the browser/extension or just randomly after some action like - opening/closing/moving tab?

I've fixed some stability issues for the next release, which can be the root of this problem, so hopefully this will be fixed (I plan to upload new version in the next 2-3 days).

**Comment by ffabbroc** [comment]
Max, unforutnately, it happens randomly and I haven't been able to identify a cause or action.

I do feel that it's somehow tied to showing or hiding the sidebar because although I usually have Sideberry always displayed, sometimes I hide the sidebar so that I can use the full Firefox screen. Then when I show the sidebar, it's been "flattened". 

I've got automatic snapshots enabled to run every hour, so hopefully that will help come up with repro steps.

Thanks,
Francesco

**Comment by mbnuqw** [comment]
@ffabbroc, could you please check the latest version (v4.8.0)?

**Comment by ffabbroc** [comment]
Max, I installed it and so far so good. Thanks for the support!

**Comment by mbnuqw** [comment]
Closing this, if there will be problems, please, reopen.
