### ISSUE TITLE
"Wrong tab position detected", when I click "Update tabs" it makes the tab position worse

### ISSUE THREAD

**Issue by snowe2010** [mbnuqw/sidebery#202]
## Steps to reproduce

Absolutely no clue. It happens on and off when opening new tabs, closing tabs, or reordering tabs

## Expected behavior

No clue what the desired behavior here is. I'm guessing it should put the tabs into their correct profiles, e.g. personal to personal, work to work, etc. 

## Actual behavior

When opening and closing tabs, notification pops up stating that the tabs are in the wrong position. If I click hide, and continue to open and close tabs, the notifications keep popping up. If I click on Update Tabs, tabs actually get reordered into the _wrong_ sections of Sidebery. I've provided a gif that demonstrates this behavior partially, though I didn't capture it reordering the tabs into the wrong position, but more that they are not reordered at all (I have too many tabs to have them all on screen at once)

Some background information. For a while now, Sidebery has been putting tabs into the wrong location. If I open a new Personal tab, for example, it might open in my Work profile. I'm guessing the goal of this new "Update tabs" feature was to fix this. My tabs are currently very badly out of order, so if you would like me to export all my tabs so you can have my entire setup I will do that. 

## Environment info
OS:  mac
Firefox version:  75.0
Addon version:  4.7.0

<details><code>
{
  "settings": {
    "version": "4.7.0",
    "nativeScrollbars": false,
    "selWinScreenshots": true,
    "tabsCheck": true,
    "tabsFix": "notify",
    "ctxMenuNative": false,
    "autoHideCtxMenu": "none",
    "ctxMenuRenderInact": false,
    "navBarLayout": "horizontal",
    "navBarInline": true,
    "hideAddBtn": false,
    "hideSettingsBtn": false,
    "navBtnCount": false,
    "hideEmptyPanels": true,
    "navMidClickAction": "none",
    "navSwitchPanelsWheel": true,
    "groupLayout": "grid",
    "dndTabAct": true,
    "dndTabActDelay": 750,
    "dndTabActMod": "none",
    "dndExp": "pointer",
    "dndExpDelay": 0,
    "dndExpMod": "none",
    "stateStorage": "global",
    "warnOnMultiTabClose": "collapsed",
    "activateOnMouseUp": false,
    "activateLastTabOnPanelSwitching": true,
    "skipEmptyPanels": false,
    "showTabRmBtn": true,
    "showTabCtx": true,
    "hideInact": false,
    "activateAfterClosing": "next",
    "activateAfterClosingPrevRule": "visible",
    "activateAfterClosingNextRule": "tree",
    "activateAfterClosingGlobal": false,
    "activateAfterClosingNoFolded": false,
    "activateAfterClosingNoDiscarded": false,
    "shiftSelAct": true,
    "askNewBookmarkPlace": false,
    "tabsRmUndoNote": true,
    "nativeHighlight": false,
    "tabsUnreadMark": false,
    "moveNewTabPin": "start",
    "moveNewTabParent": "last_child",
    "moveNewTabParentActPanel": false,
    "moveNewTab": "end",
    "pinnedTabsPosition": "panel",
    "pinnedTabsList": false,
    "pinnedAutoGroup": true,
    "tabsTree": true,
    "groupOnOpen": true,
    "tabsTreeLimit": "none",
    "hideFoldedTabs": false,
    "autoFoldTabs": false,
    "autoFoldTabsExcept": "none",
    "autoExpandTabs": false,
    "rmChildTabs": "none",
    "tabsChildCount": true,
    "tabsLvlDots": false,
    "discardFolded": false,
    "discardFoldedDelay": 0,
    "discardFoldedDelayUnit": "sec",
    "tabsTreeBookmarks": true,
    "bookmarksPanel": true,
    "warnOnMultiBookmarkDelete": "collapsed",
    "openBookmarkNewTab": false,
    "midClickBookmark": "open_new_tab",
    "actMidClickTab": false,
    "autoCloseBookmarks": false,
    "autoRemoveOther": false,
    "highlightOpenBookmarks": false,
    "activateOpenBookmarkTab": false,
    "showBookmarkLen": false,
    "bookmarksRmUndoNote": true,
    "fontSize": "m",
    "bgNoise": true,
    "animations": true,
    "animationSpeed": "fast",
    "theme": "default",
    "style": "dark",
    "sidebarCSS": true,
    "groupCSS": false,
    "snapNotify": true,
    "snapExcludePrivate": false,
    "snapInterval": 20,
    "snapIntervalUnit": "min",
    "snapLimit": 2,
    "snapLimitUnit": "snap",
    "hScrollThroughPanels": false,
    "scrollThroughTabs": "none",
    "scrollThroughVisibleTabs": false,
    "scrollThroughTabsSkipDiscarded": false,
    "scrollThroughTabsExceptOverflow": true,
    "scrollThroughTabsCyclic": false,
    "tabDoubleClick": "none",
    "tabLongLeftClick": "none",
    "tabLongRightClick": "none",
    "tabsPanelLeftClickAction": "none",
    "tabsPanelDoubleClickAction": "tab",
    "tabsPanelRightClickAction": "none",
    "tabsPanelMiddleClickAction": "tab",
    "syncName": "",
    "syncSaveSettings": false,
    "syncSaveCtxMenu": false,
    "syncSaveStyles": false,
    "syncAutoApply": false
  },
  "permissions": {
    "allUrls": true,
    "tabHide": false,
    "actualAllUrls": true,
    "actualTabHide": false
  },
  "storage": {
    "size": "4.3 mb",
    "props": {
      "containers_v4": "788 b",
      "cssVars": "1.6 kb",
      "favAutoCleanTime": "10 b",
      "favUrls": "129.3 kb",
      "favicons": "3.2 mb",
      "lastSnapTime": "13 b",
      "panelIndex": "1 b",
      "panels": "1.1 kb",
      "panels_v4": "1.1 kb",
      "prevTabsData_v4": "99.8 kb",
      "prevTabsTrees": "20.6 kb",
      "profileID": "14 b",
      "settings": "1.4 kb",
      "sidebarCSS": "33 b",
      "snapshots": "324.4 kb",
      "snapshots_v4": "341 kb",
      "tabsData_v4": "102.5 kb",
      "tabsTrees": "20.6 kb"
    }
  },
  "panels": [
    {
      "type": "bookmarks",
      "id": "bookmarks",
      "cookieStoreId": "bookmarks",
      "name": 9,
      "icon": "...",
      "bookmarks": true,
      "lockedPanel": false
    },
    {
      "type": "default",
      "id": "firefox-default",
      "name": 7,
      "icon": "...",
      "cookieStoreId": "firefox-default",
      "lockedTabs": false,
      "lockedPanel": false,
      "noEmpty": false,
      "newTabCtx": "none"
    },
    {
      "type": "tabs",
      "id": "KV0s5rtq0HbK",
      "name": 8,
      "icon": "...",
      "color": "...",
      "customIconSrc": "",
      "customIcon": "",
      "lockedTabs": false,
      "lockedPanel": false,
      "noEmpty": false,
      "newTabCtx": "firefox-container-1",
      "moveTabCtx": "firefox-container-1",
      "urlRulesActive": false,
      "urlRules": ""
    },
    {
      "type": "tabs",
      "id": "DGkGJ8fq0HbK",
      "name": 4,
      "icon": "...",
      "color": "...",
      "customIconSrc": "",
      "customIcon": "",
      "lockedTabs": false,
      "lockedPanel": false,
      "noEmpty": false,
      "newTabCtx": "firefox-container-2",
      "moveTabCtx": "firefox-container-2",
      "urlRulesActive": false,
      "urlRules": ""
    },
    {
      "type": "tabs",
      "id": "yhoiQsIq0HbK",
      "name": 9,
      "icon": "...",
      "color": "...",
      "customIconSrc": "",
      "customIcon": "",
      "lockedTabs": false,
      "lockedPanel": false,
      "noEmpty": false,
      "newTabCtx": "firefox-container-6",
      "moveTabCtx": "firefox-container-6",
      "urlRulesActive": false,
      "urlRules": ""
    }
  ],
  "cssVars": {
    "nav_btn_width": "30px"
  },
  "sidebarCSSLen": 29,
  "windows": [
    {
      "state": "maximized",
      "incognito": false,
      "tabsCount": 368
    },
    {
      "state": "minimized",
      "incognito": false,
      "tabsCount": 57
    },
    {
      "state": "minimized",
      "incognito": false,
      "tabsCount": 2
    },
    {
      "state": "maximized",
      "incognito": false,
      "tabsCount": 6
    },
    {
      "state": "normal",
      "incognito": false,
      "tabsCount": 441
    },
    {
      "state": "minimized",
      "incognito": false,
      "tabsCount": 22
    },
    {
      "state": "maximized",
      "incognito": false,
      "tabsCount": 3
    },
    {
      "state": "minimized",
      "incognito": false,
      "tabsCount": 1
    },
    {
      "state": "minimized",
      "incognito": false,
      "tabsCount": 2
    },
    {
      "state": "minimized",
      "incognito": false,
      "tabsCount": 10
    },
    {
      "state": "maximized",
      "incognito": true,
      "tabsCount": 3
    }
  ],
  "bookmarks": {
    "bookmarksCount": 565,
    "foldersCount": 27,
    "separatorsCount": 2,
    "maxDepth": 3
  }
}
</code></details>

![sidebery_update_tabs_issue](https://user-images.githubusercontent.com/1534535/79626028-35b55400-80ea-11ea-8204-6942fed71d0d.gif)

**Comment by mbnuqw** [comment]
Sorry for this issue. Yes, this is a known problem and I fixed it for the next release, which will be (hopefully) available in the next 2-3 days.

The initial issue, which is the cause of appearing these notifications, is the wrong tabs indexing (internal state differ from the actual native tabs). This happens when sidebery and another extension trying to change the tabs list simultaneously. So possible temp workarounds may look horrible:
- Use only one panel and turn off the "Position of the new tab" settings.
- Find incompatible extension and disable it.

I'll try not to delay the new release and hope the problem will be resolved.

**Comment by snowe2010** [comment]
Hmm. I wonder what extension could be causing it. I don't have anything else installed that would mess with the tabs, except Multi-account containers. Would that be doing it?

**Comment by mbnuqw** [comment]
Well, I wrote about other extensions because this is the only way I can reproduce this (and all related) issue. Maybe there is some tricky small bug in sidebery itself I didn't found yet :smile:

I've just update addon to v4.8.0. Could you please check this version?

**Comment by snowe2010** [comment]
Sure thing! Is there any way to 'force' it to rearrange the tabs? Or do I just need to wait until I get the notification again?

**Comment by mbnuqw** [comment]
If you have the `Automatically check whether tabs are positioned correctly` option enabled (in Help section), you can just create, move or close some tab to trigger the tabs position check. And if any problem is detected, you will get notification or tabs will be moved automatically (depending on the `When an error is detected:` option).

**Comment by snowe2010** [comment]
Ok, been trying for a few days and haven't seen any issues with the notifications! Haven't seen any notifications at all for tabs being reordered actually. 

What is the desired functionality of the Check? For example I have many tabs that are in the wrong section (Personal tabs in the Work panel for example), but haven't seen the notification to update them.

**Comment by mbnuqw** [comment]
`What is the desired functionality of the Check?`
It goes through the panels tabs and check indexing before save tabs data. This is enough (well, in tested cases) to detect wrong tabs positioning.

Also, note that after reload of sidebar with the incorrectly placed tabs, sidebery will update their relations with the panels, which unfortunately means that you will be needed manually move the tabs to the desired panel. (its the price for the fast startup)

Could you write what event precede the incorrect positioning of the tabs? (sidebar [re]load, creating/moving/removing tab, reopening tab in container, drag-n-drop...etc)

**Comment by snowe2010** [comment]
>Also, note that after reload of sidebar with the incorrectly placed tabs, sidebery will update their relations with the panels, which unfortunately means that you will be needed manually move the tabs to the desired panel. (its the price for the fast startup)

Ah ok, so that explains that. Cool!

>Could you write what event precede the incorrect positioning of the tabs? (sidebar [re]load, creating/moving/removing tab, reopening tab in container, drag-n-drop...etc)

So in the past when opening a new tab, I could use either cmd+t to open a new tab in the default profile, or ctrl+t to open a new tab in the current profile. Recently, cmd+t has started opening new tabs in the default profile, but in the current panel rather than in the default profile panel. So no matter which shortcut I use, they always open in the current panel, rather than the panel for their profile.

**Comment by mbnuqw** [comment]
You can use option "Move tab to this panel..." in the panel's config, to control the default panel for the new tab:

![screenshot-2020-04-23 21:53:08_001](https://user-images.githubusercontent.com/6276694/80126995-21bb9780-85ad-11ea-898e-2935b66c9c0c.png)

With this option, sidebery will automatically move the new tab opened with the cmd+t shortcut to the Default (or wherever you want) panel. This behavior will apply to all "externally" opened tabs (tabs opened from another app, or from the bookmarks, or from the cmd+t, which is our case) because they all in the default container.

**Comment by snowe2010** [comment]
Fantastic! Seems like everything is fixed then! Thanks! Sidebery is awesome. Thanks for all the hard work!

**Comment by yarub123** [comment]
> ## Steps to reproduce
> 
> Absolutely no clue. It happens on and off when opening new tabs, closing tabs, or reordering tabs
> ## Expected behavior
> 
> No clue what the desired behavior here is. I'm guessing it should put the tabs into their correct profiles, e.g. personal to personal, work to work, etc.
> ## Actual behavior
> 
> When opening and closing tabs, notification pops up stating that the tabs are in the wrong position. If I click hide, and continue to open and close tabs, the notifications keep popping up. If I click on Update Tabs, tabs actually get reordered into the _wrong_ sections of Sidebery. I've provided a gif that demonstrates this behavior partially, though I didn't capture it reordering the tabs into the wrong position, but more that they are not reordered at all (I have too many tabs to have them all on screen at once)
> 
> Some background information. For a while now, Sidebery has been putting tabs into the wrong location. If I open a new Personal tab, for example, it might open in my Work profile. I'm guessing the goal of this new "Update tabs" feature was to fix this. My tabs are currently very badly out of order, so if you would like me to export all my tabs so you can have my entire setup I will do that.
> ## Environment info
> 
> OS: mac
> Firefox version: 75.0
> Addon version: 4.7.0
> ` { "settings": { "version": "4.7.0", "nativeScrollbars": false, "selWinScreenshots": true, "tabsCheck": true, "tabsFix": "notify", "ctxMenuNative": false, "autoHideCtxMenu": "none", "ctxMenuRenderInact": false, "navBarLayout": "horizontal", "navBarInline": true, "hideAddBtn": false, "hideSettingsBtn": false, "navBtnCount": false, "hideEmptyPanels": true, "navMidClickAction": "none", "navSwitchPanelsWheel": true, "groupLayout": "grid", "dndTabAct": true, "dndTabActDelay": 750, "dndTabActMod": "none", "dndExp": "pointer", "dndExpDelay": 0, "dndExpMod": "none", "stateStorage": "global", "warnOnMultiTabClose": "collapsed", "activateOnMouseUp": false, "activateLastTabOnPanelSwitching": true, "skipEmptyPanels": false, "showTabRmBtn": true, "showTabCtx": true, "hideInact": false, "activateAfterClosing": "next", "activateAfterClosingPrevRule": "visible", "activateAfterClosingNextRule": "tree", "activateAfterClosingGlobal": false, "activateAfterClosingNoFolded": false, "activateAfterClosingNoDiscarded": false, "shiftSelAct": true, "askNewBookmarkPlace": false, "tabsRmUndoNote": true, "nativeHighlight": false, "tabsUnreadMark": false, "moveNewTabPin": "start", "moveNewTabParent": "last_child", "moveNewTabParentActPanel": false, "moveNewTab": "end", "pinnedTabsPosition": "panel", "pinnedTabsList": false, "pinnedAutoGroup": true, "tabsTree": true, "groupOnOpen": true, "tabsTreeLimit": "none", "hideFoldedTabs": false, "autoFoldTabs": false, "autoFoldTabsExcept": "none", "autoExpandTabs": false, "rmChildTabs": "none", "tabsChildCount": true, "tabsLvlDots": false, "discardFolded": false, "discardFoldedDelay": 0, "discardFoldedDelayUnit": "sec", "tabsTreeBookmarks": true, "bookmarksPanel": true, "warnOnMultiBookmarkDelete": "collapsed", "openBookmarkNewTab": false, "midClickBookmark": "open_new_tab", "actMidClickTab": false, "autoCloseBookmarks": false, "autoRemoveOther": false, "highlightOpenBookmarks": false, "activateOpenBookmarkTab": false, "showBookmarkLen": false, "bookmarksRmUndoNote": true, "fontSize": "m", "bgNoise": true, "animations": true, "animationSpeed": "fast", "theme": "default", "style": "dark", "sidebarCSS": true, "groupCSS": false, "snapNotify": true, "snapExcludePrivate": false, "snapInterval": 20, "snapIntervalUnit": "min", "snapLimit": 2, "snapLimitUnit": "snap", "hScrollThroughPanels": false, "scrollThroughTabs": "none", "scrollThroughVisibleTabs": false, "scrollThroughTabsSkipDiscarded": false, "scrollThroughTabsExceptOverflow": true, "scrollThroughTabsCyclic": false, "tabDoubleClick": "none", "tabLongLeftClick": "none", "tabLongRightClick": "none", "tabsPanelLeftClickAction": "none", "tabsPanelDoubleClickAction": "tab", "tabsPanelRightClickAction": "none", "tabsPanelMiddleClickAction": "tab", "syncName": "", "syncSaveSettings": false, "syncSaveCtxMenu": false, "syncSaveStyles": false, "syncAutoApply": false }, "permissions": { "allUrls": true, "tabHide": false, "actualAllUrls": true, "actualTabHide": false }, "storage": { "size": "4.3 mb", "props": { "containers_v4": "788 b", "cssVars": "1.6 kb", "favAutoCleanTime": "10 b", "favUrls": "129.3 kb", "favicons": "3.2 mb", "lastSnapTime": "13 b", "panelIndex": "1 b", "panels": "1.1 kb", "panels_v4": "1.1 kb", "prevTabsData_v4": "99.8 kb", "prevTabsTrees": "20.6 kb", "profileID": "14 b", "settings": "1.4 kb", "sidebarCSS": "33 b", "snapshots": "324.4 kb", "snapshots_v4": "341 kb", "tabsData_v4": "102.5 kb", "tabsTrees": "20.6 kb" } }, "panels": [ { "type": "bookmarks", "id": "bookmarks", "cookieStoreId": "bookmarks", "name": 9, "icon": "...", "bookmarks": true, "lockedPanel": false }, { "type": "default", "id": "firefox-default", "name": 7, "icon": "...", "cookieStoreId": "firefox-default", "lockedTabs": false, "lockedPanel": false, "noEmpty": false, "newTabCtx": "none" }, { "type": "tabs", "id": "KV0s5rtq0HbK", "name": 8, "icon": "...", "color": "...", "customIconSrc": "", "customIcon": "", "lockedTabs": false, "lockedPanel": false, "noEmpty": false, "newTabCtx": "firefox-container-1", "moveTabCtx": "firefox-container-1", "urlRulesActive": false, "urlRules": "" }, { "type": "tabs", "id": "DGkGJ8fq0HbK", "name": 4, "icon": "...", "color": "...", "customIconSrc": "", "customIcon": "", "lockedTabs": false, "lockedPanel": false, "noEmpty": false, "newTabCtx": "firefox-container-2", "moveTabCtx": "firefox-container-2", "urlRulesActive": false, "urlRules": "" }, { "type": "tabs", "id": "yhoiQsIq0HbK", "name": 9, "icon": "...", "color": "...", "customIconSrc": "", "customIcon": "", "lockedTabs": false, "lockedPanel": false, "noEmpty": false, "newTabCtx": "firefox-container-6", "moveTabCtx": "firefox-container-6", "urlRulesActive": false, "urlRules": "" } ], "cssVars": { "nav_btn_width": "30px" }, "sidebarCSSLen": 29, "windows": [ { "state": "maximized", "incognito": false, "tabsCount": 368 }, { "state": "minimized", "incognito": false, "tabsCount": 57 }, { "state": "minimized", "incognito": false, "tabsCount": 2 }, { "state": "maximized", "incognito": false, "tabsCount": 6 }, { "state": "normal", "incognito": false, "tabsCount": 441 }, { "state": "minimized", "incognito": false, "tabsCount": 22 }, { "state": "maximized", "incognito": false, "tabsCount": 3 }, { "state": "minimized", "incognito": false, "tabsCount": 1 }, { "state": "minimized", "incognito": false, "tabsCount": 2 }, { "state": "minimized", "incognito": false, "tabsCount": 10 }, { "state": "maximized", "incognito": true, "tabsCount": 3 } ], "bookmarks": { "bookmarksCount": 565, "foldersCount": 27, "separatorsCount": 2, "maxDepth": 3 } } `
> 
> ![sidebery_update_tabs_issue](https://user-images.githubusercontent.com/1534535/79626028-35b55400-80ea-11ea-8204-6942fed71d0d.gif)

yo how did you do the autohide been lookin for it forever. like autohide the panel but activate on hover.

**Comment by snowe2010** [comment]
@yarub123 https://github.com/mbnuqw/sidebery/issues/240, but google has more up to date results.
