### ISSUE TITLE
Click and dragging a tab crashes Firefox

### ISSUE THREAD

**Issue by OJFord** [mbnuqw/sidebery#204]
## Steps to reproduce
Click and drag on a tab.

## Expected behavior
1. I was trying to de-tree a tab, but I don't know if that's supposed to work for that.
2. Not crash Firefox.

## Actual behavior
Firefox crashes.

## Environment info
OS: linux
Firefox: 75.0
Addon: 4.7.0

<details><code>
{
  "settings": {
    "version": "4.7.0",
    "nativeScrollbars": true,
    "selWinScreenshots": true,
    "tabsCheck": true,
    "tabsFix": "notify",
    "ctxMenuNative": false,
    "autoHideCtxMenu": "none",
    "ctxMenuRenderInact": true,
    "navBarLayout": "horizontal",
    "navBarInline": false,
    "hideAddBtn": false,
    "hideSettingsBtn": false,
    "navBtnCount": true,
    "hideEmptyPanels": true,
    "navMidClickAction": "none",
    "navSwitchPanelsWheel": true,
    "groupLayout": "grid",
    "dndTabAct": true,
    "dndTabActDelay": 750,
    "dndTabActMod": "none",
    "dndExp": "pointer",
    "dndExpDelay": 0,
    "dndExpMod": "none",
    "stateStorage": "global",
    "warnOnMultiTabClose": "collapsed",
    "activateOnMouseUp": false,
    "activateLastTabOnPanelSwitching": true,
    "skipEmptyPanels": false,
    "showTabRmBtn": true,
    "showTabCtx": true,
    "hideInact": false,
    "activateAfterClosing": "next",
    "activateAfterClosingPrevRule": "visible",
    "activateAfterClosingNextRule": "tree",
    "activateAfterClosingGlobal": false,
    "activateAfterClosingNoFolded": false,
    "activateAfterClosingNoDiscarded": false,
    "shiftSelAct": true,
    "askNewBookmarkPlace": false,
    "tabsRmUndoNote": true,
    "nativeHighlight": false,
    "tabsUnreadMark": false,
    "moveNewTabPin": "start",
    "moveNewTabParent": "last_child",
    "moveNewTabParentActPanel": false,
    "moveNewTab": "end",
    "pinnedTabsPosition": "panel",
    "pinnedTabsList": false,
    "pinnedAutoGroup": true,
    "tabsTree": true,
    "groupOnOpen": true,
    "tabsTreeLimit": "none",
    "hideFoldedTabs": false,
    "autoFoldTabs": false,
    "autoFoldTabsExcept": "none",
    "autoExpandTabs": false,
    "rmChildTabs": "none",
    "tabsChildCount": true,
    "tabsLvlDots": false,
    "discardFolded": false,
    "discardFoldedDelay": 0,
    "discardFoldedDelayUnit": "sec",
    "tabsTreeBookmarks": true,
    "bookmarksPanel": true,
    "warnOnMultiBookmarkDelete": "collapsed",
    "openBookmarkNewTab": false,
    "midClickBookmark": "open_new_tab",
    "actMidClickTab": false,
    "autoCloseBookmarks": false,
    "autoRemoveOther": false,
    "highlightOpenBookmarks": false,
    "activateOpenBookmarkTab": false,
    "showBookmarkLen": false,
    "bookmarksRmUndoNote": true,
    "fontSize": "xxs",
    "bgNoise": true,
    "animations": true,
    "animationSpeed": "fast",
    "theme": "default",
    "style": "dark",
    "sidebarCSS": false,
    "groupCSS": false,
    "snapNotify": true,
    "snapExcludePrivate": false,
    "snapInterval": 0,
    "snapIntervalUnit": "min",
    "snapLimit": 0,
    "snapLimitUnit": "snap",
    "hScrollThroughPanels": false,
    "scrollThroughTabs": "none",
    "scrollThroughVisibleTabs": false,
    "scrollThroughTabsSkipDiscarded": false,
    "scrollThroughTabsExceptOverflow": true,
    "scrollThroughTabsCyclic": false,
    "tabDoubleClick": "none",
    "tabLongLeftClick": "none",
    "tabLongRightClick": "none",
    "tabsPanelLeftClickAction": "none",
    "tabsPanelDoubleClickAction": "tab",
    "tabsPanelRightClickAction": "menu",
    "tabsPanelMiddleClickAction": "tab",
    "syncName": "",
    "syncSaveSettings": false,
    "syncSaveCtxMenu": false,
    "syncSaveStyles": false,
    "syncAutoApply": false
  },
  "permissions": {
    "allUrls": false,
    "tabHide": false,
    "actualAllUrls": false,
    "actualTabHide": false
  },
  "storage": {
    "size": "119 kb",
    "props": {
      "cssVars": "1.6 kb",
      "expandedBookmarks": "2 b",
      "favAutoCleanTime": "10 b",
      "favUrls": "7.6 kb",
      "favicons": "102.9 kb",
      "panelIndex": "1 b",
      "panels_v4": "378 b",
      "prevTabsData_v4": "1.6 kb",
      "profileID": "14 b",
      "settings": "2.5 kb",
      "sidebarCSS": "2 b",
      "tabsData_v4": "1.8 kb"
    }
  },
  "panels": [
    {
      "type": "bookmarks",
      "id": "bookmarks",
      "cookieStoreId": "bookmarks",
      "name": 9,
      "icon": "...",
      "bookmarks": true,
      "lockedPanel": false
    },
    {
      "type": "default",
      "id": "firefox-default",
      "name": 7,
      "icon": "...",
      "cookieStoreId": "firefox-default",
      "lockedTabs": false,
      "lockedPanel": false,
      "noEmpty": false,
      "newTabCtx": "none",
      "moveTabCtx": "none",
      "moveTabCtxNoChild": true
    }
  ],
  "cssVars": {
    "tabs_height": "20px",
    "tabs_font": "0.8rem sans-serif"
  },
  "sidebarCSSLen": 0,
  "windows": [
    {
      "state": "normal",
      "incognito": false,
      "tabsCount": 25
    }
  ],
  "bookmarks": {
    "bookmarksCount": 168,
    "foldersCount": 24,
    "separatorsCount": 1,
    "maxDepth": 3
  }
}
</code></details>

**Comment by mbnuqw** [comment]
Thank you for the report, but I cannot reproduce this issue. Does this bug Sidebery specific? Could you please try to reproduce it on other tree tabs extensions (Tree Style Tab, Tree Tabs)?

**Comment by OJFord** [comment]
I previously used Tab Center Redux, and didn't have the issue, dragging successfully reorders tabs.

Having said that, I'm presently using my work Macbook, and I just tried in Sidebery and it also reordered (didn't crash). (What it did do earlier is suddenly restart Sidebery, not Firefox, reloading in 'auto' - light - theme instead of dark, but that's not reproducible.)

So, perhaps it's Linux-specific.

**Comment by OJFord** [comment]
Closing this as I no longer experience it. It may have been related to some other strange gtk errors that I think a reinstall fixed.
