### ISSUE TITLE
Add an attribute to the #root div for the side of the browser window Sidebery is on

### ISSUE THREAD

**Issue by nearcatch** [mbnuqw/sidebery#205]
I would like an attribute on \#root that corresponds to the side of the browser window Sidebery is on. For example, if it's on the right side the attribute is [window-position="right"], and left side is [window-position="left"]. I'm trying to package up my CSS tweaks to share with others, but I need to be able to disable some CSS blocks based on which side Sidebery is using.

**Comment by mbnuqw** [comment]
Unfortunately there is no way to find on which side sidebery is. So defining the window side for the sidebar is up to end-user :/

**Comment by nearcatch** [comment]
Unfortunate, thanks anyway.

**Comment by dexeonify** [comment]
No need for CSS, it's an option in Firefox. Click the big "Sidebery" label at the top of the sidebar and click "Move Sidebar to Right". Make sure you didn't remove the header with userChrome CSS.

**Comment by ImperialSquid** [comment]
> No need for CSS, it's an option in Firefox. Click the big "Sidebery" label at the top of the sidebar and click "Move Sidebar to Right". Make sure you didn't remove the header with userChrome CSS.

Yeah I figured this out like an hour or so after commenting and fully forgot to come back to add an edit 😅 cheers though!
