### ISSUE TITLE
Load tabs progressively allows more tabs if from different reload commands

### ISSUE THREAD

**Issue by nearcatch** [mbnuqw/sidebery#210]
## Steps to reproduce
1. Set max loading tabs to 2 tabs.
2. Open 2 groups of 20 tabs or so.
3. Select 1st group of tabs and reload. Select 2nd group of tabs and reload.

## Expected behavior
1. Tabs should be limited to 2 loading tabs, regardless of which group is loading.

## Actual behavior
1. 2 tabs from each group of 20 load, for a max of 4 tabs loading.

## Comments
Right now it seems like this feature works on a per-reload command basis, not a global limit. Sometimes I'll reload multiple discarded groups in preparation of some work, and it would be nice to not slow down the browser while they load. I use the limit of 5 loading tabs, so reloading 3 different groups means I have 15 tabs loading instead of 5.

## Environment info

OS: win
Firefox: 76.0
Addon: 4.8.0

<details><code>{
  "settings": {
    "version": "4.8.0",
    "nativeScrollbars": true,
    "selWinScreenshots": true,
    "tabsCheck": true,
    "tabsFix": "notify",
    "ctxMenuNative": false,
    "autoHideCtxMenu": "none",
    "ctxMenuRenderInact": true,
    "navBarLayout": "horizontal",
    "navBarInline": false,
    "hideAddBtn": true,
    "hideSettingsBtn": false,
    "navBtnCount": true,
    "hideEmptyPanels": false,
    "navMidClickAction": "none",
    "navSwitchPanelsWheel": false,
    "groupLayout": "list",
    "dndTabAct": false,
    "dndTabActDelay": 750,
    "dndTabActMod": "none",
    "dndExp": "pointer",
    "dndExpDelay": 0,
    "dndExpMod": "none",
    "stateStorage": "global",
    "warnOnMultiTabClose": "any",
    "activateOnMouseUp": true,
    "activateLastTabOnPanelSwitching": false,
    "skipEmptyPanels": false,
    "showTabRmBtn": false,
    "showTabCtx": true,
    "hideInact": true,
    "activateAfterClosing": "next",
    "activateAfterClosingPrevRule": "tree",
    "activateAfterClosingNextRule": "tree",
    "activateAfterClosingGlobal": false,
    "activateAfterClosingNoFolded": true,
    "activateAfterClosingNoDiscarded": true,
    "shiftSelAct": true,
    "askNewBookmarkPlace": true,
    "tabsRmUndoNote": true,
    "nativeHighlight": true,
    "tabsUnreadMark": true,
    "tabsReloadLimit": 5,
    "moveNewTabPin": "end",
    "moveNewTabParent": "last_child",
    "moveNewTabParentActPanel": false,
    "moveNewTab": "end",
    "pinnedTabsPosition": "panel",
    "pinnedTabsList": false,
    "pinnedAutoGroup": true,
    "tabsTree": true,
    "groupOnOpen": true,
    "tabsTreeLimit": "none",
    "hideFoldedTabs": true,
    "autoFoldTabs": true,
    "autoFoldTabsExcept": 2,
    "autoExpandTabs": true,
    "rmChildTabs": "folded",
    "tabsChildCount": true,
    "tabsLvlDots": true,
    "discardFolded": false,
    "discardFoldedDelay": 0,
    "discardFoldedDelayUnit": "sec",
    "tabsTreeBookmarks": true,
    "bookmarksPanel": true,
    "warnOnMultiBookmarkDelete": "collapsed",
    "openBookmarkNewTab": false,
    "midClickBookmark": "open_new_tab",
    "actMidClickTab": false,
    "autoCloseBookmarks": false,
    "autoRemoveOther": false,
    "highlightOpenBookmarks": true,
    "activateOpenBookmarkTab": false,
    "showBookmarkLen": true,
    "bookmarksRmUndoNote": true,
    "fontSize": "m",
    "bgNoise": true,
    "animations": true,
    "animationSpeed": "fast",
    "theme": "default",
    "style": "auto",
    "sidebarCSS": true,
    "groupCSS": false,
    "snapNotify": true,
    "snapExcludePrivate": false,
    "snapInterval": 180,
    "snapIntervalUnit": "min",
    "snapLimit": 14,
    "snapLimitUnit": "day",
    "hScrollThroughPanels": false,
    "scrollThroughTabs": "none",
    "scrollThroughVisibleTabs": false,
    "scrollThroughTabsSkipDiscarded": false,
    "scrollThroughTabsExceptOverflow": true,
    "scrollThroughTabsCyclic": false,
    "tabDoubleClick": "reload",
    "tabLongLeftClick": "none",
    "tabLongRightClick": "none",
    "tabsPanelLeftClickAction": "none",
    "tabsPanelDoubleClickAction": "tab",
    "tabsPanelRightClickAction": "menu",
    "tabsPanelMiddleClickAction": "undo",
    "syncName": "DeeperThought",
    "syncSaveSettings": true,
    "syncSaveCtxMenu": true,
    "syncSaveStyles": true,
    "syncAutoApply": false
  },
  "permissions": {
    "allUrls": true,
    "tabHide": true,
    "actualAllUrls": true,
    "actualTabHide": true
  },
  "storage": {
    "size": "10.4 mb",
    "props": {
      "bookmarksMenu": "226 b",
      "bookmarksPanelMenu": "54 b",
      "containers_v4": "524 b",
      "disabledKeybindings": "24 b",
      "expandedBookmarks": "2 b",
      "favAutoCleanTime": "10 b",
      "favUrls": "76.4 kb",
      "favicons": "1.1 mb",
      "lastSnapTime": "13 b",
      "panelIndex": "1 b",
      "panels_v4": "1.4 kb",
      "prevTabsData_v4": "84.4 kb",
      "profileID": "14 b",
      "settings": "2.5 kb",
      "sidebarCSS": "7.7 kb",
      "snapshots_v4": "8.9 mb",
      "tabsData_v4": "102.6 kb",
      "tabsMenu": "369 b",
      "tabsPanelMenu": "97 b"
    }
  },
  "panels": [
    {
      "type": "bookmarks",
      "id": "bookmarks",
      "cookieStoreId": "bookmarks",
      "name": 9,
      "icon": "...",
      "bookmarks": true,
      "lockedPanel": false
    },
    {
      "type": "default",
      "id": "firefox-default",
      "name": 7,
      "icon": "...",
      "cookieStoreId": "firefox-default",
      "lockedTabs": false,
      "lockedPanel": false,
      "noEmpty": false,
      "newTabCtx": "none",
      "moveTabCtx": "none",
      "moveTabCtxNoChild": true
    },
    {
      "type": "tabs",
      "id": "Qf9vV8t_uFI9",
      "name": 7,
      "icon": "...",
      "color": "...",
      "customIconSrc": "",
      "customIcon": "",
      "lockedTabs": false,
      "lockedPanel": false,
      "noEmpty": false,
      "newTabCtx": "none",
      "moveTabCtx": "none",
      "moveTabCtxNoChild": true,
      "urlRulesActive": false,
      "urlRules": ""
    },
    {
      "type": "tabs",
      "id": "fiTbDpS9AQyX",
      "name": 9,
      "icon": "...",
      "color": "...",
      "customIconSrc": "",
      "customIcon": "",
      "lockedTabs": false,
      "lockedPanel": false,
      "noEmpty": false,
      "newTabCtx": "firefox-container-4",
      "moveTabCtx": "none",
      "moveTabCtxNoChild": true,
      "urlRulesActive": false,
      "urlRules": ""
    },
    {
      "type": "tabs",
      "id": "vrjq0zPV5Rdv",
      "name": 6,
      "icon": "...",
      "color": "...",
      "customIconSrc": "",
      "customIcon": "",
      "lockedTabs": false,
      "lockedPanel": false,
      "noEmpty": false,
      "newTabCtx": "firefox-container-8",
      "moveTabCtx": "none",
      "moveTabCtxNoChild": true,
      "urlRulesActive": false,
      "urlRules": ""
    },
    {
      "type": "tabs",
      "id": "pwR4YO0Boiow",
      "name": 17,
      "icon": "...",
      "color": "...",
      "customIconSrc": "",
      "customIcon": "",
      "lockedTabs": false,
      "lockedPanel": false,
      "noEmpty": false,
      "newTabCtx": "none",
      "moveTabCtx": "none",
      "moveTabCtxNoChild": true,
      "urlRulesActive": false,
      "urlRules": ""
    }
  ],
  "cssVars": "TypeError: can't convert undefined to object",
  "sidebarCSSLen": 7598,
  "windows": [
    {
      "state": "maximized",
      "incognito": false,
      "tabsCount": 720
    },
    {
      "state": "normal",
      "incognito": false,
      "tabsCount": 1
    }
  ],
  "tabsMenu": [
    [
      "reload",
      "discard",
      "mute"
    ],
    "separator-1",
    [
      {
        "name": ""
      },
      "moveToWin",
      "moveToNewWin",
      "moveToPanel"
    ],
    "separator-3795259787627495",
    [
      {
        "name": ""
      },
      "pin",
      "group",
      "flatten"
    ],
    "separator-23946656137316935",
    [
      {
        "name": ""
      },
      "duplicate",
      "reopenInWin",
      "reopenInNewWin",
      "separator-36995635286684236",
      "reopenInCtr"
    ],
    "separator-2391613243580316",
    [
      {
        "name": ""
      },
      "bookmark",
      "copyUrls",
      "close"
    ]
  ],
  "bookmarksMenu": [
    [
      {
        "name": "Open in"
      },
      "openInNewWin",
      "openInNewPrivWin",
      "openInCtr"
    ],
    "separator-5",
    "createBookmark",
    "createFolder",
    "createSeparator",
    "separator-6",
    "sortByName",
    "sortByLink",
    "sortByTime",
    "separator-7",
    "copyUrls",
    "edit",
    "delete"
  ],
  "bookmarks": {
    "bookmarksCount": 4526,
    "foldersCount": 326,
    "separatorsCount": 0,
    "maxDepth": 8
  }
}</code></details>

**Comment by mbnuqw** [comment]
Fixed in v4.9.0
