### ISSUE TITLE
Switch panels when moving active tab to new panel

### ISSUE THREAD

**Issue by nearcatch** [mbnuqw/sidebery#212]
As title. When I use the tab context menu to send the active tab to a different panel, please switch the active panel to the new panel.

**Comment by mbnuqw** [comment]
Yep, it makes sense.

**Comment by mbnuqw** [comment]
Fixed in v4.9.0

**Comment by azkore** [comment]
Could it be configurable, please? I prefer the previous behaviour, it was much easier to sort large number of tabs between panels without constant switching between them.

**Comment by mbnuqw** [comment]
@azkore, sure

**Comment by azkore** [comment]
Great, thanks! Should I create a new issue/feature request for that?

**Comment by mbnuqw** [comment]
@azkore, no need for that. I already add task in my local task manager so this will be added in the next version (since it's quite simple to implement)

**Comment by azkore** [comment]
@mbnuqw May I ask if such an option exists now? I can't seem to find it in settings after updating to the latest version
