### ISSUE TITLE
Changing tab height

### ISSUE THREAD

**Issue by nadomodan** [mbnuqw/sidebery#216]
I wanted to change tab height so more can fit without scrolling so I added:
```
.Tab {
  height: 20px;
}
```
to sidebar css.
This doesn't work completely though as dragging tabs around to reorder them still uses the old tab height (the arrow with line marker jumps in bigger steps than tab height in css and lands between tabs). How to properly change tab height if it's possible currently?

**Comment by mbnuqw** [comment]
To change tab height you need to use css var using the special input field in the left side in the styles editor:
![screenshot-2020-05-03 20:36:14_001](https://user-images.githubusercontent.com/6276694/80918338-d0b25d00-8d7d-11ea-8de4-57b5a1f8ab52.png)

...or using the next CSS:
```css
#root {
  --tabs-height: 20px;
}
```
