### ISSUE TITLE
Close button on all tabs

### ISSUE THREAD

**Issue by gsbabil** [mbnuqw/sidebery#217]
Thanks for the wonderful addon.

Would it be possible to add an option to toggle visibility of the close button on all tabs i.e. _"Show close button on all tabs"_? The unfocused or discarded tabs may have their close buttons dimmed accordingly.

Currently, we have _"Show close button on mouse hover"_ , and visibility on hover can be turned off in settings pane. A similar on/off toggle option for all tabs would be great.

Thanks a lot.

**Comment by mbnuqw** [comment]
I think I can replace the "Show close button on mouse hover" toggle with selector "Show close button" and add next options to it: always | hover | none

**Comment by gsbabil** [comment]
Hi @mbnuqw,

> I think I can replace the "Show close button on mouse hover" toggle with selector "Show close button" and add next options to it: always | hover | none

This will be great. Thanks a lot!

**Comment by mbnuqw** [comment]
Resolved in v5.0.0
