### ISSUE TITLE
Discard does not do anything

### ISSUE THREAD

**Issue by mwoffenden** [mbnuqw/sidebery#22]
Discard does not do anything

> OS: mac x86-64  
> Firefox: 66.0.2  
> Extension: 2.2.2

**Comment by mbnuqw** [comment]
Do you try to discard active tab? If so, this is not possible by design.

**Comment by mwoffenden** [comment]
Then what is the purpose/use of Discard?

**Comment by mbnuqw** [comment]
You can discard only inactive tab[s] to free some memory.  But Firefox cannot unload currently opened/rendered page. So if you for example select all tabs and discard them, Firefox will leave current tab untouched.

**Comment by mbnuqw** [comment]
I've disabled this option for active tab in v2.3.0, so I close this issue.
