### ISSUE TITLE
Documentation ideas

### ISSUE THREAD

**Issue by denemier** [mbnuqw/sidebery#221]
Too complicated things for me in the first glance
1-no idea what container is, and difference between panel and container
2-didnt understand snapshot first it seems like auto saving feature so we dont have to do it manuelly system takes care for it self, other extensions have manuel export option but sideberry is doing that automatically? i think (i havent tried it fully)
3-no idea what the difference between session and global storage is, global storage maybe safer? where is it stored? Can extensions have own database maybe, because normal people don't know this normally. And where are snapshots stored? Can they get deleted with browser closing, do we still need to take sometimes manuel exports.

**Comment by mbnuqw** [comment]
Yes, sorry, the lack of documentation is one of the biggest problems of this project, which I need to fix.

1. Container is the Firefox feature that isolate your tabs (their cookies, localStorages). e.g. you can open multiple accounts of the same site.
Panels is the way to visually organize the tabs list/tree.

2. Snapshots stores the open tabs, panels and containers configs, and allows you to restore previous state. You can setup auto snapshots by providing the interval and limit.

3. The "Global storage" option means that tabs data (tree structure and tabs position in panels) will be stored in the storage of this addon and will be kept until the addon will be removed. The same storage type used for the snapshots.

I'll update wiki a bit later.

**Comment by denemier** [comment]
hımm thanks, the container idea looks interesting now...
