### ISSUE TITLE
changing discard title for misunderstanding?

### ISSUE THREAD

**Issue by denemier** [mbnuqw/sidebery#222]
Discard Tabs label feels like deleting tab, maybe change it to sleep/freeze tabs

**Comment by MartinGraive** [comment]
"Discard" is the dedicated term (https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/discard).

**Comment by mbnuqw** [comment]
I used title from the API docs (as @MartinGraive pointed). If it sounds wrong (I'm not a native speaker), how about "Unload tab"? - at least, it more accurate describes the target action. Oh, and I'll need (maybe) change the icon.
![screenshot-2020-05-10 23:11:48](https://user-images.githubusercontent.com/6276694/81507016-ab8c9400-9313-11ea-94f5-3b28c80e6df0.png)

**Comment by denemier** [comment]
unload tabs sounds good, by the way i liked the icon for unloading looks good to me it's classical.

But you can maybe change the mute sound icon into something like youtube players sound level icon in the future.
By the way where are you from? Greetings from turkey

**Comment by mlissner** [comment]
FWIW, I came here to file a similar bug, but I was convinced that "Discard" meant "Close" since there's no option in the menu to do that. I would have never clicked on discard had I not come to this bug and learned otherwise. 

I agree that changing it to "Unload" would be better. Neat feature!

**Comment by mbnuqw** [comment]
Fixed in v4.9.0
