### ISSUE TITLE
undo close tab feature doesnt work for me

### ISSUE THREAD

**Issue by denemier** [mbnuqw/sidebery#223]
If I close a tab but can't bring it back

**Comment by mbnuqw** [comment]
Hm... works as intended for me. Only the closed new tabs (about:newtab) not reopening, but this is a standard behavior.

Could you write your debug info (from the settings page / Help section) and if possible list of used addons (maybe there is some conflict)?

**Comment by denemier** [comment]
yeah it think as you sad its about:newtab problem, probably i have tested with newtab, normal tabs working correctly...
