### ISSUE TITLE
"Move tabs with matched URLs" not supported in default panel

### ISSUE THREAD

**Issue by MartinGraive** [mbnuqw/sidebery#225]
Hi, 
Is there a reason for the option to automatically move tabs matching a certain URL not to be available in the default panel?
Thank you

**Comment by mbnuqw** [comment]
Right now, there are, indeed, no reason to not to include this option. Its just the legacy from the v3 :) and I plan to add other configurable options to default panel including this one.

**Comment by mbnuqw** [comment]
Closing this as implemented
