### ISSUE TITLE
Rename bookmark folder when bookmarking tab tree or group

### ISSUE THREAD

**Issue by orzechow** [mbnuqw/sidebery#226]
## Description

First of all, thanks again for the feature to bookmark tab trees #36 :)

Right now, if I bookmark a tab tree, the new bookmark folder will be named as the root folder:

![Selection_097](https://user-images.githubusercontent.com/5220714/81268641-bd321b00-9037-11ea-898a-d9083b212332.png) ![Selection_098](https://user-images.githubusercontent.com/5220714/81268653-c02d0b80-9037-11ea-9520-628580ca48c1.png) ![Selection_102](https://user-images.githubusercontent.com/5220714/81268924-1dc15800-9038-11ea-96ad-4f4fb2d02b4b.png) ![Selection_100](https://user-images.githubusercontent.com/5220714/81268699-cb803700-9037-11ea-95e4-68ae98b1a7bc.png)

I'd like to see e.g. a dialog popping up that asks me for a name of this new folder instead (optional via settings of course), such that I can rename it while bookmarking.

**Comment by kamizoli** [comment]
I second this and only today asked for the same. Like the Firefox Dialog, which opens when bookarking tabs from the tab bar.

**Comment by kittydoor** [comment]
I have this issue with bookmarking entire panels. I haven't yet figured out how to effectively use panels, so I just use the default panel with multiple windows as my workflow, and this means when I try to bookmark a panel it appends to the same "Default" folder automatically. This makes the feature completely useless for me.

Is there perhaps a workaround for this that I'm missing? Or do I need to wait for this issue to be resolved for functionality?

**Comment by mbnuqw** [comment]
Available from v5.0.0

**Comment by kittydoor** [comment]
I believe that a further release than v5.0.0 was required for my issue to be solved, but I tested it now and it works exactly as mentioned in this issue! Thank you @mbnuqw for all the hard work :)

**Comment by orzechow** [comment]
Strange, I'm running v5.1.1, but don't see the option:

<img width="45%" src="https://github.com/mbnuqw/sidebery/assets/5220714/628f6af8-ce8b-4166-a082-04f38bcb9f22"/> <img width="45%" src="https://github.com/mbnuqw/sidebery/assets/5220714/33266a7c-5ea0-4f88-9c9a-81d1a4d07edd"/>


When clicking into the free space and saving all bookmarks, a dialog with bookmark folder name appears:
<img width="45%" src="https://github.com/mbnuqw/sidebery/assets/5220714/74296e0f-6c1b-421c-ab2f-1bcb277426f8"/> <img width="45%" src="https://github.com/mbnuqw/sidebery/assets/5220714/f0a0ed09-1ff3-41d7-ab8e-6063a14e2038"/>

This would be nice to have for the upper approach as well.

**Comment by mbnuqw** [comment]
@orzechow, please, open a new feature request, so I can track it.

**Comment by mbnuqw** [comment]
Got it, my mistake. Strange that I marked it as "resolved in beta"...

**Comment by orzechow** [comment]
No worries. Thanks for looking into this at all :)
