### ISSUE TITLE
Customize styles of pinned-tabs dock

### ISSUE THREAD

**Issue by mwoffenden** [mbnuqw/sidebery#23]
I cannot see which tabs are pinned, in dark mode.  I think there is a divider but it's not very visible.  Maybe offer a way to customize the divider color?

**Comment by mbnuqw** [comment]
Hm, this is nice idea! I'll add this feature.

**Comment by mbnuqw** [comment]
I've added ability to change background color overlay and shadows which can be used as borders:

![screenshot-2019 04 03-13 20 27_001](https://user-images.githubusercontent.com/6276694/55463890-6592d600-5613-11e9-81b8-e2b865d13354.png)

**Comment by mwoffenden** [comment]
Looks great.  Has this been released yet?

**Comment by mbnuqw** [comment]
It'll be released with v2.4.0, but... I don't know when exactly this happen ;)
Optimistically, this weekend.

**Comment by mbnuqw** [comment]
Landed in 2.4.0

**Comment by felixsanz** [comment]
@mbnuqw this was removed in 5.0. background can't be changed anymore. can you re-add it please?
