### ISSUE TITLE
Impossible to close TABS, Or Are Reloading Again, Why?

### ISSUE THREAD

**Issue by denemier** [mbnuqw/sidebery#230]
## Steps to reproduce
if click close a tab it doesnt close some tabs and when i close it from firefox's normal intenal top tabs it closes but than it is opening same tab again impossible to close.
what is causing that

**Comment by mbnuqw** [comment]
It can be the "Prevent closing tabs on this panel" option in the panel config. If not, please, provide debug info (Sidebery settings / Help / Show debug info).

**Comment by denemier** [comment]
Yeh that worked, i closed that option...
