### ISSUE TITLE
Dynamic sidebar as described in README does not work

### ISSUE THREAD

**Issue by penyuan** [mbnuqw/sidebery#240]
## Steps to reproduce

1. Use Firefox version 76.0.1 on Linux (kernel 4.18)
2. Install Sidebury 4.8.0
3. Follow instructions in this Github repository's README for dynamic sidebar, i.e.:
4. Set navigation button width to 30px (Settings/Styles/Navigation Strip) and Set width of pinned tabs to 30px (Settings/Styles/Sidebar css): ![](https://framapic.org/6ZGPKRYCwe20/XiBfCvtLybpo)
5. Copy and paste CSS in README into Firefox profile's `userChrome.css`

My complete `userChrome.css` is as follows:

```
@namespace url("http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul");

/* Hide tab strip */
#TabsToolbar {
    visibility: collapse !important;
}

#sidebar-header {
  display: none;
}
#sidebar-splitter {
  width: 0 !important;
}
#main-window #appcontent {
  margin-left: 30px
}
#main-window #sidebar-box {
  position: fixed;
  display: block;
  min-width: 0px !important;
  max-width: none !important;
  width: 30px !important;
  height: calc(100% - 61px); /* 61px - height of #navigator-toolbox */
  overflow: hidden;
  box-shadow: 0 0 8px 0 #00000064, 1px 0 0 0 #212121;
  transition: all 0.12s;
}
#main-window #sidebar {
  position: absolute;
  min-width: 0px !important;
  max-width: none !important;
  left: 0;
  top: 0;
  right: auto;
  bottom: auto;
  width: 30px;
  height: 100%;
}

/* Completely (almost) hide in fullscreen */
#main-window[inFullscreen] #appcontent {
  margin-left: 1px
}
#main-window[inFullscreen] #sidebar-box,
#main-window[inFullscreen] #sidebar {
  width: 1px !important;
}

/* Show on hover */
#main-window #sidebar-box:hover,
#main-window[inFullscreen] #sidebar-box:hover,
#main-window #sidebar-box:hover #sidebar,
#main-window[inFullscreen] #sidebar-box:hover #sidebar {
  height: 100% !important;
  width: 250px !important;
}
#main-window #sidebar-box:hover #sidebar:before {
  transform: translateX(-100%);
}
```

## Expected behavior

Sidebury sidebar to be hidden/retracted into a thin vertical strip on the left side of Firefox window **until** mouse cursor hovers over it to expand it.

## Actual behavior

The Sidebury sidebar is always expanded, and never retracted to the left.

## Environment info

OS: Linux (kernel 4.18 with Gnome 3.32.2)
Firefox version: 76.0.1
Addon version: 4.8.0

<details><code>
{
  "settings": {
    "version": "4.8.0",
    "nativeScrollbars": true,
    "selWinScreenshots": true,
    "tabsCheck": true,
    "tabsFix": "notify",
    "ctxMenuNative": false,
    "autoHideCtxMenu": "none",
    "ctxMenuRenderInact": true,
    "navBarLayout": "horizontal",
    "navBarInline": false,
    "hideAddBtn": true,
    "hideSettingsBtn": false,
    "navBtnCount": true,
    "hideEmptyPanels": true,
    "navMidClickAction": "none",
    "navSwitchPanelsWheel": true,
    "groupLayout": "grid",
    "dndTabAct": true,
    "dndTabActDelay": 750,
    "dndTabActMod": "none",
    "dndExp": "pointer",
    "dndExpDelay": 0,
    "dndExpMod": "none",
    "stateStorage": "global",
    "warnOnMultiTabClose": "collapsed",
    "activateOnMouseUp": true,
    "activateLastTabOnPanelSwitching": true,
    "skipEmptyPanels": false,
    "showTabRmBtn": true,
    "showTabCtx": true,
    "hideInact": false,
    "activateAfterClosing": "next",
    "activateAfterClosingPrevRule": "visible",
    "activateAfterClosingNextRule": "tree",
    "activateAfterClosingGlobal": false,
    "activateAfterClosingNoFolded": false,
    "activateAfterClosingNoDiscarded": false,
    "shiftSelAct": true,
    "askNewBookmarkPlace": false,
    "tabsRmUndoNote": true,
    "nativeHighlight": false,
    "tabsUnreadMark": false,
    "tabsReloadLimit": 5,
    "moveNewTabPin": "start",
    "moveNewTabParent": "last_child",
    "moveNewTabParentActPanel": false,
    "moveNewTab": "end",
    "pinnedTabsPosition": "panel",
    "pinnedTabsList": false,
    "pinnedAutoGroup": true,
    "tabsTree": true,
    "groupOnOpen": true,
    "tabsTreeLimit": "none",
    "hideFoldedTabs": false,
    "autoFoldTabs": false,
    "autoFoldTabsExcept": "none",
    "autoExpandTabs": false,
    "rmChildTabs": "none",
    "tabsChildCount": true,
    "tabsLvlDots": false,
    "discardFolded": false,
    "discardFoldedDelay": 0,
    "discardFoldedDelayUnit": "sec",
    "tabsTreeBookmarks": true,
    "bookmarksPanel": true,
    "warnOnMultiBookmarkDelete": "collapsed",
    "openBookmarkNewTab": false,
    "midClickBookmark": "open_new_tab",
    "actMidClickTab": false,
    "autoCloseBookmarks": false,
    "autoRemoveOther": false,
    "highlightOpenBookmarks": false,
    "activateOpenBookmarkTab": false,
    "showBookmarkLen": false,
    "bookmarksRmUndoNote": true,
    "fontSize": "xs",
    "bgNoise": true,
    "animations": true,
    "animationSpeed": "fast",
    "theme": "default",
    "style": "auto",
    "sidebarCSS": true,
    "groupCSS": false,
    "snapNotify": true,
    "snapExcludePrivate": false,
    "snapInterval": 0,
    "snapIntervalUnit": "min",
    "snapLimit": 0,
    "snapLimitUnit": "snap",
    "hScrollThroughPanels": false,
    "scrollThroughTabs": "none",
    "scrollThroughVisibleTabs": false,
    "scrollThroughTabsSkipDiscarded": false,
    "scrollThroughTabsExceptOverflow": true,
    "scrollThroughTabsCyclic": false,
    "tabDoubleClick": "none",
    "tabLongLeftClick": "none",
    "tabLongRightClick": "none",
    "tabsPanelLeftClickAction": "none",
    "tabsPanelDoubleClickAction": "tab",
    "tabsPanelRightClickAction": "menu",
    "tabsPanelMiddleClickAction": "tab",
    "syncName": "",
    "syncSaveSettings": false,
    "syncSaveCtxMenu": false,
    "syncSaveStyles": false,
    "syncAutoApply": false
  },
  "permissions": {
    "allUrls": false,
    "tabHide": false,
    "actualAllUrls": false,
    "actualTabHide": false
  },
  "storage": {
    "size": "231.6 kb",
    "props": {
      "containers_v4": "1.5 kb",
      "cssVars": "1.6 kb",
      "favAutoCleanTime": "10 b",
      "favUrls": "4.2 kb",
      "favicons": "209.5 kb",
      "panelIndex": "1 b",
      "panels_v4": "378 b",
      "prevTabsData_v4": "5.5 kb",
      "profileID": "14 b",
      "settings": "2.5 kb",
      "sidebarCSS": "33 b",
      "tabsData_v4": "5.8 kb"
    }
  },
  "panels": [
    {
      "type": "bookmarks",
      "id": "bookmarks",
      "cookieStoreId": "bookmarks",
      "name": 9,
      "icon": "...",
      "bookmarks": true,
      "lockedPanel": false
    },
    {
      "type": "default",
      "id": "firefox-default",
      "name": 7,
      "icon": "...",
      "cookieStoreId": "firefox-default",
      "lockedTabs": false,
      "lockedPanel": false,
      "noEmpty": false,
      "newTabCtx": "none",
      "moveTabCtx": "none",
      "moveTabCtxNoChild": true
    }
  ],
  "cssVars": {
    "nav_btn_width": "30px"
  },
  "sidebarCSSLen": 29,
  "windows": [
    {
      "state": "maximized",
      "incognito": false,
      "tabsCount": 60
    }
  ],
  "bookmarks": {
    "bookmarksCount": 3812,
    "foldersCount": 365,
    "separatorsCount": 0,
    "maxDepth": 7
  }
}
</code></details>

**Comment by klaa97** [comment]
I have the same issue.

## Environment info
OS: linux
Firefox: 76.0
Addon: 4.8.0

<details><code>
{
  "settings": {
    "version": "4.8.0",
    "nativeScrollbars": true,
    "selWinScreenshots": true,
    "tabsCheck": true,
    "tabsFix": "notify",
    "ctxMenuNative": true,
    "autoHideCtxMenu": 1000,
    "ctxMenuRenderInact": true,
    "navBarLayout": "horizontal",
    "navBarInline": false,
    "hideAddBtn": false,
    "hideSettingsBtn": true,
    "navBtnCount": false,
    "hideEmptyPanels": true,
    "navMidClickAction": "none",
    "navSwitchPanelsWheel": true,
    "groupLayout": "grid",
    "dndTabAct": true,
    "dndTabActDelay": 750,
    "dndTabActMod": "none",
    "dndExp": "pointer",
    "dndExpDelay": 0,
    "dndExpMod": "none",
    "stateStorage": "global",
    "warnOnMultiTabClose": "collapsed",
    "activateOnMouseUp": true,
    "activateLastTabOnPanelSwitching": true,
    "skipEmptyPanels": false,
    "showTabRmBtn": true,
    "showTabCtx": true,
    "hideInact": false,
    "activateAfterClosing": "next",
    "activateAfterClosingPrevRule": "visible",
    "activateAfterClosingNextRule": "tree",
    "activateAfterClosingGlobal": false,
    "activateAfterClosingNoFolded": false,
    "activateAfterClosingNoDiscarded": false,
    "shiftSelAct": true,
    "askNewBookmarkPlace": false,
    "tabsRmUndoNote": true,
    "nativeHighlight": false,
    "tabsUnreadMark": false,
    "tabsReloadLimit": 5,
    "moveNewTabPin": "start",
    "moveNewTabParent": "last_child",
    "moveNewTabParentActPanel": false,
    "moveNewTab": "end",
    "pinnedTabsPosition": "panel",
    "pinnedTabsList": false,
    "pinnedAutoGroup": true,
    "tabsTree": true,
    "groupOnOpen": true,
    "tabsTreeLimit": "none",
    "hideFoldedTabs": false,
    "autoFoldTabs": true,
    "autoFoldTabsExcept": "none",
    "autoExpandTabs": false,
    "rmChildTabs": "all",
    "tabsChildCount": true,
    "tabsLvlDots": true,
    "discardFolded": false,
    "discardFoldedDelay": 0,
    "discardFoldedDelayUnit": "sec",
    "tabsTreeBookmarks": true,
    "bookmarksPanel": true,
    "warnOnMultiBookmarkDelete": "collapsed",
    "openBookmarkNewTab": false,
    "midClickBookmark": "open_new_tab",
    "actMidClickTab": false,
    "autoCloseBookmarks": false,
    "autoRemoveOther": false,
    "highlightOpenBookmarks": false,
    "activateOpenBookmarkTab": false,
    "showBookmarkLen": false,
    "bookmarksRmUndoNote": true,
    "fontSize": "m",
    "bgNoise": true,
    "animations": false,
    "animationSpeed": "fast",
    "theme": "default",
    "style": "dark",
    "sidebarCSS": true,
    "groupCSS": false,
    "snapNotify": true,
    "snapExcludePrivate": false,
    "snapInterval": 0,
    "snapIntervalUnit": "min",
    "snapLimit": 0,
    "snapLimitUnit": "snap",
    "hScrollThroughPanels": false,
    "scrollThroughTabs": "none",
    "scrollThroughVisibleTabs": false,
    "scrollThroughTabsSkipDiscarded": false,
    "scrollThroughTabsExceptOverflow": true,
    "scrollThroughTabsCyclic": false,
    "tabDoubleClick": "none",
    "tabLongLeftClick": "none",
    "tabLongRightClick": "none",
    "tabsPanelLeftClickAction": "none",
    "tabsPanelDoubleClickAction": "tab",
    "tabsPanelRightClickAction": "menu",
    "tabsPanelMiddleClickAction": "tab",
    "syncName": "",
    "syncSaveSettings": false,
    "syncSaveCtxMenu": false,
    "syncSaveStyles": false,
    "syncAutoApply": false
  },
  "permissions": {
    "allUrls": true,
    "tabHide": true,
    "actualAllUrls": true,
    "actualTabHide": true
  },
  "storage": {
    "size": "826.6 kb",
    "props": {
      "cssVars": "1.6 kb",
      "disabledKeybindings": "94 b",
      "favAutoCleanTime": "10 b",
      "favUrls": "39.8 kb",
      "favicons": "779.6 kb",
      "panelIndex": "1 b",
      "panels_v4": "378 b",
      "prevTabsData_v4": "1.5 kb",
      "profileID": "14 b",
      "settings": "2.5 kb",
      "sidebarCSS": "33 b",
      "tabsData_v4": "676 b"
    }
  },
  "panels": [
    {
      "type": "bookmarks",
      "id": "bookmarks",
      "cookieStoreId": "bookmarks",
      "name": 9,
      "icon": "...",
      "bookmarks": true,
      "lockedPanel": false
    },
    {
      "type": "default",
      "id": "firefox-default",
      "name": 7,
      "icon": "...",
      "cookieStoreId": "firefox-default",
      "lockedTabs": false,
      "lockedPanel": false,
      "noEmpty": false,
      "newTabCtx": "none",
      "moveTabCtx": "none",
      "moveTabCtxNoChild": true
    }
  ],
  "cssVars": {
    "nav_btn_width": "30px"
  },
  "sidebarCSSLen": 29,
  "windows": [
    {
      "state": "normal",
      "incognito": false,
      "tabsCount": 10
    }
  ],
  "bookmarks": {
    "bookmarksCount": 652,
    "foldersCount": 53,
    "separatorsCount": 2,
    "maxDepth": 4
  }
}
</code></details>

**Comment by klaa97** [comment]
Here a fix that is working on my machine; code is partly taken from TreeStyleTabs. Try to add it to your CSS maybe and let me know @penyuan if it works!

I'm unfortunately not very skilled in Firefox CSS shenigans, so I don't really know how to make those options specific to Sidebery sidebar, so it will be applied to all the other sidebars too (that should have been the default behaviour of the stuff in the README too anyway).

```
/* Sidebar min and max width removal */
#sidebar {
    max-width: none !important;
    min-width: 0px !important;
}
/* Hide splitter 
#sidebar-splitter {
    display: none !important;
}
/* Hide sidebar header
#sidebar-header {
    visibility: collapse;
}

/* Shrink sidebar until hovered */
:root {
    --thin-tab-width: 30px;
    --wide-tab-width: 200px;
}

#sidebar-box {
    position: relative !important;
    transition: all 100ms !important;
    min-width: var(--thin-tab-width) !important;
    max-width: var(--thin-tab-width) !important;
}
#sidebar-box:hover {
    transition: all 200ms !important;
    min-width: var(--wide-tab-width) !important;
    max-width: var(--wide-tab-width) !important;
    margin-right: calc((var(--wide-tab-width) - var(--thin-tab-width)) * -1) !important;
    z-index: 1;
}
```

For completion, here my full .css
<detail>
```
@namespace html url("http://www.w3.org/1999/xhtml");
browser[blank], browser[pendingpaint] {
        opacity: 1 !important;
}

#TabsToolbar { visibility: collapse !important; } /* Hide Firefox's default tab bar. */

#sidebar-header {
  display: none;
}

#sidebar-splitter {
  width: 0 !important;
}

/* Hide main tabs toolbar */
#main-window[tabsintitlebar="true"]:not([extradragspace="true"]) #TabsToolbar > .toolbar-items {
    opacity: 0;
    pointer-events: none;
}
#main-window:not([tabsintitlebar="true"]) #TabsToolbar {
    visibility: collapse !important;
}

/* Sidebar min and max width removal */
#sidebar {
    max-width: none !important;
    min-width: 0px !important;
}
/* Hide splitter 
#sidebar-splitter {
    display: none !important;
}
/* Hide sidebar header
#sidebar-header {
    visibility: collapse;
}

/* Shrink sidebar until hovered */
:root {
    --thin-tab-width: 30px;
    --wide-tab-width: 200px;
}

#sidebar-box {
    position: relative !important;
    transition: all 100ms !important;
    min-width: var(--thin-tab-width) !important;
    max-width: var(--thin-tab-width) !important;
}
#sidebar-box:hover {
    transition: all 200ms !important;
    min-width: var(--wide-tab-width) !important;
    max-width: var(--wide-tab-width) !important;
    margin-right: calc((var(--wide-tab-width) - var(--thin-tab-width)) * -1) !important;
    z-index: 1;
}
```
</detail>

**Comment by penyuan** [comment]
Thank you @klaa97! I tried what you suggested but it didn't change anything for me... :(

Here's my complete `userChrome.css` after applying your suggestions:

```
@namespace url("http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul");

/* Hide tab strip */
#TabsToolbar {
  visibility: collapse !important;
}

/* Sidebar min and max width removal */
#sidebar {
  max-width: none !important;
  min-width: 0px !important;
}

/* Hide splitter */
#sidebar-splitter {
  display: none !important;
}

/* Hide sidebar header */
#sidebar-header {
  visibility: collapse;
}

/* Shrink sidebar until hovered */
:root {
  --thin-tab-width: 30px;
  --wide-tab-width: 200px;
}

#sidebar-box {
  position: relative !important;
  transition: all 100ms !important;
  min-width: var(--thin-tab-width) !important;
  max-width: var(--thin-tab-width) !important;
}

#sidebar-box:hover {
  transition: all 200ms !important;
  min-width: var(--wide-tab-width) !important;
  max-width: var(--wide-tab-width) !important;
  margin-right: calc((var(--wide-tab-width) - var(--thin-tab-width)) * -1) !important;
  z-index: 1;
}
```

Any other ideas?

**Comment by klaa97** [comment]
@penyuan I'm really sorry but there was a typo in what I send you before. Here the stuff that should (actually (let's hope)) work, I'm having it right now and it works, but I caught the real problem here.
You have `@namespace url("http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul")` at the start of the .css, you need to remove it to make this work! It should be safe with no side-effects according to https://www.userchrome.org/adding-style-recipes-userchrome-css.html

```
#TabsToolbar { visibility: collapse !important; }

/* Hide Firefox's default tab bar. */
#sidebar-header {
  display: none;
}

#sidebar-splitter {
  width: 0 !important;
}

/* Hide main tabs toolbar */
#main-window[tabsintitlebar="true"]:not([extradragspace="true"]) #TabsToolbar > .toolbar-items {
    opacity: 0;
    pointer-events: none;
}
#main-window:not([tabsintitlebar="true"]) #TabsToolbar {
    visibility: collapse !important;
}

/* Sidebar min and max width removal */
#sidebar {
    max-width: none !important;
    min-width: 0px !important;
}
/* Hide splitter */
#sidebar-splitter {
    display: none !important;
}
/* Hide sidebar header */
#sidebar-header {
    visibility: collapse;
}

/* Shrink sidebar until hovered */
:root {
    --thin-tab-width: 30px;
    --wide-tab-width: 200px;
}

#sidebar-box {
    position: relative !important;
    transition: all 100ms !important;
    min-width: var(--thin-tab-width) !important;
    max-width: var(--thin-tab-width) !important;
}
#sidebar-box:hover {
    transition: all 200ms !important;
    min-width: var(--wide-tab-width) !important;
    max-width: var(--wide-tab-width) !important;
    margin-right: calc((var(--wide-tab-width) - var(--thin-tab-width)) * -1) !important;
    z-index: 1;
}
```

Also,

**Comment by penyuan** [comment]
Thank you @klaa97: Progress!!

After applying your latest suggestion, now the sidebar hides as intended!!! But there are a few caveats:

1. The top Sidebury panels bar (you know, the one with the Bookmarks, tab groups buttons, etc.) squishes from a horizontal into a vertical arrangement whenever the sidebar is in the retracted stated, pushing the rest of by tabs downward.

2. I've got a couple of pinned tabs and the same thing happens: When the sidebar retracts, the pinned tabs get squished from a horizontal into a vertical arrangement.

3. The sidebar's scroll bar doesn't appear! I have to turn ON "Use native scroll-bars" in Sidebury settings to make the scroll bar appear. However, this means the scroll bar would *cover* my tabs when the sidebar is retracted.

Sorry to bug you so much, but I don't suppose you have any idea why the above happens and how to fix them? Thanks for your help!

**Comment by klaa97** [comment]
No problem!! What I can say is:

1. I think that it is probably the correct behaviour; if you want you can adjust the `--thin-tab-width:` in the .css , or your solution is as good!
2. The pin tab is intended behaviour I think. What would you suggest as intended behaviour?? If you have more tabs, they get pushed down so you can still see them all. As before, I think the solution is alright.
3. That is a problem I just faced too! I have no idea how to fix it; I can't find a solution rn (it's a bit late here lol), but I'll update it here if I find something!

**Comment by penyuan** [comment]
Thanks @klaa97 it's a bit late for me, too. :smile:

1. OK.

2. So the CSS I reported in my original post worked fine in Firefox 68 ESR. The behaviour then was that the pinned tabs would remain in a horizontal alignment, so only the leftmost tab would be visible when the sidebar is retracted. In other words, the pinned tabs stay horizontal all the time. That said, I can live with my workaround for now.

3. This is probably the biggest annoyance for me because TBH I think the native scroll bar doesn't visually fit Sidebury's sidebar and appears a bit jarring.

But like you said it's late, so maybe we can revisit this tomorrow. :) Thank you for your help!

**Comment by penyuan** [comment]
Did some searching and there is another solution proposed in [this CSS posted on GitHub](https://github.com/Aris-t2/CustomCSSforFx/releases/tag/3.0.1).

Thank you everyone! Closing issue.

**Comment by kushraj** [comment]
@klaa97 thanks for your solution. Is there a way if we can trigger this behaviour only when firefox window aspect ratio is close to 1.
