### ISSUE TITLE
Different sponsoring options

### ISSUE THREAD

**Issue by Klohto** [mbnuqw/sidebery#242]
I would love to sponsor you regularly, but I'm unable to do that with PayPal.
On top of that, PP takes a huge fee from my card for no reason and charges fees for converting currency.

Is there a plan to use Github "native" funding or that is currently not possible?
Through which payment processors would you receive the most %?

**Comment by mbnuqw** [comment]
Thank you, unfortunately there is no other options for donation currently. Plus, I cannot guarantee the continuity of development (there may be pauses, such as recently). So if you feel uncomfortable with PayPal you can contribute to this project by creating a bug report / feature request or writing the review on the addon's page. I appreciate all of these kinds of feedback.
