### ISSUE TITLE
Close other tabs than than active

### ISSUE THREAD

**Issue by artgru** [mbnuqw/sidebery#243]
## Description
From an old plugin like TabMixPlus I really miss a feature: Close all tabs than currently selected.
Would it be possible to add this feature to the context menu?

**Comment by shvchk** [comment]
Isn't it already there, you can enable "Close other tabs" in Menu editor → Tabs settings section.

**Comment by artgru** [comment]
Yes, I found it recently ^^
Thing is for me it was disabled by default. So I came across on it only when I visited the settings in order to change something :)
Thanks!
