### ISSUE TITLE
Selecting from down up has a different behavior than beginning from the top

### ISSUE THREAD

**Issue by MartinGraive** [mbnuqw/sidebery#244]
## Steps to reproduce
- Open a new window
- Open four tabs
- Go on the first one and select the three other tabs starting with the bottom one (shift-click with shift_selection_from_active disabled or ctrl-click)
- Indent the three selected tabs with a keyboard shortcut

## Expected behavior
The three selected tabs should become children of the first one, as is the case when you select from the top or when you only select two tabs or when you drag and drop the selection.

## Actual behavior
Only the first two tabs do indent. Hitting the shortcut a second time does the trick.

## Environment info
OS: linux
Firefox: 76.0.1
Addon: 4.8.0

<details><code>
{
  "settings": {
    "version": "4.8.0",
    "nativeScrollbars": false,
    "selWinScreenshots": false,
    "tabsCheck": true,
    "tabsFix": "reinit",
    "ctxMenuNative": false,
    "autoHideCtxMenu": "none",
    "ctxMenuRenderInact": true,
    "navBarLayout": "horizontal",
    "navBarInline": false,
    "hideAddBtn": false,
    "hideSettingsBtn": true,
    "navBtnCount": true,
    "hideEmptyPanels": false,
    "navMidClickAction": "none",
    "navSwitchPanelsWheel": true,
    "groupLayout": "grid",
    "dndTabAct": false,
    "dndTabActDelay": 750,
    "dndTabActMod": "none",
    "dndExp": "none",
    "dndExpDelay": 10,
    "dndExpMod": "none",
    "stateStorage": "global",
    "warnOnMultiTabClose": "none",
    "activateOnMouseUp": true,
    "activateLastTabOnPanelSwitching": true,
    "skipEmptyPanels": false,
    "showTabRmBtn": true,
    "showTabCtx": true,
    "hideInact": true,
    "activateAfterClosing": "prev",
    "activateAfterClosingPrevRule": "visible",
    "activateAfterClosingNextRule": "tree",
    "activateAfterClosingGlobal": false,
    "activateAfterClosingNoFolded": false,
    "activateAfterClosingNoDiscarded": true,
    "shiftSelAct": false,
    "askNewBookmarkPlace": false,
    "tabsRmUndoNote": true,
    "nativeHighlight": false,
    "tabsUnreadMark": false,
    "tabsReloadLimit": 5,
    "moveNewTabPin": "none",
    "moveNewTabParent": "none",
    "moveNewTabParentActPanel": false,
    "moveNewTab": "after",
    "pinnedTabsPosition": "panel",
    "pinnedTabsList": false,
    "pinnedAutoGroup": true,
    "tabsTree": true,
    "groupOnOpen": true,
    "tabsTreeLimit": 4,
    "hideFoldedTabs": false,
    "autoFoldTabs": false,
    "autoFoldTabsExcept": "none",
    "autoExpandTabs": false,
    "rmChildTabs": "folded",
    "tabsChildCount": true,
    "tabsLvlDots": true,
    "discardFolded": true,
    "discardFoldedDelay": 1,
    "discardFoldedDelayUnit": "min",
    "tabsTreeBookmarks": true,
    "bookmarksPanel": true,
    "warnOnMultiBookmarkDelete": "collapsed",
    "openBookmarkNewTab": false,
    "midClickBookmark": "open_new_tab",
    "actMidClickTab": true,
    "autoCloseBookmarks": false,
    "autoRemoveOther": false,
    "highlightOpenBookmarks": true,
    "activateOpenBookmarkTab": true,
    "showBookmarkLen": true,
    "bookmarksRmUndoNote": true,
    "fontSize": "xxs",
    "bgNoise": false,
    "animations": false,
    "animationSpeed": "fast",
    "theme": "default",
    "style": "dark",
    "sidebarCSS": true,
    "groupCSS": false,
    "snapNotify": true,
    "snapExcludePrivate": true,
    "snapInterval": 1,
    "snapIntervalUnit": "day",
    "snapLimit": 0,
    "snapLimitUnit": "snap",
    "hScrollThroughPanels": false,
    "scrollThroughTabs": "panel",
    "scrollThroughVisibleTabs": true,
    "scrollThroughTabsSkipDiscarded": true,
    "scrollThroughTabsExceptOverflow": true,
    "scrollThroughTabsCyclic": false,
    "tabDoubleClick": "exp",
    "tabLongLeftClick": "none",
    "tabLongRightClick": "none",
    "tabsPanelLeftClickAction": "none",
    "tabsPanelDoubleClickAction": "none",
    "tabsPanelRightClickAction": "menu",
    "tabsPanelMiddleClickAction": "none",
    "syncName": "",
    "syncSaveSettings": true,
    "syncSaveCtxMenu": true,
    "syncSaveStyles": true,
    "syncAutoApply": false
  },
  "permissions": {
    "allUrls": true,
    "tabHide": true,
    "actualAllUrls": true,
    "actualTabHide": true
  },
  "storage": {
    "size": "1.2 mb",
    "props": {
      "bookmarksMenu": "226 b",
      "bookmarksPanelMenu": "54 b",
      "containers_v4": "791 b",
      "cssVars": "1.6 kb",
      "disabledKeybindings": "568 b",
      "expandedBookmarks": "289 b",
      "favAutoCleanTime": "10 b",
      "favUrls": "12.2 kb",
      "favicons": "821.5 kb",
      "lastSnapTime": "13 b",
      "panelIndex": "1 b",
      "panels_v4": "942 b",
      "prevTabsData_v4": "14.4 kb",
      "profileID": "14 b",
      "settings": "2.5 kb",
      "sidebarCSS": "92 b",
      "snapshots_v4": "407.1 kb",
      "tabsData_v4": "13.9 kb",
      "tabsMenu": "196 b",
      "tabsPanelMenu": "184 b"
    }
  },
  "panels": [
    {
      "type": "bookmarks",
      "id": "bookmarks",
      "cookieStoreId": "bookmarks",
      "name": 9,
      "icon": "...",
      "bookmarks": true,
      "lockedPanel": false
    },
    {
      "type": "default",
      "id": "firefox-default",
      "name": 7,
      "icon": "...",
      "cookieStoreId": "firefox-default",
      "lockedTabs": false,
      "lockedPanel": false,
      "noEmpty": false,
      "newTabCtx": "none",
      "moveTabCtx": "none",
      "moveTabCtxNoChild": true
    },
    {
      "type": "tabs",
      "id": "urF51cl_1UHE",
      "name": 7,
      "icon": "...",
      "color": "...",
      "customIconSrc": "",
      "customIcon": "",
      "lockedTabs": false,
      "lockedPanel": false,
      "noEmpty": false,
      "newTabCtx": "none",
      "moveTabCtx": "none",
      "moveTabCtxNoChild": true,
      "urlRulesActive": false,
      "urlRules": ""
    },
    {
      "type": "tabs",
      "id": "YbMI0zt8YLNK",
      "name": 12,
      "icon": "...",
      "color": "...",
      "customIconSrc": "",
      "customIcon": "",
      "lockedTabs": false,
      "lockedPanel": false,
      "noEmpty": false,
      "newTabCtx": "none",
      "moveTabCtx": "none",
      "moveTabCtxNoChild": true,
      "urlRulesActive": false,
      "urlRules": ""
    }
  ],
  "cssVars": {
    "tabs_activated_bg": "#444444",
    "tabs_lvl_indicator_bg": "#818181ff",
    "bookmarks_bookmark_font": ".9rem sans-serif",
    "bookmarks_folder_font": ".9rem sans-serif"
  },
  "sidebarCSSLen": 85,
  "windows": [
    {
      "state": "maximized",
      "incognito": false,
      "tabsCount": 120
    },
    {
      "state": "maximized",
      "incognito": false,
      "tabsCount": 8
    },
    {
      "state": "maximized",
      "incognito": false,
      "tabsCount": 4
    },
    {
      "state": "maximized",
      "incognito": false,
      "tabsCount": 5
    }
  ],
  "tabsMenu": [
    [
      "discard",
      "mute",
      "reload"
    ],
    [
      {
        "name": ""
      },
      "moveToPanel",
      "moveToNewWin"
    ],
    "separator-1",
    "reopenInCtr",
    "duplicate",
    "separator-2",
    "group",
    "pin",
    "separator-4",
    "clearCookies",
    "close",
    "closeDescendants"
  ],
  "bookmarksMenu": [
    [
      {
        "name": "Open in"
      },
      "openInNewWin",
      "openInNewPrivWin",
      "openInCtr"
    ],
    "separator-5",
    "createBookmark",
    "createFolder",
    "createSeparator",
    "separator-6",
    "sortByName",
    "sortByLink",
    "sortByTime",
    "separator-7",
    "copyUrls",
    "edit",
    "delete"
  ],
  "bookmarks": {
    "bookmarksCount": 142,
    "foldersCount": 18,
    "separatorsCount": 1,
    "maxDepth": 3
  }
}
</code></details>

**Comment by mbnuqw** [comment]
Thanks for the report!
