### ISSUE TITLE
Do not create sub-tree when opening a link from a pinned tab

### ISSUE THREAD

**Issue by klevstul** [mbnuqw/sidebery#245]
## Description
When opening a link from a pinned tab a container tab is created representing the parent tab. The opened link is attached as a child to this tab. This behaviour is a tad annoying. I would love to have the option to completely ignore creating a tree structure when opening tabs from a pinned tab.

**Example**
Here I have gitlab.com as a pinned tab, and opening a link to the Sidebery extension from the gitlab page creates a container tab with the name "docs/abmarks.md".
![fbk_20200520171503_252x237](https://user-images.githubusercontent.com/216850/82463890-b1c20380-9abd-11ea-8323-b45298df6b44.png)

**Thank You**
Last, but not least, a huge thank you for a fantastic addon!

**Comment by mbnuqw** [comment]
You can disable this with the "Group tabs that were opened from pinned tab" option in "Position of new tab" section. Hm... I think I should make this feature opt-in.

**Comment by klevstul** [comment]
@mbnuqw 

Thanks for getting back to me. I overlooked that option. Yeah, maybe this should be opt-in instead.

**Comment by mbnuqw** [comment]
Fixed in v4.9.0
