### ISSUE TITLE
CTRL+Delete closes tabs instead of deleting words

### ISSUE THREAD

**Issue by mlissner** [mbnuqw/sidebery#247]
## Steps to reproduce

1. Start typing a message in an input box.
2. Realize you don't want a few words to the right of your cursor.
3. Press CTRL+DEL a few times

## Expected behavior

1. The words should be deleted.

## Actual behavior

1. A bunch of tabs close! 

## Environment info

OS: linux
Firefox: 76.0.1
Addon: 4.8.0

Thank you! I'm checking this out after using TST for many years. So far I'm loving it.

**Comment by mbnuqw** [comment]
Sorry, I initially choose bad defaults for shortcuts. To fix this behavior you need to change/remove the "Remove selected items or active tab" shortcut. You can change shortcut it in settings page of Sidebery (unfortunately toggle currently not work #241). To completely remove this shortcut you need go to the Add-ons Manager (about:addons), press on the "gear" button and open Manage Extensions Shortcuts, and then find it and remove it.

**Comment by mlissner** [comment]
> open Manage Extensions Shortcuts

Wow, I'm an extension dev and I know Firefox really well and never knew that one! Thanks.

I figured out how to disable it via Sidebery's preferences, so not a big deal, but I'd prioritize fixing this since it causes potential data loss, is surprising, and it's unclear what's happening or why.

**Comment by NN---** [comment]
You can go to Sideberry options and disable Ctrl+Del shortcut

**Comment by mbnuqw** [comment]
Fixed in v4.9.0
