### ISSUE TITLE
Skip folded tabs on Ctrl+Tab and Ctrl+Shift+Tab

### ISSUE THREAD

**Issue by pintassilgo** [mbnuqw/sidebery#248]
- A
  - B (hidden because tree is collapsed)
- C

If A is focused, Ctrl+Tab should switch to C. Currently the tree is expanded and B is selected.

And if C is focused, Ctrl+Shift+Tab should switch to A without expanding its tree.

This is for those like me who uses `browser.ctrlTab.recentlyUsedOrder = false`.

Thanks.

**Comment by mbnuqw** [comment]
Unfortunately, this is not possible because I haven't control over Firefox's shortcuts commands. The only way to achieve this behavior is to provide such keybindings - I can add the "Activate next/prev visible tab" commands.

**Comment by pintassilgo** [comment]
Hi,

This may not be formally possible, but there's a workaround, since Tree Style Tab can handle this. It has an option "_Don't expand collapsed tree and skip collapsed descendants, while switching focus of tabs via keyboard shortcuts_" that works as intended.

But in addition to that TST way, I think you may also provide the "Activate next/prev visible tab" keybinding so that I can configure to use it with my mouse gestures script to switch to next/prev visible tab (I use rightclick + wheel). In fact, currently I'm a TST user and it has `nextvisiblecyclic` and `prevvisiblecyclic` commands that I use with my mouse gestures.

I'm thinking about replacing TST with Sidebery because your addon handles group switching (you call them "panels") so much better. I tested your addon months ago and it's amazing how it improved since then! Maybe all my "requirements" will be fulfilled with current issues I opened. Thank you for your work and attention.

**Comment by pintassilgo** [comment]
I don't know since when, but this was implemented: the user must turn on `Hide folded tabs`.
