### ISSUE TITLE
Option to open serial tabs one next to the other, respecting Firefox default

### ISSUE THREAD

**Issue by pintassilgo** [mbnuqw/sidebery#249]
What I want is Firefox's default applied to tree structure.

Lets say I have tabs A, B and C. B is selected. Then I middleclick three links, 1, 2, 3. Tabbar will display the following order:
A, B, 1, 2, 3, C.

Then I select tab A, then switch back to B and middleclick another link, lets call it 4. Tabbar will display:
A, B, 4, 1, 2, 3, C.

I want Sidebery to display:
- A
- B
  - 4
  - 1
  - 2
  - 3
- C

Exactly like tabbar, but with tree structure. But currently there is no way to do this.

With "Place new tab opened from another tab: first child" we would have A, B, 4, 3, 2, 1, C.
With "Place new tab opened from another tab: last child" we would have A, B, 1, 2, 3, 4, C.

I think the option "none" should behave as I'm describing, but currently it seems to be the same as "panel end", so I don't even know why we have two options for the same effect.

Thanks.

**Comment by mbnuqw** [comment]
I've added an option "default", so it will be available in next release.

**Comment by mbnuqw** [comment]
Added in v4.9.0
