### ISSUE TITLE
"Skip this panel when switching panels"

### ISSUE THREAD

**Issue by pintassilgo** [mbnuqw/sidebery#252]
In the screen to configure each panel, I think there should be an option to "Skip this panel when switching panels", so the panel will be skipped when we trigger action to switch to next/previous panel (like a keybinding).

I think there may be common interest in this for Bookmarks panel, but I would also like to be able to skip specific panel of tabs.

Thanks.

**Comment by mbnuqw** [comment]
Nice idea! Will be added to the next version.

**Comment by mbnuqw** [comment]
Added in v4.9.0
