### ISSUE TITLE
Sync option for panel configuration

### ISSUE THREAD

**Issue by OJFord** [mbnuqw/sidebery#259]
## Description
I'd like to keep panel configuration in sync across devices (or rather FF installs) but presently it's not included in the sync data.

i.e. containers, new tab / URL matching settings, and  any pinned tabs.

**Comment by mbnuqw** [comment]
Duplicate of #54 (hm... I think I need to update title of that issue)

**Comment by OJFord** [comment]
Ah, sorry.
