### ISSUE TITLE
Close tab and return to previously viewed tab

### ISSUE THREAD

**Issue by kinoegit** [mbnuqw/sidebery#26]
Hi and thank you for your great work!
My issue: when a tab is closed the next tab under the closed one will be activated.
My question: is there a way to close a tab and return to previously viewed tab?
I installed "Select After Closing Current" addon but it does not seem to work with sidebery.
running ff on linux with hided native tabs toolbar

**Comment by mbnuqw** [comment]
Thanks. This is impossible at the moment, but I want to add settings to choose what tab should be activated next. And with new api (added in ff >= 65) this seems to be relatively simple, so this can be landed in next version.

**Comment by kinoegit** [comment]
Would be great! For now i switched to Tree style tab but it has another approach. It doesn't emphasizes containers as sidebery does.

**Comment by mbnuqw** [comment]
I've added field "After closing current tab activate..." with option for activating previous active tab. If there are some differences from desirable behavior feel free to reopen this issue.
