### ISSUE TITLE
Pinning active tab triggers switch to another panel

### ISSUE THREAD

**Issue by tennox** [mbnuqw/sidebery#266]
## Steps to reproduce
1. Have an additional panel with only one tab
2. Pin that tab

## Expected behavior
Pinned tab stays active, current panel stays active.

## Actual behavior
Pinned tab stays active, but the active panel view switches to a different panel.

![Sidebery pin panel bug](https://user-images.githubusercontent.com/2084639/84249694-ffe98600-ab02-11ea-9e9d-78c8281919b0.gif)

## Environment info

OS:  elementary OS Hera
Firefox version:  76.0.1 (64-bit)
Addon version:  4.9.0

<details><code>

General
Context menu
Use comma-separated list of contaianers names or /regexp/
Navigation bar
Group page
Containers
Panels
Drag and Drop
Tabs
- global storage - fast, but inaccurate in rare cases.
- session storage - more strict, but slower. (Warning: Tabs data will be removed along with Browser Session)
  Note: If you have issues with incorrectly restored tabs, try to reopen sidebar and change this option.
Position of new tab
Pinned tabs
Tabs tree
Bookmarks
Appearance
Notes:
- To apply theme color to Sidebery buttons in browser interface set "svg.context-properties.content.enabled" to "true" in about:config page.
Mouse
Keybindings
Open/Close sidebar panel
Ctrl+E
off
on
Switch to next panel
Alt+Period
off
on
Switch to previous panel
Alt+Comma
off
on
Open new tab in active panel
Ctrl+Space
off
on
Open new tab after active tab
Ctrl+Shift+Space
off
on
Open new tab as the first child of active tab
---
off
on
Open new tab as the last child of active tab
---
off
on
Remove selected items or active tab
---
off
on
Select all
---
off
on
Up
Alt+Up
off
on
Down
Alt+Down
off
on
Select up
Alt+Shift+Up
off
on
Select down
Alt+Shift+Down
off
on
Activate selection
Alt+Space
off
on
Open menu
---
off
on
Reset selection
Alt+R
off
on
Fold selected branch
---
off
on
Expand selected branch
---
off
on
Fold inactive branches
---
off
on
Active tabs history: Back
---
off
on
Active tabs history: Next
---
off
on
Active tabs history of panel: Back
---
off
on
Active tabs history of panel: Next
---
off
on
Move selected tabs to the active tab
---
off
on
Increase tab's tree level (indent)
---
off
on
Decrease tab's tree level (outdent)
---
off
on
Move tabs up
---
off
on
Move tabs down
---
off
on
Create snapshot
---
off
on
Switch to first panel
---
off
on
Switch to second panel
---
off
on
Switch to third panel
---
off
on
Switch to fourth panel
---
off
on
Switch to fifth panel
---
off
on
Switch to sixth panel
---
off
on
Switch to seventh panel
---
off
on
Switch to eighth panel
---
off
on
Switch to ninth panel
---
off
on
Switch to tenth panel
---
off
on
Permissions
Required for:
- Cleaning cookies
- Proxy and URL rules of containers
- Screenshots for the group page and windows selection panel
- Changing the User-Agent per container
Required for:
- Hiding tabs in inactive panels
- Hiding folded tabs
Required for:
- Copying URLs of tabs/bookmarks through context menu
Required for:
- Changing the User-Agent per container
Snapshots
Storage
 (~580.5 kb)
favicons
~488.3 kb
tabsData_v4
~37.4 kb
prevTabsData_v4
~31.9 kb
favUrls
~18.1 kb
settings
~2.7 kb
panels_v4
~1.7 kb
profileID
~14 b
favAutoCleanTime
~10 b
panelIndex
~1 b
Sync
 (~2.8 kb)
Settings
firefox humus - 2020.06.10 - 10:06:56 - 2.8 kb
Help
Note: Updating tabs may cause them to be rearranged
OS: linux
Firefox: 76.0.1
Addon: 4.9.0
{
  "settings": {
    "version": "4.9.0",
    "nativeScrollbars": false,
    "selWinScreenshots": true,
    "tabsCheck": true,
    "tabsFix": "notify",
    "markWindow": false,
    "markWindowPreface": "[Sidebery] ",
    "ctxMenuNative": false,
    "autoHideCtxMenu": "none",
    "ctxMenuRenderInact": true,
    "ctxMenuIgnoreContainers": "",
    "navBarLayout": "horizontal",
    "navBarInline": true,
    "hideAddBtn": false,
    "hideSettingsBtn": false,
    "navBtnCount": true,
    "hideEmptyPanels": true,
    "navMidClickAction": "none",
    "navSwitchPanelsWheel": true,
    "groupLayout": "grid",
    "skipEmptyPanels": false,
    "dndTabAct": true,
    "dndTabActDelay": 750,
    "dndTabActMod": "none",
    "dndExp": "pointer",
    "dndExpDelay": 0,
    "dndExpMod": "none",
    "stateStorage": "global",
    "warnOnMultiTabClose": "collapsed",
    "activateOnMouseUp": true,
    "activateLastTabOnPanelSwitching": true,
    "showTabRmBtn": true,
    "showTabCtx": true,
    "hideInact": false,
    "activateAfterClosing": "next",
    "activateAfterClosingPrevRule": "visible",
    "activateAfterClosingNextRule": "tree",
    "activateAfterClosingGlobal": false,
    "activateAfterClosingNoFolded": true,
    "activateAfterClosingNoDiscarded": true,
    "shiftSelAct": true,
    "askNewBookmarkPlace": false,
    "tabsRmUndoNote": true,
    "nativeHighlight": false,
    "tabsUnreadMark": false,
    "tabsReloadLimit": 5,
    "tabsReloadLimitNotif": true,
    "moveNewTabPin": "start",
    "moveNewTabParent": "last_child",
    "moveNewTabParentActPanel": false,
    "moveNewTab": "end",
    "pinnedTabsPosition": "panel",
    "pinnedTabsList": false,
    "pinnedAutoGroup": false,
    "tabsTree": true,
    "groupOnOpen": true,
    "tabsTreeLimit": "none",
    "hideFoldedTabs": false,
    "autoFoldTabs": false,
    "autoFoldTabsExcept": "none",
    "autoExpandTabs": false,
    "rmChildTabs": "none",
    "tabsChildCount": true,
    "tabsLvlDots": false,
    "discardFolded": false,
    "discardFoldedDelay": 0,
    "discardFoldedDelayUnit": "sec",
    "tabsTreeBookmarks": true,
    "treeRmOutdent": "branch",
    "bookmarksPanel": true,
    "warnOnMultiBookmarkDelete": "collapsed",
    "openBookmarkNewTab": false,
    "midClickBookmark": "open_new_tab",
    "actMidClickTab": false,
    "autoCloseBookmarks": false,
    "autoRemoveOther": false,
    "highlightOpenBookmarks": false,
    "activateOpenBookmarkTab": false,
    "showBookmarkLen": false,
    "bookmarksRmUndoNote": true,
    "fontSize": "m",
    "bgNoise": true,
    "animations": true,
    "animationSpeed": "fast",
    "theme": "default",
    "style": "auto",
    "sidebarCSS": false,
    "groupCSS": false,
    "snapNotify": true,
    "snapExcludePrivate": false,
    "snapInterval": 0,
    "snapIntervalUnit": "min",
    "snapLimit": 0,
    "snapLimitUnit": "snap",
    "hScrollThroughPanels": false,
    "scrollThroughTabs": "none",
    "scrollThroughVisibleTabs": false,
    "scrollThroughTabsSkipDiscarded": false,
    "scrollThroughTabsExceptOverflow": true,
    "scrollThroughTabsCyclic": false,
    "tabDoubleClick": "none",
    "tabLongLeftClick": "none",
    "tabLongRightClick": "none",
    "tabsPanelLeftClickAction": "none",
    "tabsPanelDoubleClickAction": "tab",
    "tabsPanelRightClickAction": "menu",
    "tabsPanelMiddleClickAction": "tab",
    "syncName": "firefox humus",
    "syncSaveSettings": true,
    "syncSaveCtxMenu": false,
    "syncSaveStyles": false,
    "syncAutoApply": false
  },
  "permissions": {
    "allUrls": true,
    "tabHide": true,
    "actualAllUrls": true,
    "actualTabHide": true
  },
  "storage": {
    "size": "580.5 kb",
    "props": {
      "favAutoCleanTime": "10 b",
      "favUrls": "18.1 kb",
      "favicons": "488.3 kb",
      "panelIndex": "1 b",
      "panels_v4": "1.7 kb",
      "prevTabsData_v4": "31.9 kb",
      "profileID": "14 b",
      "settings": "2.7 kb",
      "tabsData_v4": "37.4 kb"
    }
  },
  "panels": [
    {
      "type": "bookmarks",
      "id": "bookmarks",
      "cookieStoreId": "bookmarks",
      "name": 9,
      "icon": "...",
      "bookmarks": true,
      "lockedPanel": false,
      "skipOnSwitching": false
    },
    {
      "type": "default",
      "id": "firefox-default",
      "name": 7,
      "icon": "...",
      "cookieStoreId": "firefox-default",
      "lockedTabs": false,
      "lockedPanel": false,
      "skipOnSwitching": false,
      "noEmpty": false,
      "newTabCtx": "none",
      "dropTabCtx": "none",
      "moveTabCtx": "none",
      "moveTabCtxNoChild": true
    },
    {
      "type": "tabs",
      "id": "ofiYDNnq0LTG",
      "name": 11,
      "icon": "...",
      "color": "...",
      "customIconSrc": "",
      "customIcon": "",
      "lockedTabs": false,
      "lockedPanel": false,
      "skipOnSwitching": false,
      "noEmpty": false,
      "newTabCtx": "none",
      "dropTabCtx": "none",
      "moveTabCtx": "none",
      "moveTabCtxNoChild": true,
      "urlRulesActive": false,
      "urlRules": ""
    },
    {
      "type": "tabs",
      "id": "vI9juCzz2LnR",
      "name": 7,
      "icon": "...",
      "color": "...",
      "customIconSrc": "",
      "customIcon": "",
      "lockedTabs": false,
      "lockedPanel": false,
      "skipOnSwitching": false,
      "noEmpty": false,
      "newTabCtx": "none",
      "dropTabCtx": "none",
      "moveTabCtx": "none",
      "moveTabCtxNoChild": true,
      "urlRulesActive": true,
      "urlRules": 7
    },
    {
      "type": "tabs",
      "id": "qcfTw8X9W_w0",
      "name": 6,
      "icon": "...",
      "color": "...",
      "customIconSrc": "",
      "customIcon": "",
      "lockedTabs": false,
      "lockedPanel": false,
      "skipOnSwitching": false,
      "noEmpty": false,
      "newTabCtx": "none",
      "dropTabCtx": "none",
      "moveTabCtx": "none",
      "moveTabCtxNoChild": true,
      "urlRulesActive": true,
      "urlRules": 12
    },
    {
      "type": "tabs",
      "id": "qCBcffPfnhHv",
      "name": 9,
      "icon": "...",
      "color": "...",
      "customIconSrc": "",
      "customIcon": "",
      "lockedTabs": false,
      "lockedPanel": false,
      "skipOnSwitching": false,
      "noEmpty": false,
      "newTabCtx": "none",
      "dropTabCtx": "none",
      "moveTabCtx": "none",
      "moveTabCtxNoChild": true,
      "urlRulesActive": false,
      "urlRules": ""
    }
  ],
  "containers": [],
  "cssVars": "TypeError: can't convert undefined to object",
  "windows": [
    {
      "state": "maximized",
      "incognito": false,
      "tabsCount": 390
    }
  ],
  "bookmarks": {
    "bookmarksCount": 80,
    "foldersCount": 12,
    "separatorsCount": 0,
    "maxDepth": 3
  }
}

</code></details>

**Comment by TeNNoX** [comment]
This also happens when I close the last unpinned tab in a panel.

**Comment by TeNNoX** [comment]
Actually, it also happens when there **are** other tabs in the same panel... :astonished:

**Comment by mbnuqw** [comment]
Thank you for the report. I found the root of this problem, so it will be fixed soon.

**Comment by mbnuqw** [comment]
Fixed in v4.10.2
