### ISSUE TITLE
Optional separate Custom CSS setting to apply to tab group(s)

### ISSUE THREAD

**Issue by LeeteqXV** [mbnuqw/sidebery#269]
## Description
I want to save a set of CSS rules to apply to a tabs group.

- Would this be easy to add to this addon, having custom CSS option already?

Would be very interesting if both TreeStyleTab + "Live CSS editor" addons can be replaced with this addon... :-)

**Comment by ongots** [comment]
https://addons.mozilla.org/firefox/addon/styl-us/

**Comment by LeeteqXV** [comment]
(I know about other such CSS editing addons, just would like to be dependent on as few extra addons as possible, so if this module just needs a small change to make that function useful in other tabs as well, then that would be preferable.)
