### ISSUE TITLE
lookup in bookmarks

### ISSUE THREAD

**Issue by dzejba** [mbnuqw/sidebery#27]
Idea for improvement: add lookup field to bookmarks so that it would be easy to find them by (substring) text.

**Comment by mbnuqw** [comment]
Firefox already have this feature, so I don't think that adding this is really needed.
I personally use ctrl+L (to focus on url bar), then types "* + search query" to search for bookmark.
More info here: https://support.mozilla.org/en-US/kb/awesome-bar-search-firefox-bookmarks-history-tabs
(to increase count of results change `browser.urlbar.maxRichResults` in about:config)

Plus, there are no way (at least I cannot find how) to focus on sidebar input field with keyboard shortcut - only mouse, which is sad for keyboard guys.

**Comment by dzejba** [comment]
Aha, did not know about that, it is really nice way. Thx for hint.
