### ISSUE TITLE
Option to show (pinned) tabs in all panels

### ISSUE THREAD

**Issue by Matroc** [mbnuqw/sidebery#270]
## Description
I usually use the pinned tabs for things that I want always available (like music, notes, email, messengers etc.), but when I switch to another panel, they are not shown at the top. Would it be possible to have an option to have pinned tabs show up on all panels or assign tabs in general to multiple/all panels?

**Comment by OJFord** [comment]
I like this idea, but I do also like having panel-specific pinned tabs. e.g. My 'work' panel has some pinned tabs related to work that I wouldn't use otherwise.

It would be nice if this were an option to have it as a second 'global pins' row above the panel-specific ones, so that both can be used.

**Comment by LeeteqXV** [comment]
+1
A "second global pins" row sounds like a good enhancement.

**Comment by flamingo-cant-draw** [comment]
You can already do this. Just go Sideberry Setting -> Pinned Tabs -> Pinned Tabs Position -> Top.

**Comment by denemier** [comment]
@flamingo-cant-draw 

Wow at first i thought you misunderstood the problem, as it was just like the only problem to position pinned tabs at top.

But I just given it a try and it looks like you are right, and there is a big difference between pinned tabs positions and its not just about their visual positions:

**1**-panels (shows only panel specific pinned tabs from active group)
**2**-top (shows all pinned tabs from all groups always on top doesnt matter which tab group you are in)
**3**-left (shows all pinned tabs like 2)
**4**-right (shows all pinned tabs like 2)

**Comment by denemier** [comment]
hey @mbnuqw ,

maybe we can add a little info text inside brackets,
for the **Pinned tabs position** options in settings like:

Pinned tabs position                panels (shows only current panel)       top       left      right

**Comment by mbnuqw** [comment]
Closing this as implemented. For the both global and local (per-panel) pinned tabs, follow the #1007

**Comment by TheBigWazz** [comment]
Sorry to revive this closed thread, but I have an idea for an enhancement. Allow both Global and Panel pins to be displayed in a panel at the same time. This would allow users to benefit from both use cases of global pins and panel pins. It would be handy to have a grid of global pins in the bottom bar. Here's what this might look like. 

![Image](https://github.com/user-attachments/assets/177bb806-dab3-4d61-940e-0fa5176e6253)

**Comment by OJFord** [comment]
@TheBigWazz Unless I misunderstand you, that is exactly #1007 mentioned above?

**Comment by TheBigWazz** [comment]
@OJFord you′re correct, thanks for pointing that out.
