### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by Jipok** [mbnuqw/sidebery#271]
Your addon is great, but a few little things are missing for me:
1) You have binds to switch to the panel by number. This is great, but as an i3wm user, I’m used to that trying again to switch to the same workspace will switch you to the previous workspace.
That is, I have ctrl+1 and ctrl+3 binds that switch to the 1th and 3th panels, respectively. Being on the 3th panel, I switch to the 1th through ctrl+1. And then I would like to return to the 3th panel by pressing ctrl+1 again.
2) I would like a similar behavior for tabs. That is clicking on the current active tab should switch to the previous active tab.
3) For me, panels with a number of more than three are all tied to a specific job or task, in which I am looking for something and open many tabs.
For example, one current task may be to search for a telephone on aliexpress, and another task may be to search for information on any disease. And I absolutely do not want the sites in these different panels to be able to combine information about me together. Mostly they do this through ad networks. Containers help in this case. In your addon there is an opportunity to associate a container with a panel.
But I would like the container to be connected with only one panel and vice versa. So that they are inseparable from each other.
I am now manually creating containers and panels. However, I am confused by the different icon sets for them. And I do not see a guarantee that all tabs open on one panel will belong to one container, and vice versa.
4) Also I need the option to automatically clear all container data after closing the last tab in it.
5) As I see now, there are two options for the scrollbar: the native and the blue bar on top with automatic hiding. Is it possible to make an option with a bar on the right side?

**Comment by mbnuqw** [comment]
Closing this as outdated and invalid: One issue should include only one feature request/bug report.
