### ISSUE TITLE
why is sideberry using too much ram

### ISSUE THREAD

**Issue by denemier** [mbnuqw/sidebery#272]
## Description
![resim](https://user-images.githubusercontent.com/63566495/85487735-d554fe00-b5d5-11ea-937f-85428568f660.png)
i have 1500 tabs open but only 1 tab and 6 pinned tabs active, the rest unloaded why too much ram in task manager?
will tab number affect sideberry in the future? so more tabs more slower even if i unload all tabs only use few of them at a time?

**Comment by mbnuqw** [comment]
Closing this as outdated. Please, reopen if issue is reproduced in the latest version of Sidebery.
