### ISSUE TITLE
does this extension has a page name like moz-extension://50efb400-.........discarded.html?=

### ISSUE THREAD

**Issue by denemier** [mbnuqw/sidebery#276]
hi i found some tabs in my browser looks like
moz-extension://50efb400-.........discarded.html?=ExampleSite
which is broken and cant be opened, so i need to manuelly remove prefix from url.

i recently used some third party extensions for auto tab suspension but i deleted them, so the question is; I am not sure if those broken urls are from my older extensions or from sideberry?

By the way, it would be nice to have auto tab suspension feature for sideberry but without any url replacement i hate urls like moz-extension, because if the extension is once deleted i can't reach it anymore.

**Comment by mbnuqw** [comment]
Closing this as stale.
