### ISSUE TITLE
Some trees broken on restart

### ISSUE THREAD

**Issue by prizrak9** [mbnuqw/sidebery#278]
## Steps to reproduce
restart browser.

## Expected behaviour
some of the trees broken.

## Actual behaviour
all the trees are the way they were before closing the browser.

## Environment info

OS:  
Firefox version:  
Addon version:  

<details><code>

</code></details>

**Comment by prizrak9** [comment]
Some trees are broken every time. 
I'm trying to recreate the tree each time but it results in it being broken again. 
Some persist quite successfully.
However, all the trees get broken at some point regardless of how many restarts they manage to survive.

**Comment by Dimas-sc** [comment]
Maybe duplicated of #267 ?

**Comment by prizrak9** [comment]
Looks similar indeed.
Left a comment there.
