### ISSUE TITLE
Integration with Nighttab bookmarks

### ISSUE THREAD

**Issue by LeeteqXV** [mbnuqw/sidebery#279]
## Description
A perfect match? I suggest Sidebery could integrate with the fantastic bookmarks/new tab page provided by the Nighttab addon by @zombieFox .

Not necessarily GUI/interface-wise, perhaps just add a "NightTab bookmarks" folder after "Mobile bookmarks", and then reflect the grouping and titles?
And when Sidebery makes adjustments/additions there; could it work directly with the source, while nightTab is actively running, or use some sort of sync?

Ref. https://github.com/zombieFox/nightTab

**Comment by mbnuqw** [comment]
Closing this as stale.
