### ISSUE TITLE
Borders of the tabs

### ISSUE THREAD

**Issue by Dook1** [mbnuqw/sidebery#28]
How I can customize borders of the tabs?

**Comment by mbnuqw** [comment]
Currently there is no such options, but I've just added support of borders and shadows (which can be used as borders) for default/activated/selected tab states:

![screenshot-2019 04 03-11 28 47_001](https://user-images.githubusercontent.com/6276694/55464438-94f61280-5614-11e9-89e1-1e0c3df802cf.png)

Will be released in v2.4.0

**Comment by Dook1** [comment]
Is it possible for all tabs to do this? As in TST for example Metall style.

**Comment by mbnuqw** [comment]
It's not the same as Metal theme of TST... but it's possible to separate tabs like this:
![screenshot-2019 04 03-18 00 52_001](https://user-images.githubusercontent.com/6276694/55482963-09de4200-563f-11e9-955e-464aa132f2bd.png)

Or with a small depth ):
![screenshot-2019 04 03-17 56 23_001](https://user-images.githubusercontent.com/6276694/55483053-3db96780-563f-11e9-83bd-87cb3e8931f2.png)

**Comment by Dook1** [comment]
And how to do it?

**Comment by mbnuqw** [comment]
Just wait for v2.4.0 and play with borders/shadows in Tabs section of styles editor

**Comment by Dook1** [comment]
Thanks. Can I also add the option to round corners?

**Comment by mbnuqw** [comment]
Hmm... No, I think this will too hard to achieve b/c of current structure of tab.
Maybe later I add ability to fully control css and create completely custom themes...

**Comment by Dook1** [comment]
Ok. Thanks

**Comment by mbnuqw** [comment]
Added in v2.4.0

**Comment by Dook1** [comment]
The border does not appear when new options are enabled.

**Comment by mbnuqw** [comment]
There are two ways to create borders
- Use border style:
![screenshot-2019 04 16-20 23 08_001](https://user-images.githubusercontent.com/6276694/56223141-a31d4780-6086-11e9-9dcb-038f3bfb8b2a.png)
![screenshot-2019 04 16-20 23 25_001](https://user-images.githubusercontent.com/6276694/56223151-aadcec00-6086-11e9-8023-b4d2443c475c.png)

- Or use shadows:
![screenshot-2019 04 16-20 19 58_001](https://user-images.githubusercontent.com/6276694/56223177-b6301780-6086-11e9-8ce0-ca2ba1778976.png)
![screenshot-2019 04 16-20 20 35_001](https://user-images.githubusercontent.com/6276694/56223187-b9c39e80-6086-11e9-8db5-168221906ee2.png)

It's a bit hacky, yes, but works.

**Comment by mbnuqw** [comment]
Also you can track #39 issue

**Comment by Dook1** [comment]
It works. Thanks.
Could you make the result of the change in styles immediately visible? Like for example in "Tree tabs". Now I need to make a lot of extra clicks after each change.

**Comment by mbnuqw** [comment]
Hmm... Looks like this is a bug.
It should apply changes after field lose focus.

**Comment by mbnuqw** [comment]
And about dozens of clicks - yes this is bad. I will create separate page with all settings to see changes immediately. #34

**Comment by Dook1** [comment]
It apply. But I have to switch to "Tabs" to see the result, and then return back to the options. Yes, separate page is a great idea.
