### ISSUE TITLE
Great addon, some feedback

### ISSUE THREAD

**Issue by deflock** [mbnuqw/sidebery#281]
Thanks for the awesome addon. Works much faster and smoother than TBT.
I want to help you by implementing some features or fixing bugs, but not sure I'll have enough time for this. For now I don't want to open an separate issue for each item and just list some features/bugs for you and for myself to not forget 😀

Bugs:
1. Tab looses audible state (at least in pinned). When audio is played in background tab after some time this tab looses audible badge and it's not possible to click on it to mute. Instead of it updated badge is shown. I've checked some code and I don't know why this happens. Looks like firefox controls this and sidebery just updates state on onTabUpdates event.
2. [Needs confirmation] When the rightmost panel is active, after its closing the plus button/panel is activated instead of other panel.
3. Something wrong with Styles Editor auto height. If there is a lot of content it has two scrollbars: one for the parent container and another one for itself.

Features:
1. Scroll newly created tabs into view. If you have a lot of tabs and when you create new tabs as children from the active one they are created in background on the bottom of panel and out of view. In this case you even don't know if they are opened or not. TBT for this uses 2 things: if it's possible it scrolls panel until the new tab appears in view. But this continues while the active tab remains in view itself, otherwise TBT does not scroll but shows a colored "flash" on the bottom of panel indicating new tab is opened there.
2. Close tab on middle mouseup, not mousedown, and only if the pointer is still over this tab on mouseup event triggered.
3. Actions on mouse events + modifiers (ctrl, shift, alt, meta). For example I want to assign some action on alt + dblclick or ctrl + drag. Looks like a huge task.
4. For tab duplication: hotkey, action for point 3 (e.g. I want to duplicate tab on ctrl + drag).
5. An option for dragging tab by its favicon. As I see in commit history this was denied for some reason.
6. Custom/other addons' items in context menus. I have some addons that add items in menu, but there are not shown.
7. Disable audible state for specified tabs. I have pinned tab with a chat opened in it, when I get a new message the sound is played. I want to activate this tab quickly but instead of tab I misclick on audible badge and mute the tab instead of activating it. There is should be an option for this case: show audible badge but make it non-clickable, or do not show badge at all.
8. Make Ctrl+Tab behavior like Alt+Tab in Windows. If Ctrl+Tab combintaion is released it switches between the two same tabs. But if Ctrl is down and multiple Tab is clicked it cycles over tabs in specified order.

Well, more than I expected 😅 Could you also write some lines about your plans of this addon's near future? Will it evolutionize as is or you are going to totally rewrite some parts? Thanks for the addon again. You rock 💪

**Comment by mbnuqw** [comment]
Closing this as stale and invalid: One issue should include only one feature request/bug report.
