### ISSUE TITLE
Use new tabs.warmup() API to improve performance

### ISSUE THREAD

**Issue by harshit-j** [mbnuqw/sidebery#284]
## Description
Firefox 79 has a new tabs.warmup() API to improve performance of switching tabs. Can it be implemented in Sidebery?
[https://hacks.mozilla.org/2020/07/firefox-79/](https://hacks.mozilla.org/2020/07/firefox-79/)
> WebExtensions updates
> 
> Starting with Firefox 79, developers of tab management extensions can improve the perceived performance when users switch tabs. The new tabs.warmup() function will prepare the tab to be displayed. Developers can use this function, when they anticipate a tab switch, e.g. when hovering over a button or link.

**Comment by mbnuqw** [comment]
Closing this as implemented
