### ISSUE TITLE
HEELLLLPPPP

### ISSUE THREAD

**Issue by TopcatRanch** [mbnuqw/sidebery#285]
OS: mac
Firefox: 78.0.2
Addon: 4.9.0

All I did was reboot , and Firefox didn't restore any tabs.   I thought simple, I just
go load my latest snapshot - except now none of them are listed.    How can
I find my snapshots and load the last one ?

## Environment info

OS:  
Firefox version:  
Addon version:  

<details><code>

</code></details>

**Comment by TopcatRanch** [comment]
Does anybody know where I can find the snapshot files, so I can try to restore ???

**Comment by TravisNoles** [comment]
You can find them in the settings tab towards the bottom, snapshots have to be activated before though. Not enabled by default.

**Comment by mbnuqw** [comment]
Closing this as stale.
