### ISSUE TITLE
"New Tab" button

### ISSUE THREAD

**Issue by FaffyBucket** [mbnuqw/sidebery#286]
## Description
Please add a "New Tab" button at the end of the tab list. This is a common feature in most (all?) web browsers that have tabs. It's confusing that this is the one tab list that doesn't have a "New Tab" button.

**Comment by mbazdell** [comment]
May not be needed if clearer instructions are provided.

You can make a new tab either double clicking any blank space in the panel, or clicking the panel's icon while already on that panel.

**Comment by emvaized** [comment]
> May not be needed if clearer instructions are provided.
> 
> You can make a new tab either double clicking any blank space in the panel, or clicking the panel's icon while already on that panel.

Agreed, Sidebery lacks a great documentation a lot.
By the way, 'new tab' button may provide a wider functionality, the way it is in TST. 
For example, in my set up: 
double click on empty space -> new tab, 
middle click on empty -> close tab, 
middle click on new tab button -> new child tab, 
and single click -> new tab.

So maybe not that bad idea at all. But I like the minimalism and simplicity of non-button approach 👍

**Comment by FaffyBucket** [comment]
Thanks for the information. I did eventually figure out that double-click creates a new tab. I never would have thought that clicking the panel icon would create a tab though!

So the feature I requested is there, the problem is just that I couldn't find it. Could the panel icon be changed to a + symbol? I think that would make it clear that it functions as a new tab button.

**Comment by ChauhanT** [comment]
I think a new tab button would be an excellent UI addition. It doesn't have to span the width of the vertical bar - just a small button the size of the favicons below the last tab.

**Comment by deviant** [comment]
Presently, there is no way to create a new tab *in* a specific container. The only way is to create a new tab, reopen it in a new container, and then navigate to your chosen URL. TST has this functionality (IIRC via a small dropdown to the right of the new tab button), and the native Firefox UI lets you long-press the new tab button to select a container to open in. Firefox also has an option to require choosing which container to open new tabs in, i.e. skipping the need to long-press. A replacement for some or all of this functionality in Sidebery would be hugely appreciated.

**Comment by Qwerty-Space** [comment]
> May not be needed if clearer instructions are provided.
> 
> You can make a new tab by ... clicking the panel's icon while already on that panel.

That doesn't seem to work for me

**Comment by dexeonify** [comment]
> That doesn't seem to work for me

You have to enable it under Sidebery settings > Navigation bar > **Left click on active tabs panel**

**Comment by scruel** [comment]
It can be a great feature so that I can get the same experience while using Microsoft Edge for Firefox:
![image](https://user-images.githubusercontent.com/16933298/203697329-01d467f1-3a19-4535-85cc-8d6863e0da30.png)

Hope you can add this~

**Comment by albino1** [comment]
I can't remember if this is in v4, but in Sidebery v5 there's an option in the Settings under Tabs called `Show new tab buttons` with the options of `after tabs` or `bottom` which does what you're looking for:

![sidebery](https://user-images.githubusercontent.com/12164957/203922149-1aa4d609-5882-403d-80f7-1ba1909443d7.jpg)

It looks like this when set to `after tabs`:

![sidebery2](https://user-images.githubusercontent.com/12164957/203922332-56d1491a-7cd9-4c8a-a3bc-3e9e789ac467.jpg)

**Comment by scruel** [comment]
@albino1 Waiting v5 to be released to FF store

**Comment by brgr-m-r** [comment]
How can we enable the **"New Tab" button** to position the new tab at the **panel end**, while **"Position of new tab (general rule)"** setting is set to "**after active tab**" (or other rule selected as necessary)?

**Comment by mbnuqw** [comment]
Available from v5.0.0
