### ISSUE TITLE
Scrolling when choosing a window to move a tab to

### ISSUE THREAD

**Issue by mbaz** [mbnuqw/sidebery#29]
The "move to window" functionality is awesome. However, I have more windows open than fit in the sidebar, and I can't scroll to get to all of them. I tried scrolling with the mouse and with keys, and I can't see any scrolling bar.

**Comment by mbnuqw** [comment]
:thinking:  This is strange, I cannot reproduce this issue... Scroll (with mouse above the sidebar) works as intended.
Does the panel close after clicking on an empty area?

**Comment by mbaz** [comment]
Strange indeed -- after reading your comment I tried again, and it works now. I'll assume I was doing something wrong.
