### ISSUE TITLE
On laptop, 2 fingers swipe to switch panels triggers browser's back/forward gesture

### ISSUE THREAD

**Issue by emvaized** [mbnuqw/sidebery#291]
## Steps to reproduce
Enable 'switch panels with horizontal wheel scroll' in Mouse settings, and try to perform two-fingers swipe over sidebery (which emulates mouse wheel horiontal scroll).

## Expected behavior
Panels should switch, and browser's gesture handler events should be ignored.

## Actual behavior
Panels do switch indeed (works **really** well, especially on Macbook), but the browser itself triggers back/forward gesture at the same time, which is unwanted.

Perhaps this issue occurs only on macbooks and windows laptops with precision touchpads.

## Environment info

OS: mac
Firefox version:  79.0
Addon version: 4.9.0

**Comment by mbnuqw** [comment]
Closing this as stale. Please, reopen if this issue is reproduced in the latest version of Sidebery.
