### ISSUE TITLE
Which session manager do you recomend to use with sidebery?

### ISSUE THREAD

**Issue by labyrinth-to-solve** [mbnuqw/sidebery#295]
I would like to get back the tree structurre.
Thanks

**Comment by relink2013** [comment]
I've been on the hunt for the same thing. The snap shot feature in V5 is pretty good, but with it buried in the settings its not very convenient to use.

**Comment by mbnuqw** [comment]
You can now use keybindings to create snapshot / open snapshot viewer, you can use "Create snapshot" button in navigation bar of sidebar (Sidebery settings / Navigation bar): Left-click - to create snapshot, Middle-click to open snapshot viewer.

For possible session manager integration, track the #616
