### ISSUE TITLE
Suggestion for highlighted bookmark in sidebar

### ISSUE THREAD

**Issue by gasman1844** [mbnuqw/sidebery#302]
## Description
Currently there is an option for an open bookmark to be highlighted in the sidebar. It would be helpful if this matched the domain rather than a precise match. So a bookmark of www.bbc.co.uk will be highlighted if I open www.bbc.co.uk but if I navigate to www.bbc.co.uk/football I lose the highlight. Matching to the domain of www.bbc.co.uk would maintain the highlight while I navigate around the bbc site.

**Comment by mbnuqw** [comment]
Not planned
