### ISSUE TITLE
Option when dragging/dropping tab on top of exisiting branch to put tab at bottom of child list

### ISSUE THREAD

**Issue by shywolfcry** [mbnuqw/sidebery#309]
Have I missed an option for this somewhere? Right now, dragging and dropping a tab onto the parent of an existing branch puts the tab under the parent, at the top of all the existing child tabs. Is there, or could you please add, an option to put tabs at the bottom of the child list when dragged/dropped onto the parent? I love the addon, and thank you for your work on it.

**Comment by mbnuqw** [comment]
Should be fixed in the latest version.
