### ISSUE TITLE
Custom CSS: Change width of "container color bar"

### ISSUE THREAD

**Issue by Ruboka** [mbnuqw/sidebery#310]
In Firefox tabs can be opened inside of containers which you can specific the color of, with they are visually highlighted.

In Sideberry the color of the container in which a tab is open/active is just 1px or so it seems wide, and on the right side.
This can be difficult to see, if the page has a unhappy color scheme.

I cant find the css property of the width (I am guessing its widht?) in  --container-XXXXX. 

Could someone help me with changing the width of this colored area?

![sideberry](https://user-images.githubusercontent.com/28295651/93940423-c133b080-fd2c-11ea-8740-48546253bb9f.png)

**Comment by ongots** [comment]
`.Tab .ctx {width: 10px}`
