### ISSUE TITLE
[Feature Request] allow mouse scrolling when mouse is over "native scroll bar" and  "switch tab with scroll whell" is activated

### ISSUE THREAD

**Issue by schmurtzm** [mbnuqw/sidebery#313]
It could be nice to change the behavior of the mouse wheel when the cursor is on the "native scroll bar" to interact with it instead of switching tabs. This will offer a fast way to switch between a long list of tabs.

![image](https://user-images.githubusercontent.com/7110113/95269308-6f654d00-0839-11eb-84a4-0b1811c04c72.png)

Actual behavior : 
According to the current settings, mouse wheel switch tabs or scroll in the "native scroll bar".

Desired behavior : 
An option to scroll in the "native scroll bar" with mouse wheel when the cursor is over this "native scroll bar".

Thank you for this awesome vertical tabs manager !

**Comment by mbnuqw** [comment]
Available in the latest version as a "Scroll area" option: Sidebery settings > Mouse > Switch tabs with scroll wheel > Scroll area width
