### ISSUE TITLE
"Ctrl + T" don't respect the automatic container affectation

### ISSUE THREAD

**Issue by schmurtzm** [mbnuqw/sidebery#316]
## Steps to reproduce
create a new panel,  choose a specific container for new tab. Then press "Ctrl + T" 

## Expected behavior
It should open a new tab in the specified container.

## Actual behavior
It opens a new tab not affected to a container.

## Environment info

OS:  WIN 10 
Firefox version:  81.0.1
Addon version:  4.9.0

**Comment by JessiAuro** [comment]
This is still an issue and is quite annoying.

As a work around for anyone who finds this issue opening new tabs with `Ctrl + Space` respects your panel container rules.

**Comment by mxmilkiib** [comment]
Clicking the burger menu then selecting "New tab" doesn't respect the automatic container feature either.

Middle clicking on the tab bar empty space does create a new tab with the correct container, though I most often use ctrl-t myself.

**Comment by mbnuqw** [comment]
Duplicate of #305
(workaround will be released with v5.0.0b32)
