### ISSUE TITLE
Customize styles of containers icons

### ISSUE THREAD

**Issue by firebbs** [mbnuqw/sidebery#32]
If I have many containers, I have to make a wide sidebar to see all the cons of containers, this is very inconvenient. 
Add please in "Appearence -> Edit styles" possibility to edit size of container icons, padding and possibility to hide "Create container" button.

**Comment by mbnuqw** [comment]
Right, I'll add ability to change styles (button size, colors, borders) of navigational strip.

About 'create container' button - this button is automatically hidden if there is no space for it, so I don't think that adding special option for it is really needed.

Also, I was thinking about wrapping containers buttons into multi-row layout that they were constantly visible ... (but I can't remember why I didn't add this setting :smile:), so maybe this option is more suitable for your case, what do you think?

**Comment by firebbs** [comment]
`About 'create container' button - this button is automatically hidden if there is no space for it`
Yes, it automatically hidden, but if I click on rightmost container icon, then 'create container' button will appear, and the first containers icon will be hidden if there is no space for it.

Possibility to make containers buttons into multi-row layout is good option I think.

**Comment by mbnuqw** [comment]
> and the first containers icon will be hidden
ah, got it, ok, I'll add this option too

**Comment by mbnuqw** [comment]
Implemented in the latest version. You can change the width/height of buttons in navigation, use multi-line layout, hide "new container" and settings buttons and hide buttons of empty containers.
