### ISSUE TITLE
Use flatten on expanded branches

### ISSUE THREAD

**Issue by superuser-does** [mbnuqw/sidebery#320]
## Description
I like Flatten, but would like to use it when tab branches have been expanded. To be, a branch is a branch whether expanded or collapsed.

Currently it is greyed out unless the tabs are collapsed. I would like to remove this restriction to have more consistent behaviour with Flatten.

**Comment by mbnuqw** [comment]
To select the whole branch in unfolded state, right click on the favicon (expand icon). Then, click on flatten menu item, which will flatten selected branch.
