### ISSUE TITLE
add context menu to refresh tabs of tree/group

### ISSUE THREAD

**Issue by GeoHickle** [mbnuqw/sidebery#321]
## Description
the refresh button in context menu only refresh the tab itself, it would be great to having a button to refresh the tab itself and all its descendants.

**Comment by flexingtoohardouchie** [comment]
+1 on this. I'd really like to be able to bind unload to a keyboard shortcut, for example, so that I can select the tabs in either Sidebery or Firefox' native tab bar and press a keyboard shortcut instead of right-clicking and selecting unload.

**Comment by mbnuqw** [comment]
To select the whole branch in unfolded state, right click on the favicon (expand icon). Then, click on reload menu item, which will reload selected branch.
