### ISSUE TITLE
Unhandled URL

### ISSUE THREAD

**Issue by HenryTheVacuum** [mbnuqw/sidebery#323]
Having issues with Unhandled URL pages showing instead of the intended tab.

The actual URL is still available in the URL bar, but about:blank is messing with it?

moz-extension://34b827b0-a2f0-4694-bbf6-76bfa9a5d09d/url/url.html#about:blank#urlhttps://www.google.com

**Comment by btglr** [comment]
I have had this recurring problem too, and it's causing tabs to silently disappear when Firefox is closed and reopened. Can you look into it @mbnuqw?

**Comment by KetanBasi** [comment]
![image](https://user-images.githubusercontent.com/23256673/126485738-9c1bd758-8ef6-4a97-85f8-c2a3c826a827.png)
Restoring from snapshots always gives me this problem too

**Comment by ellidi** [comment]
This is still a problem :/

**Comment by 2ndemosthenes** [comment]
I have this problem too, any way to solve it?

**Comment by albino1** [comment]
Edit: I moved to v5, everything seems to be working fine now.

**Comment by koppor** [comment]
I think, the issue reported at https://github.com/mbnuqw/sidebery/issues/323#issuecomment-1096297415 also effects the way tabs are restored when pressing <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>N</kbd>. - When accidently closing a window with grouped tabs, the whole hierarchy is lost in v5 as of today.

**Comment by mbnuqw** [comment]
Should be fixed in the latest version. Please, reopen if the issue is reproduced in the latest version of Sidebery.
