### ISSUE TITLE
Alphabetize tabs feature request

### ISSUE THREAD

**Issue by mlissner** [mbnuqw/sidebery#328]
I do work sometimes where I have to open a lot of very similar tabs; sometimes dozens of them. It'd be great to have an option to select them all and then right click them and hit alphabetize. For me, alphabetizing could work via URL or via the HTML title. I imagine URL is easier. Would be a really nice feature (though probably a niche one).

**Comment by mbnuqw** [comment]
Implemented in v5.2.0: #643
