### ISSUE TITLE
[Feature Request] More actions for tab context menu

### ISSUE THREAD

**Issue by WhiteSp1rit** [mbnuqw/sidebery#329]
I've been using Tree Tabs addon for the longest time, and after trying Sidebery I noticed that it lacks a lot of functionality in the tab context menu, would be nice to have it:

- create new tab (configurable whether child or sibling tab) - this would probably be the easiest to implement
- expand / collapse tree
- expand / collapse all trees
- detach tab - removes it from the current tree and places it on the base level. Alternatively, it could be assigned to an already existing "Flatten" command when just one tab is selected (which is currently greyed out with 1 tab selected), don't even need a new menu entry  
- unload tree (unloads all tabs in the tree)
- reload tree
- close tree
- mute / unmute tree
- mute / unmute other tabs

**Comment by megamorphg** [comment]
These would be great. FYI, expand/collapse button and shortcuts are already there as well as close tree menu.

**Comment by mbnuqw** [comment]
Closing this as invalid - bunch of features in one issue.
Not planned / already exists:
- expand / collapse tree - not planned, as you can just click on the favicon (expand icon) to fold/unfold tree
- unload tree (unloads all tabs in the tree) - available, right click on the favicons (expand icon) to select the whole branch and open context menu, then click on the "Unload" option.
- reload tree - same
- close tree - same
- mute / unmute tree - same

Possible:
- create new tab - #1503 (created by you)
- expand / collapse all trees - no issue to track, but why not
- detach tab - no issue to track, but why not
