### ISSUE TITLE
lost all tabs, i leave sideberry

### ISSUE THREAD

**Issue by denemier** [mbnuqw/sidebery#330]
beacuse i couldnt enter snapshots area which was frozen everytime i tried, you guys need to add a feature so that snapshot files are saved into a directory if something goes wrong people should see latest snapshot export file so i can reinstall addon import my data

**Comment by denemier** [comment]
your snapshot system is actually very good  it dont know why the more ş have snapshots saved its more slower i think are you fetching all of them always or what, why not save as file in a directory

**Comment by denemier** [comment]
i hope you see this for version 5

**Comment by ongots** [comment]
Help > Export / Import

**Comment by denemier** [comment]
i am aware about export option but even after exporting and importing its almost impossible to enter the snapshots page, where i want to delete every snapshot because its too slow and only open the latest snapshot. maybe individual export feature?

**Comment by KerfuffleV2** [comment]
@denemier Late response but it seems like the export format is just JSON and pretty simple. A script to just nuke all but the last 5 or so snapshots and write out the change would be very simple. Do you have the capability to run a Python script? I could make one for you if you still need this.

**Comment by mbnuqw** [comment]
Closing this as stale.
