### ISSUE TITLE
Tabs Icons size

### ISSUE THREAD

**Issue by jenesui** [mbnuqw/sidebery#332]
I can't save the size of the icons tabs. I can zoom in with ctrl+wheelup but when firefox restarts, the size is reset.

**Comment by ongots** [comment]
This feature was introduced in Firefox 84
[https://bugzilla.mozilla.org/show_bug.cgi?id=1634556](url)

You can write in Bugzilla.
Or use custom css. For example:

```
.Tab .fav{
    width:20px;
    height:20px;
    margin:0 6px 0 7px}
```

But there you need to tinker so that everything is displayed perfectly

**Comment by mbnuqw** [comment]
Sidebery can't control zoom level. Workaround - Use style editor to change size of elements.
