### ISSUE TITLE
Extension removed from addons.mozilla.org?

### ISSUE THREAD

**Issue by domsch1988** [mbnuqw/sidebery#336]
I'm pretty sure i was able to install it just two days ago. Now, on a fresh install, i'm not able to find the extension on firefox's extension site. The Link in this repo's readme also leads to a removed site.

**Comment by strogonoff** [comment]
Can observe the same from here

**Comment by mbnuqw** [comment]
It seems so. Unfortunately, I forgot to answer the reviewer. I'll republish addon asap (today/tomorrow). Sorry :'(

**Comment by solarkraft** [comment]
There is a [thread on Mozilla's forums ](https://discourse.mozilla.org/t/what-happened-to-a-deleted-add-on-sidebery-but-any-other-add-on-as-well/74476) about the issue. 

What an idiotic response from their side.

**Comment by solarkraft** [comment]
In case you have a browser with the enabling (!!) of the installation of unsigned extensions enabled like Firefox Developer Edition or [Librewolf](https://librewolf.readthedocs.io/en/latest/) and trust that I'm not malicious you can manually install [my build of the extension package](https://transfer.sh/TC8Y6/sidebery-4.9.0.zip) while mbnuqw is taking care of Mozilla's silly business.

**Comment by mbnuqw** [comment]
Updated addon to [v4.9.1](https://github.com/mbnuqw/sidebery/releases/tag/v4.9.1) [amo](https://addons.mozilla.org/en-US/firefox/addon/sidebery/)
The issue was the wrong build of vue (with compiler with 'eval' calls) and that I didn't explain this to reviewer. So this this is fully my fault. Sorry again.
