### ISSUE TITLE
Font still too big with XXS size

### ISSUE THREAD

**Issue by Elementari** [mbnuqw/sidebery#339]
Hello, I am using Sideberry on Firefox on a Macbook Air (M1). When I set font size to XXS, it is still very big. I often use 100+ tabs. Could you please allow for considerably smaller font size, and also perhaps please reduce the distance between the tab lines and reduce the size of the favicons? This would enable a great overview of a large number of tabs. Thank you!!! Also please note that it is not clear for users if they should enable "paid for services" on paypal. When one sends a paypal donation, it will ask for a choice "services and goods / no services and goods". If one chooses no services, one has to pay 1 euro to paypal as a fee (from Europe).

**Comment by strogonoff** [comment]
Which display scaling do you use?

I have “Tabs font” set to `.88rem -apple-system, sans-serif` in Sidebery’s styles editor and it looks fine with 2x scaling.

**Comment by Elementari** [comment]
I have to apologize. It works perfectly and I am very impressed by your extension, thank you a LOT!!!

**Comment by strogonoff** [comment]
(I am not the developer, just another happy user. Glad if helped)
