### ISSUE TITLE
Ability to refresh/unload all tabs within a group

### ISSUE THREAD

**Issue by xlucas** [mbnuqw/sidebery#349]
First and foremost, thanks a lot for this great extension!

This is super useful to me and I really appreciate how well structured it is!
So easy to manipulate from the get-go and it turns out to be extremely efficient as you move to a more advanced setup. All of this without being drown in options of all kinds and convoluted descriptions 😄.

## Description

When I select "unload" on a group it seems that it unloads the "fake tab" that is used to hold the list of children tabs.

It would come in handy to be able to unload (but also reload) all tabs and their children inside a group, similarly to panels since it would offer a finer grain to what you can do inside those.

Probably relates to #321.

**Comment by mbnuqw** [comment]
It's possible to select whole branch by right-clicking on the favicon of the parent tab:

https://user-images.githubusercontent.com/6276694/112635469-ae29a680-8e5d-11eb-83b3-6687803f5af0.mp4

**Comment by xlucas** [comment]
Oh thanks 👍 
Indeed that's what I was looking for!
I guess we can close that one.
