### ISSUE TITLE
Copy links of selected tabs / group

### ISSUE THREAD

**Issue by realToadtoad** [mbnuqw/sidebery#355]
## Description
One feature that would be greatly helpful to me using this extension would be the ability to copy the links to the selected tabs (similar to this extension https://addons.mozilla.org/en-US/firefox/addon/copy-selected-tabs-to-clipboar/). This would make it easier to manage and share tabs with others.

One idea of how to implement it would be through a simple context menu option that gets the links to all of the tabs, and formats them for the clipboard. The other possible implementation would be through the group pages, allowing the user to copy all of the tabs in a group.

**Comment by mbnuqw** [comment]
It's already available via context menu (check context menu editor in settings)
To select multiple tabs you can use:
 - ctrl/shift + click
 - right-click selection (for non-native context menu): press right button on mouse and move cursor
 - right-click on the favicon of parent tab (to select whole branch)


https://user-images.githubusercontent.com/6276694/112628865-4ff8c580-8e55-11eb-9e99-b653e5c4e093.mp4

**Comment by realToadtoad** [comment]
Huh, I could have sworn I checked the context menu editor at least a couple times. Thanks!
