### ISSUE TITLE
Stop unload hided part of sidebar

### ISSUE THREAD

**Issue by OmTatSat** [mbnuqw/sidebery#356]
Actual behavior is before 16 seconds, Expected behavior is after in video below
https://drive.google.com/file/d/1-uEGojEQZ-ONmaCF9aNShC11gr_G-zoR/view?usp=sharing

## Environment info

OS:  win 10 x64
Firefox version:  68.12.0 esr x64
Addon version:  4.9.1

**Comment by ongots** [comment]
Look at the block   /*   Dynamic sidebar   */  в  userChrome.css
Нere https://github.com/ongots/firefox-sidebery-minimal-style

**Comment by OmTatSat** [comment]
> 
> 
> Look at the block /* Dynamic sidebar */ в userChrome.css
> Нere https://github.com/ongots/firefox-sidebery-minimal-style

Thank you! I can't managed to get it work from right side

But found out  how to fix it to work in my userChrome.css code

`
  :root {
  --sidebar-hover-width: 90px;
  --sidebar-visible-width: 400px;
}

#sidebar-box {
  position: relative !important;
  overflow-x: hidden !important;

  margin-left: -9px !important;
  transition: all 1s!important;
  min-width: var(--sidebar-hover-width) !important;
  max-width: var(--sidebar-hover-width) !important;
  
}

#sidebar-box:hover {
  margin-left: calc(var(--sidebar-visible-width) * -1 + var(--sidebar-hover-width) - 9px) !important;
  right: 99px !important;
  transition: all 0s!important;
  min-width: var(--sidebar-visible-width) !important;
  max-width: var(--sidebar-visible-width) !important;
  opacity: 1 !important;
  
  
}

#sidebar-box[sidebarcommand="Sidebery"] {
  overflow: hidden;
  min-width: 90px;
  max-width: 90px;
  transition: all 0.2s ease;
  border-right: 1px solid #0c0c0d;
  z-index: 2;
}

/*Expand to 400px on hover*/
#sidebar-box[sidebarcommand="treestyletab_piro_sakura_ne_jp-sidebar-action"]:hover,
#sidebar-box[sidebarcommand="treestyletab_piro_sakura_ne_jp-sidebar-action"] #sidebar {
  min-width: 400px !important;
  max-width: 400px !important;
  z-index: 1;
}

/*Expand to 400px on hover for sidebery*/
#sidebar-box[sidebarcommand="_3c078156-979c-498b-8990-85f7987dd929_-sidebar-action"]:hover,
#sidebar-box[sidebarcommand="_3c078156-979c-498b-8990-85f7987dd929_-sidebar-action"] #sidebar {
  min-width: 400px !important;
  max-width: 400px !important;
  z-index: 1;
}


`
