### ISSUE TITLE
Bookmark tab / tab tree

### ISSUE THREAD

**Issue by orzechow** [mbnuqw/sidebery#36]
Beautiful vertical tab plugin with tree style view!
I would use this plugin instead of Tree Style Tab if would have this feature:

Ability to save a whole tab tree as bookmarks, eg. by right click on the tab tree.

So, right now right click on a tab opens the context menu with entries like "Move to ..., Reopen in ..., Group, Pin, ...".
Another really handy entry would be "Bookmark this tab / tree".

For a single tab it would simply create a new bookmark. For a tab tree, it would create a bookmark folder with all the child tabs inside (with a folder structure respresenting the tab tree).

I use this feature in Tree Style Tab to manage sessions, that I can close and open later again.

**Comment by mbnuqw** [comment]
Thanks!
Yep, this feature is planned.
But for now you can create snapshots (in settings panel) to restore previous sessions.

**Comment by mbnuqw** [comment]
Now you can do that:

![Peek 2020-04-22 09-43](https://user-images.githubusercontent.com/6276694/79941454-c76fe900-847d-11ea-9806-646acf4f6307.gif)

**Comment by orzechow** [comment]
Very nice, thanks! I switched to sidebery now. Let's see if it can convince me better than "Tree Style Tab" ;)
