### ISSUE TITLE
Restoring of a snapshot results in tabs showin "aboout:blank#urlhttp..."

### ISSUE THREAD

**Issue by big-bigchen** [mbnuqw/sidebery#362]
Hi,

When I restore a sanpshot with some (~500 tabs) most of the tabs in my containers are not shown properly. Their title is shown as "about:blank#url" and then the stored url.
Also, the restoring takes a long time and takes abut 2-3 GB memory...
Wired, that...
Someone has an explanation to this?
Thanks!
Cheers,
PS using most recent FF and Sidebery release.

Otherwise: a very cool plugin in terms of tab organizing... Congrats!

![grafik](https://user-images.githubusercontent.com/29741545/111389636-9873ee80-86b1-11eb-9f8e-5502d53460b4.png)

**Comment by mbnuqw** [comment]
It's a workaround for https://bugzilla.mozilla.org/show_bug.cgi?id=1581872
When you activate these tabs, they got normal url.

**Comment by mbnuqw** [comment]
Should be fixed from Firefox v113
