### ISSUE TITLE
Prevent tab creation on panel icon click

### ISSUE THREAD

**Issue by jbonjean** [mbnuqw/sidebery#363]
## Description
I find myself accidentally creating new tabs when switching between panels using the top icon, is it currently possible to disable this behavior? Thanks.

**Comment by mbnuqw** [comment]
No, unfortunately, there is no way to disable this behavior right now, but it will be configurable in next major version.

**Comment by goodboy** [comment]
👍🏼 here.

**Comment by mbnuqw** [comment]
Now considering it as a UX bug. I'll fix it in next patch version.

**Comment by mbnuqw** [comment]
Fixed in the latest version
