### ISSUE TITLE
Easily close a pinned tab?

### ISSUE THREAD

**Issue by mwoffenden** [mbnuqw/sidebery#37]
I'd like to be able to close a pinned tab (without having to unpin it first).  Is there an option to do this?

**Comment by mbnuqw** [comment]
Thank for opening this issue. Currently, you can use middle click or keyboard shortcut.

I will add close button for pinned tabs with titles.

**Comment by mwoffenden** [comment]
I was thinking of an "over-ride" option, that is, if a tab is pinned, the close button still appears.

**Comment by mbnuqw** [comment]
I've just publish new version of sidebery with fix (if I understand you correctly) of this issue, so you can check it in version 2.4.0.

**Comment by mwoffenden** [comment]
Just updated and it works great.  So much easier to use.
