### ISSUE TITLE
Keyboard shortcut for pinning/unpinning tab

### ISSUE THREAD

**Issue by Iss-in** [mbnuqw/sidebery#370]
## Description
It will be really nice to have a keyboard shortcut for this , I used to have another extension for this specific task, but somewhy on pinning the tab,  sideberry automatically get switched to first panel from current panel after pinning the tab.

      chrome.commands.onCommand.addListener(function(action) {

      if (action == "toggle-pin-tab") {

        chrome.tabs.query({currentWindow: true, active: true,}, function(foundTabs) {

          var currentTabId = foundTabs[0].id

          chrome.tabs.get(currentTabId, function(currentTab){

            const toggledValue = !currentTab.pinned;

            chrome.tabs.update(currentTabId, {pinned: toggledValue});

          });

        });

      }

    });

this is the basic code used by the extension, if it helps

edit : it might be a bug instead, even simple pinning of tab by dragging or via context menu is bringing me to first panel after pinning operation

**Comment by mbnuqw** [comment]
Resolved in v5.0.0
