### ISSUE TITLE
switch to previous active tab?

### ISSUE THREAD

**Issue by ahahahaah** [mbnuqw/sidebery#374]
## Description
hello
in the tabs section of the settings there is "activate last active tab on pannel switching" (in my case off / on choices doesnt change anything but its not the object of the topic :p), is it possible to add "active last active tab on active tab clicking"?

it could be useful if u want to swith several times between 2 tabs that are not neighbour.
is it possible?

**Comment by mbnuqw** [comment]
Yes, reasonable feature, will add.
Since #357 already exists I'm closing this issue as a duplicate.
