### ISSUE TITLE
"middle clic on tab" choice

### ISSUE THREAD

**Issue by ahahahaah** [mbnuqw/sidebery#376]
## Description
in the "mouse" section of the settings i see that there is no "middle clic on tab" choice.
it could allow more possible actions if you add it ;)

oh, and about the actions to select, why not display them in a dropdown/combo box? (this is not important, just aesthetic)
thx :D

**Comment by mbnuqw** [comment]
Implemented. For specific actions that could be bound to this event, open new feature requests.
