### ISSUE TITLE
Provide option to hide unwanted containers for context menu 

### ISSUE THREAD

**Issue by 31j** [mbnuqw/sidebery#384]
## Description

Specifically, I'd like to hide all containers with the label "tmp" (made from temporary containers extension), as I'd never want to reopen in a specific temporary container. That way only actual container tabs are shown in the context menu. 

This is possible with the default context menu, albeit via userChrome.css, I was hoping it would be possible without this.

**Comment by 31j** [comment]
This is already implemented, somehow skimmed passed it. Apologies

**Comment by JTBrinkmann** [comment]
For anyone looking for it, its right at the top of the sidebery settings page (under _Context menu > Ignore containers_).
