### ISSUE TITLE
Custom themes

### ISSUE THREAD

**Issue by mbnuqw** [mbnuqw/sidebery#39]
Add editor for customizing all css styles.
It should be a separate page with examples, list of all available css selectors and textarea for styles.

**Comment by Jipok** [comment]
In my opinion the use of colors from the firefox theme or the system theme is much more necessary. Because it is already configured and certainly suits the user.

**Comment by mbnuqw** [comment]
Implemented in the latest version.

**Comment by dufferzafar** [comment]
Sidebery by default has dark theme. Any way to quickly set it  to be a light theme?

**Comment by mbnuqw** [comment]
@dufferzafar, right now you can only manually set light theme in sidebery settings.

I don't remember why I didn't follow @Jipok's advice :man_facepalming:, but I'll definitely add an option "auto" to use the current system style. This will prevent the blinking behavior.
Issue to track - #184

**Comment by dufferzafar** [comment]
By manually, you mean edit all the colors by hand etc? Or is there an easier way?

**Comment by mbnuqw** [comment]
Option "style" in settings
![screenshot-2020-03-31 21:03:44_002](https://user-images.githubusercontent.com/6276694/78048955-e2c26980-7393-11ea-86ad-9574a74756ae.png)
