### ISSUE TITLE
[Feature Request] - Highlight currently selected panel 

### ISSUE THREAD

**Issue by schmurtzm** [mbnuqw/sidebery#398]
## Description / actual behavior
It is really difficult to distinguish the currently selected panel so I make often mistake (I click on the currently selected panel so often it opens a new tab that I don't need). It is probably possible to extend the CSS (because I see a very light difference on the selected one)

## Desired behavior: 
Be able to select background color of the currently selected panel.

![image](https://user-images.githubusercontent.com/7110113/118550900-908e0480-b75d-11eb-82ea-65bd333d10f1.png)

**Comment by schmurtzm** [comment]
I finally find a way thanks to [the great CSS source from dlim28](https://github.com/dlim28/sideberry-css) : 

```
/* Start Panel Button styling */
.panel-btn[data-active="true"] svg {
 background-color: red;
}
/* End Panel Button styling */
```
(copy and paste it to the Sidebar stylesheet in the Styles editor)

I let it opened because I think that the default behavior should highlight more the current panel or an option could be offered in the option menu.

Thanks for this awesome extension.

**Comment by moapwr** [comment]
idk but my version (4.9.4) already does this 
![image](https://user-images.githubusercontent.com/33654027/119659421-6eb41200-be2e-11eb-856b-766e38d9d8c3.png)

can this PR be closed?

**Comment by mbnuqw** [comment]
Closing this as workaround exists.

**Comment by iFreilicht** [comment]
The suggested workaround looks quite janky IMO, as it only covers the area of the icon, not the padding around it. There is actually a CSS variable for this color (`--nav-btn-activated-bg`), and in my case I wanted it to be the same as the highlight color of the currently active tab, so I just set it like this:

```css
#root {
  --nav-btn-activated-bg: var(--tabs-activated-bg) !important;
}
```

It won't work without `!important`, and the variable only exists in v4.x, not v5. However, from what I understand, the fixes in v5 will make this workaround unnecessary.
