### ISSUE TITLE
What does "Auto hide context menu" do ?

### ISSUE THREAD

**Issue by haoadoresorange** [mbnuqw/sidebery#403]
I'm sorry if this is not the right place to ask. What does the option "Auto hide context menu" do exactly ? It seems having no effect whether I turn it on or off.

**Comment by mbnuqw** [comment]
It hides context menu after the cursor leave it (with some delay). It was added long long time ago (when I actively experiment with the context menu) and currently its useless, so this option is a candidate for removal.
