### ISSUE TITLE
auto theme font color

### ISSUE THREAD

**Issue by kushraj** [mbnuqw/sidebery#404]
If the appearance is set to auto, tab title color isn't picking its color from either of data-style , it changes only if I define the color variable in root itself.
no mater what `color2` and `color3` are, fg color in auto theme mode is always `color1`

    #root {
        fg : color1;
    }

    #root[data-style="light"] {
        fg:color2;
    }

    #root[data-style="dark"] {
        fg:color3;
    }
OS: linux
Firefox: 88.0.1
Addon: 4.9.4

any help on where exactly auto theme mode is picking its colors from ?

**Comment by ongots** [comment]
[Sample](https://github.com/ongots/firefox-sidebery-minimal-style/blob/main/SideberySidebar.css)

**Comment by mbnuqw** [comment]
You need to use "prefers-color-scheme" media queries with attribute `data-style="auto"`.
```css
/* Style 'auto' and system with dark theme (or not supported) */
#root[data-style="auto"] {
  @media (prefers-color-scheme: dark), (prefers-color-scheme: no-preference) {
    /* dark style vars */
  }
}

/* Style 'dark' and system with any theme */
#root[data-style="dark"] {
  /* dark style vars */
}

/* Style 'auto' and system with light theme */
#root[data-style="auto"] {
  @media (prefers-color-scheme: light) {
    /* light style vars */
  }
}

/* Style 'light' and system with any theme */
#root[data-style="light"] {
  /* light style vars */
}
```

**Comment by kushraj** [comment]
So I tried this, and still having an issue with auto in appearance and dark theme in firefox/system
```
#root[data-style="auto"] {
  @media (prefers-color-scheme: dark), (prefers-color-scheme: no-preference) {
    --fg-primary: #ffffff;
  }
}

#root[data-style="dark"] {
    --fg-primary: #ffffff;
}

#root[data-style="auto"] {
  @media (prefers-color-scheme: light) {
    --fg-primary: #222222;
  }
}

#root[data-style="light"] {
    --fg-primary: #222222;
}


.Tab .title {
    color: var(--fg-primary);
}


.Tab[data-active="true"]  .title {
    color: var(--fg-primary);
}

```

The font color is  black with dark background ( on inactive tabs ). happens only with auto option in appearance, both light and dark theme options works fine separately


![image](https://user-images.githubusercontent.com/36916613/120090158-f09d8700-c11d-11eb-92b2-ba0d6f1f0e04.png)

**Comment by kushraj** [comment]
i can't change the font color no matter what i do, @mbnuqw @ongots any help here pls

**Comment by ongots** [comment]
```
@media (prefers-color-scheme:dark),(prefers-color-scheme: no-preference){
	#root[data-style="auto"],
	#root[data-style="dark"]{
	
	--fg-primary: red;
	
}}


@media (prefers-color-scheme:light){
	#root[data-style="auto"],
	#root[data-style="light"]{
	
	--fg-primary: blue;
	
}}


.Tab .title {
    color: var(--fg-primary);
}


.Tab[data-active="true"]  .title {
    color: var(--fg-primary);
}
```

**Comment by isshin1** [comment]
so this got borked in latest update , @ongots same for you ?

**Comment by ongots** [comment]
#root[data-frame-color-scheme=dark] {

}

#root[data-frame-color-scheme=light] {

}
