### ISSUE TITLE
Auto-open Sidebery as default sidebar on new windows

### ISSUE THREAD

**Issue by shervinsahba** [mbnuqw/sidebery#405]
It'd be nice to open a new Firefox tab and have Sidebery already open in the sidebar. 

As is, Sidebery is not opened by default and requires Ctrl+e. This makes the right-click->"Move to new window" context menu option open the moved page underneath a blank page for me, only loading it after Ctrl+e.

Is auto-opening Sidebery a feature that I missed in the Sidebery options, or is it an option best relegated to userChrome CSS (and if so, what's the appropriate way to access it?). Thanks.

**Comment by mbnuqw** [comment]
This cannot be controlled from the addon. Firefox (in most cases (at least for me)) opens the sidebar in a new window if the sidebar was already open in the previous window. Sometimes it doesn't work and unfortunately I don't know of any workaround.

**Comment by mbnuqw** [comment]
Closing as this is not possible to implement and there is no workaround.

**Comment by clb92** [comment]
Is it just me, or does this seem to work fine now? My sidebar is automatically open in new windows now.

I'm guessing this is a result of Firefox working to implement vertical tabs themselves.

**Comment by D3SOX** [comment]
You are right but private windows are still an issue. Hope there is a workaround now by somehow forcing the sidebar?

**Comment by clb92** [comment]
It opens automatically for me in private windows too. Did you set "Run in Private Windows" to "Allow" under Add-ons and themes?

**Comment by shervinsahba** [comment]
It's been a while since I posted the original issue, but my guess now is that I mistakenly wrote "new Firefox tab" when I meant "new Firefox window" in the original post.

To see what I mean, right click a tab you already have open and choose "Move to new window". The behavior I see is that the moved tab's new window does not have Sidebery open. 

Similarly, Ctrl+Shift+P for a new private window shows no Sidebery at first. (But for some reason Ctrl+N for a new blank window does open Sidebery).

In any case, not a big issue :)

**Comment by clb92** [comment]
Weird, because it just works for me, also when moving an open tab to a new windows, like you describe. Perhaps it could be something specific to your Firefox setup, or a conflicting addon or something? I hope you find a solution :)

**Comment by D3SOX** [comment]
> It opens automatically for me in private windows too. Did you set "Run in Private Windows" to "Allow" under Add-ons and themes?

Sure otherwise I wouldn't even have access to Sideberry in private windows
