### ISSUE TITLE
Automatic/Scheduled export

### ISSUE THREAD

**Issue by hoijui** [mbnuqw/sidebery#408]
Just like the scheduled storage, but in JSON format, to a local (file-system) directory, which can be set in the settings.
The main reason for this feature for me, is to be able to _trust_.
It happened to me with many session and tabs manager plugins, that ... something happened, and then all was gone. And one can see comments of such things in the reviews of all the plugins. it is basically the main problem of this trade, in my eyes.

This would allow backing up the sessions through any backup utility, and as it is a clear text format that is easy to understand and parse, one also does not have to fear your plugin going extinct or incompatible with browser updates or anything like that, as the data would still be there and usable.
There could even be a simple HTML-Bookmarks-page version of the export, which would be usable by anyone, even without scripting abilities, or with fear of notepad.

**Comment by Heyian** [comment]
@mbnuqw Unless I'm mistaken, the snapshot export function solves this issue. I suggest we close this issue.

**Comment by mbnuqw** [comment]
Hm... it seems I was thinking about auto export of all data of Sidebery (settings > Help > Export). Now, after re-reading the original post, it's clearly about the snapshots.
