### ISSUE TITLE
Add support for tab visibility.

### ISSUE THREAD

**Issue by ademlabs** [mbnuqw/sidebery#414]
Would be cool to have Panorama Tab Groups working with Sidebery like it does for Treestyle Tabs. Having only the actively selected tab group visible would have been awesome for productivity.

**Comment by botatoKDE** [comment]
FWIW, you can do similar to this already with a couple of settings. Maybe even exactly the same (I haven't used Panorama to compare).

    Settings>Tabs>Hide tabs of inactive panels>on
will hide all tabs the current panel you're using.

      Settings>Tabs Tree>Hide folded tabs>on
        Auto fold tabs>on
          Except the last active branches>none
will make it so that only the tree you're using (and orphaned tabs) will be visible!

**Comment by mbnuqw** [comment]
Closing this as implemented.
