### ISSUE TITLE
Change Color of Active Panel in Navigation Bar

### ISSUE THREAD

**Issue by Nano-Ocelot** [mbnuqw/sidebery#415]
I'm not sure if this is an option in the style editor that I missed somehow but I would like a way to change the color of the active panel in the navigation bar as well as the line separating the navigation bar from the panel of tabs below it. I've attached a screenshot and highlighted the area I'm talking about in red.
![Screenshot_20210610_210231](https://user-images.githubusercontent.com/34014750/121616164-5cda8d80-ca30-11eb-9d21-debd24f7bcb5.png)

**Comment by Red-Eagle-LXIX** [comment]
This should help.  It adds a border around the active panel with a slight highlight.  It also highlights the hovered panel better and adds a brighter border on hover.
![SideberyPanelButtons](https://user-images.githubusercontent.com/16145736/126876523-939d1259-523a-4f24-8cc2-3f920a4d23b1.jpg)

Open Sidebery Settings
Goto Styles Editor
```
.NavigationBar .panels-box .panel-btn:hover{
  border: 1px solid #ffff00ff;
  background-color: #ffff0030 !important;
}
.NavigationBar .panels-box .panel-btn[data-active="true"]{
  border: 1px solid #0080ffff;
  background-color: #ffff0014 !important;
}
.NavigationBar .panels-box .panel-btn[data-active="true"]:hover{
  border: 1px solid #80ff00ff;
  background-color: #ffff0060 !important;
}
```

**Comment by Nano-Ocelot** [comment]
Thanks! That's a big help. Is there any way to style the separator there too? Or any way to inspect ui elements to find out what it is. If so I can probably figure it out on my own. I just don't know how to inspect ui elements of firefox itself.

**Comment by Red-Eagle-LXIX** [comment]
This is the only other thing I did for that area that you can try:
Open Sidebery Settings
Goto Styles Editor
Navigation Strip
Turn Button Height on, set value to 28px or even 26px.
Default is 32px I think.

**Comment by Nano-Ocelot** [comment]
Oh, I figured out how to inspect extensions finally. And if anyone stumbles on this, you can add this line to edit the separator. `#root[data-nav-layout="horizontal"] .NavigationBar, #root[data-nav-layout="hidden"] .NavigationBar {
  box-shadow: inset 0 -1px 0 0 #a422ad,0 0 12px 0 rgba(0,0,0,0);
}`

**Comment by mbnuqw** [comment]
Closing this as workaround exists.
