### ISSUE TITLE
Move tabs with matched urls doesn't seem to work

### ISSUE THREAD

**Issue by mike-apiabroad** [mbnuqw/sidebery#416]
## Steps to reproduce
Add a url to "move tabs with matched urls" in the panel settings

## Expected behavior
all tabs that match that pattern should be moved to that panel

## Actual behavior
Nothing happens at all

## Environment info
OS:  
Firefox version:  89
Addon version:  4.9.4

Perhaps I am just putting the url in incorrectly but i'm not sure how to say "all tabs for aws go to this panel" and use "aws.amazon.com" as the domain match. Does this require regex or am I missing something? Even with a full url it doesn't work.

Thanks!

**Comment by kaizio** [comment]
Definitely could use some documentation, I ran into the same issue. After looking at the [code](https://github.com/mbnuqw/sidebery/blob/f1c784a49882f96c478d7d8ca9b2bf0a9c08d7c9/src/actions/panels.js#L94) you need to start and end with a '/' which makes since if you look up the doc for [js regex](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions). Just not common requirement with most programs, but awesome addon!

**Comment by a-stangl** [comment]
@kaizio Regex Syntax also does not work for me even though my regex patterns seem to be correct

**Comment by kaizio** [comment]
What are you using?

**Comment by acheronfail** [comment]
Can confirm that using something like `/github.com/` works for all github links, etc

**Comment by a-stangl** [comment]
Works for me now. Could be that my regex patterns were just too complicated (even though I tested them via `window.location.toString().match(<PATTERN>)`).  🤷🏻‍♂️

**Comment by alexander-paterson** [comment]
Just to add my 2 cents. I can't get this to work either.

I tried to create two panels, one for YouTube and one for Reddit.

On the YouTube panel I put the following `/youtube.com/` and on the Reddit panel the following `/reddit.com/` however, and I haven't done extensive testing it looked like every tab was being grabbed by the first additional panel I created, which was YouTube in my case.

No matter where I opened a Reddit tab, it always opened in the YouTube panel.

**Comment by VBoudry** [comment]
Adding my comments here:
I make it work using the above formatting, and having one URL per line.

BUT after an addition, any URL will be matched to the last edited panel and back again where it was opened in an endless loop of displacing the tab between the 2 panels. Except if you open it in that last edited one.
Restarting the browse solves the issue: the behaviour is then correct.

So it seems there is an issue on the implementation: having a button/menu item correctly adding a domain could be a first step.

**Comment by k4rli** [comment]
Works well like `/(google.com|example.com)/` but it should be documented that regex is expected, not space or comma separated urls.

**Comment by mbnuqw** [comment]
Closing this as stale. Please, reopen if issue is reproduced in the latest version of Sidebery.
