### ISSUE TITLE
Closing all tabs in a tree by closing only the tree/group tab

### ISSUE THREAD

**Issue by zagliv** [mbnuqw/sidebery#418]
I looked thoroughly in every settings section but didn't find a way to close every tab in a tree by just closing the group or  parent tab.

**Comment by ongots** [comment]
Right click on the parent tab icon

**Comment by zagliv** [comment]
Thanks, it helped me! But I would like to see some more self-explanatory way to do this. For example, additional button "close every tab in this tree" in context menu. I think it would be more convenient for new users rather than forcing them to figure it out by googling.
