### ISSUE TITLE
The cursor does not appear in the address bar when opening a new tab by with a double click

### ISSUE THREAD

**Issue by mjsan** [mbnuqw/sidebery#424]
## Steps to reproduce
Double click the side bar to open a new tab.

## Expected behavior
New tab opened has the cursor in the address bar.

## Actual behavior
Cursor is not in the address bar 

## Environment info

OS:  MacOS Big Sur 11.4
Firefox version:  89
Addon version:  4.9.4

**Comment by mbnuqw** [comment]
Closing this as stale. Please, reopen if issue is reproduced in the latest version of Sidebery.
