### ISSUE TITLE
sidebar.html fails to initialise if you have only one panel

### ISSUE THREAD

**Issue by 00dani** [mbnuqw/sidebery#427]
By default, Sidebery has two panels: the bookmarks panel and a default tabs panel. On startup, if no panel has been selected, Sidebery defaults to the panel at index 1, as you can see here:
https://github.com/mbnuqw/sidebery/blob/bbd90548afe76db40c3923cf083c51d2a40be3ab/src/sidebar/actions/tabs.js#L26

If you turn the bookmarks panel *off* as I did (since I use Buku) and therefore only have one panel, then a TypeError is thrown from that code, because there is no panel at index 1. If you also turn off the navigation bar because you only have one panel  anyway (as I did), then Sidebery appears to be "stuck" with a completely empty sidebar.html and you can't do anything.

Sidebery should probably try looking for a panel at index 0 if it can't find one at index 1. I don't think it's possible to have exactly *zero* panels defined, so that case shouldn't be a problem.

**Comment by mbnuqw** [comment]
Closing this as stale. Please, reopen if issue is reproduced in the latest version of Sidebery.
