### ISSUE TITLE
Drag tab to a parent tab is wonky; "Drag and Drop" in settings have hover, but no drag & drop.

### ISSUE THREAD

**Issue by yeru83** [mbnuqw/sidebery#429]
## Steps to reproduce
At first I thought - maybe the new tab needs to finish loading first.  Nope.  Anyway, TreeStyleTabs allowed me to open a new tab, type a destination in the address bar, and drag+drop it to its parent while waiting for the tab to load.  Yes, my internet is that slow.  

## Expected behavior
Here, even after waiting, 70% of the time dragging the tab to the new parent does not function.
Dragging a parent tab in one movement together with its child tabs doesn't work hardly ever.

## Actual behavior
I click on the tab, pause while clicked, start moving it towards the intended parent, wait for the green triangle to replace the green horizontal line, and drop the tab.  Nothing happens usually.  I see that sometimes the horizontal line marker is to place the tab at a new spot on the "ladder" without "childing" it; but that hardly works right either.

## Environment info

OS:  mac
Firefox version:  89.0
Addon version:  4.9.4

<details><code>
{
  "settings": {
    "version": "4.9.4",
    "nativeScrollbars": false,
    "selWinScreenshots": true,
    "tabsCheck": true,
    "tabsFix": "notify",
    "markWindow": false,
    "markWindowPreface": "[Sidebery] ",
    "ctxMenuNative": false,
    "autoHideCtxMenu": "none",
    "ctxMenuRenderInact": true,
    "ctxMenuIgnoreContainers": "",
    "navBarLayout": "horizontal",
    "navBarInline": true,
    "hideAddBtn": false,
    "hideSettingsBtn": false,
    "navBtnCount": true,
    "hideEmptyPanels": true,
    "navMidClickAction": "none",
    "navSwitchPanelsWheel": true,
    "groupLayout": "grid",
    "skipEmptyPanels": false,
    "dndTabAct": true,
    "dndTabActDelay": 750,
    "dndTabActMod": "none",
    "dndExp": "pointer",
    "dndExpDelay": 0,
    "dndExpMod": "none",
    "stateStorage": "global",
    "warnOnMultiTabClose": "collapsed",
    "activateOnMouseUp": true,
    "activateLastTabOnPanelSwitching": true,
    "showTabRmBtn": true,
    "showTabCtx": true,
    "hideInact": false,
    "activateAfterClosing": "next",
    "activateAfterClosingPrevRule": "visible",
    "activateAfterClosingNextRule": "tree",
    "activateAfterClosingGlobal": false,
    "activateAfterClosingNoFolded": true,
    "activateAfterClosingNoDiscarded": true,
    "shiftSelAct": true,
    "askNewBookmarkPlace": true,
    "tabsRmUndoNote": true,
    "nativeHighlight": false,
    "tabsUnreadMark": false,
    "tabsReloadLimit": 5,
    "tabsReloadLimitNotif": true,
    "moveNewTabPin": "start",
    "moveNewTabParent": "last_child",
    "moveNewTabParentActPanel": false,
    "moveNewTab": "end",
    "pinnedTabsPosition": "panel",
    "pinnedTabsList": false,
    "pinnedAutoGroup": false,
    "tabsTree": true,
    "groupOnOpen": true,
    "tabsTreeLimit": "none",
    "hideFoldedTabs": false,
    "autoFoldTabs": false,
    "autoFoldTabsExcept": "none",
    "autoExpandTabs": false,
    "rmChildTabs": "folded",
    "tabsChildCount": true,
    "tabsLvlDots": false,
    "discardFolded": true,
    "discardFoldedDelay": 5,
    "discardFoldedDelayUnit": "min",
    "tabsTreeBookmarks": true,
    "treeRmOutdent": "first_child",
    "bookmarksPanel": true,
    "warnOnMultiBookmarkDelete": "collapsed",
    "openBookmarkNewTab": true,
    "midClickBookmark": "open_new_tab",
    "actMidClickTab": true,
    "autoCloseBookmarks": false,
    "autoRemoveOther": false,
    "highlightOpenBookmarks": false,
    "activateOpenBookmarkTab": false,
    "showBookmarkLen": false,
    "bookmarksRmUndoNote": true,
    "fontSize": "xxs",
    "bgNoise": false,
    "animations": true,
    "animationSpeed": "norm",
    "theme": "tactile",
    "style": "dark",
    "sidebarCSS": false,
    "groupCSS": false,
    "snapNotify": true,
    "snapExcludePrivate": false,
    "snapInterval": 0,
    "snapIntervalUnit": "min",
    "snapLimit": 0,
    "snapLimitUnit": "snap",
    "hScrollThroughPanels": false,
    "scrollThroughTabs": "panel",
    "scrollThroughVisibleTabs": true,
    "scrollThroughTabsSkipDiscarded": true,
    "scrollThroughTabsExceptOverflow": true,
    "scrollThroughTabsCyclic": false,
    "tabDoubleClick": "new_child",
    "tabLongLeftClick": "none",
    "tabLongRightClick": "new_child",
    "tabsPanelLeftClickAction": "none",
    "tabsPanelDoubleClickAction": "tab",
    "tabsPanelRightClickAction": "expand",
    "tabsPanelMiddleClickAction": "tab",
    "syncName": "",
    "syncSaveSettings": false,
    "syncSaveCtxMenu": false,
    "syncSaveStyles": false,
    "syncAutoApply": false
  },
  "permissions": {
    "allUrls": false,
    "tabHide": false,
    "actualAllUrls": false,
    "actualTabHide": false
  },
  "storage": {
    "size": "2.7 mb",
    "props": {
      "bookmarksMenu": "228 b",
      "bookmarksPanelMenu": "58 b",
      "expandedBookmarks": "97 b",
      "favAutoCleanTime": "10 b",
      "favUrls": "61 kb",
      "favicons": "2.4 mb",
      "panelIndex": "1 b",
      "panels_v4": "446 b",
      "prevTabsData_v4": "94.4 kb",
      "profileID": "14 b",
      "settings": "2.7 kb",
      "tabsData_v4": "118.7 kb",
      "tabsMenu": "308 b",
      "tabsPanelMenu": "184 b"
    }
  },
  "panels": [
    {
      "type": "bookmarks",
      "id": "bookmarks",
      "cookieStoreId": "bookmarks",
      "name": 9,
      "icon": "...",
      "bookmarks": true,
      "lockedPanel": false,
      "skipOnSwitching": false
    },
    {
      "type": "default",
      "id": "firefox-default",
      "name": 7,
      "icon": "...",
      "cookieStoreId": "firefox-default",
      "lockedTabs": false,
      "lockedPanel": false,
      "skipOnSwitching": false,
      "noEmpty": false,
      "newTabCtx": "none",
      "dropTabCtx": "none",
      "moveTabCtx": "none",
      "moveTabCtxNoChild": true
    }
  ],
  "containers": [],
  "cssVars": "TypeError: can't convert undefined to object",
  "windows": [
    {
      "state": "normal",
      "incognito": false,
      "tabsCount": 29
    },
    {
      "state": "normal",
      "incognito": false,
      "tabsCount": 49
    },
    {
      "state": "minimized",
      "incognito": false,
      "tabsCount": 47
    },
    {
      "state": "minimized",
      "incognito": false,
      "tabsCount": 3
    },
    {
      "state": "normal",
      "incognito": false,
      "tabsCount": 16
    },
    {
      "state": "normal",
      "incognito": false,
      "tabsCount": 19
    },
    {
      "state": "minimized",
      "incognito": false,
      "tabsCount": 12
    },
    {
      "state": "minimized",
      "incognito": false,
      "tabsCount": 4
    },
    {
      "state": "minimized",
      "incognito": false,
      "tabsCount": 10
    },
    {
      "state": "minimized",
      "incognito": false,
      "tabsCount": 26
    },
    {
      "state": "minimized",
      "incognito": false,
      "tabsCount": 14
    },
    {
      "state": "normal",
      "incognito": false,
      "tabsCount": 13
    },
    {
      "state": "minimized",
      "incognito": false,
      "tabsCount": 6
    },
    {
      "state": "normal",
      "incognito": false,
      "tabsCount": 110
    },
    {
      "state": "minimized",
      "incognito": false,
      "tabsCount": 11
    },
    {
      "state": "minimized",
      "incognito": false,
      "tabsCount": 10
    },
    {
      "state": "minimized",
      "incognito": false,
      "tabsCount": 3
    },
    {
      "state": "minimized",
      "incognito": false,
      "tabsCount": 24
    },
    {
      "state": "minimized",
      "incognito": false,
      "tabsCount": 30
    },
    {
      "state": "minimized",
      "incognito": false,
      "tabsCount": 24
    },
    {
      "state": "minimized",
      "incognito": false,
      "tabsCount": 7
    },
    {
      "state": "normal",
      "incognito": false,
      "tabsCount": 18
    },
    {
      "state": "normal",
      "incognito": false,
      "tabsCount": 7
    },
    {
      "state": "normal",
      "incognito": false,
      "tabsCount": 66
    },
    {
      "state": "normal",
      "incognito": false,
      "tabsCount": 16
    },
    {
      "state": "minimized",
      "incognito": false,
      "tabsCount": 22
    },
    {
      "state": "normal",
      "incognito": false,
      "tabsCount": 40
    },
    {
      "state": "minimized",
      "incognito": false,
      "tabsCount": 22
    },
    {
      "state": "minimized",
      "incognito": false,
      "tabsCount": 47
    },
    {
      "state": "normal",
      "incognito": false,
      "tabsCount": 4
    },
    {
      "state": "minimized",
      "incognito": false,
      "tabsCount": 9
    },
    {
      "state": "minimized",
      "incognito": false,
      "tabsCount": 7
    },
    {
      "state": "normal",
      "incognito": false,
      "tabsCount": 30
    },
    {
      "state": "minimized",
      "incognito": false,
      "tabsCount": 26
    },
    {
      "state": "normal",
      "incognito": false,
      "tabsCount": 1
    },
    {
      "state": "normal",
      "incognito": false,
      "tabsCount": 8
    },
    {
      "state": "normal",
      "incognito": false,
      "tabsCount": 7
    },
    {
      "state": "normal",
      "incognito": false,
      "tabsCount": 1
    },
    {
      "state": "normal",
      "incognito": false,
      "tabsCount": 1
    },
    {
      "state": "minimized",
      "incognito": false,
      "tabsCount": 48
    },
    {
      "state": "minimized",
      "incognito": false,
      "tabsCount": 1
    },
    {
      "state": "normal",
      "incognito": false,
      "tabsCount": 1
    },
    {
      "state": "normal",
      "incognito": false,
      "tabsCount": 77
    },
    {
      "state": "minimized",
      "incognito": false,
      "tabsCount": 19
    },
    {
      "state": "normal",
      "incognito": false,
      "tabsCount": 18
    },
    {
      "state": "normal",
      "incognito": false,
      "tabsCount": 11
    },
    {
      "state": "normal",
      "incognito": false,
      "tabsCount": 34
    },
    {
      "state": "normal",
      "incognito": false,
      "tabsCount": 42
    },
    {
      "state": "normal",
      "incognito": false,
      "tabsCount": 37
    },
    {
      "state": "normal",
      "incognito": false,
      "tabsCount": 6
    },
    {
      "state": "normal",
      "incognito": false,
      "tabsCount": 20
    }
  ],
  "tabsMenu": [
    [
      "undoRmTab",
      "mute",
      "reload",
      "bookmark"
    ],
    "separator-1",
    [
      {
        "name": "Move to"
      },
      "moveToNewWin",
      "moveToWin",
      "moveToPanel"
    ],
    [
      {
        "name": "Reopen in"
      },
      "reopenInNewWin",
      "reopenInWin",
      "reopenInCtr"
    ],
    "separator-2",
    "pin",
    "duplicate",
    "discard",
    "copyUrls",
    "separator-3",
    "group",
    "flatten",
    "separator-4",
    "clearCookies",
    "close"
  ],
  "bookmarksMenu": [
    [
      {
        "name": "Open in"
      },
      "openInNewWin",
      "openInNewPrivWin",
      "openInCtr"
    ],
    "separator-5",
    [
      "createBookmark"
    ],
    "createFolder",
    "createSeparator",
    "separator-6",
    "sortByName",
    "sortByLink",
    "sortByTime",
    "separator-7",
    "copyUrls",
    "edit",
    "delete"
  ],
  "bookmarks": {
    "bookmarksCount": 12978,
    "foldersCount": 930,
    "separatorsCount": 14,
    "maxDepth": 9
  }
}
</code></details>

**Comment by mbnuqw** [comment]
Closing this as stale. Please, reopen if issue is reproduced in the latest version of Sidebery.
