### ISSUE TITLE
A suggestion

### ISSUE THREAD

**Issue by gasman1844** [mbnuqw/sidebery#43]
I continue to appreciate your extension, it's brought be back to firefox, I've made a donation on the add-on page. One suggestion I'd like to ask is if it's possible in Styles to add the option to highlight a bookmark which is actually been clicked on and the page is open, similar to being able to highlight a folder which is currently open. Hope this makes sense.

**Comment by mbnuqw** [comment]
Thanks! Yes, this sounds reasonable. I can add option in settings to highlight opened bookmarks/+their parent folders path and add customizable styles.

**Comment by mbnuqw** [comment]
Implemented in the latest version.
