### ISSUE TITLE
Add setting not to follow a tab when it is moved to another panel

### ISSUE THREAD

**Issue by ErikSteiner** [mbnuqw/sidebery#431]
## Description
Is it possible to just use the right-click menu and move a tab to another panel, without following the tab to that panel?

**Comment by ErikSteiner** [comment]
I would like to add here that this problem mainly occurs for me when I have previously received many tabs from my phone. When I open the browser on my PC, all the tabs sent end up in the current panel. Moving the tabs without switching the panel only works as long as I move a tab via right-click menu that is not the active one.

**Comment by mbnuqw** [comment]
You can turn off this behavior by switching the "Switch panel after moving active tab to another panel" option in sidebery settings / Tabs section.

Please reopen if this does not help.
