### ISSUE TITLE
Unload doesn't work if selection/panel includes active tab

### ISSUE THREAD

**Issue by Yarn** [mbnuqw/sidebery#434]
## Steps to reproduce
open some tabs (and keep one of them active)

in sidebery either
-select all, right click -> unload
-right click panel -> unload tabs

## Expected behavior
unload all tabs in panel/selection besides the selected one

## Actual behavior
nothing happens

## Environment info

OS:  Linux
Firefox version:  89.0.2
Addon version:  4.9.4

<details><code>

{
  "settings": {
    "version": "4.9.4",
    "nativeScrollbars": false,
    "selWinScreenshots": false,
    "tabsCheck": true,
    "tabsFix": "notify",
    "markWindow": false,
    "markWindowPreface": "[Sidebery] ",
    "ctxMenuNative": true,
    "autoHideCtxMenu": "none",
    "ctxMenuRenderInact": true,
    "ctxMenuIgnoreContainers": "",
    "navBarLayout": "horizontal",
    "navBarInline": false,
    "hideAddBtn": true,
    "hideSettingsBtn": false,
    "navBtnCount": true,
    "hideEmptyPanels": false,
    "navMidClickAction": "none",
    "navSwitchPanelsWheel": true,
    "groupLayout": "list",
    "skipEmptyPanels": false,
    "dndTabAct": false,
    "dndTabActDelay": 750,
    "dndTabActMod": "none",
    "dndExp": "none",
    "dndExpDelay": 0,
    "dndExpMod": "none",
    "stateStorage": "global",
    "warnOnMultiTabClose": "any",
    "activateOnMouseUp": true,
    "activateLastTabOnPanelSwitching": false,
    "showTabRmBtn": false,
    "showTabCtx": true,
    "hideInact": false,
    "activateAfterClosing": "none",
    "activateAfterClosingPrevRule": "visible",
    "activateAfterClosingNextRule": "tree",
    "activateAfterClosingGlobal": false,
    "activateAfterClosingNoFolded": true,
    "activateAfterClosingNoDiscarded": true,
    "shiftSelAct": false,
    "askNewBookmarkPlace": false,
    "tabsRmUndoNote": true,
    "nativeHighlight": false,
    "tabsUnreadMark": false,
    "tabsReloadLimit": 5,
    "tabsReloadLimitNotif": true,
    "moveNewTabPin": "none",
    "moveNewTabParent": "none",
    "moveNewTabParentActPanel": false,
    "moveNewTab": "none",
    "pinnedTabsPosition": "panel",
    "pinnedTabsList": false,
    "pinnedAutoGroup": false,
    "tabsTree": true,
    "groupOnOpen": true,
    "tabsTreeLimit": "none",
    "hideFoldedTabs": false,
    "autoFoldTabs": false,
    "autoFoldTabsExcept": "none",
    "autoExpandTabs": false,
    "rmChildTabs": "none",
    "tabsChildCount": true,
    "tabsLvlDots": true,
    "discardFolded": false,
    "discardFoldedDelay": 0,
    "discardFoldedDelayUnit": "sec",
    "tabsTreeBookmarks": false,
    "treeRmOutdent": "first_child",
    "bookmarksPanel": true,
    "warnOnMultiBookmarkDelete": "any",
    "openBookmarkNewTab": true,
    "midClickBookmark": "open_new_tab",
    "actMidClickTab": false,
    "autoCloseBookmarks": false,
    "autoRemoveOther": false,
    "highlightOpenBookmarks": false,
    "activateOpenBookmarkTab": false,
    "showBookmarkLen": false,
    "bookmarksRmUndoNote": true,
    "fontSize": "xxs",
    "bgNoise": false,
    "animations": false,
    "animationSpeed": "fast",
    "theme": "default",
    "style": "dark",
    "sidebarCSS": false,
    "groupCSS": false,
    "snapNotify": true,
    "snapExcludePrivate": false,
    "snapInterval": 0,
    "snapIntervalUnit": "min",
    "snapLimit": 0,
    "snapLimitUnit": "snap",
    "hScrollThroughPanels": false,
    "scrollThroughTabs": "none",
    "scrollThroughVisibleTabs": false,
    "scrollThroughTabsSkipDiscarded": false,
    "scrollThroughTabsExceptOverflow": true,
    "scrollThroughTabsCyclic": false,
    "tabDoubleClick": "none",
    "tabLongLeftClick": "none",
    "tabLongRightClick": "none",
    "tabsPanelLeftClickAction": "none",
    "tabsPanelDoubleClickAction": "none",
    "tabsPanelRightClickAction": "menu",
    "tabsPanelMiddleClickAction": "none",
    "syncName": "",
    "syncSaveSettings": true,
    "syncSaveCtxMenu": true,
    "syncSaveStyles": true,
    "syncAutoApply": false
  },
  "permissions": {
    "allUrls": false,
    "tabHide": false,
    "actualAllUrls": false,
    "actualTabHide": false
  },
  "storage": {
    "size": "190.5 kb",
    "props": {
      "bookmarksMenu": "226 b",
      "bookmarksPanelMenu": "58 b",
      "cssVars": "1.7 kb",
      "disabledKeybindings": "724 b",
      "favAutoCleanTime": "10 b",
      "favUrls": "3.4 kb",
      "favicons": "163.3 kb",
      "panelIndex": "1 b",
      "panels_v4": "764 b",
      "prevTabsData_v4": "9 b",
      "profileID": "14 b",
      "settings": "2.7 kb",
      "tabsData_v4": "17 kb",
      "tabsMenu": "151 b",
      "tabsPanelMenu": "89 b"
    }
  },
  "panels": [
    {
      "type": "bookmarks",
      "id": "bookmarks",
      "cookieStoreId": "bookmarks",
      "name": 9,
      "icon": "...",
      "bookmarks": true,
      "lockedPanel": false,
      "skipOnSwitching": true
    },
    {
      "type": "default",
      "id": "firefox-default",
      "name": 7,
      "icon": "...",
      "cookieStoreId": "firefox-default",
      "lockedTabs": false,
      "lockedPanel": false,
      "skipOnSwitching": false,
      "noEmpty": false,
      "newTabCtx": "none",
      "dropTabCtx": "none",
      "moveTabCtx": "none",
      "moveTabCtxNoChild": true
    },
    {
      "type": "tabs",
      "id": "p0YSPXeZjfZv",
      "name": 10,
      "icon": "...",
      "color": "...",
      "customIconSrc": "",
      "customIcon": "",
      "lockedTabs": false,
      "lockedPanel": false,
      "skipOnSwitching": false,
      "noEmpty": false,
      "newTabCtx": "none",
      "dropTabCtx": "none",
      "moveTabCtx": "none",
      "moveTabCtxNoChild": true,
      "urlRulesActive": false,
      "urlRules": ""
    }
  ],
  "containers": [],
  "cssVars": {
    "bg": "#1a1a1aff",
    "ctx_menu_font": "1rem sans-serif",
    "tabs_height": "20px",
    "tabs_indent": "4px",
    "tabs_fg": "#e5e5e5ff",
    "tabs_fg_hover": "#ffffffff",
    "tabs_bg_hover": "#373737ff",
    "tabs_lvl_indicator_bg": "#ffffffff"
  },
  "windows": [
    {
      "state": "normal",
      "incognito": false,
      "tabsCount": 228
    }
  ],
  "tabsMenu": [
    "discard",
    "separator-1",
    "moveToPanel",
    "separator-3",
    "duplicate",
    "separator-22496080414567032",
    "group",
    "flatten",
    "separator-05839053997708432",
    "close"
  ],
  "bookmarksMenu": [
    [
      {
        "name": "Open in"
      },
      "openInNewWin",
      "openInNewPrivWin",
      "openInCtr"
    ],
    "separator-5",
    "createBookmark",
    "createFolder",
    "createSeparator",
    "separator-6",
    "sortByName",
    "sortByLink",
    "sortByTime",
    "separator-7",
    "copyUrls",
    "edit",
    "delete"
  ],
  "bookmarks": {
    "bookmarksCount": 78,
    "foldersCount": 10,
    "separatorsCount": 0,
    "maxDepth": 2
  }
}
</code></details>

**Comment by ellidi** [comment]
Same on Win 10, FF 94.0.2 (64-bit)

**Comment by mbnuqw** [comment]
Should be fixed in the latest version.
