### ISSUE TITLE
Add a close tree button to the menu

### ISSUE THREAD

**Issue by muesli4** [mbnuqw/sidebery#436]
## Description

Similar to closing descendants and closing the current tab in some situations it is also helpful to close the tab and all of its descendants at the same time.  The suggested label would be _Close tree_.  Please add a this to the menu.

**Comment by ongots** [comment]
Right click on the parent tab icon

**Comment by mbnuqw** [comment]
Available from v5.0.0

**Comment by rofrol** [comment]
`Settings > Menu Editor > Tabs > click "Close branch"`

<img width="1161" alt="Screenshot 2024-04-22 at 21 35 18" src="https://github.com/mbnuqw/sidebery/assets/28787/f03bf691-73c5-47ee-8938-89898849b17d">




![image](https://github.com/mbnuqw/sidebery/assets/28787/21ad96de-289d-46dc-b126-90c0870eed46)
