### ISSUE TITLE
Panel audio state

### ISSUE THREAD

**Issue by alkim0** [mbnuqw/sidebery#437]
Great add-on!

Can I request that a panel have a small marker for audio/muted if one of its tabs is playing audio/muted?

Right now I have no way of knowing which panel contains the tab that is playing the audio

**Comment by scar45** [comment]
Hopefully @mbnuqw will label this as an `enhancement` and implement soon. It seems that the functionality to detect a tab playing audio is already implemented, as you can see the :musical_note: icon next to the favicon. 

It can indeed be quite frustrating to find the tab which is playing audio when you've got tons across many panels.

**Comment by mbnuqw** [comment]
Available from v5.0.0
