### ISSUE TITLE
Panel container not respected when opening URL from external application

### ISSUE THREAD

**Issue by chupikk** [mbnuqw/sidebery#438]
I have a panel with Work container assigned to it. The panel is currently selected/active.
When I open an URL from some external application (e.g. from Slack for Windows) - the link opens in that current panel, but in default container instead of Work container.

**Detailed steps**

Go to Settings, create a new Panel. 
In Panel settings select a container (e.g. Work) for a new tab and also for other container-related options.
Switch to that panel, create a new tab using double - the tab opens in Work container.
Now go to some external (non-browser) application that has clickable URLs in it (e.g. Slack). Click on an URL - it opens in that active Panel, but in default container.

**Expected behavior** 

Tab must be opened in container assigned to the panel.

**Environment info**

OS: Win ﻿﻿10 Pro
Firefox version: 89.0.2 (64Bit)
Addon version: 4.9.4

**Comment by gleonet** [comment]
I confirm this issue.

OS: Linux Ubuntu 20.04 LTS
Firefox version: 93.0b9 (64Bits)
Addon version: 4.9.4

**Comment by aldrich** [comment]
Still an issue I would like to see a fix for. Just adding to this:

OS: mac
Firefox: 99.0.1
Addon: 4.10.1

**Comment by mbnuqw** [comment]
Should be fixed in the latest version (Panel config > Container of new tab > Detect externally opened...)
