### ISSUE TITLE
Panel and tree structure disappear when closing and opening Firefox

### ISSUE THREAD

**Issue by Lobachevskiy** [mbnuqw/sidebery#442]
## Steps to reproduce
Close Firefox, then open it again.

## Expected behavior
Tree structure and panels are restored.

## Actual behavior
All tabs except the "Default" one are gone and their tabs are appended to the "Default" panel while also flattening their tree structure completely.

Reproduced this a few times already, seems semi-random. Might have something to do with the amount of tabs I have, but this was working fine until maybe a week or two ago.

![image](https://user-images.githubusercontent.com/1773231/127764859-f54f2fa6-18a8-4ae4-a91d-63eabbf1e996.png)

## Environment info

OS:  Windows 10
Firefox version:  90.0.2 (64-bit)
Addon version:  4.9.4

<details><code>
{
  "settings": {
    "version": "4.9.4",
    "nativeScrollbars": false,
    "selWinScreenshots": true,
    "tabsCheck": true,
    "tabsFix": "notify",
    "markWindow": false,
    "markWindowPreface": "[Sidebery] ",
    "ctxMenuNative": false,
    "autoHideCtxMenu": "none",
    "ctxMenuRenderInact": true,
    "ctxMenuIgnoreContainers": "",
    "navBarLayout": "horizontal",
    "navBarInline": true,
    "hideAddBtn": false,
    "hideSettingsBtn": false,
    "navBtnCount": true,
    "hideEmptyPanels": true,
    "navMidClickAction": "none",
    "navSwitchPanelsWheel": true,
    "groupLayout": "grid",
    "skipEmptyPanels": false,
    "dndTabAct": true,
    "dndTabActDelay": 750,
    "dndTabActMod": "none",
    "dndExp": "pointer",
    "dndExpDelay": 0,
    "dndExpMod": "none",
    "stateStorage": "global",
    "warnOnMultiTabClose": "collapsed",
    "activateOnMouseUp": true,
    "activateLastTabOnPanelSwitching": true,
    "showTabRmBtn": true,
    "showTabCtx": true,
    "hideInact": false,
    "activateAfterClosing": "next",
    "activateAfterClosingPrevRule": "visible",
    "activateAfterClosingNextRule": "tree",
    "activateAfterClosingGlobal": false,
    "activateAfterClosingNoFolded": true,
    "activateAfterClosingNoDiscarded": true,
    "shiftSelAct": true,
    "askNewBookmarkPlace": false,
    "tabsRmUndoNote": true,
    "nativeHighlight": false,
    "tabsUnreadMark": false,
    "tabsReloadLimit": 5,
    "tabsReloadLimitNotif": true,
    "moveNewTabPin": "start",
    "moveNewTabParent": "last_child",
    "moveNewTabParentActPanel": false,
    "moveNewTab": "end",
    "pinnedTabsPosition": "panel",
    "pinnedTabsList": false,
    "pinnedAutoGroup": false,
    "tabsTree": true,
    "groupOnOpen": true,
    "tabsTreeLimit": "none",
    "hideFoldedTabs": false,
    "autoFoldTabs": false,
    "autoFoldTabsExcept": "none",
    "autoExpandTabs": false,
    "rmChildTabs": "folded",
    "tabsChildCount": true,
    "tabsLvlDots": false,
    "discardFolded": false,
    "discardFoldedDelay": 0,
    "discardFoldedDelayUnit": "sec",
    "tabsTreeBookmarks": true,
    "treeRmOutdent": "branch",
    "bookmarksPanel": true,
    "warnOnMultiBookmarkDelete": "collapsed",
    "openBookmarkNewTab": false,
    "midClickBookmark": "open_new_tab",
    "actMidClickTab": false,
    "autoCloseBookmarks": false,
    "autoRemoveOther": false,
    "highlightOpenBookmarks": false,
    "activateOpenBookmarkTab": false,
    "showBookmarkLen": false,
    "bookmarksRmUndoNote": true,
    "fontSize": "s",
    "bgNoise": true,
    "animations": true,
    "animationSpeed": "fast",
    "theme": "tactile",
    "style": "dark",
    "sidebarCSS": false,
    "groupCSS": false,
    "snapNotify": true,
    "snapExcludePrivate": false,
    "snapInterval": 0,
    "snapIntervalUnit": "min",
    "snapLimit": 0,
    "snapLimitUnit": "snap",
    "hScrollThroughPanels": false,
    "scrollThroughTabs": "none",
    "scrollThroughVisibleTabs": false,
    "scrollThroughTabsSkipDiscarded": false,
    "scrollThroughTabsExceptOverflow": true,
    "scrollThroughTabsCyclic": false,
    "tabDoubleClick": "none",
    "tabLongLeftClick": "none",
    "tabLongRightClick": "none",
    "tabsPanelLeftClickAction": "none",
    "tabsPanelDoubleClickAction": "tab",
    "tabsPanelRightClickAction": "menu",
    "tabsPanelMiddleClickAction": "tab",
    "syncName": "",
    "syncSaveSettings": false,
    "syncSaveCtxMenu": false,
    "syncSaveStyles": false,
    "syncAutoApply": false
  },
  "permissions": {
    "allUrls": true,
    "tabHide": true,
    "actualAllUrls": true,
    "actualTabHide": true
  },
  "storage": {
    "size": "683.9 kb",
    "props": {
      "expandedBookmarks": "2 b",
      "favAutoCleanTime": "10 b",
      "favUrls": "17.1 kb",
      "favicons": "572.2 kb",
      "panelIndex": "1 b",
      "panels_v4": "2 kb",
      "prevTabsData_v4": "44.3 kb",
      "profileID": "14 b",
      "settings": "2.7 kb",
      "tabsData_v4": "45.1 kb"
    }
  },
  "panels": [
    {
      "type": "bookmarks",
      "id": "bookmarks",
      "cookieStoreId": "bookmarks",
      "name": 9,
      "icon": "...",
      "bookmarks": true,
      "lockedPanel": false,
      "skipOnSwitching": false
    },
    {
      "type": "default",
      "id": "firefox-default",
      "name": 7,
      "icon": "...",
      "cookieStoreId": "firefox-default",
      "lockedTabs": false,
      "lockedPanel": true,
      "skipOnSwitching": false,
      "noEmpty": false,
      "newTabCtx": "none",
      "dropTabCtx": "none",
      "moveTabCtx": "none",
      "moveTabCtxNoChild": true
    },
    {
      "type": "tabs",
      "id": "FbsQWwrIczA-",
      "name": 4,
      "icon": "...",
      "color": "...",
      "customIconSrc": "",
      "customIcon": "",
      "lockedTabs": false,
      "lockedPanel": true,
      "skipOnSwitching": false,
      "noEmpty": false,
      "newTabCtx": "firefox-container-2",
      "dropTabCtx": "firefox-container-2",
      "moveTabCtx": "firefox-container-2",
      "moveTabCtxNoChild": false,
      "urlRulesActive": true,
      "urlRules": 20
    },
    {
      "type": "tabs",
      "id": "KHXtqg8r_vOb",
      "name": 5,
      "icon": "...",
      "color": "...",
      "customIconSrc": "",
      "customIcon": "",
      "lockedTabs": false,
      "lockedPanel": false,
      "skipOnSwitching": false,
      "noEmpty": false,
      "newTabCtx": "none",
      "dropTabCtx": "none",
      "moveTabCtx": "none",
      "moveTabCtxNoChild": true,
      "urlRulesActive": false,
      "urlRules": ""
    },
    {
      "type": "tabs",
      "id": "D96_XPAoAvvm",
      "name": 3,
      "icon": "...",
      "color": "...",
      "customIconSrc": "",
      "customIcon": "",
      "lockedTabs": false,
      "lockedPanel": false,
      "skipOnSwitching": false,
      "noEmpty": false,
      "newTabCtx": "none",
      "dropTabCtx": "none",
      "moveTabCtx": "none",
      "moveTabCtxNoChild": true,
      "urlRulesActive": false,
      "urlRules": ""
    },
    {
      "type": "tabs",
      "id": "ep6FiW0seDvm",
      "name": 7,
      "icon": "...",
      "color": "...",
      "customIconSrc": "",
      "customIcon": "",
      "lockedTabs": false,
      "lockedPanel": false,
      "skipOnSwitching": false,
      "noEmpty": false,
      "newTabCtx": "none",
      "dropTabCtx": "none",
      "moveTabCtx": "none",
      "moveTabCtxNoChild": true,
      "urlRulesActive": false,
      "urlRules": ""
    },
    {
      "type": "tabs",
      "id": "A3C6ONfQ435q",
      "name": 11,
      "icon": "...",
      "color": "...",
      "customIconSrc": "",
      "customIcon": "",
      "lockedTabs": false,
      "lockedPanel": false,
      "skipOnSwitching": false,
      "noEmpty": false,
      "newTabCtx": "none",
      "dropTabCtx": "none",
      "moveTabCtx": "none",
      "moveTabCtxNoChild": true,
      "urlRulesActive": false,
      "urlRules": ""
    }
  ],
  "containers": [],
  "cssVars": "TypeError: can't convert undefined to object",
  "windows": [
    {
      "state": "maximized",
      "incognito": false,
      "tabsCount": 390
    }
  ],
  "bookmarks": {
    "bookmarksCount": 89,
    "foldersCount": 15,
    "separatorsCount": 1,
    "maxDepth": 3
  }
}
</code></details>

**Comment by colemickens** [comment]
I can +1 this exact report, including the ~"it seemed like this worked reliably until very recently" part.

Sometimes I will find that it seems like it has lost all tree structure and then after another restart or reopening of the panel, the structure *returns*, too.

**Comment by Lobachevskiy** [comment]
Another detail I noticed: looks like the "flattening" of the tree structure will only occur after a certain tab, so in the first panel I will have a few dozen tabs still retaining their tree structure, however all trees are expanded, but then after a certain tab it's all flat and includes other panels as well.

**Comment by Lobachevskiy** [comment]
https://github.com/mbnuqw/sidebery/commit/bbd90548afe76db40c3923cf083c51d2a40be3ab
This looks to be the likely culprit, seeing as it removed some code before saving tabs.

@mbnuqw please look into this as this bug has major impact on usability.

**Comment by SeerLite** [comment]
For me this stopped happening when I switched the tab storage from "global storage" to "session storage" in the settings. However, this made it very buggy when using multiple windows or adding/removing tabs while having the sidebar closed. Everytime I opened a new window it would spam with "tab structure wrong" (or something similar, sorry) and clicking "update tabs" did nothing.
This made it unusable for my workflow so I went back to "global storage" and have been manually re-ordering my tabs after every restart where they get flattened (it doesn't happen on every restart).

**Comment by kevinhaas** [comment]
I'm on a fresh install with no settings changed and I see the exact thing. Don't think it has anything to do with too many tabs/panels. Just doesn't work.

**Comment by ildiem** [comment]
I'm facing the same issue. Really impacts my workflow to have to re-add my tabs back to the correct panels manually every time.

**Comment by boldcompany** [comment]
Concur. Panel tree structure flattened with only two panels and a handful of tab groups in a fresh install of Firefox 92.0.1 and Sidebery 4.9.4.

**Comment by boldcompany** [comment]
> 
> 
> Concur. Panel tree structure flattened on Firefox exit/reopen. Only two panels and a handful of tab groups in a fresh install of Firefox 92.0.1 and Sidebery 4.9.4.

This case explained by #486

**Comment by Lobachevskiy** [comment]
> Toggle "global storage" to "session storage" in the settings/tabs.

This worked for me.

**Comment by jasonkena** [comment]
Please reopen this, I still experience this in v5.

**Comment by albino1** [comment]
I've also had this happen a few times, even with v5b31.  I would say it almost always works fine, but sometimes, very rarely, I lose my panels and it's not clear why.  However, I rarely close Firefox, often going over a month without restarting it, so there aren't many opportunities for it to happen to me.

I only consistently use two panels, and the tabs from the second panel all just wind up at the end of my default panel so moving them back is easy, but for a lot of people this could be disastrous.  Even for me, it makes me hesitant to invest in more panels.

I have `Hide native tabs of inactive panels` enabled, and sometimes when switching back and forth they stop hiding and all end up stacked in one horizontal tab row even though they're still in two panels.  I mention that in case it's related.

**Comment by mmorgan6** [comment]
This just happened to me as well upon starting Firefox. I had 3 tab panels flattened into 1 with all the tree structure of tabs flattened as well.
