### ISSUE TITLE
add panel name to window title

### ISSUE THREAD

**Issue by richard-delorenzi** [mbnuqw/sidebery#445]
## Description

I see that you have something called `preface value`. That changes the title-bar. It would be nice if you could add an option to show the current panel name.

The use case: if for the window-manager to move the window to a different activity/desktop depending on the panel. e.g. If the panel name starts with work, then move to the work activity/desktop.

To get this to work, all I would need is for the active panel's name to appear in the title-bar of the window (same as the `preface value` currently does).

**Comment by ntninja** [comment]
This would allow replacing “[Crappy FireTitle](https://addons.mozilla.org/de/firefox/addon/crappy-firetitle/)” (which has its own per-window name settings independent of the panel names assigned in Sidebery) for the use-case mentioned with just this extension.

(Also I was able to replace “[Sticky Window Containers](https://addons.mozilla.org/en-US/firefox/addon/sticky-window-containers/)” with Sidebery’s per-panel container settings today, so replacing our current make-shift container/window setup with just Sidebery is going along well in any case. :slightly_smiling_face:)
