### ISSUE TITLE
Container for new tab (in panel settings), should allow selection of containers that are already used.

### ISSUE THREAD

**Issue by richard-delorenzi** [mbnuqw/sidebery#446]
## Description
When setting up a panel, we should be allowed to select any container for `container for new tab`. This will allow several panels that all have the same default container.

Motivation: This is mostly to help tidy the default (horizontal) tab bar, but also allows more flexibility in panel/container mapping.

I can see why we have to restrict the container for `Move tab to this panel if it is opened in panel: ` (at most one panel can own a container, for this setting).

**Comment by mbnuqw** [comment]
Available in the latest version.
