### ISSUE TITLE
Problems moving tabs around

### ISSUE THREAD

**Issue by mbaz** [mbnuqw/sidebery#45]
Sometimes sideberry fails to move tags around. See here for an example (you can play gifs with `sxiv -a`; let me know if you want this in another format):

https://send.firefox.com/download/3809c19b835328b2/#r3P2YpGNpuRvf-dSqTmo4A

Notice the weird "ghost" icon that appears at the very top.

Another related problem I've seen, but haven't recorded:

1. In one window, select a bunch of tags and move them to an empty group tab.
2. In a separate window, try to move a tab.
3. See the tabs from the previous window move to the current window.

I can try to record this if you want me to.

**Comment by mbnuqw** [comment]
Jeez... :man_facepalming: thanks for reporting this. I forgot about this case - this happens when user drag tab by favicon.

About other issues - I can reproduce them and will fix. (:thinking: I thought I've tested multi-windows drag-and-drag)

**Comment by Jipok** [comment]
I also have problems with this.
The tab is not dragged if I hold the cursor on it for more than half a second (approximately).
If you drag by the icon, the animation appears but the tab does not move.
![output](https://user-images.githubusercontent.com/25588359/58761991-05001680-853a-11e9-9512-73e207a53b6c.gif)

**Comment by mbnuqw** [comment]
Yeah, this is a known problem. I'm currently working on next major release (3.0.0), which should solve most of drag and drop issues.

About new tab button - I want to add customizable dock to the bottom and give user ability to choose which buttons (or other special components) to place there.

**Comment by grahamperrin** [comment]
I see the word _ghost_ in the opening post here https://github.com/mbnuqw/sidebery/issues/45#issue-438896580 but (without a screenshot) I can't tell whether it was comparable to the ghost in my https://github.com/mbnuqw/sidebery/issues/147#issuecomment-592989923 … I suspect, not comparable. 

Re: the recording in https://github.com/mbnuqw/sidebery/issues/45#issuecomment-498031268 my eye is drawn to the peculiar 'jump up' that occurred when clicking the _Sidebery – Get this Ex_ tab at the foot of the list.

**Comment by grahamperrin** [comment]
If @fgueguen [Tabs manager](https://addons.mozilla.org/addon/duplicated-tabs-manager/) is enabled then, in some situations, it may be impossible to move multiple tabs from one panel to another. 

Screen recording: 

* [2020-03-21 10:36.zip](https://github.com/mbnuqw/sidebery/files/4362722/2020-03-21.10.36.zip)

Where two tabs were successfully moved, I: 

* waited for the second tab to load before dragging.

Where four tabs could **not** be moved, I: 

* used <kbd>Control</kbd>-Click to select each non-loaded tab; then
* released the <kbd>Control</kbd> key
* dragged. 

For simplicity – not expecting an enhancement by @fgueguen – I have: 

* disabled Tabs manager
* enabled [Duplicate Tabs Closer](https://addons.mozilla.org/addon/duplicate-tabs-closer/). 

### Environment

* Sidebery 4.6.2
* Tabs manager 1.7.

```text
grahamperrin@momh167-gjp4-8570p:~ % date ; uname -v
Sat 21 Mar 2020 10:25:20 GMT
FreeBSD 13.0-CURRENT #0 r359068: Wed Mar 18 21:14:12 GMT 2020     root@momh167-gjp4-8570p:/usr/obj/usr/src/amd64.amd64/sys/GENERIC-NODEBUG 
grahamperrin@momh167-gjp4-8570p:~ % pkg query '%o %v %R' firefox
www/firefox 74.0_5,1 FreeBSD
grahamperrin@momh167-gjp4-8570p:~ % 
```

**Comment by frigvid** [comment]
Is this issue still being worked on? I still experience issues with dragging tabs within and out of tab groups, and in general, regardless of whether they're being dragged by favicon or not.

Stylebery: v4.10.2
Firefox Developer Edition: 106.0b8
Operating System: Microsoft Windows 10 Pro v2009 (10.0.19044.0)

**Comment by jathek** [comment]
I haven't noticed problems with drag&drop in the v5 beta, but dragging by favicon still doesn't seem to work.

**Comment by mbnuqw** [comment]
Closing this as stale and probably fixed.
