### ISSUE TITLE
panels lost tabs

### ISSUE THREAD

**Issue by kolossa** [mbnuqw/sidebery#450]
## Steps to reproduce
I created more than 3 panels

## Expected behavior
Add several tabs to all panels. Panels should keep these tabs.

## Actual behavior
When I close the side bar or restart firefox, only the first 3 panels keep their tabs. The other panels lost all of those.

## Environment info

OS:  Windows 7
Firefox version:  91.0
Addon version:  4.9.4

<details><code>

</code></details>

I think it would be a very useful extension, please check my problem if you can!

Thank you!

**Comment by mbnuqw** [comment]
Closing this as stale. Please, reopen if issue is reproduced in the latest version of Sidebery.
