### ISSUE TITLE
Add pinned tabs dock to navigation bar

### ISSUE THREAD

**Issue by rg-4re** [mbnuqw/sidebery#452]
I'd like to have my pinned tabs to be inline with nav bar without pushing the tabs panel down.

Here's my attempt of doing so.
![Snipaste_2021-08-16_23-07-00](https://user-images.githubusercontent.com/89082999/129729926-324aaa99-c2b2-44b2-a588-f401a9e26603.png)

Any options I've missed? Is it possible with css? 
All feedback are appreciated, thank you.

**Comment by mbnuqw** [comment]
Available in the latest version.
