### ISSUE TITLE
Keybinding import/export

### ISSUE THREAD

**Issue by ghost** [mbnuqw/sidebery#454]
Currently, looking at the JSON file exported by Sidebery, there's no data about the keybindings. What this means is that my custom keybindings cannot be shared as easily as other settings, resorting to manually setting each keybinding.

**Comment by megamorphg** [comment]
Yeah this would be nice for a more complete backup so can more easily switch between versions (v4 and v5) for instance. I have a dozen keybindings have to change every time.

**Comment by dexeonify** [comment]
AFAICT extensions shortcuts are managed by Firefox, not by the extensions themselves. None of my installed extensions has the option to backup keybindings.

**Comment by mrpandey** [comment]
@mbnuqw You marked this as "resolved in beta" more than a year ago. So is this now available in latest versions?

**Comment by albino1** [comment]
> @mbnuqw You marked this as "resolved in beta" more than a year ago. So is this now available in latest versions?

Yes, you can export keybindings and various other things.  This is what the dialog box looks like:


![export](https://github.com/mbnuqw/sidebery/assets/12164957/5ee1a27a-b668-48e4-9b04-5b04dc05dc2f)

**Comment by mbnuqw** [comment]
Available from v5.0.0
