### ISSUE TITLE
View panel as the single window

### ISSUE THREAD

**Issue by fugkco** [mbnuqw/sidebery#457]
Hi,

I'd like to see if this is possible, and if not, it would be nice to have this as a feature.

Currently I'm using panels as a context, i.e. something along the lines of two panels, one project A, and one project B. This works pretty nice except when I'm on a tab at the end, or beginning of a panel, because at that point, when I switch tab to go beyond the current tab, it goes to the next panel. E.g. if I'm on the last tab in the panel for project A, and tap the `ctrl+tab`, it goes to the next panel. This isn't as bad as some other shortcuts, namely `Alt+0-9` which makes it a lot harder to move back.

Is it possible to see force `Alt+0-9` to respect the panels? Same with `ctrl+tab`? In that, for example, if you're at the end, it refuses to go to the next tab? Same for `ctrl+shift+tab`?

Thanks

**Comment by mbnuqw** [comment]
Available in the latest version via sidebery keybindings. (Sidebery settings > Keybindings > Switching between tabs)
