### ISSUE TITLE
Solved - Facebook.com/me link is missing when Sidebery tabs are opened

### ISSUE THREAD

**Issue by kartane3** [mbnuqw/sidebery#459]
Solved.  It is Facebook reacting to the window size.  Nothing to do with Sidebery at all.  
Confirmed by using Firefox in safe mode with no Add-ons at all. 
Press Ctrl + B for the bookmarks sidebar causes the Facebook link problem to happen.  (Or Ctrl + H for the history sidebar). 
I will have to research why Facebook does this, now.  
Thanks for the heads up, https://github.com/SeerLite

## Steps to reproduce
Go to Facebook homepage. 
Open Sidebery side panel. 
Even fails if Sidebery is the only Firefox Add-on.

## Expected behavior
See facebook.com/me/ Icon (and link). 
Located near the right in the Top Nav Bar just before Facebook Menu icon
Click on Icon takes me to my Facebook Timeline page.

## Actual behavior
facebook.com/me/ Icon (and link) is missing. 

## Environment info

OS:  
Firefox version:  91.0.2 64bit
Addon version:  4.9.4

<details><code>

     {
  "settings": {
    "version": "4.9.4",
    "nativeScrollbars": true,
    "selWinScreenshots": true,
    "tabsCheck": true,
    "tabsFix": "notify",
    "markWindow": false,
    "markWindowPreface": "[Sidebery] ",
    "ctxMenuNative": false,
    "autoHideCtxMenu": "none",
    "ctxMenuRenderInact": true,
    "ctxMenuIgnoreContainers": "",
    "navBarLayout": "horizontal",
    "navBarInline": false,
    "hideAddBtn": true,
    "hideSettingsBtn": false,
    "navBtnCount": true,
    "hideEmptyPanels": false,
    "navMidClickAction": "none",
    "navSwitchPanelsWheel": false,
    "groupLayout": "grid",
    "skipEmptyPanels": false,
    "dndTabAct": true,
    "dndTabActDelay": 750,
    "dndTabActMod": "none",
    "dndExp": "pointer",
    "dndExpDelay": 0,
    "dndExpMod": "none",
    "stateStorage": "global",
    "warnOnMultiTabClose": "none",
    "activateOnMouseUp": true,
    "activateLastTabOnPanelSwitching": true,
    "showTabRmBtn": true,
    "showTabCtx": true,
    "hideInact": false,
    "activateAfterClosing": "next",
    "activateAfterClosingPrevRule": "visible",
    "activateAfterClosingNextRule": "tree",
    "activateAfterClosingGlobal": false,
    "activateAfterClosingNoFolded": true,
    "activateAfterClosingNoDiscarded": true,
    "shiftSelAct": true,
    "askNewBookmarkPlace": false,
    "tabsRmUndoNote": false,
    "nativeHighlight": false,
    "tabsUnreadMark": false,
    "tabsReloadLimit": 0,
    "tabsReloadLimitNotif": true,
    "moveNewTabPin": "end",
    "moveNewTabParent": "end",
    "moveNewTabParentActPanel": false,
    "moveNewTab": "end",
    "pinnedTabsPosition": "left",
    "pinnedTabsList": false,
    "pinnedAutoGroup": false,
    "tabsTree": false,
    "groupOnOpen": true,
    "tabsTreeLimit": "none",
    "hideFoldedTabs": false,
    "autoFoldTabs": false,
    "autoFoldTabsExcept": "none",
    "autoExpandTabs": false,
    "rmChildTabs": "none",
    "tabsChildCount": true,
    "tabsLvlDots": false,
    "discardFolded": false,
    "discardFoldedDelay": 0,
    "discardFoldedDelayUnit": "sec",
    "tabsTreeBookmarks": true,
    "treeRmOutdent": "branch",
    "bookmarksPanel": false,
    "warnOnMultiBookmarkDelete": "collapsed",
    "openBookmarkNewTab": false,
    "midClickBookmark": "open_new_tab",
    "actMidClickTab": false,
    "autoCloseBookmarks": false,
    "autoRemoveOther": false,
    "highlightOpenBookmarks": false,
    "activateOpenBookmarkTab": false,
    "showBookmarkLen": false,
    "bookmarksRmUndoNote": true,
    "fontSize": "m",
    "bgNoise": false,
    "animations": false,
    "animationSpeed": "fast",
    "theme": "default",
    "style": "light",
    "sidebarCSS": false,
    "groupCSS": false,
    "snapNotify": false,
    "snapExcludePrivate": true,
    "snapInterval": 0,
    "snapIntervalUnit": "min",
    "snapLimit": 0,
    "snapLimitUnit": "snap",
    "hScrollThroughPanels": false,
    "scrollThroughTabs": "none",
    "scrollThroughVisibleTabs": false,
    "scrollThroughTabsSkipDiscarded": false,
    "scrollThroughTabsExceptOverflow": true,
    "scrollThroughTabsCyclic": false,
    "tabDoubleClick": "none",
    "tabLongLeftClick": "none",
    "tabLongRightClick": "none",
    "tabsPanelLeftClickAction": "none",
    "tabsPanelDoubleClickAction": "tab",
    "tabsPanelRightClickAction": "menu",
    "tabsPanelMiddleClickAction": "tab",
    "syncName": "",
    "syncSaveSettings": false,
    "syncSaveCtxMenu": false,
    "syncSaveStyles": false,
    "syncAutoApply": false
  },
  "permissions": {
    "allUrls": false,
    "tabHide": false,
    "actualAllUrls": false,
    "actualTabHide": false
  },
  "storage": {
    "size": "92.7 kb",
    "props": {
      "bookmarksMenu": "2 b",
      "cssVars": "2 b",
      "disabledKeybindings": "933 b",
      "favAutoCleanTime": "10 b",
      "favUrls": "1.7 kb",
      "favicons": "80.8 kb",
      "panelIndex": "1 b",
      "prevTabsData_v4": "3.1 kb",
      "profileID": "14 b",
      "settings": "2.7 kb",
      "tabsData_v4": "3 kb",
      "tabsMenu": "2 b"
    }
  },
  "panels": "TypeError: t is undefined",
  "containers": [],
  "cssVars": {},
  "windows": [
    {
      "state": "maximized",
      "incognito": false,
      "tabsCount": 31
    }
  ],
  "tabsMenu": [],
  "bookmarksMenu": [],
  "bookmarks": {
    "bookmarksCount": 1640,
    "foldersCount": 90,
    "separatorsCount": 0,
    "maxDepth": 6
  }
}
</code></details>

**Comment by SeerLite** [comment]
Does this not happen when opening any other Firefox sidebar, like bookmarks or history?

**Comment by kartane3** [comment]
With Sidebery installed but not active, it all works as intended.  
When Sidebery is opened the Facebook icon/link disappears.  It does not matter which side tab is opened.  Sidebery, Bookmarks, History etc.  
Confirmed this behaviour even if Sideberry is the only active Firefox Add-on.

**Comment by SeerLite** [comment]
Sorry if my question is dumb, maybe I misread you. I just want to be 100% sure it's about Sidebery:

Does this happen with Sidebery uninstalled? With no add-ons at all, and opening the bookmarks sidebar?

**Comment by kartane3** [comment]
If the Sideberry side panel is active in Firefox the Facebook link problem happens. 

If I delete Sidebery, the Facebook link problem does not happen.
If Sidebery is installed but the side panel is not active, the Facebook link problem does not happen.  No matter how many other Add-ons are installed or active.
If I run Firefox in safe mode with no Add-ons active, the Facebook link problem does not happen. 

Sorry, I don't know how to run the bookmarks as a sidebar, without Sideberry.  So I did not test this option.

**Comment by SeerLite** [comment]
You can use Ctrl + B and Ctrl + H for bookmarks and history sidebars respectively. There should also be an icon either on the top right or in the overflow menu to toggle the sidebar.

If the issue doesn't happen when Sidebery is uninstalled _and_ you have either of those sidebars active, then yeah it'd be a Sidebery issue. I doubt it is though, I'm sure it has to do with Facebook reacting the window/view size.

**Comment by kartane3** [comment]
Yep.  That solved it.  Thanks, SeerLite.  Sidebery is not the cause.  

Now I have to research the Facebook window size issue.  Cheers.

**Comment by SeerLite** [comment]
Hey @kartane3, you should close this issue with the button at the bottom of the page instead of editing the title ;)

**Comment by kartane3** [comment]
Will do, @SeerLite.  Sorry, new to this forum.
