### ISSUE TITLE
Add keyboard shortcut to activate last tab on the current panel

### ISSUE THREAD

**Issue by nh2** [mbnuqw/sidebery#461]
Following up on https://github.com/mbnuqw/sidebery/issues/395#issuecomment-849831875:

I'd love a keyboard shortcut to activate the last tab on the current panel.

Ideally it would even be possible to override Alt+9 to have that behaviour, or to use Alt+0.

Thanks!

**Comment by mbnuqw** [comment]
Available from v5.0.0

**Comment by nh2** [comment]
Thanks!
