### ISSUE TITLE
Question: Does keybindings only work with the sidebar open?

### ISSUE THREAD

**Issue by mcartagenah** [mbnuqw/sidebery#462]
At the moment the shortcuts only work after I open the sidebar, is there any way to use them without opening it?

**Comment by ongots** [comment]
It is possible to hide the sidebar using css
https://github.com/ongots/pseudo-fullscreen-firefox/blob/67cbebf7d597d5f90d1896fd571d6a3abed918b0/chrome/userChrome.css#L38

**Comment by mbnuqw** [comment]
> Does keybindings only work with the sidebar open?

Yes.

> At the moment the shortcuts only work after I open the sidebar, is there any way to use them without opening it?

No.
