### ISSUE TITLE
[feature request] ability to rename group

### ISSUE THREAD

**Issue by monkeydri** [mbnuqw/sidebery#47]
Unless I missed it I see no way to rename a group

Sidebery 2.4.2

**Comment by mbnuqw** [comment]
Just click on title on group page and edit it.

**Comment by monkeydri** [comment]
:facepalm:

**Comment by mbylstra** [comment]
It's true that you can do not but it's not at all _discoverable_ that you can do that. There should be a right click "rename group" option directly within group item in tree to rename the group (or perhaps double click, just like folders in a finder). I never would have realised you can do that until I googled it and found this issue.
