### ISSUE TITLE
Ctrl+Tab is confusing when you have pinned tabs and multiple panels

### ISSUE THREAD

**Issue by pintassilgo** [mbnuqw/sidebery#471]
Unlike the other issues I opened, I guess this one is hard to fix (implement).

### Steps to reproduce

1. "*Hide tabs of inactive panels*" → on.
2. "*Pinned tabs position*" → panel.
3. Be sure to have tabs in more than one panel.
4. Be sure to have at least one pinned tab in an inactive panel.
5. Select the last tab of current panel.
6. Press Ctrl+Tab.

### Expected results

As usual, since you are viewing the last tab of the current panel, Ctrl+Tab should go back to start and activate the first tab of the current panel.

### Actual results

Instead, a pinned tab from an inactive panel is activated, thus you leave the panel you were viewing.

---

I guess this issue is caused by Firefox. It seems that pinned tabs are impossible to hide using Tab Hide API.

But given that many (if not most) of Sidebery users hide native tabbar using userChrome.css, I think it's possible for Sidebery to create an option to use its own implementation of pinned tabs instead of the Firefox default. In that case, a pinned tab would not be considered pinned for Firefox (tab.pinned would be still false). A Sidebery's pinned tab would be just a tab easier to reach and displayed by just the page icon. Pinned tabs would still be always the first on each panel. So just like regular pinned tabs, the only difference is that, by not using the native pinned tabs "API", we could have per-panel pinned tabs, thus Ctrl+Tab / Ctrl+Shift+Tab would work as expected.

**Comment by black-puppydog** [comment]
I just stumbled over these semantics myself. IMHO, when I hit Ctrl-Tab on *any* tab, the visually next tab should become active. If I'm in a panel and I'm focusing the last *pinned* tab, this should be the first non-pinned tab. Instead, pinned tabs are "globally" first (no matter whether they're panel-local or not) and focusing on the last pinned tab will activate the next tab in that underlying global order.

**Comment by Lamecarlate** [comment]
Same here: when I'm in Panel 3, in the last pinned tab, I always expect Ctrl + Tab to take me to the first normal tab of Panel 3… not Panel 1.

Before switching to Sidebery, I used TreeStyleTabs and Simple Tabs Groups. And with STG, the behaviour you describe (If I'm in a panel and I'm focusing the last pinned tab, this should be the first non-pinned tab) is precisely the one used. I wonder if it's possible to replicate in Sidebery. It could be great!

**Comment by mbnuqw** [comment]
Related: #1148, #463
Workaround: use Sidebery keybindings for switching tabs

Using an own implementation of pinned tabs is a nice idea that also solves lots of other problems, on the other hand, it could bring confusion to users who use native tabs (I don't have telemetry data to estimate the number of such users), and I don't want to maintain both implementations at the same time. Plus, Ctrl+Tab issue will still appear if you have tabs that use camera or microphone in inactive panel, so until Firefox allow users/addons to change/handle default keybindings the only solution is using Sidebery shortcuts.

**Comment by rublev** [comment]
FYI if u enable "hide native tabs of inactive panels" then you can cmd+1/2/3/4 etc within the panel and also cyclically ctrl+tab / ctrl+shift+tab
