### ISSUE TITLE
"Ignore discarded tabs" disturbs tab switching when there's no loaded tab left in the panel

### ISSUE THREAD

**Issue by pintassilgo** [mbnuqw/sidebery#473]
## Steps to reproduce

1. "*Ignore discarded tabs*" → on
2. Open a new tab at the end of a non-empty panel in which all tabs are discarded.
3. Close that tab.
4. Since there's no loaded tab left in current panel, a tab from another panel will be activated, that's right.
5. Now press Ctrl+Tab multiple times.

## Expected behavior

The expected behavior is to cycle between all tabs from current panel (which already had at least one loaded tab since the start).

## Actual behavior

After reaching the end of current tab panel, Ctrl+Tab activates a tab from another panel, which is unwanted, at least if you have "*Hide tabs of inactive panels*" → true, which is my case.

## Environment info

OS: win
Firefox: 93.0
Addon: 4.9.4

<details><code>
{
  "settings": {
    "version": "4.9.4",
    "nativeScrollbars": false,
    "selWinScreenshots": false,
    "tabsCheck": false,
    "tabsFix": "notify",
    "markWindow": false,
    "markWindowPreface": "[Sidebery] ",
    "ctxMenuNative": true,
    "autoHideCtxMenu": "none",
    "ctxMenuRenderInact": false,
    "ctxMenuIgnoreContainers": "Private",
    "navBarLayout": "horizontal",
    "navBarInline": false,
    "hideAddBtn": true,
    "hideSettingsBtn": true,
    "navBtnCount": true,
    "hideEmptyPanels": false,
    "navMidClickAction": "none",
    "navSwitchPanelsWheel": false,
    "groupLayout": "grid",
    "skipEmptyPanels": false,
    "dndTabAct": false,
    "dndTabActDelay": 750,
    "dndTabActMod": "none",
    "dndExp": "none",
    "dndExpDelay": 500,
    "dndExpMod": "none",
    "stateStorage": "session",
    "warnOnMultiTabClose": "none",
    "activateOnMouseUp": false,
    "activateLastTabOnPanelSwitching": true,
    "showTabRmBtn": false,
    "showTabCtx": true,
    "hideInact": true,
    "activateAfterClosing": "next",
    "activateAfterClosingPrevRule": "tree",
    "activateAfterClosingNextRule": "tree",
    "activateAfterClosingGlobal": false,
    "activateAfterClosingNoFolded": true,
    "activateAfterClosingNoDiscarded": true,
    "shiftSelAct": false,
    "askNewBookmarkPlace": false,
    "tabsRmUndoNote": false,
    "nativeHighlight": false,
    "tabsUnreadMark": false,
    "tabsReloadLimit": 0,
    "tabsReloadLimitNotif": true,
    "moveNewTabPin": "start",
    "moveNewTabParent": "default",
    "moveNewTabParentActPanel": false,
    "moveNewTab": "after",
    "pinnedTabsPosition": "top",
    "pinnedTabsList": false,
    "pinnedAutoGroup": false,
    "tabsTree": true,
    "groupOnOpen": true,
    "tabsTreeLimit": "none",
    "hideFoldedTabs": true,
    "autoFoldTabs": false,
    "autoFoldTabsExcept": "none",
    "autoExpandTabs": false,
    "rmChildTabs": "folded",
    "tabsChildCount": true,
    "tabsLvlDots": false,
    "discardFolded": false,
    "discardFoldedDelay": 0,
    "discardFoldedDelayUnit": "sec",
    "tabsTreeBookmarks": false,
    "treeRmOutdent": "first_child",
    "bookmarksPanel": false,
    "warnOnMultiBookmarkDelete": "collapsed",
    "openBookmarkNewTab": false,
    "midClickBookmark": "open_new_tab",
    "actMidClickTab": false,
    "autoCloseBookmarks": false,
    "autoRemoveOther": false,
    "highlightOpenBookmarks": false,
    "activateOpenBookmarkTab": false,
    "showBookmarkLen": false,
    "bookmarksRmUndoNote": true,
    "fontSize": "xxs",
    "bgNoise": false,
    "animations": false,
    "animationSpeed": "fast",
    "theme": "tactile",
    "style": "light",
    "sidebarCSS": true,
    "groupCSS": false,
    "snapNotify": false,
    "snapExcludePrivate": false,
    "snapInterval": 0,
    "snapIntervalUnit": "min",
    "snapLimit": 0,
    "snapLimitUnit": "snap",
    "hScrollThroughPanels": false,
    "scrollThroughTabs": "none",
    "scrollThroughVisibleTabs": false,
    "scrollThroughTabsSkipDiscarded": false,
    "scrollThroughTabsExceptOverflow": false,
    "scrollThroughTabsCyclic": false,
    "tabDoubleClick": "none",
    "tabLongLeftClick": "none",
    "tabLongRightClick": "none",
    "tabsPanelLeftClickAction": "none",
    "tabsPanelDoubleClickAction": "none",
    "tabsPanelRightClickAction": "menu",
    "tabsPanelMiddleClickAction": "none",
    "syncName": "",
    "syncSaveSettings": false,
    "syncSaveCtxMenu": false,
    "syncSaveStyles": false,
    "syncAutoApply": false
  },
  "permissions": {
    "allUrls": true,
    "tabHide": true,
    "actualAllUrls": true,
    "actualTabHide": true
  },
  "storage": {
    "size": "223.3 kb",
    "props": {
      "bookmarksMenu": "226 b",
      "bookmarksPanelMenu": "54 b",
      "cssVars": "481 b",
      "disabledKeybindings": "933 b",
      "favAutoCleanTime": "10 b",
      "favUrls": "5.2 kb",
      "favicons": "162.6 kb",
      "panelIndex": "1 b",
      "panels_v4": "1.7 kb",
      "prevTabsData_v4": "19.7 kb",
      "profileID": "14 b",
      "settings": "2.7 kb",
      "sidebarCSS": "8.9 kb",
      "tabsData_v4": "20 kb",
      "tabsMenu": "190 b",
      "tabsPanelMenu": "184 b"
    }
  },
  "panels": [
    {
      "type": "default",
      "id": "firefox-default",
      "name": 7,
      "icon": "...",
      "cookieStoreId": "firefox-default",
      "lockedTabs": false,
      "lockedPanel": false,
      "skipOnSwitching": false,
      "noEmpty": false,
      "newTabCtx": "none",
      "dropTabCtx": "none",
      "moveTabCtx": "none",
      "moveTabCtxNoChild": true
    },
    {
      "type": "tabs",
      "id": "1w0_Q6iAqe3j",
      "name": 2,
      "icon": "...",
      "color": "...",
      "customIconSrc": "",
      "customIcon": "",
      "lockedTabs": false,
      "lockedPanel": false,
      "skipOnSwitching": false,
      "noEmpty": false,
      "newTabCtx": "none",
      "dropTabCtx": "none",
      "moveTabCtx": "none",
      "moveTabCtxNoChild": true,
      "urlRulesActive": false,
      "urlRules": ""
    },
    {
      "type": "tabs",
      "id": "t0ugf6d7fE0j",
      "name": 13,
      "icon": "...",
      "color": "...",
      "customIconSrc": "",
      "customIcon": "",
      "lockedTabs": false,
      "lockedPanel": false,
      "skipOnSwitching": false,
      "noEmpty": false,
      "newTabCtx": "none",
      "dropTabCtx": "none",
      "moveTabCtx": "none",
      "moveTabCtxNoChild": true,
      "urlRulesActive": false,
      "urlRules": ""
    },
    {
      "type": "tabs",
      "id": "VAQViX_RLf3j",
      "name": 1,
      "icon": "...",
      "color": "...",
      "customIconSrc": "",
      "customIcon": "",
      "lockedTabs": false,
      "lockedPanel": false,
      "skipOnSwitching": false,
      "noEmpty": false,
      "newTabCtx": "none",
      "dropTabCtx": "none",
      "moveTabCtx": "none",
      "moveTabCtxNoChild": true,
      "urlRulesActive": true,
      "urlRules": 501
    }
  ],
  "containers": [],
  "cssVars": {
    "bg": "#f0f0f0",
    "tabs_fg": "#000000",
    "tabs_fg_hover": "#000000",
    "tabs_fg_active": "#000000",
    "tabs_bg_hover": "#d8e4ee",
    "tabs_activated_bg": "#9cc6e7",
    "tabs_font": "message-box",
    "tabs_height": "26px",
    "tabs_pinned_height": "33px",
    "tabs_count_font": ".6625rem Roboto"
  },
  "sidebarCSSLen": 8838,
  "windows": [
    {
      "state": "maximized",
      "incognito": false,
      "tabsCount": 184
    }
  ],
  "tabsMenu": [
    [
      {
        "name": ""
      },
      "mute",
      "reload"
    ],
    "separator-2",
    [
      {
        "name": "Move to"
      },
      "moveToPanel"
    ],
    "moveToNewWin",
    "separator-3",
    "pin",
    "discard",
    "copyUrls",
    "separator-15631594496462675",
    "flatten",
    "separator-4"
  ],
  "bookmarksMenu": [
    [
      {
        "name": "Open in"
      },
      "openInNewWin",
      "openInNewPrivWin",
      "openInCtr"
    ],
    "separator-5",
    "createBookmark",
    "createFolder",
    "createSeparator",
    "separator-6",
    "sortByName",
    "sortByLink",
    "sortByTime",
    "separator-7",
    "copyUrls",
    "edit",
    "delete"
  ],
  "bookmarks": {
    "bookmarksCount": 637,
    "foldersCount": 33,
    "separatorsCount": 1,
    "maxDepth": 2
  }
}
</code></details>

**Comment by pintassilgo** [comment]
https://github.com/pintassilgo/sidebery/commit/8bb89a0c8843db71d703ce38139117ddfc55e2e8

**Comment by mbnuqw** [comment]
Fixed (hiding the native tabs on panel switch) in the latest version.
