### ISSUE TITLE
"Place new tab (for the other cases) = none" causes critical bug after auto moving tab

### ISSUE THREAD

**Issue by pintassilgo** [mbnuqw/sidebery#477]
## Steps to reproduce
1. `Place new tab (for the other cases)` = none
2. Have at least two panels with some tabs.
3. Define a tab catching rule for one inactive panel (let's call it Panel 2), like https://example.com/
4. Open https://example.com/

## Expected behavior
1. The tab that loaded https://example.com/ must be moved to "Panel 2".
2. The view should switch to Panel 2.

## Actual behavior
The expected behavior is fulfilled, **but** all tabs from Panel 2 disappear except by the one that was moved. Tabs from other panels disappear too. The warning below pops up:
![image](https://user-images.githubusercontent.com/5483864/134786792-d37508d0-b814-4786-95f6-5c1746f662c2.png)
And you need to click "Update tabs" to fix things.

---

Sidebery 4.9.4, also tested building from last commit.

**Comment by mbnuqw** [comment]
Fixed in the latest version
