### ISSUE TITLE
Distinction when moving tabs inside tree

### ISSUE THREAD

**Issue by ashtonx** [mbnuqw/sidebery#48]
Minor enhancement request.
When you want to move tab to a position that is outside, but below last entry of a tree, most of the times tab ends up at the bottom of a tree even if intention is for it to be outside.

I feel there should be some marking when it's gonna end up in a tree or outside, like some glow around arrow, dotted line or simple indentation. 

I'm guessing indentation or some other marking that shows it would do better in case of multi level trees.

**Comment by mbnuqw** [comment]
Yeah. Currently, to place element right after expanded group you need to fold this group (point mouse cursor to the drag pointer's triangle). Then you can place dragged element next to it.

But this is not very user-friendly and I've already thought about solutions.
One of them - to add special areas in drop pointer to let you choose drop-level, like this:
```
       Now           |     What I meant
                     |
 Tab-1               |  Tab-1
     Tab-2           |      Tab-2
         Tab-3       |          Tab-3
>-----------------   | > 1 > 2 > 3 >-------
 Tab-4               |  Tab-4
 Tab-5 (Dragged)     |  Tab-5 (Dragged)
```

What do you think about this?

**Comment by ashtonx** [comment]
If numbers were only visible based on tab as level It'd prolly be most perfect

1,2,3 might feel bit off, though I didn't see it in practice. 
I think tab arrow jumping around would be better.

Unless you mean something like number + extra arrow placed at position of indentation

>----------------
> 1 >-----------
>--- 2 >--------
>-------- 3 >---

Could also be change to dots, the ones you use to distinguish the levels of tree
for example
>-----------
* >---------
* * >-------
* * * >-----

Either way some sort of level marker would be really good.

Sorry for late response was very busy with some stuff past 2 days.

**Comment by mbnuqw** [comment]
Yes, I've used numbers in my example just to show relations with tabs levels and I think to use arrows or dots or any other kind of visual representation as you already suggest. Also I think it's possible to somehow highlight target parent tab...

Anyway, I will test multiple variants and upload screenshots here.

**Comment by mbnuqw** [comment]
I've added multi-lvl drag-and-drop feature in v4.5.0
![image](https://user-images.githubusercontent.com/6276694/73949911-e221cf80-491c-11ea-8e82-79faecc4c5da.gif)

..so, I guess I can close this issue
