### ISSUE TITLE
Wrong choice of tab after closing last child when the parent is unloaded

### ISSUE THREAD

**Issue by pintassilgo** [mbnuqw/sidebery#481]
1. Install Sidebery 4.9.4 with default settings (after closing current, activate: next tab / next tab rule: tree / ignore discarded tabs: true).
2. Open two consecutive tabs (Tab A and Tab B).
3. Select Tab A and open a link in new tab to create a child tab (Tab A-child).
4. Right-click Tab A and unload it.
At this time, this is our tab structure:
- Tab A (discarded)
  - Tab A-child (active)
- Tab B
5. Close current tab (Tab A-child).

Following Sidebery settings (activate next tab and ignore discarded tabs), Tab B should be activated. Instead, Tab A is activated despite it was unloaded.

A slightly different step can produce a another unwanted result. Follow the first two steps above, then:
3. Be sure to have at least one loaded tab *before* Tab A (it can even be in a panel with lower index than current).
4. Select Tab A and open multiple links in new tab to create children tabs (Tab A-child, Tab A-child2...).
5. Right-click Tab A and unload it.
6. Tab A-child is now active, close it.
7. Tab A-child2 is now active, close it.
8. Continue closing current tab until you closed the last child of Tab A.

Now, following Sidebery settings (activate next tab and ignore discarded tabs), again Tab B should be activated. Instead, the last loaded tab **above** Tab A is activated. If there's no other loaded tab in current panel, then the last loaded tab from the previous panel is activated.

**Comment by pintassilgo** [comment]
With "After closing current tab activate: none", unloading the activated parent tab doesn't even work, because it seems that it itself is chosen as the successor tab.

**Comment by pintassilgo** [comment]
To prevent activating discarded tab when "ignore discarded tabs" is enabled:
https://github.com/pintassilgo/sidebery/commit/4b346b1b0f1ae9363ad76bc8b1275d3606e5c08a

**Comment by mbnuqw** [comment]
Fixed in the latest version
