### ISSUE TITLE
some sidebery features break when certain tab-control add-ons are used simultaneously

### ISSUE THREAD

**Issue by boldcompany** [mbnuqw/sidebery#486]
## Steps to reproduce
1. Install sidebery in Firefox.
2. Install a tab control add-on such as Sebastian Blask's "[Open Tabs Next to Current](https://addons.mozilla.org/en-US/firefox/addon/open-tabs-next-to-current)".

## Expected behavior
Many users might expect that sidebery would manage tabs independently of literal positioning in the main Firefox tab display. They might expect that sidebery would have its own system of tab management that would not be affected by tab repositioning elsewhere in Firefox.

## Actual behavior
When a utility like "[Open Tabs Next to Current](https://addons.mozilla.org/en-US/firefox/addon/open-tabs-next-to-current)" is installed, a few things may occur:
1. The creation and management of sidebery tab groups often malfunctions. Groups are created erroneously in panels different from intended, and tabs are grouped in erroneous, unexpected ways.
2. On Firefox restart, panel/group hierarchy can be jumbled and broken.

NOTE: It might be determined that "it's the other add-ons' fault." But perhaps sidebery could be adapted to work more consistently when installed alongside these other helpful add-ons.

## Environment info

OS:  Windows 10
Firefox version:  92.0.1
Addon version:  4.9.4

**Comment by pintassilgo** [comment]
As mentioned in the description of `Open Tabs Next to Current`, there's no need to install that extension, you can just set `browser.tabs.insertAfterCurrent` in `about:config`.

**Comment by SeerLite** [comment]
I don't have any such extension and the setting `browser.tabs.insertAfterCurrent` is off in `about:config`, and I still get my tree structure disappearing on every other restart.

Will do what you have done and test for what exactly is causing it on a new profile now...

**Comment by boldcompany** [comment]
@pintassilgo Thank you for your excellent support.
