### ISSUE TITLE
Allow customization of container colored mark

### ISSUE THREAD

**Issue by costincaraivan** [mbnuqw/sidebery#488]
## Description

I have a wide a big screen and the container icon is off to the right, so when navigating through tabs I frequently check the colored mark on the tabs in Sidebery.

However, the mark is slightly too subtle, plus the colors offer only a limited range of customizability.

I'd like to be able to make the mark wider, probably 2x wider than it is now, to make it stand out and figure out which tab is from which container at a glance.

**Comment by AnttiBoman** [comment]
Container marker to left: https://github.com/mbnuqw/sidebery/issues/1259#issuecomment-1734274673

Making it wider: https://github.com/mbnuqw/sidebery/issues/348#issuecomment-808217140
I had to add `#root` in front of the selector, though.

**Comment by mbnuqw** [comment]
You can also colorize the whole tab with container color: Sidebery settings > Tabs > Tabs colorization > Colorize tabs > Generate color from container.
