### ISSUE TITLE
Auto-snapshots are not created

### ISSUE THREAD

**Issue by dlobue** [mbnuqw/sidebery#489]
## Steps to reproduce
- Set auto-snapshot interval to 1 minute
- Set snapshots limit to 50 snapshots
- Exclude private windows: on
- show notification after snapshot creation: on
- Click `create snapshot` to create first snapshot.
- Click `view snapshot` and note a snapshot was created. also note the number of snapshots that exist.
- wait several minutes
- refresh the snapshots viewer page and note the number of snapshots

## Expected behavior
- there are more snapshots when looking at the snapshot viewer the second time than there were the first time.
- A notification to show every minute when the automatic snapshots are created.

## Actual behavior
- No snapshots are automatically created.
- no notifications are shown for auto-snapshots.

## Environment info

OS:  Linux
Firefox version:  89.0.2
Addon version:  4.9.4

also happens on:
OS:  Mac big sur
Firefox version:  92.0.1
Addon version:  4.9.4

<details><code>
{
  "settings": {
    "version": "4.9.4",
    "nativeScrollbars": false,
    "selWinScreenshots": false,
    "tabsCheck": true,
    "tabsFix": "notify",
    "markWindow": false,
    "markWindowPreface": "[Sidebery] ",
    "ctxMenuNative": false,
    "autoHideCtxMenu": "none",
    "ctxMenuRenderInact": true,
    "ctxMenuIgnoreContainers": "",
    "navBarLayout": "horizontal",
    "navBarInline": false,
    "hideAddBtn": false,
    "hideSettingsBtn": false,
    "navBtnCount": true,
    "hideEmptyPanels": true,
    "navMidClickAction": "none",
    "navSwitchPanelsWheel": false,
    "groupLayout": "grid",
    "skipEmptyPanels": false,
    "dndTabAct": false,
    "dndTabActDelay": 750,
    "dndTabActMod": "none",
    "dndExp": "pointer",
    "dndExpDelay": 0,
    "dndExpMod": "none",
    "stateStorage": "global",
    "warnOnMultiTabClose": "none",
    "activateOnMouseUp": true,
    "activateLastTabOnPanelSwitching": true,
    "showTabRmBtn": true,
    "showTabCtx": true,
    "hideInact": false,
    "activateAfterClosing": "prev_act",
    "activateAfterClosingPrevRule": "visible",
    "activateAfterClosingNextRule": "tree",
    "activateAfterClosingGlobal": false,
    "activateAfterClosingNoFolded": true,
    "activateAfterClosingNoDiscarded": true,
    "shiftSelAct": false,
    "askNewBookmarkPlace": false,
    "tabsRmUndoNote": false,
    "nativeHighlight": false,
    "tabsUnreadMark": false,
    "tabsReloadLimit": 5,
    "tabsReloadLimitNotif": true,
    "moveNewTabPin": "start",
    "moveNewTabParent": "first_child",
    "moveNewTabParentActPanel": false,
    "moveNewTab": "after",
    "pinnedTabsPosition": "panel",
    "pinnedTabsList": false,
    "pinnedAutoGroup": false,
    "tabsTree": true,
    "groupOnOpen": true,
    "tabsTreeLimit": 2,
    "hideFoldedTabs": false,
    "autoFoldTabs": false,
    "autoFoldTabsExcept": "none",
    "autoExpandTabs": false,
    "rmChildTabs": "folded",
    "tabsChildCount": true,
    "tabsLvlDots": true,
    "discardFolded": true,
    "discardFoldedDelay": 10,
    "discardFoldedDelayUnit": "min",
    "tabsTreeBookmarks": true,
    "treeRmOutdent": "branch",
    "bookmarksPanel": true,
    "warnOnMultiBookmarkDelete": "collapsed",
    "openBookmarkNewTab": true,
    "midClickBookmark": "delete",
    "actMidClickTab": false,
    "autoCloseBookmarks": false,
    "autoRemoveOther": false,
    "highlightOpenBookmarks": true,
    "activateOpenBookmarkTab": true,
    "showBookmarkLen": true,
    "bookmarksRmUndoNote": true,
    "fontSize": "m",
    "bgNoise": false,
    "animations": false,
    "animationSpeed": "fast",
    "theme": "default",
    "style": "dark",
    "sidebarCSS": false,
    "groupCSS": false,
    "snapNotify": true,
    "snapExcludePrivate": true,
    "snapInterval": 1,
    "snapIntervalUnit": "min",
    "snapLimit": 50,
    "snapLimitUnit": "snap",
    "hScrollThroughPanels": false,
    "scrollThroughTabs": "none",
    "scrollThroughVisibleTabs": false,
    "scrollThroughTabsSkipDiscarded": false,
    "scrollThroughTabsExceptOverflow": true,
    "scrollThroughTabsCyclic": false,
    "tabDoubleClick": "duplicate",
    "tabLongLeftClick": "none",
    "tabLongRightClick": "none",
    "tabsPanelLeftClickAction": "none",
    "tabsPanelDoubleClickAction": "tab",
    "tabsPanelRightClickAction": "menu",
    "tabsPanelMiddleClickAction": "tab",
    "syncName": "",
    "syncSaveSettings": false,
    "syncSaveCtxMenu": false,
    "syncSaveStyles": false,
    "syncAutoApply": false
  },
  "permissions": {
    "allUrls": false,
    "tabHide": true,
    "actualAllUrls": false,
    "actualTabHide": true
  },
  "storage": {
    "size": "155.3 kb",
    "props": {
      "disabledKeybindings": "937 b",
      "favAutoCleanTime": "10 b",
      "favUrls": "322 b",
      "favicons": "38.9 kb",
      "lastSnapTime": "13 b",
      "panelIndex": "1 b",
      "panels_v4": "775 b",
      "prevTabsData_v4": "9 b",
      "profileID": "14 b",
      "settings": "2.7 kb",
      "snapshots_v4": "73.2 kb",
      "tabsData_v4": "38.3 kb"
    }
  },
  "panels": [
    {
      "type": "bookmarks",
      "id": "bookmarks",
      "cookieStoreId": "bookmarks",
      "name": 9,
      "icon": "...",
      "bookmarks": true,
      "lockedPanel": false,
      "skipOnSwitching": false
    },
    {
      "type": "default",
      "id": "firefox-default",
      "name": 7,
      "icon": "...",
      "cookieStoreId": "firefox-default",
      "lockedTabs": false,
      "lockedPanel": false,
      "skipOnSwitching": false,
      "noEmpty": false,
      "newTabCtx": "none",
      "dropTabCtx": "none",
      "moveTabCtx": "none",
      "moveTabCtxNoChild": true
    },
    {
      "type": "tabs",
      "id": "jLh9Mg2U2Lbs",
      "name": 11,
      "icon": "...",
      "color": "...",
      "customIconSrc": "",
      "customIcon": "",
      "lockedTabs": false,
      "lockedPanel": false,
      "skipOnSwitching": false,
      "noEmpty": false,
      "newTabCtx": "none",
      "dropTabCtx": "none",
      "moveTabCtx": "none",
      "moveTabCtxNoChild": true,
      "urlRulesActive": false,
      "urlRules": ""
    }
  ],
  "containers": [],
  "cssVars": "TypeError: can't convert undefined to object",
  "windows": [
    {
      "state": "maximized",
      "incognito": false,
      "tabsCount": 510
    }
  ],
  "bookmarks": {
    "bookmarksCount": 9348,
    "foldersCount": 113,
    "separatorsCount": 1,
    "maxDepth": 3
  }
}
</code></details>

**Comment by chtiland** [comment]
I also have this problem (Under Linux and Firefox 94.0) and can't create snapshot manually too. 
Removing snapshots works (so that's not user's rights problem as I first thought).
Last snapshot on 2012.12.02.

**Comment by ongots** [comment]
After deleting snapshots_V4 in the Settings / Data section, the creation of snapshots worked for me.

**Comment by chtiland** [comment]
> After deleting snapshots_V4 in the Settings / Data section, the creation of snapshots worked for me.
👍🏼 
Also seem solved for me too, snapshot creation works now.

**Comment by mbnuqw** [comment]
Closing this as stale. Please, reopen if issue is reproduced in the latest version of Sidebery.
