### ISSUE TITLE
Reverse tabs, proxy.pac, icons loading

### ISSUE THREAD

**Issue by ongots** [mbnuqw/sidebery#49]
Крутое расширение, не хватает только:
1. Обратной последовательности вкладок
2. "URL автоматической настройки proxy" для proxy.pac АнтиЗапрет
3. Автоматической подгрузки значков закладок

**Comment by mbnuqw** [comment]
3. Вопросов нет - #50 :)
2. Вот это будет сложно реализовать, хотя идея хорошая. Позже посмотрю еще, может получится что-то сделать.
1. Не совсем понял - имеется ввиду порядок открытия новых вкладок?

**Comment by ongots** [comment]
Да, новые вкладки вверху старые внизу. Так реже приходится прокручивать список, и мышевозить ненадо вниз экрана:)
Я использовал css в Tab Center Redux
```
/* Использовать обратную последовательность */
#tablist {
  flex-direction: column-reverse;
  display: flex;
  flex: 0 0 auto;}
.tab.pinned {order: 1;}
```

**Comment by mbnuqw** [comment]
Closing in favor of #117
