### ISSUE TITLE
Window seclection in Sidebery panel

### ISSUE THREAD

**Issue by WintermuteTwin** [mbnuqw/sidebery#490]
## Description
I use the Titler extension to give each window a text label to categorize groups of tabs. It would be awesome to have easy access to that list of windows with a windows icon to the right of the down arrow next to "Sidebery" at the top of the panel.

**Comment by mbnuqw** [comment]
> with a windows icon to the right of the down arrow next to "Sidebery" at the top of the panel.

It's not part of Sidebery so it's impossible to implement.
For getting access to all windows track the #137 issue
