### ISSUE TITLE
Minor feature request: escape panel or container specific settings

### ISSUE THREAD

**Issue by Glokta0** [mbnuqw/sidebery#491]
## Description - feature request

Hi there! I love this tool - it's wonderful!
This is just a tiny feature request - that might improve usability for individuals like me that are usually glued to their keyboards.

When one configures a specific panel or container, a overlay opens to configure it. It would be awesome, to just quit/confirm this process by pressing escape. Currently, the overlays only close, if you click next to it. Please, correct me if I'm mistaken or if its just me - or if I just haven't found the shortcut yet!

Again, thanks a ton for crafting this tool,
Cheers!

**Comment by YuruiHong** [comment]
Same thing for my `Open this site in your assigned Container?` confirmation page. An Esc shortcut to remain in the previous container would be great.
