### ISSUE TITLE
Move to window function is not picking up the actual window name in most cases

### ISSUE THREAD

**Issue by WintermuteTwin** [mbnuqw/sidebery#493]
## Steps to reproduce
Using Titler extension to name each FF window. Have several open windows that are named.
Install Sidebery
right click on a tab and select move to window
all windows show up with their proper window name
add a new window and give it a title with Titler
right click on a tab and select move to window
the new window doesn't show the proper window name - just "Mozilla Firefox"

close browser and restart Firefox
right click on a tab and select move to window
none of the windows show up with their proper window name

## Expected behavior
Move to window shows all the proper window names with Titler titles

## Environment info

OS:  
Firefox version:  latest
Addon version:  latest

<details><code>

</code></details>

**Comment by megamorphg** [comment]
This would be great to have fixed. I'm also using Titler extension and have this issue.

**Comment by mbnuqw** [comment]
Should be fixed in the latest version.
