### ISSUE TITLE
Items fall out of groups after a restart of Firefox

### ISSUE THREAD

**Issue by mbetrifork** [mbnuqw/sidebery#496]
## Steps to reproduce
Mark some tabs, right click and place them in a group.
Close firefox
Restart the computer
Open firefox

## Expected behavior
Tabs still in the groups I created

## Actual behavior
Group is there, empty. All tabs which were in the group are now outside the group, as "siblings" of the group.

## Environment info

OS:  Ubuntu 21.04
Firefox version:  Version 93.0 64bit
Addon version:  4.9.4

<details><code>
Sorry I don't have any Debug Info button.

</code></details>

**Comment by mbnuqw** [comment]
Should be fixed in the latest version.
