### ISSUE TITLE
Close multiple tabs.

### ISSUE THREAD

**Issue by bjwest** [mbnuqw/sidebery#508]
## Description
Would it be possible to add the ability to close multiple tabs, allowing closing to the bottom and top from the current tab?  This is a feature I use multiple times a day and sorely miss.

**Comment by SeerLite** [comment]
What you can do for now is ctrl+click your current tab, then shift+click the top/bottom tab to get them all selected and then right click any -> close.

**Comment by unit-of-inductance** [comment]
It would be great if this would also work using `ctrl+w` as is the case for the Firefox's normal horizontal tab. The fact that this does not work in Sidebery annoys me surprisingly often.

Edit: Ah sorry this is already tracked in #748, where also the Keybinding option "Close selected or active tab / Delete selected bookmarks" is mentioned.

**Comment by mbnuqw** [comment]
Implemented in the latest version (check the context menu editor)
