### ISSUE TITLE
Add removal of "Default" (tabs) panel?

### ISSUE THREAD

**Issue by Ralithune** [mbnuqw/sidebery#513]
I know, I'm sorry, the whole point of this addon is to manage tabs on the side but I'm using it for a more-compact-bookmarks-sidebar.  I have to change the view to the bookmarks on every single tab I swap to, and I just don't want to use Sidebery to manage my tabs.

Firefox lets you put bookmarks on the side, yes, but they are way too spaced out - the beginnings of each of the names of a lot of my bookmarks are all the same, so I don't see their differences until I get 20-30 characters in.

Sidebery offers a great, more compact version of that, but I can't turn off the tabs list.

Thanks for making the addon at all :)

**Comment by mbnuqw** [comment]
Available in the latest version
