### ISSUE TITLE
I can't find Sidebery in Firefox context menu

### ISSUE THREAD

**Issue by MW-J97** [mbnuqw/sidebery#514]
Hi there, 
First, thank you so much for this great tool. It's really fantastic. 
Please, I didn't find the extension in the Firefox context menu.
What I mean is:- I want to right-click on the tabs in Firefox toolbar, not the sidebar, and then group them from context menu. 
So, I need to be like those extensions in this screenshot, https://i.imgur.com/Ar2yH8p.png.

How can I do this??
Thanks in advance.

**Comment by mbnuqw** [comment]
Not planned
