### ISSUE TITLE
Discarded tab is being selected even with "Ignore discarded tabs = on"

### ISSUE THREAD

**Issue by pintassilgo** [mbnuqw/sidebery#515]
## Steps to reproduce
1. Install Sidebery and don't change any setting. Default is: `After closing current tab activate → next tab`, `Ignore discarded tabs → on`.
2. Open a bunch of tabs in root level.
3. Close the first tab.
4. The second tab (now the first), if opened, will be selected.
5. Reopen the closed tab by pressing Ctrl+Shift+T.
6. Right click the second tab and click `Unload`.
7. Again, with first tab selected, close it.

## Expected behavior
The second tab (now it's the first) is discarded, so it shouldn't be selected. The next open tab should be selected instead.

## Actual behavior
The discarded tab is selected.

Sidebery 4.9.4

**Comment by mbnuqw** [comment]
Fixed in the latest version
