### ISSUE TITLE
Unload active tab is broken if "After closing current tab activate → none"

### ISSUE THREAD

**Issue by pintassilgo** [mbnuqw/sidebery#516]
## Steps to reproduce
1. Set `After closing current tab activate → none`.
2. Right-click active tab and click `Unload`.

## Expected behavior
The tab should be discarded and another tab should be selected.

## Actual behavior
Nothing happens and you can see an error thrown in console.

Sidebery 4.9.4.

**Comment by mbnuqw** [comment]
Fixed in the latest version
