### ISSUE TITLE
Automatic snapshots

### ISSUE THREAD

**Issue by ongots** [mbnuqw/sidebery#52]
Добавьте снепшоты по расписанию, с указанием интервала(например каждые 2 часа) и количества(например 10). Я дважды за пол года терял сессии из-за жесткой перезагрузки системы. Firefox дает только один шанс на восстановление, если его упустить вкладки будут утеряны. Поэтому приходится использовать Session Boss для автоматического сохранения сессий.

В каком файле Sidebery хранит настройки и снепшоты? Чтобы переносить, бекапить, восстанавливать.

css для скрытия боковой панели можно добавить в описание:
```
/* Hiding sidebar */
#sidebar{height: 97vh}
#appcontent{margin-left: 30px}
#sidebar-box:hover, #sidebar{max-width: 240px}
#sidebar-box{
    overflow: hidden;
    max-width: 30px;
    position: fixed;
    transition: 90ms}
[inFullscreen] #sidebar{height: 100vh}
[inFullscreen] #appcontent{margin-left: 1px}
[inFullscreen] #sidebar-box:hover, #sidebar{max-width: 240px}
[inFullscreen] #sidebar-box{
    overflow: hidden;
    max-width: 1px;
    position: fixed;
    top: 1px;
    transition: 90ms}
```

**Comment by mbnuqw** [comment]
Да, сейчас функция снепшотов номинальная. В планах создавать снепшоты при любом изменении списка табов, добавить возможность экспорта в файл или закладки.

`переносить, бекапить, восстанавливать` - верно, стоило сразу об этом подумать :thinking:
Добавлю экспорт  #53
и синхронизацию настроек #54
Сейчас все данные хранятся в локальном сторе аддона - т.е. где-то в .sqlite файлике в папке с профилем и достать эти данные будет проблематечно.

За css огромное спасибо, добавлю.

**Comment by ongots** [comment]
"Длительное нажатие кнопки мыши по табу" много ложных срабатываний, нужно увеличить время нажатия.

Так как я использую CSS для скрытия вкладок, хотелось бы передвинуть кнопку вкладок влево(чтобы она была в один ряд с значками сайтов), кнопку закладок можно расположить слева от кнопки настроек.

Я обновил CSS для скрытия вкладок выше.

**Comment by mbnuqw** [comment]
Открыл #57 для точной настройки длительного нажатия.

В след. версии (скоро) будет добалена возможность менять css, так что проблема с кастомизацией должна решиться.

**Comment by ongots** [comment]
Нужно предотвратить автоматический переход между контейнерами при закрытии вкладки. Опция "Заблокировать панель" не помогает. Чтобы предотвратить переключение на другой-контейнер при закрытии вкладки

**Comment by mbnuqw** [comment]
Implemented in the latest version.
