### ISSUE TITLE
[Feature Request] Hide title bar

### ISSUE THREAD

**Issue by nulledone** [mbnuqw/sidebery#520]
![1](https://user-images.githubusercontent.com/29547468/143661789-a7510e92-cca4-47e4-9c6f-df535f8b92bd.png)

**Comment by pintassilgo** [comment]
Extensions can't do that. But there's [this](https://github.com/mbnuqw/sidebery/wiki/Firefox-Styles-Snippets-(via-userChrome.css)) (look for "*Hide sidebar top-menu*").

**Comment by nulledone** [comment]
Nope, you might be wrong.
![1](https://user-images.githubusercontent.com/29547468/143675361-b82ce0fe-7027-42f1-93e6-0553d913ead9.png)
 
I've been using TST for a while and it can do that (probably does it differently). Anyway it also shows my firefox custom theme as it's background which looks way nicer.

**Comment by pintassilgo** [comment]
TST also can't do that. Install it in a fresh new profile and you'll see it.

I guess you did [this](https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#hide-the-tree-style-tab-header-at-the-top-of-the-sidebar) (or something equivalent) a time ago and forgot about it.

**Comment by mbnuqw** [comment]
Impossible to implement. Use userChrome.css hacks
e.g. when Sidebery is active
```css
#sidebar-box[sidebarcommand="_3c078156-979c-498b-8990-85f7987dd929_-sidebar-action"] #sidebar-header {
  display: none;
}
```
