### ISSUE TITLE
Integrate bookmark toolbar right under title bar

### ISSUE THREAD

**Issue by nulledone** [mbnuqw/sidebery#521]
![2](https://user-images.githubusercontent.com/29547468/143661834-a2e3b1ce-189f-41ab-b4d5-d4c31cd0deda.png)

**Comment by mbnuqw** [comment]
It's possible now to add shortcuts (configurable URL and container) in New Tab Bar (under the tabs). Top position for this bar: #1279, [workaround](https://github.com/mbnuqw/sidebery/issues/1452#issuecomment-1942499345). Additional bookmarks toolbar is not planned.
