### ISSUE TITLE
Move tabs between windows UI shows wrong titles

### ISSUE THREAD

**Issue by Addlai** [mbnuqw/sidebery#529]
## Steps to reproduce
Context click on a tab in Sideberry and select the "Move to window..." icon.

## Expected behavior
The choices will have titles and icons in agreement with what the Firefox Window menu shows

## Actual behavior
Usually, there are just generic titles. However, if I close Sideberry and reopen it, the correct titles and icons appear.

## Environment info

OS:  
Firefox version:  92.0.2
Addon version:  4.9.4

<details><code>

{
  "settings": {
    "version": "4.9.4",
    "nativeScrollbars": true,
    "selWinScreenshots": false,
    "tabsCheck": true,
    "tabsFix": "notify",
    "markWindow": false,
    "markWindowPreface": "[Sidebery] ",
    "ctxMenuNative": false,
    "autoHideCtxMenu": "none",
    "ctxMenuRenderInact": true,
    "ctxMenuIgnoreContainers": "",
    "navBarLayout": "hidden",
    "navBarInline": false,
    "hideAddBtn": false,
    "hideSettingsBtn": false,
    "navBtnCount": true,
    "hideEmptyPanels": true,
    "navMidClickAction": "none",
    "navSwitchPanelsWheel": true,
    "groupLayout": "grid",
    "skipEmptyPanels": false,
    "dndTabAct": true,
    "dndTabActDelay": 750,
    "dndTabActMod": "none",
    "dndExp": "pointer",
    "dndExpDelay": 0,
    "dndExpMod": "none",
    "stateStorage": "global",
    "warnOnMultiTabClose": "collapsed",
    "activateOnMouseUp": true,
    "activateLastTabOnPanelSwitching": true,
    "showTabRmBtn": true,
    "showTabCtx": true,
    "hideInact": false,
    "activateAfterClosing": "next",
    "activateAfterClosingPrevRule": "visible",
    "activateAfterClosingNextRule": "tree",
    "activateAfterClosingGlobal": false,
    "activateAfterClosingNoFolded": true,
    "activateAfterClosingNoDiscarded": true,
    "shiftSelAct": true,
    "askNewBookmarkPlace": false,
    "tabsRmUndoNote": true,
    "nativeHighlight": false,
    "tabsUnreadMark": false,
    "tabsReloadLimit": 5,
    "tabsReloadLimitNotif": true,
    "moveNewTabPin": "start",
    "moveNewTabParent": "last_child",
    "moveNewTabParentActPanel": false,
    "moveNewTab": "end",
    "pinnedTabsPosition": "panel",
    "pinnedTabsList": false,
    "pinnedAutoGroup": false,
    "tabsTree": true,
    "groupOnOpen": true,
    "tabsTreeLimit": 1,
    "hideFoldedTabs": false,
    "autoFoldTabs": false,
    "autoFoldTabsExcept": "none",
    "autoExpandTabs": false,
    "rmChildTabs": "none",
    "tabsChildCount": true,
    "tabsLvlDots": false,
    "discardFolded": false,
    "discardFoldedDelay": 0,
    "discardFoldedDelayUnit": "sec",
    "tabsTreeBookmarks": true,
    "treeRmOutdent": "branch",
    "bookmarksPanel": true,
    "warnOnMultiBookmarkDelete": "collapsed",
    "openBookmarkNewTab": false,
    "midClickBookmark": "open_new_tab",
    "actMidClickTab": false,
    "autoCloseBookmarks": false,
    "autoRemoveOther": false,
    "highlightOpenBookmarks": false,
    "activateOpenBookmarkTab": false,
    "showBookmarkLen": false,
    "bookmarksRmUndoNote": true,
    "fontSize": "xxl",
    "bgNoise": false,
    "animations": false,
    "animationSpeed": "fast",
    "theme": "default",
    "style": "light",
    "sidebarCSS": true,
    "groupCSS": false,
    "snapNotify": true,
    "snapExcludePrivate": false,
    "snapInterval": 0,
    "snapIntervalUnit": "min",
    "snapLimit": 0,
    "snapLimitUnit": "snap",
    "hScrollThroughPanels": false,
    "scrollThroughTabs": "panel",
    "scrollThroughVisibleTabs": false,
    "scrollThroughTabsSkipDiscarded": false,
    "scrollThroughTabsExceptOverflow": true,
    "scrollThroughTabsCyclic": true,
    "tabDoubleClick": "none",
    "tabLongLeftClick": "none",
    "tabLongRightClick": "none",
    "tabsPanelLeftClickAction": "none",
    "tabsPanelDoubleClickAction": "tab",
    "tabsPanelRightClickAction": "menu",
    "tabsPanelMiddleClickAction": "tab",
    "syncName": "",
    "syncSaveSettings": false,
    "syncSaveCtxMenu": false,
    "syncSaveStyles": false,
    "syncAutoApply": false
  },
  "permissions": {
    "allUrls": false,
    "tabHide": false,
    "actualAllUrls": false,
    "actualTabHide": false
  },
  "storage": {
    "size": "2.1 mb",
    "props": {
      "containers_v4": "1.2 kb",
      "cssVars": "1.7 kb",
      "disabledKeybindings": "24 b",
      "expandedBookmarks": "2 b",
      "favAutoCleanTime": "10 b",
      "favUrls": "78.7 kb",
      "favicons": "1.8 mb",
      "groupCSS": "2 b",
      "panelIndex": "1 b",
      "panels_v4": "446 b",
      "prevTabsData_v4": "117.7 kb",
      "profileID": "14 b",
      "settings": "2.7 kb",
      "sidebarCSS": "8 b",
      "tabsData_v4": "117.7 kb"
    }
  },
  "panels": [
    {
      "type": "bookmarks",
      "id": "bookmarks",
      "cookieStoreId": "bookmarks",
      "name": 9,
      "icon": "...",
      "bookmarks": true,
      "lockedPanel": false,
      "skipOnSwitching": false
    },
    {
      "type": "default",
      "id": "firefox-default",
      "name": 7,
      "icon": "...",
      "cookieStoreId": "firefox-default",
      "lockedTabs": false,
      "lockedPanel": false,
      "skipOnSwitching": false,
      "noEmpty": false,
      "newTabCtx": "none",
      "dropTabCtx": "none",
      "moveTabCtx": "none",
      "moveTabCtxNoChild": true
    }
  ],
  "containers": [
    {
      "id": "firefox-container-1",
      "name": 8,
      "icon": "...",
      "color": "...",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-2",
      "name": 4,
      "icon": "...",
      "color": "...",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-3",
      "name": 7,
      "icon": "...",
      "color": "...",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-4",
      "name": 8,
      "icon": "...",
      "color": "...",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-6",
      "name": 11,
      "icon": "...",
      "color": "...",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    }
  ],
  "cssVars": {
    "bg": "#ffffff",
    "tabs_height": "34px",
    "tabs_indent": "30px",
    "tabs_bg_hover": "#ff9090",
    "tabs_bg_active": "#ffff00",
    "tabs_activated_bg": "#fef4c0",
    "tabs_selected_bg": "#458fff",
    "tabs_border": "none",
    "tabs_lvl_indicator_bg": "#eaff33ff",
    "bookmarks_folder_open_fg": "#eae6e3ff"
  },
  "sidebarCSSLen": 3,
  "groupCSSLen": 0,
  "windows": [
    {
      "state": "normal",
      "incognito": false,
      "tabsCount": 46
    },
    {
      "state": "normal",
      "incognito": false,
      "tabsCount": 68
    },
    {
      "state": "normal",
      "incognito": false,
      "tabsCount": 10
    },
    {
      "state": "normal",
      "incognito": false,
      "tabsCount": 54
    },
    {
      "state": "normal",
      "incognito": false,
      "tabsCount": 53
    },
    {
      "state": "normal",
      "incognito": false,
      "tabsCount": 60
    },
    {
      "state": "normal",
      "incognito": false,
      "tabsCount": 35
    },
    {
      "state": "normal",
      "incognito": false,
      "tabsCount": 18
    },
    {
      "state": "normal",
      "incognito": false,
      "tabsCount": 239
    },
    {
      "state": "normal",
      "incognito": false,
      "tabsCount": 12
    },
    {
      "state": "normal",
      "incognito": false,
      "tabsCount": 141
    },
    {
      "state": "normal",
      "incognito": false,
      "tabsCount": 47
    },
    {
      "state": "normal",
      "incognito": false,
      "tabsCount": 131
    },
    {
      "state": "normal",
      "incognito": false,
      "tabsCount": 27
    },
    {
      "state": "normal",
      "incognito": false,
      "tabsCount": 18
    },
    {
      "state": "normal",
      "incognito": false,
      "tabsCount": 20
    },
    {
      "state": "normal",
      "incognito": false,
      "tabsCount": 22
    },
    {
      "state": "normal",
      "incognito": false,
      "tabsCount": 24
    }
  ],
  "bookmarks": {
    "bookmarksCount": 3487,
    "foldersCount": 245,
    "separatorsCount": 40,
    "maxDepth": 5
  }
}
</code></details>

**Comment by mbnuqw** [comment]
Should be fixed in the latest version
