### ISSUE TITLE
Send all tabs from panel to bookmarks folder

### ISSUE THREAD

**Issue by rjameson3** [mbnuqw/sidebery#532]
## Description
I am a past user of TreeTabs and starting testing SideBery in hopes of getting the same tab management and reliable (too many times Iost TreeTabs tab order, or worse - grouping).  I tend to have 100+ tabs open and live in live tabs.   When they get too many or the project I am working on is finished,  I send all tabs from the group to a folder of bookmarks for archive.

I did not see a way to send all tabs from a panel to a book mark folder - so thought would be a good feature request.

**Comment by kishvanchee** [comment]
@rjameson3 I was looking for this feature as well. From the README

> You can drag and drop links or tabs to create bookmarks and vice-versa.

I found the following two ways to achieve what we are looking for (I guess). Previously I used to select all tabs and bookmark them under one folder. Following are the approaches I've found to work with Sidebery.

### Method One
1. create a new bookmarks folder on the bookmarks panel
2. Select the tabs you want on sidebery (Ctrl / Shift select)
3. Drag them from the sidebery panel to the bookmarks panel into the desired bookmarks folder.
4. This creates directories and subdirectories in your bookmarks for each nested tabs with the parent tab being the top directory's name for each nesting.

### Method Two
1. Select the tabs you want to bookmark (Ctrl / Shift)
2. Right click and select the star for bookmarking them.
3. This will create a new folder with the top directory name as same as the top tab. Each directory gets created similar to the previous method.

I have tested this on Firefox 95. If there are better ways to do this then others can pitch in on this.

**Comment by arthurEspooner** [comment]
adding all from a panel seems a little weird; the context menus are already pretty cluttered with icons that aren't so clear. just use alt/shift to select which ones in the tab and use method two above. very easy.

**Comment by mbnuqw** [comment]
Available from v5.0.0
