### ISSUE TITLE
Tab flip.

### ISSUE THREAD

**Issue by guigirl42** [mbnuqw/sidebery#541]
## Description
Mimic the behaviour of _TreeStyleTab_'s companion extension _Tab flip for Tree Style Tab_ [https://framagit.org/ariasuni/tst-tabflip], please.

"_Clicking active tab activate the last active one. It allows you to switch quickly between two tabs without moving the mouse, very useful when the two tabs are far away_".

In the absence of a built-in tab flip function in _Sidebery_, i use either good old Ctrl+Tab to trigger the tab flip, or my custom mouse-gesture i configured in _Gesturefy_. However, this action exists natively in Vivaldi browser, & for years is also available in FF's _TreeStyleTab_ Add-On, & is **very efficient for one's workflow**.

**Comment by megamorphg** [comment]
Motion to close as this feature exists in v5:
![image](https://user-images.githubusercontent.com/1782353/164717819-a354d8b0-d820-45d0-a700-4b54e4adf9a7.png)

**Comment by guigirl42** [comment]
Ok thanks. I know this is a rotten question, but do you have any approximate idea of release date for this next version?

**Comment by mbnuqw** [comment]
Well, I don't set any deadlines but it's at least a month of pre-release work.

**Comment by MrQwerky** [comment]
Couldn't find this setting in v5.0.0.b24; perhaps it will be in stable v5?  I agree this is a desirable feature; I seem to recall that this used to be native functionality in Firefox a long time ago.

**Comment by guigirl42** [comment]
> Couldn't find this setting in v5.0.0.b24

Oh no, that's worrisome / disappointing. 😟

Fwiw, it took me a long time to _fully_ migrate my workflow from `TreeStyleTab` AddOn to `Sidebery` AddOn, & since managing that, IMO `Sidebery` is fantastic, **but**... i absolutely do miss _not_ having the Tab-Flip / Backward-Activation function. I am really hanging out for the next update, so now hearing it might not be included, is upsetting.

**Comment by MrQwerky** [comment]
> Here is exactly where the option is located in v5: ![image](https://user-images.githubusercontent.com/1782353/178151186-6804de86-275f-465d-9ee1-9b5ab65c7d98.png)

Thank you. Have found and set the option, and works as expected.
 
> Also, I personally use the previous/next tab keybindings more since I hate having to move the mouse to click the tab and sometimes flip through 3+ at a time.

Like you, I am more keyboard oriented than mouse oriented, but I am confused by the above.  Do you mean native Firefox keybindings (Ctrl+Tab, Shift+Ctrl+Tab) set to use MRU order?  I prefer sequential order rather than MRU.

Or, do you mean some Sidebery keybindings?  In that case, I'm not sure which ones you refer to.

My preference would be for Sidebery to have a keybinding (perhaps called 'Prior Tab'?) that would simply move to the last focused tab, just as is done now by mouse clicking with this setting we are discussing.  Press the key again, and go back to the first tab.  Successive pressings going back and forth between two tabs.  This way, only a single key is required, rather than two keys in MRU order.  And, it is better than using the mouse, because the two tabs may be far enough apart in the panel's list that they are not both visible at the same time.

**Comment by MrQwerky** [comment]
Sadly, I cannot get either of those Sidebery keybindings to perform any action at all, no matter what keys I assign to them.  I have tried assigning keys to them both by Sidebery's own settings, and by FF Add-Ons settings.  Nothing seems to work.

**Comment by guigirl42** [comment]
@megamorphg 
>  "beta" is just a label in this case. **It is better than v4 in almost every way and is actually more stable IMO**. I have been using it for the past months and have 1000+ tabs for work and personal windows and am loving it, especially after the most recent update.

Ta heaps for this great advice. I took the leap, & now i am [as Max would say to 99] _"loving it"_. 😁 
***

@mbnuqw 
> still no even estimate release dates, sorry.

That's ok, i understand [& agree that naggy pests like me can be _so annoying_ 🤪]. Anyway, per above, i'm now using your Beta, & IMO it's _wonderful_. **Congratulations on all your fine work** ... & specifically wrt _this_ current Issue, the new `Tab Flip` function works exactly how i wanted. 😀 From my perspective anyway, this issue can now be _Closed_, if you wish. 
***

@mbnuqw A quick off-topic question [if you wish i could create a new Issue for this]: do you envisage one day including on-hover tab-thumbnails in `Sidebery`? If you don't know what i mean, look at the Vivaldi browser, which does it really well [as did its spiritual forebear, Opera Presto].

**Comment by mbnuqw** [comment]
@guigirl42, tabs previews are already [in progress](https://github.com/mbnuqw/sidebery/issues/301). I'll leave this issue open until this feature is merged into stable version.

**Comment by guigirl42** [comment]
@mbnuqw Oh how exciting; i can't wait [heehee]. Good luck with it!

**Comment by guigirl42** [comment]
Is there a way to colour the audio-icon of a tab, _separate_ to the tab's name-font?

![](https://i.postimg.cc/BnxkdKrS/20220712-211723.png)

**Comment by jathek** [comment]
> Is there a way to colour the audio-icon of a tab, _separate_ to the tab's name-font?

Add this to sidebery's sidebar styles page in the options (in v5, but might work in v4 too).
```css
.Tab .audio > svg {
  fill: red !important;
}
```

**Comment by guigirl42** [comment]
Oh wow, _marvellous_ -- thanks so much, @nearcatch  🤗

**Comment by eternaleye** [comment]
Is there any chance we could get a keybinding for tab flip? I currently use the prev/next active tab bindings, but I'd rather use a single binding to toggle between the most recent pair.

**Comment by mbnuqw** [comment]
Resolved in v5.0.0
