### ISSUE TITLE
Clicking bookmark button no longer toggles back and forth between start and end of bookmarks.

### ISSUE THREAD

**Issue by shazzap** [mbnuqw/sidebery#543]
## Steps to reproduce

Click Sidebery's bookmark button. Bookmarks are now displayed. Click the bookmark button again. Nothing happens. Click it yet again, still nothing happens.

## Expected behavior

With previous versions of Sidebery, clicking the bookmark button again would automatically scroll to the bottom of the bookmark list. Clicking it yet again would auto-scroll back to the top of the list. This was a very convenient feature to quickly traverse the bookmark list.

## Actual behavior

This no longer works with with version.  4.10.0

The first press of the bookmarks button does display the bookmarks. However any clicks of the button do nothing. The bookmark list is no longer auto-scrolled to the bottom (or top) of the list.

## Environment info

OS:  Windows 10
Firefox version:  95.0
Addon version:   4.10.0

<details><code>

</code></details>

**Comment by mbnuqw** [comment]
From v4.10.0 this function is under option "Settings -> Navigation bar -> Left click on active bookmarks panel"
