### ISSUE TITLE
Container Proxy Deosn't Run in Background

### ISSUE THREAD

**Issue by bah2830** [mbnuqw/sidebery#55]
This extension has been amazing, it has quickly become my favorite sidebar tab manager. With the ability to set proxies per container it makes it that much more useful.

One issue I'm noticing though is if I have tabs opened in a proxied container. When I close the sidebar the proxied tabs are no longer going through the proxy. I'm not sure if this is a limitation of the extension framework or if there is something that can be done. It may even be a setting that I'm missing and this isn't a bug at all.

#### Additional Details:
- version: 2.4.2
- proxy type: socks5 with DNS proxy
    - This is a ssh tunnel to a jump box for work

**Comment by mbnuqw** [comment]
Yeah, it'll be possible in next version (v3.0.0) I'm working on. This is related with #35.

**Comment by mbnuqw** [comment]
Implemented in the latest version.
