### ISSUE TITLE
[Feature request] Automatic snapshot/export to file

### ISSUE THREAD

**Issue by meshy** [mbnuqw/sidebery#551]
## Description

I recently lost all my snapshots. I presume that this is because of a corrupt firefox extension database (see #550).

Now that I've got the extension working again, I would really like to have been able to restore from a snapshot, but it seems that the snapshots are also stored in that database, and so were lost (or were lost when I uninstalled/re-installed the extension).

I notice that there is an existing "export" feature. Might there be a way to combine this with the snapshots, so that we could have regular automatic backups to disk?

Aside: Thank you for this extension! Of all the extensions I have, this one is the best by far!

**Comment by Heyian** [comment]
@llc0930 I suggest we close this issue, this is working now.

**Comment by llc0930** [comment]
Um? So why tag me?

**Comment by Heyian** [comment]
> Um? So why tag me?

I saw you were involved in a couple of issues and I thought you were a maintainer. My mistake.
