### ISSUE TITLE
Tree structure for pinned tabs

### ISSUE THREAD

**Issue by DmitrySamoylov** [mbnuqw/sidebery#553]
Hi! In settings, I can enable titles of pinned tabs. This way all pinned tabs are structured as a non-scrollable plain list. It'd be useful to manage pinned tabs like a tree, not a list. The reasoning is that I'd like to have a non-scrollable tree of tabs at the top and a scrollable part at the bottom, just like it's done in the Firefox tab bar: pinned tabs are not scrollable and unpinned are scrollable.

**Comment by mbnuqw** [comment]
Not planned
