### ISSUE TITLE
Switch to the active panel after opening a tab from Bookmarks panel

### ISSUE THREAD

**Issue by CrendKing** [mbnuqw/sidebery#555]
## Description
Not sure if this is asked before. When I open tab from the Sidebery Bookmarks panel, currently (v4.10.0) Sidebery stays at the Bookmarks panel. Instead, I want Sidebery to switch to the panel the new tab belongs to immediately. I do not find any setting related.

**Comment by mbnuqw** [comment]
Available in the latest version: In bookmarks panel, setting "Switch back to previously active tabs panel after mouse leave"

**Comment by CrendKing** [comment]
Thank you! I do see the config code (`conf.tempMode`) and i18n label exist in repo, but I don't see the setting in the extension (v5.2.0, latest in Firefox). What's weird is, those code were already introduced 2 years ago.

![S](https://github.com/mbnuqw/sidebery/assets/975235/d42090ac-d6a5-4798-9f28-c9f92a6aa38c)

**Comment by mbnuqw** [comment]
The setting is in config popup of the bookmarks panel: Sidebery settings > Navigation bar > Click on bookmark panel element > "Switch back to..."
