### ISSUE TITLE
autoshow and authohide with mouse hover? (floating above content)

### ISSUE THREAD

**Issue by jorjio** [mbnuqw/sidebery#556]
## Description
Hi,
Maybe I miss something, But I am trying to see if showing and hiding the sidebar (or parts of it) while mouse hover is possible?
another suggestion - if possible that the sidebar will float over the page, and will not change the size of the web page.
Please see screen capture when using tree-style-tab extension on Firefox.

![firefox_6MsEOAlwnU](https://user-images.githubusercontent.com/5610394/150448487-a1b41406-d853-44da-b77a-0399dbe8c637.gif)
.

Thanks so much for a gorgeous addon!!

**Comment by NotSoMewwo** [comment]
I use this one as my CSS for sidebery, although it affects all sidebars such as bookmarks.

```
*#sidebar-box + #sidebar-splitter {
  display: none !important;
}

#sidebar-box #sidebar-header {
  visibility: collapse;
}


#sidebar-box {
  overflow: hidden !important;
  position: relative !important;
  transition: all 300ms !important;
  min-width: var(--thin-tab-width) !important;
  max-width: var(--thin-tab-width) !important;
  z-index: 1;
}
#sidebar-box:hover,
#sidebar-box #sidebar {
  transition: all 200ms !important;
  min-width: var(--wide-tab-width) !important;
  max-width: var(--wide-tab-width) !important;
  margin-right: calc((var(--wide-tab-width) - var(--thin-tab-width)) * -1) !important;
  z-index: 1;
}

:root { --thin-tab-width: 32px; }
:root { --wide-tab-width: 300px; }
```

**Comment by jorjio** [comment]
great!
Thanks.
