### ISSUE TITLE
Expanded folder (color, color on hover, color on click) are not displayed as specified

### ISSUE THREAD

**Issue by conniff1** [mbnuqw/sidebery#561]
Hello,
great add in!

I found a small bug: 

## Steps to reproduce
Sidebery/Settings/Styles editor/Expanded folder color e.g. set to the color blue

## Expected behavior
Bookmarks/Expanded folders should be blue

## Actual behavior
Bookmarks/Expanded folders always has the color white (see video)

Also
- "Expanded folder color on hover" and
- "Expanded folder color on click"
do not have the set colors.

## Environment info
OS: win
Firefox: 96.0.3
Addon: 4.10.0

https://user-images.githubusercontent.com/44544921/151677792-7dc947aa-f588-4067-8e7a-c6e5bd17b51a.mp4

greeting
Conniff

**Comment by mbnuqw** [comment]
Closing as stale. In v5 use General/"Frame foreground" and Bookmarks/"Node activated foreground"
