### ISSUE TITLE
Mouse wheel scrolling too quickly fails to switch through a corresponding number of tabs

### ISSUE THREAD

**Issue by y4mz** [mbnuqw/sidebery#564]
## Steps to reproduce
- Enable 'Switch tabs with scroll wheel'
- Wheel scroll quickly over tabs, e.g. 7 wheel notches

## Expected behavior
Switches through 7 tabs.

## Actual behavior
Switches through less than 7 tabs.

## Environment info
OS: Linux
Firefox version: 96.0.3
Addon version: 4.10.0

**Comment by y4mz** [comment]
This seems to be fixed in version 5.0.0.

**Comment by mbnuqw** [comment]
Fixed in the latest version.
