### ISSUE TITLE
Bookmarks to Firefox settings pages don't open

### ISSUE THREAD

**Issue by questionmuppet** [mbnuqw/sidebery#567]
Firefox settings pages don't open properly when launched from the Sidebery Bookmarks panel.

The following bookmarks open their respective settings pages when launched from the Firefox Bookmarks page.
- about:preferences
- about:config
- about:profiles

Opening these from Sidebery sends you to a separate page where you have to manually copy-paste the link into the address bar. It would be nice if these links opened normally like any other.

I've noticed the "Bookmark Manager and Viewer" plugin can't launch these bookmarks either, so I'm wondering if there's a Firefox permissions issue preventing it.

## Steps to reproduce
1. Create a bookmark to a Firefox settings page (about:preferences, et.al.)
2. Open Sidebery Bookmarks panel
3. Click on the new bookmark

## Expected behavior
Firefox opens corresponding settings page.

## Actual behavior
Firefox opens tab with text "about:preferences" and copy button.

## Environment info
OS:  Ubuntu 20.04.3 LTS
Firefox version: 97.0b9
Addon version: 4.10.0

<details><code>{
  "settings": {
    "version": "4.10.0",
    "nativeScrollbars": false,
    "selWinScreenshots": true,
    "tabsCheck": true,
    "tabsFix": "notify",
    "markWindow": false,
    "markWindowPreface": "[Sidebery] ",
    "ctxMenuNative": false,
    "autoHideCtxMenu": "none",
    "ctxMenuRenderInact": true,
    "ctxMenuIgnoreContainers": "",
    "navBarLayout": "horizontal",
    "navBarInline": false,
    "hideAddBtn": false,
    "hideSettingsBtn": false,
    "navBtnCount": true,
    "hideEmptyPanels": true,
    "navActTabsPanelLeftClickAction": "none",
    "navActBookmarksPanelLeftClickAction": "scroll",
    "navMidClickAction": "none",
    "navSwitchPanelsWheel": true,
    "groupLayout": "grid",
    "skipEmptyPanels": true,
    "dndTabAct": true,
    "dndTabActDelay": 750,
    "dndTabActMod": "none",
    "dndExp": "hover",
    "dndExpDelay": 1000,
    "dndExpMod": "none",
    "stateStorage": "global",
    "warnOnMultiTabClose": "any",
    "activateOnMouseUp": false,
    "activateLastTabOnPanelSwitching": true,
    "showTabRmBtn": true,
    "showTabCtx": true,
    "hideInact": true,
    "activateAfterClosing": "next",
    "activateAfterClosingPrevRule": "tree",
    "activateAfterClosingNextRule": "tree",
    "activateAfterClosingGlobal": false,
    "activateAfterClosingNoFolded": true,
    "activateAfterClosingNoDiscarded": true,
    "shiftSelAct": true,
    "askNewBookmarkPlace": false,
    "tabsRmUndoNote": true,
    "nativeHighlight": true,
    "tabsUnreadMark": true,
    "tabsReloadLimit": 0,
    "tabsReloadLimitNotif": true,
    "tabsPanelSwitchActMove": false,
    "moveNewTabPin": "end",
    "moveNewTabParent": "first_child",
    "moveNewTabParentActPanel": false,
    "moveNewTab": "end",
    "pinnedTabsPosition": "top",
    "pinnedTabsList": false,
    "pinnedAutoGroup": true,
    "tabsTree": true,
    "groupOnOpen": true,
    "tabsTreeLimit": 1,
    "hideFoldedTabs": true,
    "autoFoldTabs": false,
    "autoFoldTabsExcept": 5,
    "autoExpandTabs": false,
    "rmChildTabs": "none",
    "tabsChildCount": true,
    "tabsLvlDots": true,
    "discardFolded": false,
    "discardFoldedDelay": 0,
    "discardFoldedDelayUnit": "sec",
    "tabsTreeBookmarks": true,
    "treeRmOutdent": "first_child",
    "bookmarksPanel": true,
    "warnOnMultiBookmarkDelete": "collapsed",
    "openBookmarkNewTab": true,
    "midClickBookmark": "edit",
    "actMidClickTab": false,
    "autoCloseBookmarks": false,
    "autoRemoveOther": false,
    "highlightOpenBookmarks": true,
    "activateOpenBookmarkTab": true,
    "showBookmarkLen": false,
    "bookmarksRmUndoNote": true,
    "fontSize": "m",
    "bgNoise": true,
    "animations": true,
    "animationSpeed": "fast",
    "theme": "default",
    "style": "auto",
    "sidebarCSS": false,
    "groupCSS": false,
    "snapNotify": true,
    "snapExcludePrivate": false,
    "snapInterval": 0,
    "snapIntervalUnit": "min",
    "snapLimit": 0,
    "snapLimitUnit": "snap",
    "hScrollThroughPanels": true,
    "scrollThroughTabs": "panel",
    "scrollThroughVisibleTabs": true,
    "scrollThroughTabsSkipDiscarded": true,
    "scrollThroughTabsExceptOverflow": true,
    "scrollThroughTabsCyclic": true,
    "tabDoubleClick": "exp",
    "tabLongLeftClick": "none",
    "tabLongRightClick": "pin",
    "tabsPanelLeftClickAction": "none",
    "tabsPanelDoubleClickAction": "collapse",
    "tabsPanelRightClickAction": "menu",
    "tabsPanelMiddleClickAction": "tab",
    "syncName": "Raspberry Swirl(2)",
    "syncSaveSettings": true,
    "syncSaveCtxMenu": true,
    "syncSaveStyles": true,
    "syncAutoApply": false
  },
  "permissions": {
    "allUrls": true,
    "tabHide": true,
    "actualAllUrls": true,
    "actualTabHide": true
  },
  "storage": {
    "size": "125.3 kb",
    "props": {
      "bookmarksMenu": "119 b",
      "bookmarksPanelMenu": "40 b",
      "containers_v4": "1.3 kb",
      "cssVars": "1.7 kb",
      "expandedBookmarks": "180 b",
      "favAutoCleanTime": "10 b",
      "favUrls": "5.2 kb",
      "favicons": "99.8 kb",
      "lastSnapTime": "13 b",
      "panelIndex": "1 b",
      "panels_v4": "2 kb",
      "prevTabsData_v4": "99 b",
      "profileID": "14 b",
      "settings": "2.8 kb",
      "snapshots_v4": "10.9 kb",
      "tabsData_v4": "99 b",
      "tabsMenu": "275 b",
      "tabsPanelMenu": "150 b"
    }
  },
  "panels": [
    {
      "type": "bookmarks",
      "id": "bookmarks",
      "cookieStoreId": "bookmarks",
      "name": 9,
      "icon": "...",
      "bookmarks": true,
      "lockedPanel": true,
      "skipOnSwitching": false
    },
    {
      "type": "tabs",
      "id": "wItVugAdD2ta",
      "name": 3,
      "icon": "...",
      "color": "...",
      "customIconSrc": "",
      "customIcon": "",
      "lockedTabs": false,
      "lockedPanel": false,
      "skipOnSwitching": false,
      "noEmpty": false,
      "newTabCtx": "none",
      "dropTabCtx": "none",
      "moveTabCtx": "none",
      "moveTabCtxNoChild": true,
      "urlRulesActive": false,
      "urlRules": ""
    },
    {
      "type": "tabs",
      "id": "ca9VcJjDnYsb",
      "name": 13,
      "icon": "...",
      "color": "...",
      "customIconSrc": "",
      "customIcon": "",
      "lockedTabs": false,
      "lockedPanel": false,
      "skipOnSwitching": false,
      "noEmpty": false,
      "newTabCtx": "none",
      "dropTabCtx": "none",
      "moveTabCtx": "none",
      "moveTabCtxNoChild": true,
      "urlRulesActive": false,
      "urlRules": ""
    },
    {
      "type": "tabs",
      "id": "Hxx2FwReJcH7",
      "name": 5,
      "icon": "...",
      "color": "...",
      "customIconSrc": "",
      "customIcon": "",
      "lockedTabs": false,
      "lockedPanel": false,
      "skipOnSwitching": true,
      "noEmpty": false,
      "newTabCtx": "none",
      "dropTabCtx": "none",
      "moveTabCtx": "none",
      "moveTabCtxNoChild": true,
      "urlRulesActive": false,
      "urlRules": ""
    },
    {
      "type": "tabs",
      "id": "LC5Ik4O8SUG7",
      "name": 8,
      "icon": "...",
      "color": "...",
      "customIconSrc": "",
      "customIcon": "",
      "lockedTabs": false,
      "lockedPanel": false,
      "skipOnSwitching": false,
      "noEmpty": false,
      "newTabCtx": "none",
      "dropTabCtx": "none",
      "moveTabCtx": "none",
      "moveTabCtxNoChild": true,
      "urlRulesActive": false,
      "urlRules": ""
    },
    {
      "type": "tabs",
      "id": "Z8VqwQolp8G7",
      "name": 6,
      "icon": "...",
      "color": "...",
      "customIconSrc": "",
      "customIcon": "",
      "lockedTabs": false,
      "lockedPanel": false,
      "skipOnSwitching": false,
      "noEmpty": false,
      "newTabCtx": "none",
      "dropTabCtx": "none",
      "moveTabCtx": "none",
      "moveTabCtxNoChild": true,
      "urlRulesActive": false,
      "urlRules": ""
    },
    {
      "type": "default",
      "id": "firefox-default",
      "name": 7,
      "icon": "...",
      "cookieStoreId": "firefox-default",
      "lockedTabs": false,
      "lockedPanel": false,
      "skipOnSwitching": false,
      "noEmpty": false,
      "newTabCtx": "none",
      "dropTabCtx": "none",
      "moveTabCtx": "none",
      "moveTabCtxNoChild": true
    }
  ],
  "containers": [
    {
      "id": "firefox-container-1",
      "name": 8,
      "icon": "...",
      "color": "...",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-2",
      "name": 9,
      "icon": "...",
      "color": "...",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": true,
      "includeHosts": 89,
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-3",
      "name": 7,
      "icon": "...",
      "color": "...",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-4",
      "name": 8,
      "icon": "...",
      "color": "...",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-6",
      "name": 5,
      "icon": "...",
      "color": "...",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": true,
      "includeHosts": 28,
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    }
  ],
  "cssVars": {
    "bg": "#181818ff",
    "title_fg": "#a40060ff",
    "sub_title_fg": "#fff",
    "label_fg": "#fff",
    "label_fg_hover": "#fff",
    "label_fg_active": "#aaa",
    "info_fg": "#898989",
    "true_fg": "#64df64",
    "false_fg": "#df6464",
    "active_fg": "#a5417cff",
    "inactive_fg": "#5c5c5c",
    "favicons_placeholder_bg": "rgba(255,255,255,0.141)",
    "tabs_activated_border": "1px solid purple"
  },
  "windows": [
    {
      "state": "maximized",
      "incognito": false,
      "tabsCount": 14
    }
  ],
  "tabsMenu": [
    [
      {
        "name": "Organize"
      },
      "bookmark",
      "copyUrls",
      "moveToWin"
    ],
    [
      {
        "name": "Panels"
      },
      "moveToPanel"
    ],
    "separator-9588708382417734",
    "group",
    "flatten",
    "duplicate",
    "separator-3802111930883487",
    "clearCookies",
    "close",
    "separator-061573684940704254",
    [
      {
        "name": "Offload"
      },
      "pin",
      "moveToNewWin"
    ]
  ],
  "bookmarksMenu": [
    "separator-5",
    "createFolder",
    "createBookmark",
    "createSeparator",
    "separator-6",
    "copyUrls",
    "edit",
    "delete",
    "sortByName"
  ],
  "bookmarks": {
    "bookmarksCount": 163,
    "foldersCount": 45,
    "separatorsCount": 27,
    "maxDepth": 7
  }
}
</code></details>

**Comment by mbnuqw** [comment]
[It's impossible for addons](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/create#url). That page with copy button is a workaround for this limitation.
