### ISSUE TITLE
[Feature request] "Remove selected items or active tab", select next tab

### ISSUE THREAD

**Issue by jmickelin** [mbnuqw/sidebery#569]
## Description
I would like for the "Remove selected items or active tab" keyboard shortcut to automatically select the next adjacent tab after the selection has been deleted. The use-case for this would be walking through your tab tree to prune tabs you no longer need, closing them as soon as you encounter them. After closing the tab, you should not lose your position in the tree. Currently, you have to scroll back from your active tab again.

Also, does it really make sense to do the "or active tab" case at all? There is already a built-in keyboard shortcut for this, and doing both in the same command is really counterintuitive. I could create a separate feature request for splitting this behavior (or introducing an alternative shortcut that just does the former and does nothing if nothing is selected).

**Comment by mbnuqw** [comment]
Closing as "wontfix" as workaround exists: Use "Select range up/down" keybindings to select all tabs you want to close.

> Also, does it really make sense to do the "or active tab" case at all?

Ctrl+W and Sidebery's shortcut have different behavior when multiple tabs selected (and "Highlight native tabs..." is on). I don't like Ctrl+W behavior (when it's impossible to close multiple tabs without closing the active one), and also don't like using two different keybindings for closing a single active tab and multiple selected tabs. But users still can use Ctrl+W for closing an active tab and Sidebery's shortcut for closing multiple selected tabs if they like, so I don't see any problem here as well as counterintuitiveness.
