### ISSUE TITLE
Reopen Closed Tab is confusing

### ISSUE THREAD

**Issue by aphive** [mbnuqw/sidebery#570]
## Steps to reproduce
* close a tab in sidebery sidebar
* right click on sidebar to get context menu
* no option to re-open closed tab in same window
    * I do get some options if I click on an actual tab, but they are all to open my tab in different envs (see screenshots)

## Expected behavior
Should get options to re-open closed tabs in same window and were it was in a simple way not have to pick from several options that may not make sense.

In Tree Style Tab for example, I just get one option to reopen closed tabs in whatever window the tab was closed in should I have multiple windows open:
![TST](https://user-images.githubusercontent.com/6079962/153526425-96632cf1-d56e-416c-90bf-3e2fb460c017.png)

## Actual behavior
When right clicking to open the options menu I get some options to reopen but it's options like Open in Work, Open in Banking, etc, not just a re-open closed tab.
![2022-02-10_14-03](https://user-images.githubusercontent.com/6079962/153526482-6b33256a-b139-4bc4-91d5-1d829039c799.png)

If I click outside of the tabs I don't get any options.
![2022-02-10_14-03_1](https://user-images.githubusercontent.com/6079962/153526521-92ec8f35-50b2-421f-9b84-62ce024dc99f.png)

## Environment info

OS:  Ubuntu 21.10
Firefox version:  96.0 (64-bit)
Addon version:  4.10.0

<details><code>
{
  "settings": {
    "version": "4.10.0",
    "nativeScrollbars": false,
    "selWinScreenshots": true,
    "tabsCheck": true,
    "tabsFix": "notify",
    "markWindow": false,
    "markWindowPreface": "[Sidebery] ",
    "ctxMenuNative": false,
    "autoHideCtxMenu": "none",
    "ctxMenuRenderInact": true,
    "ctxMenuIgnoreContainers": "",
    "navBarLayout": "horizontal",
    "navBarInline": true,
    "hideAddBtn": false,
    "hideSettingsBtn": false,
    "navBtnCount": true,
    "hideEmptyPanels": true,
    "navActTabsPanelLeftClickAction": "none",
    "navActBookmarksPanelLeftClickAction": "none",
    "navMidClickAction": "none",
    "navSwitchPanelsWheel": true,
    "groupLayout": "grid",
    "skipEmptyPanels": false,
    "dndTabAct": true,
    "dndTabActDelay": 750,
    "dndTabActMod": "none",
    "dndExp": "pointer",
    "dndExpDelay": 0,
    "dndExpMod": "none",
    "stateStorage": "global",
    "warnOnMultiTabClose": "collapsed",
    "activateOnMouseUp": true,
    "activateLastTabOnPanelSwitching": true,
    "showTabRmBtn": true,
    "showTabCtx": true,
    "hideInact": false,
    "activateAfterClosing": "next",
    "activateAfterClosingPrevRule": "visible",
    "activateAfterClosingNextRule": "tree",
    "activateAfterClosingGlobal": false,
    "activateAfterClosingNoFolded": true,
    "activateAfterClosingNoDiscarded": true,
    "shiftSelAct": true,
    "askNewBookmarkPlace": false,
    "tabsRmUndoNote": true,
    "nativeHighlight": false,
    "tabsUnreadMark": false,
    "tabsReloadLimit": 5,
    "tabsReloadLimitNotif": true,
    "tabsPanelSwitchActMove": true,
    "moveNewTabPin": "start",
    "moveNewTabParent": "last_child",
    "moveNewTabParentActPanel": false,
    "moveNewTab": "end",
    "pinnedTabsPosition": "panel",
    "pinnedTabsList": false,
    "pinnedAutoGroup": false,
    "tabsTree": true,
    "groupOnOpen": true,
    "tabsTreeLimit": "none",
    "hideFoldedTabs": false,
    "autoFoldTabs": false,
    "autoFoldTabsExcept": "none",
    "autoExpandTabs": true,
    "rmChildTabs": "none",
    "tabsChildCount": false,
    "tabsLvlDots": true,
    "discardFolded": true,
    "discardFoldedDelay": 0,
    "discardFoldedDelayUnit": "sec",
    "tabsTreeBookmarks": true,
    "treeRmOutdent": "branch",
    "bookmarksPanel": true,
    "warnOnMultiBookmarkDelete": "collapsed",
    "openBookmarkNewTab": false,
    "midClickBookmark": "open_new_tab",
    "actMidClickTab": false,
    "autoCloseBookmarks": false,
    "autoRemoveOther": false,
    "highlightOpenBookmarks": false,
    "activateOpenBookmarkTab": false,
    "showBookmarkLen": false,
    "bookmarksRmUndoNote": true,
    "fontSize": "l",
    "bgNoise": true,
    "animations": true,
    "animationSpeed": "fast",
    "theme": "tactile",
    "style": "dark",
    "sidebarCSS": false,
    "groupCSS": false,
    "snapNotify": true,
    "snapExcludePrivate": false,
    "snapInterval": 0,
    "snapIntervalUnit": "min",
    "snapLimit": 0,
    "snapLimitUnit": "snap",
    "hScrollThroughPanels": false,
    "scrollThroughTabs": "none",
    "scrollThroughVisibleTabs": false,
    "scrollThroughTabsSkipDiscarded": false,
    "scrollThroughTabsExceptOverflow": true,
    "scrollThroughTabsCyclic": false,
    "tabDoubleClick": "none",
    "tabLongLeftClick": "none",
    "tabLongRightClick": "none",
    "tabsPanelLeftClickAction": "none",
    "tabsPanelDoubleClickAction": "tab",
    "tabsPanelRightClickAction": "menu",
    "tabsPanelMiddleClickAction": "tab",
    "syncName": "",
    "syncSaveSettings": false,
    "syncSaveCtxMenu": false,
    "syncSaveStyles": false,
    "syncAutoApply": false
  },
  "permissions": {
    "allUrls": false,
    "tabHide": false,
    "actualAllUrls": false,
    "actualTabHide": false
  },
  "storage": {
    "size": "408.7 kb",
    "props": {
      "cssVars": "1.6 kb",
      "favAutoCleanTime": "10 b",
      "favUrls": "8.1 kb",
      "favicons": "360 kb",
      "panelIndex": "1 b",
      "prevTabsData_v4": "18 kb",
      "profileID": "14 b",
      "settings": "2.8 kb",
      "tabsData_v4": "17.7 kb"
    }
  },
  "panels": "TypeError: t is undefined",
  "containers": [],
  "cssVars": {
    "bg": "#323232",
    "btn_bg": "#245484"
  },
  "windows": [
    {
      "state": "maximized",
      "incognito": false,
      "tabsCount": 115
    },
    {
      "state": "maximized",
      "incognito": false,
      "tabsCount": 15
    }
  ],
  "bookmarks": {
    "bookmarksCount": 11,
    "foldersCount": 7,
    "separatorsCount": 0,
    "maxDepth": 2
  }
}
</code></details>

**Comment by dexeonify** [comment]
The "Reopen Closed Tab" you are looking for is the ↩ "undo" button at the top of the row, which can be found in both context menu.

The "Reopen in Work/Banking/etc" is to reopen the selected tab in a specific _container_. Let's say you want to open your banking site in the "Banking" container.

**Comment by aphive** [comment]
Thanks for the information, that makes sense, kind of hidden but that was my fault for not hovering over the icons..
