### ISSUE TITLE
Skip unloaded tabs when scrolling with mouse

### ISSUE THREAD

**Issue by david-bartley** [mbnuqw/sidebery#571]
## Description
Skip unloaded tabs when scrolling with mouse

Awesome tool by the way :rocket:

**Comment by dexeonify** [comment]
Enable **Skip discarded tabs** under **Switch tabs with scroll wheel** :P

**Comment by david-bartley** [comment]
Ooooh that is what discarded means! Many thanks, I'm happy!

**Comment by megamorphg** [comment]
This should be closed.
