### ISSUE TITLE
Priority (containers and masks)

### ISSUE THREAD

**Issue by mature-woman** [mbnuqw/sidebery#572]
If I select "Move tabs of the selected container to this panel" (1), "Move tabs with matching addresses to this panel" (2) works later, which makes me unable to use the containers

![изображение](https://user-images.githubusercontent.com/21334019/153690604-2db75eb8-7594-42fc-b59e-e2e4b9efb9db.png)

**Comment by mbnuqw** [comment]
Maybe I don't understand, but I don't see an issue here. You can open a new tab in the container you want, then navigate to github.
