### ISSUE TITLE
[Request] Open new tab when double-clicking in blank space

### ISSUE THREAD

**Issue by ylapointe** [mbnuqw/sidebery#575]
It would be great to enable the ability to open new tabs by double-clicking in the blank area below the tabs... I used to use Tree Tabs (https://addons.mozilla.org/en-US/firefox/addon/tree-tabs/), and it had a similar feature.

**Comment by dexeonify** [comment]
Sidebery Settings > Mouse > Double click on tabs panel > **create tab**

**Comment by ylapointe** [comment]
wow ... how did i miss that... (facepalm)... never mind
