### ISSUE TITLE
Can disable bookmark panel?

### ISSUE THREAD

**Issue by sylin527** [mbnuqw/sidebery#576]
## Description

It's a nice add-on for me to show tab title personally, because of the custom style feature.

But it handles bookmarks and tabs very slowly.
I have 100 000 bookmarks, each time when I open Sidebery, open bookmark panel, wait a long time to load bookmarks.

How to disable all bookmarks features? Like disable bookmark panel.

**Comment by coskunkut** [comment]
Settings/Bookmarks/Bookmarks Panel -> OFF
