### ISSUE TITLE
tree structure only saved in the window from which exit was initiated

### ISSUE THREAD

**Issue by prizrak9** [mbnuqw/sidebery#58]
I have 2 windows. 
Make primitive trees in each. 
Quit app from one of them.
Start again.
See that only in the window from which the app was closed saved tree structure.

> OS: win x86-64  
> Firefox: 68.0  
> Extension: 2.4.2

**Comment by mbnuqw** [comment]
Yes, unfortunately current version cannot restore tree in the second window due to some architectural flaws. But the problem will be solved in next major release in which I add basic session manager, so stay tuned!

**Comment by mbnuqw** [comment]
Fixed in v3.0.8.
