### ISSUE TITLE
Move To Right Side of Browser

### ISSUE THREAD

**Issue by seniorm0ment** [mbnuqw/sidebery#582]
I know this was possible, but I forgot how.
Trying to resetup on a fresh install.

Either way, I know TreeStyleTabs had an option to just move it. That'd be cool.

**Comment by siddhpant** [comment]
Why would you make an "issue" for this?

**Comment by seniorm0ment** [comment]
The issue was moreso asking for an option, however adding it to the documentation would be nice.
I thought there used to be an option, that's why I was a bit confused. I figured maybe it bugged or something after an update I'm not sure. I was trying to figure it out for an hour.
I'm using the same userChrome as my old profile, and it did not move around anywhere if that is what you are suggesting by move it natively. So I am not sure. No intentions to waste the developers time, but I don't know where else I could've asked.

**Comment by siddhpant** [comment]
Have a look at https://www.simplehelp.net/2008/09/04/how-to-move-your-sidebar-to-the-right-side-of-firefox/

**Comment by dexeonify** [comment]
Note: If you remove the sidebar header in `userChrome.css`, you don't even have the option to move it through the menu. So, undo any changes in your `userChrome.css` first.

**Comment by seniorm0ment** [comment]
Thank you,
also thank you that's probably why I have not seen the option.

**Comment by siddhpant** [comment]
Yeah, it might be good.

Also, please close the issue.

**Comment by seniorm0ment** [comment]
I'm unable to close it on Fasthub client :/

**Comment by gunir** [comment]
Solution is
sidebar.position_start | false

**Comment by albino1** [comment]
You don't even need to do that, there's a built in Firefox option on the sidebar menu called `Move Sidebar to Right`:

![side](https://github.com/mbnuqw/sidebery/assets/12164957/9a7d061a-67cb-45fa-94f4-ad1ec662b383)

**Comment by gunir** [comment]
> Note: If you remove the sidebar header in `userChrome.css`, you don't even have the option to move it through the menu. So, undo any changes in your `userChrome.css` first.



> You don't even need to do that, there's a built in Firefox option on the sidebar menu called `Move Sidebar to Right`:
> 
> ![side](https://private-user-images.githubusercontent.com/12164957/286029432-9a7d061a-67cb-45fa-94f4-ad1ec662b383.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNTE5NjIsIm5iZiI6MTcwMTI1MTY2MiwicGF0aCI6Ii8xMjE2NDk1Ny8yODYwMjk0MzItOWE3ZDA2MWEtNjdjYi00NWZhLTk0ZjQtYWQxZWM2NjJiMzgzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDA5NTQyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiYTI0Mzg3ZDMzNWEyYjI1MDk1OGIwMGE1MDA4ZjQ0ZTZkZWU3YzIzZjg1NTY4ZWNjZmNmOWY3MmE1NDU3YmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6mSvRF-JXHIh7dKy-kbfvHwfeJq6m-SQQdrJMU5W05I)

Not really for some people, there's people who use userChrome.css to hide header, that's why about:config works for 100% cases

**Comment by siddhpant** [comment]
A userChrome.css enthusiast will have a collapsible sidebar header, there is no reason to remove it altogether.
