### ISSUE TITLE
Search bar for tabs and bookmarks [Feature Request] 

### ISSUE THREAD

**Issue by emvaized** [mbnuqw/sidebery#584]
## Description
It would be awesome to have search bar, which will allow to search tabs by matches in urls or tab titles. For bookmarks panel, such a search bar may search matches in urls, bookmark titles or tags. 

I think it may bring a lot of utility to Sidebery.

**Comment by dexeonify** [comment]
This is one of the features in [v5](https://github.com/mbnuqw/sidebery/tree/v5) :)

**Comment by emvaized** [comment]
> This is one of the features in [v5](https://github.com/mbnuqw/sidebery/tree/v5) :)

Wow, looks promising! Looking forward to see first stable version.
