### ISSUE TITLE
How to make it look as in the screenshots on the store?

### ISSUE THREAD

**Issue by taigi100** [mbnuqw/sidebery#585]
Hey,

I got one question, in the screenshots in the store there is not a "title bar" for the vertical bookmarks with a dropdown, but a few bookmarks by the looks of it. How do I achieve that?

What I have:
![image](https://user-images.githubusercontent.com/10900362/158081471-52aab4d7-29e3-40ad-8834-b9572558210f.png)

What I want: 
![image](https://user-images.githubusercontent.com/10900362/158081484-59aba67a-2335-47b4-898a-9ed1e5d0821b.png)

**Comment by dexeonify** [comment]
You're almost there. Change **Pinned tabs position** in Settings/Pinned tabs to **top**. Then, pin a tab to get the exact layout as the screenshot.

To remove the header, put this in your `userChrome.css` file:
```css
/* Remove sidebar header */
#sidebar-header {
    display: none
}
```

> I got one question, in the screenshots in the store there is not a "title bar" for the vertical bookmarks with a dropdown

Not sure if I understand fully, do you mean the big "Sidebery" label?

> but a few bookmarks by the looks of it. How do I achieve that?

I don't see "a few bookmarks", there's only 1. If you meant these colourful icons, those are called panels:
![image](https://user-images.githubusercontent.com/72267349/158094848-35c29e70-ffd5-4289-92fa-35764d653f22.png)
