### ISSUE TITLE
From my limited testing, it doesn't make you lose all your tabs. If anything goes wrong, Firefox will always keep track of recently closed tabs.

### ISSUE THREAD

**Issue by jirawat025** [mbnuqw/sidebery#590]
From my limited testing, it doesn't make you lose all your tabs. If anything goes wrong, Firefox will always keep track of recently closed tabs.

_Originally posted by @dexeonify in https://github.com/mbnuqw/sidebery/issues/574#issuecomment-1041813718_

**Comment by dexeonify** [comment]
What?
