### ISSUE TITLE
Suggested Improvement to "about:blank#urlhttp..." Issue

### ISSUE THREAD

**Issue by AEAJuneBug** [mbnuqw/sidebery#592]
Hi.

Per #362, a Firefox bug with containers would result in tabs restored having their title shown as "about:blank#url".

This makes it impossible/difficult to tell tabs' titles apart.

My suggestion is that tabs that have their URL changed to "about:blank#url ..." have their original title preserved. This would greatly help with backup/restore operations of tabs in Sideberry.

Thanks for the excellent add-on that has become a necessity to my Firefox.

**Comment by mbnuqw** [comment]
Yep, I tried this but it was impossible to set the title for "about:..." page. Anyway, it's already "fixed" in v5 - I removed this hack. Containered tabs will be opened and loaded in normal mode. When [1581872](https://bugzilla.mozilla.org/show_bug.cgi?id=1581872) will be fixed I'll return opening of them in discarded mode.
