### ISSUE TITLE
Removing items from context menu

### ISSUE THREAD

**Issue by prizrak9** [mbnuqw/sidebery#60]
Even though there is a way to reorder items in the context menu It would be great to be able to choose which items I want to see there.

**Comment by mbnuqw** [comment]
You can just move item to the end of list and click on down button again to disable it. This is a temporary solution and I will add more convenient way to disable menu options, so I mark this issue as a bug.

**Comment by mbnuqw** [comment]
Fixed in the latest version - added button for disabling the option.
