### ISSUE TITLE
Provide a convenient way to define the "long" clicks

### ISSUE THREAD

**Issue by d-faure** [mbnuqw/sidebery#600]
Cf. #528 diagnostic and my own experience, I would find convenient to have a way to define the duration of a "long" click.

It would be also very comfortable to get some kind of visual feedback on them.

**Comment by mbnuqw** [comment]
In v5 I've already added an option to change delay (in "Mouse section") and changed it default value to 500ms. And as for visual feedback - I agree, it should definitely be implemented.

**Comment by mbnuqw** [comment]
Available from v5.0.0
