### ISSUE TITLE
The Group feature doesn't work anymore and messes everything up

### ISSUE THREAD

**Issue by cluxter** [mbnuqw/sidebery#607]
## Steps to reproduce
Upgrade to Firefox 99, right-click on a tab, then click on "Group".

## Expected behavior
The tab(s) should be put in a new group.

## Actual behavior
The group is not created. Then, after using this option, clicking on another tab will select the previous tab and it's not possible to select again the current tab.

### Addon data
The "Debug info" in settings > "Help" doesn't exist in my Firefox.
Here are some info:
```
Addon version: 4.10.0
Firefox version: 99.0.1 (64 bits)
OS: ArchLinux

```

### Logs
In the console of the addon when we click on "Group":
```
Uncaught (in promise) Error: An unexpected error occurred undefined
    dt moz-extension://175045df-c294-4808-9eb3-42a45e3e4c9a/sidebar/sidebar.js:34
    AsyncFunctionThrow self-hosted:642
    (Async: async)
    dt self-hosted:1121
    onClick moz-extension://175045df-c294-4808-9eb3-42a45e3e4c9a/sidebar/sidebar.js:55
    onClick self-hosted:1121
    click moz-extension://175045df-c294-4808-9eb3-42a45e3e4c9a/sidebar/sidebar.js:56
    VueJS 29
    l moz-extension://175045df-c294-4808-9eb3-42a45e3e4c9a/sidebar/sidebar.js:46
    l self-hosted:1121
    select moz-extension://175045df-c294-4808-9eb3-42a45e3e4c9a/sidebar/sidebar.js:88
    select self-hosted:1121
```

**Comment by cluxter** [comment]
I downgraded Firefox to v97 and it works fine as before. So it definitely has something to do with the new Firefox versions.

**Comment by mbnuqw** [comment]
Thanks for the report! Looks like this bug https://bugzilla.mozilla.org/show_bug.cgi?id=1753607 (this happens if the parent tab is unloaded). I completely forgot to fix/workaround this in v4, will do soon.

**Comment by cluxter** [comment]
Thank you very much for your fast answer.
Could you please post a message here once the patch is out? So we can resume updating Firefox to its latest version again. Thanks again and keep up the good work!

**Comment by mbnuqw** [comment]
@cluxter, I've uploaded v4.10.1 with the fix, so after reviewing it'll be available in AMO (and for auto updates)

**Comment by cluxter** [comment]
Awesome, thank you very much for your reactivity! I'll test it as soon as it's available on the Firefox store.

**Comment by cluxter** [comment]
Just tested it, it seems to work great. Thanks so much!
