### ISSUE TITLE
High CPU usage and freeze when mouse over tab

### ISSUE THREAD

**Issue by steelywing** [mbnuqw/sidebery#611]
## Short description

High CPU usage and freeze when mouse over tab

**Only happen when**
- Sidebar on right side
- The tab title too long, and tooltip of title appear

Note
- Not only in unloaded tab
- Also happen on [TST add-on](https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab/)

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install Sidebery.
 3. Open a tab with [long title](https://www.mozilla.org/en-US/firefox/)
 4. Open Windows Task Manager
 5. Move sidebar to right side
 6. Mouse over the tab and stop moving mouse (wait the title tooltip)
 7. The CPU will be very high and sometimes Firefox freeze
 8. Move mouse to outside of sidebar will resume normal

## Environment

Windows 10, Firefox after 99

I can reproduce on 2 PC, so I think this is not display driver issue

**Comment by steelywing** [comment]
I think this is Firefox issue, I created a [bug report](https://bugzilla.mozilla.org/show_bug.cgi?id=1765713) to Firefox

**Comment by mbnuqw** [comment]
I can't reproduce it on linux so this issue is maybe a Windows specific firefox bug. You can also try to play with WebRender (toggling the "gfx.webrender.all" property in about:config (with reloading browser)) and try to turn on/off hardware acceleration in firefox settings.

**Comment by steelywing** [comment]
Firefox v100 has fixed this issue

**Comment by chinook77** [comment]
I'm experimenting this bug since FF 125.
