### ISSUE TITLE
Panels as groups

### ISSUE THREAD

**Issue by prizrak9** [mbnuqw/sidebery#62]
Would be great to see an option for making panels look and behave just like groups with additional functionality and limitaions.

**Comment by Dook1** [comment]
I support this. 
Обычных групп не хватает. Перемещение вкладок между контейнерами полностью переоткрывает их, если вкладок достаточно много - это напрягает. Ну и естественно контейнеры есть контейнеры - у каждого свои куки, поэтому приходится перенастраивать сайты.

**Comment by mbnuqw** [comment]
Done in v4.x.x

**Comment by prizrak9** [comment]
how to enable and use this feature?

**Comment by mbnuqw** [comment]
Sorry, looks like I didn't understand you correctly. Right now, panels are just the way to separate tabs. They not linked to containers anymore and you can freely remove all of them (except the default), preserve all containers and place all (containered or not) tabs in one default panel.

Have you suggested that group tabs be more configurable?

**Comment by prizrak9** [comment]
Well, that's cool, but I meant the containers behaving like groups. Basically, I just want to see all my tabs in one panel. Just group them by a container.

**Comment by mbnuqw** [comment]
Just to clarify, right now its possible to have structure like that:
![screenshot-2020-01-11 15:51:42](https://user-images.githubusercontent.com/6276694/72203168-51291700-348a-11ea-96e4-6bf79479886e.png)
You just need to manually place tabs.

And you're suggesting adding an option in group page that will automatically move containered tabs into it, correct?

**Comment by mbnuqw** [comment]
Oh, sorry I forgot to mention that to freely move containered tabs you need to disable options "Move tabs of selected container to this panel" and "Container of new tab" for target container in panels config.

**Comment by prizrak9** [comment]
Oh, I see. The options are expanding so quickly it's becoming less intuitive. 
I guess it's good now. Although I think the tabs, that are dragndropped to a containered tab should be automatically reopened in that same (parent node's) container. 
Making an option like that would be great.

**Comment by mbnuqw** [comment]
This is nice idea indeed! I've opened the issue: #121
