### ISSUE TITLE
Option to move the scrollbar to the left side of the sidebar

### ISSUE THREAD

**Issue by advait404** [mbnuqw/sidebery#622]
having an option to have the scrollbar to the left side of the sidebar would be useful. I have enabled the native scrollbar option, and I am using the sidebar on the left side. By changing the scrollbar location, it would be much easier to drag the scrollbar with the mouse.

**Comment by advait404** [comment]
I found a css solution for this: 

/* moving scrollbar to the left and reducing its width*/
.scroll-container{ direction: rtl }
.scroll-container > .scrollable{ direction: ltr }
.scroll-container { scrollbar-width: thin }

It would be nice for this to have an option in the sidebery menu, under the native scrollbar option.

**Comment by mbnuqw** [comment]
Available from v5.0.0
