### ISSUE TITLE
[Feature request] "Trash bin" for closed tabs with preserved tree structure

### ISSUE THREAD

**Issue by token0** [mbnuqw/sidebery#624]
## Description
"Trash bin" for closed tabs with preserved tree structure
Proposed button places: Tabs panel or bottom of sidebar (along with New tab button)

**Comment by mbnuqw** [comment]
Done in b30 (though, it has a time limit which I already find too short, so it will be increased soon)

**Comment by efermi** [comment]
@mbnuqw, could it be made non sticky, like scrollable, or combined with the new tab button, or a new panel in the navbar? Otherwise it takes up too much of real estate on my screen.

**Comment by mbnuqw** [comment]
@efermi, I'll make it configurable/removable in the next release. Right now, to hide it use this custom CSS:
```css
.TabsPanel .bottom-bar {
  display: none;
}
```
