### ISSUE TITLE
I can't see which window is which! - Show existing title preface in windows titles list when "[Sidebery] preface" option is off

### ISSUE THREAD

**Issue by gantheaume** [mbnuqw/sidebery#626]
On v5.0.0b18, Firefox 91.8.0esr (64-bit)

You added an option "Add preface to the browser window's title if Sidebery sidebar is active". Conveniently it seems, you don't show the "[Sidebery]" preface in the list of all open windows (for example when using the function "move tab to other window"). 

But even when the option is off, the preface is not displayed.
And I happen to use this preface (with the addon "window titler": https://addons.mozilla.org/en-US/firefox/addon/window-titler/ ) to name my windows and keep track of them (one per subject, I always have dozens open). Thus I'm now totally lost when Sidebery shows my windows and I want to move tabs from one to another. I used this option a lot and now hardly can.

Could you please enable showing the preface of the window title in the window title list when this "sidebery preface" option is off, as v4 did?
(and if as a bonus, toggling the option off immediately after putting it on could just restore the pre-existing prefaces, that would be perfect - just lost all my custom titles by testing the option - didn't have the latest snapshot done. _**Edit:**_ _it seems my previous titles came back! But still not visible in the sidebery list._)

In any case, thanks for this addon, great work, very excited about the v5 :)

**Comment by cptSwing** [comment]
Aye, interaction with either 'Window-Titler' or 'Crappy Firetitle' (sic!) extensions is spotty at best, unfortunately - nobody being at fault here, of course. It seems to me Sidbery and the other window-title extensions are fighting over who can edit a window's title last - would it be possible for Sidebery to just concatenate the existing Window title with it's own preface? (for me, main use of Sidebery's title preface is the conditional hiding of FF's tab-bar when SB is open)

Sorry, random aside. I am seriously awed by Sidebery and it's gazillion features. Thanks to any and all who are contributing.

**Comment by mbnuqw** [comment]
Should be fixed, feel free to reopen if not.
