### ISSUE TITLE
Tabs get flattened after 10'th nesting. 

### ISSUE THREAD

**Issue by denikryt** [mbnuqw/sidebery#627]
## Steps to reproduce
Just open a new child tab in the next child ten times and more.

## Expected behavior
Tabs saves reliationships no matter how deep they are nesting.
In settings the maximum nesting is set to off, it means unlimited amount of childs.

## Actual behavior
Tabs get flattened after 10'th nesting. 

### Addon data
<details><code>

</code></details>

### Logs
<details><code>

</code></details>

**Comment by dexeonify** [comment]
Fixed in v5 beta
![image](https://user-images.githubusercontent.com/72267349/167236503-51335e89-ef61-444b-9be1-9bffc76bbda8.png)

**Comment by denikryt** [comment]
@dexeonify It happens while I'm surfing wikipedia and other further articles from it, for example. For navigation experience such bug a bit confusing and counterproductive.

**Comment by denikryt** [comment]
Also I'm keeping tabs in tree structure and in some cases hierarchy exceed the limit of nesting.

**Comment by denikryt** [comment]
🙏🏻

**Comment by kakhulu31** [comment]
> I've increased the max level (to 16) and changed styles for overflowed tabs to stay at the max level.
Thanks for bringing your attention to this issue, however I dont think that increasing the max level to 16 will solve the problem for those who go so deep. 
Tst has a better approach to solve this problem, it simply reduces the horizontal gap between descendants the deeper you go without forcing any limit. This option would actually help.
And the ultimate solution would be adding a horizontal scroll bar as well as removing the limit.

**Comment by mbnuqw** [comment]
Dynamic indent values is a nice idea, definitely will try to add it. Horizontal scroll is not possible b/c:
- It will prevent horizontal scroll wheel to switch between panels (if configured)
- It's only possible with native scrollbars
- It will not work with drag and drop pointer positioning (or require its complete reworking)

**Comment by mbnuqw** [comment]
Fixed in v4.10.2
