### ISSUE TITLE
Tabs don't open in the good panels when Firefox is re-open

### ISSUE THREAD

**Issue by junior76fr67** [mbnuqw/sidebery#633]
## Steps to reproduce
I have 3 panels specific panels and 2 firefox windows open. These 3 panels are used in the 2 windows.

When I re-start firefox, in one of the windows the tabs are opened in the good panel. In the other windows, in 90% of the time, all the tabs unpinned are open in one panel all the tabs pinned in a other.

[SideBerry.pdf](https://github.com/mbnuqw/sidebery/files/8681170/SideBerry.pdf)

### Addon data
<details><code>

</code></details>

### Logs
<details><code>

</code></details>

**Comment by deiwo** [comment]
Same problem here.
I noticed that the panels get merged only in the main window (the one that was originally open first) and the other windows keep their panels intact.
My OS is Debian.

**Comment by mbnuqw** [comment]
The fix is on the way (will be delivered with v4.10.2). For now, you can try to set `Sidebery settings / Tabs / Where to store tabs data` to session storage. Or try [v5.0.0b22](https://github.com/mbnuqw/sidebery/releases/tag/v5.0.0b22)

**Comment by junior76fr67** [comment]
Works fine now. Thks.
@mbnuqw : +1:  Issues can be closed.
