### ISSUE TITLE
Settings: Fix quick transitions

### ISSUE THREAD

**Issue by ongots** [mbnuqw/sidebery#634]
Group Page, Containers, Panels

**Comment by mbnuqw** [comment]
Not sure if I correctly understand the issue. Navigation between these sections works ok. Could you give more info?

**Comment by ongots** [comment]
"Контейнеры" открывают "Групповую страницу".
"Панели" открывают "Контейнеры".
"Панели" наверно нужно удалить потому что они теперь в "Навигации".
"Групповая страница" отсутствует в боковом меню.

**Comment by mbnuqw** [comment]
Got it, it's wrong translation in the Ru locale.
