### ISSUE TITLE
Move selected tabs in a *new* panel

### ISSUE THREAD

**Issue by rafo** [mbnuqw/sidebery#644]
## Description

Move selected tabs in a *new* panel

Could work like the  right click "Group" function or by drag and drop on the "+" sign (but who want to drag things around the screen? Maybe to complicated). 

## Proposal
After selecting and right clicking on "Move To/New Panel": Opens the "create panel" popup like always but adds the prior selected tabs after configuring the panel...

**Comment by mbnuqw** [comment]
Available from v5.0.0
