### ISSUE TITLE
Cannot resize sidebar

### ISSUE THREAD

**Issue by notorand-it** [mbnuqw/sidebery#649]
## Steps to reproduce
Shrink the sidebar width by dragging its right side.

## Expected behavior
It should let the user decide the width.

## Actual behavior
It decides an apparently hardcoded minimum width.
![SHOT-20220602_102349](https://user-images.githubusercontent.com/5338874/171587701-4150caf9-a507-42e6-a327-1574c5d67000.png)

## Debug info
<code>
{
  "settings": {
    "version": "4.10.1",
    "nativeScrollbars": true,
    "selWinScreenshots": true,
    "tabsCheck": true,
    "tabsFix": "notify",
    "markWindow": false,
    "markWindowPreface": "[Sidebery] ",
    "ctxMenuNative": false,
    "autoHideCtxMenu": "none",
    "ctxMenuRenderInact": true,
    "ctxMenuIgnoreContainers": "",
    "navBarLayout": "horizontal",
    "navBarInline": true,
    "hideAddBtn": false,
    "hideSettingsBtn": false,
    "navBtnCount": true,
    "hideEmptyPanels": true,
    "navActTabsPanelLeftClickAction": "none",
    "navActBookmarksPanelLeftClickAction": "none",
    "navMidClickAction": "none",
    "navSwitchPanelsWheel": true,
    "groupLayout": "grid",
    "skipEmptyPanels": false,
    "dndTabAct": true,
    "dndTabActDelay": 750,
    "dndTabActMod": "none",
    "dndExp": "pointer",
    "dndExpDelay": 0,
    "dndExpMod": "none",
    "stateStorage": "session",
    "warnOnMultiTabClose": "collapsed",
    "activateOnMouseUp": true,
    "activateLastTabOnPanelSwitching": true,
    "showTabRmBtn": true,
    "showTabCtx": true,
    "hideInact": false,
    "activateAfterClosing": "next",
    "activateAfterClosingPrevRule": "visible",
    "activateAfterClosingNextRule": "tree",
    "activateAfterClosingGlobal": false,
    "activateAfterClosingNoFolded": true,
    "activateAfterClosingNoDiscarded": true,
    "shiftSelAct": true,
    "askNewBookmarkPlace": false,
    "tabsRmUndoNote": true,
    "nativeHighlight": false,
    "tabsUnreadMark": false,
    "tabsReloadLimit": 5,
    "tabsReloadLimitNotif": true,
    "tabsPanelSwitchActMove": true,
    "moveNewTabPin": "start",
    "moveNewTabParent": "last_child",
    "moveNewTabParentActPanel": false,
    "moveNewTab": "end",
    "pinnedTabsPosition": "panel",
    "pinnedTabsList": true,
    "pinnedAutoGroup": false,
    "tabsTree": true,
    "groupOnOpen": true,
    "tabsTreeLimit": "none",
    "hideFoldedTabs": false,
    "autoFoldTabs": false,
    "autoFoldTabsExcept": "none",
    "autoExpandTabs": false,
    "rmChildTabs": "none",
    "tabsChildCount": true,
    "tabsLvlDots": false,
    "discardFolded": false,
    "discardFoldedDelay": 0,
    "discardFoldedDelayUnit": "sec",
    "tabsTreeBookmarks": true,
    "treeRmOutdent": "branch",
    "bookmarksPanel": true,
    "warnOnMultiBookmarkDelete": "collapsed",
    "openBookmarkNewTab": false,
    "midClickBookmark": "open_new_tab",
    "actMidClickTab": false,
    "autoCloseBookmarks": false,
    "autoRemoveOther": false,
    "highlightOpenBookmarks": false,
    "activateOpenBookmarkTab": false,
    "showBookmarkLen": false,
    "bookmarksRmUndoNote": true,
    "fontSize": "xxs",
    "bgNoise": true,
    "animations": true,
    "animationSpeed": "fast",
    "theme": "default",
    "style": "auto",
    "sidebarCSS": false,
    "groupCSS": false,
    "snapNotify": true,
    "snapExcludePrivate": false,
    "snapInterval": 0,
    "snapIntervalUnit": "min",
    "snapLimit": 0,
    "snapLimitUnit": "snap",
    "hScrollThroughPanels": false,
    "scrollThroughTabs": "none",
    "scrollThroughVisibleTabs": false,
    "scrollThroughTabsSkipDiscarded": false,
    "scrollThroughTabsExceptOverflow": true,
    "scrollThroughTabsCyclic": false,
    "tabDoubleClick": "none",
    "tabLongLeftClick": "none",
    "tabLongRightClick": "none",
    "tabsPanelLeftClickAction": "none",
    "tabsPanelDoubleClickAction": "tab",
    "tabsPanelRightClickAction": "menu",
    "tabsPanelMiddleClickAction": "tab",
    "syncName": "",
    "syncSaveSettings": false,
    "syncSaveCtxMenu": false,
    "syncSaveStyles": false,
    "syncAutoApply": false
  },
  "permissions": {
    "allUrls": false,
    "tabHide": false,
    "actualAllUrls": false,
    "actualTabHide": false
  },
  "storage": {
    "size": "14.7 kb",
    "props": {
      "expandedBookmarks": "18 b",
      "favAutoCleanTime": "10 b",
      "favUrls": "222 b",
      "favicons": "11 kb",
      "panelIndex": "1 b",
      "prevTabsData_v4": "9 b",
      "profileID": "14 b",
      "settings": "2.8 kb",
      "tabsData_v4": "488 b"
    }
  },
  "panels": "TypeError: t is undefined",
  "containers": [],
  "cssVars": "TypeError: can't convert undefined to object",
  "windows": [
    {
      "state": "maximized",
      "incognito": false,
      "tabsCount": 5
    }
  ],
  "bookmarks": {
    "bookmarksCount": 21,
    "foldersCount": 9,
    "separatorsCount": 0,
    "maxDepth": 2
  }
}
</code>

### Addon data
OS: ArchLinux x86_64
Browser: Firefox v101.0 (64-bit)

### Logs
<details><code>

The provided directions don't seem to apply to my case: there is no option to set/get logs.
</code></details>

**Comment by rafo** [comment]
> It decides an apparently hardcoded minimum width

I think these are hardcoded restrictions from Firefox. There seems to be a minimum and a maximum. For me, it would be great to expand sideberry much further, but i doubt there is anything doable from the plugin itself but maybe by FF CSS hacks.

**Comment by notorand-it** [comment]
Just like hiding the "default" tab bar: FF CSS hacks only AFAIK.
This type of extension makes fewer sense with Firefox than with chromium-based browsers.
It's a pity.

**Comment by rafo** [comment]
I also find it totally unacceptable that it is only possible to hide the table bar in a complicated and time-consuming way.

**Comment by notorand-it** [comment]
We live in a strange world: easy things made complicated.

**Comment by dexeonify** [comment]
Not a Sidebery bug, a simple Google search shows that you can put this in your userChrome.css file:
```css
/* remove maximum/minimum width restriction of sidebar */
#sidebar {
  max-width: none !important;
  min-width: 0px !important;
}
```

> This type of extension makes fewer sense with Firefox than with chromium-based browsers.

I don't understand this. Chromium users love to boast about their native vertical tabs, when we have Tree Style Tabs and Sidebery for years, with much more customisability.

> Just like hiding the "default" tab bar: FF CSS hacks only AFAIK.

As for this, I have to agree. There's [bug 1332447](https://bugzilla.mozilla.org/show_bug.cgi?id=1332447) but I doubt there will be any progress on it anytime soon. At least the CSS "hacks" allow me to switch between the tab bar and sidebar dynamically.

**Comment by rafo** [comment]
> > This type of extension makes fewer sense with Firefox than with chromium-based browsers.
> 
> I don't understand this. Chromium users love to boast about their native vertical tabs, when we have Tree Style Tabs and Sidebery for years, with much more customisability.

True, but i think he dont want to blame sideberry but the simple fact that you cant resize the sidebar in FF (Brave also cant do it. Dont know about Google Chrome) as you want, without wading through css hacks and wondering why everything is broken again with the next update. And a resizable (to 100%) sidebar would be great for sideberry.

**Comment by mbnuqw** [comment]
Closing this because there is no way to fix the issue from Sidebery side.

**Comment by nazdridoy** [comment]
> Not a Sidebery bug, a simple Google search shows that you can put this in your userChrome.css file:
> 
> ```css
> /* remove maximum/minimum width restriction of sidebar */
> #sidebar {
>   max-width: none !important;
>   min-width: 0px !important;
> }
> ```
> 
> > This type of extension makes fewer sense with Firefox than with chromium-based browsers.
> 
> I don't understand this. Chromium users love to boast about their native vertical tabs, when we have Tree Style Tabs and Sidebery for years, with much more customisability.
> 
> > Just like hiding the "default" tab bar: FF CSS hacks only AFAIK.
> 
> As for this, I have to agree. There's [bug 1332447](https://bugzilla.mozilla.org/show_bug.cgi?id=1332447) but I doubt there will be any progress on it anytime soon. At least the CSS "hacks" allow me to switch between the tab bar and sidebar dynamically.

"min width" does not work anymore in FF 107
Use #sidebar-box instead of #sidebar

/* remove maximum/minimum width restriction of sidebar */
#sidebar-box {
  max-width: none !important;
  min-width: 0px !important;
}
