### ISSUE TITLE
[v5] Upgrading from v4 to v5 Causes Group Tabs to Disappear

### ISSUE THREAD

**Issue by megamorphg** [mbnuqw/sidebery#656]
## Steps to reproduce
1. Install Sidebery v4
2. Create a tab group
3. Upgrade to Sidebery v5
4. Observe group tabs are missing

Workaround:
Take a snapshot in v4 and restore it in v5 after upgrade.

## Expected behavior
Group tabs stay the same

## Actual behavior
Group tabs disappear

### Addon data
<details><code>

</code></details>

### Logs
<details><code>

</code></details>

**Comment by mbnuqw** [comment]
Hm... The old `/group/group.html` url should show the standard `File not found` placeholder page.

What did you see after upgrading when you activate the group page with `page.group/group.html` url? Was it empty or some kind of warning page was shown?

**Comment by mbnuqw** [comment]
All right, looks like I need to do more tests of upgrading with restoring groups in multiple windows. Thanks for the info!
