### ISSUE TITLE
[v5] New Tab with Ctrl + T does not open at bottom of panel

### ISSUE THREAD

**Issue by megamorphg** [mbnuqw/sidebery#662]
## Steps to reproduce 1
Configuration Place New Tab (for other cases) = 'none' or 'panel end'

1. Go to 1st panel with tabs.
2. Go to 2nd empty panel. It automatically creates new tab. Close tab.
3. Go back to 1st panel.
4. Create new tab with Ctrl + T
5. Observe it opens in Panel 2 instead of bottom of panel

## Steps to reproduce 2
1. Go to 1st panel with tabs.
2. Go to a group in middle of list
3. Use shortcut to "create new child tab first/last"
4. Close tab
5. Create new tab with Ctrl + T
6. Observe it opens under child tab instead of bottom of panel

## Expected behavior
Open new tab with Ctrl + T at bottom of panel

## Actual behavior
Opens new tab at last inserted position

### Addon data
<details><code>
{
  "settings": {
    "nativeScrollbars": true,
    "nativeScrollbarsThin": false,
    "nativeScrollbarsLeft": false,
    "selWinScreenshots": true,
    "updateSidebarTitle": true,
    "markWindow": false,
    "markWindowPreface": "[SB] ",
    "logLvl": 3,
    "ctxMenuNative": true,
    "ctxMenuRenderInact": true,
    "ctxMenuRenderIcons": true,
    "ctxMenuIgnoreContainers": "",
    "navBarLayout": "vertical",
    "navBarInline": false,
    "navBarSide": "left",
    "hideAddBtn": false,
    "hideSettingsBtn": false,
    "navBtnCount": true,
    "hideEmptyPanels": false,
    "navActTabsPanelLeftClickAction": "new_tab",
    "navActBookmarksPanelLeftClickAction": "scroll",
    "navTabsPanelMidClickAction": "discard",
    "navBookmarksPanelMidClickAction": "convert",
    "navSwitchPanelsWheel": true,
    "groupLayout": "list",
    "skipEmptyPanels": true,
    "dndTabAct": true,
    "dndTabActDelay": 5000,
    "dndTabActMod": "alt",
    "dndExp": "pointer",
    "dndExpDelay": 50,
    "dndExpMod": "alt",
    "dndOutside": "data",
    "searchBarMode": "static",
    "warnOnMultiTabClose": "any",
    "activateLastTabOnPanelSwitching": true,
    "showTabRmBtn": true,
    "hideInact": true,
    "activateAfterClosing": "prev",
    "activateAfterClosingGlobal": true,
    "activateAfterClosingNoFolded": true,
    "activateAfterClosingNoDiscarded": false,
    "askNewBookmarkPlace": true,
    "tabsRmUndoNote": true,
    "nativeHighlight": true,
    "tabsUnreadMark": true,
    "tabsReloadLimit": 5,
    "tabsReloadLimitNotif": true,
    "showNewTabBtns": true,
    "newTabBarPosition": "bottom",
    "tabsPanelSwitchActMove": true,
    "openSubPanelOnMouseHover": false,
    "colorizeTabs": true,
    "colorizeTabsSrc": "domain",
    "moveNewTabPin": "end",
    "moveNewTabParent": "default",
    "moveNewTabParentActPanel": true,
    "moveNewTab": "none",
    "pinnedTabsPosition": "left",
    "pinnedTabsList": true,
    "pinnedAutoGroup": true,
    "tabsTree": true,
    "groupOnOpen": true,
    "tabsTreeLimit": "none",
    "hideFoldedTabs": true,
    "autoFoldTabs": false,
    "autoFoldTabsExcept": 5,
    "autoExpandTabs": false,
    "rmChildTabs": "folded",
    "tabsChildCount": true,
    "tabsLvlDots": true,
    "discardFolded": true,
    "discardFoldedDelay": 10,
    "discardFoldedDelayUnit": "min",
    "tabsTreeBookmarks": true,
    "treeRmOutdent": "first_child",
    "colorizeTabsBranches": false,
    "colorizeTabsBranchesSrc": "url",
    "warnOnMultiBookmarkDelete": "any",
    "autoCloseBookmarks": false,
    "autoRemoveOther": false,
    "highlightOpenBookmarks": true,
    "activateOpenBookmarkTab": false,
    "showBookmarkLen": true,
    "bookmarksRmUndoNote": true,
    "loadBookmarksOnDemand": true,
    "pinOpenedBookmarksFolder": true,
    "loadHistoryOnDemand": false,
    "fontSize": "xxl",
    "animations": true,
    "animationSpeed": "norm",
    "theme": "proton",
    "colorScheme": "ff",
    "sidebarCSS": false,
    "groupCSS": false,
    "snapNotify": true,
    "snapExcludePrivate": false,
    "snapInterval": 3,
    "snapIntervalUnit": "hr",
    "snapLimit": 7,
    "snapLimitUnit": "day",
    "hScrollAction": "switch_panels",
    "navSwitchPanelsDelay": 128,
    "scrollThroughTabs": "panel",
    "scrollThroughVisibleTabs": true,
    "scrollThroughTabsSkipDiscarded": true,
    "scrollThroughTabsExceptOverflow": false,
    "scrollThroughTabsCyclic": true,
    "scrollThroughTabsScrollArea": 90,
    "autoMenuMultiSel": true,
    "longClickDelay": 500,
    "wheelThreshold": false,
    "wheelThresholdX": 10,
    "wheelThresholdY": 60,
    "tabDoubleClick": "none",
    "tabsSecondClickActPrev": true,
    "shiftSelAct": true,
    "activateOnMouseUp": true,
    "tabLongLeftClick": "none",
    "tabLongRightClick": "duplicate",
    "tabCloseMiddleClick": "discard",
    "tabsPanelLeftClickAction": "none",
    "tabsPanelDoubleClickAction": "collapse",
    "tabsPanelRightClickAction": "menu",
    "tabsPanelMiddleClickAction": "rm_act_tab",
    "bookmarksLeftClickAction": "open_in_new",
    "bookmarksLeftClickActivate": true,
    "bookmarksLeftClickPos": "after",
    "bookmarksMidClickAction": "open_in_new",
    "bookmarksMidClickActivate": false,
    "bookmarksMidClickPos": "default",
    "syncName": "Firefox X470",
    "syncSaveSettings": true,
    "syncSaveCtxMenu": true,
    "syncSaveStyles": true,
    "syncSaveKeybindings": true
  },
  "permissions": {
    "allUrls": true,
    "tabHide": true,
    "clipboardWrite": true,
    "webRequest": true,
    "webRequestBlocking": true
  },
  "storage": {
    "size": "2.42 mb",
    "props": {
      "containers": "2.21 kb",
      "contextMenu": "1.41 kb",
      "expandedBookmarkFolders": "75 b",
      "favDomains": "32.3 kb",
      "favHashes": "3.59 kb",
      "favicons": "256 kb",
      "groupCSS": "2 b",
      "lastSnapTime": "13 b",
      "panelIndex": "1 b",
      "prevTabsDataCache": "157 kb",
      "profileID": "14 b",
      "settings": "3.48 kb",
      "sidebar": "2.06 kb",
      "sidebarCSS": "2 b",
      "snapshots": "1.82 mb",
      "tabsDataCache": "156 kb",
      "ver": "10 b"
    }
  },
  "sidebar": {
    "panels": {
      "history": {
        "type": 4,
        "id": "history",
        "name": "len: 7",
        "color": "toolbar",
        "iconSVG": "icon_clock",
        "tempMode": false,
        "lockedPanel": false,
        "skipOnSwitching": false,
        "viewMode": "history"
      },
      "bookmarks": {
        "type": 1,
        "id": "bookmarks",
        "name": "len: 9",
        "iconSVG": "icon_bookmarks",
        "iconIMGSrc": "",
        "iconIMG": "",
        "color": "toolbar",
        "lockedPanel": false,
        "tempMode": false,
        "skipOnSwitching": false,
        "rootId": "root________",
        "viewMode": "tree",
        "autoConvert": false
      },
      "firefox-default": {
        "type": 2,
        "id": "firefox-default",
        "name": "len: 7",
        "color": "toolbar",
        "iconSVG": "icon_tabs",
        "iconIMGSrc": "",
        "iconIMG": "",
        "lockedPanel": false,
        "skipOnSwitching": false,
        "noEmpty": false,
        "newTabCtx": "none",
        "dropTabCtx": "none",
        "moveTabCtx": "none",
        "moveTabCtxNoChild": true,
        "urlRulesActive": false,
        "urlRules": "",
        "bookmarksFolderId": -1,
        "newTabBtns": []
      },
      "oPvtGQIvR9Am": {
        "type": 2,
        "id": "oPvtGQIvR9Am",
        "name": "len: 6",
        "color": "toolbar",
        "iconSVG": "icon_tabs",
        "iconIMGSrc": "",
        "iconIMG": "",
        "lockedPanel": false,
        "skipOnSwitching": false,
        "noEmpty": false,
        "newTabCtx": "none",
        "dropTabCtx": "none",
        "moveTabCtx": "none",
        "moveTabCtxNoChild": true,
        "urlRulesActive": false,
        "urlRules": "",
        "bookmarksFolderId": -1,
        "newTabBtns": []
      },
      "77PJQY1X7zAm": {
        "type": 2,
        "id": "77PJQY1X7zAm",
        "name": "len: 6",
        "color": "toolbar",
        "iconSVG": "icon_tabs",
        "iconIMGSrc": "",
        "iconIMG": "",
        "lockedPanel": false,
        "skipOnSwitching": false,
        "noEmpty": false,
        "newTabCtx": "none",
        "dropTabCtx": "none",
        "moveTabCtx": "none",
        "moveTabCtxNoChild": true,
        "urlRulesActive": false,
        "urlRules": "",
        "bookmarksFolderId": -1,
        "newTabBtns": []
      },
      "Gi2njE8Dnlan": {
        "type": 2,
        "id": "Gi2njE8Dnlan",
        "name": "len: 6",
        "color": "toolbar",
        "iconSVG": "icon_tabs",
        "iconIMGSrc": "",
        "iconIMG": "",
        "lockedPanel": false,
        "skipOnSwitching": false,
        "noEmpty": false,
        "newTabCtx": "none",
        "dropTabCtx": "none",
        "moveTabCtx": "none",
        "moveTabCtxNoChild": true,
        "urlRulesActive": false,
        "urlRules": "",
        "bookmarksFolderId": -1,
        "newTabBtns": []
      }
    },
    "nav": [
      "search",
      "history",
      "bookmarks",
      "sd-0RTG0nRBEA0E",
      "firefox-default",
      "oPvtGQIvR9Am",
      "77PJQY1X7zAm",
      "Gi2njE8Dnlan",
      "sd-LG6U0Z8jb4ZE",
      "add_tp",
      "remute_audio_tabs",
      "collapse",
      "sd-0Ruoc0-VQ28E",
      "sp-0",
      "sd-apkhtLfLJqBF",
      "create_snapshot",
      "settings"
    ]
  },
  "containers": [
    {
      "id": "firefox-container-1",
      "name": "8",
      "icon": "...",
      "color": "blue",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": "",
      "cookieStoreId": "firefox-container-1",
      "colorCode": "#37adff"
    },
    {
      "id": "firefox-container-2",
      "name": "4",
      "icon": "...",
      "color": "orange",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": "",
      "cookieStoreId": "firefox-container-2",
      "colorCode": "#37adff"
    },
    {
      "id": "firefox-container-3",
      "name": "7",
      "icon": "...",
      "color": "green",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": "",
      "cookieStoreId": "firefox-container-3",
      "colorCode": "#37adff"
    },
    {
      "id": "firefox-container-4",
      "name": "8",
      "icon": "...",
      "color": "pink",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": "",
      "cookieStoreId": "firefox-container-4",
      "colorCode": "#37adff"
    },
    {
      "id": "firefox-container-6",
      "name": "3",
      "icon": "...",
      "color": "toolbar",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": "",
      "cookieStoreId": "firefox-container-6",
      "colorCode": "#37adff"
    },
    {
      "id": "firefox-container-7",
      "name": "21",
      "icon": "...",
      "color": "toolbar",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": "",
      "cookieStoreId": "firefox-container-7",
      "colorCode": "#37adff"
    },
    {
      "id": "firefox-container-8",
      "name": "11",
      "icon": "...",
      "color": "blue",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": "",
      "cookieStoreId": "firefox-container-8",
      "colorCode": "#37adff"
    }
  ],
  "windows": [
    {
      "state": "normal",
      "incognito": false,
      "tabsCount": 3
    },
    {
      "state": "maximized",
      "incognito": false,
      "tabsCount": 109
    },
    {
      "state": "maximized",
      "incognito": false,
      "tabsCount": 72
    },
    {
      "state": "normal",
      "incognito": false,
      "tabsCount": 79
    },
    {
      "state": "maximized",
      "incognito": false,
      "tabsCount": 52
    },
    {
      "state": "normal",
      "incognito": false,
      "tabsCount": 198
    },
    {
      "state": "maximized",
      "incognito": false,
      "tabsCount": 208
    },
    {
      "state": "maximized",
      "incognito": false,
      "tabsCount": 286
    }
  ],
  "bookmarks": {
    "bookmarksCount": 1783,
    "foldersCount": 236,
    "separatorsCount": 1,
    "maxDepth": 5
  }
}
</code></details>

### Logs
<details><code>
</code></details>

**Comment by mbnuqw** [comment]
Thank you for the report! This is happening b/c sidebery think that the new tab is reopened and sidebery is trying to restore its previous position. And you probably use some new-tab addon (or non-standard `about:newtab`/`about:blank`), right? I forgot about this case, will try to fix this asap.

**Comment by polt515** [comment]
This same problem occurs when I set " Place new tab (general rule) to none " Ctrl + T opens a new tab in a different panel.

**Comment by mbnuqw** [comment]
@polt515, in this case it's expected behavior. By default, Ctrl+T (it's Firefox shortcut and addons cannot handle it) is opening tab at the end of the tabs list and because "Place new tab" is set to "none" Sidebery is not moving this tab and just assigning it to the nearest panel.

**Comment by polt515** [comment]
> 

So even if "Hide native tab of inactive panels is on" Ctrl+T will still move to a different panel

**Comment by megamorphg** [comment]
@polt515 you just need to set place new tab to "Panel End" or whatever else you want--anything except none.
