### ISSUE TITLE
[v5] Menu editor for tabs context menu: sub-menu item disappears if similar starting name as menu

### ISSUE THREAD

**Issue by megamorphg** [mbnuqw/sidebery#663]
## Steps to reproduce
1. Go to Menu editor for tabs and add a sub-menu 
2. Name sub-menu with a similar starting name as sub-item
3. Observe characters disappear in UI and context menu for sub-items
![Menu Editor Tabs Context Menu](https://user-images.githubusercontent.com/1782353/173497136-d1a31077-659d-4e17-8ef8-2145d046622b.gif)

## Expected behavior
Sub-menu name can be starting similar to sub-item without erasing

## Actual behavior
Sub-menu name cannot be starting similar to sub-item without erasing

### Logs
<details><code>
{
  "settings": {
    "nativeScrollbars": true,
    "nativeScrollbarsThin": false,
    "nativeScrollbarsLeft": false,
    "selWinScreenshots": true,
    "updateSidebarTitle": true,
    "markWindow": false,
    "markWindowPreface": "[SB] ",
    "logLvl": 3,
    "ctxMenuNative": true,
    "ctxMenuRenderInact": true,
    "ctxMenuRenderIcons": true,
    "ctxMenuIgnoreContainers": "",
    "navBarLayout": "vertical",
    "navBarInline": false,
    "navBarSide": "left",
    "hideAddBtn": false,
    "hideSettingsBtn": false,
    "navBtnCount": true,
    "hideEmptyPanels": false,
    "navActTabsPanelLeftClickAction": "new_tab",
    "navActBookmarksPanelLeftClickAction": "scroll",
    "navTabsPanelMidClickAction": "discard",
    "navBookmarksPanelMidClickAction": "convert",
    "navSwitchPanelsWheel": true,
    "groupLayout": "list",
    "skipEmptyPanels": true,
    "dndTabAct": true,
    "dndTabActDelay": 5000,
    "dndTabActMod": "alt",
    "dndExp": "pointer",
    "dndExpDelay": 50,
    "dndExpMod": "alt",
    "dndOutside": "data",
    "searchBarMode": "static",
    "warnOnMultiTabClose": "any",
    "activateLastTabOnPanelSwitching": true,
    "showTabRmBtn": true,
    "hideInact": true,
    "activateAfterClosing": "prev",
    "activateAfterClosingGlobal": true,
    "activateAfterClosingNoFolded": true,
    "activateAfterClosingNoDiscarded": false,
    "askNewBookmarkPlace": true,
    "tabsRmUndoNote": true,
    "nativeHighlight": true,
    "tabsUnreadMark": true,
    "tabsReloadLimit": 5,
    "tabsReloadLimitNotif": true,
    "showNewTabBtns": true,
    "newTabBarPosition": "bottom",
    "tabsPanelSwitchActMove": true,
    "openSubPanelOnMouseHover": false,
    "colorizeTabs": true,
    "colorizeTabsSrc": "domain",
    "moveNewTabPin": "end",
    "moveNewTabParent": "default",
    "moveNewTabParentActPanel": true,
    "moveNewTab": "none",
    "pinnedTabsPosition": "left",
    "pinnedTabsList": true,
    "pinnedAutoGroup": true,
    "tabsTree": true,
    "groupOnOpen": true,
    "tabsTreeLimit": "none",
    "hideFoldedTabs": true,
    "autoFoldTabs": false,
    "autoFoldTabsExcept": 5,
    "autoExpandTabs": false,
    "rmChildTabs": "folded",
    "tabsChildCount": true,
    "tabsLvlDots": true,
    "discardFolded": true,
    "discardFoldedDelay": 10,
    "discardFoldedDelayUnit": "min",
    "tabsTreeBookmarks": true,
    "treeRmOutdent": "first_child",
    "colorizeTabsBranches": false,
    "colorizeTabsBranchesSrc": "url",
    "warnOnMultiBookmarkDelete": "any",
    "autoCloseBookmarks": false,
    "autoRemoveOther": false,
    "highlightOpenBookmarks": true,
    "activateOpenBookmarkTab": false,
    "showBookmarkLen": true,
    "bookmarksRmUndoNote": true,
    "loadBookmarksOnDemand": true,
    "pinOpenedBookmarksFolder": true,
    "loadHistoryOnDemand": false,
    "fontSize": "xxl",
    "animations": true,
    "animationSpeed": "norm",
    "theme": "proton",
    "colorScheme": "ff",
    "sidebarCSS": false,
    "groupCSS": false,
    "snapNotify": true,
    "snapExcludePrivate": false,
    "snapInterval": 3,
    "snapIntervalUnit": "hr",
    "snapLimit": 7,
    "snapLimitUnit": "day",
    "hScrollAction": "switch_panels",
    "navSwitchPanelsDelay": 128,
    "scrollThroughTabs": "panel",
    "scrollThroughVisibleTabs": true,
    "scrollThroughTabsSkipDiscarded": true,
    "scrollThroughTabsExceptOverflow": false,
    "scrollThroughTabsCyclic": true,
    "scrollThroughTabsScrollArea": 70,
    "autoMenuMultiSel": true,
    "longClickDelay": 500,
    "wheelThreshold": false,
    "wheelThresholdX": 10,
    "wheelThresholdY": 60,
    "tabDoubleClick": "none",
    "tabsSecondClickActPrev": true,
    "shiftSelAct": true,
    "activateOnMouseUp": true,
    "tabLongLeftClick": "none",
    "tabLongRightClick": "duplicate",
    "tabCloseMiddleClick": "discard",
    "tabsPanelLeftClickAction": "none",
    "tabsPanelDoubleClickAction": "collapse",
    "tabsPanelRightClickAction": "menu",
    "tabsPanelMiddleClickAction": "rm_act_tab",
    "bookmarksLeftClickAction": "open_in_new",
    "bookmarksLeftClickActivate": true,
    "bookmarksLeftClickPos": "after",
    "bookmarksMidClickAction": "open_in_new",
    "bookmarksMidClickActivate": false,
    "bookmarksMidClickPos": "default",
    "syncName": "Firefox X470",
    "syncSaveSettings": true,
    "syncSaveCtxMenu": true,
    "syncSaveStyles": true,
    "syncSaveKeybindings": true
  },
  "permissions": {
    "allUrls": true,
    "tabHide": true,
    "clipboardWrite": true,
    "webRequest": true,
    "webRequestBlocking": true
  },
  "storage": {
    "size": "2.42 mb",
    "props": {
      "containers": "2.21 kb",
      "contextMenu": "1.43 kb",
      "expandedBookmarkFolders": "75 b",
      "favDomains": "32.3 kb",
      "favHashes": "3.59 kb",
      "favicons": "256 kb",
      "groupCSS": "2 b",
      "lastSnapTime": "13 b",
      "panelIndex": "1 b",
      "prevTabsDataCache": "157 kb",
      "profileID": "14 b",
      "settings": "3.48 kb",
      "sidebar": "2.07 kb",
      "sidebarCSS": "2 b",
      "snapshots": "1.82 mb",
      "tabsDataCache": "157 kb",
      "ver": "10 b"
    }
  },
  "sidebar": {
    "panels": {
      "history": {
        "type": 4,
        "id": "history",
        "name": "len: 7",
        "color": "toolbar",
        "iconSVG": "icon_clock",
        "tempMode": false,
        "lockedPanel": false,
        "skipOnSwitching": false,
        "viewMode": "history"
      },
      "bookmarks": {
        "type": 1,
        "id": "bookmarks",
        "name": "len: 9",
        "iconSVG": "icon_bookmarks",
        "iconIMGSrc": "",
        "iconIMG": "",
        "color": "toolbar",
        "lockedPanel": false,
        "tempMode": false,
        "skipOnSwitching": false,
        "rootId": "root________",
        "viewMode": "tree",
        "autoConvert": false
      },
      "firefox-default": {
        "type": 2,
        "id": "firefox-default",
        "name": "len: 7",
        "color": "toolbar",
        "iconSVG": "icon_tabs",
        "iconIMGSrc": "",
        "iconIMG": "",
        "lockedPanel": false,
        "skipOnSwitching": false,
        "noEmpty": false,
        "newTabCtx": "none",
        "dropTabCtx": "none",
        "moveTabCtx": "none",
        "moveTabCtxNoChild": true,
        "urlRulesActive": false,
        "urlRules": "",
        "bookmarksFolderId": -1,
        "newTabBtns": []
      },
      "oPvtGQIvR9Am": {
        "type": 2,
        "id": "oPvtGQIvR9Am",
        "name": "len: 6",
        "color": "toolbar",
        "iconSVG": "icon_tabs",
        "iconIMGSrc": "",
        "iconIMG": "",
        "lockedPanel": false,
        "skipOnSwitching": false,
        "noEmpty": false,
        "newTabCtx": "none",
        "dropTabCtx": "none",
        "moveTabCtx": "none",
        "moveTabCtxNoChild": true,
        "urlRulesActive": false,
        "urlRules": "",
        "bookmarksFolderId": -1,
        "newTabBtns": []
      },
      "77PJQY1X7zAm": {
        "type": 2,
        "id": "77PJQY1X7zAm",
        "name": "len: 6",
        "color": "toolbar",
        "iconSVG": "icon_tabs",
        "iconIMGSrc": "",
        "iconIMG": "",
        "lockedPanel": false,
        "skipOnSwitching": false,
        "noEmpty": false,
        "newTabCtx": "none",
        "dropTabCtx": "none",
        "moveTabCtx": "none",
        "moveTabCtxNoChild": true,
        "urlRulesActive": false,
        "urlRules": "",
        "bookmarksFolderId": -1,
        "newTabBtns": []
      },
      "Gi2njE8Dnlan": {
        "type": 2,
        "id": "Gi2njE8Dnlan",
        "name": "len: 6",
        "color": "toolbar",
        "iconSVG": "icon_tabs",
        "iconIMGSrc": "",
        "iconIMG": "",
        "lockedPanel": false,
        "skipOnSwitching": false,
        "noEmpty": false,
        "newTabCtx": "none",
        "dropTabCtx": "none",
        "moveTabCtx": "none",
        "moveTabCtxNoChild": true,
        "urlRulesActive": false,
        "urlRules": "",
        "bookmarksFolderId": -1,
        "newTabBtns": []
      }
    },
    "nav": [
      "search",
      "history",
      "bookmarks",
      "sd-0RTG0nRBEA0E",
      "firefox-default",
      "oPvtGQIvR9Am",
      "77PJQY1X7zAm",
      "Gi2njE8Dnlan",
      "sd-LG6U0Z8jb4ZE",
      "add_tp",
      "sd-e-Q-eSYNM2fG",
      "remute_audio_tabs",
      "collapse",
      "sd-0Ruoc0-VQ28E",
      "sp-0",
      "sd-apkhtLfLJqBF",
      "create_snapshot",
      "settings"
    ]
  },
  "containers": [
    {
      "id": "firefox-container-1",
      "name": "8",
      "icon": "...",
      "color": "blue",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": "",
      "cookieStoreId": "firefox-container-1",
      "colorCode": "#37adff"
    },
    {
      "id": "firefox-container-2",
      "name": "4",
      "icon": "...",
      "color": "orange",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": "",
      "cookieStoreId": "firefox-container-2",
      "colorCode": "#37adff"
    },
    {
      "id": "firefox-container-3",
      "name": "7",
      "icon": "...",
      "color": "green",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": "",
      "cookieStoreId": "firefox-container-3",
      "colorCode": "#37adff"
    },
    {
      "id": "firefox-container-4",
      "name": "8",
      "icon": "...",
      "color": "pink",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": "",
      "cookieStoreId": "firefox-container-4",
      "colorCode": "#37adff"
    },
    {
      "id": "firefox-container-6",
      "name": "3",
      "icon": "...",
      "color": "toolbar",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": "",
      "cookieStoreId": "firefox-container-6",
      "colorCode": "#37adff"
    },
    {
      "id": "firefox-container-7",
      "name": "21",
      "icon": "...",
      "color": "toolbar",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": "",
      "cookieStoreId": "firefox-container-7",
      "colorCode": "#37adff"
    },
    {
      "id": "firefox-container-8",
      "name": "11",
      "icon": "...",
      "color": "blue",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": "",
      "cookieStoreId": "firefox-container-8",
      "colorCode": "#37adff"
    }
  ],
  "windows": [
    {
      "state": "normal",
      "incognito": false,
      "tabsCount": 3
    },
    {
      "state": "maximized",
      "incognito": false,
      "tabsCount": 109
    },
    {
      "state": "maximized",
      "incognito": false,
      "tabsCount": 72
    },
    {
      "state": "normal",
      "incognito": false,
      "tabsCount": 79
    },
    {
      "state": "maximized",
      "incognito": false,
      "tabsCount": 51
    },
    {
      "state": "fullscreen",
      "incognito": false,
      "tabsCount": 198
    },
    {
      "state": "maximized",
      "incognito": false,
      "tabsCount": 209
    },
    {
      "state": "maximized",
      "incognito": false,
      "tabsCount": 286
    }
  ],
  "bookmarks": {
    "bookmarksCount": 1783,
    "foldersCount": 236,
    "separatorsCount": 1,
    "maxDepth": 5
  }
}
</code></details>

**Comment by mbnuqw** [comment]
Hm.. indeed, an empty string is not a very clear description for menu item.

**Comment by megamorphg** [comment]
Working now!
