### ISSUE TITLE
[v5] Moving a child out of a parent with keyboard shortcut, causes sibling tabs to flatten or rearrange

### ISSUE THREAD

**Issue by megamorphg** [mbnuqw/sidebery#669]
## Steps to reproduce
![2022-06-17-1416-31 moving child up out of a tree](https://user-images.githubusercontent.com/1782353/174402532-e8c6d781-e21b-4571-a906-ad6893c2cf36.gif)
1. Create a tree as shown
2. Move child up out of parent node using keyboard shortcut
3. Observe sibling tabs above parent all flatten

![2022-06-17-1424-40](https://user-images.githubusercontent.com/1782353/174403134-f830d831-33a5-4476-b4e8-9e9c7c7c8efc.gif)
1. Create a tree as shown
2. Move child up down out of parent node using keyboard shortcut
3. Observe sibling tabs below parent rearrange

## Expected behavior
Child tabs do not affect other tab positions when moved up or down out of a parent via keyboard shortcut.

The tab(s) that are being moved should maintain their own structure and be moved to position without affecting other tab indentation.

## Actual behavior
Child tabs moved up or down out of a parent via keyboard shortcut cause sibling tabs to be flattened or other strange behavior.

### Addon data
<details><code>
{
  "settings": {
    "nativeScrollbars": true,
    "nativeScrollbarsThin": false,
    "nativeScrollbarsLeft": true,
    "selWinScreenshots": true,
    "updateSidebarTitle": true,
    "markWindow": false,
    "markWindowPreface": "[SB] ",
    "logLvl": 3,
    "ctxMenuNative": true,
    "ctxMenuRenderInact": true,
    "ctxMenuRenderIcons": true,
    "ctxMenuIgnoreContainers": "",
    "navBarLayout": "vertical",
    "navBarInline": false,
    "navBarSide": "left",
    "hideAddBtn": false,
    "hideSettingsBtn": false,
    "navBtnCount": true,
    "hideEmptyPanels": true,
    "navActTabsPanelLeftClickAction": "new_tab",
    "navActBookmarksPanelLeftClickAction": "scroll",
    "navTabsPanelMidClickAction": "discard",
    "navBookmarksPanelMidClickAction": "convert",
    "navSwitchPanelsWheel": true,
    "groupLayout": "list",
    "skipEmptyPanels": true,
    "dndTabAct": true,
    "dndTabActDelay": 5000,
    "dndTabActMod": "alt",
    "dndExp": "pointer",
    "dndExpDelay": 50,
    "dndExpMod": "alt",
    "dndOutside": "data",
    "searchBarMode": "static",
    "warnOnMultiTabClose": "any",
    "activateLastTabOnPanelSwitching": true,
    "showTabRmBtn": true,
    "hideInact": true,
    "activateAfterClosing": "prev",
    "activateAfterClosingGlobal": true,
    "activateAfterClosingNoFolded": true,
    "activateAfterClosingNoDiscarded": false,
    "askNewBookmarkPlace": true,
    "tabsRmUndoNote": true,
    "nativeHighlight": true,
    "tabsUnreadMark": true,
    "tabsReloadLimit": 5,
    "tabsReloadLimitNotif": true,
    "showNewTabBtns": true,
    "newTabBarPosition": "bottom",
    "tabsPanelSwitchActMove": true,
    "openSubPanelOnMouseHover": false,
    "colorizeTabs": true,
    "colorizeTabsSrc": "domain",
    "moveNewTabPin": "end",
    "moveNewTabParent": "default",
    "moveNewTabParentActPanel": true,
    "moveNewTab": "none",
    "pinnedTabsPosition": "left",
    "pinnedTabsList": true,
    "pinnedAutoGroup": false,
    "tabsTree": true,
    "groupOnOpen": true,
    "tabsTreeLimit": "none",
    "hideFoldedTabs": true,
    "autoFoldTabs": false,
    "autoFoldTabsExcept": 5,
    "autoExpandTabs": false,
    "rmChildTabs": "folded",
    "tabsChildCount": true,
    "tabsLvlDots": true,
    "discardFolded": true,
    "discardFoldedDelay": 10,
    "discardFoldedDelayUnit": "min",
    "tabsTreeBookmarks": true,
    "treeRmOutdent": "first_child",
    "colorizeTabsBranches": false,
    "colorizeTabsBranchesSrc": "url",
    "warnOnMultiBookmarkDelete": "any",
    "autoCloseBookmarks": false,
    "autoRemoveOther": false,
    "highlightOpenBookmarks": true,
    "activateOpenBookmarkTab": true,
    "showBookmarkLen": true,
    "bookmarksRmUndoNote": true,
    "loadBookmarksOnDemand": true,
    "pinOpenedBookmarksFolder": true,
    "loadHistoryOnDemand": true,
    "fontSize": "xxl",
    "animations": true,
    "animationSpeed": "norm",
    "theme": "compact",
    "colorScheme": "ff",
    "sidebarCSS": false,
    "groupCSS": false,
    "snapNotify": true,
    "snapExcludePrivate": false,
    "snapInterval": 5,
    "snapIntervalUnit": "hr",
    "snapLimit": 50,
    "snapLimitUnit": "day",
    "hScrollAction": "switch_act_tabs",
    "navSwitchPanelsDelay": 128,
    "scrollThroughTabs": "panel",
    "scrollThroughVisibleTabs": true,
    "scrollThroughTabsSkipDiscarded": true,
    "scrollThroughTabsExceptOverflow": false,
    "scrollThroughTabsCyclic": true,
    "scrollThroughTabsScrollArea": -80,
    "autoMenuMultiSel": true,
    "longClickDelay": 500,
    "wheelThreshold": false,
    "wheelThresholdX": 10,
    "wheelThresholdY": 60,
    "tabDoubleClick": "none",
    "tabsSecondClickActPrev": true,
    "shiftSelAct": true,
    "activateOnMouseUp": true,
    "tabLongLeftClick": "none",
    "tabLongRightClick": "duplicate",
    "tabCloseMiddleClick": "discard",
    "tabsPanelLeftClickAction": "none",
    "tabsPanelDoubleClickAction": "collapse",
    "tabsPanelRightClickAction": "menu",
    "tabsPanelMiddleClickAction": "rm_act_tab",
    "bookmarksLeftClickAction": "open_in_new",
    "bookmarksLeftClickActivate": true,
    "bookmarksLeftClickPos": "after",
    "bookmarksMidClickAction": "open_in_new",
    "bookmarksMidClickActivate": false,
    "bookmarksMidClickPos": "default",
    "syncName": "Firefox X470",
    "syncSaveSettings": true,
    "syncSaveCtxMenu": true,
    "syncSaveStyles": true,
    "syncSaveKeybindings": true
  },
  "permissions": {
    "allUrls": true,
    "tabHide": true,
    "clipboardWrite": true,
    "webRequest": true,
    "webRequestBlocking": true
  },
  "storage": {
    "size": "3.37 mb",
    "props": {
      "bookmarksRecentFolders": "16 b",
      "containers": "2.21 kb",
      "contextMenu": "1.43 kb",
      "expandedBookmarkFolders": "75 b",
      "favDomains": "48 kb",
      "favHashes": "4.33 kb",
      "favicons": "310 kb",
      "groupCSS": "2 b",
      "lastSnapTime": "13 b",
      "panelIndex": "1 b",
      "prevTabsDataCache": "158 kb",
      "profileID": "14 b",
      "settings": "3.48 kb",
      "sidebar": "4.22 kb",
      "sidebarCSS": "2 b",
      "snapshots": "2.7 mb",
      "tabsDataCache": "158 kb",
      "ver": "10 b"
    }
  },
  "sidebar": {
    "panels": {
      "history": {
        "type": 4,
        "id": "history",
        "name": "len: 7",
        "color": "toolbar",
        "iconSVG": "icon_clock",
        "tempMode": false,
        "lockedPanel": false,
        "skipOnSwitching": false,
        "viewMode": "history"
      },
      "bookmarks": {
        "type": 1,
        "id": "bookmarks",
        "name": "len: 9",
        "iconSVG": "icon_bookmarks",
        "iconIMGSrc": "",
        "iconIMG": "",
        "color": "toolbar",
        "lockedPanel": false,
        "tempMode": false,
        "skipOnSwitching": false,
        "rootId": "root________",
        "viewMode": "tree",
        "autoConvert": false
      },
      "oPvtGQIvR9Am": {
        "type": 2,
        "id": "oPvtGQIvR9Am",
        "name": "len: 7",
        "color": "toolbar",
        "iconSVG": "icon_tabs",
        "iconIMGSrc": "",
        "iconIMG": "",
        "lockedPanel": false,
        "skipOnSwitching": false,
        "noEmpty": false,
        "newTabCtx": "none",
        "dropTabCtx": "none",
        "moveTabCtx": "none",
        "moveTabCtxNoChild": true,
        "urlRulesActive": false,
        "urlRules": "",
        "bookmarksFolderId": -1,
        "newTabBtns": []
      },
      "l57xRuBBu53N": {
        "type": 2,
        "id": "l57xRuBBu53N",
        "name": "len: 6",
        "color": "toolbar",
        "iconSVG": "icon_tabs",
        "iconIMGSrc": "",
        "iconIMG": "",
        "lockedPanel": false,
        "skipOnSwitching": false,
        "noEmpty": false,
        "newTabCtx": "none",
        "dropTabCtx": "none",
        "moveTabCtx": "none",
        "moveTabCtxNoChild": true,
        "urlRulesActive": false,
        "urlRules": "",
        "bookmarksFolderId": -1,
        "newTabBtns": []
      },
      "firefox-default": {
        "type": 2,
        "id": "firefox-default",
        "name": "len: 6",
        "color": "blue",
        "iconSVG": "icon_tabs",
        "iconIMGSrc": "",
        "iconIMG": "",
        "lockedPanel": false,
        "skipOnSwitching": false,
        "noEmpty": false,
        "newTabCtx": "none",
        "dropTabCtx": "none",
        "moveTabCtx": "none",
        "moveTabCtxNoChild": true,
        "urlRulesActive": false,
        "urlRules": "",
        "bookmarksFolderId": "v1-NPzNuzw9d",
        "newTabBtns": []
      },
      "77PJQY1X7zAm": {
        "type": 2,
        "id": "77PJQY1X7zAm",
        "name": "len: 6",
        "color": "turquoise",
        "iconSVG": "icon_tabs",
        "iconIMGSrc": "",
        "iconIMG": "",
        "lockedPanel": false,
        "skipOnSwitching": false,
        "noEmpty": false,
        "newTabCtx": "none",
        "dropTabCtx": "none",
        "moveTabCtx": "none",
        "moveTabCtxNoChild": true,
        "urlRulesActive": false,
        "urlRules": "",
        "bookmarksFolderId": -1,
        "newTabBtns": []
      },
      "Gi2njE8Dnlan": {
        "type": 2,
        "id": "Gi2njE8Dnlan",
        "name": "len: 6",
        "color": "green",
        "iconSVG": "icon_tabs",
        "iconIMGSrc": "",
        "iconIMG": "",
        "lockedPanel": false,
        "skipOnSwitching": false,
        "noEmpty": false,
        "newTabCtx": "none",
        "dropTabCtx": "none",
        "moveTabCtx": "none",
        "moveTabCtxNoChild": true,
        "urlRulesActive": false,
        "urlRules": "",
        "bookmarksFolderId": -1,
        "newTabBtns": []
      },
      "wdzkA8VBChsL": {
        "type": 2,
        "id": "wdzkA8VBChsL",
        "name": "len: 6",
        "color": "yellow",
        "iconSVG": "icon_tabs",
        "iconIMGSrc": "",
        "iconIMG": "",
        "lockedPanel": false,
        "skipOnSwitching": false,
        "noEmpty": false,
        "newTabCtx": "none",
        "dropTabCtx": "none",
        "moveTabCtx": "none",
        "moveTabCtxNoChild": true,
        "urlRulesActive": false,
        "urlRules": "",
        "bookmarksFolderId": -1,
        "newTabBtns": []
      },
      "Ak5q9G_7_hsL": {
        "type": 2,
        "id": "Ak5q9G_7_hsL",
        "name": "len: 6",
        "color": "orange",
        "iconSVG": "icon_tabs",
        "iconIMGSrc": "",
        "iconIMG": "",
        "lockedPanel": false,
        "skipOnSwitching": false,
        "noEmpty": false,
        "newTabCtx": "none",
        "dropTabCtx": "none",
        "moveTabCtx": "none",
        "moveTabCtxNoChild": true,
        "urlRulesActive": false,
        "urlRules": "",
        "bookmarksFolderId": -1,
        "newTabBtns": []
      },
      "tIpuOF5MEisL": {
        "type": 2,
        "id": "tIpuOF5MEisL",
        "name": "len: 6",
        "color": "red",
        "iconSVG": "icon_tabs",
        "iconIMGSrc": "",
        "iconIMG": "",
        "lockedPanel": false,
        "skipOnSwitching": false,
        "noEmpty": false,
        "newTabCtx": "none",
        "dropTabCtx": "none",
        "moveTabCtx": "none",
        "moveTabCtxNoChild": true,
        "urlRulesActive": false,
        "urlRules": "",
        "bookmarksFolderId": -1,
        "newTabBtns": []
      },
      "sIhAINvH6isL": {
        "type": 2,
        "id": "sIhAINvH6isL",
        "name": "len: 6",
        "color": "pink",
        "iconSVG": "icon_tabs",
        "iconIMGSrc": "",
        "iconIMG": "",
        "lockedPanel": false,
        "skipOnSwitching": false,
        "noEmpty": false,
        "newTabCtx": "none",
        "dropTabCtx": "none",
        "moveTabCtx": "none",
        "moveTabCtxNoChild": true,
        "urlRulesActive": false,
        "urlRules": "",
        "bookmarksFolderId": -1,
        "newTabBtns": []
      },
      "nNIxD1ytsrsL": {
        "type": 2,
        "id": "nNIxD1ytsrsL",
        "name": "len: 6",
        "color": "purple",
        "iconSVG": "icon_tabs",
        "iconIMGSrc": "",
        "iconIMG": "",
        "lockedPanel": false,
        "skipOnSwitching": false,
        "noEmpty": false,
        "newTabCtx": "none",
        "dropTabCtx": "none",
        "moveTabCtx": "none",
        "moveTabCtxNoChild": true,
        "urlRulesActive": false,
        "urlRules": "",
        "bookmarksFolderId": -1,
        "newTabBtns": []
      }
    },
    "nav": [
      "search",
      "history",
      "bookmarks",
      "sd-0RTG0nRBEA0E",
      "oPvtGQIvR9Am",
      "l57xRuBBu53N",
      "firefox-default",
      "77PJQY1X7zAm",
      "Gi2njE8Dnlan",
      "wdzkA8VBChsL",
      "Ak5q9G_7_hsL",
      "tIpuOF5MEisL",
      "sIhAINvH6isL",
      "nNIxD1ytsrsL",
      "sd-LG6U0Z8jb4ZE",
      "add_tp",
      "sd-e-Q-eSYNM2fG",
      "remute_audio_tabs",
      "collapse",
      "sd-0Ruoc0-VQ28E",
      "sp-0",
      "sd-apkhtLfLJqBF",
      "create_snapshot",
      "settings"
    ]
  },
  "containers": [
    {
      "id": "firefox-container-1",
      "name": "8",
      "icon": "...",
      "color": "blue",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": "",
      "cookieStoreId": "firefox-container-1",
      "colorCode": "#37adff"
    },
    {
      "id": "firefox-container-2",
      "name": "4",
      "icon": "...",
      "color": "orange",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": "",
      "cookieStoreId": "firefox-container-2",
      "colorCode": "#37adff"
    },
    {
      "id": "firefox-container-3",
      "name": "7",
      "icon": "...",
      "color": "green",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": "",
      "cookieStoreId": "firefox-container-3",
      "colorCode": "#37adff"
    },
    {
      "id": "firefox-container-4",
      "name": "8",
      "icon": "...",
      "color": "pink",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": "",
      "cookieStoreId": "firefox-container-4",
      "colorCode": "#37adff"
    },
    {
      "id": "firefox-container-6",
      "name": "3",
      "icon": "...",
      "color": "toolbar",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": "",
      "cookieStoreId": "firefox-container-6",
      "colorCode": "#37adff"
    },
    {
      "id": "firefox-container-7",
      "name": "21",
      "icon": "...",
      "color": "toolbar",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": "",
      "cookieStoreId": "firefox-container-7",
      "colorCode": "#37adff"
    },
    {
      "id": "firefox-container-8",
      "name": "11",
      "icon": "...",
      "color": "blue",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": "",
      "cookieStoreId": "firefox-container-8",
      "colorCode": "#37adff"
    }
  ],
  "windows": [
    {
      "state": "normal",
      "incognito": false,
      "tabsCount": 3
    },
    {
      "state": "maximized",
      "incognito": false,
      "tabsCount": 117
    },
    {
      "state": "maximized",
      "incognito": false,
      "tabsCount": 79
    },
    {
      "state": "normal",
      "incognito": false,
      "tabsCount": 78
    },
    {
      "state": "maximized",
      "incognito": false,
      "tabsCount": 50
    },
    {
      "state": "normal",
      "incognito": false,
      "tabsCount": 199
    },
    {
      "state": "maximized",
      "incognito": false,
      "tabsCount": 209
    },
    {
      "state": "maximized",
      "incognito": false,
      "tabsCount": 291
    }
  ],
  "bookmarks": {
    "bookmarksCount": 1790,
    "foldersCount": 240,
    "separatorsCount": 1,
    "maxDepth": 5
  }
}
</code></details>

**Comment by mbnuqw** [comment]
Ah, right :), closing it.
