### ISSUE TITLE
[Feature Request] Shortcuts for Closing Tabs Inside Active Panel

### ISSUE THREAD

**Issue by YahiaJr** [mbnuqw/sidebery#671]
## Description
Is it possible to create 3 shortcuts for tab-closing actions [Tabs to the right (down) | to the left (up) | other tabs] **inside the active panel**.

I have the actions in the context menu however a shortcut for each of them would be very handy in a keyboard-focused environment.

it's important for the shortcuts to do the action within the active panel, not globally. Because if it's globally, it would close tabs in other panels that may not be intended to be closed.

**Comment by mbnuqw** [comment]
Resolved in v5.0.0
