### ISSUE TITLE
[enhancement] keybinding to switch to last viewed tab

### ISSUE THREAD

**Issue by hervenicol** [mbnuqw/sidebery#673]
## Description

I often work with 2 tabs, and switch a lot between them.
I got used to using https://framagit.org/ariasuni/tst-tabflip with Treetab for it.

The behaviour is:
* I click on the current tab, it switches to the previous-active one
* I can do the same with a keyboard shortcut

I'd love to have a similar feature on Sidebery!

**Comment by albino1** [comment]
FWIW, there's already keyboard shortcuts in Sideberry for switching last active tabs.  In the settings under `Keybindings` take a look at:

`Active tabs history of panel: Back`

`Active tabs history of panel: Next`

As a side note, I used AutoHotKey to assign those keybindings to shift+mouse wheel so I can roll the wheel and scroll back and forth through all of my most recent tabs regardless of where they are in the tree.  Pretty handy.

**Comment by hervenicol** [comment]
Wow, I didn't see the tab history shortcuts :facepalm: Sorry!
And if the "click to switch to previous" is in v5, then I'll wait for it to be released, perfect!
Thanks!
