### ISSUE TITLE
[v5] Make Tab Moving Insertion Horizontal Line More Precise for Tree Level

### ISSUE THREAD

**Issue by megamorphg** [mbnuqw/sidebery#677]
## Description
Not sure if this is a bug but currently when moving a tab around the horizontal line is not precise:
![image](https://user-images.githubusercontent.com/1782353/176465276-9eeaa70b-7dca-40ad-a25c-adc5fdddb9a2.png)

The tab I am moving is going to be inserted above "System Monitor" tab but the horizontal line is confusing regarding which level of the node it will be inserted in.

This is especially important when there are a lot of tabs with different levels and than I drag left/right to put into the right level incorrectly.

It should be a simple fix by just offsetting the insertion line to the right by whatever numbering of pixels to make the line only directly under the tree level that it will insert in.

Maybe there a styling thing that I can do to offset to the right a few pixels and just get the effect I'm looking for?

**Comment by megamorphg** [comment]
I noticed another issue related to this and I'm not sure if it is now fixed in the unreleased fix you've committed above:
when dragging a tab group with many nested items to somewhere else (with many tabs including using scroll bar), it just moves it to the end, instead of the dragged-to location.
Just noting here after you've released so I can test it.

**Comment by mbnuqw** [comment]
It's probably a different bug, and unfortunately I can't reproduce it (neither on b25 nor b26). Could you describe how it can be reproduced step-by-step? (you can write in this issue without creating a new one)

**Comment by megamorphg** [comment]
Fortunately, I can't reproduce it in b26. I also did upgrade Firefox profile to an M2 instead of SSD yesterday so maybe the performance was the original cause.

Anyway, this original issue is fixed in b26 and working perfectly and we can close this.
