### ISSUE TITLE
Allow binding ctrl+w to "close multiple tabs"

### ISSUE THREAD

**Issue by willhansen** [mbnuqw/sidebery#679]
## Description

I can use ctrl+w to close one tab, but in a hilarious twist, when I try to bind it to the "close multiple tabs" option, it closes the settings tab and doesn't bind

**Comment by mbnuqw** [comment]
Firefox is not allowing to re-bind its shortcuts. Instead you can set the `Close child tabs along with parents` to `all` (in Sidebery settings / Tabs tree) and turn on the `Highlight native tabs (in top horizontal bar) along with tabs in sidebar` toggle.
