### ISSUE TITLE
grouping search results puts tabs in weird state

### ISSUE THREAD

**Issue by niun** [mbnuqw/sidebery#691]
## Steps to reproduce
*   Put multiple tabs with a common keyword on a panel with other tabs between the tabs of interest.
*   Enter the common keyword in the Sidebery search bar. The panel should now show only the tabs of interest.
*   Group all the tabs of interest (I am selecting with right mouse button, then click "Group" in the context menu, enter group name, click "create").
*   Clear the search input.

## Expected behavior
The new group should be shown in the position for new tabs (or maybe in the position of the first tab of interest). The new group should contain all the tabs of interest. (would be really cool and useful if this would work)

## Actual behavior
The new group is shown in the position of the first tab of interest, containing only this first tab. The other tabs of interest are indented one level in their original position and the "contains tabs count" of the tab(group) before is increased by one. When collapsing those groups where the tabs of interest don't belong,  the tab of interest is folded away but it does not reappear when opening the group again. Collapsing the intensionally created group with the first tab of interest, only this first tab is folded away. But when opening this group, all the other tabs of interest that disappeared after folding the other groups, reappear.

**Update:**
Sometimes this flattens nearly all groups on the panel. Don't know in which cases. Maybe if one of the tabs has no group before them. Also when not grouping but selecting the tabs of a search result and then sending them to another panel, behaves strange. Some of the tabs (all but the first one?) appears doubled in the target panel.

If all tabs in the original panel are directly consecutive, the groupin seems to work. But really useful for this functionality would be if you could group tabs with common keywords that are scattered across a panel with a lot of tabs. 

### Addon data
<details><code>
General
Context menu
Use comma-separated list of contaianers names or /regexp/
Navigation bar
Group page
Containers
Drag and Drop
Press the "Alt" key before dragging to invert this option
Search
Tabs
Position of new tab
Pinned tabs
Tabs tree
Bookmarks
History
Appearance
Notes:
- To apply theme color to Sidebery buttons in browser interface set "svg.context-properties.content.enabled" to "true" in about:config page.
Mouse
Positive - at the right, negative - at the left side of the panel
Only for non-native context menu
Navigation bar actions
Tab actions
Tabs panel actions
Bookmarks actions
Snapshots
 (20: ~358 kb)
Sync
 (~12.9 kb / 100 kb)
Settings
[ --- Removed those synced settings information as I did not want my to have my computer names in here --- ]

v5.0.0b25
{
  "settings": {
    "nativeScrollbars": true,
    "nativeScrollbarsThin": true,
    "nativeScrollbarsLeft": false,
    "selWinScreenshots": true,
    "updateSidebarTitle": true,
    "markWindow": true,
    "markWindowPreface": " ",
    "logLvl": 0,
    "ctxMenuNative": false,
    "ctxMenuRenderInact": true,
    "ctxMenuRenderIcons": true,
    "ctxMenuIgnoreContainers": "",
    "navBarLayout": "vertical",
    "navBarInline": false,
    "navBarSide": "left",
    "hideAddBtn": false,
    "hideSettingsBtn": false,
    "navBtnCount": true,
    "hideEmptyPanels": false,
    "navActTabsPanelLeftClickAction": "new_tab",
    "navActBookmarksPanelLeftClickAction": "scroll",
    "navTabsPanelMidClickAction": "discard",
    "navBookmarksPanelMidClickAction": "none",
    "navSwitchPanelsWheel": false,
    "groupLayout": "list",
    "skipEmptyPanels": false,
    "dndTabAct": true,
    "dndTabActDelay": 2500,
    "dndTabActMod": "none",
    "dndExp": "hover",
    "dndExpDelay": 1500,
    "dndExpMod": "none",
    "dndOutside": "data",
    "searchBarMode": "static",
    "warnOnMultiTabClose": "collapsed",
    "activateLastTabOnPanelSwitching": true,
    "showTabRmBtn": true,
    "hideInact": false,
    "activateAfterClosing": "next",
    "activateAfterClosingGlobal": false,
    "activateAfterClosingNoFolded": true,
    "activateAfterClosingNoDiscarded": false,
    "askNewBookmarkPlace": true,
    "tabsRmUndoNote": true,
    "nativeHighlight": true,
    "tabsUnreadMark": true,
    "tabsReloadLimit": 5,
    "tabsReloadLimitNotif": true,
    "showNewTabBtns": true,
    "newTabBarPosition": "after_tabs",
    "tabsPanelSwitchActMove": true,
    "tabsUrlInTooltip": "full",
    "openSubPanelOnMouseHover": true,
    "colorizeTabs": true,
    "colorizeTabsSrc": "domain",
    "moveNewTabPin": "start",
    "moveNewTabParent": "last_child",
    "moveNewTabParentActPanel": false,
    "moveNewTab": "end",
    "pinnedTabsPosition": "top",
    "pinnedTabsList": false,
    "pinnedAutoGroup": true,
    "tabsTree": true,
    "groupOnOpen": true,
    "tabsTreeLimit": "none",
    "hideFoldedTabs": false,
    "autoFoldTabs": false,
    "autoFoldTabsExcept": "none",
    "autoExpandTabs": false,
    "rmChildTabs": "folded",
    "tabsChildCount": true,
    "tabsLvlDots": false,
    "discardFolded": false,
    "discardFoldedDelay": 5,
    "discardFoldedDelayUnit": "min",
    "tabsTreeBookmarks": true,
    "treeRmOutdent": "branch",
    "colorizeTabsBranches": false,
    "colorizeTabsBranchesSrc": "url",
    "warnOnMultiBookmarkDelete": "collapsed",
    "autoCloseBookmarks": false,
    "autoRemoveOther": false,
    "highlightOpenBookmarks": true,
    "activateOpenBookmarkTab": true,
    "showBookmarkLen": true,
    "bookmarksRmUndoNote": true,
    "loadBookmarksOnDemand": true,
    "pinOpenedBookmarksFolder": true,
    "loadHistoryOnDemand": true,
    "fontSize": "m",
    "animations": false,
    "animationSpeed": "fast",
    "theme": "proton",
    "colorScheme": "ff",
    "sidebarCSS": true,
    "groupCSS": false,
    "snapNotify": false,
    "snapExcludePrivate": true,
    "snapInterval": 5,
    "snapIntervalUnit": "min",
    "snapLimit": 20,
    "snapLimitUnit": "snap",
    "hScrollAction": "none",
    "navSwitchPanelsDelay": 128,
    "scrollThroughTabs": "none",
    "scrollThroughVisibleTabs": false,
    "scrollThroughTabsSkipDiscarded": false,
    "scrollThroughTabsExceptOverflow": true,
    "scrollThroughTabsCyclic": true,
    "scrollThroughTabsScrollArea": 0,
    "autoMenuMultiSel": true,
    "longClickDelay": 500,
    "wheelThreshold": false,
    "wheelThresholdX": 10,
    "wheelThresholdY": 60,
    "tabDoubleClick": "new_after",
    "tabsSecondClickActPrev": false,
    "shiftSelAct": true,
    "activateOnMouseUp": true,
    "tabLongLeftClick": "none",
    "tabLongRightClick": "duplicate",
    "tabCloseMiddleClick": "discard",
    "tabsPanelLeftClickAction": "none",
    "tabsPanelDoubleClickAction": "tab",
    "tabsPanelRightClickAction": "menu",
    "tabsPanelMiddleClickAction": "undo",
    "bookmarksLeftClickAction": "open_in_act",
    "bookmarksLeftClickActivate": false,
    "bookmarksLeftClickPos": "default",
    "bookmarksMidClickAction": "open_in_new",
    "bookmarksMidClickActivate": false,
    "bookmarksMidClickPos": "default",
    "syncName": "xps13",
    "syncSaveSettings": true,
    "syncSaveCtxMenu": true,
    "syncSaveStyles": true,
    "syncSaveKeybindings": true
  },
  "permissions": {
    "allUrls": true,
    "tabHide": true,
    "clipboardWrite": true,
    "webRequest": true,
    "webRequestBlocking": true
  },
  "storage": {
    "size": "999 kb",
    "props": {
      "bookmarksRecentFolders": "31 b",
      "containers": "1.57 kb",
      "contextMenu": "1.46 kb",
      "disabledKeybindings": "2 b",
      "expandedBookmarkFolders": "272 b",
      "favDomains": "40.5 kb",
      "favHashes": "3.67 kb",
      "favicons": "265 kb",
      "groupCSS": "380 b",
      "lastSnapTime": "13 b",
      "panelIndex": "1 b",
      "prevTabsDataCache": "158 kb",
      "profileID": "14 b",
      "settings": "3.51 kb",
      "sidebar": "8.46 kb",
      "sidebarCSS": "948 b",
      "snapshots": "358 kb",
      "tabsDataCache": "157 kb",
      "ver": "10 b"
    }
  },
  "sidebar": {
    "panels": {
      "bookmarks": {
        "type": 1,
        "id": "bookmarks",
        "name": "len: 9",
        "iconSVG": "icon_bookmarks",
        "iconIMGSrc": "",
        "iconIMG": "",
        "color": "toolbar",
        "lockedPanel": false,
        "tempMode": true,
        "skipOnSwitching": false,
        "rootId": "root________",
        "viewMode": "tree",
        "autoConvert": false
      },
      "DP_k1JrgKXcT": {
        "type": 1,
        "id": "DP_k1JrgKXcT",
        "name": "len: 8",
        "iconSVG": "icon_bookmarks",
        "iconIMGSrc": "",
        "iconIMG": "",
        "color": "purple",
        "lockedPanel": false,
        "tempMode": true,
        "skipOnSwitching": false,
        "rootId": "53t2sK1WTvFe",
        "viewMode": "tree",
        "autoConvert": false
      },
      "history": {
        "type": 4,
        "id": "history",
        "name": "len: 7",
        "color": "toolbar",
        "iconSVG": "icon_clock",
        "tempMode": false,
        "lockedPanel": false,
        "skipOnSwitching": false,
        "viewMode": "history"
      },
      "zC1IzT7OBFng": {
        "type": 2,
        "id": "zC1IzT7OBFng",
        "name": "len: 10",
        "color": "green",
        "iconSVG": "icon_coffee",
        "iconIMGSrc": "",
        "iconIMG": "",
        "lockedPanel": false,
        "skipOnSwitching": false,
        "noEmpty": false,
        "newTabCtx": "none",
        "dropTabCtx": "none",
        "moveTabCtx": "none",
        "moveTabCtxNoChild": true,
        "urlRulesActive": false,
        "urlRules": "",
        "bookmarksFolderId": -1,
        "newTabBtns": []
      },
      "doi11m2Qw6XD": {
        "type": 2,
        "id": "doi11m2Qw6XD",
        "name": "len: 5",
        "color": "pink",
        "iconSVG": "icon_play",
        "iconIMGSrc": "len: 29",
        "iconIMG": "len: 602",
        "lockedPanel": false,
        "skipOnSwitching": false,
        "noEmpty": false,
        "newTabCtx": "none",
        "dropTabCtx": "none",
        "moveTabCtx": "none",
        "moveTabCtxNoChild": true,
        "urlRulesActive": false,
        "urlRules": "",
        "bookmarksFolderId": -1,
        "newTabBtns": []
      },
      "ttg1JAzCgD-g": {
        "type": 2,
        "id": "ttg1JAzCgD-g",
        "name": "len: 18",
        "color": "yellow",
        "iconSVG": "chill",
        "iconIMGSrc": "",
        "iconIMG": "",
        "lockedPanel": false,
        "skipOnSwitching": false,
        "noEmpty": false,
        "newTabCtx": "none",
        "dropTabCtx": "none",
        "moveTabCtx": "none",
        "moveTabCtxNoChild": true,
        "urlRulesActive": false,
        "urlRules": "",
        "bookmarksFolderId": -1,
        "newTabBtns": []
      },
      "I8MOJzr0LHsg": {
        "type": 2,
        "id": "I8MOJzr0LHsg",
        "name": "len: 10",
        "color": "turquoise",
        "iconSVG": "icon_books",
        "iconIMGSrc": "",
        "iconIMG": "",
        "lockedPanel": false,
        "skipOnSwitching": false,
        "noEmpty": false,
        "newTabCtx": "none",
        "dropTabCtx": "none",
        "moveTabCtx": "none",
        "moveTabCtxNoChild": true,
        "urlRulesActive": false,
        "urlRules": "",
        "bookmarksFolderId": -1,
        "newTabBtns": []
      },
      "KIwVIJ9tiDMx": {
        "type": 2,
        "id": "KIwVIJ9tiDMx",
        "name": "len: 17",
        "color": "pink",
        "iconSVG": "icon_flask",
        "iconIMGSrc": "",
        "iconIMG": "",
        "lockedPanel": false,
        "skipOnSwitching": false,
        "noEmpty": false,
        "newTabCtx": "none",
        "dropTabCtx": "none",
        "moveTabCtx": "none",
        "moveTabCtxNoChild": true,
        "urlRulesActive": false,
        "urlRules": "",
        "bookmarksFolderId": -1,
        "newTabBtns": []
      },
      "2Yhyi8xhEXMx": {
        "type": 2,
        "id": "2Yhyi8xhEXMx",
        "name": "len: 4",
        "color": "purple",
        "iconSVG": "icon_circle",
        "iconIMGSrc": "len: 946",
        "iconIMG": "len: 946",
        "lockedPanel": false,
        "skipOnSwitching": false,
        "noEmpty": false,
        "newTabCtx": "none",
        "dropTabCtx": "none",
        "moveTabCtx": "none",
        "moveTabCtxNoChild": true,
        "urlRulesActive": false,
        "urlRules": "",
        "bookmarksFolderId": -1,
        "newTabBtns": []
      },
      "Q_YNXQ9INF-f": {
        "type": 2,
        "id": "Q_YNXQ9INF-f",
        "name": "len: 8",
        "color": "red",
        "iconSVG": "cart",
        "iconIMGSrc": "",
        "iconIMG": "",
        "lockedPanel": false,
        "skipOnSwitching": false,
        "noEmpty": false,
        "newTabCtx": "none",
        "dropTabCtx": "none",
        "moveTabCtx": "none",
        "moveTabCtxNoChild": true,
        "urlRulesActive": false,
        "urlRules": "",
        "bookmarksFolderId": -1,
        "newTabBtns": []
      },
      "III1_KWisG0K": {
        "type": 2,
        "id": "III1_KWisG0K",
        "name": "len: 4",
        "color": "orange",
        "iconSVG": "dollar",
        "iconIMGSrc": "",
        "iconIMG": "",
        "lockedPanel": false,
        "skipOnSwitching": false,
        "noEmpty": false,
        "newTabCtx": "firefox-container-3",
        "dropTabCtx": "firefox-container-3",
        "moveTabCtx": "firefox-container-3",
        "moveTabCtxNoChild": true,
        "urlRulesActive": false,
        "urlRules": "",
        "bookmarksFolderId": -1,
        "newTabBtns": []
      },
      "3w1n27hy1nZx": {
        "type": 2,
        "id": "3w1n27hy1nZx",
        "name": "len: 6",
        "color": "green",
        "iconSVG": "icon_gamepad",
        "iconIMGSrc": "",
        "iconIMG": "",
        "lockedPanel": false,
        "skipOnSwitching": false,
        "noEmpty": false,
        "newTabCtx": "none",
        "dropTabCtx": "none",
        "moveTabCtx": "none",
        "moveTabCtxNoChild": true,
        "urlRulesActive": false,
        "urlRules": "",
        "bookmarksFolderId": -1,
        "newTabBtns": []
      },
      "MJlegVgfLSet": {
        "type": 2,
        "id": "MJlegVgfLSet",
        "name": "len: 22",
        "color": "blue",
        "iconSVG": "icon_search",
        "iconIMGSrc": "",
        "iconIMG": "",
        "lockedPanel": false,
        "skipOnSwitching": false,
        "noEmpty": false,
        "newTabCtx": "none",
        "dropTabCtx": "none",
        "moveTabCtx": "none",
        "moveTabCtxNoChild": true,
        "urlRulesActive": false,
        "urlRules": "",
        "bookmarksFolderId": -1,
        "newTabBtns": [
          "https://de.wikipedia.org/wiki/Wikipedia:Hauptseite",
          "https://www.onlinegdb.com/"
        ]
      },
      "UJhSQQaKNrtg": {
        "type": 2,
        "id": "UJhSQQaKNrtg",
        "name": "len: 8",
        "color": "blue",
        "iconSVG": "briefcase",
        "iconIMGSrc": "",
        "iconIMG": "",
        "lockedPanel": false,
        "skipOnSwitching": false,
        "noEmpty": false,
        "newTabCtx": "none",
        "dropTabCtx": "none",
        "moveTabCtx": "none",
        "moveTabCtxNoChild": true,
        "urlRulesActive": false,
        "urlRules": "",
        "bookmarksFolderId": -1,
        "newTabBtns": []
      },
      "upbFZnPJrQCx": {
        "type": 2,
        "id": "upbFZnPJrQCx",
        "name": "len: 11",
        "color": "blue",
        "iconSVG": "icon_book",
        "iconIMGSrc": "",
        "iconIMG": "",
        "lockedPanel": false,
        "skipOnSwitching": false,
        "noEmpty": false,
        "newTabCtx": "none",
        "dropTabCtx": "none",
        "moveTabCtx": "none",
        "moveTabCtxNoChild": true,
        "urlRulesActive": false,
        "urlRules": "",
        "bookmarksFolderId": -1,
        "newTabBtns": []
      },
      "firefox-default": {
        "type": 2,
        "id": "firefox-default",
        "name": "len: 7",
        "color": "toolbar",
        "iconSVG": "icon_tabs",
        "iconIMGSrc": "",
        "iconIMG": "",
        "lockedPanel": false,
        "skipOnSwitching": false,
        "noEmpty": false,
        "newTabCtx": "none",
        "dropTabCtx": "none",
        "moveTabCtx": "none",
        "moveTabCtxNoChild": true,
        "urlRulesActive": false,
        "urlRules": "",
        "bookmarksFolderId": -1,
        "newTabBtns": []
      }
    },
    "nav": [
      "bookmarks",
      "DP_k1JrgKXcT",
      "history",
      "sd-3bo6FjCizzVC",
      "collapse",
      "remute_audio_tabs",
      "sd-w2Dng8E9BBVC",
      "zC1IzT7OBFng",
      "doi11m2Qw6XD",
      "ttg1JAzCgD-g",
      "I8MOJzr0LHsg",
      "KIwVIJ9tiDMx",
      "2Yhyi8xhEXMx",
      "Q_YNXQ9INF-f",
      "III1_KWisG0K",
      "3w1n27hy1nZx",
      "sd-L92LNQ5ltDVC",
      "MJlegVgfLSet",
      "UJhSQQaKNrtg",
      "upbFZnPJrQCx",
      "sd-Lm3L10ZpaEVC",
      "firefox-default",
      "sd-wdJvvAVQ7KVC",
      "add_tp",
      "sp-xRaotwFiteNa",
      "create_snapshot",
      "settings"
    ]
  },
  "containers": [
    {
      "id": "firefox-container-1",
      "cookieStoreId": "firefox-container-1",
      "name": "8",
      "icon": "...",
      "color": "green",
      "colorCode": "#37adff",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-2",
      "cookieStoreId": "firefox-container-2",
      "name": "6",
      "icon": "...",
      "color": "blue",
      "colorCode": "#37adff",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-3",
      "cookieStoreId": "firefox-container-3",
      "name": "7",
      "icon": "...",
      "color": "red",
      "colorCode": "#37adff",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-4",
      "cookieStoreId": "firefox-container-4",
      "name": "9",
      "icon": "...",
      "color": "pink",
      "colorCode": "#37adff",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-6",
      "cookieStoreId": "firefox-container-6",
      "name": "8",
      "icon": "...",
      "color": "toolbar",
      "colorCode": "#37adff",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    }
  ],
  "sidebarCSSLen": "908",
  "groupCSSLen": "369",
  "windows": [
    {
      "state": "maximized",
      "incognito": false,
      "tabsCount": 862
    }
  ],
  "bookmarks": {
    "bookmarksCount": 1136,
    "foldersCount": 68,
    "separatorsCount": 4,
    "maxDepth": 6
  }
}
</code></details>

### Logs
<details><code>
[[sidebar:1] Tab created: n31 #888 panelId:zC1IzT7OBFng lvl:0 parentId:-1 chunk-RZE65QZS.js:17321:13
[sidebar:1] Tabs.updateTabsTree: 30 - 141 chunk-RZE65QZS.js:17321:13
[group:1] Settings: Loaded group.js:17175:13
[sidebar:1] Tabs.cacheTabsData chunk-RZE65QZS.js:17321:13
[bg] Store: storing: tabsDataCache chunk-RZE65QZS.js:17319:13
</code></details>

When producing the log, the newly created group swallowed another group, completely flattened. This did not happen before...

**Comment by mbnuqw** [comment]
Thank you for the report.

**Comment by niun** [comment]
Cool, on my side it looks like it is working perfectly now in v5.0.0b26. Thank you!
