### ISSUE TITLE
Incorrect tabs tree on opening bookmarks

### ISSUE THREAD

**Issue by OmTatSat** [mbnuqw/sidebery#696]
## Description
When i bookmark tabs tree it will create groups for all sub trees, and when i will restore it will create not exactlyly what i see before bookmarking.  After restore, I want ability have all sub tab trees but without groups folders near every sub tree, is it posible?

Also in bookmarks i want to see not only group name but also all tabs in sub trees.

Also ability to restore tree in exact panel and place it after active tab. Without loading restored tabs before i activate them, and with icons from bookmarks.

**Comment by OmTatSat** [comment]
Also, i think good alternative would be some enhancements to session administration, like:
have ability to see sessions in sideway bar like extra panel with bookmarks but with sessions in it.
have ability to restore selected part of sesssion
have ability to save separate session to protect it from auto deletion.

**Comment by mbnuqw** [comment]
Incorrect tabs tree on opening bookmarks is a bug. 

For session management suggestion check the #720 or create new feature request.

**Comment by zilexa** [comment]
I don't want to create another issue for just a question:

I bookmarked a group with 29 tabs in a tree. When I close the group, how can I open it again? 
It does not seem possible via Bookmarks > group > open all in tabs. Only the 2 "leaves" or tabs at the top level are opened.

**Comment by mbnuqw** [comment]
@zilexa, If you meant the native menu bar, it seems like Firefox doesn't allow opening a sub-trees of the bookmark folder. You can try using the bookmark panel in sidebery where you can open full tree of bookmarks folder.

**Comment by mbnuqw** [comment]
Fixed from v5.0.0
