### ISSUE TITLE
Custom CSS styling

### ISSUE THREAD

**Issue by brekco** [mbnuqw/sidebery#698]
If I am writing custom CSS for sideberry, how would I style only unread tabs?

**Comment by dexeonify** [comment]
Use the `.Tab[data-unread="true"]` attribute selector to style only unread tabs. FYI, you can use `about:debugging` to monitor state changes.

**Comment by brekco** [comment]
Thank you for that. It worked great. I used it to color text of unread tabs. But doing this brings up another question. If I color the text yellow for example and I open Firefox and reload the previous session, the tab text is yellow but it is very muted as if there is an overlay over the tabs that mutes the color. How can I stop that from happening? Thanks for your help.

**Comment by ongots** [comment]
```
.Tab[data-discarded="true"] > .body > .t-box, .Tab[data-discarded="true"] > .body > .ctx {
	opacity: .56;
}
```

**Comment by mbnuqw** [comment]
Seems like resolved question, closing
