### ISSUE TITLE
Issue, lock on bookmarks panel not working

### ISSUE THREAD

**Issue by gasman1844** [mbnuqw/sidebery#7]
Thanks again for your work on this. This is to report a bug introduced by 1.91. - the lock on the bookmarks panel isn't working, clicking on a bookmark results in  the panel switching to the tabs panel

> OS: win x86-64  
> Firefox: 64.0.2  
> Extension: 1.9.1

**Comment by mbnuqw** [comment]
Should be fixed in 1.9.2
