### ISSUE TITLE
Select non-adjacent tabs with the control key and clicking

### ISSUE THREAD

**Issue by ChukwuemezieChristopherAneke** [mbnuqw/sidebery#70]
Selecting multiple tabs with right click and drag works very well (more efficient than the standard Shift+click). However it is not possible to select multiple tabs individually when those tabs are not next to each other (i.e. the standard Ctrl+click is not possible). Enabling selection of non-adjacent tabs would be a useful enhancement

**Comment by 00madz** [comment]
I didnt even realise the right-click drag was an option as quite non-standard. I'd been trying with shift (to select an adjacent range) and ctrl to select individual tabs and was disappointed it didn't work - i absolutely love sidebery and being able to select multiple tabs like this to operate on is the only thing missing for me

**Comment by mbnuqw** [comment]
Implemented in the latest version.
