### ISSUE TITLE
When a pinned tab is selected, the hidden tabs aren't changing in firefox

### ISSUE THREAD

**Issue by gu-does-git** [mbnuqw/sidebery#700]
## Description
When clicking in a different panel pinned tab, the hidden tabs aren't showed. It changes the panel in the sidebery sidebar but it don't act like I changed the tab in the sidebar although it changed.

## Expected behavior
Initially in the A Panel so it's showing the A Panel's tabs.
1. Click in the B Panel pinned tab.
2. Changes the showed tabs to the B Panel's tab in the sidebar but also in the native Firefox.

## Actual behavior
Initially in the A Panel so it's showing the A Panel's tabs.
1. Click in the B Panel pinned tab.
2. Changes the showed tabs to the B Panel's tab in the sidebar **but doesn't change in the native Firefox**.

**Comment by microbearsmb** [comment]
This behavior continues for me, on version 5.1.1.1
