### ISSUE TITLE
Scroll tabs with right click (or Alt, CTRL, etc.) + mouse wheel when the mouse cursor is not under tabs or Sidebery panel. 

### ISSUE THREAD

**Issue by ovnis82** [mbnuqw/sidebery#702]
Hi, 

It would be great to navigate betweens tabs with the mouse wheel when the mouse cursor is on a web site page a little bit like this add-on: 
https://chrome.google.com/webstore/detail/tab-wheel-scroll/aknfcgiicpmnfhncpljcadokcghjblal?hl=fr

thx

**Comment by mbnuqw** [comment]
Out of scope of Sidebery, try to use Foxy Gestures (Other Gestures in settings).
