### ISSUE TITLE
All New Tabs Moved to Panel With Regex Matching

### ISSUE THREAD

**Issue by MerfAvenger** [mbnuqw/sidebery#703]
## Steps to reproduce
Create two panels, one without URL matching (Google Panel) and one with matching (Localhost Panel) for localhost.

Regex Tried:
/localhost/
/localhost:[0-9]+/
/^.*localhost:[0-9]+/
/^(http:\\/\\/)?(localhost:)([0-9]+)/

Create "localhost:8080" tab in Google Panel.
Create "google.com" tab in Google Panel.

## Expected behavior

Localhost tab moved to Localhost Panel.
Google tab remains in Google Panel.

## Actual behavior

Localhost tab moved to Localhost Panel.
Google tab moved to Localhost Panel.

## Debug info

Creating Google Panel regex in the above scenario appears to have the magical powers to override whatever is causing the matcher to move the panels in the first place.

Only one panel seems to become the Hoarder of Tabs and it isn't the highest one in the panel ordering settings.

Seems to not be associated to settings or any cached data as this is the same problem I have on my work macbook, on my entirely separate instance on my personal windows machine. My work laptop gets around this by having regex for essentially everything I use daily. 

### Addon data
<details><code>
{
  "settings": {
    "version": "4.10.1",
    "nativeScrollbars": false,
    "selWinScreenshots": true,
    "tabsCheck": true,
    "tabsFix": "notify",
    "markWindow": false,
    "markWindowPreface": "[Sidebery] ",
    "ctxMenuNative": false,
    "autoHideCtxMenu": "none",
    "ctxMenuRenderInact": true,
    "ctxMenuIgnoreContainers": "",
    "navBarLayout": "vertical",
    "navBarInline": false,
    "hideAddBtn": true,
    "hideSettingsBtn": false,
    "navBtnCount": false,
    "hideEmptyPanels": true,
    "navActTabsPanelLeftClickAction": "none",
    "navActBookmarksPanelLeftClickAction": "none",
    "navMidClickAction": "none",
    "navSwitchPanelsWheel": true,
    "groupLayout": "grid",
    "skipEmptyPanels": true,
    "dndTabAct": true,
    "dndTabActDelay": 750,
    "dndTabActMod": "none",
    "dndExp": "pointer",
    "dndExpDelay": 0,
    "dndExpMod": "none",
    "stateStorage": "session",
    "warnOnMultiTabClose": "collapsed",
    "activateOnMouseUp": true,
    "activateLastTabOnPanelSwitching": true,
    "showTabRmBtn": true,
    "showTabCtx": true,
    "hideInact": false,
    "activateAfterClosing": "next",
    "activateAfterClosingPrevRule": "visible",
    "activateAfterClosingNextRule": "tree",
    "activateAfterClosingGlobal": false,
    "activateAfterClosingNoFolded": true,
    "activateAfterClosingNoDiscarded": true,
    "shiftSelAct": true,
    "askNewBookmarkPlace": false,
    "tabsRmUndoNote": true,
    "nativeHighlight": false,
    "tabsUnreadMark": false,
    "tabsReloadLimit": 5,
    "tabsReloadLimitNotif": true,
    "tabsPanelSwitchActMove": true,
    "moveNewTabPin": "start",
    "moveNewTabParent": "last_child",
    "moveNewTabParentActPanel": false,
    "moveNewTab": "end",
    "pinnedTabsPosition": "panel",
    "pinnedTabsList": false,
    "pinnedAutoGroup": false,
    "tabsTree": true,
    "groupOnOpen": true,
    "tabsTreeLimit": "none",
    "hideFoldedTabs": false,
    "autoFoldTabs": false,
    "autoFoldTabsExcept": "none",
    "autoExpandTabs": false,
    "rmChildTabs": "none",
    "tabsChildCount": true,
    "tabsLvlDots": false,
    "discardFolded": false,
    "discardFoldedDelay": 0,
    "discardFoldedDelayUnit": "sec",
    "tabsTreeBookmarks": true,
    "treeRmOutdent": "branch",
    "bookmarksPanel": true,
    "warnOnMultiBookmarkDelete": "collapsed",
    "openBookmarkNewTab": false,
    "midClickBookmark": "open_new_tab",
    "actMidClickTab": false,
    "autoCloseBookmarks": false,
    "autoRemoveOther": false,
    "highlightOpenBookmarks": false,
    "activateOpenBookmarkTab": false,
    "showBookmarkLen": false,
    "bookmarksRmUndoNote": true,
    "fontSize": "m",
    "bgNoise": true,
    "animations": true,
    "animationSpeed": "fast",
    "theme": "default",
    "style": "auto",
    "sidebarCSS": false,
    "groupCSS": false,
    "snapNotify": true,
    "snapExcludePrivate": false,
    "snapInterval": 10,
    "snapIntervalUnit": "min",
    "snapLimit": 1024,
    "snapLimitUnit": "kb",
    "hScrollThroughPanels": true,
    "scrollThroughTabs": "panel",
    "scrollThroughVisibleTabs": false,
    "scrollThroughTabsSkipDiscarded": false,
    "scrollThroughTabsExceptOverflow": true,
    "scrollThroughTabsCyclic": false,
    "tabDoubleClick": "none",
    "tabLongLeftClick": "none",
    "tabLongRightClick": "none",
    "tabsPanelLeftClickAction": "none",
    "tabsPanelDoubleClickAction": "tab",
    "tabsPanelRightClickAction": "menu",
    "tabsPanelMiddleClickAction": "tab",
    "syncName": "",
    "syncSaveSettings": false,
    "syncSaveCtxMenu": false,
    "syncSaveStyles": false,
    "syncAutoApply": false
  },
  "permissions": {
    "allUrls": true,
    "tabHide": true,
    "actualAllUrls": true,
    "actualTabHide": true
  },
  "storage": {
    "size": "74.1 kb",
    "props": {
      "containers_v4": "268 b",
      "favAutoCleanTime": "10 b",
      "favUrls": "1.3 kb",
      "favicons": "62.5 kb",
      "lastSnapTime": "13 b",
      "panelIndex": "1 b",
      "panels_v4": "1.1 kb",
      "prevTabsData_v4": "201 b",
      "profileID": "14 b",
      "settings": "2.8 kb",
      "snapshots_v4": "4.8 kb",
      "tabsData_v4": "741 b"
    }
  },
  "panels": [
    {
      "type": "bookmarks",
      "id": "bookmarks",
      "cookieStoreId": "bookmarks",
      "name": 9,
      "icon": "...",
      "bookmarks": true,
      "lockedPanel": false,
      "skipOnSwitching": true
    },
    {
      "type": "default",
      "id": "firefox-default",
      "name": 7,
      "icon": "...",
      "cookieStoreId": "firefox-default",
      "lockedTabs": false,
      "lockedPanel": false,
      "skipOnSwitching": false,
      "noEmpty": false,
      "newTabCtx": "none",
      "dropTabCtx": "none",
      "moveTabCtx": "none",
      "moveTabCtxNoChild": true
    },
    {
      "type": "tabs",
      "id": "Uk_mQjAWCoaY",
      "name": 20,
      "icon": "...",
      "color": "...",
      "customIconSrc": "",
      "customIcon": "",
      "lockedTabs": false,
      "lockedPanel": false,
      "skipOnSwitching": false,
      "noEmpty": false,
      "newTabCtx": "none",
      "dropTabCtx": "none",
      "moveTabCtx": "none",
      "moveTabCtxNoChild": true,
      "urlRulesActive": true,
      "urlRules": 20
    },
    {
      "type": "tabs",
      "id": "YbSY_YQmlr_X",
      "name": 7,
      "icon": "...",
      "color": "...",
      "customIconSrc": "",
      "customIcon": "",
      "lockedTabs": false,
      "lockedPanel": false,
      "skipOnSwitching": false,
      "noEmpty": false,
      "newTabCtx": "none",
      "dropTabCtx": "none",
      "moveTabCtx": "none",
      "moveTabCtxNoChild": true,
      "urlRulesActive": true,
      "urlRules": 33
    }
  ],
  "containers": [
    {
      "id": "firefox-container-6",
      "name": 7,
      "icon": "...",
      "color": "...",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    }
  ],
  "cssVars": "TypeError: can't convert undefined to object",
  "windows": [
    {
      "state": "maximized",
      "incognito": false,
      "tabsCount": 7
    }
  ],
  "bookmarks": {
    "bookmarksCount": 5,
    "foldersCount": 5,
    "separatorsCount": 0,
    "maxDepth": 2
  }
}
</code></details>

### Logs
** I've tried to do this but get the following:**
ERROR

Cannot connect to the debug target. See details below:
Error: descriptorFromUrl, unsupported type 'extension)' parameter

Assuming you meant to just open the console and attempt to reproduce this, I've done so in a fresh google tab and there's no errors/warnings/logs from anything except google's site.
<details><code>

</code></details>

Minor Edit: Checking the issue again, updated the test regex as markdown read /^(http:\\/\\/)?(localhost:)([0-9]+)/ as /^(http:\/\/)?(localhost:)([0-9]+)/ with only one prior \\.

**Comment by kellyclowers** [comment]
I wonder if this is related to what happened to mine... though it didn't move immediately, I had many tabs in certain panels, but when the sidebery sidebar got closed, when it reopened, all tabs not in my main/first panel were moved to my second panel... which has a regex...

**Comment by MerfAvenger** [comment]
That's very possible - I loaded Firefox yesterday and this behaviour was no longer happening, it seems fairly sporadic. I would say that what @kellyclowers is describing definitely could happen with the behaviour I've seen from this issue.

**Comment by kellyclowers** [comment]
https://github.com/mbnuqw/sidebery/discussions/705 

For me it happened when I closed the sidebar - I hit cmd-b instead cmd-v, which switches to the bookmarks sidebar, then I hit it again, which doesn't undo the switch, but closes the sidebar. I hit cmd-b again to open the bookmarks sidebar, then used the dropdown to switch back to Sidebery, and it was all messed up.

I haven't done anything with snapshots, and I usually leave my browser open a week or longer, so I haven't seen if it did it on browser restart

**Comment by kellyclowers** [comment]
So I just restarted Firefox and it restored perfectly, no issues

**Comment by mbnuqw** [comment]
I can reproduce this issue. As a workaround you can reload sidebar after changing the URL rules (to apply these rules correctly). Without reloading, new tabs moved to the wrong panel will have wrong panelId and on the next init of sidebar it will result in wrong panels/tabs structure. I'll try to bring the fix for this issue to v4.10.2

**Comment by mbnuqw** [comment]
Should be fixed in v4.10.2, if you can still reproduce it, please, reopen.
