### ISSUE TITLE
Colored tabs lose their color when using containers (Sidebery 5.0.0b25)

### ISSUE THREAD

**Issue by shazzap** [mbnuqw/sidebery#704]
## Steps to reproduce

Have the Google Container installed.
Turn on colored tabs in Sidebery based on domain.
Browse to a reddit page that has youtube links.
Click on the youtube link.
Youtube page is launched in new google container tab.
Close the tab that has youtube.
All the Sidebery tabs then re-display without color.

## Expected behavior

Expect the tabs to retain their color

## Actual behavior

Tabs are re-displayed without domain-base color, even though verifying Sidebery settings indicate that domain-based color is still set.

Have to toggle the color setting off and back on to regain color.

### Addon data
<details><code>

</code></details>

### Logs
<details><code>

</code></details>

**Comment by mbnuqw** [comment]
This was fixed in 4324bd67ca74499aabf0f81cf8995db645321167 (will be in the next beta)

**Comment by mbnuqw** [comment]
Fixed in v5.0.0b30
