### ISSUE TITLE
A couple of questions...

### ISSUE THREAD

**Issue by chaoscreater** [mbnuqw/sidebery#708]
Hi there,

I recently came across this extension and I'm having trouble configuring it to my liking. In Edge Chromium, you can create groups for your tabs and they are automatically coloured, which makes it really easy to identify:

![image](https://user-images.githubusercontent.com/18227319/181426342-cfcbcb71-3c3f-4fac-a2ef-53785e201f59.png)

However, here you can see the group "Test" does not stand out very well. If you have multiple groupsl, this makes it hard to find. They look just like a normal tab:

![image](https://user-images.githubusercontent.com/18227319/181426470-100de20e-9eeb-431a-9ab8-6db292a888ca.png)

I looked through the Style editor and I don't see any option to colour the Group.

Secondly, is it possible to count the number of tabs inside the group and add this as a number against the group?

Thirdly, if I create a new tab, I would like it to create next to the current tab. It does that just fine, but for some reason it will always scroll my tab tree all the way to the bottom. Can I change this behaviour?

**Comment by dexeonify** [comment]
> I looked through the Style editor and I don't see any option to colour the Group.

In v5, Sidebery has the option to colorize tabs or branches. Currently, the colors are automatically picked and can't be manually set.

> Secondly, is it possible to count the number of tabs inside the group and add this as a number against the group?

Should be enabled by default, otherwise enable the option "Show count of descendants on the folded tab" in Sidebery settings. It only appears if you fold the group.

> Thirdly, if I create a new tab, I would like it to create next to the current tab. It does that just fine, but for some reason it will always scroll my tab tree all the way to the bottom. Can I change this behaviour?

Can't reproduce in a new profile with "Place new tab (for the other cases)" set to "After active tab".

**Comment by chaoscreater** [comment]
Thanks, managed to resolve the 2nd and 3rd issue.

For the first issue, I don't think the tabs and branches are the same as Groups? If you have a look at my first screenshot, I have a group called "Test" and I have tabs under it. The root is a Group, not a tab.

**Comment by dexeonify** [comment]
A group is also a tab to Firefox and Sidebery because it has its own page. Unlike Edge where it only colors the group, Sidebery will colorize the group _and_ the child tabs.

**Comment by mbnuqw** [comment]
Manual colorization for tab/tabs branch is planned and will be added soon in v5, I also want to experiment with different (optional) group tab styling (in sidebar) to make it more distinguishable.
