### ISSUE TITLE
v5.0.0b25 multi-tab select bug compared to v4.10.1.

### ISSUE THREAD

**Issue by guigirl42** [mbnuqw/sidebery#722]
## Steps to reproduce
1. Install v4.10.1.
2. Select two or more tabs
3. Move mouse pointer from the Sidebery tab/s to anywhere in the active tab's page [do not click, merely move & hover]
4. Observe that all selected tabs remain selected ... = GOOD.
5. Replace v4.10.1 with v5.0.0b25
6. Repeat steps 2 & 3 
7. Observe that now all non-active selected tabs become deselected the instant the pointer crosses the Sidebery to Page interface boundary ... = BAD.

## Expected behavior
v5.0.0b25 multi-tab select behaviour should be identical to v4.10.1, ie, once user has selected multiple tabs, they should remain selected regardless of mouse position, until & unless user LMB-clicks somewhere.

## Actual behavior
1. All non-active selected tabs become deselected the instant the pointer crosses the Sidebery to Page interface boundary.
2. I have verified this unwanted behaviour in Nightly & vanilla FF, in my daily + virgin profiles in each, & with default & modified Sidebery config. Otoh, with the non-beta Sidebery version, the behaviour is good in all my profiles & versions of FF.

### Addon data
<details><code>
{
  "settings": {
    "nativeScrollbars": false,
    "nativeScrollbarsThin": true,
    "nativeScrollbarsLeft": false,
    "selWinScreenshots": false,
    "updateSidebarTitle": true,
    "markWindow": false,
    "markWindowPreface": "[Sidebery] ",
    "logLvl": 3,
    "ctxMenuNative": false,
    "ctxMenuRenderInact": true,
    "ctxMenuRenderIcons": true,
    "ctxMenuIgnoreContainers": "",
    "navBarLayout": "horizontal",
    "navBarInline": true,
    "navBarSide": "left",
    "hideAddBtn": false,
    "hideSettingsBtn": false,
    "navBtnCount": true,
    "hideEmptyPanels": true,
    "navActTabsPanelLeftClickAction": "none",
    "navActBookmarksPanelLeftClickAction": "none",
    "navTabsPanelMidClickAction": "none",
    "navBookmarksPanelMidClickAction": "none",
    "navSwitchPanelsWheel": true,
    "groupLayout": "grid",
    "skipEmptyPanels": false,
    "dndTabAct": true,
    "dndTabActDelay": 750,
    "dndTabActMod": "none",
    "dndExp": "pointer",
    "dndExpDelay": 750,
    "dndExpMod": "none",
    "dndOutside": "win",
    "searchBarMode": "dynamic",
    "warnOnMultiTabClose": "collapsed",
    "activateLastTabOnPanelSwitching": true,
    "showTabRmBtn": true,
    "hideInact": false,
    "activateAfterClosing": "next",
    "activateAfterClosingGlobal": false,
    "activateAfterClosingNoFolded": true,
    "activateAfterClosingNoDiscarded": true,
    "askNewBookmarkPlace": false,
    "tabsRmUndoNote": true,
    "nativeHighlight": false,
    "tabsUnreadMark": false,
    "tabsReloadLimit": 5,
    "tabsReloadLimitNotif": true,
    "showNewTabBtns": true,
    "newTabBarPosition": "after_tabs",
    "tabsPanelSwitchActMove": false,
    "tabsUrlInTooltip": "full",
    "openSubPanelOnMouseHover": false,
    "colorizeTabs": false,
    "colorizeTabsSrc": "domain",
    "moveNewTabPin": "start",
    "moveNewTabParent": "last_child",
    "moveNewTabParentActPanel": false,
    "moveNewTab": "end",
    "pinnedTabsPosition": "panel",
    "pinnedTabsList": false,
    "pinnedAutoGroup": false,
    "tabsTree": true,
    "groupOnOpen": true,
    "tabsTreeLimit": "none",
    "hideFoldedTabs": false,
    "autoFoldTabs": false,
    "autoFoldTabsExcept": "none",
    "autoExpandTabs": false,
    "rmChildTabs": "none",
    "tabsChildCount": true,
    "tabsLvlDots": false,
    "discardFolded": false,
    "discardFoldedDelay": 0,
    "discardFoldedDelayUnit": "sec",
    "tabsTreeBookmarks": true,
    "treeRmOutdent": "branch",
    "colorizeTabsBranches": false,
    "colorizeTabsBranchesSrc": "url",
    "warnOnMultiBookmarkDelete": "collapsed",
    "autoCloseBookmarks": false,
    "autoRemoveOther": false,
    "highlightOpenBookmarks": false,
    "activateOpenBookmarkTab": false,
    "showBookmarkLen": false,
    "bookmarksRmUndoNote": true,
    "loadBookmarksOnDemand": true,
    "pinOpenedBookmarksFolder": true,
    "loadHistoryOnDemand": true,
    "fontSize": "m",
    "animations": true,
    "animationSpeed": "norm",
    "theme": "proton",
    "colorScheme": "ff",
    "sidebarCSS": false,
    "groupCSS": false,
    "snapNotify": true,
    "snapExcludePrivate": false,
    "snapInterval": 0,
    "snapIntervalUnit": "min",
    "snapLimit": 0,
    "snapLimitUnit": "snap",
    "hScrollAction": "none",
    "navSwitchPanelsDelay": 128,
    "scrollThroughTabs": "none",
    "scrollThroughVisibleTabs": false,
    "scrollThroughTabsSkipDiscarded": false,
    "scrollThroughTabsExceptOverflow": true,
    "scrollThroughTabsCyclic": false,
    "scrollThroughTabsScrollArea": 0,
    "autoMenuMultiSel": true,
    "longClickDelay": 500,
    "wheelThreshold": false,
    "wheelThresholdX": 10,
    "wheelThresholdY": 60,
    "tabDoubleClick": "none",
    "tabsSecondClickActPrev": true,
    "shiftSelAct": true,
    "activateOnMouseUp": false,
    "tabLongLeftClick": "none",
    "tabLongRightClick": "none",
    "tabCloseMiddleClick": "close",
    "tabsPanelLeftClickAction": "none",
    "tabsPanelDoubleClickAction": "tab",
    "tabsPanelRightClickAction": "menu",
    "tabsPanelMiddleClickAction": "tab",
    "bookmarksLeftClickAction": "open_in_act",
    "bookmarksLeftClickActivate": false,
    "bookmarksLeftClickPos": "default",
    "bookmarksMidClickAction": "open_in_new",
    "bookmarksMidClickActivate": false,
    "bookmarksMidClickPos": "default",
    "syncName": "",
    "syncSaveSettings": false,
    "syncSaveCtxMenu": false,
    "syncSaveStyles": false,
    "syncSaveKeybindings": false
  },
  "permissions": {
    "allUrls": false,
    "tabHide": false,
    "clipboardWrite": false,
    "webRequest": false,
    "webRequestBlocking": false
  },
  "storage": {
    "size": "10.9 kb",
    "props": {
      "containers": "1.25 kb",
      "favDomains": "150 b",
      "favHashes": "33 b",
      "favicons": "1.55 kb",
      "lastSnapTime": "13 b",
      "panelIndex": "1 b",
      "prevTabsDataCache": "851 b",
      "profileID": "14 b",
      "settings": "3.5 kb",
      "sidebar": "405 b",
      "snapshots": "2.14 kb",
      "tabsDataCache": "856 b",
      "ver": "10 b"
    }
  },
  "sidebar": {
    "panels": {
      "tabs-panel": {
        "type": 2,
        "id": "tabs-panel",
        "name": "len: 4",
        "color": "toolbar",
        "iconSVG": "icon_tabs",
        "iconIMGSrc": "",
        "iconIMG": "",
        "lockedPanel": false,
        "skipOnSwitching": false,
        "noEmpty": false,
        "newTabCtx": "none",
        "dropTabCtx": "none",
        "moveTabCtx": "none",
        "moveTabCtxNoChild": true,
        "urlRulesActive": false,
        "urlRules": "",
        "bookmarksFolderId": -1,
        "newTabBtns": []
      }
    },
    "nav": [
      "tabs-panel",
      "add_tp",
      "sp-0",
      "settings"
    ]
  },
  "containers": [
    {
      "id": "firefox-container-1",
      "cookieStoreId": "firefox-container-1",
      "name": "8",
      "icon": "...",
      "color": "blue",
      "colorCode": "#37adff",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-2",
      "cookieStoreId": "firefox-container-2",
      "name": "4",
      "icon": "...",
      "color": "orange",
      "colorCode": "#37adff",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-3",
      "cookieStoreId": "firefox-container-3",
      "name": "7",
      "icon": "...",
      "color": "green",
      "colorCode": "#37adff",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-4",
      "cookieStoreId": "firefox-container-4",
      "name": "8",
      "icon": "...",
      "color": "pink",
      "colorCode": "#37adff",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    }
  ],
  "windows": [
    {
      "state": "normal",
      "incognito": false,
      "tabsCount": 8
    }
  ],
  "bookmarks": {
    "bookmarksCount": 5,
    "foldersCount": 5,
    "separatorsCount": 0,
    "maxDepth": 2
  }
}
</code></details>

**Comment by mbnuqw** [comment]
Thanks for the report! Will be fixed in next beta.

**Comment by guigirl42** [comment]
> in next beta

Good, thanks. 

I'd been wondering this for a while, so now seems a good time to ask. Before i changed from the Stable to Beta version some months ago [per a separate _Issue_ here], i knew that ordinary FF/Nightly updates of my AddOns would of course include Sidebery [Stable]. With Beta, however, i am unsure. Will it also be automatically updated with my other AOs here when you do release that next Beta, or would i need to keep watching here for the next Beta then _manually_ download & install it?

**Comment by mbnuqw** [comment]
The beta release is also automatically updated (every 24hr or `extensions.update.interval` in about:config Firefox checks for updates to addons), so you don't have to do anything.

**Comment by guigirl42** [comment]
As context for why i created this Issue, & why this misbehaviour is a problem for my workflow, i offer this additional info, fwiw.

Another of my installed Add-Ons is `Tile Tabs WE`. The fact that my selected tabs become deselected the instant my pointer leaves the Sidebery panel, ie, prior to reaching the TT icon in the Add-Ons panel at the RHS of the URL bar, effectively breaks the practicable usage of TT, which relies on the user having selected her desired tabs to tile first. It works fine with the standard version of Sidebery, but not for the current Beta, as earlier described.

**Comment by guigirl42** [comment]
> Tile Tabs WE + Sidebery = awesomeness

Heehee, yeah, pretty good, _eh_?

>right click on the tab in Sidebery also pops open the Tile context sub-menu

Ah, that's _only_ when using _Native_ Context Menu, whereas sadly NO AddOns are included in the dedicated Sidebery context menu. Overall, i can't stop using the latter, rather than the former, coz of its fabbo RMB functionality.

**Comment by guigirl42** [comment]
Hi @mbnuqw 

Regarding `[Fixed: Handling mouseleave and focusout with selected items](https://github.com/mbnuqw/sidebery/commit/e286f12c675f475dc580dda733823db510f75f0d)`...

I know this question is silly, but can you pls give me _any_ idea **when your next Beta might be available** for us? This Issue [ie, per this current thread] so badly mucks up my workflow that sadly i've needed to revert to `TreeStyleTab` from `Sidebery`, so that i can still interact with the page context menu of `Tile Tabs WE`. 

I suppose that one option available to me would be to revert from the current Beta, back to the current Stable, in order to once more seamlessly also use `Tile Tabs WE`. However, that option is unattractive coz then i would lose the valuable feature which was the very reason i first changed from Stable to Beta, viz "[Tab-Flip / Backward-Activation](https://github.com/mbnuqw/sidebery/issues/541#issuecomment-1181347098)".

It would be marvellous if i could soon return instead to `Sidebery`, & still _fully_ use `Tile Tabs WE`. Basically, i need _both_AOs. 🥺

Thanks.

**Comment by mbnuqw** [comment]
beta26 is out now (sorry for the delay).

**Comment by guigirl42** [comment]
Nice work, thank you!
