### ISSUE TITLE
[v5] Move Tab To Start/End Keybinding

### ISSUE THREAD

**Issue by megamorphg** [mbnuqw/sidebery#725]
## Description
I noticed a [bug](https://github.com/mbnuqw/sidebery/issues/711) where if I use an [extension that moves the tab to the last tab or 1st tab](https://addons.mozilla.org/en-US/firefox/addon/move-tab-hotkeys/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search), if the the tab is currently in a tree, it will **flatten the** tree from the current tab all the way to the tab's new location.
This is disastrous when I have 400 tabs with complex tree structure.

However I do need an ability to sometimes move a single tab to the very bottom that is native to Sidebery (since extensions will conflict with the tree structure).
I use this as a way to "queue" the tab for later review. I know I can move the tab to its own panel or another window but this seems the most efficient in terms of clicks.

**Comment by mbnuqw** [comment]
Ok, I'll add these keybindings. Also, I think I can fix that behavior with flattening tree.

**Comment by mbnuqw** [comment]
Resolved in v5.0.0
