### ISSUE TITLE
new tab causes sidebar to be scrolled to the bottom

### ISSUE THREAD

**Issue by elig0n** [mbnuqw/sidebery#727]
## Steps to reproduce
When there are more than a pageful of tabs in the sidebar, opening a new tab (not at the bottom view) will scroll the sidebar to the bottom.

## Expected behavior
Keep the scrolling position intact or only move around functionally, i..e. center the new tab in the middle of the sidebar.

## Actual behavior
Tab goes out of view and so is the entire scroll-page. 
Tree orientation gets lost until one scrolls back.

## Debug info
Version: 4.10.1
Browser: Firefox 102.0.1
OS: Linux
### Logs
Will post if needed

**Comment by mbnuqw** [comment]
Cannot reproduce, everything works as intended: sidebar scrolls after the new active tab which is placed as configured in `Sidebery settings / Position of new tab` (checked in v4.10.1 and 4.10.2 with different settings). Please, provide debug info ('Settings / Help / Show debug info')

**Comment by elig0n** [comment]
Oops. It looks like I had the "Position of new tab (other cases)" set to "panel end" while another extension "Open Tabs Next to Current" was enabled, so it created a mess. Now I disabled the extension and changed the setting to "first child of active tab" which fixed it.
