### ISSUE TITLE
Missing fence icon in Sidebery UI

### ISSUE THREAD

**Issue by eneerge** [mbnuqw/sidebery#73]
There is a "fence" icon that does not display within the Sidebery sidebar.  If you select it within the Firefox container UI settings, it simply does not show in the Sidebery UI. Sidebery UI does not even display it as an option when editing or creating a new container.

[https://i.imgur.com/N1p5Iu9.png](https://i.imgur.com/N1p5Iu9.png)

**Comment by mbnuqw** [comment]
Thanks for reporting!

**Comment by mbnuqw** [comment]
Fixed in the latest version.
