### ISSUE TITLE
Drag and drop tab as the last child of a group

### ISSUE THREAD

**Issue by GreatestFool** [mbnuqw/sidebery#739]
I haven't found a setting or an issue for this, though I may have missed something.

When you add a tab to a group it is added as the first child of the group, I'd very much prefer if a config setting could be added to change this behavior. I personally much more prefer adding tabs as the last child of a group, similar to how Tree Style Tabs does it, because that makes more sense for me.

If there already is a setting for this, please do point me in its direction. If this doesn't exist, I'll edit the issue to make it fit a feature request template more accurately, but for now it is only an inquiry.

**Comment by mbnuqw** [comment]
No, there is no option for this, but I'll add it.

**Comment by GreatestFool** [comment]
Thank you :)

**Comment by mbnuqw** [comment]
Fixed from v5.0.0
