### ISSUE TITLE
Automatically open "clicked" links in a different container

### ISSUE THREAD

**Issue by eneerge** [mbnuqw/sidebery#74]
Adding the ability to default open clicked links in a different container would be ideal.

Example
A user has a Gmail container to keep Google account information separate from normal browsing. However, upon clicking a link in an email received, that link will open within the Gmail context.

Perhaps this is resolvable by a regex in the "Exclude URLs" configuration of the container.  However, I tried using ".+" and that did not work.  This makes me think that the "includes" are parsed before the "excludes"? Perhaps that could be reversed and the above would not be an issue?

**Comment by mbnuqw** [comment]
You can try to use negative look-ahead in "Include" rule: '/(?!ignoreme|ignoreme2|ignoremeN)/'.

**Comment by eneerge** [comment]
The following worked:

Include:
`amazon.com`

Exclude:
`/^(?!.*amazon).*$/`

Now if I navigate outside of amazon from amazon, it will immediately jump out of the amazon container.  I'm going to set this up for gmail as well.

**Comment by mbnuqw** [comment]
I've fixed include/exclude rules behavior, so in next version you can just write:
```
Include:
/^https?://(\w)*(\.){0,1}amazon.com/

Exclude:
/.+/
```

**Comment by mbnuqw** [comment]
Fixed in the latest version.
