### ISSUE TITLE
Enable hiding of upper tabs on window

### ISSUE THREAD

**Issue by Braxusz** [mbnuqw/sidebery#744]
## Description
I love having this add-on and the vertical tabs, but I would really like to have the ability to also hide the tabs on the top of the browser that are no longer needed.

**Comment by albino1** [comment]
You'll need to use userChrome.css to do it.  See this wiki for more info:

https://github.com/mbnuqw/sidebery/wiki/Firefox-Styles-Snippets-(via-userChrome.css)

**Comment by mbnuqw** [comment]
Not possible due API limitation
https://bugzilla.mozilla.org/show_bug.cgi?id=1332447

Also you can try [this CSS to hide tabs toolbar](https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/hide_tabs_toolbar.css) and [this to preserve windows controls](https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/window_control_placeholder_support.css).
