### ISSUE TITLE
Close several tabs keyboard shortcut

### ISSUE THREAD

**Issue by elig0n** [mbnuqw/sidebery#746]
When selecting several tabs (i.e. holding Shift while selecting a tab far from the current one; or selecting tabs via the bindings of "Select range up/down") a simple Ctrl+w would only close the current tab. 
It would ofcourse be better if Firefox's default binding of Ctrl+w could be used to close all the selected tabs, otherwise a binding that closes the current tab as well as multiple selected tabs seems needed.

**Comment by dexeonify** [comment]
Enable **Highlight native tabs (in top horizontal bar) along with tabs in sidebar** in Sidebery Settings > Tabs.
This question has been asked multiple times that I don't understand why it's not the default.

**Comment by elig0n** [comment]
@dexeonify thanks, I found that setting in Sidebery Settings -> Tabs, though and not at the top horizontal bar of the sidebar.
