### ISSUE TITLE
Close tab selection with Ctrl + W

### ISSUE THREAD

**Issue by GreatestFool** [mbnuqw/sidebery#748]
## Description
If you select a range of tabs and right click the selection and select `close`, it closes all tabs that are selected.

However, if you select a range of tabs and try to close them with `Ctrl + W` it only closes one of the tabs, not all of them like expected behavior. I could not find a setting for this, nor an active issue regarding it. If there is one, please close this one and point me in the right direction, if there isn't one, please consider adding this feature :) It shouldn't be _too_ hard, I think, considering the logic for closing all selected tabs are there, just not bound to a specific keybind.

**Comment by albino1** [comment]
I don't know about in v4, but FWIW I just tested in v5 and I can select a bunch of tabs in the sidebar and ctrl+w to close all of them at the same time. Also, if I then ctrl+shift+t all of them get restored.

**Comment by GreatestFool** [comment]
In that case, since v5 is currently only in the pre-release stage and I assume it isn't exactly stable yet, I'll just wait for it to reach stable in the meantime. Thanks for the heads up :)

**Comment by andrevmatos** [comment]
I'm using v5.0.0rc5, and this is still an issue with Ctrl+W or Middle click; only clicked tab closes, even though the close selection on middle click is set in Settings. Right click + Close menu is the only way to close the whole selection.
Should this be reopened?

**Comment by albino1** [comment]
I'm on v5.0.0rc5 and it still works for me.  Maybe there's some option that needs to be checked or changed that I don't remember changing.

**Comment by GreatestFool** [comment]
This should be reopened, yes. It never got fixed, as far as I'm aware. I've looked through all the settings when v5 initially became available on the test setup I was using back in the day—and am still using on another machine—but with no luck in finding it. Granted, perhaps I am blind, but this should be default behavior and not a opt-out by default anyway if the functionality is in place somewhere in the code base.

**Comment by ww7** [comment]
I'm new user and Ctrl/CMD+W closing only active Tab, I think we need a feature request for such option.
On the Keybindings we have separate "Close selected or active tab / Delete selected bookmarks" were impossible to set Ctrl/CMD+W

**Comment by unit-of-inductance** [comment]
> I'm new user and Ctrl/CMD+W closing only active Tab, I think we need a feature request for such option. On the Keybindings we have separate "Close selected or active tab / Delete selected bookmarks" were impossible to set Ctrl/CMD+W

My workaround right now is to just set "Close selected or active tab / Delete selected bookmarks" to `CTRL/CMD+ALT+W`.

**Comment by Titas22** [comment]
Interestingly, closign tabs works with ```CTRL+F4``` which seems to be doing the same this (might be in different scope?) as ```CTRL+W```

**Comment by andrevmatos** [comment]
It seems that if you "select" multiple tabs with middle button (i.e. click-and-hold on first tab, then drag to the last tab, and release), it also closes all selected tabs. This must be contiguous though

**Comment by albino1** [comment]
> I'm on v5.0.0rc5 and it still works for me. Maybe there's some option that needs to be checked or changed that I don't remember changing.

To update this on a comment from another issue, you may need to have `Highlight Native Tabs` turned on in settings for this to work.
