### ISSUE TITLE
[v5] Turning off "Switch panel after moving active tab" turns off "Hide native tabs of inactive panels", too

### ISSUE THREAD

**Issue by Qjo1** [mbnuqw/sidebery#749]
A: `Hide native tabs of inactive panels` cannot be turned on while 
B: `Switch panel after moving active tab to another panel` is turned off. 

- When turning on A, B will automatically switch on, too. 
- When turning off B, A will also be turned off. 
- However, B can be on, while A is off.

Is there a reason for this? Ideally, I'd like to have both; A on and B off.

**Comment by mbnuqw** [comment]
This is intentional behavior because Firefox cannot hide an active tab when you move it to the inactive panel.
