### ISSUE TITLE
Include/Exclude Rules are parsed multiple times

### ISSUE THREAD

**Issue by eneerge** [mbnuqw/sidebery#75]
The include/exclude rules for each container are parsed everytime a tab is loaded. If you have conflicting substrings/regex, this could lead to tabs that continuously keep changing in an infinite loop.

EG:
Container 1: Include "gmail.com"
Container 2: Include "."
Go to gmail.com and watch the never ending tab war

**Comment by mbnuqw** [comment]
Thanks for the report.
Yes, unfortunately now the only way to stop this pin-pong is only reload sidebar and fix conflicting rules.
hm... I think I can detect this behavior and disable conflicting rules with maybe some notification about it.

**Comment by mbnuqw** [comment]
Fixed in the latest version.
