### ISSUE TITLE
Ability to hide tabs or groups of tabs from the top tab bar

### ISSUE THREAD

**Issue by jimmyhiggs337** [mbnuqw/sidebery#751]
## Description
I'd like the ability to hide a tab or group of tabs from the top tab bar, I was thinking it would work like this when you right click a tab or tab group:
- unload (existing option)
- unload and hide tabs
- hide tabs

Edit: I meant to clarify that this would be for hiding tabs from the top bar

**Comment by emvaized** [comment]
And how to bring hidden tabs back afterwards?

**Comment by jimmyhiggs337** [comment]
Just as there is a 'reload' to the 'unload' there could be an 'un-hide' to the 'hide', this would be only hiding the tabs from the top bar.

Additionally there could be an option in the settings to toggle that would allow a tab to be unhidden on click, 

As it stands when a panel is selected, any tabs that have been hidden on from the top bar that are in that panel are immediately unhidden

**Comment by emvaized** [comment]
If the tab will be hidden from the top bar, it also will be hidden from the Sidebery as well — which brings the question, how to get it back afterwards. Therefore, what you're requesting will also require to implement an option to always show hidden tabs on panel, which will probably require to rewrite a lot of underlying logic, and I think will break few things including the container functionality. 

Given that, and quite rarity of cases when user may actually need such a function, it looks quite unlikely for this to be implemented.

**Comment by albino1** [comment]
Maybe turn on `Hide native tabs of inactive panels` in the settings and then you can just "hide" tabs you don't care about by dumping them into an inactive panel.

**Comment by jimmyhiggs337** [comment]
@emvaized as of right now, if a tab is hidden, it is still visible in sidebery, but if you navigate way and then back to the panel the tab is in, it will automatically unhide the tab

**Comment by jimmyhiggs337** [comment]
> If the tab will be hidden from the top bar, it also will be hidden from the Sidebery as well — which brings the question, how to get it back afterwards. Therefore, what you're requesting will also require to implement an option to always show hidden tabs on panel, which will probably require to rewrite a lot of underlying logic, and I think will break few things including the container functionality.
> 
> Given that, and quite rarity of cases when user may actually need such a function, it looks quite unlikely for this to be implemented.

@emvaized as of right now, if a tab is hidden, it is still visible in sidebery, but if you navigate away and then back to the panel the tab is in, it will automatically unhide the tab

**Comment by jimmyhiggs337** [comment]
> Maybe turn on `Hide native tabs of inactive panels` in the settings and then you can just "hide" tabs you don't care about by dumping them into an inactive panel.

wow, I completely missed this, this is ALMOST what I'm looking for, thank you so much! I would also like to hide tabs in a tab group even if the panel is selected, but I can definitely make do with this at least for now

**Comment by jimmyhiggs337** [comment]
update: there is a "hide folded tabs option" the feature I want exists!
