### ISSUE TITLE
detailed view of groups with tabs on the page, and not in the sidebar

### ISSUE THREAD

**Issue by dobriy2003** [mbnuqw/sidebery#756]
## Steps to reproduce

Please tell me how to make a detailed view of groups with tabs on the page, and not in the sidebar. To make it look like in the picture https://prnt.sc/wsal8gPf7fNf
My email address dobriy2003@gmail.com
### Addon data
<details><code>

</code></details>

### Logs
<details><code>

</code></details>

**Comment by dexeonify** [comment]
...click on the group tab?
