### ISSUE TITLE
Slowness

### ISSUE THREAD

**Issue by ongots** [mbnuqw/sidebery#76]
Тормозит открытие и закрытие вкладок, изменение настроек. Медленная загрузка при запуске.

> OS: win x86-64  
> Firefox: 70.0  
> Extension: 3.0.0

**Comment by mbnuqw** [comment]
Если перезагрузить аддон, тормоза сохраняются?

**Comment by ongots** [comment]
Да. Сейчас попробовал переустановить, без изменений. 
Расширение и раньше работало не быстро, но сейчас вообще все плохо.

**Comment by mbnuqw** [comment]
Хм.. печально. Можете зайти в раздел для отладки (в Настойках), скопировать данные под заголовком JSON и выложить сюда? (Там нет никакой приватной информации - все урлы и названия вырезаны)

**Comment by mbnuqw** [comment]
Еще - напишите, пожалуйста, занимаемое место в Storage (тоже в разделе отладки).
Спасибо.

**Comment by ongots** [comment]
https://drive.google.com/open?id=1wWAxGNv_xS4C17M8otTYyCA1awPtsvGS

General info
Windows: 1
Containers: 1
Tabs: 1169
Pinned Tabs: 0
Bookmarks: 1208
Folders: 47
Separators: 23
Max Depth: 4

snapshots~378.3 kb
favicons~8.5 kb
cssVars~1.6 kb
settings~1.4 kb
panels~757 b
tabsMenu~176 b
bookmarksMenu~113 b
favUrls~50 b
lastSnapTime~13 b
favAutoCleanTime~10 b
tabsTrees~2 b
panelIndex~1 b

**Comment by mbnuqw** [comment]
Спасибо, буду отлаживать...
'Tabs: 1169' впечетляет ;)

**Comment by snowe2010** [comment]
I'm having trouble reading the russian, but I'm seeing slowness as well. 
<img width="604" alt="Screen Shot 2019-09-03 at 1 41 31 PM" src="https://user-images.githubusercontent.com/1534535/64203508-ccc9e600-ce50-11e9-94e7-3bdb3c116eac.png">

https://gist.github.com/snowe2010/6c75f5cf570ea49053a31c8a1ef61976

that took me a long time to find a way to upload it as well

**Comment by mbnuqw** [comment]
@snowe2010, thanks and sorry about this bug
I will try to fix it asap

**Comment by snowe2010** [comment]
no worries, I noticed it started happening immediately after sidebery reloaded. I'm guessing the plugin updated?

**Comment by mbnuqw** [comment]
Yes, I've completely rewritten the mechanism of handling tabs, so there is a lot of space for possible bugs... (

**Comment by snowe2010** [comment]
Ok, it gets much faster if I go below 1140 tabs. Still slow, but like 4 or 5 times as fast.

**Comment by mbnuqw** [comment]
I've upload version 3.0.3, which has a faster method of tabs rendering. If you still have some performance issues feel free to reopen this.
