### ISSUE TITLE
Problem opening "about:performance" bookmark

### ISSUE THREAD

**Issue by tsaost** [mbnuqw/sidebery#760]
## Steps to reproduce
1. Bookmark "about:performance"
2. From Sidebery bookmark panel, click on the bookmark
## Expected behavior
Opens "about:performance"

## Actual behavior
Opens "moz-extension://e8449aaa-33c6-4b3d-a9ba-29230975aee6/url/url.html#about:performance"

### Addon data
<details><code>

</code></details>

### Logs
<details><code>

</code></details>

**Comment by guigirl42** [comment]
I confirm [in Nightly].
- Sidebery v4.10.2 --> `moz-extension://97b90f29-7493-48f2-9888-63cc16c2095e/url/url.html#about:performance`
- Sidebery v5.0.0b26 --> `moz-extension://ab46a72f-d8d7-4e31-9417-40906bb206bf/page.url/url.html#%5B%22about%3Aperformance%22%2C%22about%3Aperformance%20%7C%20Task%20Manager%22%5D`

😮

**Comment by mbnuqw** [comment]
This is an API limitation - addons cannot open this URL (more info https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/create#url)
