### ISSUE TITLE
[v5] Add option for Pinned Tabs to be truly global so panels don't switch when selecting them

### ISSUE THREAD

**Issue by albino1** [mbnuqw/sidebery#761]
## Description

Currently in v5 if you have pinned tabs they have to be panel-specific even if you make them visible globally by setting `Pinned tabs position` to `globally - top`.   The consequence of this is that if you enable `Hide native tabs of inactive panels` then every time you click on any of your pinned tabs all of your currently visible tabs are replaced with whatever panel the pinned tabs are actually connected to.

Basically my feature request is to add an option so that when activating a pinned tab it doesn't switch panels.  Or, if they're intentionally pinned globally to the top of every panel that it also acts as if they're part of every panel and not just part of a random panel that might not be the one you're currently using, allowing you to click them without switching panels and losing your visible tabs.

I've made a demonstration video explaining what I'm talking about.  In it you can see that every time I click and activate a pinned tab, the native horizontal active tabs change.  This behavior is the same regardless of if I set `Pinned tabs position` to `in panel - top` or `globally - top`.

<details>

  <summary>Video - Activating Pinned Tabs Causes Panel to Switch and Visible Tabs to be Replaced</summary>

![AL-Sidebery-GlobalPinnedTabs](https://user-images.githubusercontent.com/12164957/190950906-3eb227a0-f310-45e7-a65b-50f7572536c2.gif)

</details>

Thanks!

**Comment by mbnuqw** [comment]
> Currently in v5 if you have pinned tabs they have to be panel-specific even if you make them visible globally by setting Pinned tabs position to globally - top

It's a bug, thanks for the report!

**Comment by albino1** [comment]
Thanks so much!

**Comment by mbnuqw** [comment]
Resolved in v5.0.0b27
