### ISSUE TITLE
[v5] Treat normal New Tab with an active Pinned Tab the same as "New Tab Opened from Pinned Tab"

### ISSUE THREAD

**Issue by albino1** [mbnuqw/sidebery#762]
## Description

In v5 there's a setting called `Place new tab opened from pinned tab` which specifies the location where new tabs are placed when opening a tab *from a link* on the pinned tab.  However, if you simply *create* a normal blank new tab with the pinned tab active then the new tab location is different.

So, for example, if you have `Place new tab opened from pinned tab` set to `panel end` and you open a link from a pinned tab it goes to end.  However, if you just create a new tab (ctrl+t) it instead goes to the beginning because it's "after" the pinned tab.  I understand why this happens, I just don't think it's necessarily ideal and seems contradictory to the intentionally chosen `Place new tab opened from pinned tab` behavior.

My feature request is to either simply treat both events as the same, as I'm not sure why you would want different behaviors for very similar actions, or to create a secondary option allowing you to choose the new tab behavior when a pinned tab is active.

Using a blank version of Firefox Portable these are my test settings where I've set `Place new tab opened from pinned tab` to `panel end`:

<details>

  <summary>Image - Position of New Tab Settings</summary>

![AL-Sidebery-NewTabSettings](https://user-images.githubusercontent.com/12164957/190951873-6af38e60-b0e2-4e5c-8e80-44d094de1e9f.jpg)

</details>

And now here's a video demonstration I've made where you can see the different behavior depending on if you open a tab *from* a pinned tab or *create* a new tab:

<details>

  <summary>Video - Pinned Tab Open From vs Create Tab Behavior</summary>

![AL-Sidebery-NewTabWhilePinnedActive](https://user-images.githubusercontent.com/12164957/190952830-ae8abde0-675d-469a-9b21-4a34049d8df5.gif)

</details>

Thanks!

**Comment by albino1** [comment]
Thank you!

**Comment by mbnuqw** [comment]
Resolved in v5.0.0b27
