### ISSUE TITLE
[Help] How to hide the normal firefox tab bar

### ISSUE THREAD

**Issue by needlesslygrim** [mbnuqw/sidebery#763]
I want to use Sidebery, but I don't want to have the normal tab bar still enabled. Is there a way to hide it while Sidebery is open? Thanks in advance.

**Comment by albino1** [comment]
You'll need to do it with userChrome.  Take a look at this code snippet in the Wiki:

https://github.com/mbnuqw/sidebery/wiki/Firefox-Styles-Snippets-(via-userChrome.css)#completely-hide-tabs-strip

**Comment by needlesslygrim** [comment]
This doesn't work for me, it leaves a very small thin tab bar.

**Comment by albino1** [comment]
Maybe try adding `!important`:

```
#TabsToolbar {
  display: none !important;
}
```

**Comment by needlesslygrim** [comment]
Ah, yes that works. Forgot to say that I was mostly interested in the dynamic switching, although this would be ok if I could move the window controls down so that they are still visible? If not that's fine. Thanks.

**Comment by mbnuqw** [comment]
You can manually adjust height of `TabsToolbar` to set right toolbar size in visible mode or you can just remove height (but this will turn off animation of switching between visible and hidden state).

Also you can try [this CSS to hide tabs toolbar](https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/hide_tabs_toolbar.css) and [this to preserve windows controls](https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/window_control_placeholder_support.css).

**Comment by needlesslygrim** [comment]
Thanks for the help!

**Comment by davidleejy** [comment]
Is hiding the original Firefox tab bar an option that can be made into toggle-able setting in Sidebery?

**Comment by mbnuqw** [comment]
@davidleejy, No, not possible, here is more info: https://bugzilla.mozilla.org/show_bug.cgi?id=1332447

**Comment by davidleejy** [comment]
> @davidleejy, No, not possible, here is more info: https://bugzilla.mozilla.org/show_bug.cgi?id=1332447

Oh dear.. it's a 6 year old issue haha

**Comment by MaikoID** [comment]
I tried following the instructions but I am not sure if they work for MAC, does it?

1. I enabled toolkit.legacyUserProfileCustomizations.stylesheets on about:config
2. I created the CSS file: /Users/user/Library/Application Support/Firefox/Profiles/g0nl525n.default-release/userChrome.css

But no matter what I write on userChrome.css it has no effect. I restarted FF v111 a couple of times to be sure.

**Comment by albino1** [comment]
> `/Users/user/Library/Application Support/Firefox/Profiles/g0nl525n.default-release/userChrome.css`

This the wrong folder, it needs to be in the subfolder `chrome`, like this:

`/Users/user/Library/Application Support/Firefox/Profiles/g0nl525n.default-release/chrome/userChrome.css`

If you don't have a `chrome` subfolder already, just create one.
