### ISSUE TITLE
[v5.b26] Tab sub-menu trim and translation broken

### ISSUE THREAD

**Issue by Qjo1** [mbnuqw/sidebery#764]
## Steps to reproduce
Right click on a tab in tab or bookmarks panel.

## Expected behavior
`Move to`, `Reopen in` and `Sort` (bookmarks panel) should be translated into existing localization. Descriptors in those sub menus should be trimmed, omitting the "move to", "reopen in" or "sort" parts.

## Actual behavior
`Move to`, `Reopen in` and `Sort` remain English. The rest of the menu(s) is translated properly.
Trimming does not occur, except for the `Sort` sub-menu. However, here the English "sort" is being trimmed, not the given translated term (`Sortieren` in German), making for a broken sentence.

## Additional Info
Both things were tested and confirmed working when transmitting PR #745, so the bug must have been introduced afterwards. That should narrow it down.

**Comment by mbnuqw** [comment]
This is happened because English locale was used and sidebery saved that values in the context menu config. For new users or users that didn't change context menu settings the sub-menu titles should be ok. To restore German translation you can open context menu editor and reset settings there.

**Comment by Qjo1** [comment]
Yes, that did the trick. Wow, thank you for this fast reply and fix!
