### ISSUE TITLE
[Request] Scroll newly created background tabs into view

### ISSUE THREAD

**Issue by emvaized** [mbnuqw/sidebery#770]
## Description
When user opens link from page in a background tab, it can appear out of view when tabs list is long enough. It causes user to not being able to see if the tab was open correctly or not, and what is the exact location of the new tab — it is required to scroll the view first to see it. 

Would be great if every new background tab gets scrolled into view automatically, the same way as it currently happens with new foreground (active) tabs.

**Comment by emvaized** [comment]
It was already mentioned in https://github.com/mbnuqw/sidebery/issues/281, but since this ticket is quite old and generalized, I find it appropriate to bring it on top in a separate ticket.

**Comment by KAGEYAM4** [comment]
I have been looking for this too, is there any workaround you know of till it officially get implemented, i created a reddit post, if i find any will post here.

**Comment by emvaized** [comment]
@PhoenixCODE2322 
Here I created a quick fork with this feature implemented in the most silly way. You can test it if you like — but you'd need to build it first, and then temporary install from `about:debug` page. 
https://github.com/emvaized/sidebery/tree/scroll_to_new_tab

**Comment by jathek** [comment]
This feature works for new tabs but it doesn't work if you undo close tab.

**Comment by mbnuqw** [comment]
Resolved from v5.0.0
