### ISSUE TITLE
v5 AddOn Data Import does not work [5.0.0b26].

### ISSUE THREAD

**Issue by guigirl42** [mbnuqw/sidebery#771]
## Steps to reproduce

1. Export all data & save the resultant file.
2. Attempt to Import that data/file into another Firefox instance.

## Expected behavior
The alternative FF instance should actually accept all the new data, & change accordingly.

## Actual behavior

- The alternative FF instance's Sidebery Settings tab closes, but NOTHING changes in the Sidebery bar. 
- I exported from FF-Nightly.
- I imported to both FF-Beta & plain FF. Neither succeeded.

### Addon data
<details><code>
{
  "settings": {
    "nativeScrollbars": true,
    "nativeScrollbarsThin": false,
    "nativeScrollbarsLeft": true,
    "selWinScreenshots": true,
    "updateSidebarTitle": true,
    "markWindow": false,
    "markWindowPreface": "[Sidebery] ",
    "ctxMenuNative": false,
    "ctxMenuRenderInact": true,
    "ctxMenuRenderIcons": true,
    "ctxMenuIgnoreContainers": "",
    "navBarLayout": "horizontal",
    "navBarInline": true,
    "navBarSide": "left",
    "hideAddBtn": false,
    "hideSettingsBtn": false,
    "navBtnCount": true,
    "hideEmptyPanels": true,
    "navActTabsPanelLeftClickAction": "none",
    "navActBookmarksPanelLeftClickAction": "none",
    "navTabsPanelMidClickAction": "none",
    "navBookmarksPanelMidClickAction": "none",
    "navSwitchPanelsWheel": true,
    "groupLayout": "list",
    "skipEmptyPanels": false,
    "dndTabAct": false,
    "dndTabActDelay": 750,
    "dndTabActMod": "none",
    "dndExp": "none",
    "dndExpDelay": 0,
    "dndExpMod": "none",
    "dndOutside": "win",
    "searchBarMode": "dynamic",
    "warnOnMultiTabClose": "collapsed",
    "activateLastTabOnPanelSwitching": false,
    "showTabRmBtn": true,
    "hideInact": false,
    "activateAfterClosing": "next",
    "activateAfterClosingGlobal": false,
    "activateAfterClosingNoFolded": true,
    "activateAfterClosingNoDiscarded": true,
    "askNewBookmarkPlace": true,
    "tabsRmUndoNote": true,
    "nativeHighlight": true,
    "tabsUnreadMark": true,
    "tabsUpdateMark": "all",
    "tabsReloadLimit": 7,
    "tabsReloadLimitNotif": true,
    "showNewTabBtns": true,
    "newTabBarPosition": "after_tabs",
    "tabsPanelSwitchActMove": true,
    "tabsUrlInTooltip": "full",
    "openSubPanelOnMouseHover": false,
    "colorizeTabs": false,
    "colorizeTabsSrc": "domain",
    "moveNewTabPin": "start",
    "moveNewTabParent": "last_child",
    "moveNewTabParentActPanel": true,
    "moveNewTab": "end",
    "pinnedTabsPosition": "panel",
    "pinnedTabsList": false,
    "pinnedAutoGroup": false,
    "tabsTree": true,
    "groupOnOpen": true,
    "tabsTreeLimit": "none",
    "hideFoldedTabs": false,
    "autoFoldTabs": false,
    "autoFoldTabsExcept": 5,
    "autoExpandTabs": false,
    "rmChildTabs": "none",
    "tabsChildCount": true,
    "tabsLvlDots": false,
    "discardFolded": false,
    "discardFoldedDelay": 7,
    "discardFoldedDelayUnit": "sec",
    "tabsTreeBookmarks": true,
    "treeRmOutdent": "first_child",
    "colorizeTabsBranches": false,
    "colorizeTabsBranchesSrc": "url",
    "warnOnMultiBookmarkDelete": "collapsed",
    "autoCloseBookmarks": false,
    "autoRemoveOther": false,
    "highlightOpenBookmarks": true,
    "activateOpenBookmarkTab": true,
    "showBookmarkLen": true,
    "bookmarksRmUndoNote": true,
    "loadBookmarksOnDemand": false,
    "pinOpenedBookmarksFolder": true,
    "loadHistoryOnDemand": false,
    "fontSize": "xxs",
    "animations": true,
    "animationSpeed": "fast",
    "theme": "compact",
    "colorScheme": "ff",
    "sidebarCSS": true,
    "groupCSS": true,
    "snapNotify": true,
    "snapExcludePrivate": true,
    "snapInterval": 7,
    "snapIntervalUnit": "min",
    "snapLimit": 3,
    "snapLimitUnit": "snap",
    "hScrollAction": "switch_panels",
    "navSwitchPanelsDelay": 128,
    "scrollThroughTabs": "panel",
    "scrollThroughVisibleTabs": true,
    "scrollThroughTabsSkipDiscarded": true,
    "scrollThroughTabsExceptOverflow": true,
    "scrollThroughTabsCyclic": true,
    "scrollThroughTabsScrollArea": 0,
    "autoMenuMultiSel": true,
    "multipleMiddleClose": false,
    "longClickDelay": 500,
    "wheelThreshold": false,
    "wheelThresholdX": 10,
    "wheelThresholdY": 60,
    "tabDoubleClick": "none",
    "tabsSecondClickActPrev": true,
    "shiftSelAct": true,
    "activateOnMouseUp": true,
    "tabLongLeftClick": "none",
    "tabLongRightClick": "none",
    "tabCloseMiddleClick": "close",
    "tabsPanelLeftClickAction": "none",
    "tabsPanelDoubleClickAction": "tab",
    "tabsPanelRightClickAction": "menu",
    "tabsPanelMiddleClickAction": "tab",
    "newTabMiddleClickAction": "new_child",
    "bookmarksLeftClickAction": "open_in_act",
    "bookmarksLeftClickActivate": false,
    "bookmarksLeftClickPos": "default",
    "bookmarksMidClickAction": "open_in_new",
    "bookmarksMidClickActivate": false,
    "bookmarksMidClickPos": "default",
    "syncName": "",
    "syncSaveSettings": false,
    "syncSaveCtxMenu": false,
    "syncSaveStyles": false,
    "syncSaveKeybindings": false
  },
  "permissions": {
    "allUrls": true,
    "tabHide": false,
    "clipboardWrite": true,
    "webRequest": false,
    "webRequestBlocking": false
  },
  "storage": {
    "size": "1.3 mb",
    "props": {
      "bookmarksRecentFolders": "76 b",
      "containers": "1.59 kb",
      "contextMenu": "1.45 kb",
      "expandedBookmarkFolders": "235 b",
      "favDomains": "148 kb",
      "favHashes": "15.7 kb",
      "favicons": "1.1 mb",
      "groupCSS": "759 b",
      "lastSnapTime": "13 b",
      "panelIndex": "1 b",
      "prevTabsDataCache": "3.74 kb",
      "profileID": "14 b",
      "settings": "3.57 kb",
      "sidebar": "1.24 kb",
      "sidebarCSS": "3.1 kb",
      "snapshots": "15.2 kb",
      "tabsDataCache": "3.09 kb",
      "ver": "10 b"
    }
  },
  "sidebar": {
    "panels": {
      "firefox-default": {
        "type": 2,
        "id": "firefox-default",
        "name": "len: 23",
        "color": "purple",
        "iconSVG": "icon_tabs",
        "iconIMGSrc": "",
        "iconIMG": "",
        "lockedPanel": false,
        "skipOnSwitching": false,
        "noEmpty": true,
        "newTabCtx": "none",
        "dropTabCtx": "none",
        "moveTabCtx": "none",
        "moveTabCtxNoChild": true,
        "urlRulesActive": false,
        "urlRules": "",
        "bookmarksFolderId": -1,
        "newTabBtns": []
      },
      "nOTtcRKp1dRl": {
        "type": 2,
        "id": "nOTtcRKp1dRl",
        "name": "len: 21",
        "color": "orange",
        "iconSVG": "icon_gamepad",
        "iconIMGSrc": "",
        "iconIMG": "",
        "lockedPanel": false,
        "skipOnSwitching": false,
        "noEmpty": true,
        "newTabCtx": "none",
        "dropTabCtx": "none",
        "moveTabCtx": "none",
        "moveTabCtxNoChild": true,
        "urlRulesActive": false,
        "urlRules": "",
        "bookmarksFolderId": -1,
        "newTabBtns": []
      },
      "bookmarks": {
        "type": 1,
        "id": "bookmarks",
        "name": "len: 9",
        "iconSVG": "icon_bookmarks",
        "iconIMGSrc": "",
        "iconIMG": "",
        "color": "green",
        "lockedPanel": false,
        "tempMode": false,
        "skipOnSwitching": false,
        "rootId": "root________",
        "viewMode": "tree",
        "autoConvert": false
      },
      "history": {
        "type": 4,
        "id": "history",
        "name": "len: 7",
        "color": "toolbar",
        "iconSVG": "icon_clock",
        "tempMode": false,
        "lockedPanel": false,
        "skipOnSwitching": false,
        "viewMode": "history"
      }
    },
    "nav": [
      "firefox-default",
      "nOTtcRKp1dRl",
      "bookmarks",
      "history",
      "sp-0",
      "search",
      "settings"
    ]
  },
  "containers": [
    {
      "id": "firefox-container-3",
      "name": "7",
      "icon": "...",
      "color": "green",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": "",
      "cookieStoreId": "firefox-container-3",
      "colorCode": "#37adff"
    },
    {
      "id": "firefox-container-6",
      "name": "25",
      "icon": "...",
      "color": "yellow",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": "",
      "cookieStoreId": "firefox-container-6",
      "colorCode": "#37adff"
    },
    {
      "id": "firefox-container-8",
      "name": "10",
      "icon": "...",
      "color": "red",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": "",
      "cookieStoreId": "firefox-container-8",
      "colorCode": "#37adff"
    },
    {
      "id": "firefox-container-9",
      "name": "9",
      "icon": "...",
      "color": "orange",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": "",
      "cookieStoreId": "firefox-container-9",
      "colorCode": "#37adff"
    },
    {
      "id": "firefox-container-12",
      "name": "7",
      "icon": "...",
      "color": "turquoise",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": "",
      "cookieStoreId": "firefox-container-12",
      "colorCode": "#37adff"
    }
  ],
  "sidebarCSSLen": "3057",
  "groupCSSLen": "736",
  "windows": [
    {
      "state": "normal",
      "incognito": false,
      "tabsCount": 30
    }
  ],
  "bookmarks": {
    "bookmarksCount": 8885,
    "foldersCount": 1185,
    "separatorsCount": 9,
    "maxDepth": 12
  }
}
</code></details>

**Comment by guigirl42** [comment]
Oh, more info!

I tried once again, but this time i only chose SOME of the categories in Nightly to _Export_ [originally i had used `All`]. This time i only selected `Settings`, `Styles` & `Containers config`. Upon new _Import_ to FF-Beta, it was **successful this time**. Hence, intuitively, one or more of `Snapshots`, `Site Icons cache` or `Keybindings` seems to cause Import to fail.

**Comment by mbnuqw** [comment]
Thanks for the report. Could you share the logs from the _Import_ instance right after the import attempt?

> To get logs: 
> - Open DevTools (open this url in new tab: about:devtools-toolbox?id=%7B3c078156-979c-498b-8990-85f7987dd929%7D&type=extension)
> - Navigate to "console" tab,
> - Click on the trash bin icon (at the top-left) to clear console,
> - Then try to reproduce the issue
> - If messages appear, copy and paste them here.

**Comment by guigirl42** [comment]
I did not have much luck trying to do as you asked. 

- Following your instructions did not reveal anything at all;  no text appeared in that tab's Console window with either the unsuccessful, or the successful, Import attempts.
- Not really knowing what i was doing, i also tried using the generic FF Console whilst repeating the Import attempts. I've pasted the output below, but i've no idea if it's relevant or not.

FF's Console during **_failed_** `Import - All` from FF-Beta:

```
17:24:42.274 TypeError: browser.browserAction.setBadgeBackgrounColor is not a function background.js:320:27
17:25:33.373 browser.ui.customized_widgets - The key length must be limited to 72 characters.
17:25:33.410 Error: sendRemoveListener on closed conduit {3c078156-979c-498b-8990-85f7987dd929}.137438953730 ConduitsChild.jsm:112:13
17:25:33.494 InvalidStateError: JSWindowActorChild.sendAsyncMessage: JSWindowActorChild cannot send at the moment ConduitsChild.jsm:67
17:25:33.496 InvalidStateError: JSWindowActorChild.sendAsyncMessage: JSWindowActorChild cannot send at the moment ConduitsChild.jsm:67
17:25:33.548 Promise resolved after context unloaded
chunk-JCCLQ76A.js:17849
17:25:33.823 [sidebar:1] Tabs loading: Cannot find panels: zD8AdKjED7mm chunk-JCCLQ76A.js:17245:13
```


FF's Console during **_successful_** `Import - 3` [ie, `Settings`, `Styles` & `Containers config`] from FF-Beta:

```
17:39:46.596 TypeError: browser.browserAction.setBadgeBackgrounColor is not a function background.js:320:27
17:40:06.570 browser.ui.customized_widgets - The key length must be limited to 72 characters.
```

🤷‍♀️

**Comment by mbnuqw** [comment]
The absence of logs is also useful information, thanks. Next questions:
- Are all instances (_Export_ and _Import_) v5?
- Does the settings tab close immediately after importing data, or does it close with some delay?
- Could you try to import `Snapshots`, `Site Icons cache` and `Keybindings` one by one to figure out what is the culprit?

**Comment by guigirl42** [comment]
>Are all instances (Export and Import) v5?

Yes, & atm all 5.0.0b27 [vs 26 when i first raised this Issue].

>Does the settings tab close immediately after importing data, or does it close with some delay?

Afaict, ~instantaneously.

>Could you try to import Snapshots, Site Icons cache and Keybindings one by one to figure out what is the culprit?

- For today's series of testing, unlike all previous tests wrt this Issue, both my Exporting FF & my Importing FF were the same fox channel; _FF-Beta_. The Export was from my daily default FF-Beta instance, whilst the Import was in a separate Test FF-Beta profile i created for... _tests_, heehee. My earlier tests, both when i created this Issue, & then also for other tests you asked me to try, involved different foxes; Nightly to Stable, Nightly to Beta, Beta to Nightly,  [& maybe also] Beta to Stable [i can't recollect clearly any more]. I've no idea if this detail is significant, but i record it here for completeness.
- After each of the following tests, i "reset" my Test profile by uninstalling its _Sidebery_, then closing & relaunching said Test profile window,then reinstalling 5.0.0b27 to ensure that each new test began "clean".
- In today's first test, i Exported all categories **_except_** Snapshots. The Import was successful.
- For the second test, i created a new Export, this time being _**only**_ Snapshots. The Import was successful [to my amazement].
- For the third test,  i created a another new Export, this time being _**All**_ [ie, same as when/why i created this Issue].  The Import result bewildered me, & i'll discuss it in next dot-points.
- I could see that at least part of the Import had succeeded, because my default panels changed to my custom names. Furthermore when i reopened Sidebery Settings, i could see that my custom settings were there, + my custom CSS in the Styles Editor, + my snapshots in the Snapshots Viewer. 
- Next i tried opening the latest snapshot in a new window. I Initially, visually, thought that the import must indeed have partially failed, because  the Sidebery bar in said new window was closed, & when i opened it, both its tab panels were hidden [like when they are empty], & the Sidebery tabs bar was also empty.  The panels refused all attempts to make them unhide. Given this window seemed to be useless, i went to close it. However i realised then that in fact despite not being able to see them, many or all of the snapshot's tabs _must_ have restored, as FF warned me that i was about to close 28 tabs. Then i found that i can access some of them via FF's native Ctrl+Tab function. 

I'm going to do some more testing, & will update here later...

**Comment by guigirl42** [comment]
I've done another test now, reusing that 3rd Export file _from FF-Beta_ per my previous post [ie, being `All`], this time Importing it _into a Nightly virgin_ profile [5.0.0b27]. Therein, i opened one of the imported snapshots in a new [Nightly virgin profile] window, and... 

...it seems to be entirely successful 😲

I am beginning to suspect that my decision to create this Issue might have been unfounded, based on some misunderstandings by me.  Specifically, i now retrospectively suspect:

1. i had initially erroneously misinterpreted the _**broken**_ status of _most_ of my pinned tabs each time i had tried Importing then opening said imported snapshots, as denoting an Import process failure.  However, more recently i learned, via another Issue someone else had raised, that apparently Sidebery's Snapshots cannot access any of the internal FF pages [eg, any of the `about:` pages]. When i then checked, afaict 100% of the various snapshots' broken pinned-tabs, are in fact those internal URLs. 
2. i had [stupidly 🤦‍♀️] confused myself in my _original_ tests, incorrectly expecting that my active tab-panel in the _Importing_ fox, would _automatically_ populate with all the tabs from the imported file... ie, i now believe that originally i cognitively mixed up the separate functions of Import vs subsequently Open Snapshot from said import. _D'oh!_ 
3. i now deeply suspect that those recent tests per my _previous_ post, were probably not very useful. Though i overlooked it at the time, i now suspect that my choice of using my TEST Beta profile was inappropriate. That profile is explicitly setup to run in a "session-wipe" mode, being locked-down with various private settings, which now in hindsight might explain its confusing results vs my latest successful test per this current post. 

I'll keep monitoring this over coming days, but now suspect i owe an apology for causing confusion & time-wasting. _Gulp_.

**Comment by mbnuqw** [comment]
Thank you very much for your time spent on these test! This makes me think that I probably should add some notification for successful/failed import, plus of course documentation of the Export/Import process.

Also this
> Next i tried opening the latest snapshot in a new window. I Initially, visually, thought that the import must indeed have partially failed, because the Sidebery bar in said new window was closed, & when i opened it, both its tab panels were hidden [like when they are empty], & the Sidebery tabs bar was also empty. The panels refused all attempts to make them unhide. Given this window seemed to be useless, i went to close it. However i realised then that in fact despite not being able to see them, many or all of the snapshot's tabs must have restored, as FF warned me that i was about to close 28 tabs. Then i found that i can access some of them via FF's native Ctrl+Tab function.

looks like a bug (these empty panels shouldn't be empty after the snapshot is restored), I'll try to test this too.

Thanks again, if you'll not notice any problems with export/import you can to close this issue.

**Comment by guigirl42** [comment]
>looks like a bug ... I'll try to test this too

_Maybe_ it's a bug, but _maybe it's not_. As i said in my previous _mea culpa_ post, i now suspect that most of this Issue is probably simply a series of mistakes & misunderstandings by ME, rather than a problem in Sidebery v5. 

>if you'll not notice any problems with export/import you can to close this issue

Yes, that's probably best. I'll do that now, so that you can _fully focus_ on the _next Beta_ giving us our [hover tab-thumbnails](https://github.com/mbnuqw/sidebery/issues/301). 😁 🤪
