### ISSUE TITLE
Pls incorporate "What's New" release-notes when Beta updates.

### ISSUE THREAD

**Issue by guigirl42** [mbnuqw/sidebery#773]
## Description
I changed from v4 Stable to v5 Beta some months ago [& overall it's been great]. When i first changed, it was 5.0.0b25. Recently it updated to 5.0.0b26, & now it has become 5.0.0b27 in my Firefoxes. Each time i look for info to help me understand what's changed, i can't find anything, not in the FF `about:addons` page, nor [afaict] even here in Github. I'm not a programmer, so trying to interpret specific commits is quite hard for me; some kind of "plain English [etc]" dot-point list of fixes, changes & new features would be preferred.

Thanks for all your work! 
***

Oh! I just noticed this, on the main page:
![image](https://user-images.githubusercontent.com/76090786/192176138-35860703-8023-4c2f-a623-880d019d5878.png)

Well, that's good to know... but given i failed to notice that sub-section before, how can i retrospectively learn what had changed in previous Betas, eg 26?

**Comment by dexeonify** [comment]
Use the [release section](https://github.com/mbnuqw/sidebery/releases), and look for releases labelled with "Pre-release". There's a full changelog showing the commits for each new version. For user-facing issues, the commit message is usually descriptive enough. You don't have to understand all the commits, some of them are simply internal improvements/fixes/changes.

**Comment by guigirl42** [comment]
Many thanks!

Presumably then, this is the place i'll go to discover, sooner or later, when we get our [tabs hover-thumbnails](https://github.com/mbnuqw/sidebery/issues/301) 😁

Ta for your advice. Much of it remains a bit too cryptic for me, but it's certainly far better than what i had before [ie, zilch, haha].

**Comment by albino1** [comment]
I use the release section method, but I do agree that a more human-readable changelog would be nice to have, especially for people that aren't actively following all of the github issues or don't have the technical ability to parse the brief commit messages.

**Comment by mbnuqw** [comment]
Ok, I'll write a summary from the next release.
