### ISSUE TITLE
(Re)Use Firefox Sync/Account name as Sidebery’s Sync Profil name

### ISSUE THREAD

**Issue by silverhook** [mbnuqw/sidebery#774]
It would make things easier if Sidebery would by default use Firefox’ own Sync/Account name as the Sync Name.

You can find that in `about:config` (i.e. `prefs.js` or `user.js`) under `identity.fxaccounts.account.device.name`

**Comment by mbnuqw** [comment]
Not possible via the WebExtension API

**Comment by silverhook** [comment]
@mbnuqw , where does Sidebery store the name then exactly?

**Comment by mbnuqw** [comment]
In [browser.storage.local](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/local) in the "[settings](https://github.com/mbnuqw/sidebery/blob/v5/src/types/storage.ts#L10).[syncName](https://github.com/mbnuqw/sidebery/blob/00ee928be5231548c41c3eb9dd6b27a498a766eb/src/types/settings.ts#L175)" property.

**Comment by silverhook** [comment]
Thanks :)

**Comment by silverhook** [comment]
@mbnuqw , sorry to bug you again, but what exactly does the _Sync_ functionality do in Sidebery? I tried to figure it out from the settings and searched the Wiki, but am still not entirely sure.

Is it to back-up settings to Firefox Sync or to sync the settings between different Firefox Profiles/devices, or what?

**Comment by mbnuqw** [comment]
It back-ups settings, context menu config or/and custom styles to Firefox Sync which allows you to sync these parts between different Firefox Profiles. After you turned on sync in Sidebery settings in profile A and Firefox Sync is synchronized, you can open Sidebery settings in profile B and see/apply synchronized stuff from profile A.

**Comment by silverhook** [comment]
But, if I understand correctly, this means:
1) Sidebery settings don’t automatically sync, but you need to press the button to apply them in a new Profile/device;
2) the Sync name there is more a means to name a back-up/snapshot of the Sidebery settings; and
3) Sidebery’s Sync has nothing to do with open tabs.

…I apologise for the questions, but I’m just trying to understand and am a bit confused still.

**Comment by silverhook** [comment]
OK, I think I got it. But it does not sync automatically, I need to _apply_ the changes, right?

**Comment by mbnuqw** [comment]
Yes, only the manual applying of synced data because there can be multiple sources of data and (at least in my setup) Firefox Sync works unpredictably - that are the reasons I didn't implement auto-applying of the data.

**Comment by silverhook** [comment]
Got it. That makes it a bit unfortunate for my use case, but on the other hand since the defaults I can work with, it also makes one less setting for me to worry about syncing :)
