### ISSUE TITLE
Tab trees: Improved and/or skippable confirm-close dialog?

### ISSUE THREAD

**Issue by deanishe** [mbnuqw/sidebery#776]
First off, amazing extension. I've had it two days, and it's already my primary UI. Marvellous!

## Description

Closing a tree of tabs can a bit cumbersome on account of the "Are you sure you want to close N tabs?" confirmation. I find myself counting the number of tabs to see if it'll be quicker to close them individually instead.

The problem is that because the dialog always appears in the centre of the window, and doesn't respond to keyboard input (with a regular macOS dialog, I can use `SPACE` to confirm and `ESC` to cancel, for example), the "close subtree" feature often requires a lot more mousing than just mashing the middle mouse button on the top row of the subtree.

Would it be possible to make the dialog work like a regular one, or let the user disable the confirmation altogether?

**Comment by albino1** [comment]
I don't remember if there's a similar setting in v4, but in v5 in `Settings -> Tabs` you can just set `Warn on trying to close multiple tabs` to `none` and you won't get a confirmation any more.

**Comment by mbnuqw** [comment]
As @albino1 mentioned, the "Warn on trying to close multiple tabs" will do the trick. It is also available in v4.
