### ISSUE TITLE
Sidebar empty after reopen.

### ISSUE THREAD

**Issue by lkhphuc** [mbnuqw/sidebery#78]
> OS: linux x86-64  
> Firefox: 69.0  
> Extension: 3.0.2  

1. On a clean reinstall, tabs will show up in the sidebar.
2. After close and reopen the sidebar again, all tabs disappear
3. Go to Debug, delete all caches, close and open sidebar again, tabs appear.
4. Close and open sidebar, tabs disappear.

**Comment by mbnuqw** [comment]
Do you use option "After closing current tab activate: previously active tab"?

**Comment by mbnuqw** [comment]
Can you check version 3.0.3?

**Comment by lkhphuc** [comment]
Can confirm the problem is from the option "Last active tab".
Updated to 3.0.3 and everything works fine. Closing now.
Thank again for awesome work.
