### ISSUE TITLE
Clarifying the setting “Delete open bookmarks from ‘Other Bookmarks’ folder”

### ISSUE THREAD

**Issue by GordemProo** [mbnuqw/sidebery#783]
When exactly does this setting apply? Can it wipe some bookmarks if occasionally enabled for a second (that is the case)? How to know if it did? Does it ignore the “Warn on trying to close multiple tabs” setting?

**Comment by mbnuqw** [comment]
This setting will delete bookmark only if:
- You open bookmarks panel in Sidebery sidebar
- Open bookmark in folder "Other Bookmarks" (by clicking on it, through context menu or using keyboard)

_- Can it wipe some bookmarks if occasionally enabled for a second (that is the case)?_
No

_- How to know if it did?_
You will see that the bookmark will be removed from the list after you click on it. I'll also add "undo" notification.

_- Does it ignore the “Warn on trying to close multiple tabs” setting?_
Yes

Another notes:
- I just found that this feature is broken (bookmarks are not deleted) in v5 (will be fixed soon)
- It applies only on top-level bookmarks on "Other Bookmarks" folder
