### ISSUE TITLE
FEATURE REQUEST: Custom icon: local file selection instead of base64

### ISSUE THREAD

**Issue by boldcompany** [mbnuqw/sidebery#785]
## Description
Currently, sidebery supports automatic loading of remote icons of a variety of formats. The user does not have to do anything special other than set appropriate add-on permissions and then include the URL string, such as...
ex: https://news.ycombinator.com/y18.gif

However, local icons do not work the same way. The user must manually enter a prefix...
ex: data:image/png;base64, 
and then provide a base64-encoded icon...
ex: R0lGODlhEgASAKIAAP/jyvihV/aKLfmxc/////9mAAAAAAAAACH5BAAAAAAALAAAAAASABIAAAMpWLrc/jDKOQkRy8pBhuKeRAAKQFBBxwVUYY5twXVxodV3nLd77f9ASQIAOw==
which is probably counterintuitive to most users.

It would be very convenient if the user could simply enter, for example:
C:\Users\User1\Desktop\icon.png
...and sidebery would process and load the png automatically, as it does with the remote file.

**Comment by danielnichols** [comment]
I agree that adding base64 icons is not intuitive, although I feel like accessing file paths as described may run into some permission issues... Perhaps a better way to go about it would be to use an upload file dialog?

**Comment by quazar-omega** [comment]
Looks to be solved in stable too, thank you @mbnuqw!

**Comment by mbnuqw** [comment]
Available from v5.0.0
