### ISSUE TITLE
Adding Folders Or Management On Containers

### ISSUE THREAD

**Issue by zidanpragata** [mbnuqw/sidebery#796]
## Description
![Screenshot_8](https://user-images.githubusercontent.com/43347895/194782483-fd5eea34-bb17-4b2b-9be0-e98950749853.jpg)

if the container reaches hundreds, it is not very user friendly to use, please add features to manage or add folders such as folders in bookmarks, thank you.

**Comment by mbnuqw** [comment]
Duplicate of #354
