### ISSUE TITLE
Pinned tabs not divide into container group

### ISSUE THREAD

**Issue by DavisGuohua-xie** [mbnuqw/sidebery#8]
Thank you for this productivity add on. No sure if is an issue or feature request or some setting we need to do.  we have the Pinned group and each group for each container. But can we see the pinned tabs in each contain group and in the pinned tab group?

**Comment by mbnuqw** [comment]
Thanks. Yes, I can add option to show pinned tabs at the top of corresponding container (in list or icon-grid layout).

**Comment by mbnuqw** [comment]
Reworked pinned tabs in 2.0.0. You can now place pinned tabs separately by containers or globally at top/left/right.
Feel free to reopen this if you have some issues or suggestions with pinned tabs positioning
