### ISSUE TITLE
Open new tabs at top of list

### ISSUE THREAD

**Issue by tranhl** [mbnuqw/sidebery#80]
In containers with lots of tabs open, it's sometimes tedious having to scroll all the way to the bottom of the list to open a new tab. It would be nice to open new tabs at the top of the list so that users never have to scroll.

**Comment by mbnuqw** [comment]
Doesn't panel automatically scroll down to a newly opened tab? (I'll add an option to place new tabs at the top of the panel, but just curious, maybe this is a bug.)

**Comment by mbnuqw** [comment]
Now, in v4.x.x you can configure position of a new tab, so I'm closing this issue.
