### ISSUE TITLE
100 tabs (only 39 loaded) : 4.5 Gb RAM usage (Firefox)

### ISSUE THREAD

**Issue by Elaws** [mbnuqw/sidebery#801]
For 39 tabs loaded in Sidebery (and 61 unloaded), is it normal to have a RAM usage of 4.5 Gb ?

Not sure if the problem comes from Sidebery or Firefox.

**Comment by mbnuqw** [comment]
You can open `about:performance` and check `Memory` value for `Sidebery ({3c078156-979c-498b-8990-85f7987dd929})`

**Comment by Elaws** [comment]
Really weird : Sidebery only uses 7Mo. 

When I open ~20 tabs, RAM usage goes from ~1Gb to ~3Gb but the values of RAM usage for these tabs add-up to only ~500Mb...

**Comment by mbnuqw** [comment]
Ok, looks like the problem isn't on Sidebery side. You can ask for help on [r/firefox](https://www.reddit.com/r/firefox/search?q=memory&restrict_sr=on)

**Comment by dexeonify** [comment]
Use `about:processes` or `about:memory`
