### ISSUE TITLE
Option to open new tab unloaded

### ISSUE THREAD

**Issue by DeliciousPi2745** [mbnuqw/sidebery#806]
It would be fantastic to have an option to open new tabs in an unloaded state. I often find myself troubleshooting/researching and opening several links in quick succession, that then take me a while to get through, consuming memory even though I haven't started reading them yet. Combined with ADHD and lots of research for various projects, I often find myself with a huge amount of opened tabs even before I've gotten around to looking at them.

As a workaround, I currently have the timeout setting for tab unloading set to a fairly aggressive 5 minutes, which helps to keep the memory usage down but isn't ideal, as many tabs I keep going back to end up unloading themselves and having to reload every time. I've also tried using the bookmark system, but the problem is that this is often for stuff I don't want to keep around long-term (usually no more than an hour or two), resulting in my having to go in and delete the bookmarks at the end anyways in addition to the tabs. I've also tried just remembering the links I want to follow and not opening any new tabs, but that leads to me often completely forgetting what I was planning on investigating.

An option to open new tabs in an unloaded state, or, if that's not possible, to unload tabs that haven't ever been interacted with on an extremely short timer, would be wonderful. I realize that my case is fairly niche, though, and I'm not even sure whether or not this is in Sidebery's wheelhouse. Given how broad the scope of the project is vis-a-vis tab unloading/containers, though, I thought it might be worth asking about.

**Comment by emvaized** [comment]
[Auto Tab Discard](https://addons.mozilla.org/firefox/addon/auto-tab-discard/) addon provides an option which might be exactly what you're looking for: 
<img width="1189" alt="Снимок экрана 2022-10-17 в 19 25 29" src="https://user-images.githubusercontent.com/37851576/196231716-500d900e-384f-4f73-9639-92bfa8217d9f.png">

**Comment by mbnuqw** [comment]
It's probably better to create a feature request for this in [Auto Tab Discard](https://github.com/rNeomy/auto-tab-discard/) (and use @emvaized's suggested workaround) because I don't want to add such generic behavior that doesn't interact with sidebery panels/tabs branches.
