### ISSUE TITLE
Feature Request: Hide/Unload Tabs in Other Panels

### ISSUE THREAD

**Issue by OIK2** [mbnuqw/sidebery#807]
While I like being able to organize my tabs into various panels, they can become a little overwhelming in the top bar.  It would be nice if when I change panels it would unload the tab(to save memory), as well as hiding the tab(to save visual space).

**please remove, I found the setting**

**Comment by emvaized** [comment]
<img width="866" alt="Снимок экрана 2022-10-17 в 19 20 59" src="https://user-images.githubusercontent.com/37851576/196230655-6c8a7fda-ba62-4006-9047-68920f3ab746.png">

**Comment by OIK2** [comment]
Found the setting
