### ISSUE TITLE
Enhancements

### ISSUE THREAD

**Issue by ongots** [mbnuqw/sidebery#81]
1. Экспорт/Импорт:
-не все настройки переносятся
-табы перенеслись в обратном порядке, при этом табы в контейнере перенеслись правильно
-создаются лишние пустые контейнеры
-после перезапуска браузера вкладки из контейнера свалились в общий список вкладок

2. Если выбрать: Вид > Тема > нет - интерфейс ломается

3. favicons в закладках не подхватываются закладками родственого домена. Т.е. если у меня несколько закладок одного сайта и я открою одну, иконка появится только на этой одной закладке.

4. Закончить перевод интерфейса(несколько пунктов меню контейнера и несколько названий стилей)
5. Добавить возможность скрыть border под панелью навигации
6. Отцентровать первую иконку панели навигации к иконкам сайтов --nav-btn-width 30px

7. Добавьте CSS в описание
```
/* Hiding sidebar */
#sidebar{height: 97vh}
#appcontent{margin-left: 30px}
#sidebar-box:hover, #sidebar{max-width: 240px}
#sidebar-box{
    overflow: hidden;
    max-width: 30px;
    position: fixed;
    transition: 90ms}
[inFullscreen] #sidebar{height: 100vh}
[inFullscreen] #appcontent{margin-left: 1px}
[inFullscreen] #sidebar-box:hover, #sidebar{max-width: 240px}
[inFullscreen] #sidebar-box{
    overflow: hidden;
    max-width: 1px;
    position: fixed;
    top: 1px;
    transition: 90ms}
```
> OS: win x86-64  
> Firefox: 70.0  
> Extension: 3.0.2  <- 3.0.4  : )

**Comment by mbnuqw** [comment]
1. Экспорт/Импорт:  
-хм, если так, то баг. Что конкретно не перенеслось?
-экспортом переносятся только конфиги (общие настройки, настройки панелей, кастомные стили и меню). Добавлю, пожалуй, пояснение со списком того что будет экспортировано.
-баг
-хм.. тут сложно сказать что может быть причиной. Например, Firefox не сохраняет контейнеры созданные расширением после удаления этого расширения. Буду тестить.

2. Да, без стилей там ничего и не должно быть

3. Это исправление бага в версии 2. Там как раз, фавиконки кешировались по доменному имени и, в случае когда с разных путей одного домена приходили разные фавиконки, возникала путаница. Например тот же гитхаб:
![screenshot-2019 09 06-01 59 17](https://user-images.githubusercontent.com/6276694/64380302-26493500-d04a-11e9-97c6-5a5a21c1417d.jpg)
Поэтому, я решил хранить все по полному пути. А для закладок сделаю позже отдельную функцию для подгрузки иконок.

4. Да

5. Есть кастомный css:
```css
.Sidebar .nav {
  box-shadow: none;
}

.TabsPanel .container,
.Bookmarks .bookmarks-wrapper {
  box-shadow: none;
}
```
например

6. Есть кастомные стили.

7. В дев ветку добавил (немного изменил там некоторые стили - у меня не было видно кнопки с настройками), скоро в мастер залью.

Extension: 3.0.2 <- 3.0.4 - упс))

**Comment by ongots** [comment]
1. Экспорт/Импорт: 
-несколько раз все перепроверил. Настройки переносятся, извиняюсь за неверную информацию. Не переносятся только разрешения.
После импорта нужно сделать автоматическую перезагрузку страницы настроек. Чтобы было видно что импорт произошел и настройки применились.

-после применения снепшота или перемещении вкладок в контейнер, счетчики вкладок показывают завышеное число, пока не перезапустишь расширение или браузер.

2. А в чем смысл? Может убрать : )

8. Когда закрываю самый нижний таб, открывается таб из контейнера. Хотя стоит опция 'Заблокировать панель', это не препятствует переключению на вкладку из другого контейнера, а хотелось бы.

9. При перетаскивании вкладки над спящими они зачем-то загружаются.

10. В форме 'Сообщить об ошибке' снова ошибка : )

**Comment by mbnuqw** [comment]
- Для экспорта и ипорта думаю сделать список с чекбоксами, чтобы было видно и не вызывало вопросов. И да, пожалуй, после удачного импорта стоит автоматом перезагружать аддон.
- Да, с применением снепшота сейчас есть проблемы, буду чинить.
- Может кто-то захочет полностью переписать стили ). (~~я просто сделал тут как в TreeStyleTab~~)
- А что стоит в опции 'После закрытия текущей вкладки активировать'? И переключается панель или только вкладка?
- Да, это при перетаскивании чего-либо и (относительно) длительном наведением на вкладку она активируется. Это нужно чтобы иметь возможность перетащить что-то с одной страницы на другую. На самом деле самого иногда раздражает, думаю увеличить задержку перед активацией.
- Какая? (хм...вроде норм сейчас)

**Comment by ongots** [comment]
4. Стоит 'выкл', потому что он наиболее адекватно выбирает вкладку после закрытия. Переключается только вкладка.

6. Много строк не несущих информации

**Comment by mbnuqw** [comment]
4. Тогда все верно, если опция выключена Sidebery ничего не делает с порядком включения вкладок и Firefox переключает вкладку на след (по дефолтам)
5. ? это информация для меня, чтобы не задавать одинаковые вопросы

**Comment by ongots** [comment]
7. В css отредактированном вами: появляются светлые поля во время раскрытия; скролбар уезжает за экран

11. Сделать возможным перемещение закладки из папки в закрытую папку, при включенной опции 'Автоматически закрывать папки'

**Comment by mbnuqw** [comment]
Closing in favor of #117
