### ISSUE TITLE
[v5] Ctrl + Click Drag Out of Sidebar to Copy Tab (and any nested tabs) to destination

### ISSUE THREAD

**Issue by megamorphg** [mbnuqw/sidebery#823]
## Description
Currently this feature already exists when dragging from one profile with Sidebery to another profile's Sidebery.

Also I think this is fine to hard-code because no one will ever expect Ctrl + Click Drag to do anything other than copy the tabs.

**Comment by mbnuqw** [comment]
Closing as fixed in b30
