### ISSUE TITLE
Suggestion: Option to show all tabs

### ISSUE THREAD

**Issue by sig-kill** [mbnuqw/sidebery#83]
I use containers pretty often but it can be tedious having to switch between the container tabs at the top

I'd like to be able to have a setting that puts all tabs in the same main list regardless of what container it's in, preferably with some kind of distinguishing marking (colored underline, colored sidebar, etc)

This feature is the default behavior of Tree Style Tabs

![image](https://user-images.githubusercontent.com/8879524/64583517-21d09500-d346-11e9-92f3-31fc3473d0f5.png)

**Comment by piecevcake** [comment]
Me too.  I use Tree Tabs vertical groups to group tabs from different containers by task, need to see all the tabs for a task and switch between them! (Example- same site with different logins, facebook and google searches)

**Comment by mbnuqw** [comment]
Done in v4.x.x
