### ISSUE TITLE
Ability to rename Tabs

### ISSUE THREAD

**Issue by masoncowen** [mbnuqw/sidebery#830]
## Description
Would like if I could rename the tabs.
I currently use an external renaming tab extension but that doesn't keep the name when you follow a link.

**Comment by albino1** [comment]
Maybe take a look at this discussion:

https://github.com/mbnuqw/sidebery/issues/185

**Comment by masoncowen** [comment]
Thanks, github's search seems a bit useless. Nothing came up when I searched for rename tabs.
