### ISSUE TITLE
inquiry: possible to select tab via mouse without activating?

### ISSUE THREAD

**Issue by boldcompany** [mbnuqw/sidebery#833]
## Description
**Use Case**
Often a user wants to select a tab (or a group of tabs) to perform certain actions (closing, moving to another panel, etc.) but doesn't want to have to activate one of those selected tabs. 

**Inquiry**
Is it currently possible to select a sidebery tab via mouse (perhaps using a keyboard modifier) without activating that tab?

If it is not yet possible, this would be a feature request.

**Comment by albino1** [comment]
FWIW, if you ctrl+click the tab instead of just regular clicking the tab it doesn't activate.

**Comment by mbnuqw** [comment]
As mentioned by @albino1, you can: 
- select individual tabs with ctrl+click
- select tabs range with shift+click
- (if you don't use native context menu) select tabs range with right click
- use keyboard shortcuts to do that

These selected tabs will be handled (inside sidebery) separately from the current active tab (if it wasn't selected). You can also enable the "Sidebery settings > Tabs > Highlight native tabs..." setting. This will give Firefox and the other addons an ability to see selected from Sidebery tabs and interact with them, but in this case the current active tab will be included in that list.

**Comment by boldcompany** [comment]
@albino1 Thank you for your note. Solution works.

@mbnuqw This is such an excellent and complete feature set with precisely matches the use case and beyond.

Many thanks to you!!
