### ISSUE TITLE
[Feature request] Add a shortcut to open "Snapshots viewer"

### ISSUE THREAD

**Issue by gaesa** [mbnuqw/sidebery#838]
## Description
I use snapshots to restore unexpectedly closed windows and tabs, so it would be better to have a shortcut to open the snapshots page directly, or I need to open the settings firstly and then click "Snapshots viewer" , but I haven't found that shortcut in "Keybindings" where only a shortcut about creating a snapshots exists.

**Comment by baileymh** [comment]
Would also appreciate this! 
Maybe add it as an icon on the navigation bar like the Create Snapshop button.

**Comment by mbnuqw** [comment]
@baileymh You can also middle-click on "Create Snapshot" button to open the viewer.

**Comment by mbnuqw** [comment]
Resolved in v5.0.0
