### ISSUE TITLE
History / Back button is lost when changing containers

### ISSUE THREAD

**Issue by eneerge** [mbnuqw/sidebery#84]
This may not be fixable, but when you click on a link within a container that is excluded from being opened in said container, then your back button history is lost.

EG:
1. Set up container for DuckDuckGo
2. Use Include URL: /^http[s]{0,1}://(\w)*(\.){0,1}duckduckgo.com/
3. Exclude URL: /^(?!.*duckduckgo).*$/
4. Search for "test" in DuckDuckGo
5. Click the first link
6. The link opens outside of the DuckDuckGo container, but all history is lost and the back button can not be used

Ideally, history would be maintained, but I'm not sure if that's possible.  However when matching an exclusion, could the link open in a new tab? This should prevent losing your previous searches in your DuckDuckGo tab.

Worth noting a workaround is to simply middle click the link / open in new tab manually. 

With that said, I can envision scenarios where this auto breaking out of container based on an exclusion may not be foreseen and you don't manually click to open in a new tab and your back button is suddenly disabled.

**Comment by mbnuqw** [comment]
Yes, this is not appropriate behavior. I'll check what I can do with this.

**Comment by mbnuqw** [comment]
There is no way to fix this, closing.
