### ISSUE TITLE
Plain light theme is not so light

### ISSUE THREAD

**Issue by bcbwatt** [mbnuqw/sidebery#843]
## Steps to reproduce
- Open Firefox in [new profile](https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles)
- Install Sidebery 5.0.0b29
- Select plain, light in appearance options
- Set the sidebar CSS as follows:
```
#root.root {--tabs-height: 30px;}
#root.root {--bookmarks-folder-height: 30px;}
#root.root {--bookmarks-bookmark-height: 30px;}
#root.root {--btn-roundness: 4px;}
#root.root {--tabs-indent: 15px;}

.Tab[data-selected="true"] {
	opacity: 1.0;
}

.Tab[data-discarded="true"] > .body > .fav {
  opacity: 1.0;
}

.Tab[data-discarded="true"] > .body > .t-box, .Tab[data-discarded="true"] > .body > .ctx {
  opacity: 1.0;
}

.Tab .fav {
	transform: scale(1.0, 1.0);
}


.NavigationBar{
  background: #fafafa;
}
```

## Expected behavior

There is usable contrast between indented tabs and the background. The overall theme is light. [As seen in 5.0.0b28](https://imgur.com/a/Yi10xVw).

## Actual behavior
[This](https://imgur.com/a/LHbVlHA) is what it looks like. Every tab is much darker, and there is less contrast between the background and indented tabs. 
The selected tab is certainly more distinctive, but at the expense of making every single other tab look worse.

**Comment by mbnuqw** [comment]
Fixed in v5.0.0b30
