### ISSUE TITLE
Reopening Closed Tabs Places them at Panel End with "Panel End" Setting

### ISSUE THREAD

**Issue by megamorphg** [mbnuqw/sidebery#845]
## Steps to reproduce
Related to #829
1. Set "Position of new tab (general rule)" to "panel end"
2. Close a tab within a tree
3. Re-open the closed tab with `Ctrl + Shift + T`

## Expected behavior
Closed tab re-opens in same position as it was before it was closed (position of new tab rule should not apply to re-opened tab)

## Actual behavior
Closed tab re-opens at "panel end"

## Debug info

<details><summary><b>Addon data</b></summary><code>
{
  "addonVersion": "5.0.0b29",
  "firefoxVersion": "106.0.5",
  "settings": {
    "nativeScrollbars": true,
    "nativeScrollbarsThin": false,
    "nativeScrollbarsLeft": true,
    "selWinScreenshots": true,
    "updateSidebarTitle": true,
    "markWindow": false,
    "markWindowPreface": "[SB] ",
    "ctxMenuNative": false,
    "ctxMenuRenderInact": true,
    "ctxMenuRenderIcons": true,
    "ctxMenuIgnoreContainers": "",
    "navBarLayout": "vertical",
    "navBarInline": false,
    "navBarSide": "left",
    "hideAddBtn": false,
    "hideSettingsBtn": false,
    "navBtnCount": true,
    "hideEmptyPanels": true,
    "navActTabsPanelLeftClickAction": "new_tab",
    "navActBookmarksPanelLeftClickAction": "scroll",
    "navTabsPanelMidClickAction": "discard",
    "navBookmarksPanelMidClickAction": "convert",
    "navSwitchPanelsWheel": true,
    "groupLayout": "list",
    "skipEmptyPanels": true,
    "dndTabAct": true,
    "dndTabActDelay": 5000,
    "dndTabActMod": "alt",
    "dndExp": "pointer",
    "dndExpDelay": 50,
    "dndExpMod": "alt",
    "dndOutside": "data",
    "searchBarMode": "static",
    "warnOnMultiTabClose": "collapsed",
    "activateLastTabOnPanelSwitching": true,
    "showTabRmBtn": true,
    "hideInact": true,
    "activateAfterClosing": "prev",
    "activateAfterClosingGlobal": true,
    "activateAfterClosingNoFolded": true,
    "activateAfterClosingNoDiscarded": false,
    "askNewBookmarkPlace": true,
    "tabsRmUndoNote": true,
    "nativeHighlight": true,
    "tabsUnreadMark": true,
    "tabsUpdateMark": "all",
    "tabsReloadLimit": 3,
    "tabsReloadLimitNotif": false,
    "showNewTabBtns": true,
    "newTabBarPosition": "bottom",
    "tabsPanelSwitchActMove": true,
    "tabsUrlInTooltip": "full",
    "openSubPanelOnMouseHover": false,
    "colorizeTabs": true,
    "colorizeTabsSrc": "domain",
    "moveNewTabPin": "end",
    "moveNewTabParent": "first_child",
    "moveNewTabParentActPanel": true,
    "moveNewTab": "end",
    "moveNewTabActivePin": "end",
    "pinnedTabsPosition": "left",
    "pinnedTabsList": true,
    "pinnedAutoGroup": false,
    "tabsTree": true,
    "groupOnOpen": true,
    "tabsTreeLimit": "none",
    "hideFoldedTabs": true,
    "autoFoldTabs": false,
    "autoFoldTabsExcept": 5,
    "autoExpandTabs": false,
    "rmChildTabs": "folded",
    "tabsChildCount": true,
    "tabsLvlDots": true,
    "discardFolded": true,
    "discardFoldedDelay": 10,
    "discardFoldedDelayUnit": "min",
    "tabsTreeBookmarks": true,
    "treeRmOutdent": "first_child",
    "colorizeTabsBranches": false,
    "colorizeTabsBranchesSrc": "domain",
    "warnOnMultiBookmarkDelete": "any",
    "autoCloseBookmarks": false,
    "autoRemoveOther": false,
    "highlightOpenBookmarks": true,
    "activateOpenBookmarkTab": true,
    "showBookmarkLen": true,
    "bookmarksRmUndoNote": true,
    "loadBookmarksOnDemand": true,
    "pinOpenedBookmarksFolder": true,
    "loadHistoryOnDemand": true,
    "fontSize": "xxl",
    "animations": false,
    "animationSpeed": "fast",
    "theme": "proton",
    "density": "compact",
    "colorScheme": "ff",
    "sidebarCSS": false,
    "groupCSS": false,
    "snapNotify": true,
    "snapExcludePrivate": true,
    "snapInterval": 6,
    "snapIntervalUnit": "hr",
    "snapLimit": 31,
    "snapLimitUnit": "day",
    "hScrollAction": "switch_act_tabs",
    "navSwitchPanelsDelay": 128,
    "scrollThroughTabs": "panel",
    "scrollThroughVisibleTabs": true,
    "scrollThroughTabsSkipDiscarded": true,
    "scrollThroughTabsExceptOverflow": false,
    "scrollThroughTabsCyclic": true,
    "scrollThroughTabsScrollArea": -90,
    "autoMenuMultiSel": true,
    "multipleMiddleClose": true,
    "longClickDelay": 500,
    "wheelThreshold": false,
    "wheelThresholdX": 10,
    "wheelThresholdY": 60,
    "tabDoubleClick": "none",
    "tabsSecondClickActPrev": true,
    "shiftSelAct": true,
    "activateOnMouseUp": true,
    "tabLongLeftClick": "none",
    "tabLongRightClick": "duplicate",
    "tabCloseMiddleClick": "discard",
    "tabsPanelLeftClickAction": "none",
    "tabsPanelDoubleClickAction": "tab",
    "tabsPanelRightClickAction": "menu",
    "tabsPanelMiddleClickAction": "undo",
    "newTabMiddleClickAction": "new_child",
    "bookmarksLeftClickAction": "open_in_new",
    "bookmarksLeftClickActivate": true,
    "bookmarksLeftClickPos": "after",
    "bookmarksMidClickAction": "open_in_new",
    "bookmarksMidClickActivate": false,
    "bookmarksMidClickPos": "default",
    "syncName": "X470-FF-Release-default",
    "syncSaveSettings": true,
    "syncSaveCtxMenu": true,
    "syncSaveStyles": true,
    "syncSaveKeybindings": true
  },
  "permissions": {
    "allUrls": true,
    "tabHide": true,
    "clipboardWrite": true,
    "webRequest": true,
    "webRequestBlocking": true
  },
  "storage": {
    "size": "26.6 mb",
    "props": {
      "bookmarksRecentFolders": "76 b",
      "containers": "3.36 kb",
      "contextMenu": "1.49 kb",
      "expandedBookmarkFolders": "155 b",
      "favDomains": "325 kb",
      "favHashes": "21.5 kb",
      "favicons": "1.48 mb",
      "groupCSS": "2 b",
      "lastSnapTime": "13 b",
      "panelIndex": "1 b",
      "prevTabsDataCache": "297 kb",
      "profileID": "14 b",
      "settings": "3.62 kb",
      "sidebar": "4.27 kb",
      "sidebarCSS": "2 b",
      "snapshots": "24.2 mb",
      "tabsDataCache": "300 kb",
      "ver": "10 b"
    }
  },
  "sidebar": {
    "panels": {
      "bookmarks": {
        "type": 1,
        "id": "bookmarks",
        "name": "len: 9",
        "iconSVG": "icon_bookmarks",
        "iconIMGSrc": "",
        "iconIMG": "",
        "color": "toolbar",
        "lockedPanel": false,
        "tempMode": false,
        "skipOnSwitching": false,
        "rootId": "root________",
        "viewMode": "tree",
        "autoConvert": false
      },
      "history": {
        "type": 4,
        "id": "history",
        "name": "len: 7",
        "color": "toolbar",
        "iconSVG": "icon_clock",
        "tempMode": false,
        "lockedPanel": false,
        "skipOnSwitching": false,
        "viewMode": "history"
      },
      "oPvtGQIvR9Am": {
        "type": 2,
        "id": "oPvtGQIvR9Am",
        "name": "len: 7",
        "color": "toolbar",
        "iconSVG": "icon_tabs",
        "iconIMGSrc": "",
        "iconIMG": "",
        "lockedPanel": false,
        "skipOnSwitching": false,
        "noEmpty": false,
        "newTabCtx": "none",
        "dropTabCtx": "none",
        "moveTabCtx": "none",
        "moveTabCtxNoChild": true,
        "urlRulesActive": false,
        "urlRules": "",
        "bookmarksFolderId": -1,
        "newTabBtns": []
      },
      "cQUpsJL2HbcG": {
        "type": 2,
        "id": "cQUpsJL2HbcG",
        "name": "len: 6",
        "color": "blue",
        "iconSVG": "icon_tabs",
        "iconIMGSrc": "",
        "iconIMG": "",
        "lockedPanel": false,
        "skipOnSwitching": false,
        "noEmpty": false,
        "newTabCtx": "none",
        "dropTabCtx": "none",
        "moveTabCtx": "none",
        "moveTabCtxNoChild": true,
        "urlRulesActive": false,
        "urlRules": "",
        "bookmarksFolderId": -1,
        "newTabBtns": []
      },
      "77PJQY1X7zAm": {
        "type": 2,
        "id": "77PJQY1X7zAm",
        "name": "len: 6",
        "color": "turquoise",
        "iconSVG": "icon_tabs",
        "iconIMGSrc": "",
        "iconIMG": "",
        "lockedPanel": false,
        "skipOnSwitching": false,
        "noEmpty": false,
        "newTabCtx": "none",
        "dropTabCtx": "none",
        "moveTabCtx": "none",
        "moveTabCtxNoChild": true,
        "urlRulesActive": false,
        "urlRules": "",
        "bookmarksFolderId": -1,
        "newTabBtns": []
      },
      "Gi2njE8Dnlan": {
        "type": 2,
        "id": "Gi2njE8Dnlan",
        "name": "len: 6",
        "color": "green",
        "iconSVG": "icon_tabs",
        "iconIMGSrc": "",
        "iconIMG": "",
        "lockedPanel": false,
        "skipOnSwitching": false,
        "noEmpty": false,
        "newTabCtx": "none",
        "dropTabCtx": "none",
        "moveTabCtx": "none",
        "moveTabCtxNoChild": true,
        "urlRulesActive": false,
        "urlRules": "",
        "bookmarksFolderId": -1,
        "newTabBtns": []
      },
      "wdzkA8VBChsL": {
        "type": 2,
        "id": "wdzkA8VBChsL",
        "name": "len: 6",
        "color": "yellow",
        "iconSVG": "icon_tabs",
        "iconIMGSrc": "",
        "iconIMG": "",
        "lockedPanel": false,
        "skipOnSwitching": false,
        "noEmpty": false,
        "newTabCtx": "none",
        "dropTabCtx": "none",
        "moveTabCtx": "none",
        "moveTabCtxNoChild": true,
        "urlRulesActive": false,
        "urlRules": "",
        "bookmarksFolderId": -1,
        "newTabBtns": []
      },
      "Ak5q9G_7_hsL": {
        "type": 2,
        "id": "Ak5q9G_7_hsL",
        "name": "len: 6",
        "color": "orange",
        "iconSVG": "icon_tabs",
        "iconIMGSrc": "",
        "iconIMG": "",
        "lockedPanel": false,
        "skipOnSwitching": false,
        "noEmpty": false,
        "newTabCtx": "none",
        "dropTabCtx": "none",
        "moveTabCtx": "none",
        "moveTabCtxNoChild": true,
        "urlRulesActive": false,
        "urlRules": "",
        "bookmarksFolderId": -1,
        "newTabBtns": []
      },
      "tIpuOF5MEisL": {
        "type": 2,
        "id": "tIpuOF5MEisL",
        "name": "len: 6",
        "color": "red",
        "iconSVG": "icon_tabs",
        "iconIMGSrc": "",
        "iconIMG": "",
        "lockedPanel": false,
        "skipOnSwitching": false,
        "noEmpty": false,
        "newTabCtx": "none",
        "dropTabCtx": "none",
        "moveTabCtx": "none",
        "moveTabCtxNoChild": true,
        "urlRulesActive": false,
        "urlRules": "",
        "bookmarksFolderId": -1,
        "newTabBtns": []
      },
      "sIhAINvH6isL": {
        "type": 2,
        "id": "sIhAINvH6isL",
        "name": "len: 6",
        "color": "pink",
        "iconSVG": "icon_tabs",
        "iconIMGSrc": "",
        "iconIMG": "",
        "lockedPanel": false,
        "skipOnSwitching": false,
        "noEmpty": false,
        "newTabCtx": "none",
        "dropTabCtx": "none",
        "moveTabCtx": "none",
        "moveTabCtxNoChild": true,
        "urlRulesActive": false,
        "urlRules": "",
        "bookmarksFolderId": -1,
        "newTabBtns": []
      },
      "nNIxD1ytsrsL": {
        "type": 2,
        "id": "nNIxD1ytsrsL",
        "name": "len: 6",
        "color": "purple",
        "iconSVG": "icon_tabs",
        "iconIMGSrc": "",
        "iconIMG": "",
        "lockedPanel": false,
        "skipOnSwitching": false,
        "noEmpty": false,
        "newTabCtx": "none",
        "dropTabCtx": "none",
        "moveTabCtx": "none",
        "moveTabCtxNoChild": true,
        "urlRulesActive": false,
        "urlRules": "",
        "bookmarksFolderId": -1,
        "newTabBtns": []
      },
      "l57xRuBBu53N": {
        "type": 2,
        "id": "l57xRuBBu53N",
        "name": "len: 7",
        "color": "toolbar",
        "iconSVG": "icon_tabs",
        "iconIMGSrc": "",
        "iconIMG": "",
        "lockedPanel": false,
        "skipOnSwitching": false,
        "noEmpty": false,
        "newTabCtx": "none",
        "dropTabCtx": "none",
        "moveTabCtx": "none",
        "moveTabCtxNoChild": true,
        "urlRulesActive": false,
        "urlRules": "",
        "bookmarksFolderId": -1,
        "newTabBtns": []
      }
    },
    "nav": [
      "search",
      "bookmarks",
      "history",
      "sd-XqcSsH9U_eJG",
      "sp-arYkJj_-YW8z",
      "sd-0RTG0nRBEA0E",
      "oPvtGQIvR9Am",
      "cQUpsJL2HbcG",
      "77PJQY1X7zAm",
      "Gi2njE8Dnlan",
      "wdzkA8VBChsL",
      "Ak5q9G_7_hsL",
      "tIpuOF5MEisL",
      "sIhAINvH6isL",
      "nNIxD1ytsrsL",
      "l57xRuBBu53N",
      "sd-LG6U0Z8jb4ZE",
      "sp-0",
      "sd-0Ruoc0-VQ28E",
      "add_tp",
      "sd-uGNt_zOfLHJG",
      "remute_audio_tabs",
      "sd-wfp6yaNpcIJG",
      "collapse",
      "sd-apkhtLfLJqBF",
      "create_snapshot",
      "sd-Rrd5zW7r0JJG",
      "settings"
    ]
  },
  "containers": [
    {
      "id": "firefox-container-1",
      "name": "8",
      "icon": "...",
      "color": "blue",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": true,
      "includeHosts": "34",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": "",
      "cookieStoreId": "firefox-container-1",
      "colorCode": "#37adff"
    },
    {
      "id": "firefox-container-2",
      "name": "4",
      "icon": "...",
      "color": "orange",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": true,
      "includeHosts": "30",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": "",
      "cookieStoreId": "firefox-container-2",
      "colorCode": "#37adff"
    },
    {
      "id": "firefox-container-3",
      "name": "7",
      "icon": "...",
      "color": "green",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": true,
      "includeHosts": "33",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": "",
      "cookieStoreId": "firefox-container-3",
      "colorCode": "#37adff"
    },
    {
      "id": "firefox-container-4",
      "name": "8",
      "icon": "...",
      "color": "pink",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": true,
      "includeHosts": "34",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": "",
      "cookieStoreId": "firefox-container-4",
      "colorCode": "#37adff"
    },
    {
      "id": "firefox-container-6",
      "name": "3",
      "icon": "...",
      "color": "toolbar",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": true,
      "includeHosts": "29",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": "",
      "cookieStoreId": "firefox-container-6",
      "colorCode": "#37adff"
    },
    {
      "id": "firefox-container-7",
      "name": "2",
      "icon": "...",
      "color": "turquoise",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": true,
      "includeHosts": "47",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": "",
      "cookieStoreId": "firefox-container-7",
      "colorCode": "#37adff"
    },
    {
      "id": "firefox-container-8",
      "name": "2",
      "icon": "...",
      "color": "blue",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": true,
      "includeHosts": "28",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": "",
      "cookieStoreId": "firefox-container-8",
      "colorCode": "#37adff"
    },
    {
      "id": "firefox-container-10",
      "cookieStoreId": "firefox-container-10",
      "name": "4",
      "icon": "...",
      "color": "yellow",
      "colorCode": "#37adff",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-11",
      "cookieStoreId": "firefox-container-11",
      "name": "7",
      "icon": "...",
      "color": "purple",
      "colorCode": "#37adff",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-12",
      "cookieStoreId": "firefox-container-12",
      "name": "7",
      "icon": "...",
      "color": "red",
      "colorCode": "#37adff",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    }
  ],
  "windows": [
    {
      "state": "maximized",
      "incognito": false,
      "tabsCount": 261
    },
    {
      "state": "normal",
      "incognito": false,
      "tabsCount": 280
    },
    {
      "state": "maximized",
      "incognito": false,
      "tabsCount": 246
    },
    {
      "state": "normal",
      "incognito": false,
      "tabsCount": 9
    },
    {
      "state": "normal",
      "incognito": false,
      "tabsCount": 151
    },
    {
      "state": "maximized",
      "incognito": false,
      "tabsCount": 242
    },
    {
      "state": "maximized",
      "incognito": false,
      "tabsCount": 553
    },
    {
      "state": "maximized",
      "incognito": false,
      "tabsCount": 231
    },
    {
      "state": "minimized",
      "incognito": false,
      "tabsCount": 1
    },
    {
      "state": "maximized",
      "incognito": false,
      "tabsCount": 1
    },
    {
      "state": "maximized",
      "incognito": false,
      "tabsCount": 1
    }
  ],
  "bookmarks": {
    "bookmarksCount": 1997,
    "foldersCount": 262,
    "separatorsCount": 31,
    "maxDepth": 6
  }
}
</code></details>

**Comment by albino1** [comment]
FWIW this works for me with [v5.0.0b29](https://github.com/mbnuqw/sidebery/releases/tag/v5.0.0b29):

<details>
  <summary>Position of New Tab Panel End</summary>

![sidebery](https://user-images.githubusercontent.com/12164957/201504282-60291297-04cf-492b-8917-111eb6a1dfda.jpg)

</details>

<details>
  <summary>Restoring via CTRL+Shift+T</summary>

![firefox_imgJerKkJs](https://user-images.githubusercontent.com/12164957/201504324-5d22c9d7-59a2-4bc8-ba65-9f6e07246c0a.gif)


</details>

**Comment by megamorphg** [comment]
Weird, it's now working for me too. Maybe it was due to some other reason (heavy browsing) but I changed only that setting back to "None" and then the issue was resolved. Will test "Panel end" some more.

**Comment by mbnuqw** [comment]
Fixed in v5.0.0b30
