### ISSUE TITLE
[v5] The submenus of Non-native context menu are not automatically expanded on hover

### ISSUE THREAD

**Issue by wordpure** [mbnuqw/sidebery#849]
Is it possible to make sidebery's context menu automatically expand submenus on mouse hover.

![图片](https://user-images.githubusercontent.com/68013962/202172883-c0f7ae97-0579-4616-bc9b-f4b9451efcf8.png)

![图片](https://user-images.githubusercontent.com/68013962/202171718-59cf66e7-2d2a-4068-b214-149e78615853.png)

![图片](https://user-images.githubusercontent.com/68013962/202172904-9fec6b42-bd77-4f41-a7f5-6026fbd1975a.png)

Firefox version: 108.00b2
Sidebery version: 5.0.0b29

**Comment by mbnuqw** [comment]
It's not possible. The sidebery's context menu area is restricted by sidebar width. It is possible to enter to the sub-menu on hover with some delay, but in tests it appears that mis-hover is too time expensive (to return to the previous menu) and clicking is much faster (though it takes some time to write this action in muscle-memory).
