### ISSUE TITLE
[v5] Unable to reopen the URLs already included in a container in another container

### ISSUE THREAD

**Issue by wordpure** [mbnuqw/sidebery#850]
If a URL is already included in a container, it will still end up being opened in the including container, even if you choose to reopen in another container in the context menu.

This is not convenient for temporarily switching containers, is there an option to change its behavior?

![图片](https://user-images.githubusercontent.com/68013962/202177722-9884ebfe-71e9-422f-a840-e916ae2ca1c0.png)

![图片](https://user-images.githubusercontent.com/68013962/202177698-c43c7013-afba-4c18-99da-cc56ec1e7059.png)

**Comment by dexeonify** [comment]
With the latest beta release, reopening a tab _included in a container_ in another container **through the context menu** is fixed. But if you try to do the same with the new tab buttons/shortcuts, it won't work. In other words, middle clicking on the new tab button should reopen the current tab in default container, regardless of the container settings, for the current session.

**Comment by wordpure** [comment]
> With the latest beta release, reopening a tab _included in a container_ in another container **through the context menu** is fixed.

Thanks for the great work, in 5.0.0.rc5, reopening in other containers works fine. However, I found that when reopening, the tab bar will flicker briefly due to new and close tabs. Is it possible to avoid this by hiding tabs?

> But if you try to do the same with the new tab buttons/shortcuts, it won't work.

It is indeed a pity that the container state of the current tab cannot be inherited. Currently I use [multifoxContainer](https://github.com/xiaoxiaoflood/firefox-scripts/blob/master/chrome/multifoxContainer.uc.js), a UserChrome Scripts, to achieve this function.

**Comment by mbnuqw** [comment]
> However, I found that when reopening, the tab bar will flicker briefly due to new and close tabs. Is it possible to avoid this by hiding tabs?

Not possible.

**Comment by mbnuqw** [comment]
Resolved in v5.0.0
