### ISSUE TITLE
Add "rename group" Context menu Option

### ISSUE THREAD

**Issue by nazdridoy** [mbnuqw/sidebery#853]
There should be a Context menu Option "rename group" . Opening the group tab and then clicking the group name and renaming seems kind of a convoluted method.

**Comment by mbnuqw** [comment]
Added with https://github.com/mbnuqw/sidebery/commit/292b1459a70533ece11e3addab1cd1bce0dd9b23 (#185) in v5.0.0b30

**Comment by mbnuqw** [comment]
Available from v5.0.0
