### ISSUE TITLE
[v5] customisable delay for tab switching

### ISSUE THREAD

**Issue by j0lol** [mbnuqw/sidebery#860]
## Description
There is a min delay for panel switching:
![image](https://user-images.githubusercontent.com/24716467/203456523-c66b64b8-492f-4775-8089-c1d9a04c4dda.png)
but not for tab switching. I find this panel option useful because my trackpad scrolls quite quickly and this makes switching between panels more precise. As far as I can tell, there is no option here for tabs, and it is very hard for me to switch between tabs by scrolling.

**Comment by mbnuqw** [comment]
There is a "threshold" setting for this case - Sidebery settings / Mouse / "Set threshold for switching between panels and tabs...".
