### ISSUE TITLE
Where is user data ? 

### ISSUE THREAD

**Issue by Elaws** [mbnuqw/sidebery#865]
I would like to backup my sidebery settings and snapshots : where is stored user data ? Is it simply in Firefox Profile (AppData/Roaming/Mozilla on Windows) ?

I would like to just sync some AppData folder instead of manually exporting settings from Sidebery>Help>Export.

Thanks

**Comment by mbnuqw** [comment]
Sidebery uses the [standard storage API](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage), so all user data is stored somewhere in Profile folder, which means that syncing that folder will also sync sidebery data.

**Comment by Illiou** [comment]
More specifically, as far as I found out, for Firefox on Windows it is in:
```
%appdata%\Roaming\Mozilla\Firefox\Profiles\[profileName]\storage\default\moz-extension+++[UUID][...]
```
The UUID of the extension can be found in `about:debugging`, I don't know if it is changes with each installation.
