### ISSUE TITLE
Option to hide Sidebery Titlebar

### ISSUE THREAD

**Issue by RavenStryker** [mbnuqw/sidebery#866]
## Description
Hello! I'm not sure if this is currently possible (I haven't found a way to do it), but being able to hide the Sidebery titlebar would be a great addition. I feel like hiding the titlebar and instead adding a small toggle arrow above the settings button can accomplish the same thing and look much more aesthetically pleasing.

![image](https://user-images.githubusercontent.com/20632191/204350862-0431e3f7-a503-49b9-8e23-f13213ba17a3.png)

**Comment by albino1** [comment]
You have to do it with your `userChrome.css` file.  You can find the code snippet in the Github Wiki here:

https://github.com/mbnuqw/sidebery/wiki/Firefox-Styles-Snippets-(via-userChrome.css)

```
#sidebar-header {
  display: none;
}
```

**Comment by RavenStryker** [comment]
Cheers, that worked like a charm!
