### ISSUE TITLE
Auto-export every X minutes/hours, or, SAVE/SYNC snapshots to the cloud

### ISSUE THREAD

**Issue by wsalopek** [mbnuqw/sidebery#876]
## Description
I'd like to be able to auto-export, (and only snapshots), every X minutes/hours/days, to a user-selectable folder on my hard drive.

And I'd like to be able to IMPORT that snapshots export, to a copy of Sideberry running on another computer.

Thanks...

**Comment by azizLIGHT** [comment]
Would this work as a workaround? 
Make a script to backup the firefox profile directory, and maintain a list of these automated and dated backups to restore into

Would taking a backup of the Firefox profile dir while Firefox is running make incoherent backups of sidebery tree? My firefox is almost always running so live backups are the only way. I wonder if those "live" backups would work to restore sidebery tree without error

**Comment by domportera** [comment]
it would be extra amazing if you could just specify a raw download location (I.e. C:/SomeFolder/SomeOtherFolder) that these auto backups would go to. then any file-syncing cloud storage system would just work out of the box without any additional API dependencies

edit: reviewing the PR, theoretically it should be possible to do this provided your desired backup location is on the drive by abusing relative paths (i.e. `../../../../CloudFolder/SomeOtherCloudFolder`). If the backup location is on a different drive. then a symlink might be required.

Regarding the UX issue discussed in the PR #1047, personally i think most people dont have "Save As" as their default. And if they do, maybe the auto-backup system comes with a warning if using non-relative paths about this focus-stealing annoyance with that FF setting

**Comment by mbnuqw** [comment]
Available from v5.0.0 - as an auto export option (#1047).
