### ISSUE TITLE
Disable progress bar animation

### ISSUE THREAD

**Issue by simonstratmann** [mbnuqw/sidebery#879]
## Description
I find the progress animation (the bar that goes along the tab while the page is loading) annoying. I don't mind it in the top bar but when reading I can see the bar to the left and it's a bit distracting. I disabled animations but it didn't change this.

I'm not sure if Firefox allows disabling it just for the sideberry tabs but that would be great. Thanks!

**Comment by mbnuqw** [comment]
Fixed since v5.0.0 (or this is out of scope of Sidebery if I misunderstood)
