### ISSUE TITLE
Tabs shown in wrong/all panels. Any solutions? Is it only me/ my setup?

### ISSUE THREAD

**Issue by knighthawk0811** [mbnuqw/sidebery#881]
## Steps to reproduce
Every time I restart my PC and open FF I'll see tabs visible in the wrong panels. As I switch panels some tabs will simply show in ALL panels. The choice of extra tabs is unknown

## Expected behavior
tabs are only visible when the panel they belong to is visible

## Actual behavior
Current tab (and 0-n other tabs) becomes visible even after switching to any/all panels

## Possible solution
If you switch to (refresh) at least one tab in every panel and go back/forth the problem goes away.

## Notes
I don't want to HAVE to go through all my panels to fix this every day. Is there an "incorrect" combination of settings causing this? Can it be fixed?

It's possible this happens more often than only on restart, but so far I have only confirmed for sure that it happens after a restart.

## Debug info

<details><summary><b>Addon data</b></summary><code>

General
Context menu
Use comma-separated list of contaianers names or /regexp/
Navigation bar
Group page
Containers
Panels
Drag and Drop
Tabs
- global storage - fast, but inaccurate in rare cases.
- session storage - more strict, but slower. (Warning: Tabs data will be removed along with Browser Session)
  Note: If you have issues with incorrectly restored tabs, try to reopen sidebar and change this option.
Position of new tab
Pinned tabs
Tabs tree
Bookmarks
Appearance
Notes:
- To apply theme color to Sidebery buttons in browser interface set "svg.context-properties.content.enabled" to "true" in about:config page.
Mouse
Keybindings
Open/Close sidebar panel
F1
off
on
Switch to next panel
Alt+Period
off
on
Switch to previous panel
Alt+Comma
off
on
Open new tab in active panel
Ctrl+Space
off
on
Open new tab after active tab
Ctrl+Shift+Space
off
on
Open new tab as the first child of active tab
---
off
on
Open new tab as the last child of active tab
---
off
on
Remove selected items or active tab
---
off
on
Select all
---
off
on
Select up
Alt+Up
off
on
Select down
Alt+Down
off
on
Select range up
Alt+Shift+Up
off
on
Select range down
Alt+Shift+Down
off
on
Activate selection
Alt+Space
off
on
Reset selection
Alt+R
off
on
Open menu
---
off
on
Fold selected branch
---
off
on
Expand selected branch
---
off
on
Fold inactive branches
---
off
on
Active tabs history: Back
---
off
on
Active tabs history: Next
---
off
on
Active tabs history of panel: Back
---
off
on
Active tabs history of panel: Next
---
off
on
Move selected tabs to the active tab
---
off
on
Move tabs up
---
off
on
Move tabs down
---
off
on
Increase tab's tree level (indent)
---
off
on
Decrease tab's tree level (outdent)
---
off
on
Create snapshot
---
off
on
Switch to first panel
---
off
on
Switch to second panel
---
off
on
Switch to third panel
---
off
on
Switch to fourth panel
---
off
on
Switch to fifth panel
---
off
on
Switch to sixth panel
---
off
on
Switch to seventh panel
---
off
on
Switch to eighth panel
---
off
on
Switch to ninth panel
---
off
on
Switch to tenth panel
---
off
on
Permissions
Required for:
- Cleaning cookies
- Proxy and URL rules of containers
- Screenshots for the group page and windows selection panel
- Changing the User-Agent per container
Required for:
- Hiding tabs in inactive panels
- Hiding folded tabs
Required for:
- Copying URLs of tabs/bookmarks through context menu
Required for:
- Changing the User-Agent per container
Required for:
- Per-container proxy
Snapshots
Storage
 (~530.3 kb)
favicons
~496.9 kb
panels_v4
~10.6 kb
prevTabsData_v4
~6.5 kb
tabsData_v4
~6 kb
favUrls
~5.2 kb
settings
~2.8 kb
containers_v4
~788 b
tabsMenu
~308 b
bookmarksMenu
~226 b
sidebarCSS
~215 b
tabsPanelMenu
~184 b
bookmarksPanelMenu
~54 b
expandedBookmarks
~35 b
profileID
~14 b
favAutoCleanTime
~10 b
panelIndex
~1 b
Sync
 (~5.7 kb)
Settings
D_n4v_Ghjn1I - 2022.12.09 - 13:31:45 - 2.9 kb
Context menu
D_n4v_Ghjn1I - 2022.12.08 - 10:15:19 - 911 b
Styles
D_n4v_Ghjn1I - 2022.12.08 - 10:15:20 - 1.9 kb
Help
Note: Updating tabs may cause them to be rearranged
OS: win
Firefox: 107.0.1
Addon: 4.10.2
{
  "settings": {
    "version": "4.10.2",
    "nativeScrollbars": true,
    "selWinScreenshots": true,
    "tabsCheck": true,
    "tabsFix": "notify",
    "markWindow": false,
    "markWindowPreface": "[Sidebery] ",
    "ctxMenuNative": false,
    "autoHideCtxMenu": "none",
    "ctxMenuRenderInact": true,
    "ctxMenuIgnoreContainers": "",
    "navBarLayout": "vertical",
    "navBarInline": false,
    "hideAddBtn": false,
    "hideSettingsBtn": false,
    "navBtnCount": true,
    "hideEmptyPanels": true,
    "navActTabsPanelLeftClickAction": "none",
    "navActBookmarksPanelLeftClickAction": "none",
    "navMidClickAction": "none",
    "navSwitchPanelsWheel": true,
    "groupLayout": "list",
    "skipEmptyPanels": false,
    "dndTabAct": true,
    "dndTabActDelay": 750,
    "dndTabActMod": "none",
    "dndExp": "pointer",
    "dndExpDelay": 0,
    "dndExpMod": "none",
    "stateStorage": "session",
    "warnOnMultiTabClose": "collapsed",
    "activateOnMouseUp": true,
    "activateLastTabOnPanelSwitching": true,
    "showTabRmBtn": true,
    "showTabCtx": true,
    "hideInact": true,
    "activateAfterClosing": "next",
    "activateAfterClosingPrevRule": "visible",
    "activateAfterClosingNextRule": "tree",
    "activateAfterClosingGlobal": false,
    "activateAfterClosingNoFolded": true,
    "activateAfterClosingNoDiscarded": true,
    "shiftSelAct": true,
    "askNewBookmarkPlace": false,
    "tabsRmUndoNote": true,
    "nativeHighlight": false,
    "tabsUnreadMark": false,
    "tabsReloadLimit": 5,
    "tabsReloadLimitNotif": true,
    "tabsPanelSwitchActMove": true,
    "moveNewTabPin": "end",
    "moveNewTabParent": "last_child",
    "moveNewTabParentActPanel": false,
    "moveNewTab": "end",
    "pinnedTabsPosition": "panel",
    "pinnedTabsList": false,
    "pinnedAutoGroup": false,
    "tabsTree": false,
    "groupOnOpen": true,
    "tabsTreeLimit": "none",
    "hideFoldedTabs": false,
    "autoFoldTabs": false,
    "autoFoldTabsExcept": "none",
    "autoExpandTabs": false,
    "rmChildTabs": "none",
    "tabsChildCount": true,
    "tabsLvlDots": false,
    "discardFolded": false,
    "discardFoldedDelay": 0,
    "discardFoldedDelayUnit": "sec",
    "tabsTreeBookmarks": true,
    "treeRmOutdent": "branch",
    "bookmarksPanel": true,
    "warnOnMultiBookmarkDelete": "collapsed",
    "openBookmarkNewTab": false,
    "midClickBookmark": "open_new_tab",
    "actMidClickTab": false,
    "autoCloseBookmarks": false,
    "autoRemoveOther": false,
    "highlightOpenBookmarks": false,
    "activateOpenBookmarkTab": false,
    "showBookmarkLen": false,
    "bookmarksRmUndoNote": true,
    "fontSize": "xxl",
    "bgNoise": true,
    "animations": true,
    "animationSpeed": "fast",
    "theme": "default",
    "style": "auto",
    "sidebarCSS": true,
    "groupCSS": false,
    "snapNotify": true,
    "snapExcludePrivate": false,
    "snapInterval": 0,
    "snapIntervalUnit": "min",
    "snapLimit": 0,
    "snapLimitUnit": "snap",
    "hScrollThroughPanels": false,
    "scrollThroughTabs": "none",
    "scrollThroughVisibleTabs": false,
    "scrollThroughTabsSkipDiscarded": false,
    "scrollThroughTabsExceptOverflow": true,
    "scrollThroughTabsCyclic": false,
    "tabDoubleClick": "none",
    "tabLongLeftClick": "none",
    "tabLongRightClick": "none",
    "tabsPanelLeftClickAction": "none",
    "tabsPanelDoubleClickAction": "tab",
    "tabsPanelRightClickAction": "menu",
    "tabsPanelMiddleClickAction": "tab",
    "syncName": "",
    "syncSaveSettings": true,
    "syncSaveCtxMenu": true,
    "syncSaveStyles": true,
    "syncAutoApply": false
  },
  "permissions": {
    "allUrls": false,
    "tabHide": true,
    "actualAllUrls": false,
    "actualTabHide": true
  },
  "storage": {
    "size": "530.4 kb",
    "props": {
      "bookmarksMenu": "226 b",
      "bookmarksPanelMenu": "54 b",
      "containers_v4": "788 b",
      "expandedBookmarks": "35 b",
      "favAutoCleanTime": "10 b",
      "favUrls": "5.2 kb",
      "favicons": "496.9 kb",
      "panelIndex": "1 b",
      "panels_v4": "10.6 kb",
      "prevTabsData_v4": "6.5 kb",
      "profileID": "14 b",
      "settings": "2.8 kb",
      "sidebarCSS": "215 b",
      "tabsData_v4": "6.2 kb",
      "tabsMenu": "308 b",
      "tabsPanelMenu": "184 b"
    }
  },
  "panels": [
    {
      "type": "bookmarks",
      "id": "bookmarks",
      "cookieStoreId": "bookmarks",
      "name": 9,
      "icon": "...",
      "bookmarks": true,
      "lockedPanel": false,
      "skipOnSwitching": false
    },
    {
      "type": "default",
      "id": "firefox-default",
      "name": 7,
      "icon": "...",
      "cookieStoreId": "firefox-default",
      "lockedTabs": false,
      "lockedPanel": false,
      "skipOnSwitching": false,
      "noEmpty": false,
      "newTabCtx": "none",
      "dropTabCtx": "none",
      "moveTabCtx": "none",
      "moveTabCtxNoChild": true
    },
    {
      "type": "tabs",
      "id": "zxSc20C4dCfJ",
      "name": 3,
      "icon": "...",
      "color": "...",
      "customIconSrc": "",
      "customIcon": "",
      "lockedTabs": false,
      "lockedPanel": false,
      "skipOnSwitching": false,
      "noEmpty": false,
      "newTabCtx": "none",
      "dropTabCtx": "none",
      "moveTabCtx": "none",
      "moveTabCtxNoChild": true,
      "urlRulesActive": false,
      "urlRules": ""
    },
    {
      "type": "tabs",
      "id": "XgFbLCR9tu1I",
      "name": 7,
      "icon": "...",
      "color": "...",
      "customIconSrc": 13,
      "customIcon": 390,
      "lockedTabs": false,
      "lockedPanel": false,
      "skipOnSwitching": false,
      "noEmpty": false,
      "newTabCtx": "none",
      "dropTabCtx": "none",
      "moveTabCtx": "none",
      "moveTabCtxNoChild": true,
      "urlRulesActive": false,
      "urlRules": ""
    },
    {
      "type": "tabs",
      "id": "ot0KR-e9CI1I",
      "name": 9,
      "icon": "...",
      "color": "...",
      "customIconSrc": 8,
      "customIcon": 594,
      "lockedTabs": false,
      "lockedPanel": false,
      "skipOnSwitching": false,
      "noEmpty": false,
      "newTabCtx": "none",
      "dropTabCtx": "none",
      "moveTabCtx": "none",
      "moveTabCtxNoChild": true,
      "urlRulesActive": false,
      "urlRules": ""
    },
    {
      "type": "tabs",
      "id": "K_HfJOSFTK1I",
      "name": 12,
      "icon": "...",
      "color": "...",
      "customIconSrc": 8,
      "customIcon": 834,
      "lockedTabs": false,
      "lockedPanel": false,
      "skipOnSwitching": false,
      "noEmpty": false,
      "newTabCtx": "none",
      "dropTabCtx": "none",
      "moveTabCtx": "none",
      "moveTabCtxNoChild": true,
      "urlRulesActive": false,
      "urlRules": ""
    },
    {
      "type": "tabs",
      "id": "g3PeXrKR7F1I",
      "name": 17,
      "icon": "...",
      "color": "...",
      "customIconSrc": 7,
      "customIcon": 318,
      "lockedTabs": false,
      "lockedPanel": false,
      "skipOnSwitching": false,
      "noEmpty": false,
      "newTabCtx": "none",
      "dropTabCtx": "none",
      "moveTabCtx": "none",
      "moveTabCtxNoChild": true,
      "urlRulesActive": false,
      "urlRules": ""
    },
    {
      "type": "tabs",
      "id": "PbyUTE5zyy1I",
      "name": 8,
      "icon": "...",
      "color": "...",
      "customIconSrc": 9,
      "customIcon": 1162,
      "lockedTabs": false,
      "lockedPanel": false,
      "skipOnSwitching": false,
      "noEmpty": false,
      "newTabCtx": "none",
      "dropTabCtx": "none",
      "moveTabCtx": "none",
      "moveTabCtxNoChild": true,
      "urlRulesActive": false,
      "urlRules": ""
    },
    {
      "type": "tabs",
      "id": "TF1euOiej73I",
      "name": 8,
      "icon": "...",
      "color": "...",
      "customIconSrc": 8,
      "customIcon": 766,
      "lockedTabs": false,
      "lockedPanel": false,
      "skipOnSwitching": false,
      "noEmpty": false,
      "newTabCtx": "none",
      "dropTabCtx": "none",
      "moveTabCtx": "none",
      "moveTabCtxNoChild": true,
      "urlRulesActive": false,
      "urlRules": ""
    },
    {
      "type": "tabs",
      "id": "mBLzIls9eC1I",
      "name": 10,
      "icon": "...",
      "color": "...",
      "customIconSrc": 8,
      "customIcon": 1070,
      "lockedTabs": false,
      "lockedPanel": false,
      "skipOnSwitching": false,
      "noEmpty": false,
      "newTabCtx": "none",
      "dropTabCtx": "none",
      "moveTabCtx": "none",
      "moveTabCtxNoChild": true,
      "urlRulesActive": false,
      "urlRules": ""
    },
    {
      "type": "tabs",
      "id": "Lsw0T0ImOk3I",
      "name": 8,
      "icon": "...",
      "color": "...",
      "customIconSrc": 11,
      "customIcon": 954,
      "lockedTabs": false,
      "lockedPanel": false,
      "skipOnSwitching": false,
      "noEmpty": false,
      "newTabCtx": "none",
      "dropTabCtx": "none",
      "moveTabCtx": "none",
      "moveTabCtxNoChild": true,
      "urlRulesActive": false,
      "urlRules": ""
    },
    {
      "type": "tabs",
      "id": "BVesLcxo-U03",
      "name": 3,
      "icon": "...",
      "color": "...",
      "customIconSrc": 12,
      "customIcon": 1038,
      "lockedTabs": false,
      "lockedPanel": false,
      "skipOnSwitching": false,
      "noEmpty": false,
      "newTabCtx": "none",
      "dropTabCtx": "none",
      "moveTabCtx": "none",
      "moveTabCtxNoChild": true,
      "urlRulesActive": false,
      "urlRules": ""
    }
  ],
  "containers": [
    {
      "id": "firefox-container-1",
      "name": 3,
      "icon": "...",
      "color": "...",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-4",
      "name": 10,
      "icon": "...",
      "color": "...",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-6",
      "name": 17,
      "icon": "...",
      "color": "...",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    }
  ],
  "cssVars": "TypeError: can't convert undefined to object",
  "sidebarCSSLen": 198,
  "windows": [
    {
      "state": "maximized",
      "incognito": false,
      "tabsCount": 58
    }
  ],
  "tabsMenu": [
    [
      "undoRmTab",
      "mute",
      "reload",
      "bookmark"
    ],
    "separator-1",
    [
      {
        "name": "Move to"
      },
      "moveToNewWin",
      "moveToWin",
      "moveToPanel"
    ],
    [
      {
        "name": "Reopen in"
      },
      "reopenInNewWin",
      "reopenInWin",
      "reopenInCtr"
    ],
    "separator-2",
    "pin",
    "duplicate",
    "discard",
    "copyUrls",
    "separator-3",
    "group",
    "flatten",
    "separator-4",
    "clearCookies",
    "close"
  ],
  "bookmarksMenu": [
    [
      {
        "name": "Open in"
      },
      "openInNewWin",
      "openInNewPrivWin",
      "openInCtr"
    ],
    "separator-5",
    "createBookmark",
    "createFolder",
    "createSeparator",
    "separator-6",
    "sortByName",
    "sortByLink",
    "sortByTime",
    "separator-7",
    "copyUrls",
    "edit",
    "delete"
  ],
  "bookmarks": {
    "bookmarksCount": 102,
    "foldersCount": 23,
    "separatorsCount": 0,
    "maxDepth": 3
  }
}

</code></details>

<details><summary><b>Logs</b></summary><code>

</code></details>

**Comment by albino1** [comment]
The best current solution seems to be upgrading from v4 to v5.  It's still technically in beta, but it's been very stable for me for quite a few releases now.  Maybe give that a try:

https://github.com/mbnuqw/sidebery/releases

**Comment by knighthawk0811** [comment]
Thanks. Trying it out now. Will know more next time I restart (I'm at work so maybe later)

**Comment by knighthawk0811** [comment]
Solved
