### ISSUE TITLE
[v5] non-consecutive tabs cannot be moved to different window

### ISSUE THREAD

**Issue by rdegraaff** [mbnuqw/sidebery#886]
## Steps to reproduce
1. Open more than two tabs with websites in a single window
2. Open a new/different window
3. Select a couple of the tabs **in a non-consecutive order**. (Hold ctrl while clicking some tabs)
4. Try to drag the selected tabs over to the Sidebery panel in the new window (Hover over one of the selected tabs, hold mouse button and start dragging)

## Expected behavior
- All the selected tabs are moved to the new window.

## Actual behavior
- Only a single tab is moved, namely the one that was hovered over before dragging to a different window

**Comment by mbnuqw** [comment]
Fixed in v5.0.0b30
