### ISSUE TITLE
Lock focus inside a container

### ISSUE THREAD

**Issue by prizrak9** [mbnuqw/sidebery#89]
I want an option to save the last active tabs for every container so that when I close one tab I won't be switched to tabs from other containers.

**Comment by prizrak9** [comment]
Oh, I see how it's supposed to work. But it's not what I want.
I have many tabs open already and when I close one of them I expect the previous tab from the same container to be open.

The idea is when I'm working in the working container and close a tab I expect it to not open a tab from another container even if it was previous globally. Instead, I want you to be switched to the previous tab from the same container so maybe you can introduce some local tab histories so that when close tab from working container I won't be switched to one from the personal container or something.

I'm talking about this option to be locked to every container open.
![image](https://user-images.githubusercontent.com/26070759/64880164-2f489080-d660-11e9-9277-3e8cbe53691c.png)

**Comment by mbnuqw** [comment]
Aha, got it now! Yes, behavior that you describes looks more logical, so I think I'll add an option to change this, and also I'll update defaults for this case.

**Comment by mbnuqw** [comment]
Now we have sub-option 'Globally' of option 'After closing current tab activate...' to handle this case.
