### ISSUE TITLE
[v5] Unpinning multiple tabs should keep their order

### ISSUE THREAD

**Issue by koppor** [mbnuqw/sidebery#894]
## Steps to reproduce

1. Pin tabs
    ![image](https://user-images.githubusercontent.com/1366654/212259555-1b8652a2-b61f-40e7-97d0-2bc93d3b4fa4.png)
2. Select multiple pinned tabs
3. Choose "unpin"
    ![image](https://user-images.githubusercontent.com/1366654/212259657-65c7e038-ead4-45e8-a381-e259fd2548dd.png)
4. See the order reversed
    ![image](https://user-images.githubusercontent.com/1366654/212259728-c913d9d7-8752-46f5-bb20-dd277956b408.png)

## Expected behavior

- Order should be kept

## Actual behavior

- Order reversed

**Comment by mbnuqw** [comment]
Fixed in v5.0.0b30.
