### ISSUE TITLE
Sideberry at Tor - Configuration Problem, Link of the Screen-Video-View

### ISSUE THREAD

**Issue by GreimersStefan** [mbnuqw/sidebery#896]
## Steps to reproduce
- Open Firefox in [new profile](https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles)
- Install Sidebery
- ...

## Debug info

<details><summary><b>Addon data</b></summary><code>

</code></details>

<details><summary><b>Logs</b></summary><code>

</code></details>
[https://magentacloud.de/s/JE6XH2xszeBnoRa](url)

**Comment by mbnuqw** [comment]
This happens because sidebar in that new window is not open. Unfortunately, Sidebery (and any other addon) cannot control whether the sidebar is shown when the window is opened or not (and you need to manually open sidebar with Sidebery).

**Comment by GreimersStefan** [comment]
Thanks for the answer. I've now gone and copied everything from Opera, translated it into Java with Visual Studio Code and imported it into your app. You can handle everything with this. However, I published a message in the Tor Browser Project, according to which there is a configuration problem with Tor, in which servers with specified text modules are simply rejected and Java style sheets are rejected. So I'm asking you and me how to configure or program a connection, possibly in an extension that grants permission. As far as I know, the problem is in the Tor Project console, which was programmed to be so unchangeable.

> Am 20.01.2023 um 18:15 schrieb Max Badryzlov ***@***.***>:
> 
> This happens because sidebar in that new window is not open. Unfortunately, Sidebery (and any other addon) cannot control whether the sidebar is shown when the window is opened or not (and you need to manually open sidebar with Sidebery).
> 
>
