### ISSUE TITLE
Additional bookmark panels for bookmark folders

### ISSUE THREAD

**Issue by GeniusBroccoli** [mbnuqw/sidebery#897]
Is it possible to create additional bookmark panels for individual folders in bookmarks? I haven't found such feature, but is there one? And if not, let it be a new feature request.

**Comment by mbnuqw** [comment]
It is already implemented in the v5 beta-version. There you can create bookmarks panel from any bookmarks folder.

**Comment by mbnuqw** [comment]
Available since v5.0.0
