### ISSUE TITLE
Drag and drop multiple tabs to the panel's icon leads to incorrect tabs positioning

### ISSUE THREAD

**Issue by mbnuqw** [mbnuqw/sidebery#91]
## Description
Incorrect handling of drop event on the panel's icon

## Steps to reproduce
- Select multiple tabs
- Drag and drop them to the icon of another panel

## Expected behavior
- Tabs should be reopened at the end of the target panel

## Actual behavior
- In some cases losing tree
- Incorrect initial positioning, which leads to the glitching UI

## Environment info

OS: linux  
Firefox: 69.0  
Addon: 3.0.7

**Comment by TheSwingingStar** [comment]
Can confirm that all Tabs are picked up by the extension and properly set to the Default Group now.

**Comment by mbnuqw** [comment]
Was fixed in v3.1.0
