### ISSUE TITLE
Make Sydebery follow the global Firefox theme

### ISSUE THREAD

**Issue by marzecdawid** [mbnuqw/sidebery#911]
## Description
I recently moved from Tree Style Tab to Sydebery and the biggest downside is that the Sidebery does not follow the style set for Firefox. Writing your own custom style for Sydebery requires some knowledge of CSS and a lot of time.
Making it to follow the global Firefox style would allow to easily and quickly change the appearance of the Sydebery with thousands of custom themes alrady available on the Firefox addons page.

**Comment by ghost** [comment]
With the beta, this is possible. **Uninstall your current version before installing the beta.**

**Comment by marzecdawid** [comment]
@EldritchEevee It is working correctly in the beta, thank you very much!
