### ISSUE TITLE
v5: Add universal tab-unread status

### ISSUE THREAD

**Issue by ElDani82** [mbnuqw/sidebery#913]
## Description
The tab's data-unread attribute only triggers the first time a tab is opened. Once a tab has been read, most of the expected changes to the tab don't change the bool value.

Unless I'm missing something, there's no universal way of visually highlighting when a tab is actually unread. If the setting is active, a change to document.title can trigger the data-unread attribute, however redirecting to a different url (which includes a change to the tab title) does not trigger it. Neither does reloading the tab while it's in the background.

I assume the data-unread attribute was not meant to be used this way?

In any case, I'd love to have a way of visually highlighting tabs that contain new information, whether they've been (automatically) reloaded or the location.href has changed.

This was possible with some CSS in Tree Style Tab, which I used before switching to Sidebery and it would be a great help to get this functionality back.

I'm using the latest beta v5.0.0b30

**Comment by mbnuqw** [comment]
Yes, the `data-unread` attribute is applied to the tab itself, and it doesn't handle the changes of the page in that tab. There is the `data-updated` attribute for tracking changes of the page's title, which can be activated with the `Show mark on tabs with updated title` option in the "Tabs" section of sidebery settings. Though, it doesn't handle the first change of a title after the location.href changed. I can add a sub-option to handle this case as well.

**Comment by mbnuqw** [comment]
Added in [v5.0.0b31](https://github.com/mbnuqw/sidebery/releases/tag/v5.0.0b31)

**Comment by ElDani82** [comment]
Just tested it, working perfectly. Thank you!
