### ISSUE TITLE
Confusing UI colorizing semantics

### ISSUE THREAD

**Issue by no1xsyzy** [mbnuqw/sidebery#919]
## Steps to reproduce
- Open Firefox in [new profile](https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles)
- Install Sidebery
- Either close a collapsed tab or remove a panel, there will be a pop-up.

## Expected behavior
In confirm pop-up, the dangerous operation "Yes" should be red and the no-op operation "No" should be grey.
(That is how warning works to human.)

## Actual behavior
The dangerous "Yes" is blue and the no-op "No" is red, which is confusing.

## More info
Relevant file
https://github.com/mbnuqw/sidebery/blob/cbca465ba2358763b6020306b84eb68bac3c8e7a/src/sidebar/components/popup.confirm.vue
I have tried to locate all invoker of this pop-up, and all of them are using "Yes" to warn the dangerous things. I shall conclude that it can be solved by simply changing the pop-up.

**Comment by mbnuqw** [comment]
Resolved in v5.0.0
