### ISSUE TITLE
Default Panel empty, and New Tabs outside any container in Icecat 

### ISSUE THREAD

**Issue by TheSwingingStar** [mbnuqw/sidebery#92]
## Description
Started using Sidebery lately, but as as soon as I installed it, I noticed that tabs already open beforehand were not shown within the extension, being only accessible by Tab Switching (Ctrl+Tab), which ignores the container structuring. Added onto this, tabs created with New Tab (Ctrl+T) or (Ctrl+Shift+T)  are also not shown within any of the panels, nor are their child tabs.

## To Reproduce
Using Windows 10, with [Icecat 68.1.0 (64-bit)](https://github.com/muslayev/icecat-win64/releases), install latest Sidebery from addons.mozilla.org

**Comment by mbnuqw** [comment]
Could you, please, copy and paste the debug info (Settings/Help/button "Debug info") here?
Also, does the issue persist after you restart the sidebar?

**Comment by TheSwingingStar** [comment]
Yes, the issue persists if I open/close the sidebar, or even if I disable-enable the extension.

## Debug Info
`{
  "settings": {
    "version": "3.0.7",
    "nativeScrollbars": false,
    "ctxMenuNative": false,
    "autoHideCtxMenu": "none",
    "ctxMenuRenderInact": false,
    "navBarInline": true,
    "hideSettingsBtn": false,
    "hideAddBtn": true,
    "navBtnCount": true,
    "hideEmptyPanels": false,
    "navMidClickAction": "none",
    "navSwitchPanelsWheel": false,
    "groupLayout": "grid",
    "activateLastTabOnPanelSwitching": true,
    "skipEmptyPanels": false,
    "showTabRmBtn": true,
    "hideInact": false,
    "activateAfterClosing": "prev",
    "activateAfterClosingPrevRule": "tree",
    "activateAfterClosingNextRule": "tree",
    "pinnedTabsPosition": "top",
    "pinnedTabsList": false,
    "tabsTree": true,
    "groupOnOpen": true,
    "tabsTreeLimit": "none",
    "hideFoldedTabs": false,
    "autoFoldTabs": true,
    "autoExpandTabs": true,
    "rmChildTabs": "none",
    "tabsChildCount": true,
    "tabsLvlDots": true,
    "discardFolded": false,
    "discardFoldedDelay": 0,
    "discardFoldedDelayUnit": "sec",
    "bookmarksPanel": false,
    "openBookmarkNewTab": false,
    "autoCloseBookmarks": false,
    "autoRemoveOther": false,
    "highlightOpenBookmarks": false,
    "activateOpenBookmarkTab": false,
    "showBookmarkLen": false,
    "fontSize": "xxs",
    "bgNoise": true,
    "animations": true,
    "theme": "default",
    "style": "dark",
    "sidebarCSS": false,
    "groupCSS": false,
    "snapInterval": 0,
    "snapIntervalUnit": "min",
    "snapLimit": 0,
    "snapLimitUnit": "snap",
    "hScrollThroughPanels": false,
    "scrollThroughTabs": "none",
    "scrollThroughVisibleTabs": false,
    "scrollThroughTabsExceptOverflow": true,
    "tabDoubleClick": "new_after",
    "tabLongLeftClick": "none",
    "tabLongRightClick": "none",
    "tabsPanelLeftClickAction": "none",
    "tabsPanelDoubleClickAction": "tab",
    "tabsPanelRightClickAction": "none"
  },
  "permissions": {
    "allUrls": false,
    "tabHide": false,
    "actualAllUrls": false,
    "actualTabHide": false
  },
  "storage": {
    "size": "195.5 kb",
    "props": {
      "bookmarksMenu": "113 b",
      "cssVars": "1.5 kb",
      "favAutoCleanTime": "10 b",
      "favUrls": "9.2 kb",
      "favicons": "181.4 kb",
      "panelIndex": "1 b",
      "panels": "1.4 kb",
      "settings": "1.4 kb",
      "tabsMenu": "176 b",
      "tabsTrees": "2 b"
    }
  },
  "panels": [
    {
      "cookieStoreId": "bookmarks",
      "icon": "...",
      "name": 9,
      "type": "bookmarks",
      "dashboard": "BookmarksDashboard",
      "panel": "BookmarksPanel",
      "lockedPanel": false,
      "bookmarks": true
    },
    {
      "cookieStoreId": "firefox-default",
      "icon": "...",
      "name": 7,
      "type": "default",
      "dashboard": "DefaultTabsDashboard",
      "panel": "TabsPanel",
      "lockedTabs": false,
      "lockedPanel": false,
      "noEmpty": false,
      "lastActiveTab": -1
    },
    {
      "cookieStoreId": "icecat-container-2",
      "color": "...",
      "icon": "...",
      "name": 4,
      "type": "ctx",
      "dashboard": "TabsDashboard",
      "panel": "TabsPanel",
      "lockedTabs": false,
      "lockedPanel": false,
      "proxy": null,
      "proxified": false,
      "noEmpty": false,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "lastActiveTab": -1
    },
    {
      "cookieStoreId": "icecat-container-6",
      "color": "...",
      "icon": "...",
      "name": 5,
      "type": "ctx",
      "dashboard": "TabsDashboard",
      "panel": "TabsPanel",
      "lockedTabs": false,
      "lockedPanel": false,
      "proxy": null,
      "proxified": false,
      "noEmpty": false,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "lastActiveTab": 3
    },
    {
      "cookieStoreId": "icecat-container-1",
      "color": "...",
      "icon": "...",
      "name": 8,
      "type": "ctx",
      "dashboard": "TabsDashboard",
      "panel": "TabsPanel",
      "lockedTabs": false,
      "lockedPanel": false,
      "proxy": null,
      "proxified": false,
      "noEmpty": false,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "lastActiveTab": -1
    }
  ],
  "cssVars": {},
  "windows": [
    {
      "state": "maximized",
      "incognito": false,
      "tabsCount": 5,
      "logs": [
        "[INFO] Settings loaded",
        "[INFO] Containers loaded",
        "[INFO] Tabs loaded",
        "[INFO] Keybindings loaded",
        "[INFO] Tabs menu loaded",
        "[INFO] Bookmarks menu loaded",
        "[INFO] Styles loaded",
        "[INFO] Permissions loaded",
        "[INFO] Favicons loaded"
      ]
    }
  ],
  "tabsMenu": [
    [
      "undoRmTab",
      "mute",
      "reload",
      "bookmark"
    ],
    "moveToNewWin",
    "moveToNewPrivWin",
    "moveToAnotherWin",
    "moveToWin",
    "moveToCtr",
    "pin",
    "discard",
    "group",
    "flatten",
    "clearCookies",
    "close"
  ],
  "bookmarksMenu": [
    "openInNewWin",
    "openInNewPrivWin",
    "openInCtr",
    "createBookmark",
    "createFolder",
    "createSeparator",
    "edit",
    "delete"
  ],
  "bookmarks": {
    "bookmarksCount": 2,
    "foldersCount": 4,
    "separatorsCount": 1,
    "maxDepth": 1
  }
}`

**Comment by mbnuqw** [comment]
Thanks. I think I found the issue, so I hope I'll fix this in the next release (~tomorrow).

**Comment by TheSwingingStar** [comment]
I'm happy to hear that. 

Is there any chance that one could override the default New Tab behavior, so that it respects the current panel, instead of going to Default? The Ctrl+T shortcut is a bit too ingrained at this point, and even modifying the omni.ja isn't enough to remove, so that I can map it to Sidebery's "new tab in current container" shortcut.

**Comment by mbnuqw** [comment]
No, unfortunately this is not possible. But I plan to add option to hijack new tab and reopen it in the current panel.

**Comment by mbnuqw** [comment]
Fixed in v3.0.8.
