### ISSUE TITLE
Issue with Bookmark panel overwriting the horizontal navigation bar.

### ISSUE THREAD

**Issue by shazzap** [mbnuqw/sidebery#920]
## Steps to reproduce

Sidebery 5.30, Firefox on Windows

On the navigation bar, click the bookmark button to display the bookmark panel.

Now click the navigation's bookmark button again to jump to the bottom of the bookmarks.

The bookmark panel now expands to cover up the area where the navigation bar was.

It also adds a blank section at the very bottom of the book mark panel.

Note that this works fine if the navigation panel is set to display vertically. The problem occurs
when the navigation bar is displayed horizontally.

In order to get the navigation bar to display, you have to toggle show / hide Sidebery via Sidebery's toolbar icon.

## Expected behavior

Clicking the the bookmark icon again, that the bookmark panel should not overwrite the navigation bar.

It should not create blank area at the bottom of the bookmark panel.

It should simply jump to the bottom of the bookmarks (or back up to the top) and not interfere with the navigation bar.

**Comment by mbnuqw** [comment]
Fixed in [v5.0.0b31](https://github.com/mbnuqw/sidebery/releases/tag/v5.0.0b31)
