### ISSUE TITLE
[FR] Move panel to bookmarks

### ISSUE THREAD

**Issue by shvchk** [mbnuqw/sidebery#925]
## Description
Would be nice to have a menu entry to move all tabs in a panel to bookmarks.

Of course, user could select all tabs in a panel manually (Ctrl/Shift + click) and then bookmark selected tabs, but (1) this is not very convenient with lots of tabs and (2) this doesn't always work as expected with multiple panels: for some reason tabs from other panels can get bookmarked, too.

**Comment by mbnuqw** [comment]
Available since v5.0.0. Tab panel menu options: Save/Convert to bookmarks
