### ISSUE TITLE
The line of the pointer when moving a tab is going over the scrollbar

### ISSUE THREAD

**Issue by d3xMachina** [mbnuqw/sidebery#932]
## Steps to reproduce
- Open Firefox in [new profile](https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles)
- Install Sidebery
- Enable the "Use native scroll-bars" option of Sidebery (you can also disable the thin scrollbar to make it more visible)
- Open many tabs until there is a scrollbar
- Move a tab with the mouse between 2 tabs

![image](https://user-images.githubusercontent.com/16732772/217912250-b43b4857-eda8-41ee-86ad-5f14dee3806a.png)

## Expected behavior
The line of the pointer should not go over the scrollbar.

## Actual behavior
The line of the pointer should goes over the scrollbar.

## Possible fix
Put the html element with the "pointer" class that contains the pointer and line in the element with the "container" class ?

**Comment by mbnuqw** [comment]
Resolved in v5.0.0
