### ISSUE TITLE
Question: How are tabs in separate panels in a single Firefox window handled when SideBery is uninstalled/disabled?

### ISSUE THREAD

**Issue by davidleejy** [mbnuqw/sidebery#935]
Hello fellow SideBery users, 

Opening a discussion about concerns that users may have about how tabs in separate panels will be handled after SideBery is uninstalled, disabled, or if tabs are synced to a Firefox installation without SideBery; Firefox _likely_ does not recognize the concept of "panels", so what happens to tabs stored in separate panels?

I.e. upon SideBery uninstallation/disabling, are tabs in panels beyond the first panel: (i) discarded?; (ii) rendered in a separate Firefox window?; (iii) stacked in sequential order in the same Firefox window?; etc.

Depending on the outcome, some users might prefer using native Firefox windows to partition their stacks of tabs instead of Sidebery panels.

**Comment by mbnuqw** [comment]
On sidebery uninstalling tabs will stay in sequential order in the same Firefox window. It's planned to add more options to convert sidebery panels to windows (#884) (currently in the beta version, you can only drag and drop the panel's icon to the outside of the window to create new window with tabs of the dragged panel).
