### ISSUE TITLE
Bookmark not dragged to minimized folder

### ISSUE THREAD

**Issue by ongots** [mbnuqw/sidebery#94]
Закладка не перетаскивается в свернутую папку.
Ожидается что папка развернется автоматически, для выбора места вставки.
Особенно актуально при включенной опции 'Автоматически сворачивать папки', т.к. развернуть две папки одновременно невозможно.

Вопрос по ccs: 
.root > .nav::before {width: 0}
почему в инспекторе работает, а в редакторе стилей нет? Перепробовал все варианты.
Это разделитель главного меню в настройках.

**Comment by mbnuqw** [comment]
Для разворачивания свернутых закладок / табов при перетаскивании нужно навести курсор на треугольник указателя у свернутого элемента.
![Sidebery-1](https://user-images.githubusercontent.com/6276694/65571096-d2f94100-df7c-11e9-8cb1-011d43face56.gif)

Но это не очень интуитивно, согласен). Наверное добавлю еще разворачивание при наведении с задержкой.

---

Насчет css - есть возможность менять только для сайдбара и страницы группы табов. Для страницы настроек пока нельзя - там планируются изменения. Позже, добавлю.

**Comment by ongots** [comment]
Разворачивание папок не работает если выключить 'Древовидное отображение табов'
