### ISSUE TITLE
Tab bar on right instead of left?

### ISSUE THREAD

**Issue by TheRealBev** [mbnuqw/sidebery#944]
Title says it all.  A choice would be nice.

Also nice to get rid of the horizontal tab bar when the Sidebery tab bar is running.

**Comment by albino1** [comment]
To move it to the right just click the Firefox button that says `Move Sidebar to Right`:

![side-right](https://user-images.githubusercontent.com/12164957/219199436-96e547e4-5b05-4697-9740-e43350ebde3d.jpg)

To hide the horizontal tab bar you'll need to use userChrome.css.  See the Wiki for more info:

https://github.com/mbnuqw/sidebery/wiki/Firefox-Styles-Snippets-(via-userChrome.css)

**Comment by mbnuqw** [comment]
It's not possible from addon side. I hope all questions are resolved thanks to @albino1, closing the issue.
