### ISSUE TITLE
feature request: move to group/ drag a tab on a group to have that tab in that group

### ISSUE THREAD

**Issue by formula-spectre** [mbnuqw/sidebery#948]
Afaik there is no option to add a tab to a group if that tab was not spawned by a child of the group. this would be handy to keep things tidy

**Comment by mbnuqw** [comment]
You can drag and drop tabs into any tab to create the branch or add them to existed branch.

https://user-images.githubusercontent.com/6276694/219847905-64f25762-697f-4a53-b76c-0919d80b283f.mp4

**Comment by formula-spectre** [comment]
apparently, it was not working on me, but now it does, thank you and sorry!
