### ISSUE TITLE
Please add export snapshot option

### ISSUE THREAD

**Issue by Photo-0ps** [mbnuqw/sidebery#949]
## Description
Hey, great app, made dealing with 100's of tabs in firefox no longer an actual nightmare. The fact that it creates snapshots with regularity is a lifesaver. I use private browsing exclusively, so any crashes or necessary restarts meant losing tabs with no history to recover from. Snapshots fixed this.

However, I heavily rely on note taking apps to give context to tabs and fit them into the relevent projects. I could export the tabs wholesale, but I lose the benefit of the pre-sorting done by the sidebery panels. As such, my current workflow is to open the snapshots in sidebery settings and ctrl-A ctrl-C. From there, I have an Alfred (mac) workflow that applies some basic regex to the copied text in order to format it in a markdown-friendly way and then saves it to a directory as .md file. This file is then easily modified in apps like Obisidian or Bear etc. 

The problem is, I have to do this manual process for every snapshot and have to rely on an external application to do the processing of the clipboard item. It's a lot of steps to achieve something as simple as saving the current snapshot to a local file. I've tried finding the snapshots in the extension local storage directory but haven't had any luck reading the encrypted database.

I would really appreciate it if you could add an export snapshot button, or preferably an option to export on creation, so it creates a local file every time a snapshot is created. It would save me a lot of manual work and would be pretty much tick off all my requirements for tab management (the others already being satisfied by sidebery).

I've attached the .plist for my alfred workflow. A lot of fluff in there and I'm sure anyone with a basic understanding of scripting could vastly improve it, but I'm including it in the hopes it might help in some way. 

Thanks again for the amazing extension and the continuous refinement I see you doing in the commits.
PO

[info.txt](https://github.com/mbnuqw/sidebery/files/10777355/info.txt)

**Comment by brgr-m-r** [comment]
It would be very useful to be able to export multiple tabs selectively to clipboard or files like with Session Buddy (popular Chromium extension). At least to Markdown format. Also with separate files per session/snapshot or window.
And in general, in the Sidebery sidebar, to be able to easily copy selected tabs/tree as hyperlinked titles or markdown links. Instead of just the current limited options to copy either URLs only or Titles only separately.

**Comment by Photo-0ps** [comment]
> It would be very useful to be able to export multiple tabs selectively to clipboard or files like with Session Buddy (popular Chromium extension). At least to Markdown format. Also with separate files per session/snapshot or window. And in general, in the Sidebery sidebar, to be able to easily copy selected tabs/tree as hyperlinked titles or markdown links. Instead of just the current limited options to copy either URLs only or Titles only separately.

Have a look at the "Copy Selected Links" addon, should be able to do most of what you want. Can be configured to export links in multiple different formats. I use it to export multiple links as bullet-point [title](link) in markdown format.

**Comment by brgr-m-r** [comment]
> Have a look at the "Copy Selected Links" addon, should be able to do most of what you want. Can be configured to export links in multiple different formats. I use it to export multiple links as bullet-point [title](link) in markdown format.

Thanks. I've just tried ["Copy Selected Links"](https://addons.mozilla.org/en-US/firefox/addon/copy-selected-links/) add-on (also with its keyboard shortcut). Unfortunately, it just doesn't seem to work where needed: neither on Sidebery sidebar (for multiple selected tabs/tree), nor on Sidebery Snapshots page. So far it works only when selecting linked text within ordinary webpages.

Basically, we should be able to copy the tree of hyperlinked titles easily. From the specific selected tabs in Sidebery sidebar or snapshot viewer. Just like how it works already when copying from the Bookmark Library (but without the need to manually create/navigate/delete bookmarks all the time).

Note: what partially works on the Snapshots page already is that one can select and copy a subset of the snapshot links. But how that is pasted e.g. to Obsidian is currently rather sub-optimal: 
- default paste results in huge favicons, text and URLs pasted separately
- text-only paste also keeps the titles and URLs separate. 

It would be preferable to have hyperlinked titles instead (more readable and space-efficient).

**Comment by Photo-0ps** [comment]
> Thanks. I've just tried ["Copy Selected Links"](https://addons.mozilla.org/en-US/firefox/addon/copy-selected-links/) add-on (also with its keyboard shortcut). Unfortunately, it just doesn't seem to work where needed: neither on Sidebery sidebar (for multiple selected tabs/tree), nor on Sidebery Snapshots page. So far it works only when selecting linked text within ordinary webpages.
> 

Sorry, I'm an idiot, was looking at the wrong extension. I meant "Copy Selected Tabs to Clipboard".

**Comment by brgr-m-r** [comment]
No problem ) Thanks for the clarification.
It turns out I already had ["Copy Selected Tabs to Clipboard"](https://addons.mozilla.org/en-US/firefox/addon/copy-selected-tabs-to-clipboar/) installed. In general, it's a good extension (useful options, keyboard shortcuts). But somehow it also doesn't work on Sidebery sidebar (multiple selected tabs), nor on Sidebery Snapshots page. 
Anyway, I'll keep trying to find a solution :)

**Comment by mbnuqw** [comment]
@Bregor-Mar-Rian, you need to enable "Native context menu" and "Highlight native tabs..." options in sidebery settings. After that, you can use it with selected tabs in sidebar.

**Comment by brgr-m-r** [comment]
> @Bregor-Mar-Rian, you need to enable "Native context menu" and "Highlight native tabs..." options in sidebery settings. After that, you can use it with selected tabs in sidebar.

@mbnuqw, many thanks! Now it works with Sidebery sidebar (though not with Snapshots). If only it preserved the tab tree structure, that would be glorious!

I see "Highlight native tabs..." is the main setting for this (works with the other extension shortcuts). 
"Native context menu" seems optional - to have the right-click option. Now trying to see if there is any substantial difference between the native and Sidebery context menu. If Sidebery features are not lost with the native menu (apparently so), it seems like the way to go.

**Comment by brgr-m-r** [comment]
@mbnuqw the new snapshot import/export feature with 'Full-tree structure in Markdown' is great! Thanks!

Do you think it would be possible to make it work also per window within the snapshot? 
(UI-wise, basically, adding "Export window" button besides "Open window")

Ultimately, that would be in the direction of making it more modular and flexible. Hopefully, at some point to sync relevant tabs/bookmarks with Markdown knowledge base (with supporting JSON as necessary) such as Obsidian. That would be truly glorious...

**Comment by mbnuqw** [comment]
Available since v5.0.0

@brgr-m-r, you can create a new feature request if there isn't one already.
