### ISSUE TITLE
Middle click to unload tab

### ISSUE THREAD

**Issue by kostur86** [mbnuqw/sidebery#951]
## Description
At the moment middle click on tab has much less option then any other type of clicks.
It would be nice to have all the same options for all the click types
It would be nice to be able to assign unload to clicks

**Comment by FabianoLothor** [comment]
I would love to use it to duplicate tabs. Currently on v5 is closing.

To unload, the middle-click on the panel does the job for me.

**Comment by emvaized** [comment]
You can assign middle click on tab's close button to unload the tab

**Comment by kostur86** [comment]
> You can assign middle click on tab's close button to unload the tab

Hmmm, I do not see such option anywhere :confused: Only one i found in Settings is "Unload folded tabs". Are you talking about some CSS or config file configuration?

**Comment by albino1** [comment]
You might have to be on Sidebery v5, but the option is under `Tab Actions`:

![sidebery](https://user-images.githubusercontent.com/12164957/228037238-4eac7e1c-f765-4d8e-b5fe-90dc2ffd4e71.jpg)

**Comment by brgr-m-r** [comment]
> Currently on v5 [middle-click over any tab] is closing [the tab].

How to change or disable that??

On ThinkPad keyboards with TrackPoint, the middle-click is required to activate scrolling (with TrackPoint) and usually we don't want to close tabs when we simply need to scroll up/down the panel across multiple tabs.

**Comment by DukeVengeance** [comment]
Option *Middle click on close tab button* only customises the behaviour when you click the X button, it's always closing the tab when you middle click on the tab body.

Currently I think it's impossible to make middle click consistent for unloading: i.e.
**Middle click on anything to unload** (Tab Panels, Tabs, Close Tab Buttons...)

**Comment by mbnuqw** [comment]
Resolved in v5.0.0
