### ISSUE TITLE
[Enhancement] Set `color-scheme: light dark`.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [mbnuqw/sidebery#952]
#### Rationale

Using [`download.opensuse.org/repositories/openSUSE:/Factory/standard/x86_64/MozillaFirefox-123.0-1.1.x86_64.rpm`](https://download.opensuse.org/repositories/openSUSE:/Factory/standard/x86_64/MozillaFirefox-123.0-1.1.x86_64.rpm), [`tree_style_tab-3.8.26`](https://addons.mozilla.org/firefox/downloads/file/3975864/tree_style_tab-3.8.26.xpi) perfectly adheres to the colouration of my desktop environment (KDE Plasma 5), whereas [`sidebery-4.10.2`](https://addons.mozilla.org/firefox/downloads/file/3994928/sidebery-4.10.2.xpi) does not. The browser obviously exposes the correct colouration to extensions since the aforementioned is able to utilize it, yet Sideberry lacks even the option to adhere to it.

**Comment by mbnuqw** [comment]
Available since v5.0.0

**Comment by RokeJulianLockhart** [comment]
> https://github.com/mbnuqw/sidebery/issues/952#issuecomment-1985977583

Indeed, per [`releases/tag/v5.0.0`](https://github.com/mbnuqw/sidebery/releases/tag/v5.0.0#:~:text=proton%20theme%20and%20added%20support%20of%20firefox%20colors%20(themes)). Thanks, @mbnuqw.
