### ISSUE TITLE
Change `activateAfterClosing` will Prevent `Unload tabs`

### ISSUE THREAD

**Issue by qupig** [mbnuqw/sidebery#957]
## Steps to reproduce
- Sidebery: `Reset Settings`
- Change: `After closing current tab activate`(`activateAfterClosing`) setting

## Expected behavior
Changing this setting should not affect `Unload tabs` functionality

## Actual behavior
Change to anything other than the default ("next"), and the `Unload tabs` functionality will fail.
Restore to the default value "next tab", and the `Unload tabs` function is restored.
The last active tab in the `group` **cannot** be `Unload`.

OS: mac
Firefox: 110.0
Addon: 4.10.2

**Comment by mbnuqw** [comment]
Fixed since v5.0.0
