### ISSUE TITLE
Some trees get broken on browser restart

### ISSUE THREAD

**Issue by prizrak9** [mbnuqw/sidebery#96]
## Environment info

OS:  
Firefox:  
Addon:  

<details><code>

</code></details>

**Comment by mbnuqw** [comment]
Please, check if this problem persists in v3.1.0. If this bug still exists, please write more info:
- debug info from settings page
- steps to reproduce
Thanks.

**Comment by prizrak9** [comment]
seems alright so far

**Comment by mbnuqw** [comment]
Cool, so I'm closing this issue. If you'll get some problems with trees restoration, reopen it.
