### ISSUE TITLE
Hide pinned tabs

### ISSUE THREAD

**Issue by FabianoLothor** [mbnuqw/sidebery#965]
## Description

I didn't find this option, not sure if it's possible to implement, but would be nice to have an option where when enabled the pinned tabs would also be hidden according with their panel.

**Comment by mbnuqw** [comment]
[It's not possible to hide pinned tabs.](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/hide)
