### ISSUE TITLE
v5 - Restore from Bookmarks Enhacements

### ISSUE THREAD

**Issue by FabianoLothor** [mbnuqw/sidebery#967]
## Description

Please, add the following options to the Restore from Bookmarks feature:
- When a page is set to a certain container, list it as "unloaded" until we click them
- Don't update the title of the tab if it has one defined

Probably doing the first, you also do the second. Despite of that, currently, when you restore the pages and they are loaded the titles are changing.

That's not the expected behavior, because when we manually edit a title of a tab, they remain the same even when we refresh them or open a different URL.

So, I assume they should keep this behavior when we restore them from the bookmarks.

**Comment by mbnuqw** [comment]
> When a page is set to a certain container, list it as "unloaded" until we click them

Fixed

> Don't update the title of the tab if it has one defined

Track the #1518 issue
