### ISSUE TITLE
settings pages are invalid

### ISSUE THREAD

**Issue by FabianoLothor** [mbnuqw/sidebery#968]
## Description

Impossible to use settings pages as a valid bookmark link

![image](https://user-images.githubusercontent.com/2192995/221475977-3af25af9-955e-49c9-b4bf-8f44bb1d62e5.png)

**Comment by mbnuqw** [comment]
[It's not possible for addons to open such urls](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/create#url)
