### ISSUE TITLE
Tabs not in correct groups after browser restart

### ISSUE THREAD

**Issue by n4st3** [mbnuqw/sidebery#97]
## Description
If there are tabs in multiple groups, after browser restart they are at the bottom of parent

MainGroup
-SubGroup1
--SubGroup1.1
---Tab1.1.1
---Tab1.1.2
-SubGroup2
--SubGroup2.1
---Tab2.1.1
---Tab2.1.2

Will after restart look like this

MainGroup
-SubGroup1
-SubGroup2
--SubGroup1.1
---Tab1.1.1
---Tab1.1.2
--SubGroup2.1
---Tab2.1.1
---Tab2.1.2

## Steps to reproduce

Create the tree as i described above, restart the browser and the tabs will be shuffled

## Expected behavior

The tree should remain the same after restart of the browser

## Actual behavior

The tabs gets moved to the last parent group.

## Environment info

OS:  Winsows 8
Firefox:  69.0.2
Addon:  Sidebery

{
  "settings": {
    "version": "3.0.8",
    "nativeScrollbars": false,
    "ctxMenuNative": false,
    "autoHideCtxMenu": "none",
    "ctxMenuRenderInact": false,
    "navBarInline": true,
    "hideSettingsBtn": false,
    "hideAddBtn": false,
    "navBtnCount": true,
    "hideEmptyPanels": true,
    "navMidClickAction": "none",
    "navSwitchPanelsWheel": true,
    "groupLayout": "grid",
    "activateLastTabOnPanelSwitching": false,
    "skipEmptyPanels": false,
    "showTabRmBtn": true,
    "hideInact": false,
    "activateAfterClosing": "next",
    "activateAfterClosingPrevRule": "visible",
    "activateAfterClosingNextRule": "tree",
    "pinnedTabsPosition": "panel",
    "pinnedTabsList": true,
    "tabsTree": true,
    "groupOnOpen": true,
    "tabsTreeLimit": "none",
    "hideFoldedTabs": false,
    "autoFoldTabs": false,
    "autoExpandTabs": true,
    "rmChildTabs": "none",
    "tabsChildCount": true,
    "tabsLvlDots": true,
    "discardFolded": false,
    "discardFoldedDelay": 0,
    "discardFoldedDelayUnit": "sec",
    "bookmarksPanel": true,
    "openBookmarkNewTab": false,
    "autoCloseBookmarks": false,
    "autoRemoveOther": false,
    "highlightOpenBookmarks": false,
    "activateOpenBookmarkTab": false,
    "showBookmarkLen": false,
    "fontSize": "m",
    "bgNoise": true,
    "animations": true,
    "theme": "default",
    "style": "dark",
    "sidebarCSS": true,
    "groupCSS": false,
    "snapInterval": 5,
    "snapIntervalUnit": "min",
    "snapLimit": 100000,
    "snapLimitUnit": "kb",
    "hScrollThroughPanels": false,
    "scrollThroughTabs": "none",
    "scrollThroughVisibleTabs": false,
    "scrollThroughTabsExceptOverflow": true,
    "tabDoubleClick": "none",
    "tabLongLeftClick": "none",
    "tabLongRightClick": "duplicate",
    "tabsPanelLeftClickAction": "none",
    "tabsPanelDoubleClickAction": "tab",
    "tabsPanelRightClickAction": "none"
  },
  "permissions": {
    "allUrls": true,
    "tabHide": false,
    "actualAllUrls": true,
    "actualTabHide": false
  },
  "storage": {
    "size": "2.7 mb",
    "props": {
      "bookmarksMenu": "117 b",
      "cssVars": "1.5 kb",
      "favAutoCleanTime": "10 b",
      "favUrls": "6.1 kb",
      "favicons": "131.1 kb",
      "groupCSS": "2 b",
      "lastSnapTime": "13 b",
      "panelIndex": "1 b",
      "panels": "1.9 kb",
      "prevTabsTrees": "14.9 kb",
      "settings": "1.4 kb",
      "sidebarCSS": "101 b",
      "snapshots": "2.5 mb",
      "tabsMenu": "178 b",
      "tabsTrees": "17 kb"
    }
  },
  "panels": [
    {
      "cookieStoreId": "bookmarks",
      "icon": "...",
      "name": 9,
      "type": "bookmarks",
      "dashboard": "BookmarksDashboard",
      "panel": "BookmarksPanel",
      "lockedPanel": false,
      "bookmarks": true
    },
    {
      "cookieStoreId": "firefox-default",
      "icon": "...",
      "name": 7,
      "type": "default",
      "dashboard": "DefaultTabsDashboard",
      "panel": "TabsPanel",
      "lockedTabs": false,
      "lockedPanel": false,
      "noEmpty": false,
      "lastActiveTab": 101
    },
    {
      "cookieStoreId": "firefox-container-7",
      "color": "...",
      "icon": "...",
      "name": 12,
      "type": "ctx",
      "dashboard": "TabsDashboard",
      "panel": "TabsPanel",
      "lockedTabs": false,
      "lockedPanel": true,
      "proxy": "...",
      "proxified": false,
      "noEmpty": false,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "lastActiveTab": 136
    },
    {
      "cookieStoreId": "firefox-container-8",
      "color": "...",
      "icon": "...",
      "name": 5,
      "type": "ctx",
      "dashboard": "TabsDashboard",
      "panel": "TabsPanel",
      "lockedTabs": false,
      "lockedPanel": false,
      "proxy": null,
      "proxified": false,
      "noEmpty": false,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "lastActiveTab": 87
    },
    {
      "cookieStoreId": "firefox-container-9",
      "color": "...",
      "icon": "...",
      "name": 8,
      "type": "ctx",
      "dashboard": "TabsDashboard",
      "panel": "TabsPanel",
      "lockedTabs": false,
      "lockedPanel": false,
      "proxy": "...",
      "proxified": false,
      "noEmpty": false,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "lastActiveTab": 89
    },
    {
      "cookieStoreId": "firefox-container-10",
      "color": "...",
      "icon": "...",
      "name": 9,
      "type": "ctx",
      "dashboard": "TabsDashboard",
      "panel": "TabsPanel",
      "lockedTabs": false,
      "lockedPanel": false,
      "proxy": null,
      "proxified": false,
      "noEmpty": false,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "lastActiveTab": 79
    }
  ],
  "cssVars": {},
  "sidebarCSSLen": 91,
  "groupCSSLen": 0,
  "windows": [
    {
      "state": "maximized",
      "incognito": false,
      "tabsCount": 105,
      "logs": [
        "[INFO] Settings loaded",
        "[INFO] Containers loaded",
        "[INFO] Tabs loaded",
        "[INFO] Keybindings loaded",
        "[INFO] Tabs menu loaded",
        "[INFO] Bookmarks menu loaded",
        "[INFO] Styles loaded",
        "[INFO] Permissions loaded",
        "[INFO] Favicons loaded"
      ]
    }
  ],
  "tabsMenu": [
    [
      "undoRmTab",
      "mute",
      "reload",
      "bookmark"
    ],
    "moveToNewWin",
    "moveToNewPrivWin",
    "moveToAnotherWin",
    "moveToWin",
    "moveToCtr",
    "pin",
    "discard",
    "group",
    [
      "flatten"
    ],
    "clearCookies",
    "close"
  ],
  "bookmarksMenu": [
    [
      "openInNewWin"
    ],
    [
      "openInNewPrivWin"
    ],
    "openInCtr",
    "createBookmark",
    "createFolder",
    "createSeparator",
    "edit",
    "delete"
  ],
  "bookmarks": {
    "bookmarksCount": 11,
    "foldersCount": 6,
    "separatorsCount": 1,
    "maxDepth": 2
  }
}

**Comment by mbnuqw** [comment]
Thanks for the report. Yes, I can reproduce similar behavior in some cases, but don't know yet the exact cause of this. I'll dig into this soon.

**Comment by mbnuqw** [comment]
I've fixed possibly related to this issue bugs in v3.1.1 could you check if the problem is still there? I'm not sure, because I couldn't reproduce exactly that behavior that you describe. If an issue is not fixed with v3.1.1, could you post here the list of installed addons?

**Comment by n4st3** [comment]
yep, fixed with the 3.1.1. Thanks!
