### ISSUE TITLE
New Tab

### ISSUE THREAD

**Issue by usamartinez** [mbnuqw/sidebery#970]
## Description
Hi 
How about adding a new tab to the right click context menu or above the settings button or below the deafult button.
Somewhere that with one click one can get a new tab.
If I missed it my apologies .
So far this is the best add on I use, thank you for a great job.
Mario

**Comment by fourteen-1** [comment]
Second this. Although, there are plenty of shortcuts within the app settings to do this (Double-click, Middle Click, Ctrl+Space) and even within the browser (firefox in my case: Ctrl+T), i think it'd be neat to have a "button" on the sidebar, preferably in the RMB context menu. It's not a necessary feature but definitely a basic one that's kind of missing.

**Comment by Terkyz** [comment]
I don't know if it is related, but is it possible to make Sidebery open a new tabwhile keeping the previous session? I would like to have a new tab as a starting point to choose which window to go to.

**Comment by mbnuqw** [comment]
Available (configurable New Tab bar) in the latest version.
