### ISSUE TITLE
Inconsistent behavior when dragging a URL into the tab bar

### ISSUE THREAD

**Issue by robmonte** [mbnuqw/sidebery#973]
## Steps to reproduce
- Highlight some text that is a URL: e.g. `https://google.com`
- Drag the text into empty tab bar area and release

## Expected behavior
- The website should be opened in a new tab. (Note this is not dragging the URL onto an existing tab)

## Actual behavior
- There are 3 scenarios:
  - Sometimes it just works as expected; a new tab is opened to the URL you dragged
  - Sometimes nothing happens at all
  - Sometimes Firefox searches for the the text of the URL being dragged using the default search engine

## Debug info

<details>
<summary><b>Addon data</b></summary>
     
```json
To get addon data: 
- Go to the Sidebery settings page - section "Help"
- Click on the "Debug info" button
- Copy and paste here inside this codeblock, replacing this text.
Note: all URLs, titles and other personal info are skipped.
```
</details>

<details>
<summary><b>Logs</b></summary>

```
To get logs: 
- Open DevTools (open this url in new tab: about:devtools-toolbox?id=%7B3c078156-979c-498b-8990-85f7987dd929%7D&type=extension).
- Navigate to "console" tab.
- Click on the trash bin icon (at the top-left) to clear console.
- Then try to reproduce the issue.
- If messages appear, copy and paste them here inside this codeblock, replacing this text.
```
</details>

**Comment by mbnuqw** [comment]
Should be fixed in the latest version.
