### ISSUE TITLE
[v5] Keybindings to scroll.

### ISSUE THREAD

**Issue by zelch** [mbnuqw/sidebery#976]
## Description

With Tree Style Tabs, I've gotten very used to having key bindings for scrolling to the top or bottom of the list of tabs.

I'm not seeing any options for controlling the scrolling of tabs in sidebery, either in steps, or in the full top/bottom.

And it would be quite useful, at least for me.

**Comment by albino1** [comment]
Are these not them?

`Switch to first tab of active panel`
`Switch to the last tab of active panel`

![sidebery](https://user-images.githubusercontent.com/12164957/223038266-f1a3b64c-2764-4789-ae67-5beb93db27a7.jpg)

**Comment by zelch** [comment]
@albino1 Close, but not quite.

I want to scroll without switching.

Edit: Also, switch to the first tap of the active panel switches to the first pinned tab, not the first unpinned tab, which means that it doesn't scroll up at all.

**Comment by albino1** [comment]
FWIW, if you click on the scrollbar in the sidebar then Home/End/Page Up/Page Down will all work to navigate your scroll position.  That's one extra step than you're asking for, but thought I would mention it in case you were unaware.
