### ISSUE TITLE
Clock in FOOTER

### ISSUE THREAD

**Issue by PedisettiVenkatesh** [mbnuqw/sidebery#978]
## Description (Suggestion)
Add a Clock in the footer of the **Sidebery**. I use the browser in full screen and had to exit full screen every time I want to know the time. It would be better if there is a clock at the bottom of the **Sidebery** as there is a lot of empty space at bottom.

A **footer** can lead to many more ideas. such as tab memory, clock, timer, etc. We can also try adding other extensions buttons (which can't be seen in full screen).

**Comment by mbnuqw** [comment]
Out of scope. Workarounds:
- Clock - [Use new tab addons](https://addons.mozilla.org/en-US/firefox/search/?q=new%20tab&type=extension) or [this](https://addons.mozilla.org/en-US/firefox/addon/small-clock/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search) or [this](https://addons.mozilla.org/en-US/firefox/addon/toolbar-clock/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search) or [this](https://addons.mozilla.org/en-US/firefox/addon/mini_clock/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search), optionally use `browser.fullscreen.autohide: false` in about:config.
- Tab memory - it's impossible to get such data for addon.
- Timer - [Addons](https://addons.mozilla.org/en-US/firefox/search/?q=timer&type=extension)
- Other extensions - impossible for addon.
