### ISSUE TITLE
Conditionally show/hide Sidebery for windows that are taller than they are wide

### ISSUE THREAD

**Issue by dhorkin** [mbnuqw/sidebery#979]
## Description
I have two monitors; one is oriented vertically, the other landscape (like most people).

Sidebery is great when I'm on my normal 16:9 monitor. But when I'm on my 9:16 monitor, vertical tabs take up critical screen real estate.

There's an addon I use called [Paxmod ](https://github.com/numirias/paxmod) that allows you to have multiple tab rows at the top of your screen.

I created a request over there to add ability to conditionally switch behavior. https://github.com/numirias/paxmod/issues/108

I'm not sure whether some of this functionality would be better suited for implementation in Sidebery as opposed to Paxmod, so I'm creating a semi-duplicate issue here of the one there.

For convenience, here's a simplified version of my desired behavior that doesn't explain Sidebery behavior:

## When I'm on my Portrait monitor:
- automatically close `Sidebery` if open (but leave other sidebars open)
- normal Paxmod behavior (titlebar disabled, multiple tab rows)
- integrate Sidebery panels into Paxmod so that I can access Sidebery panels even when Sidebery's sidebar is closed (not sure whether or not Sidebery exposes an API for the panels. I imagine the visual side of this would need to be on Paxmod side)

## When I'm on my Landscape monitor:
- I would like to automatically open `Sidebery` sidebar
- replace Paxmod's tab rows with a combination of the default Firefox titlebar (i.e. your window title plus minimize/maximize/close buttons) and "tabs" that are actually Sideberry "panels" (basically, show what Sidebery shows at the top of their sidebar as the tabs at the top of the screen)

## Current behavior / Example of why I want this:
![image](https://user-images.githubusercontent.com/59899746/223307927-2f424f1b-c263-4c56-91e7-12ad7b012a32.png)

**Comment by mbnuqw** [comment]
Impossible to do from Sidebery side. You can use #214 (Sidebery settings > General > Add preface...) with userChrome.css as a workaround (to show/hide native tabs when Sidebery sidebar is off/on), but Firefox still requires explicit user action (click) to open/close sidebar.
