### ISSUE TITLE
Wrong place for new children tabs after closing some old children tabs

### ISSUE THREAD

**Issue by crewdk** [mbnuqw/sidebery#98]
## Description
Wrong place for children tabs

## Steps to reproduce
For example we have page with 10 links on it. Open links 1-5, so we have 1 root tab and 5 children tabs. Close any children tab, start open any links from root tab.

## Expected behavior
For example I closed tab #5, then open new links from root tabs

1. Root tab
  1.1 Tab 1
  1.2 Tab 2
  1.3 Tab 3
  1.4 Tab 4
  1.6 Tab 6
  1.7 Tab 7

## Actual behavior

1. Root tab
  1.1 Tab 6
  1.2 Tab 7
  1.3 Tab 1
  1.4 Tab 2
  1.5 Tab 3
  1.6 Tab 4

## Environment info
OS: win 
Firefox version:   69.0.3
Addon version:  3.1.0

<details><code>
{
  "settings": {
    "version": "3.1.0",
    "nativeScrollbars": false,
    "ctxMenuNative": false,
    "autoHideCtxMenu": "none",
    "ctxMenuRenderInact": true,
    "navBarInline": true,
    "hideSettingsBtn": false,
    "navBtnCount": true,
    "hideEmptyPanels": true,
    "navMidClickAction": "none",
    "navSwitchPanelsWheel": true,
    "groupLayout": "grid",
    "activateOnMouseUp": false,
    "activateLastTabOnPanelSwitching": true,
    "skipEmptyPanels": false,
    "showTabRmBtn": false,
    "hideInact": false,
    "activateAfterClosing": "next",
    "activateAfterClosingPrevRule": "visible",
    "activateAfterClosingNextRule": "tree",
    "pinnedTabsPosition": "left",
    "pinnedTabsList": false,
    "tabsTree": true,
    "groupOnOpen": true,
    "tabsTreeLimit": "none",
    "hideFoldedTabs": false,
    "autoFoldTabs": false,
    "autoExpandTabs": false,
    "rmChildTabs": "none",
    "tabsChildCount": true,
    "tabsLvlDots": true,
    "discardFolded": true,
    "discardFoldedDelay": 15,
    "discardFoldedDelayUnit": "min",
    "bookmarksPanel": false,
    "openBookmarkNewTab": false,
    "autoCloseBookmarks": false,
    "autoRemoveOther": false,
    "highlightOpenBookmarks": false,
    "activateOpenBookmarkTab": false,
    "showBookmarkLen": false,
    "fontSize": "m",
    "bgNoise": false,
    "animations": true,
    "theme": "tactile",
    "style": "dark",
    "sidebarCSS": true,
    "groupCSS": false,
    "snapInterval": 15,
    "snapIntervalUnit": "min",
    "snapLimit": 20,
    "snapLimitUnit": "snap",
    "hScrollThroughPanels": false,
    "scrollThroughTabs": "none",
    "scrollThroughVisibleTabs": false,
    "scrollThroughTabsExceptOverflow": true,
    "tabDoubleClick": "none",
    "tabLongLeftClick": "none",
    "tabLongRightClick": "none",
    "tabsPanelLeftClickAction": "none",
    "tabsPanelDoubleClickAction": "tab",
    "tabsPanelRightClickAction": "none"
  },
  "permissions": {
    "allUrls": true,
    "tabHide": true,
    "actualAllUrls": true,
    "actualTabHide": true
  },
  "storage": {
    "size": "1.2 mb",
    "props": {
      "expandedBookmarks": "2 b",
      "favAutoCleanTime": "10 b",
      "favUrls": "26.2 kb",
      "favicons": "862.1 kb",
      "lastSnapTime": "13 b",
      "panelIndex": "1 b",
      "panels": "1 kb",
      "prevTabsTrees": "16 kb",
      "settings": "1.4 kb",
      "sidebarCSS": "77 b",
      "snapshots": "398.5 kb",
      "tabsTrees": "18.7 kb"
    }
  },
  "panels": [
    {
      "icon": "...",
      "name": 8,
      "type": "bookmarks",
      "panel": "BookmarksPanel",
      "lockedPanel": false,
      "bookmarks": true
    },
    {
      "cookieStoreId": "firefox-private",
      "icon": "...",
      "name": 14,
      "type": "private",
      "panel": "TabsPanel",
      "private": true
    },
    {
      "cookieStoreId": "firefox-default",
      "icon": "...",
      "name": 4,
      "type": "default",
      "panel": "TabsPanel",
      "lockedTabs": false,
      "lockedPanel": true,
      "noEmpty": true
    },
    {
      "cookieStoreId": "firefox-container-2",
      "color": "...",
      "icon": "...",
      "name": 6,
      "type": "ctx",
      "panel": "TabsPanel",
      "lockedTabs": false,
      "lockedPanel": false,
      "proxy": null,
      "proxified": false,
      "noEmpty": false,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": ""
    },
    {
      "cookieStoreId": "firefox-container-6",
      "color": "...",
      "icon": "...",
      "name": 3,
      "type": "ctx",
      "panel": "TabsPanel",
      "lockedTabs": false,
      "lockedPanel": false,
      "proxy": null,
      "proxified": false,
      "noEmpty": false,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": ""
    }
  ],
  "cssVars": "TypeError: can't convert undefined to object",
  "sidebarCSSLen": 67,
  "windows": [
    {
      "state": "maximized",
      "incognito": false,
      "tabsCount": 145,
      "logs": [
        "[INFO] Settings loaded",
        "[INFO] Containers loaded",
        "[INFO] Tabs loaded",
        "[INFO] Keybindings loaded",
        "[INFO] Styles loaded",
        "[INFO] Favicons loaded",
        "[INFO] Permissions loaded"
      ]
    }
  ],
  "bookmarks": {
    "bookmarksCount": 913,
    "foldersCount": 79,
    "separatorsCount": 85,
    "maxDepth": 4
  }
}</code></details>

**Comment by mbnuqw** [comment]
Yes, this is the default behavior of Firefox. In v3.2.0 I'll add ability to control position of created tab.

**Comment by mbnuqw** [comment]
Fixed in the latest version. Now you can set position of new child tab in settings.
