### ISSUE TITLE
Advice of incompatibility with other add-ons

### ISSUE THREAD

**Issue by alan-palacios** [mbnuqw/sidebery#980]
## Description
I recently switched from TreeStyleTab to Sidebery but since the start I was having issues where every new tab was being moved automatically to the last panel. After I reset settings and check it in a fresh Firefox setup I found out that TreeStyleTab add-on was causing the problems because I didn't disable it at first. 
I think maybe it's worth it to put and advice in some place like the README about this kind of errors if you don't disable other tab add-ons.
Even though I found a mention of it in https://github.com/mbnuqw/sidebery/issues/147#issuecomment-599105875 after I solved, it was difficult for me to notice the cause of the error.

**Comment by mbnuqw** [comment]
Fixed in a5381057a33b085351c856519fe0f4b82cc1ec9e
