### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Jeffdefff07** [mbnuqw/sidebery#983]
## Description

It would be nice to have an option to 'minimize' the side panel. Below is a screenshot of the basic idea. 

Also, this add-on is amazing! It does almost everything I want to minimize how much room the non-website area takes up and being able to shrink it would be the final piece. It makes me cringe a little to mention this, but Microsoft Edge has a side tab panel feature that has the ability to minimize. That could provide a real world example of my request. 

Thanks for the consideration! Have a great rest of your day!

![SideberryMockup](https://user-images.githubusercontent.com/112791064/224063971-5517bd48-dce8-4dc7-a91c-c1d1b091af40.png)

**Comment by emvaized** [comment]
You should search [r/FirefoxCSS](https://www.reddit.com/r/FirefoxCSS) for setups like that, Sidebery itself could not modify browser UI due to security limitations

**Comment by mbnuqw** [comment]
It's not possible from addon side. Use [userChrome.css.](https://www.reddit.com/r/FirefoxCSS/search?q=auto+hide+sidebar&restrict_sr=on)
