### ISSUE TITLE
[Req] User agent in container

### ISSUE THREAD

**Issue by Iquaridys** [mbnuqw/sidebery#99]
if this can be applied I would be very cool add-ons,
- add custom user agents in the container (if a proxy is possible, then user agents can)
- add custom / produce fingerprints like canvas in the container (I think it's hard, but this is good)

**Comment by ImCowboySibs** [comment]
Hi, I used the feature as well, it works for User Agent header spoofing, but it does not spoof the JS User agent settings which causes issues with some sites. 

Support needs to be added for the following User Agent detection methods if possible:

1. navigator.userAgent (onload)
2. iframe navigator.userAgent
3.iframe navigator.appVersion

**Comment by mbnuqw** [comment]
@ImCowboySibs , you're right, I can add sub-option to inject script that will spoof the navigator.userAgent of the page (and its iframes) to specified one.

**Comment by mbnuqw** [comment]
Closing this issue, for spoofing JS UserAgent track #145.
