### ISSUE TITLE
How to change font colour on tabs ?

### ISSUE THREAD

**Issue by onguarde** [mbnuqw/sidebery#998]
Under Tabs section of the styles editor, I managed to change the active tab font colour. By changing the "activated foreground". 

![image](https://user-images.githubusercontent.com/681355/227172282-bcdb48e1-de0c-4495-a6a6-5e696c8f7fe9.png)

Is there a similar setting to change the font colour on inactive tabs? I can't find any in the tabs section.

**Comment by onguarde** [comment]
Found it, this changes the inactive tabs' font colour. 

![image](https://user-images.githubusercontent.com/681355/227172515-4c6532ae-7345-4922-aeef-a98acf9a1041.png)

This was placed in the "General" section instead of the "Tabs" section. Perhaps it should be moved?

**Comment by craftgear** [comment]
Thanks @onguarde ! 
I was looking for this too.

I'd like to have a way to change font color on inactive tabs only but still better than nothing.

**Comment by mbnuqw** [comment]
Resolved in v5.0.0
